### ISSUE TITLE
Pagination maxPages bug

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#100]
If you set the `maxPages` parameter of the pagination widget to 5, you start getting negative pages when you click on 5

**Comment by pixelastic** [comment]
What do you mean by "padding of the pagination"?

**Comment by Jerskouille** [comment]
The padding being the max number of pages to the right and the left of the current one.

**Comment by pixelastic** [comment]
Ah ok, I see that this option may actually be more useful than the `maxPages` (because we could guess the max pages by reading the helper configuration)

**Comment by vvo** [comment]
Padding is cool, maxpages is to limit the number of pages even if there are more results

**Comment by vvo** [comment]
Actually padding is already available as an option @Jerskouille: https://github.com/algolia/instantsearch.js#pagination

**Comment by vvo** [comment]
You can safely rely on the readme for all things documentation on widgets, we keep it updated.

**Comment by Jerskouille** [comment]
Oh you're right, I relied on the `example/app.js` more than on the README, my bad.
