### ISSUE TITLE
Include geo filtering in currentRefinedValues

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#1002]
I think it would make sense that the currentRefinedValues widget shows when a geo feature is used, either area filtering or search around a point.

I'm not sure how this should be done though, as displaying lat/lng coordinates does not make sense.
A quick hack is to provide a function for the template option and have an external source for the label to display depending on the coordinates/area filtering that is used.

Something like this:

```js
instantsearch.widgets.currentRefinedValues({
                        container: '#active-filters',
                        clearAll: false,
                        attributes: [
                            {
                                name: '_geoloc',
                                label: 'Location',
                                template: function(a) {
                                    return SomeObject.currentLocation;
                                }
                            }
                        ]
                       })
```

Thoughts?

**Comment by vvo** [comment]
> I'm not sure how this should be done though, as displaying lat/lng coordinates does not make sense.

Yes, if the go-to solution is always to use a specific template then your workaround (is it working?) seems good.

**Comment by olance** [comment]
Right now the widget doesn't recognize `_geoloc` as a special value to display geo search information, so that would be the minimum needed change.

To work around this there's the possibility to declare a fake facet attribute in the settings and change its value. That works well, and then the template idea works well, but it's very hacky :)

**Comment by vvo** [comment]
Ok so the issue here is that the currentRefinedValues is not reading generic searchParameters, only refinements: https://github.com/algolia/instantsearch.js/blame/e81c320a0f025332c9fdbb4bb0177eada54216cd/src/lib/utils.js#L159

geoloc is only a searchParameter, what we could do is that if we find a match for the name of the attribute inside the searchParameters then we accept it. So that you do not have to declare a fake facet.

**Comment by olance** [comment]
That sounds like a good compromise @vvo  :)

**Comment by vvo** [comment]
Moved to #1087
