### ISSUE TITLE
Allow blacklisting attributes for currentRefinedValues

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#1003]
There's currently an option (`onlyListedAttributes`) for whitelisting attributes to display on the currentRefinedValues widget.

Would it be possible to add another one for blacklisting attributes? Something like `withoutListedAttributes`.
Otherwise it's a bit painful to list every possible attributes but the one(s) to be blacklisted.

**Comment by vvo** [comment]
I don't understand the "onlyListedAttributes" behavior from reading the documentation, when is it used?

I thought that as soon as you provided a list of attributes inside `attributes.*`, those were the only one displayed.

If I get it right, you want to pass a list of attributes to then be used as a blacklist to not show them?

**Comment by olance** [comment]
I guess it's not mandatory to use `attributes.*` for each facet attribute you want to show on the list.

So you got it right, the idea would be to be able to make sure specific attributes do not show in the list.

**Comment by Shipow** [comment]
If you don't put onlyListedAttributes you will display every attributes, in that case '''attributes''' is used for templating.

Olance proposition make sens for me too. It was painful to add every attributes, I searched for this negative method.

**Comment by vvo** [comment]
We need a second pass over the currentRefinedValues, the current usage is not straightforward. It does a good job but I am sure we could find an easier API while allowing more use cases.

I will open a new issue to discuss that.

**Comment by olance** [comment]
Hey, running into this problem again with a client.... any update on the subject? A possible quick fix?

**Comment by vvo** [comment]
Unfortunately no, no news in this

**Comment by olance** [comment]
OK, had you created an issue like you had mentioned in your last comment?

'cause the docs also need to be improved, I couldn't even find out how to properly use `attributes[].template` myself...

**Comment by vvo** [comment]
PR welcomed!

**Comment by olance** [comment]
Of course!
But do you have this issue or not? :P

**Comment by vvo** [comment]
Yes https://github.com/algolia/instantsearch.js/issues/1064
