### ISSUE TITLE
priceRanges: inputs are not filled when clicking on a range

### ISSUE THREAD

**Issue by xPaw** [algolia/instantsearch.js#1009]
https://community.algolia.com/instantsearch.js/documentation/#priceranges

If you click "$2 - 80", it would be nice if inputs got filled in with "2" and "80".

**Comment by vvo** [comment]
Hi @xPaw indeed that would be nice, do you think you could submit a PR?

**Comment by xPaw** [comment]
> do you think you could submit a PR?

Sadly not.

**Comment by bobylito** [comment]
I think that the issue is more general. Those inputs should be connected to the state, in the same fashion that the search box is, so that any other widget filtering changing the values of the refinement should have an impact here.
