### ISSUE TITLE
searchBox widget error in IE9

### ISSUE THREAD

**Issue by terranboy** [algolia/instantsearch.js#1012]
When I added searchBox widget, the IE9 debugging show:

SCRIPT5007: Unable to get value of the property 'add': object is null or undefined 

but other widgets work fine.
 my code:
`search.addWidget(
        instantsearch.widgets.searchBox({
          container: '#search-input',
          placeholder: 'Search ...'
        })
 );`
If I remove this widget, it works fine.

**Comment by vvo** [comment]
Hi, are you using the polyfill we mention here: https://github.com/algolia/instantsearch.js#browser-support?

**Comment by terranboy** [comment]
Yes , have include polyfill

**Comment by vvo** [comment]
Can you create a small jsfiddle reproducing the issue?

**Comment by terranboy** [comment]
Sorry, the polyfill.js I just used is not right, now it works fine.
Thank you

**Comment by vvo** [comment]
Great!

**Comment by jAmstr** [comment]
Hi,
Does Instant search still support IE9 ? the link doesn't seem to take me anywhere: https://github.com/algolia/instantsearch.js#browser-support

I need to support IE9 and above for a project and be able to use instantsearch.js

**Comment by Haroenv** [comment]
We technically support IE10+ (https://github.com/algolia/instantsearch.js#support), but with poly fills for some things you should be able to get it properly working. You should open a new issue for problems you encounter
