### ISSUE TITLE
Add active refinements info for the menu, hierarchicalMenu and the refinementList widgets 

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#1013]
Would be great to add more info in the markup about the active. That would help to build UI/UX where the list of those possible filter items are hidden.

We could for instance imagine to have:
- add a class at the top level that there is 1 or more items selected
- add a count value in the `ais-menu--header` to indicate how many items have been selected (+ extra attribute, to get that value easily accessible programmatically)

![pasted image at 2016_05_05 23_26](https://cloud.githubusercontent.com/assets/1101220/15152209/af404e30-16d4-11e6-9265-88bf6dae3a4a.png)

```html
<div data-reactroot="" class="ais-root ais-menu">
  <div class="ais-menu--header ais-header ais-menu__active" data-active-items="1">
    Cuisine <span class="ais-header-active--count">1</span>
  </div>
  <div class="ais-body ais-menu--body">
     ...
```

What do you guys think?

**Comment by bobylito** [comment]
Like that!

**Comment by pixelastic** [comment]
I love the idea, but wondering about retro-compatibility. Adding the count in the default template of the header might break a lot of designs. And it makes much more sense for UI where the list is hidden, not so much when it is displayed.

- Adding a data-attribute should be trivial
- Adding an `__active` class on the header if a filter is selected should be doable as well
- Instead of changing the default template, I would simply pass the count to the template, and let users use this information or not in their design.

WDYT?

**Comment by vvo** [comment]
> Adding an __active class on the header if a filter is selected should be doable as well
> Instead of changing the default template, I would simply pass the count to the template, and let users use this information or not in their design.

:+1: 

> Adding a data-attribute should be trivial

What is the goal of having `data-active-items="1"` in your current demo @seafoox?

**Comment by pixelastic** [comment]
If you have the correct attribute on an element, you can easily add the count through CSS with

```css
:after {
  content: attr('data-active-items');
}
```

**Comment by vvo** [comment]
> If you have the correct attribute on an element, you can easily add the count through CSS with

I understand but at the same time this would be the first time we include data this way, I would first just pass the data in the template and build the same without the need to have another data attribute.

Every css class or data attribute we add raise the surface of the API (and raise the complexity).

**Comment by pixelastic** [comment]
You're right. @seafoox did you had any other need for the attribute that could not be fixed by a specific CSS class?

**Comment by seafoox** [comment]
I could eventually be interesting to have the list of active refinements at the root level. But I don't have any use case yet. So for now, I'd say no, I don't see any other need for the attribute that could not be fixed by a specific CSS class.
