### ISSUE TITLE
add rtl support for rangeSlider

### ISSUE THREAD

**Issue by R4ph-t** [algolia/instantsearch.js#1016]

**Comment by bobylito** [comment]
Hi @R4ph-t 

Thanks for submitting this issue. I'm not very familiar with the use of the dir html attribute. Could you provide us a sample? What will be the impact on the other widgets? Should we do something for them too?

**Comment by vvo** [comment]
We need more details on this issue (description?)

**Comment by vvo** [comment]
I think I got it, we could just pass and expose the direction option of nouislider in instantsearch.js: https://refreshless.com/nouislider/slider-options/#section-direction

That's easy to add

**Comment by vvo** [comment]
moved to #1069
