### ISSUE TITLE
Fallback on hierarchicalFacet

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#1017]
If you don't declare your facet correctly in a widget config, it ends up using the hierarchical facet in place of giving a precise error.

example of wrong syntax -> 'facet' : ['lang'] in place of ['facet']:['lang']

Don't know if you can do something with that. But it would definitely have helped me to get some help here.

**Comment by pixelastic** [comment]
Ah yes, could make sense.

Could you post your complete instanciating code, with the "wrong" settings?

**Comment by Shipow** [comment]
no I didn't keep it, but basically this  'facet' : ['lang'] in the getConfiguration should trigger the behaviour.

**Comment by vvo** [comment]
I did not get the whole issue. Particulary this:

> it ends up using the hierarchical facet in place of giving a precise error.

**Comment by pixelastic** [comment]
I understood the issue the first time I read it, but now I don't understand it anymore :/

@Shipow could you tell us which widget you were using, what option you passed and what was the expected behavior?

**Comment by vvo** [comment]
There's no difference in JS between:

```js
var obj = {
  ['facet']: ['lang'] // computed property name resolving to 'facet'
}
```

[Computed properties](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names)

and

```js
var obj = {
  'facet': ['lang'] // computed property name resolving to 'facet'
}
```

or

```js
var obj = {
  facet: ['lang'] // computed property name resolving to 'facet'
}
```

They all resolve to the same object structure.

The original issue and description is not what we are looking for, open a new issue if you remember the exact problem.
