### ISSUE TITLE
[Documentation] Layout is broken on Cr, FF and Safari (probably others too)

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1020]
In the documentation, we currently have a big white bar appearing.

https://www.dropbox.com/s/0sxyu85eicokgei/Screenshot%202016-05-17%2010.26.51.png?dl=0

**Comment by Shipow** [comment]
fixed with https://github.com/algolia/instantsearch.js/commit/4759a0e13df1a6db5680abeb6f7d24f9f4740211
