### ISSUE TITLE
Release script failing on Travis

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#1021]
I tried to release the 1.5.1 version using the `npm run release` but the [Travis build on master](https://travis-ci.org/algolia/instantsearch.js/builds/130811740) kept failing.

Here is the error:

```
npm prune
npm run shrinkwrap --dev
> instantsearch.js@1.5.1 shrinkwrap /home/travis/build/algolia/instantsearch.js
> npm-shrinkwrap --dev
Problems were encountered
Please correct and try again.
invalid: babel-runtime@6.6.1 /home/travis/build/algolia/instantsearch.js/node_modules/babel-runtime
something went wrong. Did not write npm-shrinkwrap.json
```

I restarted the build and it failed again. I tried to replicate on my machine using the same node and npm version and the `shrinkwrap` worked perfectly. I even globally installed `npm@2` to be sure to have the same one.

So in the end the tag was already created and picked by the jsdelivr bot, so I simply updated the website. Still, don't know what happened here, so your insight will be valuable @vvo.

**Comment by vvo** [comment]
I dunno also, what I do in those cases is delete the travis cache for the repository (on the travis settings). I think it has to do with babel-runtime being installed while not expected. I will regenerate the shrinkwrap and pray

**Comment by pixelastic** [comment]
Ok, thanks, I did not know we could do that.

Also, not related but I don't think I'm an admin on this project. I cannot see the ENV variables in Travis.

**Comment by vvo** [comment]
Seems like you are an admin on this project, core team is admin, you are in core team
