### ISSUE TITLE
[hitsWidget]: Provide an `onClick` handler on the hits

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#1023]
We sometimes need to trigger a specific behavior when people are clicking the hits results displayed. Something like opening more details in a lightbox, or in a side panel. And we usually need context about the specific hit that was clicked. There is currently no built-in way to do that.

For example, on the [Marvel demo](https://pixelastic.github.io/marvel/) I open the side panel when you click on a result hit. I managed to do that by listening to the click event on the hits wrapper (and filtering only on event targeting the hits themselves) through and external jQuery binding (`$('.hits').on('click', '.hit', (event) => {})`). I also put the hits details in a JSON encoded form in an hidden `textarea` to get it.

This is hacky and maybe we could directly embed this into the widget. I suggest something like:

```javascript
search.addWidget(
  instantsearch.widgets.hits({
    container: '#hits-container',
    onClick: (event, data) => {
      // event is the usual event, while data is the data passed to the template
    }
  })
);
```

**Comment by vvo** [comment]
This is a tricky one, we can do it but we need to remember people will then want to add any dom handler to it this way.

If we were in a pure JS world we could do something like:

```
search.addWidget(
  instantsearch.widgets.hits({
    container: '#hits-container',
    onDomNodeAdded: (domNode, hitData) => {
      // do anything you want
    }
  })
);
```

What do you think? (without thinking about current restrictions we have because of our implementation)

**Comment by pixelastic** [comment]
I like the idea, it gives a lot of flexibility but... is more for advanced users that want full control. I'd rather try to focus on the usual use-cases for most of our users first.

If we follow your suggestion, users will have to define a method (`onDomNodeAdded`) to add their own method to the DOM element. They might have to workaround `this` binding, event delegation, etc. I'd rather we keep this complexity internally.

We could also add an `onDomNodeAdded` later on, but for now I'd rather focus on the common use-case.

WDYT?

**Comment by vvo** [comment]
I am against adding onClick (only) because even if it solves the "click" use case, it will easily get out of control:
- I want to listen for double click
- I want to listen for drag event
- I want to listen for mouseenter mouseleave
- I want to read some data attributes I just set in my template
- ..

I do not see onDomNodeAdded as something over engineered while we can see onClick as being too narrow on the API it exposes.

The current usecase you faced might be seen at the "only usecase" but I fear they are more to take into account.

We need to think more and more in term of pluggable API endpoints giving power to everyone. Answering beginners question like "How to add a click to every hit element" belongs to a guide and not a dedicated API entry point.

onDomNodeAdded is actually already doable by using React refs (those can be callbacks) https://facebook.github.io/react/docs/more-about-refs.html

**Comment by pixelastic** [comment]
Makes sense, I didn't think of all those use-cases.

Not sure on the naming `onDomNodeAdded`, this feels really low level. Why not `onRender` to stay consistent with our naming of events? It could still pass the DOM node and data to the function, just maybe not add a mention of "adding a DOM node to the DOM tree" in the naming.

**Comment by vvo** [comment]
Yes we can iterate on the API option name now that we agree on the API feature

**Comment by pixelastic** [comment]
So what do you think of `onRender(data, node)` ?

**Comment by vvo** [comment]
onRender I would expect it to represent a render event each time the hit widget is rendered. Using "dom node" I wanted to emphasis on the item being added but that's not good. And we need to take into account the "allItems" template

**Comment by pixelastic** [comment]
The more I think about it, the more I think my approach of listening to the `click` event on the parent and filtering on the actual target was the right one. Binding specific event `onRender` won't be as effective, and the whole concept of a DOM node with our React implementation makes real sense.

The question is how can I know the internal data of the element that is clicked. My hacky `textarea` solution works, or I could have kept a hashtable of hits ids <=> data in memory and use it on click. Not sure any of that actually needs to be inside the widget...

**Comment by bobylito** [comment]
Sorry late for the party, but what about event delegation and data-* attributes? (it would work great in the case you describe @pixelastic

**Comment by Shipow** [comment]
I use data attributes with searchstone, I end up with 12 data attributes in the tag, that's not really convenient. I like the idea to pass the hit somehow.

**Comment by bobylito** [comment]
JSON.stringify in a single data attribute?

**Comment by vvo** [comment]
From the discussions I see here, I see advanced developers (= knowing how to do DOM with either jQuery or JavaScript), willing to control the full markup generated by IS (events, html).

What if if we said and provided you something like "Here's a render method, please do some DOM and send it back to us", you would be able to achieve what you want without the need to add custom API entries and without the need for the advanced users to learn those API entries, and their possible restrictions.

**Comment by pixelastic** [comment]
> Here's a render method, please do some DOM and send it back to us

You mean, like the `template` method? ;)

Maybe we can allow the `template` method to return a DOM element instead of a string. That way we can bind any event with any data to hit easily. That would be really straightforward.

Not sure about memory leaks and garbage collecting of that, but otherwise this feels like the easiest API.

**Comment by vvo** [comment]
> Maybe we can allow the template method to return a DOM element instead of a string. That way we can bind any event with any data to hit easily. That would be really straightforward.

YES! This is the ultimate "low level" non-leaky API that we could provide. We need to discuss this along with what are the real templating option we provide by default, will try to have a proposal soon.

**Comment by vvo** [comment]
Revisiting this, given our renderers proposal, we might finally implement this in the default hits renderer since this is a common pattern in recent demos. And you don't want to render the hits yourself for such a simple usecase.

Moved to #1078
