### ISSUE TITLE
[Documentation] hierarchicalMenu `cssClasses.depth` option seems wrong

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#1025]
<img width="576" alt="capture d ecran 2016-05-22 a 22 43 02" src="https://cloud.githubusercontent.com/assets/314079/15461303/c160f346-206e-11e6-9548-0607b2812a8d.png">

Probably a bad copy/paste. There's no "depth" element, but a class to differentiate the different depths of items in the hierarchy, right?

Proposition:
> CSS class to add to each item element to denote its depth. The actual level will be appended to the given class name (ie. if `"depth"` is given, the widget will add `"depth0"`, `"depth1"`, ... according to the level of each item).

**Comment by pixelastic** [comment]
Nice catch. I'll submit a PR.

**Comment by olance** [comment]
Thanks @pixelastic :)
