### ISSUE TITLE
Add thousand separator to value in hits template

### ISSUE THREAD

**Issue by JonnyTurnerUK** [algolia/instantsearch.js#1033]
Hey all, I'm trying to figure out a way to add a thousand separator comma into a 'price' in the hits template but it's now driving me crazy! I've been trying / looking into many ways over the last few hours and learning Mustache but can't figure out the best approach.

Any help would be hugely grateful.

**Comment by vvo** [comment]
Hi @JonnyTurnerUK I am sorry you wasted that much time. First, did you had a look at our documentation about hogan helpers? https://community.algolia.com/instantsearch.js/documentation/#helpers

**Comment by than** [comment]
Here's how I was able to whip this together pretty quickly, grabbing a comma script from SO. (I'm using `addCommas` elsewhere.)

```
${{#helpers.addCommas}}{{price}}{{/helpers.addCommas}}
```

```
search.templatesConfig.helpers.addCommas = function(/*text, render*/) {
   return this.price.toString().addCommas();
};

String.prototype.addCommas = function() {
  nStr = this;
  nStr += '';
  x = nStr.split('.');
  x1 = x[0];
  x2 = x.length > 1 ? '.' + x[1] : '';
  var rgx = /(\d+)(\d{3})/;
  while (rgx.test(x1)) {
          x1 = x1.replace(rgx, '$1' + ',' + '$2');
  }
  return x1 + x2;
}
```

**Comment by vvo** [comment]
Awesome!

**Comment by JonnyTurnerUK** [comment]
That's awesome!! I've read through the docs but think I got distracted with transformData and got totally confused. Been practicing with the hogan helpers so many thanks fo help! Chuffed!
