### ISSUE TITLE
Expose filters in rangeSlider

### ISSUE THREAD

**Issue by than** [algolia/instantsearch.js#1035]
First of all, instant search is AWESOME.

My current use case is pretty typical, I have a real estate search. There are a small number of properties currently with a list price of > $1,000,000. The bulk of properties for sale are in the $75,000 - $250,000 range. 

However, the default uniform range of the slider means that a huge chunk of the slider is wasted on a large range from 250K to 4.5M. 

Exposing this option would be very useful. https://refreshless.com/nouislider/pips/#section-steps

**Comment by vvo** [comment]
> First of all, instant search is AWESOME.

Hi, thanks!

I believe your need is to have a non-linear slider like this: https://refreshless.com/nouislider/slider-values/#section-non-linear

Do you also want to show the pips (small bars at bottom)?

**Comment by than** [comment]
Yep! That's basically it.

I wonder if there was a way for it to update the range based on the actual available price values. i.e. Since the slider is able to update the `min` and `max` values on the fly, it'd be great to have the slider be able to dynamically update the first quartile, median, and third quartile along with min/max.

**Comment by vvo** [comment]
@than Did you try using ranges: [..] like documented here: http://refreshless.com/nouislider/slider-values/#section-non-linear

If this does not work, then we will update our slider.

As for programmatically updating values, we will provide that in #1069

**Comment by than** [comment]
@vvo `ranges` does not work as currently set up. On my quick glance, it looks like the range will always be set to the `min` and `max` values of the result set returned from algolia.

**Comment by vvo** [comment]
Ok then I will do a quick feature to allow passing ranges

**Comment by bobylito** [comment]
This kind of use case can be solved with connectors where the output is delegated to a user function. Let's close this one for now. If the need still exists, please reopen a new issue. Thanks.
