### ISSUE TITLE
instantsearch.js V1 project feedback

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1038]
Hello to every instantsearch.js user. instantsearch.js V1 is out since some time now and we need to plan a V2.

Since the release of V1, we gathered a lot of feedback, issues and features requests about the project.

We have a lot of ideas for V2 but we would like to hear feedback from everyone interested.

If you are interested in giving that feedback, we have a dedicated google document.

If you want to participate in the future of instantsearch.js then send me an email (vincent@algolia.com) or add a comment here with your email address and I will send you back the url of the google doc.

I won't share the link publicly right now to avoid things like people deleting the whole content.

Still, has we do everything open source, the whole content of the document will be shared once we reach a good roadmap.

**Comment by andymac4182** [comment]
andrew.mcclenaghan@gmail.com We have just released our integration. Loving instantsearch but have a few ideas for possible features.
