### ISSUE TITLE
I can't hide the pagination when there is only one result page.

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#1039]
![image](https://cloud.githubusercontent.com/assets/976175/15608895/f9a150c8-241c-11e6-9511-b84a3a91892b.png)

**Comment by pixelastic** [comment]
One way to solve this would be to add a CSS class on the wrapper denoting how many pages in the pagination we have.

Something like `ais-pagination__pagecount-1`, `ais-pagination__pagecount-2`, etc.

**Comment by pixelastic** [comment]
I've had a go at a PR https://github.com/algolia/instantsearch.js/pull/1049, but I'm wondering if we should use the number of max pages, or the number of displayed pages.

(Please answer in the PR)

**Comment by vvo** [comment]
This was solved using a simple custom widget https://github.com/algolia/instantsearch.js/pull/1049#issuecomment-222927757
