### ISSUE TITLE
The collapsible options on a refinement list breaks the refresh of the widget

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#1041]
![bug-collaspe](https://cloud.githubusercontent.com/assets/976175/15612117/c6eeec60-242d-11e6-8fae-f0c69d33d27d.gif)

**Comment by pixelastic** [comment]
I don't understand the actions you're doing in the gif. Could you write them down?

**Comment by Shipow** [comment]
sure
- i'm selecting the "leage of explorers"
- it doesn't refresh the list
- i'm collapsing the menu and re-opening it again
- the list is correctly displayed (LOE active)

**Comment by pixelastic** [comment]
Which version are you using? Latest?

Could you copy the widget code so I can repro?

**Comment by Shipow** [comment]
Latest.

`searchstone.addWidget(
  instantsearch.widgets.refinementList({
    container: '#set',
    attributeName: 'setFull',
    operator: 'and',
    limit: 10,
    sortBy: function(a,b){
      return set.indexOf(a.name) - set.indexOf(b.name);
    },
    templates: {
      header: 'Set',
      item: '<a href="#" class="list-group-item{{#isRefined}} active{{/isRefined}}" data-facet-value="{{name}}"><span class="value">{{name}}</span> <span class="badge">{{count}}</span></a>'
    },
    collapsible: true
  })
);`
