### ISSUE TITLE
I can't get rid of the react dev version error message.

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#1044]
![image](https://cloud.githubusercontent.com/assets/976175/15644288/606c404c-2652-11e6-912c-0d631e4fc607.png)

**Comment by vvo** [comment]
Hello, 

If you are not using the builded version of instantsearch.js (jsDelivr) then you need to build your project using webpack's ENV plugin: https://github.com/algolia/instantsearch.js/blob/9aa93e0d7ae9843729f158c8deff679eaf8ec7d2/scripts/webpack.config.jsdelivr.babel.js#L29-L35

Then on the command line, when building: `NODE_ENV=production npm run build`

**Comment by vvo** [comment]
See http://facebook.github.io/react/downloads.html#npm

**Comment by Shipow** [comment]
Thanks @vvo I'll try that and get back :) worth a FAQ entry maybe.

**Comment by vvo** [comment]
This is a NODE_ENV issue and webpack issue, solved by https://github.com/algolia/instantsearch.js/issues/1044#issuecomment-222443662
