### ISSUE TITLE
Ability to change the Powered By template

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#1047]
I'm handling internationalization of the search in Algolia for Zendesk right now and the string "Search by Algolia" is the only one I'm not able to change depending of the language.

I can hack it by passing `poweredBy: false` to the widget and manually adding it myself, but I feel like we could just provide a template to replace the `PoweredBy` component on the SearchBox widget.

**Comment by pixelastic** [comment]
Yep, agreed. Care to do a PR?

**Comment by pixelastic** [comment]
Actually, I'm taking care of that.

**Comment by pixelastic** [comment]
Suggested a PR here: https://github.com/algolia/instantsearch.js/issues/1048
