### ISSUE TITLE
When we can't find a container DOM node, we should have an error that provides the selector and the widget

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#105]
It would be great to have the DOM selector that we tried to use and that didn't match anything when receiving the error:

```
Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

**Comment by redox** [comment]
:+1: Also got the error and the React stack trace is a nightmare to decipher. Also, what about prefixing the error by the widget name?

**Comment by bobylito** [comment]
Yep sure! Makes sense

**Comment by vvo** [comment]
Can be implemented in the utils.getContainer very easily, anyone can grab this one :)
