### ISSUE TITLE
searchParameters.facetFilters does not exist?

### ISSUE THREAD

**Issue by thailehuy** [algolia/instantsearch.js#1058]
I'm sure facetFilters is a valid search parameter on Algolia itself, but the library is saying that it is an unrecognized option.

Is there a reason for this? Or Am I missing anything?

**Comment by vvo** [comment]
Hi @thailehuy I believe you are trying to pre-select some default facet values?

**Comment by thailehuy** [comment]
@vvo Yes, yes I do

My typical situation is that I have a central index that contains items for several countries. Then users access www.mywebsite.com/<country> and search for items within that country

Right now I'm working around it with a hack by adding a default widget with disjunctive facet point to the current country (but that get reset with a clearAll widget)

I tried to use facetFilters in searchParameters, and it does pass that up to Algolia for the initial search, however, subsequent search got messed up and never run correctly.

**Comment by vvo** [comment]
> Right now I'm working around it with a hack by adding a default widget with disjunctive facet point to the current country (but that get reset with a clearAll widget)

That's the way to do it, unfortunately for now the "clear all" widget is not able to avoid clearing some filters.

We will make this easier in the long term.

For now, what you can do is use the currentRefinedValues with the clearAll option along with onlyListedAttributes:

```js
var clearAll = instantsearch.widgets.currentRefinedValues({
    container: "#active-refinements",
    clearAll: 'after',
    attributes: [{
      name: 'attr' // you must put a list of attributes you want the clearAll button to clear
    }],
    onlyListedAttributes: true
  })
);
```

When clicking clearAll of this widget, it should clear the list of attributes you gave but not the language.

**Comment by thailehuy** [comment]
Thanks, any reason why facetFilters is not supported?
Because I used an older version of tutorial with Algolia search and Algolia search helper that allow me to build that functionality perfectly.

Now instantsearch recommended by Algolia lacks that function and it confuses me.

**Comment by vvo** [comment]
`facetFilters` is a raw Algolia REST API entry while instantsearch.js and the helper are UI abstractions on top of Algolia so we learn the hard way on the various needs of our users like having a fixed facet filter.

If you are transitionning from JS client + helper to instantsearch.js I would love to have more of your issues. Everytime you hit the feature wall (you are not able to easily do what you want), please open an issue for us to discuss it and make instantsearch.js better.

**Comment by vvo** [comment]
Reopen the issue if this is not working

**Comment by thailehuy** [comment]
Thanks, it works for now
I hope facetFilters get added soon
