### ISSUE TITLE
Add the page, nbPages & hitsPerPage values to the Stats widget

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#106]
To be able to display:

```
Page YY of about XXXXX results (36 ms) 
```

or

```
Results YY-ZZ of about XXXXX results (36 ms) 
```

**Comment by Jerskouille** [comment]
And maybe the query too ?

**Comment by redox** [comment]
> And maybe the query too ?

Yes, it has been added 10 minutes ago; that's how I discover it.

**Comment by bobylito** [comment]
Isn't that based on a template?

**Comment by redox** [comment]
> Isn't that based on a template?

We should probably forward the whole answer object.

**Comment by vvo** [comment]
> We should probably forward the whole answer object.

Yes it works for this widget we can do it.
