### ISSUE TITLE
Merge clearAll and currentRefinedValues in a single widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1063]
Those two widgets are really close.

One of them is a single "clear all" button, the other one is a list of the active filters plus a "clear all" button.

We need to review the API and use cases of those widgets to see if and how could we merge them.

As a user I would be a bit lost here, I would prefer to have a "clearFilters" widget that could do both with a straightforward API.

**Comment by timkelty** [comment]
@vvo what was the resolution here, are the filters going to merged or remain separate?

**Comment by vvo** [comment]
Those will remain separate, we are working on react instantsearch whose API will drive IS v2 API.

We will have two separate components but both will be able to show and filter only a subset on attributes if tou want to
