### ISSUE TITLE
rangeSlider upgrade

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1069]
Given user feedback on our first rangeSlider:
- it should be possible to have a single handle (= no range)
- it should be possible to have min/max inputs to change
- we should document all the options, some of the noUiSlider option are not documented
- we should rename rangeSlider to slider
- we should be able to display the min and max values in different containers than the tooltips (#826)
- hide the tooltip when it's equal to upper/lower bound (#785)
- we should be able to programmatically set the ranges
- expose rtl option
- we should be able to have non linear sliders see #1035

**Comment by davids101** [comment]
Would love to see non-linear sliding implemented as soon as possible

**Comment by kaskajp** [comment]
Would love to be able to manipulate the tooltips when they're equal to their upper/lower bounds. Especially the upper one so I could display it like "€ 70 000+" or something.

**Comment by vvo** [comment]
@kaskajp thanks. are you proposing a new feature on top of the issue detail or backing an existing item?

Can you detail a bit more your comment so we can see if it fits an upgrade or not

**Comment by kaskajp** [comment]
- hide the tooltip when it's equal to upper/lower bound

Instead of just being able to hide, I'd like to be able to change the contents of the tooltip. So I could manipulate them sort of like in the examples below.

![screen shot 2017-01-04 at 11 29 04](https://cloud.githubusercontent.com/assets/1626458/21639604/3ae79b84-d271-11e6-829f-e7a0f3b1e00b.png)
![screen shot 2017-01-04 at 11 29 26](https://cloud.githubusercontent.com/assets/1626458/21639609/3e4c6e58-d271-11e6-8300-329f642e94fe.png)
![screen shot 2017-01-04 at 11 30 14](https://cloud.githubusercontent.com/assets/1626458/21639613/404f9b62-d271-11e6-8ee9-47daad90a51a.png)

**Comment by vvo** [comment]
That maybe you can already do it, try:

```js
tooltips: {
  format: function() {
    // console.log(arguments);
  }
}
```

**Comment by kaskajp** [comment]
Oh yeah, you're right. Thanks! Apart from that I'd definitely like to back:

- it should be possible to have min/max inputs to change

**Comment by bobylito** [comment]
Connectors offers a complete control on the underlying component / rendering making all the features possible without cluttering the API with options that are rare. However we can consider options one by one to be added if they are really common (please open a new issue if so 🙏 )

**Comment by bobylito** [comment]
> it should be possible to have min/max inputs to change

In v2, [we have a widget for that](https://community.algolia.com/instantsearch.js/v2/widgets/rangeSlider.html)™️.

**Comment by jasperkennis** [comment]
Whatever happened to the first idea; having a single slider?

I'm looking for a way to have a slider where the min is fixed to 0, and only the max can be adjusted.

**Comment by bobylito** [comment]
Hi @jasperkennis :) We provide connectors for such a case. In the [connectRange](https://community.algolia.com/instantsearch.js/v2/connectors/connectRange.html) you will be able to refine a range and build your own UI. We do not provide a widget with a single handle as we thought it was too much of an edge case at the time, but we're always listening to new feedback :)

**Comment by jasperkennis** [comment]
Thanks, if I build one I'll make sure to share it with you.

**Comment by bobylito** [comment]
Thanks @jasperkennis that would be awesome :) Don't forget to post it to the forum too https://discourse.algolia.com/

**Comment by jasperkennis** [comment]
@bobylito here's my crude version, this is sufficient for my needs so I probably won't update on it soon, it has some dependencies that others might find undesirable.

https://gist.github.com/jasperkennis/5fdbfc041ca65f58a4abac2468925eb8
