### ISSUE TITLE
Bug with facets and no results

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#107]
It is reproducible on the demo : just put a random string in the search box, it throws an error : 
```
e.getFacetValues(...).data is null
```

While implementing on Shopify, the error was with the slider first, but it might be all facet widgets:

```
TypeError: stats is undefined
```
for `range: { min: stats.min, max: stats.max }` in the slider code.

**Comment by vvo** [comment]
If it's easily reproducible on the demo and if you have time maybe you can have a look?

**Comment by pixelastic** [comment]
I've managed to fix the issue on the menu widget, but not sure what the best behavior for empty min/max is for the slider. Just do not display it?

**Comment by vvo** [comment]
We are working on the same issue :D

**Comment by vvo** [comment]
I'll let you handle it @pixelastic no big deal, to avoid this state next time: assign and move the task on waffle.io. I had moved it but not obvious (ready instead of doing).
