### ISSUE TITLE
Create a calendar widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1077]

**Comment by florentdestremau** [comment]
My try for now:

```
search.addWidget({
          getConfiguration: function () {
          },
          init: function (params) {
            var datepicker = $('.bootstrap-datepicker').datepicker({
              autoclose: true,
              format: 'dd/mm/yyyy',
              todayHighlight: true,
              weekStart: 1,
              language: 'fr',
              disableKeyboard: true,
              startDate: 'today'
            });
            var date = new Date();
            datepicker.datepicker('setDate', date);
            datepicker.on('change', function () {
              var date = $(this).datepicker('getDate');
              console.log(moment(date).unix());
              params.helper.removeNumericRefinement('timeStamp');
              params.helper.addNumericRefinement('timeStamp', '>=', moment(date).unix());
              params.helper.search();
            });

            params.helper.removeNumericRefinement('timeStamp');
            params.helper.addNumericRefinement('timeStamp', '>=', moment(date).unix());
          },
          render: function (params) {}
        });
```

It's working nicely since yesterday !

**Comment by vvo** [comment]
Awesome, congrats!!

**Comment by florentdestremau** [comment]
@vvo I wonder thought if there isn't a better way to handle the filter update in another way than remove + add ?

**Comment by chrisvidal** [comment]
@florentdestremau 
Did you release a calendar widget ?

**Comment by florentdestremau** [comment]
hi @chrisvidal, sorry but I never had the time to finish it properly so it's just the widget above for now.

**Comment by chrisvidal** [comment]
Alright, i will try to implement it, thanks
In my scenario, we need to use 2 date pickers, i guess that would work by just adding another datepicker widget

**Comment by redox** [comment]
Hey guys, did you see that Airbnb recently released https://github.com/airbnb/react-dates? Looks like the ideal calendar library to used in instantsearch.js \o/

**Comment by FredHasselot** [comment]
Hi,

It's an old issue but...

> params.helper.removeNumericRefinement('timeStamp');
>               params.helper.addNumericRefinement('timeStamp', '>=', moment(date).unix());
>               params.helper.search();

i'm using something similar with the helper method on a custom date selector widget :

` helper.removeNumericRefinement(attr).addNumericRefinement(attr, "=", timestamp).search(); `

It's fine, it filter the hits but...

How i would createURL like : `my_attr=timestamp` ?
i can't figure it out

🙏

**Comment by Haroenv** [comment]
there's a calendar widget example now https://github.com/algolia/instantsearch/tree/master/examples/js/calendar-widget which uses connectRange @FredHasselot
