### ISSUE TITLE
hits: implement onClick handler

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1078]
Following #1023

**Comment by SaadBinShahid** [comment]
Is this implemented ? If yes, can you please give me the link to it's documentation.

I want to capture which hit of the search-result (hits) is clicked using onclick event with and hit-object as parameter in it.

**Comment by vvo** [comment]
@SaadBinShahid Not implemented.

To do hit in instantsearch.js v1 you can do a custom widget and then render the hits as you want using jQuery for instance.

See this example: https://jsfiddle.net/vvoyer/fy8ve2dL/1/

**Comment by SaadBinShahid** [comment]
Thank you very much. That'll really help.

Regards,
Saad Bin Shahid | Software Engineer | www.saadbinshahid.com |
