### ISSUE TITLE
After reading the doc for url sync, I have no idea how it works.

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#1080]
The doc says to define an array of string for the parameters i want to track in the url.

So I came up with: `urlSync: {
    trackedParameters: ['query','cost','set']
  }` but it didn't work so I went to the full documentation (helper) where I found that maybe I should use 'disjunctiveFacet:['cost',...]' but... from here I've stopped.

I guess it miss an example.

**Comment by vvo** [comment]
That's a documentation issue, created #1089
