### ISSUE TITLE
Default output for range sliders in the active refinements list needs some love

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#1082]
https://www.dropbox.com/s/jwqymgx290qxay0/Screenshot%202016-06-12%2011.34.36.png?dl=0

^ This is the current output.

Could be something like "1 < attribute < 3" or "attribute: 1 to 3"

**Comment by vvo** [comment]
This is a general issue about numeric filters on an attribute don't you think? Yet linked to the rangeSlider in your example.

**Comment by bobylito** [comment]
The new connector API will let the users completly customize the output of the currentRefinement widget. This is not out-of-the-box but it will be possible to reformat / aggregate the values.
