### ISSUE TITLE
Should we use lodash?

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1085]
PROS:
- no brainer, use a single library for all data manipulation/check
- widely used
- no need to learn most JavaScript data manipulation/check methods

CONS:
- heavy from a library POV. Lodash is 10% of our minified build
- no need to learn most JavaScript data manipulation/check methods

Context:
- we can use ES6 **syntax** for arrow functions
- our browser support starts at ES5, which means we can access Array.map, filter, forEach
- we may have missing helper methods/options solved by using lodash methods (like https://github.com/algolia/instantsearch.js/blob/427521e9d82a23315e3ad7cf318313f265f3815c/src/widgets/numeric-selector/numeric-selector.js#L85-L86)
- we have to chose between lodash 3, lodash 4 and ultimately this duplicate code with our users (see #984)
- we could go with the facebook approach and share and create only what we really need: https://github.com/facebook/fbjs
- we do not know the performance implications of using lodash

From our current lodash usage in instantsearch.js (search "lodash/"), the only "tricky" non ES5, non arrow function solvable use case of lodash seems to be lodash/find (Array.find).

**Comment by pixelastic** [comment]
I feel like there is much more to lodash than just map, filter and each. It helps write complex code in a few lines, with method names that are explicit and clearly tell what the intent is. It's not just a polyfill, it really helps you write better code and focus on the business logic.

For me the improved readability and maintenance is worth the extra size. Of course, this is true only if we can select which part of lodash to import and not import blindly the whole lib.

**Comment by vvo** [comment]
> Of course, this is true only if we can select which part of lodash to import and not import blindly the whole lib.

This is already what we are doing in fact.

**Comment by vvo** [comment]
> It helps write complex code in a few lines

I feel this is really subjective. We would need code samples where our usage of lodash is obviously the right approach versus non lodash.

> this is true only if we can select which part of lodash to import

It is also true only if you are used to code every data transformation/check with lodash. And still subjective.

**Comment by Shipow** [comment]
> we can use ES6 syntax for arrow functions
this is complicating a lot the product

**Comment by vvo** [comment]
> this is complicating a lot the product (for those who are not front-end dev)

I can understand that, the syntax introduced by ES6 can be confusing if you are constantly switching from ES5 projects to ES6 projects.

Still, I don't believe we should restrict ourselves from using today JavaScript in a attempt to avoid having to learn it.

Any shift in the tech stack is hard if you are not using that tech stack day to day, but the longer you wait, the harder it will be (technical debt).

**Comment by Shipow** [comment]
Valable argument if you are working on a new project, more difficult if you work on an existing project where consistency is king. I'm not totally sold on the fact that it's our aim to educate users on new syntax.

To my POV it just complicates a lot the onboarding of our product.
I have no problem with you writing es6, I just think it's not adapted to examples and code snippets that we provide.

**Comment by pixelastic** [comment]
I remember a few PRs with comments like "Ooh, nice easy lodash one-liner". I just feel like if we are going to code ourselves the same helpers that what lodash is already doing, then we should just use the damn library :)

But yes, this is subjective, I personnally am more productive with lodash than without.

**Comment by bobylito** [comment]
From my experience, map, foreach, filter and reduce are very raw tools. If you want to do something that is not well suited with one of the first three, you end up using the fourth (reduce) which is quite hard to grasp if you're not used to it.

Lodash contains lots of shortcuts to avoid bloating your code. This makes the code very explicit as the function name is explicit about what you're trying to achieve, thus more readable.

One thing that could be very important for this issue, would be a static analysis of our usage of the lodash library. What I have in mind here, is to be able to figure what kind of usage we do lodash, `are we using basic functionnalities (map, reduce and co, or more fancy functions)?`, `where are we using those functions?`, `do we use shortcut syntax?`.

**Comment by vvo** [comment]
We use it for now, we only need to be careful at only using it when absolutely necessary, not for bind/map etc.. And always think about the underlying data structure: can we make it/refactor so that the number of calls to lodash (or even regular map etc..) is not so needed?
