### ISSUE TITLE
Allow to control autoHideContainer behavior

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1086]
The default behavior of autoHideContainer is widget based.

Given the widget, we will apply some rules that ultimately will decide if we want to show or hide the widget.

Some of those rules, may or may not make sense given the user use case. See #986.

I believe we should allow the user to override that default behavior.

**Comment by davids101** [comment]
I would like to see this as an optional feature

**Comment by bobylito** [comment]
This can be done with instantsearch.js v2's connectors.
