### ISSUE TITLE
Guide: urlSync

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1089]
There should be a dedicated section in the guide about url sync.

It should explains:
- [ ] what is the default behavior
- [ ] how to only set some attributes (trackedParameters)
- [ ] how to rename attributes
- [ ] how to add and sync more parameters (like custom_param=avalue)
- [x] what is is_v?
- [ ] when do you need to use the hash method (< IE9)
- [ ] Document default aliases

**Comment by bobylito** [comment]
Document the default aliases (see #1102)

**Comment by bobylito** [comment]
Closed in favor of #2216
