### ISSUE TITLE
Fix the Select menu on mobile

### ISSUE THREAD

**Issue by LukyVj** [algolia/instantsearch.js#1090]
To get the actual page as a first option. 
See https://github.com/algolia/instantsearch.js/blob/master/docs/_assets/javascripts/responsiveNavigation.js

**Comment by vvo** [comment]
cc @LukyVj still want to do this?

**Comment by LukyVj** [comment]
I wonder how I missed this comment, I'll do it!

**Comment by LukyVj** [comment]
Also fix #1091
