### ISSUE TITLE
rangeSlider format option for tooltips receives `undefined`

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#1092]
I'm trying to use the `format` function option of `tooltips` with the rangeSlider widget, but it fails because the function is not passed any parameter.

![](https://cloud.githubusercontent.com/assets/314079/16015350/8d4927bc-3195-11e6-9f81-fd034da3e5f2.png)

See this fiddle:
https://jsfiddle.net/fy1p8569/

(Note that I'm using `rawValue` here because I was not aware it was not passed anymore to the formatter function, but `formattedValue` is `undefined` as well)

**Comment by vvo** [comment]
Should be fixed, reopen if reproducible, provide a jsFiddle.
