### ISSUE TITLE
Toggle widget displaying 0 for count when there are results

### ISSUE THREAD

**Issue by davidpike7** [algolia/instantsearch.js#1096]
We are using toggle widget to check a numeric boolean value (can either be 1 or 0). It is setup like so:

```js
this.instantsearch.addWidget(
    instantsearch.widgets.toggle({
        container: '#journeys-specials-widget',
        attributeName: 'hasSpecialOffer',
        label: 'Only show specials',
        values: {
            on: 1,
        },
        templates: {
            item: refinementItem
        },
    })
);
```

The filter is working as intended but is displaying an incorrect value of 0 next to the toggle as there are 40 results displayed when toggled.

I feel like this has something to do with the off value not working correctly. If I set it to `0` the refinement is activated by default which isn't what we want.

The toggle was working previously when the values were `true` or `false` but our data changed and it stopped working.

**Comment by vvo** [comment]
@davidpike7 Can you provide us either a live jsfiddle, a live demo. Here or over support@algolia.com.

This will ease the debugging process.

**Comment by vvo** [comment]
The bug comes from the fact that where to look for the count of the toggled/untoggled values is different is the facet contains only numeric values (API automatically makes it a numeric facet). Fixing today

**Comment by davidpike7** [comment]
I'm afraid we're still having this issue. We've updated to 1.6.4 and still get a 0 on the toggle even though we have 100+ items with the flag set.

You can see the site on the link I've previously sent you.
