### ISSUE TITLE
[slider] create widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#11]
This widget needs to be able to render this:

![2015-08-05-105352_471x166_scrot](https://cloud.githubusercontent.com/assets/123822/9081879/511b2f5a-3b60-11e5-9341-91711d1fd055.png)

## API

TODO, detail the initiailization API like we do in the readme for other widgets

**Comment by pixelastic** [comment]
Sliders with multiple values are not yet supported, but we might be able to fake it by using two sliders positionned on top of each other

http://ng-range-slider.herokuapp.com/ (this example uses Angular, but I don't know to which extent yet)

I still don't know how we could approach this one without relying on external dependencies, but I guess having our default markup as simple as possible (like real input form elements) is a good start.

**Comment by redox** [comment]
We're also used to use [ion.rangeSlider](http://ionden.com/a/plugins/ion.rangeSlider/en.html), pretty nice especially when the 2 bounds are close together.

**Comment by vvo** [comment]
Maybe we should just code a minimal slider ourselves. That's no rocket science!

I did hack at some point https://github.com/vvo/slideways2 (not a range slider)

**Comment by pixelastic** [comment]
This does not seem too hard on the surface, but I wonder how much custom code would be needed to make it work correctly on mobile. Did you had any issues with that @vvo ?

**Comment by vvo** [comment]
Did no tried on mobile. Also the current ui-kit slider I retried it and worked well. The guy taking this issue will decide :)
