### ISSUE TITLE
Hits widget: transformData not always called when refining

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#1100]
When using a `refinementList` (or presumably other sorts of filtering), if a hit exists before and after refinement, `transformData` is NOT called the subsequent time(s).

Original post: http://stackoverflow.com/questions/37924976/instantsearch-js-hits-widget-transforming-data-on-refinement?noredirect=1#comment63313526_37924976

Demo: https://jsfiddle.net/timkelty/LyuL5eze/7/

**Comment by vvo** [comment]
@timkelty Revisiting this issue so basically the hits widget works like that:
- if the hits list is 0
- if the hits list length is different from the previous hits length
- or if some hits are different from the previous list (deep comparison)

Then we do render the hits again and call transformData.

So yes, if the hits list is absolutely the same between two clicks then we do not re-render it.

Can I ask you what you are doing in this formatData that would require the hits to still be re-rendered? Thanks

**Comment by timkelty** [comment]
In this case `formatData` is changing the display of the data based on `refinementList` criteria.
Specifically, choosing which product image is displayed (e.g. user filters "green", and an existing hit still needs to be re-rendered to display the image tagged as "green").

**Comment by vvo** [comment]
Ok so I fixed this issue by removing any check we had on the rendering of hits, it's too tricky to try to optimize that for now.

**Comment by timkelty** [comment]
Thanks, will test.

**Comment by vvo** [comment]
Not yet released, test in one hour
