### ISSUE TITLE
External query string parameters in urls are sent to the API

### ISSUE THREAD

**Issue by rayrutjes** [algolia/instantsearch.js#1102]
When we have a url like `www.website.com/page.html?s=param&query=a` it will send it will automatically append "test" to the "synonyms" value of the searchParameters, resulting in the request to Algolia failing.

https://codepen.io/rayrutjes/full/dXOWwX/?s=test

**Comment by vvo** [comment]
's' is indeed the short syntax for synonyms when stored in the url, see https://github.com/algolia/algoliasearch-helper-js/blob/0910355880512524ccd08fc610204eb00e9b9ffd/src/SearchParameters/shortener.js#L50

This needs to be documented at the urlSync level in the guide.

**Comment by rayrutjes** [comment]
In my case, the `s` parameter being the query, I ended up with:

```
urlSync: {
            mapping: {'q': 's'}
        },
```

Thx for the quick answer!
