### ISSUE TITLE
is_v parameter append to url even if not tracked.

### ISSUE THREAD

**Issue by rayrutjes** [algolia/instantsearch.js#1105]
I have the following config:
```js
var search = instantsearch({
            appId: algolia.application_ID,
            apiKey: algolia.search_API_key,
            indexName: algolia.default_search_index,
            urlSync: {
                mapping: {'q': 's'},
                trackedParameters: ['query']
            },

            searchParameters: {
                distinct: '1'
            }
        });
```

I want to only have the `query` tracked in the url as `s`.
A weird `is_v` parameter gets also append even if it is not part of the `trackedParameters` list.

**Comment by vvo** [comment]
is_v parameter was introduced so that we know from which versions of IS are the URLS.

It is not possible to remove it. Adding that to the documentation to make it clearer.
