### ISSUE TITLE
starRating widget does not hide when no data

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#1113]
All filtering widgets are hidden when there's no data to be shown.
The starRating widget does not. Instead, when no results contain any rating value (ie. everything is `null`), all stars choices are showing, grayed out.

It is a bit confusing when everything else disappears and only this stays in, but unusable.

There should probably at least be an option to have the same behavior.

**Comment by vvo** [comment]
Good idea, moving to #1119

**Comment by vvo** [comment]
I am not able to reproduce this @olance, using the instantsearch.js repo, modifying app.js to show only searchbox, hits, starRating. When typing something rubish and no results, starRating is hidden.

You can check the condition here: https://github.com/algolia/instantsearch.js/blob/0710af0ed0920049458080669ef5be063019c573/src/widgets/star-rating/star-rating.js#L160

**Comment by olance** [comment]
That is weird. Indeed I don't reproduce in a simple example as well, there must have been something else going on.
