### ISSUE TITLE
Entry point to customize hit output

### ISSUE THREAD

**Issue by Mach12** [algolia/instantsearch.js#1114]
It currently is impossible (or undocumented?) to not use the `hits` widget to get the hits.

However, as a fervent user of [Vue.js](https://vuejs.org/), I would appreciate the ability to, instead, use a hook to get the raw result data. Vue provides [more than enough tools](https://vuejs.org/guide/list.html) to render a list of results such as a list of hits, and this would let me have components for every result, but also insert Vue directives in the hit template, as they need to be processed by Vue to be functional.

For example, when one (like me) makes an SPA using Vue and [vue-router](https://github.com/vuejs/vue-router), if the hits must send the user to another part of the website, the attribute for the links' targets will be defined by `v-link`, not `href`. `v-link` directives, like any Vue directive, are only interpreted by Vue if the template output to DOM is done by Vue.

All this rambling just to tell you that I'd like to have (or discover) a hook to show the results using another technology than yours.

**Comment by vvo** [comment]
@Mach12 If you are using vuejs, I would advise you, for the moment to use our lower level JavaScript helper: https://github.com/algolia/algoliasearch-helper-js

It's basically what IS is wrapping in a widget API but if you are only looking at the raw results then you could use that.

We have a tutorial showing how to use it with jQuery: https://www.algolia.com/doc/search/instant-search/algoliahelperjs

Let me know how it goes.
