### ISSUE TITLE
Unable to find #search-input using instantsearch.js and Meteor

### ISSUE THREAD

**Issue by yonidej** [algolia/instantsearch.js#1116]
I am trying to use the instantsearch.js tutorial with Meteor but I have this error:

utils.js:79Uncaught Error: Container must be `string` or `HTMLElement`. Unable to find #search-box

Here is my code:

<img width="675" alt="screenshot 2016-07-04 12 50 54" src="https://cloud.githubusercontent.com/assets/19519903/16557015/fbd985e0-41e5-11e6-97f6-2e98d1953135.png">
<img width="671" alt="screenshot 2016-07-04 12 51 18" src="https://cloud.githubusercontent.com/assets/19519903/16557023/05ec8af0-41e6-11e6-9505-f1968ba290e0.png">

**Comment by vvo** [comment]
Hi @yonidej you might have a caching issue or something because "Unable to find #search-box" means that you sent "#search-box" as a container for the searchBox, while it's "search-input"

**Comment by yonidej** [comment]
Sorry, I meant search-input

**Comment by yonidej** [comment]
I get this error every time I try to connect a widget with it's corresponding id/html element. Maybe it has something to do with Meteor, am I requiring the right way? And do I need to install Algolia search NPM as well instead of just instantsearch NPM?

**Comment by vvo** [comment]
Is your main.js script inserted before the HTML DOM?

If so, you might want to use the https://developer.mozilla.org/en/docs/Web/Events/DOMContentLoaded

**Comment by yonidej** [comment]
It works. Thank you!

**Comment by yonidej** [comment]
@vvo I made a [repo](https://github.com/yonidej/Meteor-Instantsearch.js) for Meteor, Instantsearch.js compatibility. In addition to using the DOMContentLoaded event, I had to remove the getTemplate function and use a Mustache String template instead of wrapping it in a script like the [tutorial.](https://www.algolia.com/doc/search/instant-search#templates). It probably has something to do with Blaze templating...

**Comment by gathuku** [comment]
Am having the same problem implementing in a Jekyll site.

**Comment by Haroenv** [comment]
Please open a new issue @gathuku. Do you have a div with that id on your page?
