### ISSUE TITLE
Meteor templating(Blaze) won't work inside widgets

### ISSUE THREAD

**Issue by yonidej** [algolia/instantsearch.js#1117]
I got the [tutorial](https://demo.algolia.com/instant-search-demo/) code to work by using a Mustache String template(see below) and now I want to include a Meteor template inside the hits div but it does not work. Specifically, I want to include an "add to shopping cart" button right below the description but I cannot use Meteor templates inside the hits div so I can't add  a button. Can you please help?

Here is the code for my main.js: 

<img width="921" alt="screenshot 2016-07-05 00 35 18" src="https://cloud.githubusercontent.com/assets/19519903/16570135/628504f6-4248-11e6-877c-9c177df3f045.png">

Here is the code I am using for the {{test}} template helper. It just returns the string "test" when {{test}} is called: 

<img width="272" alt="screenshot 2016-07-05 00 45 50" src="https://cloud.githubusercontent.com/assets/19519903/16570205/d89b4bc2-4249-11e6-9eab-6106ebf01be9.png">

**Comment by yonidej** [comment]
I got the tutorial to work using a Mustache String template(see below) but I want to stop using the {{ delimiter for instantsearch. Specifically, I want to use a Meteor template but it does not work because Meteor uses {{template}} format as well.

<img width="770" alt="screenshot 2016-07-04 23 20 20" src="https://cloud.githubusercontent.com/assets/19519903/16569327/e6d3f4ca-423d-11e6-9ff8-765d5ea2ae78.png">

**Comment by yonidej** [comment]
I tried changing the Hogan default delimiter to <% %> but it didn't work.  

<img width="499" alt="screenshot 2016-07-04 23 03 47" src="https://cloud.githubusercontent.com/assets/19519903/16570272/e5337ba6-424a-11e6-90f1-898f1167bc20.png">

**Comment by yonidej** [comment]
Do you think I would run into problems if I used React for my view layer instead of Blaze?

**Comment by vvo** [comment]
For now, untill we make instantsearch-react (this is currently being worked on), I advise you if you need to add a "add to cart" button to add it into your hits template and then if you need to bind an action on it, either use the old time onClick=window.action OR use event delegation https://davidwalsh.name/event-delegate

If you have any idea on how to make instantsearch.js better integrate with meteor.js templating I would be happy to know them!

Let me know if the dirty solution works for now

**Comment by yonidej** [comment]
Unfortunately, Meteor uses template based routing so I need to include the instantsearch widgets. And I always get this error: `utils.js:79Uncaught Error: Container must be `string` or `HTMLElement`. Unable to find #hits`

Any solution you can think of? 

I've tried everything I could think of(changing the routers, inserting as html...).

**Comment by yonidej** [comment]
btw thank u for the awesome support!

**Comment by vvo** [comment]
@yonidej `Uncaught Error: Container must be "string" or "HTMLElement". Unable to find #hits` really means that at the moment this line was executed, there was no div named id="hits". This is the first thing you would have to fix

**Comment by yonidej** [comment]
@vvo I tried changing the order in which the DOM was rendered but it doesn't mesh well with Meteor's templating system. I just checked out instantsearch-react and it looks like it's coming out July. So I'll wait for that.

**Comment by vvo** [comment]
Ok nice

**Comment by thomasspiesser** [comment]
I haven't tested this thoroughly, but I have used Blaze to at least render the hits template like this:

    Template.someTemplate.onRendered( function() {
      search.addWidget(
        instantsearch.widgets.hits({
          container: '#hits',
          hitsPerPage: 10,
          templates: {
            item: (data) => Blaze.toHTMLWithData(Template.yourPreviewTemplate, data),
            empty: Blaze.toHTML(Template.noResults)
          }
        })
      );
    });

**Comment by vvo** [comment]
Thanks!
