### ISSUE TITLE
Api proposal: currentRefinementsList widget

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#112]
The goal is to be able to list the current refinement and delete them one by one or all at one time.

Example from Jadopado :

![capture d ecran 2015-09-22 a 11 48 39](https://cloud.githubusercontent.com/assets/1689007/10015385/205abb20-6120-11e5-8c5c-2923f71f6f3d.png)

```
search.addWidget(
 instantsearch.widgets.currentRefinementsList({
    container: '#current-refinements',
    //clearAllButon // true or false
    //template
 })
);
```

Resulting dom would look something like:

```
<div id='current-refinements'>
  <div>Clear All</div>
  <div>
     <div>Men <span>x</span></div>
     <div>Nike <span>x</span></div>
</div>
```

What do you think ?

**Comment by redox** [comment]
:+1: we might iterate on the `currentRefinementsList` naming and use `ul/li` instead of `div`, but we'll need it!

**Comment by pixelastic** [comment]
Yep, totally agree this one is missing and needed.

**Comment by Jerskouille** [comment]
Alright, based on #378 here is the API I'm going for:

```js
search.addWidget(
  instantsearch.widgets.currentRefinedValues({
    container: '#current-refinements-list',
    cssClasses: {root, header, body, clearAll, item, clearItem, footer},
    facets: [ // Optional, if not specified, takes all of the facets
      { name: 'category'[, label: 'Category', transformData: function (data) { /* ... */ return data; }]},
      { name: 'brand'[, label: 'Brand', transformData: function (data) { /* ... */ return data; }]}
    ],
    templates: {
      header: '',
      item: '' + // Called with this.facets[current_facet.name].transformData({cssClasses, facet: {name[, label(||= facet.name)]}, name, count})
        '<label class="{{ cssClasses.label }}">' +
        '  {{ name }}' +
        '  <span class="{{ cssClasses.count }}">' +
        '    {{ count }}' +
        '  </span>' +
        '</label>',
      clearAll: '' +
        '<a class="{{ cssClasses.clearAll }}" href="{{ url }}">' +
        '  Clear all' +
        '</a>',
      footer: ''
    },
    clearAll: 'after', // [true, false, 'before', 'after'] (true == 'before')
    hideContainerWhenNoRefinements: true
  })
);
```

**Comment by pixelastic** [comment]
Looks good. Just have two questions:

- Why a `label`? Shouldn't an `a` be better?
- What is `cssClasses.clearItem`?

**Comment by vvo** [comment]
Ah yes indeed @pixelastic, labels should be kept for forms. We have a label in refinementList only because the default template is using a checkbox so it makes sense (click on label = validate checkbox)

**Comment by Jerskouille** [comment]
Alright for an `a`, and the `cssClasses` were indeed wrong.

**Comment by vvo** [comment]
@Jerskouille can you create a new issue and go for it so we avoid confusions about this current issue proposal/state? thx
