### ISSUE TITLE
Change event?

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#1128]
Is it possible to add a change event? So when a visitor uses a filter there should be a change event triggered? I want to give the visitor some visual feedback, like a loading button or so. The search is now too fast, visitors don't notice changes :P 

```javascript
var onChangeHandler = function() {};
search.on('change', onChangeHandler);
```

**Comment by vvo** [comment]
You could use the searchFunction for that:

```js
var search = instantsearch({
  searchFunction(helper) {
    // do something like showing a loading thing
    // when ready, use
    helper.search();
  }
});

instantsearch.on('render', function() {
  // remove the loading indicator
});
```

Although we do not recommend this, maybe show a very small fake progression bar showing everything is allright to the user if he needs some progress.

It also depends if those users were used to your old possibly slow search, those may be a bit lost but new users won't notice.
