### ISSUE TITLE
Api proposal: allow searchBox to reuse an <input>

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#113]
Following discussions we had in #25, here's the "final" proposal:

- [x] reimplement the searchBox widget using vanilla JavaScript to allow enhancing an already present `input` instead of generating a complete markup
- [x] automatically detect if the container is an <input> and bind to it, otherwise generate the DOM like right now

This issue was created to aboid confusions when reading all conversations in #25

**Comment by bobylito** [comment]
:+1:
