### ISSUE TITLE
CurrentRefinedValues widget bug?

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#1130]
When you visit [URL1] first and afterwards [URL2] the current refined values aren't shown anymore and the sort by widget has an issue as well.

I get this error in the console:
index.js:959Uncaught Error: merkFull is not defined in the facets attribute of the helper configuration

Which is true, I haven't defined it in searchParameters.facets, but when I do I can't select other values in this refinementList. Shouldn't the same code that gathers the values from the url define the facets in the helper or so? Or am I doing something wrong?

Both URL's are non public test sites. You can find the url's at http://codepen.io/Maaark123/pen/GqvBqb

**Comment by vvo** [comment]
Hi, thanks for your question.

Here's how you are using current refined values

```js
search.addWidget(
  instantsearch.widgets.currentRefinedValues({
    container: '#current-refined-values',
    clearAll: false,
    templates: {... },
    onlyListedAttributes: true,
    attributes: [{name: 'prijs', label: 'Prijs'}, {name: 'merkFull'}, {name: 'merkCat'},{name: 'carType'}, {name: 'loadIndexDisplay'}, {name: 'speedIndexDisplay'}, {name: '_tags'}, {name: 'aanbevolen', label: 'Aanbevolen door'}, {name: 'brandstofverbruik', label: 'Brandstofverbruik'}, {name: 'grip', label: 'Grip'}, {name: 'rolgeluid', label: 'Max. Rolgeluid (dB)'}]
  })
);
```

But `merkFull` is not defined as a facet so why would we want the user to be able to clear it? 

Thanks

**Comment by Maaark** [comment]
I'm not sure if I understand you.

MerkFull is a refinementList and works as expected (and can be cleared in the currentRefinements). We have set the urlsync option to true, so we want the show the same state when a user refreshes the page for example.

When you now refresh the page you will get this error, but we want it to work exactly the same as it did without the refresh. 

Not sure if it's the currentRefinements that causes this.

Another question about the currentRefinementsList, is it possible to edit the template a bit more? We've edited the template and added a cross to delete the selection and we now only want to have the cross clickable.

**Comment by vvo** [comment]
> Another question about the currentRefinementsList, is it possible to edit the template a bit more? We've edited the template and added a cross to delete the selection and we now only want to have the cross clickable.

Please can you open separate issues.

**Comment by Maaark** [comment]
@vvo Done

**Comment by vvo** [comment]
@Maaark I am following this issue back, I cannot find the urls anymore. But nevermind, could you create a jsFiddle with the least amount of code needed to reproduce the error? That would help me.

I understand that it means digging inside the error and almost solving it but I believe since you can reproduce it on your environement, with some try and console.log() and code commenting you should be able to generate a simple jsFiddle using your data or fake data so that we can really understand how to simply trigger this bug.

Thanks.

**Comment by Maaark** [comment]
@vvo 
http://codepen.io/Maaark123/pen/akYqWQ - not really working since it doesn't append data to the url (urlsync: true),  so I think it's impossible to see the issue via this url? 

It might be better to share our test environment url with you. So you can see it in action. Can I share the url's with you per email? How can I reach you?

**Comment by vvo** [comment]
I can download the codepen example and see the url bug. Just confirm me what are the steps to reproduce the behavior and what are you expecting instead.

**Comment by Maaark** [comment]
In the example, click on Michelin => url should change, refresh the page
and see in the console the error.

After the refresh the other brands arent shown anymore, even when you
deselect Michelin.

Is it clear what I mean?

**Comment by vvo** [comment]
@Maaark We found the bug and will publish a new version tomorrow morning CET. Thanks A LOT for your patience and feedback

**Comment by vvo** [comment]
In the meantime, to fix your issue, you can do this:

```js
	searchRefinements1 = {maat: ['235 / 50 R18'],isZomerband: [1],}
	searchRefinements2 = {maat: ['235 / 50 R18'],isZomerband: [1],}
```

And then use

```js
	  	facetsRefinements: window.searchRefinements1,
    	disjunctiveFacetsRefinements: window.searchRefinements2,
```

(Same thing for facets and disjunctiveFacets options

**Comment by Maaark** [comment]
@vvo Great! I will apply it to our test environment in the afternoon, will let you know if it worked.
