### ISSUE TITLE
Error when running linter

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#1139]
When I try to run `npm run lint`, I have the following error:

```
Error: algolia:
        Configuration for rule "no-cond-assign" is invalid:
        Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error").
```

Same error occurs if I try to use `"eslint-config-algolia": "^5.1.0"` in another project. Looks like the syntax (now?) expect you to pass `2` instead of `error` in the eslint config.

**Comment by pixelastic** [comment]
Actually, after `rm node_modules && npm install` I now have a different issue:

```
Cannot find module 'eslint-config-algolia'
Referenced from: /home/tim/local/www/algolia/javascript/instantsearch.js/.eslintrc.js
Error: Cannot find module 'eslint-config-algolia'
Referenced from: /home/tim/local/www/algolia/javascript/instantsearch.js/.eslintrc.js
```

I should mention that I tested that on latest develop.

**Comment by vvo** [comment]
Yep sorry about that, you now need npm@3, that will fix it.

**Comment by vvo** [comment]
https://github.com/algolia/instantsearch.js/commit/1c295a41d30a36199fef3e6ce531aa64070104c3
