### ISSUE TITLE
Adding options.templates.allItems to refinementList widget (similar to the hits widget)

### ISSUE THREAD

**Issue by jfrueh** [algolia/instantsearch.js#1150]
I'm trying to gain more control over the refinementList widget template and how it is rendered.  In this case I'm specifically trying to create a 3 column layout with results alphabetized down column 1, then down column 2, and finally down column 3.  I'm unable to achieve this with the the way the current template renders HTML and custom CSS.  

I need to write my own custom template to handle it but I need to be able to iterate over the entire collection of refinements as opposed to just having access to them one at a time (like the options.templates.item property currently provides).

Here's what I'd like to see (similar to what you implemented to in the hits widget)

```javascript
instantsearch.widgets.refinementList({
    templates:{
        allItems: myRenderingFunction
    }
});

myRenderinfFunction = function(refinements){
 //here I can loop through all refinements and build the HTML however I need
}
```

Perhaps I'm missing an already easy way to do this - I'm not sure.  Any thoughts?

**Comment by vvo** [comment]
Hi @jfrueh this is currently not doable indeed. But that is definitely one of the main aspects of IS we are currently working on: provide full control of the markup and events given a widget, in an easy way.

We will get there ultimately but for now to do what you want, you will have to build custom widgets.

See https://github.com/algolia/instantsearch.js/issues/868#issuecomment-188206988 for a detailed explanation on doing a custom widget, you will have to tune it to do a refinement list and you will have to understand the helper for now.

I am sorry this currently does not fits your need for now, thanks for all the feedback!
