### ISSUE TITLE
starRating widget doesn't display a filter for 5 stars

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#1156]
In the starRating widget, we're generating filters for 1+, 2+, 3+ and 4+ stars, but not for records with 5 stars only:
![capture d ecran 2016-07-28 a 15 31 17](https://cloud.githubusercontent.com/assets/314079/17214282/76ba7d3c-54d8-11e6-8781-63790c9bf1e3.png)

We could maybe also have an option to show a link to filter on records that have a 0 rating?

**Comment by bobylito** [comment]
1/ true. Maybe we should add a 5 star option. @redox what do you think?
2/ 0 rating: Isn't that when you don't select anything?

**Comment by olance** [comment]
@bobylito When you don't select anything, by definition you get everything :)
So there's no way to say "I want the worst product ever". But then again, maybe it does not make sense to have this option ^^

**Comment by bobylito** [comment]
Well if you have a user generated content, it's not very likely to have strict 5 stars.

For the 0 rating, because of the design of the widget, it would be 0+ which is equivalent to selecting nothing.

I propose to close this issue for now :)
