### ISSUE TITLE
API proposal: `transformData` before template rendering

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#116]
Following discussion in #72 .

In a lot of wigets, there are many reasons that could justify modifying the data before calling the `render` method of the template: formatting, adding lambdas, etc. Right now, we're doing it by passing a function to `template`, however it doesn't seem logical that data modification happens there.

A solution that could make sense would be to add an optional `transformData` parameter to the object passed to a widget constructor which would accept a callback.

This callback would accept one object parameter: the previously object sent to `render`.  
It would then return a new (or not) object to be used with the `render` method.

```js
instantsearch.widgets.refinementList({
  container: '#myfacet',
  facetName: 'myfacet',
  template: '{{ value }}',
  transformData: function (refinement) {
    return { value: '$' + refinement.name };
  }
});
```

Some questions:
- Should we deep clone the object before sending it to `transformData` ?
- How to handle the *multiple templates* widgets (e.g. hits)? I am not found of the plural form of `transformsData`, and `transforms` might be clearer. Is there anything else we'd like to transform ?

**Comment by vvo** [comment]
> Should we deep clone the object before sending it to transformData ?

Should not be needed since every render re-computes fresh data, so the data is not yet passed to any other widget.


> How to handle the multiple templates widgets (e.g. hits) ? This could be an idea:

Yes `transformData` (instead of transformsData) and mapping to the templates.$KEY should be allright.

Also with #115 we will soon no more have single 'template' but 'templates' everywhere.

**Comment by pixelastic** [comment]
Regarding your example, wouldn't this be a simpler way to solve the issue?

```javascript
instantsearch.widgets.refinementList({
  container: '#myfacet',
  facetName: 'myfacet',
  template: '{{ value }}',
  transformData: function (refinement) {
    return { value: '$' + refinement.value };
  }
});
```

I feel the `transformData` is about transforming the data we got from the widget before passing it to the template. But not go too deep inside what helpers the Mustache render method has available. This should just be a _take object as input, returns object as output_ IMHO.

**Comment by redox** [comment]
:+1: with @pixelastic; didn't see we where dealing with the `helpers` in the first comment.

**Comment by vvo** [comment]
> didn't see we where dealing with the helpers in the first comment

Me neither sorry @Jerskouille! I think you can update the proposal with something simpler (but keeping the `transformData: {keys,keys}` solution which is needed.

**Comment by Jerskouille** [comment]
Simplified, but don't see why helpers weren't a good example.

**Comment by vvo** [comment]
Do you think passing a function in the helpers: {} would have worked? I thought that to have lambdas in hogan it was more work.

**Comment by pixelastic** [comment]
@vvo It would have worked, the function @Jerskouille was passing was one carefully wrapped once or twice so Hogan would get it :)

But you're right, in the end what you suggested first was a specific use-case knowing Hogan.
