### ISSUE TITLE
Collapsable filters for mobile

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#1161]
Hello,

We are building a more mobile friendly version of our filters and therefor we want to create collapsable filter boxes. Since we are already using Bootstrap 3 at our site I wanted to use their collapse functionality.

When I add the needed html via jQuery to the instantsearch generated html it doesn't work. It seems that it isn't picking up the click event.

When I add this:

```
this.addEventListener("click", function(){ 

            $($(this).data('target')).collapse('toggle');
        });
```

The collapse part works, but it seems that instantsearch is no longer picking up the events.. 

You can see what I mean at https://markputs.nl/algolia.php (make your screen small, javascript can be found in Algolia.js)

Thanks.

**Comment by bobylito** [comment]
@Maaark thanks for sharing you're use case. It seems that you are changing the content of the dom generated by the instant search widget (l.696 of algolia.js for example), and this will mess with the internal React rendering. If you change the outer dom it should be ok though.

**Comment by Maaark** [comment]
@bobylito What do you mean exactly with the outerdom? What element? Since we need to have a specific structure in order to have collapse functionality

**Comment by bobylito** [comment]
I use "outer DOM" as opposed to the DOM that's inside the widget. If you create DOM wrappers that fits the rules for your scripts that would work.

**Comment by Maaark** [comment]
But the issue is that I need to alter the react generated html to give it the right structure for the collapse functionality.

**Comment by bobylito** [comment]
Actually, there is an option to make the refinement list widget collapse already built-in. https://community.algolia.com/instantsearch.js/documentation/#refinementlist Would that work for you? 

<img width="473" alt="screenshot 2016-08-03 11 37 03" src="https://cloud.githubusercontent.com/assets/393765/17361033/a07fa562-596e-11e6-8bc8-4debfd42191d.png">

**Comment by Maaark** [comment]
@bobylito I tried that one but it didn't work. I reapplied it now, so you can see that it's not working and perhaps find the bug.

To make it a bit more complicated, we want to show the minimalized version only to devices with a window width < 600px. Bigger sizes should get our current version, with all options visible. Is that something we can do?

**Comment by Maaark** [comment]
@bobylito Can you confirm to me that it's a bug or did we do something wrong?

**Comment by bobylito** [comment]
I will make a proper example to test and check the behaviour and see if we're on the same page.

**Comment by vvo** [comment]
Hi @Maaark if you experienced any issue while using the collapsable option can you please demonstrate it somehow then we can work on it? Thanks

**Comment by Maaark** [comment]
@vvo You can see what I mean at https://markputs.nl/algolia.php. Make your screen 400px, click at filter resultaten and all of those refinement lists are collapsable: true. See for example that Merken area.

**Comment by Maaark** [comment]
@bobylito @vvo Any idea when you guys can have a look at this?

**Comment by vvo** [comment]
@Maaark I had a look right now, I can see the collapsible option seems not to work in your case. Could you try to first update instantsearch.js to the latest version? Your are using an old version (1.6.x), we are at 1.8.x.

Then if it's still not working I would advise you to try to reproduce the bug in a isolated simple webpage first, it will help you understand what can go wrong.



> And is it possible to make the collapsable functionality work with predefined window width limits? So for example we want to be the refinement lists only collapsable when the window width is < 768px?

Once the collapsible option is working in a simple webpage, you should try using our predefined CSS classes to apply some CSS media queries on top of them so that the widget are collapsed only based on the viewport.

See our CSS file (https://cdn.jsdelivr.net/instantsearch.js/1/instantsearch.css):

```css
.ais-root__collapsible .ais-header {
  cursor: pointer;
}

.ais-root__collapsed .ais-body, .ais-root__collapsed .ais-footer {
  display: none;
}
```

**Comment by bobylito** [comment]
It's an old issue and we haven't encountered it again. Please reopen an issue if you're experiencing it again.
