### ISSUE TITLE
More useful no-results message

### ISSUE THREAD

**Issue by kokliKo** [algolia/instantsearch.js#1164]
In the [instant-search-demo built using the algoliasearch-helper](https://demo.algolia.com/examples/instant-search/jquery/), there is a neat "no-results" UI that contains the currently active filters.
![image](https://cloud.githubusercontent.com/assets/2853038/17312198/e12766dc-5805-11e6-9a95-0d6c9da2680c.png)

Unless I missed something, recreating this with instantsearch.js requires a custom widget (the widget `currentrefinedvalues` can't be easily integrated into the no-results message).

Would it be possible to have this feature handled natively by the library?

**Comment by bobylito** [comment]
Have you tried the (currentRefinedValues)[https://community.algolia.com/instantsearch.js/documentation/#currentrefinedvalues] widget?

**Comment by redox** [comment]
> Have you tried the currentRefinedValues widget?

Yes, but @kokliKo mentions it's complex to use "inside" the no-results page.

**Comment by bobylito** [comment]
My bad :/ As of now the widgets are not composable and thus you can't mix them together. What about an option for the `hits` widget? I know we want to limit the number of options for the widgets, but if this case make sense we could internally reuse the widget.

**Comment by kokliKo** [comment]
Not sure about what's the best solution, maybe an option for the `hits` widget would be good like you mentioned.

Having a way to remove refined facets when having no-results is - I think - a best practice in terms of UX, so I would advocate for having it in the default widgets one way or another.

**Comment by bobylito** [comment]
> Having a way to remove refined facets when having no-results is - I think - a best practice in terms of UX, so I would advocate for having it in the default widgets one way or another.

Are you considering having an option in each widget?

**Comment by kokliKo** [comment]
Hmmmm didn't think about that. I don't think it's necessary though. Having it in the `hits` should be enough.

**Comment by bobylito** [comment]
We should try to see how to do that by making a prototype and depending on the difficulty, let's see if we do a guide or a super widget. CC @mthuret

**Comment by bobylito** [comment]
There is now a guide for customizing the no results page: https://community.algolia.com/instantsearch.js/v2/guides/no-result.html
