### ISSUE TITLE
document every widget with jsdoc

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#117]
Some of the widgets are documented using jsdoc, some are not.

It helps quickly document in the readme all the available options.

**Comment by pixelastic** [comment]
We might also need a way to document the data passed to the templates in a consistent way.

**Comment by vvo** [comment]
@pixelastic are you still working on this one? we miss some widget jsdoc

**Comment by pixelastic** [comment]
I thought I had done them all (except Stats because you were working on it).

**Comment by vvo** [comment]
Indeed sorry it seems like every widget is now documented.
