### ISSUE TITLE
The search lands on 404 if no results and enterkey is pressed

### ISSUE THREAD

**Issue by rayrutjes** [algolia/instantsearch.js#1171]
![image](https://cloud.githubusercontent.com/assets/5570853/17371348/d1e8b36a-599f-11e6-8c8c-b028f9f3a3e2.png)

**Comment by maxiloc** [comment]
@vvo @LukyVj Is there a reason why are we not using docsearch.js for the doc ?

**Comment by LukyVj** [comment]
Not that im aware of

**Comment by bobylito** [comment]
Wanna help @rayrutjes @maxiloc?

**Comment by vvo** [comment]
> @vvo @LukyVj Is there a reason why are we not using docsearch.js for the doc ?

It was never done, the search on this website was done before we released docsearch

**Comment by bobylito** [comment]
Fixed in the new website.
