### ISSUE TITLE
Example combining instantsearch.js and autocomplete.js 

### ISSUE THREAD

**Issue by chriscalip** [algolia/instantsearch.js#1173]
Who wants it? Can we have it?

is it possible to combine instantsearch.js and autocomplete.js on one app.js ?

Would like to make use of autocomplete.js multiple datasources while using instantsearch.js widgets..

**Comment by tecmusti** [comment]
**instantsearch.js**
```javascript
search = instantsearch({
  appId: XXX,
  apiKey: YYY,
  indexName: 'instantsearch_index'
});
search.start();
```

**autocomplete.js**

```javascript
	var client = algoliasearch('XXX', 'YYY');
	var index = client.initIndex('autocomplete_index');
	$('#main-search-form .form-control').autocomplete({ hint: true }, [
		{
		  source: $.fn.autocomplete.sources.hits(index, { hitsPerPage: 10 }),
		  displayKey: 'name',
		  templates: {
		    suggestion: function(suggestion) {
		      return suggestion._highlightResult.name.value;
		    }
		  }
		}
	]).on('autocomplete:selected', function(event, suggestion, dataset) {
		search.helper.setQuery(suggestion.name).search();
	});
```

**Comment by chriscalip** [comment]
cool.

**Comment by tnpriyanka12** [comment]
Im Trying to implement this in .NET, but doesn't seem to work. 
I have a console log just before calling .search(), which prints fine but the function itself doesn't seem to trigger.

**Comment by bobylito** [comment]
You're awesome @tecmusti !

**Comment by GiacomoSilli** [comment]
Hello, any working example of it ?

**Comment by Haroenv** [comment]
Probably not the same tactics as in the original post, but we have this example: https://codesandbox.io/s/rlp0m6yp

**Comment by GiacomoSilli** [comment]
> Probably not the same tactics as in the original post, but we have this example: https://codesandbox.io/s/rlp0m6yp

Thank you for this
