### ISSUE TITLE
clear query from the clearAll widget

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#1174]
There did not seem to be a way to clear the query with the clearAll widget.

The weird thing is there, the method clearing refinements is called _clearRefinementsAndSearch but does not seems to clear the search.

Probably fixable with an event based approach, or an extra option

**Comment by chriscalip** [comment]
In addition I would like to have a way to extend this widget to call a custom callback..
Use case is clearAll widget is use app state clear all.

**Comment by tecmusti** [comment]
You can do it by writing a custom widget.

**HTML**
`<button id="clear-all" style="display: none">Clear All</button>`

**JAVASCRIPT**
```javascript
var customClearAllWidget = {
	init: function(args) {
		var helper = args.helper;
		document.getElementById('clear-all').addEventListener('click', function() {
			helper.setQuery('').clearRefinements().search();
		});
	},
	render:function(args){
		var helper = args.helper;
		var state = helper.getState();
        //Check refined facets and query. If we dont't have any, hide widget.
		if(state.getRefinedDisjunctiveFacets()=='' && state.getQueryParameter('query')==''){
			document.getElementById('clear-all').style.display = 'none';
			return false;
		}
		document.getElementById('clear-all').style.display = '';
	}
};
search.addWidget(customClearAllWidget);
```

**Comment by chriscalip** [comment]
sounds good enough for me.

**Comment by bobylito** [comment]
That could probably be added as a single method on the [helper](https://github.com/algolia/algoliasearch-helper-js). I'm filing an [issue](https://github.com/algolia/algoliasearch-helper-js/issues/342) there.

**Comment by elfeffe** [comment]
This doesn't clear URL "q" parameter, so if you refresh, it searches for the same query

**Comment by bobylito** [comment]
> This doesn't clear URL "q" parameter, so if you refresh, it searches for the same query

You have now an option on the currentRefinedValues widget to clear also the query: https://community.algolia.com/instantsearch.js/v2/widgets/currentRefinedValues.html#struct-CurrentRefinedValuesWidgetOptions-clearsQuery
