### ISSUE TITLE
any status update on react components from #920?

### ISSUE THREAD

**Issue by acomito** [algolia/instantsearch.js#1181]
I was wondering if there was a status update on https://github.com/algolia/instantsearch.js/issues/920?

It sounded like there would be something available in july but my search didn't turn anything up.

If it isn't ready yet, does anyone have alternative suggestions? I'm using react and redux at the moment (with meteor).

**Comment by Morhaus** [comment]
Hey,

I'm currently working full time on bringing Instantsearch to React. You can track my progress on the instantsearch-react* branches.

If everything goes as planned, we should have something out by the end of August.

For now, you can use the [`react-algoliasearch-helper`](https://github.com/algolia/react-algoliasearch-helper). It's largely inspired by Redux, and allows you to connect your UI components to the state of an [`algoliasearch-helper`](https://github.com/algolia/algoliasearch-helper-js).

**Comment by acomito** [comment]
Great news!
