### ISSUE TITLE
toggle widget: autoHideContainer option not respected

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#1185]
See example: https://jsfiddle.net/timkelty/gov4cwhb/1/

I've explicitly set `autoHideContainer` to `true` (even though it is supposed to be the default).
There are 0 matched items, but the widget container still shows.

The `autoHideContainer` option seems to work fine in other widgets (e.g. refinementList)

![screen shot 2016-08-09 at 4 45 14 pm](https://cloud.githubusercontent.com/assets/18329/17533072/439a2510-5e51-11e6-8fc7-ad1ebc43daf4.png)

**Comment by rogerroelofs** [comment]
The issue here is that autoHide is calculated based on the total number of hits for both on and off states.  Switching to using facetValue.count seems reasonable to me but I'm not convinced that behavior will fit every use case.  What do you all think?
