### ISSUE TITLE
Displaying active query in currentRefinedValues widget

### ISSUE THREAD

**Issue by jfrueh** [algolia/instantsearch.js#1192]
Is there a way to display the active query (i.e. search term) in the currentRefinedValues widget?  

We are finding it difficult to communicate to the user that their results are always filtered by the search term they have entered.  If we were able to display the search term in the currentRefinedValues widget it would make things really clear.  

I'm unable to come up with a good work-around at the moment...  Thanks for the consideration and any ideas.

**Comment by bobylito** [comment]
This is not possible in the current state of this widget, but I think it's possible to extend the scope of what we display here.
