### ISSUE TITLE
[stats] create widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#12]
This widget needs to be able to render this:

![2015-08-05-105238_504x104_scrot](https://cloud.githubusercontent.com/assets/123822/9081855/2b30d466-3b60-11e5-845f-6cd6719bf4e2.png)

Even if I don't like theses stats (which user needs this kinds of information but developers?), we should have a widget for it.

### Usage

Given this html:

```html
<div id="stats"></div>
```

And JavaScript:

```js
instant.addWidget(
  instantsearch.widgets.stats({
    container: '#stats'
  });
});
```

We default to render:

```html
<div>10,000 results <small>found in 2ms</small></div>
```

### Options

* `container` string or DOMElement
* `template` string (hogan) or function
* `cssClass` string (space separated class names to apply to root element)

### Available data when passing your own template

* processingTime number (ms)
* nbHits number

**Comment by pixelastic** [comment]
This as actually been merged already.
