### ISSUE TITLE
Firefox warning: your code will run very slowly

### ISSUE THREAD

**Issue by JustinDrake** [algolia/instantsearch.js#1201]
The full warning is:

> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

I can reproduce on Firefox on Linux and Mac OS X.

**Comment by bobylito** [comment]
Hi @JustinDrake thanks for reporting this issue. Do you find this error in the documentation or on a specific example? Or is it in your implementation? Either way can you give us the URL?

**Comment by JustinDrake** [comment]
Sorry, this is an error displayed in the FireFox JavaScript console. My specific implementation is www.duosear.ch, but I believe the issue is not specific to my implementation.

**Comment by vvo** [comment]
Hi @JustinDrake I am not reproducing the error using Firefox stable. Wondering how I could reproduce it.

**Comment by JustinDrake** [comment]
Simply browsing to www.duosear.ch on FireFox 47 was enough to show the warning in the JavaScript console. I'm now on FireFix 48 and the warning has gone. 👍

**Comment by vvo** [comment]
Cool!
