### ISSUE TITLE
BC issue with sortBy "isRefined"

### ISSUE THREAD

**Issue by rayrutjes** [algolia/instantsearch.js#1202]
I have implementations where:

`sortBy: 'isRefined'`

Previously this would make active refinements go to the top of the list.

Now this is no longer the case and I have to use `sortBy: 'isRefined:desc'`

Any clue on this?

**Comment by bobylito** [comment]
This feature relies on the Helper. I opened an issue [there](https://github.com/algolia/algoliasearch-helper-js/issues/354).

**Comment by bobylito** [comment]
The regression has been introduced with 1.8.

**Comment by bobylito** [comment]
This is fixed in 2.13.0 of the helper.

**Comment by vvo** [comment]
released

**Comment by rayrutjes** [comment]
Thx @bobylito
