### ISSUE TITLE
Stopping a search

### ISSUE THREAD

**Issue by chrisvidal** [algolia/instantsearch.js#1203]
Hi, 
im trying to toggle between different search index trough different screens
Hence i have a dropdown with the 2 search options (companies or projects)
I'm using the urlsync because i need to be able to bookmark the url to retrieve a search results instantly later on.

I have 2 searchBox widget, 2 agolia search instances, and this 2 instances are started immediately.
I would like to be able to stop/start the search instance so that the url sync works fine when i toggle from one to another index

**Comment by vvo** [comment]
Hi @chrisvidal before I can answer you more I would be interested in seeing what you are building. We have very little examples of multi index search with instantsearch.js and to be able to build the right set of API we would like to know more/see your current interface.

Do you think you can share it with us? Mabe via support if it's currently not public: support@algolia.com (mention instantsearch.js, this issues and Vincent)

**Comment by chrisvidal** [comment]
Hi @vvo 
thanks for your reply, actually we managed to solve my requirements in the issue #1206 

my initial plan was to use different instance of is, but i ended up using only one and using the method helper.setIndex() to switch between index.

But since there is a start() method anyway, i think a stop() method could help in some situation
