### ISSUE TITLE
Removing widget

### ISSUE THREAD

**Issue by chrisvidal** [algolia/instantsearch.js#1206]
we can add a widget but how about remove a widget ?
i didnt see anything about this.
Lets say the user is able to add/remove himself widgets himself trough a UI ?

**Comment by bobylito** [comment]
Hi @chrisvidal, thanks for posting :)

By design, you can't add widgets after the `start` call nor can you remove widgets. Adding this possibility would be a huge change in the architecture of instantsearch.js. We are considering this for the next version of instantsearch.

However, there is a workaround that works pretty well. Add all the possible widgets on the page, and then dynamically hide / show your widgets. Would that work for you?

PS: Feel free to post more details about your application so that we can answer more accurately :)

**Comment by chrisvidal** [comment]
im using exactly this workaround for now but i have log js error in the console stating stuff like 
````
Uncaught Error: project_type is not a retrieved facet.
````

however i tried to cleanup the widget array anyway before adding the new widget.
It seems that it is still possible to add widget after the start method

````javascript
instanceSearchHelper.setIndex(state.currentIndexName);
instantsearch.widgets.length = 0;
state.widgets.forEach(instanceSearch.addWidget, instanceSearch);
instanceSearchHelper.search();
`````

**Comment by chrisvidal** [comment]
the workaround seems to work perfectly in my case,
the only issue that is remaining is the url sync that does not consider anymore the facet attributes selected 
the url keeps only the query,
any workaround for this please ?

**Comment by bobylito** [comment]
Can you share a link to your live website or a simplified view (on codepen for example) that demonstrates your issue?

**Comment by chrisvidal** [comment]
hi Alex,
right now im still in local dev mode on this particular feature, im thinking to push on a alpha server later in the day, Is there a way i can communicate you privately an url please ?

**Comment by bobylito** [comment]
Hi @chrisvidal, you can send a message to support@algolia.com and mention me :)

**Comment by chrisvidal** [comment]
thanks Alex :)
Since i push my new features, the url sync seems to be working again. Anyway im standing the url.

the toggling between index, is screwing up the url sync.
I think i should use the herlper.clearRefinements() and helper.clearTags() methods upon index switching.

**Comment by bobylito** [comment]
Hi @chrisvidal thanks for sharing the link.

I haven't been able to properly debug the code. But at least I have a much better understanding of your issue. Have you tried to reset the url when you switch from one instance of instantsearch to another?

**Comment by chrisvidal** [comment]
Thanks Alex for your time


right now, i didn’t clean up anything.
I’m thinking to do a helper.clearRefinements() and helper.clearTags()

that should do the trick i hope :)



Regards,
Christophe Vidal
Voilaah - Web Design Studio

**Comment by bobylito** [comment]
That will definitely clean up the URL.

**Comment by vvo** [comment]
I believe we can move this conversation to #1203
