### ISSUE TITLE
Use remarketing with search results

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#1218]
We want to use Google Adwords Dynamic Remarketing with our search results. Is there functionality available for this? Or do we need to custom build something? And if so, what is the best way to implement this?

See https://support.google.com/adwords/answer/3103357?hl=en retail section for more info please.

**Comment by vvo** [comment]
Hi @Maaark we do not have anything builtin with google adwords but we are very interested in the needs you have.

I have no knowledge at all about google adword or the page you linked unfortunately so you will have to explain it to me a bit more in detail what is it you want to achieve.

Can you detail a bit more for example what are the type of calls you would want to do to google adwords and how it relates to instantsearch.js/search?

Thanks

**Comment by Maaark** [comment]
@vvo Adwords retargeting are those ad blocks on websites that display products you recently viewed. To do that Google Adwords needs to know what products a customer viewed/searched for. 

To do so we need to implement some code that runs after a search. That code needs to contain this info:

```<script type="text/javascript">
var google_tag_params = {
ecomm_prodid: "REPLACE_WITH_STRING_VALUE",
ecomm_pagetype: "REPLACE_WITH_STRING_VALUE"
};
</script>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = xxxxxxxx;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/xxxxxxxx/?value=0&guid=ON&script=0"/>
</div>
</noscript>```

ecomm_prodid is an array with the product id's as in the shopping feed
ecomm_pagetype is a predefined string which is the same for all search queries on this page. 

So the main thing is that the ecomm_prodid gets filled with the product id's after a search and that the listed code is executed.

Is this clear enough? Or do you have additional questions?

**Comment by vvo** [comment]
So let's say I type "mp3" in a product search interface, I get ten different mp3 players, you want to send all of their ids to google adwords. Is that it?

**Comment by Maaark** [comment]
@vvo Yeah, that's all :)

**Comment by vvo** [comment]
Ok then to do so, you could do a small custom widget like this:

```js
var adWidget = {
  render: function(params) {
    var hits = params.results.hits;
    var ids = hits.map(function(hit) { return hit.id });
    adWordsCallWith(ids);
  }
};

search.addWidget(adWidget);
```

Something like that would work, then about the calls to make to google adwords, its up to you. There I cannot really help you.

Let me know how it goes.

**Comment by Maaark** [comment]
@vvo Thanks, that worked!
