### ISSUE TITLE
Unable to define only one active/inactive showMore template

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#1221]
If I want to override the `active` or `inactive` templates of the `showMore` in a `refinementList`, it seems that I have to override both.

If I only supply `options.showMore.templates.active` or `options.showMore.templates.inactive`, then I'm greeted with `Uncaught Error: Template must be 'string' or 'function', was 'undefined' (key: show-more-inactive)`.

The workaround is to provide both templates, but the ideal fix would be to allow overriding only one of the two, and use the default value for the other one.

 ```javascript
instantsearch.widgets.refinementList({
  showMore: {
    templates: {
      active: 'this will fail'
      // inactive:'unless this is uncommented',
    }
  }
})
```

**Comment by vvo** [comment]
Yep indeed we should be able to provide one or another, or at least be more specific in the docs. Either solution works for me.

**Comment by vvo** [comment]
Workaround for now is OK
