### ISSUE TITLE
Better PoweredBy logo

### ISSUE THREAD

**Issue by rayrutjes** [algolia/instantsearch.js#1222]
The current powered by logo is not very nice: it is blurred, not retina ready and doesn't scale well.

![image](https://cloud.githubusercontent.com/assets/5570853/18004093/204363bc-6b92-11e6-9ec1-e590f3d66e62.png)

**Comment by vvo** [comment]
Is it blurry because of using a non retina PNG? SVG could be a solution

**Comment by redox** [comment]
> Is it blurry because of using a non retina PNG? SVG could be a solution

So first it's blurry indeed, but mostly it's not the current/latest version of the logo /o\

I kept the same PNG format for now. Maybe base64/inlined SVG is working as well -> I think we went for PNG to target old IE browsers (https://css-tricks.com/probably-dont-base64-svg/#article-header-id-1).

**Comment by rayrutjes** [comment]
I think that we can now use SVG everywhere now, don't you agree @Shipow ?

**Comment by vvo** [comment]
This should be safe yes, if anyone wants to try it

**Comment by redox** [comment]
I'll go for it then.

**Comment by Shipow** [comment]
gogo SVG

**Comment by rayrutjes** [comment]
@Shipow Already merged in #1223 ;)
