### ISSUE TITLE
API Proposal - non numeric counts on refinementList et al

### ISSUE THREAD

**Issue by lowfatcode** [algolia/instantsearch.js#1227]
I'm using (and loving) instantsearch.js for the project I'm working on but I've hit a limitation that doesn't seem necessary.

I have a lot of results to filter/facet, and when presenting the refinementList options to the user instead of showing "Archived (103,256)" I want to present it as "Archived (100k+)". This is better UX as there is less parsing required to understand the size of the result set. I actually plan to break it down into a range of steps.

I've tried to use the transformData mechanism on the refinementList widget which *would work* if it weren't for the fact that the number is then manipulated as an integer further down the chain causing "NaN" to be output.

It feels like there shouldn't be any need to modify that value so it should end up intact in the output. Another option would be to allow something like an "overrideCount" property to be added to the object in the transformData method which would be used instead if present.

**Comment by vvo** [comment]
Hi @lowfatcode I think you should be able to accomplish what you want by using a custom template for refinementList and then creating a mustache helper (if you use mustache templating). Here's how:

https://community.algolia.com/instantsearch.js/documentation/#helpers

There's an example on the right part of the page (on desktop) that shows how to create a helper that would change some numerical data formatting.

I do agree that a generic way to do that (modifying template data before sending to template) could be nice.

Let me know how it goes

**Comment by lowfatcode** [comment]
I'll take a look at that thanks! I kind of thought transformData *was* that thing. But I'm probably mistaken!

**Comment by vvo** [comment]
Yep in your case it's a bit different, we try by default in the template to show the numbers in the user locale (1,000 or 1 000 or 1.000). Thus when modifying it to be "100k", it becomes a string, no more a number (and results in NaN Not A Number in JS)

**Comment by lowfatcode** [comment]
That is a very sensible reason for that to happen - I understand now! I'll take a look at the Moustache handler - to be honest I'm not a big fan of the limitations of Moustache, I keep finding I'm fighting it so I may end up just building my DOM from scratch anyway, in which case problem solved!

**Comment by vvo** [comment]
> I keep finding I'm fighting it so I may end up just building my DOM from scratch anyway, in which case problem solved!

Yep we also think that mustache by default can be a limitation for more advanced users and will default to function templates in the next instantsearch iteration (while still providing mustache templates for users willing to use them).

And if you use a function for templates then yes: problem solved you can just compute the template data here.

**Comment by vvo** [comment]
Thanks for your feedback!

**Comment by chrisvidal** [comment]
talking about the existing helpers formatNumber, is there a reason why it is not used in the priceRange widget ?

**Comment by vvo** [comment]
No particular reason, indeed that could be a nice addition, can you create a new issue about it? If you feel like coding it, go! :)

**Comment by chrisvidal** [comment]
hehe i can sure create an issue for this, but coding a react stuff :) its another story haha
