### ISSUE TITLE
Ability to turn searchOnEnterKeyPressOnly off or on for searchbox widget

### ISSUE THREAD

**Issue by urbanitedesign** [algolia/instantsearch.js#1233]
It will be great to be able to target this option through javascript to turn it off or on.

Our use case is we want to turn this off or on depending on when certain events are triggered.

**Comment by vvo** [comment]
Hi @urbanitedesign, it is currently not possible to update options after initialisation, we might provide this in the future.

In the meantime the easiest way is to instantiate two searchBox widget and hide/show them when you want.

This should work pretty well and still be performant.

Let met know

**Comment by urbanitedesign** [comment]
Yes I was told that it wasn't possible just yet, but would definitely be useful if you could.

I will give the 2 search boxes a go, nice idea hadn't thought of that. Thanks!

**Comment by vvo** [comment]
Ok, reopen the issue if that fails, I take good note of the "be able to update options dynamically", it's a recurring need.
