### ISSUE TITLE
every widget must have a visible example

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1238]
Every widget page documentation should include visual examples of different widget use cases. We currently only display an example code snippet, not the actual result.

At least one classical example usage and one HOC example per widget.

Related to #1237

**Comment by Kikobeats** [comment]
Maybe this could be easily fixed using https://getstorybook.io/

**Comment by vvo** [comment]
I dont know if the workflow/result of getstorybook can be easily integrated within our doc website. I do not want to have to generate two different websites (one for documentation, one for overview)

**Comment by Kikobeats** [comment]
that's true 👍
