### ISSUE TITLE
write a react-router + react-instantsearch example

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1239]
We need to be compatible with the React ecosystem, thus having a page showing the use of react-router along with react-instantsearch is mandatory.

**Comment by mthuret** [comment]
WIP here. 
The example will take advantage of the state/onStateChange/createURL api on IS. 
That way users will have a generic example (even though based on react-router), if they don't want to use history. (also, react-router is now using the v3 of history and our current impl were not compatible anymore). 

Based on that, I'll will also have a look at our current browser impl (createHistory in v2 leads to createBrowserHistory), and see if we can simplify a bit what we have.

**Comment by mthuret** [comment]
under guide/advanced-topics/UrlRouting
