### ISSUE TITLE
Smart debounce

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1245]
This has been asked and answered too many times. It's tricky to implement for users even since we provided the queryHook option.

We need to implement a debounce option on the SearchBox.

This is tricky to do it right, as @bobylito noted we could do it the "dumb way" (my first idea) and just use lodash debounce, done.

But this would lead to people using debounce and debouce searches to every 700ms which would be bad for the Algolia product overall.

@bobylito proposed to develop an adaptative debounce that would adapt to the user typing speed behavior. We liked the idea.

We can then see this feature as an addition to the overall Algolia experience, it's true that for some heavy typists, making one request per keystroke is not at all smart and efficient. And does not provide a better experience: there's no way we are gonna render anything if there's only say 15ms between two keystrokes.

First the network will take some time, then the rendering will take some time, and once that finished we may already be two keystrokes further.

PS: Should we also adapt to the network/response time? If the network response time \* 2 > interval between two keystrokes, is it worth making a new request next time immediately?

**Comment by JStonevalley** [comment]
Hi is there any progress in this area or do i have to resort to using lodash in an implementation of my own?

**Comment by vvo** [comment]
For now you have to use lodash yep and the queryHook (when using instantsearch.js)

**Comment by vvo** [comment]
User feedback linked to this: https://news.ycombinator.com/item?id=13962790

**Comment by mthuret** [comment]
Will be handled by #1994
