### ISSUE TITLE
*List: allow to provide an itemComponent

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1248]
There's currently no way to override the rendered item component in RefinementList, Menu, HierarchicalMenu and possibly others.

As soon as a user provides an itemComponent then the default itemComponent is no more used and the user will have to provide a react component being passed the data and the refine method to bind.

**Comment by bobylito** [comment]
From my experience using react-is for the tourism example, and IMHO this is so straightfoward to use the HOC that I don't think we need that.

**Comment by vvo** [comment]
> this is so straightfoward to use the HOC that I don't think we need that.

True.
