### ISSUE TITLE
urlSync for pages doesn't work with numericSelector and Pagination

### ISSUE THREAD

**Issue by dylanpinn** [algolia/instantsearch.js#1253]
Hi

I am trying to implement instantsearch on an app. I have everything work as expected except that the urlSync doesn't work for keeping the current page. It works for everything else and only works as expected when I remove my numericSelectors.

You can test this by using the tourism example in the docs and enabling urlSync, changing pages and refreshing takes you back to the first page.

Any suggestions?

**Comment by vvo** [comment]
Hi @dylanpinn I did what you said: activating urlSync on the tourism example, going to page 2, page 3, then hitting the back button. And it worked, the styling is badly done because both page 3 and page 2 would be shown as "active". But that's only styling, the page was refreshed with hits from page 2.

Let me know if you have another way to trigger the bug.

Thanks

**Comment by dylanpinn** [comment]
Thanks for the reply @vvo. Sorry it has taken me a while to get back to you.

My issue isn't with the back and forward buttons but if you refresh the page, it doesn't load the current page but loads the first page of results. I uploaded a video of it [https://www.youtube.com/watch?v=2ctWQhP1Sp4](https://www.youtube.com/watch?v=2ctWQhP1Sp4)

It works as expected if you comment this out in `search.js`, then go to the second results page and refresh it loads the correct page.

```js
search.addWidget(
  instantsearch.widgets.numericSelector({
    container: '#guests',
    attributeName: 'person_capacity',
    operator: '>=',
    options: [
      { label: '1 guest', value: 1},
      { label: '2 guests', value: 2},
      { label: '3 guests', value: 3},
      { label: '4 guests', value: 4},
      { label: '5 guests', value: 5},
      { label: '6 guests', value: 6}
    ]
  })
);
```

**Comment by vvo** [comment]
Was fixed @dylanpinn thanks a lot for feedback

**Comment by dylanpinn** [comment]
@vvo Thanks works a treat. 👍
