### ISSUE TITLE
rangeSlider widget value round issue on Safari

### ISSUE THREAD

**Issue by semanticdreamer** [algolia/instantsearch.js#1254]
First things first: THX a ton for all your awesome work w/ instantsearch.js 👍  

Seems there is an issue w/ the `rangeSlider`widget - only on Safari, so far tested on OS X only.

![](https://owc-dropshare.s3-eu-west-1.amazonaws.com/2016-09-02_11-18-27-vWoRlQCPKr.png)

To reproduce: https://community.algolia.com/instantsearch.js/documentation/#rangeslider

**Comment by bobylito** [comment]
Isn't that related to the underlying implementation @vvo ?

**Comment by vvo** [comment]
This will be released on monday

**Comment by semanticdreamer** [comment]
Wow, THAT was fast. THX @vvo 👍

**Comment by JanPetr** [comment]
@vvo I'm still experiencing the issue on Magento demo:
<img width="490" alt="screenshot 2016-09-12 18 07 28" src="https://cloud.githubusercontent.com/assets/1058144/18443141/dbed4c52-7913-11e6-95a5-5d51c3aea97f.png">

I'm using the latest version of IS with algoliaBundle, built today. Reopen?

**Comment by vvo** [comment]
@JanPetr Magento 1 or 2? Can you provide steps to reproduce the issue, I can use the developement environement of magento 1

**Comment by JanPetr** [comment]
Magento 1, go to https://magento.algolia.com/women/tops-blouses.html and play a bit with slider's left handle. Cannot reproduce all the time, usually it happens around value 200, but only from time to time :(
Google Chrome 52.0.2743.116, MacBook Pro

**Comment by vvo** [comment]
Released
