### ISSUE TITLE
Theming using CSS Modules

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1256]
The current theming strategy in `react-instantsearch` is to have BEM CSS Classes but allow people to use any technique implemented by https://github.com/markdalgleish/react-themeable.

1. Is this (BEM Classes) the right approach for a React based library?
2. Should we use CSS Modules instead?

https://github.com/css-modules/css-modules
https://github.com/javivelasco/react-css-themr
react-toolbox allows them https://github.com/react-toolbox/react-toolbox#prerequisites

I have 0 experience using CSS modules, but for sure we want to be compatible with them.

Allowing other theming techniques is nice, especially if we are gonna wrap `react-instantsearch` in `instantsearch` v2

**Comment by bobylito** [comment]
Those CSS modules seems right for React, but what about vanilla instantsearch?

> I have 0 experience using CSS modules, but for sure we want to be compatible with them.

Why? :)

**Comment by vvo** [comment]
CSS Modules seems to be a new way to style React components (and possibly non React) that is gaining some traction:
- https://css-tricks.com/css-modules-part-1-need/
- http://survivejs.com/react/advanced-techniques/styling-react/
- https://github.com/react-toolbox/react-toolbox (styling is done with CSS modules by default)

Not saying we should always surf the last trend but at least assure we are compatible with it (reduce the number of times you will hit a wall).

**Comment by vvo** [comment]
> but what about vanilla instantsearch?

I don't know if those will be relevant for vanilla instantsearch. I would say with vanilla instantsearch, our BEM approach worked well and we should keep it for now, without any other choice.

**Comment by vvo** [comment]
Also see this completely made up chart from google trends:

![2016-09-06-101448_2109x702_scrot](https://cloud.githubusercontent.com/assets/123822/18266406/c96ac12a-741a-11e6-89a8-61a625d19c56.png)

https://www.google.com/trends/explore?date=all&q=%22CSS%20modules%22,%22inline%20styles%22

**Comment by Kikobeats** [comment]
react-toolbox also is using a something more sophisticated for theming: https://github.com/javivelasco/react-css-themr#react-css-themr

**Comment by pgburrack** [comment]
Are css module supported now?

**Comment by Haroenv** [comment]
We have themes available, but they are regular css files: https://github.com/algolia/instantsearch/tree/master/packages/instantsearch.css
