### ISSUE TITLE
rangeSlider is hidden when only one value possible

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#1260]
I have a range slider for filtering on years. I also have facetting on tags and authors. It seems that when I do a facetting on tags and authors that results in only one year, the whole slider disappear.

![2016-09-05_12h15m31](https://cloud.githubusercontent.com/assets/283419/18244830/77f19dea-7362-11e6-83ba-7eb7ddca982f.gif)

^ Here, it's the last one, "Année".

You can see it live [here](https://pixelastic.github.io/parisweb/?q=&hPP=10&idx=parisweb&p=0&fR%5Btags%5D%5B0%5D=identit%C3%A9%20num%C3%A9rique&is_v=1)

I would suggest displaying the only possible value, in textual format instead of not displaying anything.

**Comment by vvo** [comment]
> I would suggest displaying the only possible value, in textual format instead of not displaying anything.

Works for me. This is also where we are gonna go by default for most widgets: do not hide contextual information even if no action doable by the user (but clear the refinement).

For example a toggle that would lead to no results if clicked or the same set of results should be displayed as disabled/grayed out instead of hidden (https://github.com/algolia/instantsearch.js/pull/1197#issuecomment-241666223).

**Comment by pixelastic** [comment]
Yep, I think it makes more sense. I will not be able to submit a PR anytime soon, though.

**Comment by bobylito** [comment]
👍 seems like an interesting UX / behavior improvement.

**Comment by bobylito** [comment]
This is low priority for @pixelastic, I propose this moves to v2.

**Comment by bobylito** [comment]
In v1, autoHideContainer was not working correctly: you couldn't disable the automatic hiding behaviour. However I test with your app in v2 and you get the following:

<img width="1272" alt="screen shot 2017-12-29 at 16 07 53" src="https://user-images.githubusercontent.com/393765/34439998-75d26d94-ecb2-11e7-81be-d3c59ddb2eea.png">

Do you think it's OK @pixelastic?

**Comment by bobylito** [comment]
Also after checking the code, the condition for hiding is when we have the max value equal to the min. I don't know what could be another condition, thoughts?

**Comment by pixelastic** [comment]
I think it's good enough in term of behavior. Maybe it could be improved by greying out the element (adding a class to the element when it's "disabled" like this?).

**Comment by bobylito** [comment]
> I think it's good enough in term of behavior. Maybe it could be improved by greying out the element (adding a class to the element when it's "disabled" like this?).

The slider is actually completely disabled when that happens \o/ I think we're on the same page then, closing the issue.

**Comment by pixelastic** [comment]
I understand it is disabled, but is there a custom CSS class added to it so I, as the website owner, can style it differently to clearly show it's disabled (putting it all grayscale or whatever). Or do I have to add the class myself from my template?

**Comment by Haroenv** [comment]
you can style it with `whatever[disabled]` I guess

**Comment by bobylito** [comment]
In v2, we use `ais-range-slider--disabled` as way to detect that a slider is disabled.

<img width="661" alt="screen shot 2017-12-29 at 17 26 04" src="https://user-images.githubusercontent.com/393765/34441645-64720f04-ecbd-11e7-830f-6ca7a9d4bbc8.png">

**Comment by pixelastic** [comment]
That's perfect! :+1:
