### ISSUE TITLE
How to easily conditionally display components based on the search state

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1266]
A typical use case is:
- when there're no search results, I want to display a specific component
- when there's no query I want to display a completely different homepage (jadopado like)

Currently in `react-instantsearch` we have a <NoResults/> component that allows us to display specific behavior when there're no results. 

The <NoResults/> current implementation is simple: it returns the child if there're results, and `null` if not. 

It means we can write:

```jsx
<NoResults>
	<div> No results</div>
<NoResults/>
<div>
//rest of the page
</div>
```

Now the issue is that `// rest of the page` will still be displayed when there're no results: **we need to have an if/else behavior**. 

With the current implementation, we could use an HOC and write something like: 

```js
function MyResults(props) {
  if (props.noResults) {
    return (
      <div className="results-wrapper">
        <div className="no-results">
          No results found matching <span className="query">{props.query}</span>
        </div>
      </div>
    );
  } else {
    return (
      <div className="results-wrapper">
      </div>
    );
  }
}

const ConnectedResults = NoResults.connect(MyResults);
```

As you can see, having a NoResults component is not that useful because the only thing we need is the ability to use the connect function. Also, it's not very simple in a user point of view, regarding that it's a common pattern. 

Now, what we could also do is to give the opportunity to the user to write directly something like this : 

```jsx
<NoResults>
        <div className="no-results">
          No results found matching <span className="query">{this.props.query}</span>
        </div>
<NoResults/>
<HasResults>
	<stuff>
<HasResults/>
```

And if we want to access parent props from the child, we can change the <NoResults/> implementation to this : 

```js
render() {
    if (!this.props.noResults) {
      return null;
    }

    return Children.map(this.props.children, child => {
      return React.cloneElement(child, this.props); //perform a merge between parent and child props
    })[0];
  }
 ```

That's one way to have a simpler api. 

With that in mind, opening the conservation: 

* Are HOC sufficient? Or are those patterns (NoQuery, NoResults, HasQuery ..) too frequent in UIs?
* Is the pattern with NoResults/HasResults is a better way to go (with some more documentation to know the props that are available) 
* Does you have any other ideas about the api we should use?

**Comment by bobylito** [comment]
I don't know if it's relevant to our discussion but I have two use cases that we often see:
 - when first displaying the page, display a content page instant of the empty query (a query with no parameters set)
 - when there are no results, display a list of all the refinements so that the end-user can discard some of them to get back to a state with results

**Comment by vvo** [comment]
> when first displaying the page, display a content page instant of the empty query (a query with no parameters set)

Yep that's the <NoQuery> component for example (does not exists today)

> when there are no results, display a list of all the refinements so that the end-user can discard some of them to get back to a state with results

Yes that's the <NoResults> component (exists today)

**Comment by vvo** [comment]
Also relevant: `<HasItems>` for any list of refinement items. This could provide most of the "autoHideContainer" behavior in V1 for people willing to have it.

**Comment by mthuret** [comment]
Here's an api proposal for the Results/Query conditional display: 

We could have a `Conditional` widget that will take a `show` prop. This prop will take a function with `(state, results)` as parameters and will expect a boolean in return. 

Example with the Query/NoQuery example: 

```js
<Conditional show={(state, results) => !state.q}>
      <div>No Query entered</div>
</Conditional>
<Conditional show={(state, results) => state.q}>
      <div>a query is entered</div>
</Conditional>
```

I voluntarily didn't include the `<HasItems>` one. Right now, with our current state management, I don't see an easy way to hide/show facets that will work with the ClearAll button.

**Comment by mthuret** [comment]
After second thought, even with the above api, basic limitation appear (like you're not able to access the query when hitting no results). 

In the end, for the release, we're just gonna create a "Conditional Display" guide explaining how to use the `createConnector` function to build it.
