### ISSUE TITLE
Do we need history.js?

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1267]
We are using https://github.com/mjackson/history internally to sync our search state to the url. I am not sure this is entirerly needed.

Investigate if:
- we need it?
- does it leaks to the public API (url sync doc and code)?

In instantsearch.js v1 we used two methods from the browser history API and it worked perfectly. Also we do not need to support hash based url state now (history API starts at IE11 which is OK for react-instantsearch).

**Comment by bobylito** [comment]
* Do we need it? Yes we need it, for usage beyond the web (for example using react-native)
 * Does it leak? as far as I can tell no. One of the of props of `InstantSearch` let you pass your own implementation, while theoretically nice to have, I don't know why we would and I suggest we remove it if we're not sure :)

**Comment by vvo** [comment]
> Does it leak? as far as I can tell no. One of the of props of InstantSearch let you pass your own implementation, while theoretically nice to have, I don't know why we would and I suggest we remove it if we're not sure :)

Currently I thought it leaked since the history prop expects an history object that must comply with history (V2!) API.

What we need to ensure is that we can use react-instantsearch in an environnement where react-router is already used and react-instantsearch comes on top.

**Comment by bobylito** [comment]
> Currently I thought it leaked since the history prop expects an history object that must comply with history (V2!) API.

Yes this is what I mentioned in my comment. It isn't strictly speaking leak. Since [history](https://github.com/mjackson/history) and react-router share the same maintainers and that react-router v2 was made to decouple the history management and the routing parts, I have a very optimistic view on the subject.

**Comment by vvo** [comment]
> One of the of props of InstantSearch let you pass your own implementation, while theoretically nice to have, I don't know why we would and I suggest we remove it if we're not sure :)

It seems to be the way to make IS + React-Router work together, we will see how it goes with #1239
