### ISSUE TITLE
[urlSync] order of url parameter

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#128]
Would it be possible to keep the order in trackedParameters when hashing the current state ?

**Comment by vvo** [comment]
You mean keep the order in the generated url string compared to the trackedParameters you gave?

I guess that's feasible, maybe to enforce having always the same pattern showing up in the url?

**Comment by maxiloc** [comment]
yes exactly

**Comment by vvo** [comment]
This is a helper issue you might want to create (and we can keep this one opened)

**Comment by bobylito** [comment]
Will fix this one :) Check the helper for progress.
