### ISSUE TITLE
Documentation pages should provide anchors for all headers

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1283]
Much like

![2016-09-15-093324_257x71_scrot](https://cloud.githubusercontent.com/assets/123822/18541760/7ab05068-7b27-11e6-89f0-a2708e7c8216.png)

See our places website https://community.algolia.com/places/documentation.html

This can be done either with:
- marked tuning to generate anchors next to headers
- JavaScript generation (https://github.com/algolia/places/blob/4f3c0f7a8f6760c41cd1f775b3a52137abc8cda2/docs/source/javascripts/anchorableElements.js)

Along with some CSS:
- https://github.com/algolia/places/blob/5207bc2445485fb1556109472dcf6b58a48e654e/docs/source/stylesheets/components/_documentation.scss#L232-L264

**Comment by bobylito** [comment]
Too bad we can't use https://developer.mozilla.org/en/docs/Web/Guide/HTML/Using_data_attributes with html markup :)
