### ISSUE TITLE
When clicking on the current page, search should not go back to the first one (no toggle)

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1287]
This is an example of this behaviour on the tourism example.

![pagination-revert-bug](https://cloud.githubusercontent.com/assets/393765/18548598/de9385a6-7b49-11e6-976f-fbe9d749b9ab.gif)

**Comment by vvo** [comment]
I am unsure this is a default behavior we should implement, if I ctrl+click the third page that is already selected (new tab) I expect it to open the 3rd page in a new tab.

Here it would mean going to the first page.

**Comment by bobylito** [comment]
Oups I should have mentionned that this is a bug :) And we should revert to the behaviour found in IS and basically all websites on internet when it comes to pagination.

**Comment by vvo** [comment]
:+1:

**Comment by bobylito** [comment]
While fixing this one, it actually triggered another bug which prevent the page from being reset when there is another filter that change its parameter. #workingOnASolution

**Comment by vvo** [comment]
was solved
