### ISSUE TITLE
Providing default themes for react-instantsearch widgets 

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1293]
react-instantsearch currently use under the hood react-themable for styling widgets. Using this library allow a user to style its components using its preferred approach (ex: pure css, css-modules or aphrodite...)

By default, react-instantsearch is only providing BEM classes to components. 

Issue : it would be nice to have some default themes, especially for the components that are a bit hard to style. However, default themes must not be intrusive for the user. 

As discussed, we will provide default themes using Aphrodite, but the user will have to explicitly import it and use it through the props `theme` that already exists. 

ToDo: 

* Checking that creating Aphrodite Stylesheet without using it, doesn't have some side-effects. 
* Create default theme for each widgets.

**Comment by mthuret** [comment]
I'll begin by styling with Aphrodite : SearchBox, Range (Slider), Rating, Pagination. 

Just to be sure we are all on the same page: for now, all the other components will have a default theme that is going to be the BEM classes we already provide.

**Comment by vvo** [comment]
> for now, all the other components will have a default theme that is going to be the BEM classes we already provide.

Do you already now how could we do better maybe? It will look a bit strange no?

**Comment by vvo** [comment]
Closing this in favor of #1256
