### ISSUE TITLE
Question: hits template ng-href alternative?

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#1298]
Hello,

Is it possible to use an href alternative in the hits templates? Like angular provides?

So for example instead of <a href="{{url}}"></a> something like <a ng-href="{{url}}"></a>? 

Asking this because some crawlers seem to follow the {{ url }} url of the template.

**Comment by vvo** [comment]
Hi @Maaark Sorry we missed this question, can you give us some more details and a code sample that is not working for you? Thanks

**Comment by bobylito** [comment]
With connectors you have a complete control over the rendering and you should be able to implement whatever you need. Can you open another issue if it's not enough?
