### ISSUE TITLE
Export strategy naming

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1303]
We currently have something like:

- `import {Range} from 'react-instantsearch';` => will render a slider
- `import {Range} from 'react-instantsearch';` => Range.input will render an input, Range.connect is the generic connector

Aside from #1300, we have a naming problem because it should be obvious that Range is a slider by default.

We need to move to:

```js
import {
  RangeSlider,
  RangeInput,
  rangeConnect
} from 'react-instantsearch';
```

Single namespace, clear separation, every export only import what he needs (connect does not loads the Slider CSS code for instance).

**The following ↓↓↓ discussion and comments are no more relevant as for decision making. We aligned and this issue description is our final statement.**

**Comment by mthuret** [comment]
I think that's better to name the Range, a RangeSlider, instead of letting the user discovering it in the doc. 
As for the connector, I'm fine with ***Connector. Also, maybe every connector can just have the root name ?

**Comment by vvo** [comment]
> I think that's better to name the Range, a RangeSlider, instead of letting the user discovering it in the doc.

:+1: 

> Also, maybe every connector can just have the root name ?

Do you mean import {SearchBox} would be a connector? If so, how do you name the SearchBox default implementation?

**Connector should do it.

**Comment by bobylito** [comment]
I like the current way because it's namespaced. I hear the need for preventing the import of unnecessary stuff. Could we have a connector namespace?

```js
import {range} from 'react-instantsearch/connectors';
// the connectors are in their own namespace to enforce using predictable naming
import {RangeInput} from 'react-instantsearch';
// the default level is for connected components / widgets
import {RangeInputComponent} from 'react-instantsearch/component';
// this namespace for the dumb components if we wish to expose them
```

**Comment by vvo** [comment]
@bobylito Yes this is a solution (namespacing connectors) that works. I am honestly hesitating between what you propose and this:

```js
import {RangeSlider, RangeInput, RangeConnector} from 'react-instantsearch';
```

Both are very close but the above format does not require the user to add a new import line as soon as he wants to use SearchBox AND any connector, he can reuse the same single import:

```js
import {
  SearchBox,
  RangeConnector
} from 'react-instantsearch';
```

What do you think?

> import {RangeInputComponent} from 'react-instantsearch/component';
> // this namespace for the dumb components if we wish to expose them

Side note, I am not sure I understand what's the difference between RangeInput and RangeInputComponent. Today we only have RangeInput (our default, exposed, soon styled components)

**Comment by vvo** [comment]
Iteration proposal:

```js
import {SearchBox, connectSearchBox} from 'react-instantsearch';
```

Single namespace

**Comment by bobylito** [comment]
`connectSearchBox` makes a lot of sense since it's a function!

the name is a tad long but I guess the single namespace is more straightforward.

**Comment by vvo** [comment]
Awesome, deal! I am updating the PR description for a better overwiew of the needed changes.

**Comment by bobylito** [comment]
I know this issue already consensus but isn't there some conflict with the react-native specific namespacing that we'd like to introduce? @mthuret @vvo

**Comment by mthuret** [comment]
Yes, you're right, for react-native we probably need something like you proposed before: 

```js 
import {range} from 'react-instantsearch/connectors';
// the connectors are in their own namespace to enforce using predictable naming
import {RangeInput} from 'react-instantsearch';
// the default level is for connected components / widgets
import {RangeInputComponent} from 'react-instantsearch/component';
// this namespace for the dumb components if we wish to expose them
```

**Comment by vvo** [comment]
Nice to restart this discussion
With what you propose @mthuret (and what I did propose at some point too) there are some flaws:
- root level is DOM, making native look like not nice enough to be root (Thanks @bobylito for pointing that out in our discussion, took time but this makes sense now)
- import {RangeInputComponent} from 'react-instantsearch/component'; is DOM only but you have no way to tell it

Iteration proposal:

```js
// root level is kept for everything non platform specific, for now connectors mostly.
import {connectRange, connectSearchBox} from 'react-instantsearch';
import {RangeInput, RawRangeInput, InstantSearch} from 'react-instantsearch/dom';
import {InstantSearch} from 'react-instantsearch/native';
```

Ultimately, we might even have to create different packages (for dom and native), just as facebook did (if we find the relevant reasons again).

**Comment by vvo** [comment]
moved to #1454
