### ISSUE TITLE
Cannot share custom component within Menu.connect and RefinementList.connect

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1305]
We cannot share custom components within Menu.connect and RefinementList.connect. This was a feedback from @GregoryPotdevin here: https://gitter.im/algolia/instantsearch.js?at=57da5121df21a75730fbd208

Menu connectors:

- selectedItem
- items
- refine, expects single value
- createURL expects single value

RefinementList connector:

- selectedItems
- items
- refine, expects array of values
- createURL expects array of values

Every connector rendering a list of items should provide the exact same API for consistency and ease of use.

Something like:

- items[{value, isRefined, name, toggleState}]
- refine(item.toggleState)
- createURL(item.toggleState)
- defaultRefinement

Linked to #1304, what do you think?

**Comment by GregoryPotdevin** [comment]
Easy part : menu connector could provide both `selectedItem` (for ease of use) and `selectedItems` (for compatibility).

What's `toggleState` in your example ?

**Comment by vvo** [comment]
> Easy part : menu connector could provide both selectedItem (for ease of use) and selectedItems (for compatibility).

Easy but already including legacy code :D

`toggleState` would be the precomputed state for every item, see #1304

**Comment by GregoryPotdevin** [comment]
It feels kind of weird to have on each item a field with the state of the other items. Something that feels a bit cleaner (but is probably too verbose) would be to provide a "toggle" function : 
```js
refine(toggle(item.value))
createURL(toggle(item.value))
```

The main advantage of this API is that it's possible to implement "clear" buttons (`createURL({})`, `refine({})`). The "business" logic of how to toggle items would be contained in the `toggle` function. For multi-select, it's a classic toggle, while for Menu toggling an item unselects the previously selected item.

**Comment by vvo** [comment]
@GregoryPotdevin indeed that would work, but what are the obvious differences between

```js
refine(toggle(item.value))
```

and

```js
refine(item.state);
```

?

**Comment by vvo** [comment]
> The main advantage of this API is that it's possible to implement "clear" buttons (createURL({}), refine({}))

This is already the case, you can call refine(null), but we will still provide a clear() method because that's the intent of the user.

**Comment by GregoryPotdevin** [comment]
I'm not 100% confortable with the idea of storing in each item a computed value that depends on other (selected) items but I don't like `refine(toggle(item.value))` either ^^

**Comment by vvo** [comment]
Moved to #1304
