### ISSUE TITLE
NumericRefinementList and Range distinction

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1306]
Our NumericRefinementList has it's own namespace while this is a Range with multiple start/end values and a possible multiple/single element selected behavior.

I don't know yet how to make this easier. I find it weird that we have both NumericRefinementList and Range. A NumericRefinementList is a Range dealing with multiple ranges. So we either have a naming issue or we need to merge them.

Maybe we can just rename NumericRefinementList to MultiRange?

**Comment by vvo** [comment]
Also add `multiselect={false}` to allow selecting only one value. By default you should be able to select multiple of them.

Also visually indicate non-relevant ranges given the current faceting stats.

**Comment by mthuret** [comment]
The multiselect option is no longer a priority for the first react-instantsearch release.
