### ISSUE TITLE
ClearAll widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1313]
There's currently no ClearAll widget for `react-instantsearch`, do we need one?

**Comment by mthuret** [comment]
A widget that will clear both filters and query at the same time ?

**Comment by vvo** [comment]
> A widget that will clear both filters and query at the same time?

Sorry no, not exactly.

In most implementations we had, we want a ClearAllFilter button. Do we have this today?

(changed the title)

**Comment by mthuret** [comment]
On the e-commerce example, I used CurrentFilters to do it : 

```js
<CurrentFilters
        theme={{
          root: 'CurrentFilters',
          filters: {
            display: 'none',
          },
          clearAll: 'CurrentFilters__clearAll btn',
        }}
        translations={{
          clearAll: 'Clear all filters',
        }}
      />
```

**Comment by vvo** [comment]
Since the intent of the user should be "I want a ClearAll button" I fear that he will not find this easy to do versus:

```js
<ClearAll/>
```
