### ISSUE TITLE
Write the guide content

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1315]
We need a very good guide for react-instantsearch that will explain basic and advanced concepts.

Parts that need to be written:
- [ ] Introduction (what's react instantsearch)
- [ ] Widgets (connected widgets to Algolia)
- [ ] Connectors (HOC providing simple mechanism for controlling rendering)
- [ ] Preselecting values (VirtualWidgets)
- [ ] Configuring Algolia parameters (distinct use case)
- [ ] Wrapping 3rd party libraries
- [ ] Styling (CSS Class names only)
- [ ] Creating a custom menu with manual items (#1062) 
- [ ] Conditionally displaying widgets
- [ ] Url synchronisation (Only show it can be activated/deactivated)

We should leave out parts like creating your own widget, injecting state, passing a history etc. for now because those APIs are unstable and may well change in the future.

**Comment by bobylito** [comment]
What about making a concepts guide to explain the overall architecture? This group several aspects like: 
 - what is instantsearch?
 - widgets
 - connectors

**Comment by vvo** [comment]
All in for an architecture overview item. As long as we are able to keep it simple. Even if we have multiple concepts in the library, once explained those should remain simple to understand.

Then how do we introduce that guide/link it? Just wondering because most of the time I tend to skip any "Architecture" link in a guide. Because I think "Well, that's your job to walk me through the API in a effective way, I don't want to read your architecture details.

In the proposal, we have " What is react-instantsearch" then "Widgets" and "Connectors" Maybe just filling those items without the need to create an - architecture link would better guide people to clicking/learning them?

**Comment by vvo** [comment]
updated the issue with better description on the next steps to be done

**Comment by mthuret** [comment]
What do you think of a structure like this ? 

1. Introduction
   - what's react-instantsearch
   - purposes of widgets
   - purposes of connectors
2. Styling
3. Connectors
   - How to use connectors (half the part that already exists in making your own widget)
4. Wrapping 3rd party libraries
5. Create your own widget
   - create connector api (used for conditional display)
6. Conditionally displaying widgets
7. FAQ
  - How to preselect values (virtual widgets)
  - How to add manual values to a Menu/RefinementList...
  - How to synchronize the url (this link being referenced within the InstantSearch component doc)

Also, do we want to keep the intro page for connectors/components?

**Comment by vvo** [comment]
It's taking shape! Some suggestions:
~~purposes of~~ widgets
~~purposes of~~ connectors (you do not yet know about them, you cannot ask their purposes)
~~Wrapping~~ 3rd party UI libraries
~~FAQ~~ Advanced topics

**Comment by mthuret** [comment]
Some part have been done. Feedback are needed :)
we still miss: Configuring Algolia parameters (distinct use case)
