### ISSUE TITLE
Default Filters with Custom Widget 

### ISSUE THREAD

**Issue by JonnyTurnerUK** [algolia/instantsearch.js#1330]
Hi All, 

I'm trying to get my head around using default filtering with custom widgets and I've come to a frustrating dead-end. 

I have a car search function (make, model, price...) that I'm placing across a website and I need to search all makes and models etc which is working great, but in some places I need to default filter the search form by make e.g. Hyundai, but the rest of the makes still need to be selectable  - basically a pre-selected value for an attribute - so I tried default filters (https://community.algolia.com/instantsearch.js/documentation/#default-filters).

Here's what I've got so far:

    var search = instantsearch({
      [...],
      urlSync: true,
      searchParameters: {
        facetsRefinements: {
          make: ['Hyundai']
        },
      }
    });

With this added, I only get the value 'Hyundai' in the drop down along with the title 'All makes' BUT I don't get any 'hits'. The error I get in the console is "Error: make is not defined in the facets attribute of the helper configuration". I've googled and have seen a few solutions but none work for me. Reading the documentation on helpers, that made me more confused as I'm unsure as to how to "connect" helpers with instsantsearch when initiating searches. 

I then read about facets that aren't defined by adding to the above:

    facets: ['make']

This then pulls back all hits that are only Hyundai but leaves my select dropdown completely blank (I imagine this overrides the custom widget use). I've got a feeling I'm approaching this in the wrong way as I all I need to is to a pre-selected value for the attributeName 'make' as if someone has already selected Hyundai. 

Hopefully this is not too confusing! Any pointers would be great and many thanks in advance.

**Comment by vvo** [comment]
Hi @JonnyTurnerUK sorry for the late response. I believe you are using a custom widget, could you maybe give us the code of the custom widget here?

What may be the source of your issues here is that ultimately you would want to use a "disjunctive facets" that would allow you to not only refine on a facets but keep showing the other facet values.

For this to work, I would advise you to change facets and facetsRefinements to disjunctiveFacets and disjunctiveFacetsRefinements.

The use case of default selected filters is very important to us because more and more frequent. This is today a pain to use and we want to make it easier.

**Comment by JonnyTurnerUK** [comment]
Hi @vvo, no probs at all, really appreciate the help. Sure, I've pasted the custom widget code below that was from this thread - https://github.com/algolia/instantsearch.js/issues/1022. I tried disjunctiveFacets as mentioned above but get the same result in the way that the stock gets filtered, there's 'Hyundai' in the refined values but nothing in the dropdown.

    instantsearch.widgets.customSelectorWidget = function customSelectorWidget(options) {
        var container = options.container;
        var attributeName = options.attributeName;
        var limit = options.limit || 10;
        var title = options.title || 'All';

        container = document.querySelector(container);
        var selectElement = null;
        var currentlySelectedValue = null;
        return {
            getConfiguration: function getConfiguration() {
                return {
                    hierarchicalFacets: [{
                        name: attributeName,
                        attributes: [attributeName]
                }]
            };
        },

        init: function init(options) {
            var helper = options.helper;
            container.innerHTML = '<label class="field select"><select></select><i class="arrow"></i></label>';
            selectElement = container.querySelector('select');

            selectElement.addEventListener('change', function() {
                var selectedIndex = selectElement.selectedIndex;
                var selectedValue = selectElement.options[selectedIndex].value;
                if (selectedValue === '__EMPTY__') {
                    selectedValue = currentlySelectedValue;
                }
                helper.toggleRefinement(attributeName, selectedValue);
                helper.search();
                currentlySelectedValue = selectedValue;
            });
        },

        render: function render(options) {

            var results = options.results;
            var sortBy = ['name:asc', 'count:desc'];
            var facetValues = results.getFacetValues(attributeName, {sortBy: sortBy}).data;

            if(facetValues){
                facetValues = facetValues.slice(0, limit);
                var innerOptions = ['<option value="__EMPTY__">' + title + '</option>'];
                facetValues.forEach(function(facetValue) {
                    var selected = facetValue.isRefined ? 'selected="selected"' : '';
        	    innerOptions.push('<option value="' + facetValue.name + '" ' + selected + '>' + facetValue.name + " (" + facetValue.count + ')</option>');
                });
                    selectElement.innerHTML = innerOptions.join('\n');
                }
            }
        }
    };

    search.addWidget(
        instantsearch.widgets.customSelectorWidget({
            container: '#make',
            attributeName: 'make',
            limit: 50,
            title: 'All makes',
        })
    );

Thanks again,

**Comment by vvo** [comment]
Hi again, do you think you could work into getting a functionnal jsFiddle http://jsfiddle.net/ for us to hack on it? That way, once you have the jsFiddle up and running, and that you can show us the behavior that is not expected. We can easily help you on it.

Thanks a lot for using instantsearch.js

**Comment by JonnyTurnerUK** [comment]
Definitely, I'll work on it now and try and get something asap for you.

**Comment by JonnyTurnerUK** [comment]
@vvo - managed to create something here with the Ikea credentials - https://jsfiddle.net/JonnyTurnerUK/3cjth7s2/5/

In this case, I'm using 'Material' as opposed to 'Make' so therefore, on load, the dropdown should be populated with all other materials with Glass selected within it. Hope this makes sense.

**Comment by vvo** [comment]
Ok I think I just fixed it by doing this:

```js
  searchParameters: {
    hierarchicalFacetsRefinements: {
      materials: ['Glass']
    }
  }
```

Let me know how it goes

**Comment by JonnyTurnerUK** [comment]
Awesome!!! I tried various types of facets, it turns out that 'Hyundai' should have been 'HYUNDAI' also for it to be selected in the hierarchy too. 

DOH! Thanks a lot for that. Much appreciated.

**Comment by vvo** [comment]
Great! Clearly this is our fault for now, not being good at this default selected game :) Happy coding

**Comment by jon-heller** [comment]
Just wanted to chime in -- hit a brick wall with a similar issue for awhile before discovering this thread. I had `menu` widgets, which when prefiltered were not showing as selected. 

My fix was also to change `facetsRefinements` to `hierarchicalFacetsRefinements`. Even though my facets are not hierarchical. Maybe update [the documentation](https://community.algolia.com/instantsearch.js/documentation/#default-filters) to recommend using `hierarchicalFacetsRefinements` instead?

Thanks!

**Comment by vvo** [comment]
Definitely gonna do that, thanks!

**Comment by vvo** [comment]
Done https://github.com/algolia/instantsearch.js/commit/19756c331e2a2965a974f1b75c3ca36bf489b266
