### ISSUE TITLE
Slider design best practices

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#135]
Food for thought about sliders:

> Use a slider only when the precise value won’t matter to the user, but rather only the approximate range. Make sure that the users can select that range correctly without having to struggle too much to hit a precise value. In addition, any slider labels must be displayed above or beside the slider, rather than below it, in order to remain visible while the user is selecting a value. Alternatively, consider a different UI element that allows users to tap or even type to specify their choice rather than relying on press-and-drag gestures.

[Source](http://www.nngroup.com/articles/gui-slider-controls/)

In other words: we might have to rething the use-cases of where we advocate a slider in a UX perspective. I don't think our current slider implementation fits with the above guidelines.

What we could do:

- [ ] Set a `snap` value by default, to not having to precisely select by the minimum unit (maybe automatically divide the whole range in X chunks)
- [ ] Move both tooltips above the slider, so one can still see its value while sliding on a mobile
- [ ] Allow one to specify an exact value (maybe directly in the tooltips. We talked about that already)

**Comment by redox** [comment]
I agree @pixelastic :) @Shipow your thoughts?

**Comment by vvo** [comment]
> Move both tooltips above the slider, so one can still see its value while sliding on a mobile

Careful, you then have to handle tooltip overlaps/find a way for them to not overlap. And ionrangeslider "merging" is not so great solution to this.

> Allow one to specify an exact value (maybe directly in the tooltips. We talked about that already)

This could be an option as proposed by @seafoox and @bobylito where you ask the API to generate `<input/>` to be placed before the slider.

> In other words: we might have to rething the use-cases of where we advocate a slider in a UX perspective

Yes slider are fun to develop but a pain to use and design well. A good price range is better in many situations. Or just `<input>`s.

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is very old and not done, reopen if you have the need and want to fix it
