### ISSUE TITLE
Default filters

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#1357]
Right now if you want a filter that:
- is there by default
- you can not clear with clearAll

You need to add it to the API key, maybe it could make sense to handle that from instantsearch.js

**Comment by vvo** [comment]
Maybe you can use filters='' param?

**Comment by vvo** [comment]
Wait, it seems feasible: https://github.com/algolia/instantsearch.js/pull/1194 :D

**Comment by bobylito** [comment]
We need to investigate a proper way to do that. #1194 is not enough from what I get of the use case. @maxiloc in your request, the granularity should be the attribute, right? Not just a parameter?

**Comment by jasperkennis** [comment]
I do this. However I do not expose clearAll, nor could I figure out how to invoke it real quick, so maybe this doesn't help at all.

```javascript
var search = instantsearch({
	    appId: 'x',
	    apiKey: 'x',
	    indexName: index_name,
	    urlSync: true,
	    searchParameters: {
	    	    filters: "name:" + filters
	    }
});
```

**Comment by bobylito** [comment]
For now, default values should be added using `searchParameters` on the InstantSearch constructor. Values that can't be cleared should be implemented either using `filters` or implement a `searchFunction` that always add the value. There is more than one way to do that and it should be tailored on the usage, we should consider making that a guide.
