### ISSUE TITLE
numericRefinementList radio not getting classes 

### ISSUE THREAD

**Issue by spoeken** [algolia/instantsearch.js#1358]
The radio input seems to ignore classes set in options.

`cssClasses: {
          root: 'w-100 pa3',
          item: 'w-100',
          active: '',
          label: 'dib w-100',
          radio: 'fl w1',
          header: '',
          list: ''
      },`

Result:
`<label class="ais-refinement-list--label dib w-100">
  <input type="radio" class="" name="pris" checked="">All
</label>`

**Comment by bobylito** [comment]
Hi @spoeken, thanks for reporting this issue. Can you tell me what version of instantsearch are you using?

**Comment by spoeken** [comment]
Hi, I'm have 1.8.8
