### ISSUE TITLE
[searchBox] manually focus on load when there's no query

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#137]
The current `searchBox` behavior is to add `autofocus="autofocus"` to the generated or inplace searchBox.

This cannot always work because `autofocus` attribute works if you are before DOMReady/load I guess.

There's currently a bug where there is sometimes autofocus, sometimes not.

In the end here's what we should do:
- manually focus the searchBox if there's no query defined (empty query)
- do not do anything if there's already a query, most of the time it looks weird to autofocus in this case
- add an autofocus: true/false option to the searchBox (since the user cannot disable autofocus with autofocus=off now)

**Comment by redox** [comment]
If we auto-focus (whatever the way) could we make sure we introduce an option to disable the behavior? We already got the question from a few e-commerce customers who didn't want their searchbar to be focused.

**Comment by vvo** [comment]
Indeed if we manually focus using DOM method we need to have an autofocus: true/false option also here

**Comment by bobylito** [comment]
If we have the autofocus option, does it still make sense to have the smart behaviour you suggested @vvo ?

**Comment by vvo** [comment]
We may need "autofocus: true/false/auto" Because otherwise people setting "true" would think that there will be always autofocus. While auto would be the "smart" one from the description that should fit most use cases?

**Comment by bobylito** [comment]
Yep that was exactly what I wanted to know. Will do that after the PR on QS.
