### ISSUE TITLE
Search form that submits on click and goes to results page

### ISSUE THREAD

**Issue by JonnyTurnerUK** [algolia/instantsearch.js#1378]
Hey all, we need to have a search function across various pages but this time, the results won't be vibisle on the page so therefore, when submitted, the user will be taken to a results page. Has anybody achieved this?

I've got the search functions in place and I've removed the hits etc so it works as expected, just finding it difficult to go off to another page and show results. Looking through many posts with similar questions, I've tried helpers and many functions but it appears that's out of my scope. 

Initially, I though that I could try 'getQueryUrl' as I thought this was the full query of the search on change but haven't managed to get it working. 

Any help would massively appreciated. Thanks!

**Comment by vvo** [comment]
Hi @JonnyTurnerUK,

You want to use instantsearch.js in a context where the user has to submit a form and be redirected to another webpage?

I am unsure why would you need instantsearch.js for then, since it was built for instant page updates? Maybe I am missing some context here.

The best way would be for you to give us access to some live environement demonstrating the issue.

Thanks

**Comment by JonnyTurnerUK** [comment]
Hey @vvo, I see where you're coming from. Basically, we're using the search function primarily where it does give instant results which is great and all working but the client would like a search form on the homepage so the user can search and the see the results.

Is there another route that I should go down? I'll still need instantsearch.js for the main listing page, it's just the form on the homepage.

**Comment by vvo** [comment]
What are the available search filters on the homepage, only the query?

**Comment by JonnyTurnerUK** [comment]
It's a car search function so we have - make, model, price min, price max, bodytype and fuel. Just a couple of them. I did originally look at trying to form a URL on submit and then simply just redirect to that.

**Comment by vvo** [comment]
> I did originally look at trying to form a URL on submit and then simply just redirect to that.

Yes this is the way to go for now indeed. But you could also completely replace the homepage content and use instantsearch.js on the homepage as if it was a search page.

Maybe what you could try is this:

```js
var search = instantsearch({
  searchFunction: function() {
    var queryString = search.helper.getStateAsQueryString();
    // redirect to queryString
  },
....
})
```

Let me know how it goes.

**Comment by JonnyTurnerUK** [comment]
Definitely a possibility. I'm back at the office in the morning so I'll definitely give that a go. As always, really appreciate the help. I'll let you know how it goes.

**Comment by JonnyTurnerUK** [comment]
Hey @vvo, just managed to get onto it and the above works exactly how I need. It's helped me understand a lot more about helpers so really appreciate the help and guidance. Thanks!

**Comment by vvo** [comment]
Awesome!!
