### ISSUE TITLE
Styling guide proposal

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1380]
# Styling

Default widgets in `react-instantsearch` comes with some styling already applied and loaded.

When styling components, you can decide to either extend or completely replace our default styles, using CSS classes or inline style.

All widget accepts a theme prop and the theme keys are defined in the widget docs.

# CSS classes styling

## Reusing our class names

Show how to style by adding a style.css and redefining our BEM classes

## Providing your own classes

theme={yourClasses}

## Extending the default theme

theme=extendTheme(defaultTheme, yourClasses)

# Inline styling

## Providing inline style

theme={inlineStyles}

## Extending our default theme

theme=extendTheme(defaultTheme, inlineStyles)

# react-themeable

The theme={} props accepts any parameter that react-themeable support...

# Tooling

Only here we can start talking about some tools we recommend as for CSS modules

## CSS modules with webpack

You can use webpack css modules on your side and still extend our themes.

Small js example, no need to explain how to configure webpack.

## Localized CSS with babel

Default themes of react-instantsearch are built with babel.. You can use it with your own code, and load css with insert-css.

Small js example, no need to explain how to configure babel.

## insertCss, insertStylesheet

Talk about insert-css and insert-stylesheet modules

**Comment by rayrutjes** [comment]
We should take this as an opportunity to correct our BEM syntax which is currently wrong.
Current is:
```
{block}--{element}__{modifier}
```
But really should be:
```
{block}__{element}--{modifier}
```
