### ISSUE TITLE
React 15.3.1 shouldn't be a dependency.

### ISSUE THREAD

**Issue by salazareddie** [algolia/instantsearch.js#1386]
Propose using
`"react": "^0.14.0"` in devdependencies 
See this [example](https://github.com/ReactTraining/react-router/blob/master/package.json)

**Comment by vvo** [comment]
Hi @salazareddie, thanks for the issue. Can you explain and comment how/if the current state is triggering some bad behavior on your side?

Thanks

**Comment by salazareddie** [comment]
@vvo 

For NPM < 3 this causes two version of react to be loaded, and the app to go [kaboom](https://facebook.github.io/react/warnings/refs-must-have-owner.html). The guys at material-ui had a similar issue, [here](https://github.com/callemall/material-ui/issues/2818#issuecomment-170708363).

**Comment by vvo** [comment]
Yep you're right thanks, it should be a peerDependency thought right? Because if you use this with npm, you will need react to be installed. Thus a peer will indicate this to you.

Also this may break some existing installations of instantsearch.js for npm users if we do this. For sure next breaking version we will do it, but for now we cannot.

What we can do is move to "^0.15.0", would that be fine for you?

**Comment by salazareddie** [comment]
@vvo Yes, it should be a peerDependency. Moving to `^15.0.0` should work for us. I think you will have to do the same for `react-dom`. Will grab latest once you push. Thanks for the quick turn around.

**Comment by vvo** [comment]
Ok so we are gonna move to ^15.0.0 put stick with dependencies field. We will move to peerDependency in another breaking version. None planned yet.

**Comment by vvo** [comment]
@salazareddie What's the react version you are using right now?

**Comment by salazareddie** [comment]
@vvo We are using 0.14.0. Tested the above solution locally and will do the trick. Just get these warnings when I npm install:
```
npm WARN unmet dependency /Users/esalazar/projects/***/node_modules/instantsearch.js requires react@'^15.0.0' but will load
npm WARN unmet dependency /Users/esalazar/projects/***/node_modules/react,
npm WARN unmet dependency which is version 0.14.8
npm WARN unmet dependency /Users/esalazar/projects/***/node_modules/instantsearch.js requires react-dom@'^15.0.0' but will load
npm WARN unmet dependency /Users/esalazar/projects/***/node_modules/react-dom,
npm WARN unmet dependency which is version 0.14.8
```

**Comment by vvo** [comment]
ok fine then thx, will do it assap

**Comment by salazareddie** [comment]
@vvo any updates on this?

**Comment by vvo** [comment]
Going to do a release in the coming hour, are you a react user? We do have a react specific set of components in the work right now if you want to beta test it, email at vincent@algolia.com thx

**Comment by vvo** [comment]
should be fixed, let me know

**Comment by salazareddie** [comment]
@vvo Do you want me to add a separate issue for moving the dependency to peer dependencies?

**Comment by vvo** [comment]
@salazareddie It's ok we'll do it but only on a breaking change, should happen this year :)
