### ISSUE TITLE
Cannot seem to get Mustache helpers working correctly

### ISSUE THREAD

**Issue by Sammaye** [algolia/instantsearch.js#1390]
Taking from: http://mustache.github.io/mustache.5.html it should be possible to pass variable into the helpers however, it is not quite working for me.

I have:

```javascript
		instantsearch.widgets.hits({
			container: '#resultHolder',
			transformData: {
				item: function(o){
					$.each(o.products, function(k, v){
						o.products[k] = {idx: k, obj: v};
					});
					return o;
				}
			},
			templates: {
				empty: 'No results',
				item: '{{#products}}{{obj.id}}{{#helpers.button}}{{obj}}{{/helpers.button}}{{/products}}',
			},
			hitsPerPage: 20
		})
```

now `{{obj.id}}` works perfectly fine but `{{obj}}` just prints `{{obj}}` in this:
```javascript
	search.templatesConfig.helpers.button = function(text){
		console.log(text);
	};
```

It seems that maybe there is something missing here?

**Comment by vvo** [comment]
Can you try using:

```js
    search.templatesConfig.helpers.button = function(text){
        console.log(this); // this should be the entire item
    };
```

I am unsure objects are supported. Maybe also try:

```js
    search.templatesConfig.helpers.button = function(text, render){
        console.log(render(text));
    };
```

https://community.algolia.com/instantsearch.js/documentation/#helpers

let me know

**Comment by Sammaye** [comment]
I tried {{object.id}} as well which was the same.

Logging `this` does give me the entire item

**Comment by Sammaye** [comment]
Oh hang on, I didn't try render()

**Comment by Sammaye** [comment]
Ok render() actually work but, yes, it doesn't support objects. But it works in accordance with mustache.

Thanks!
