### ISSUE TITLE
Adjust currentRefinedValues collapsed state

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#1394]
Hello,

Is it possible to adjust the collapse state after the widget is added? 

I want to collapse the filters on widths < 500px and un-collapse them on bigger widths. I can't do this in the addwidget function because I want to take switching orientations in account.

**Comment by vvo** [comment]
There's no easy way to do that with the collapsible option, I would disable collapsible option then use our CSS class names and media queries to collapse them when you want.

**Comment by Maaark** [comment]
@vvo Ok. But how do I make them un-collapse? Since the last time I tried I couldn't hook a onclick on the label because of React was getting in my way :)

**Comment by vvo** [comment]
@Maaark I thought you wanted to collapse/uncollapse based on media queries, not clicks?

**Comment by Maaark** [comment]
@vvo Collapse/uncollapse is based on the media queries indeed to start with. But they need to be toggled after a click. 

We want to show on small devices the closed version, after click it should open. On big devices it should always be open.

**Comment by vvo** [comment]
Can you create a small jsFiddle demonstrating the closest you can get to the behavior you want? Then inline here the jsFiddle and what's missing. Thanks!

**Comment by bobylito** [comment]
In v2, connectors let you recreate a complete rendering for widgets, therefore you can implement such behaviour. Closing for now, let me know if we can help. If you think it does not fit your usage, please  reopen an issue. Thanks 🙇
