### ISSUE TITLE
How to set a default query to search

### ISSUE THREAD

**Issue by sunel** [algolia/instantsearch.js#1395]
I am trying to set a default query to search instead of a empty search?

As i have pretty urls my search query will be like this

www.site.com/search/book instead of www.site.com/search?q=book

so i cant have the url sync enabled, so I have set urlSync to false. Now the inital query that is been passed is empty as it cant ready the url.

Is there a way to set the query before the search i been triggred.

i tried using the helper from the searchFunction but the api for the helper is totally diff from algoliasearchHelper

**Comment by vvo** [comment]
> Is there a way to set the query before the search i been triggred.

Yes, you could try to do this:

```js
var search = instantsearch({
  searchFunction(helper) {
    if (firstLoad) {
      search.helper.setQuery('book');
      helper.search();
    }
  }   
});
```

This is tricky as an API I must say, should work though.

**Comment by sunel** [comment]
Will try this

mean while when i went through the code found this for SearchParameters 

```
{
   "query": "book",
   "disjunctiveFacets": [
      "customerReviewCount",
      "category",
      "salePrice_range",
      "manufacturer"
  ],
   "maxValuesPerFacet": 30,
   "page": 0,
   "hitsPerPage": 10,
   "facets": [
      "type",
      "shipping"
  ]
}
```

**Comment by vvo** [comment]
Yep this should work also, unsure if you are then able to override the query, try it and close the issue if solved. Thanks!
