### ISSUE TITLE
Publishing process

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#14]
npm publish => jsdelivr, see algolia/algoliasearch-client-js#92

**Comment by vvo** [comment]
- [ ] main entry point for library should be dist/instantsearch.js (to be compatible with every module loader)

**Comment by vvo** [comment]
I did the first releases of instantsearch.js, we have:
- up to date project on github, default branch is now master
- https://github.com/algolia/instantsearch.js
- online demo (updated at release or manually with npm run gh-pages): http://algolia.github.io/instantsearch.js/
- npm published (readme will be updated next release): https://www.npmjs.com/package/instantsearch.js
- published on jsdelivr: http://www.jsdelivr.com/projects/instantsearch.js with automatic update through npm
- no dist/ in github
- dist/ is in npm
- default export is dist/instantsearch.js in package.json
- single release command: npm run release hope you love it
- some badges and readme update

**Comment by redox** [comment]
@vvo Could the online demo use the `dist` version + non-minified instantiations of the widgets instead of the `bundle.js`?

**Comment by vvo** [comment]
Oh yes I see what you mean, yeah it would be better. Ill do that now.
