### ISSUE TITLE
A filter change event needs to be emitted

### ISSUE THREAD

**Issue by Sammaye** [algolia/instantsearch.js#1410]
I have a fair amount of custom code which allows for graceful mobile rendering of search results with their filters.

This all works great until I click on a filter, at which point the view is re-rendered and the bindings of my jQuery are lost etc. I wouldn't mind except that I have no way to destruct my plugins and re-construct.

Maybe `render` should be called again?

**Comment by Sammaye** [comment]
Okay, on further investigation I found that actually `render` is called each time, I just had  a misconception abut that

**Comment by vvo** [comment]
Nice
