### ISSUE TITLE
Improve Range Slider on Mobile

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1421]
desktop:

![](https://d17oy1vhnax1f7.cloudfront.net/items/1w2Y451x020i3w320117/Screen%20Recording%202016-10-16%20at%2011.26%20am.gif)

mobile:

![](https://d17oy1vhnax1f7.cloudfront.net/items/3g3X2z351D3Y2F3U1N0o/Screen%20Recording%202016-10-16%20at%2011.27%20am.gif)

**Comment by vvo** [comment]
Thanks, ultimately we will either bundle an existing slider OR only provide an easy way to connect any slider.

**Comment by vvo** [comment]
moved to #1407
