### ISSUE TITLE
Need a way of making default facets that are not tracked in state

### ISSUE THREAD

**Issue by Sammaye** [algolia/instantsearch.js#1426]
What I mean is a bit tricky sine I am not sure how to explain it. Imagine I have:

```javascript
var search = instantsearch({
	appId: '<?= Yii::$app->algolia->applicationId ?>',
	apiKey: '<?= Yii::$app->algolia->apiKey ?>',
	indexName: 'titles',
	urlSync: true,
	searchParameters: {
		facetsRefinements: {
			live: [true],
			hide: [false]
		},
		facets: ['live', 'hide']
	}
});
```

But I do not have `live` or `hide` in my widgets as facets, there are two things I expect:

- The "clear all" widget does not show
- They are not tracked in the URL since these are like default params for this widget

Is there a way of doing this? If not, does this sound like a reasonable idea?

**Comment by vvo** [comment]
clearAll widget, use this option:
![2016-10-18-141734_922x92_scrot](https://cloud.githubusercontent.com/assets/123822/19477276/aa113cc0-953d-11e6-94e0-41884c2479a2.png)


urlSync, use this option:
![2016-10-17-160833_905x287_scrot](https://cloud.githubusercontent.com/assets/123822/19440906/fc8ae27c-9483-11e6-99b7-511e9deb31a4.png)

Let me know how it goes

**Comment by Sammaye** [comment]
It kind of works but the button still shows up, it stops tracking it in the URL etc etc, but the button to clear them still shows oddly

**Comment by vvo** [comment]
Given the code then it may be a bug: https://github.com/algolia/instantsearch.js/blob/308907b042a8f6308d8f0e5dc6534835fdb322b7/src/widgets/clear-all/clear-all.js#L80-L99

Because the code is supposed to handle it. I saw you already submitted a PR to fix a css class (merged), maybe you can give a try at this one too? That would be awesome.

**Comment by Sammaye** [comment]
I think that was someone else :) I don't know enough about react etc to create a PR here

**Comment by Sammaye** [comment]
For the minute I have got around this using https://community.algolia.com/instantsearch.js/documentation/#currentrefinedvalues and just hiding the filter list

**Comment by vvo** [comment]
Ok nice, thanks for getting back here!
