### ISSUE TITLE
API proposal : let the user pass a reference to a file for templating

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#143]
In order to make templating very easy and well done, we could provide a way to load the template from a URL. The code could look like : 

```js
var template = InstantSearch.templateLoader;

search.addWidget(instantsearch.widgets.hits({
    container: '#hits',
    templates: {
      empty: 'No results',
      hit: template('./templates/hit.html')
    },
    hitsPerPage: 6
}));
```

**Comment by vvo** [comment]
You mean we would then do something like an ajax call to load the template? Yes it works but is it a good practice to do X ajax calls to load templates?

**Comment by bobylito** [comment]
Short answering no :). But it is both useful, and would let the user start nicely (using operated files for template) and right away.

**Comment by redox** [comment]
I would rather go for inlined `$('<script type="text/template">....</script>').text()` I think. Introducing asynchronism here can be tricky.

**Comment by vvo** [comment]
> $('<script type="text/template">....</script>').text()

Then you do not need any of this, you just pass a string :)

**Comment by bobylito** [comment]
@redox we can internalize the loading and asynchronousity.

**Comment by pixelastic** [comment]
Not sure of the benefits of that. Inline templating or `script` workaround seems easier to me, without adding complexity to our side.

**Comment by bobylito** [comment]
This a public favorite, let's close this one!
