### ISSUE TITLE
instantsearch.js and AMD (requirejs & almond)

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [algolia/instantsearch.js#1430]
Does instantsearch provide support for AMD?

The reason I am asking this is that in my implementation using requirejs and almond, I am getting the following error from Almond: `Uncaught Error: See almond README: incorrect module build, no module name`
[Here is an explanation of it.](https://github.com/requirejs/almond/blob/master/README.md#incorrect-module-build-no-module-name)

In the instantsearch.js code, the module is defined here:

```
if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define([], factory);
    else if(typeof exports === 'object')
        exports["instantsearch"] = factory();
    else
        root["instantsearch"] = factory();
```

If I modify this and give `define([], factory);` a name like `define('instantsearch', [], factory);` then everything is fine.

Has anyone had success implementing instantsearch using Almond.js?

**Comment by vvo** [comment]
Hi @Giovanni-Mattucci I guess the option we should use then in webpack (we use webpack to build) is this: http://webpack.github.io/docs/configuration.html#output-umdnameddefine

What do you think?

Also, do you think you could try to build not from the dist file but from the raw sources (available in npm)?

**Comment by Giovanni-Mattucci** [comment]
@vvo that is in the right direction. Not naming the define() is the right way to go, I believe it is necessary for webpack, and has caused people some grief: https://github.com/webpack/webpack/issues/989
They fixed this when using webpack with the command you mentioned.

I just need to figure out how to have my compiled js detect unnamed defines, and give them names at compile. I am not sure how to do this using requirejs. :(

In the future I will be migrating to webpack but for now I am using requirejs + almond.

I've yet to try building from the source.

**Comment by Giovanni-Mattucci** [comment]
Unfortunately I've had to resort to doing this for the time being:
```
requirejs: {
      compile: {
        options: {
          baseUrl: '<%= config.jsDir %>',
          mainConfigFile: '<%= config.jsDir %>/config.js',
          name: 'main',
          out: '<%= config.distDir %>/<%= config.jsDir %>/main.js',
          paths: {
            'jquery': 'empty:'
          },
          optimize: 'uglify2',
          generateSourceMaps: true,
          preserveLicenseComments: false,
          onBuildRead: function (id, path, contents) {
              if (id.indexOf('instant-search') === 0) {
                  return contents.replace(/define\(\[\], factory\)/i, 'define("instant-search", [], factory)');
              } else {
                  return contents;
              }
          }
        }
      }
    }
```
I'm doing a string replace on build of instantsearch's define().

Eventually when I migrate to webpack this will be a non-issue, but I wish I could figure out how to make requirejs notice instantsearch and name it appropriately on build.

**Comment by vvo** [comment]
@Giovanni-Mattucci I was more proposing you to name the module in our UMD build for AMD, but maybe that's not the right choice? I must say I never use AMD so I blindy trust webpack to do the right thing.. :D

**Comment by vvo** [comment]
> Not naming the define() is the right way to go

I thought what you wanted was us to NAME it, I wonder if naming our AMD define by using http://webpack.github.io/docs/configuration.html#output-umdnameddefine inside our own build step would make it easier for you? And also if it would break any existing website.

**Comment by Giovanni-Mattucci** [comment]
@vvo well naming it would fix my current implementation, but that would make your module less portable so says require.js documentation :) http://requirejs.org/docs/api.html#modulename generally the optomization tool should do this, but in my case it wasn't adding names for unnamed modules.

With many people moving to webpack though, in the future I'll be using that as well and this will be less of an issue. My above solution is working though going forward :)

**Comment by vvo** [comment]
Nice! Thanks for getting back here
