### ISSUE TITLE
How to trigger event?

### ISSUE THREAD

**Issue by Sammaye** [algolia/instantsearch.js#1431]
Say, for example: I want to trigger the clear filters action on demand how would I go about that? I noticed that the script does not use normal registration of events (or from what the Chrome debugger says at least)

**Comment by vvo** [comment]
Hi @Sammaye could you maybe create a small jsFiddle to show how far you went in term of trying to trigger a click on the clear button programmatically?

Thanks

**Comment by Sammaye** [comment]
I can actually do better: I can give over a URL:

https://nhbs-webapp-sammaye.c9users.io/browse/beta-search?q=&hPP=20&idx=titles&p=0&is_v=1

Basically in the source code you will see:

``` javsascript
$('#navSearchForm .site-search-input').on('keyup', function(){
	console.log($('#navSearchForm .site-search-input').val().length);
	if($('#navSearchForm .site-search-input').val().length <= 0){
		console.log(search);
		$('.btn-clear-all-filters').trigger('click');
	}
});
```

I have checked it gets down to: `console.log(search);` but I inspect the elements in the debugger and their events are empty and I cannot seem to trigger the button's click

**Comment by vvo** [comment]
Indeed jQuery.trigger will not work here since jQuery.trigger only triggers events that were registered through jQuery event handling.

You might have better results by using this: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#Triggering_built-in_events

Or any non jQuery way to trigger a click. Try this and if it does not work you will have to create a [custom widget](https://community.algolia.com/instantsearch.js/documentation/#custom-widgets) and use the [helper](https://community.algolia.com/algoliasearch-helper-js/) inside it.

**Comment by Sammaye** [comment]
Problem is that code is IE 11 and up by that document. Is there anything that support less? I mean we run the js on jquery 1.13 and it seems to work just great so maybe there is a hacky way?

**Comment by Sammaye** [comment]
Ok so actually I misread the document, the old fashioned way (which I had forgotten since using jQuery) works

**Comment by vvo** [comment]
Awesome, can you provide the detailed fix you used? For further reference.

**Comment by Sammaye** [comment]
So, I changed my function to be:

```javascript
var event; // The custom event that will be created
$('#navSearchForm .site-search-input').on('keyup', function(){
	if($('#navSearchForm .site-search-input').val().length <= 0){
		if(document.createEvent){
			event = document.createEvent("Event");
			event.initEvent("click", true, true);
		}else{
			event = document.createEventObject();
			event.eventType = "click";
		}
		event.eventName = "click";
		
		if(document.createEvent){
			document
				.getElementsByClassName('btn-clear-all-filters')[0]
				.dispatchEvent(event);
		}else{
			document
				.getElementsByClassName('btn-clear-all-filters')[0]
				.fireEvent("on" + event.eventType, event);
		}
	}
});
```

**Comment by vvo** [comment]
Thanks!
