### ISSUE TITLE
rangeSlider could really do with a format for the start, middle and end figures

### ISSUE THREAD

**Issue by Sammaye** [algolia/instantsearch.js#1436]
Exactly that, would be good if rangeSlider would have a format option for not just tooltips but also the other values that are shown on it.

An example is using epoch date stamps with the range slider, getting out a step of 1,113,782,400.

**Comment by vvo** [comment]
We are using nouislider, can you check if this works: https://refreshless.com/nouislider/pips/#section-steps?

Thanks

**Comment by Sammaye** [comment]
This looks good though how does instantsearch use nouislider? So for example how would I put 

```javascript
noUiSlider.create(pipsSteps, {
	range: range_all_sliders,
	start: 0,
	pips: {
		mode: 'steps',
		density: 3,
		filter: filter500,
		format: wNumb({
			decimals: 2,
			prefix: '$'
		})
	}
});
```

into the instantsearch?

Do I need to use a specific param to send raw params to nouislider or should it just understand if I slap a new property in the widget defnition of `pips`?

**Comment by Sammaye** [comment]
Using:

```
 search.addWidget(
	instantsearch.widgets.rangeSlider({
		container: '#priceRange',
		attributeName: 'lp',
		tooltips: {
			format: function(rawValue) {
				return '£' + Math.round(rawValue).toLocaleString();
			}
		},
		pips: {
			mode: 'steps',
			density: 3,
			format: function(rawValue) {
				return '£' + Math.round(rawValue).toLocaleString();
			}
		},
		templates: {
			header: 'Price Range'
		},
		cssClasses: {
			root: 'panel panel-default quick-search-facet-panel',
			header: 'panel-heading',
			body: 'panel-body'
		}
	})
);
```

does not work

**Comment by vvo** [comment]
It may just be that those options are from a recent version of nouislider that we do not support. Which option specifically is not working? pips.mode and density should be ok no?

**Comment by Sammaye** [comment]
Not from what I can see.

I just changed density to 5 and it did not work, kept them at 3

**Comment by Sammaye** [comment]
Oh wait, looking at wrong element, though worse, it breaks the actual element

**Comment by Sammaye** [comment]
Ok I actually got it working with:

```javascript
search.addWidget(
	instantsearch.widgets.rangeSlider({
		container: '#priceRange',
		attributeName: 'lp',
		tooltips: {
			format: function(rawValue) {
				return '£' + Math.round(rawValue).toLocaleString();
			}
		},
		pips: {
			mode: 'positions',
			values: [0,50,100],
			density: 3,
			format: wNumb({
				decimals: 0,
				prefix: '£'
			})
		},
		templates: {
			header: 'Price Range'
		},
		cssClasses: {
			root: 'panel panel-default quick-search-facet-panel',
			header: 'panel-heading',
			body: 'panel-body'
		}
	})
);
```

**Comment by vvo** [comment]
AWESOME! Thanks for putting the answer back here.
