### ISSUE TITLE
Cannot add a min value to the range slider without a max

### ISSUE THREAD

**Issue by Sammaye** [algolia/instantsearch.js#1438]
When I add only a min value an error is returned saying range is not numeric

**Comment by vvo** [comment]
I just tried in our dev app (https://github.com/algolia/instantsearch.js#development-workflow) and it worked well. Could you create a small jsFiddle reproducing the issue? Thanks

**Comment by Sammaye** [comment]
Got one here https://jsfiddle.net/Sammaye/5dqsx47g/1/ I am not using the dev version of the files and maybe that is the problem

**Comment by vvo** [comment]
Hi @Sammaye you need to use the latest version of instantsearch, you were currently using 1.5.1, fixed your example: https://jsfiddle.net/5dqsx47g/2/

**Comment by Sammaye** [comment]
Ok thanks
