### ISSUE TITLE
Template defaults for hits

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#144]
Right now, you can't use the hits widget without actually passing a template for both the results and empty results. We could have `'No results` for empty and `function(h){return '<pre>'+JSON.stringify(h, null, 2)+'</pre>';}` for the result. It's not ideal but let the user start immediately.

**Comment by vvo** [comment]
There's now a default template which is `hit: 'Object #{{objectID}}, this is the default `hits` template, you should provide one'`, JSON.stringify would be interesting.

**Comment by redox** [comment]
:+1:  for the default JSON-stringified version.

**Comment by Jerskouille** [comment]
:+1: for the `JSON.stringify` too.

**Comment by pixelastic** [comment]
I'm working on a cleanup of the hits widget, I'll add this as well.

**Comment by redox** [comment]
@pixelastic still on it?

**Comment by pixelastic** [comment]
Was already done, sorry.
