### ISSUE TITLE
[jsDelivr]: push the sourcemap

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#145]
https://github.com/jsdelivr/jsdelivr/tree/master/files/jquery/2.1.4 jquery is doing it so let's do it :)

TODO:
- [ ] generate and push the sourcemap in jsdelivr (only need to do a release)
- [ ] check that the sourcemap is downloaded

**Comment by bobylito** [comment]
kewl!

**Comment by vvo** [comment]
Is downloading the .map an automatic behavior from browsers or do we need to do something to indicate where it is?

**Comment by pixelastic** [comment]
The main file should contain a comment referencing the filemap location. Something like `//# sourceMappingURL=bundle.js.map`.

Tools that generate sourcemaps usually update the original file as well. We'll just have to push both to jsdelivr.

**Comment by Jerskouille** [comment]
Successfully tested.
