### ISSUE TITLE
[SearchBox] on Firefox, the Algolia Logo is not displayed on the poweredBy

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1451]
Works on Chrome and Safari. 

![image](https://cloud.githubusercontent.com/assets/6885378/19566469/b4c14eb8-96ea-11e6-8c94-e1feb96bf3d3.png)

**Comment by bobylito** [comment]
:(

**Comment by vvo** [comment]
I think the underlying svg data needs to be encoded, see http://stackoverflow.com/questions/30733607/svg-data-image-not-working-on-firefox

**Comment by mthuret** [comment]
Great, it works :) see #1452
