### ISSUE TITLE
Implement good looking default style for widgets

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1456]
From recent discussions, we decided that our default (connected) widgets should provide a default style that is good looking by default.

Right now we were on a track were only the SearchBox had some "good" default styling and behavior. But we should push it further. We are all convinced that the connector API is good enough and so easy to use that there's no need to provide only a very light style for our own widget, we can be opiniated here.

Steps to get there:
- [x] create a raw examples using all our widgets (or use storybook?)
- [x] summon @LukyVj to help us come up with a consistent style
- [x] stop documenting theme= props, the only public API is now CSS class names
- [x] rewrite stories/examples to use class names instead of the theme props
- [x] document all available CSS class names for every widget

**Comment by bobylito** [comment]
\o/
