### ISSUE TITLE
Replace our RangeSlider with airbnb/rheostat

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1457]
For now, there's no way we are gonna make a better Slider that airbnb/rheostat. So the best option is to make our RangeSlider be a thin wrapper on top of airbnb/rheostat and make it look good, consistent (#1456).

We also discussed that we could maybe just not include a default slider, but for our set of widgets that would look pretty weird to not have a RangeSlider widget by default. Even if connecting one is very easy.

**Comment by mthuret** [comment]
Using Rheostat as our default implementation will introduce some inconsistencies between our classnames and theirs. 
Trying not to complicate things before the first release, I propose that we do not provide a Slider but instead explain how to connect easily to an existing one. 

As for the design (#1456) we can use Rheostat to have a complete example.

**Comment by vvo** [comment]
Works for me as we discussed if we still manage to have a RangeSlider* item in the widgets/ documentation that says "Since there are a lot of already existing sliders, we did not include one by default but here's how to connect .."
