### ISSUE TITLE
[Menu] No highlight for selected value by default

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#146]
When an item is selected in the menu widget, there is no visual clue that anything is selected.

**Comment by Jerskouille** [comment]
To me a safe bet would be to add an `em` tag around selected options in the `refinement-list` and `menu` templates.

**Comment by vvo** [comment]
The default menu widget can embed em tags by default that should do it

**Comment by bobylito** [comment]
`em` or `strong` would work yes I guess :)

**Comment by pixelastic** [comment]
We should add a CSS class to the current selected element instead of adding markup to it. This will fall under the whole BEM refactoring that is planned.

**Comment by vvo** [comment]
Indeed but then the default template will still not emphasis what's the selected element. We can have `<em>` AND a bem class added to it?

Can you explain what do you plan for #47 (inside the issue). So that we can see what we are going to do exactly.

**Comment by pixelastic** [comment]
We are already adding custom CSS in other widgets (poweredBy for example). We should do the same here for the critical stuff (like emphasis on default templates). Adding a new markup element makes all CSS rules more complex and is not needed.

**Comment by vvo** [comment]
linked with #47 and #160

**Comment by pixelastic** [comment]
We are adding a `ais-widgetname--item__active` to the active item.
