### ISSUE TITLE
How can I make an object a Facet?

### ISSUE THREAD

**Issue by hadijaveed** [algolia/instantsearch.js#1462]
##### Sample Object:

```
{
    "productName": 'some product',
    "brand": {
         "name": "some brand",
         "id": "123",
         "url": "www.somebrand.com"
    }
}
```

Is there any way I can make facet like that. I do understand the concept of facet which is not for something like that. But instead of making a separate index I want to keep one index and get the brands that are matched with the product name

**Comment by vvo** [comment]
@hadijaveed This is doable but you won't be able to retrieve the id and url properties sadly. cc @Shipow I think at some point you wanted to introduce the concept of facet metadata right? Being able to retrieve some metadata of a matching fact.

**Comment by hadijaveed** [comment]
@vvo thank you for your response.

**Comment by vvo** [comment]
This is not yet available in the engine sorry.
