### ISSUE TITLE
useHash:true makes it render slower.

### ISSUE THREAD

**Issue by semeano** [algolia/instantsearch.js#1478]
If I use the _useHash_ option under _urlSync_, the results renderization gets really slow.

Here's **without** _useHash_:
![without useHash](http://g.recordit.co/A1n7bNNLN7.gif)
(video: http://recordit.co/A1n7bNNLN7)

And **with** _useHash_:
![with useHash](http://g.recordit.co/8bxwVUGy9B.gif)
(video: http://recordit.co/8bxwVUGy9B)

**Comment by vvo** [comment]
Hi @semeano, is the "without useHash" case still using urlSynchronisation? Indeed it may be that in some situations, updating the hash too often leads to bad performance.

**Comment by semeano** [comment]
Hi @vvo,

Yes, it is still using urlSync.
The only difference between those two is just the useHash flag.

**Comment by bobylito** [comment]
@semeano Which browser are you using for your tests? On which platform / OS?

**Comment by semeano** [comment]
Sorry, should have mentioned on the first post.

Chrome 54.0.2840.71 (64-bit)
Mac OS X 10.9.5 (Mavericks)

**Comment by semeano** [comment]
Just a suggestion. Instead of updating the url on every keystroke, why not use the urlSync.threshold parameter to affect the url updating time too?

**Comment by vvo** [comment]
> Just a suggestion. Instead of updating the url on every keystroke, why not use the urlSync.threshold parameter to affect the url updating time too?

It's tricky, because then you have an interface that gets updated at every keystroke but the url itself is only updated after 700ms, which results in a visual distraction if you already started reading the webpage (we tried it, not convincing).

Can I ask you the reason for using the hash instead of the url? Ultimately I think we will remove the hash option because it causes too much issues.

**Comment by semeano** [comment]
I was having some issues. Sometimes if I went back to the results page (i.e. homepage > results page > product page > back to results page), the url would stop sync.

But right now I'm not using urlSync anymore.

**Comment by vvo** [comment]
We'd better try to fix those non working urlSync classical issues before we try to fix the performance of the hash based one that we will eventually drop support of.

If you are able to reproduce the issue, please open a new one, thanks a lot
