### ISSUE TITLE
Formatting imported data

### ISSUE THREAD

**Issue by spindriftwebs** [algolia/instantsearch.js#1480]
Hi, I'm a complete newbie to Algolia but loving what I see so far.  I have a simple faceted search working for 4000 products but I have an issue where the price is being displayed in alphabetical order, not numerical.  I understand this is because the price index is a string and not an integer.

I've used the instructions here: https://www.algolia.com/doc/guides/indexing/import-synchronize-data/php to import my data but am really struggling on how to tell the API to import my price field as an integer.

Any help would be much appreciated.  Thanks.

**Comment by vvo** [comment]
I guess you fixed this @spindriftwebs, maybe you can add a small comment on how you fixed it for future reference?
