### ISSUE TITLE
meta: Add issues and PR templates

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1481]
In order to help people contribute in a more consistent way, we could implement templates for issue and PR's.

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by vvo** [comment]
Especially useful for issues creation yes to emphasis on reproducibility.

As for PR I never encoutered PR templates, not sure what fits in it.

**Comment by bobylito** [comment]
Thanks for handling that @vvo 

As a sidenote, for PR it's useful to remind that's it's cool to have a description, screenshot and emojis ;)

**Comment by vvo** [comment]
> As a sidenote, for PR it's useful to remind that's it's cool to have a description, screenshot and emojis ;)

Indeed, we can add it too then!

**Comment by vvo** [comment]
(adding the PR template)
