### ISSUE TITLE
Map search phrase to different indexes

### ISSUE THREAD

**Issue by Xaptor** [algolia/instantsearch.js#1485]
Hi,

i am looking to create a search where the user searches "fast car" and the response is ordered by speed in descending order with all cars where max_speed (int) >=180? Another example is a user searches for "cheap women shoes" and get all women shoes with a price lower than 50 ordered by price ascending.

What's the best way to implement this behaviour? My first idea was to create a master search index in front with a few documents for fast/slow, cheap/expensive, dark/light, etc. These results map to the real indexes with their own order. But there are some disadvantages like many indexes and more operations which result in higher cost.

I am very excited to receive your ideas.

**Comment by vvo** [comment]
Hi @Xaptor that's a very good usecase.

Right now there's no easy way to do this, we do not have query interpretation at Algolia level in the API. So we would have to find ways to do it on the frontend and update the filters accordingly.

We are currently focused on releasing a first working version of react-instantsearch, once we get that out we will be able to think about advanced use cases like yours.

Please allow us two weeks before we can come up with another response. Thanks

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
