### ISSUE TITLE
IE8 not even supported with polyfill

### ISSUE THREAD

**Issue by Sammaye** [algolia/instantsearch.js#1491]
Taking your example https://community.algolia.com/instantsearch.js/examples/media/ it is likely a small strict error or something.

As to why IE8: since Bootstrap 3 still supports it and many e-commerce sites still have to support IE8 currently.

**Comment by vvo** [comment]
Hi @Sammaye unfortunately we do not officially support IE8 and won't spend time on it. This browser version is deprecated. https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by Sammaye** [comment]
I realise it is not officially supported but the polyfill fully supports IE8 and technically it should just be standards error using the polyfill, not a full on functionality error, so was kind of hoping maybe a quick look into it would be allowed, but ok

**Comment by vvo** [comment]
Unfortunately I don't even have anymore any VirtualBox capable of running IE8, those went out of service at some point and I never managed to get them back up.

Most of my debugging sessions with old IES are taking a LOT of time with little return on investement for IE8.

You can have a try if you want with https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/.

Thanks for your understanding.

**Comment by Sammaye** [comment]
I have the VMs but unfortauntely I just don't know enough about about react, in  way this is the problem with modern web development; so many tools no one can possibly know them all

**Comment by vvo** [comment]
@Sammaye for this kind of issue there's little chance it's linked to React completely. As a first try you could use the IE8 debugger to see what is the failing JavaScript call. That would help already.

Are you using instantsearch lite?

**Comment by Sammaye** [comment]
I am mostly using the default one here //
cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.js

**Comment by vvo** [comment]
ok then you should be safe and something else is broken

**Comment by Sammaye** [comment]
Nah, since the example https://community.algolia.com/instantsearch.js/examples/media/ also runs that and doesn't work.

But we have since decided not to support IE8 now and just take the plunge

**Comment by vvo** [comment]
> But we have since decided not to support IE8 now and just take the plunge

Awesome decision, way to go as from our POV

**Comment by Sammaye** [comment]
TBH my POV is to drop all IE but so many, especially from China and government organisations buy on the platform.

Next is to try IE9 and see if it works on that
