### ISSUE TITLE
Being able to change the order of appearance of links in the sidebar

### ISSUE THREAD

**Issue by LukyVj** [algolia/instantsearch.js#1496]
Espacially for guides, I'm forced to add an ID to the header of the `guides.md` in order to not break the JS. 

If I do so, the first link should be "intro" but strangely, it's in 3rd position, so I'm forced to rename the page "Guides Introduction" in order to make it appear first in the sidebar list.

**Comment by mthuret** [comment]
I used the navWeight to make the intro page appears first.
