### ISSUE TITLE
Refinements via Query String Documentation

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [algolia/instantsearch.js#1506]
There is no documentation on how to modify the facet filters via query string:
`facet=Category,Value`

It would be useful to detail the syntax for how to set facet refinements via query string.

**Comment by vvo** [comment]
Hi @Giovanni-Mattucci there's is no way with Algolia to set filters via the query string. Those are configured via different parameters. Ultimately what are you trying to achieve, what's your underlying usecase?

Thanks

**Comment by Giovanni-Mattucci** [comment]
The use-case would be sending the user to an Algolia Instant search page with predefined filtering and faceting. This can be done for search parameters `q=searchterm`. And I'm pretty sure we can do the same with all sorts of filtering can't we? `fR[category][0]=value` and `dFR[facet]=value`. So having that detailed might be useful, I know I would have found it useful.

**Comment by vvo** [comment]
Ok understood, we have a FAQ about it (easy to miss, no worries): https://community.algolia.com/instantsearch.js/documentation/#default-filters

Let me know if that's sufficient.

**Comment by Giovanni-Mattucci** [comment]
Yes I referenced that, but eventually what I needed was this: 
https://community.algolia.com/algoliasearch-helper-js/reference.html#searchparameters

And from there I could figure out the values for search parameters:
`idx, fD, dFR` etc.
Is there somewhere that defines all the different mapping values you can set?
```
urlSync: {
                trackedParameters: ['query', 'page', 'attribute:*'],
                mapping: {
                    p: 'page',
                    q: 'search',
                    fR: 'facetRefinement',
                    dFR: 'disjunctiveFacetRefinement'
                    //what else?
                }
            }
```

**Comment by vvo** [comment]
Full reference: https://github.com/algolia/algoliasearch-helper-js/blob/39bec1caf24a60acd042eb7bb5d7d7c719fde58b/src/SearchParameters/shortener.js#L6

**Comment by bobylito** [comment]
Closing for now.
