### ISSUE TITLE
Bad rendering of hero and logo

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1512]
![bug](https://cloud.githubusercontent.com/assets/123822/20010261/c152dcaa-a2a7-11e6-9ba3-a0d0cbc2a922.gif)

**Comment by vvo** [comment]
Google chrome Linux

**Comment by vvo** [comment]
seems to be a recent upgrade on my "system" (linux). will try to see what's wrong

**Comment by vvo** [comment]
The mix-blend-mode prop is triggering this bad behavior on my machine, wonder if there are compatibility issues here.

**Comment by vvo** [comment]
Seems like it's also not supported on IE EDGE which is a browser we do support, @LukyVj do you think there are other ways to accomplish what you want without mix-blend-mode?

**Comment by LukyVj** [comment]
Omg, yeah, you did well! 

The support is not that perfect, yet :) 

![](https://puu.sh/sdwkQ/932ee02d90.png)

**Comment by vvo** [comment]
Yep :p

**Comment by vvo** [comment]
Assigned to you, close it when we found another way
