### ISSUE TITLE
Markdown link are not taking into account if inside a props table

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1517]
![capture d ecran 2016-11-07 a 15 20 29](https://cloud.githubusercontent.com/assets/6885378/20060930/d2b835b4-a4fd-11e6-8a1a-340fceb87529.png)

**Comment by vvo** [comment]
Solved right?

**Comment by mthuret** [comment]
Yes, I added markdown for props right now.
Later it may be necessary elsewhere, or for style consistency. (there are tables also for for classnames/translations).
