### ISSUE TITLE
use ES6 import/export

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#152]
- and enforce it with eslint

**Comment by bobylito** [comment]
Benefits?

**Comment by pixelastic** [comment]
Really easy and future-proof syntax.

**Comment by vvo** [comment]
> Benefits?

I do not see any direct benefit. The only interesting part is porting our code to an import/export pattern that is now part of ECMAScript instead of relying on `require` that is not part of the language.

BUT we already use things that are not part of the language (like the mighty css loading technique) so this is not true to say we only use standard things :).

**Comment by vvo** [comment]
Doable, but some require cannot be ported to import for now: decorators, they are placed somewhere in render() to be testable (mockable with rewire).

We can get out of it if we import on top but decorate in render with a simple guard DecoratedRefinementList = DecoratedRefinementList || decorate(RefinementList)

**Comment by pixelastic** [comment]
Could you link to an example of a decorator imported inside `render`? I don't think I get the issue, I had a look at a few widgets and decorators are `require`d at the top of the file.

**Comment by vvo** [comment]
Sorry this was not in render but in main instantiation: https://github.com/algolia/instantsearch.js/blob/e05cbefd5fdff9e6f2fda869e8aa21194d1de2d4/widgets/menu/menu.js#L49

This weird notation is done to allow unit testing, otherwise the HOC cannot be mocked..

**Comment by vvo** [comment]
Quick win, doable, we then need to ensure to disallow using require and force import

**Comment by vvo** [comment]
Mostly done, will be released
