### ISSUE TITLE
connectCurrentRefinements API

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1532]
This connector is used to be able to display the current refinements, and also to be able to clear them (one by one or every refinements).

To do that, the user has access to a prop called items, which follow this structure: `array.<{clear: function, label: string}>. The label follow the format 'facetName: facetValue'.`

So let's say we have a refinementList with three colors checked, you will have something like:
`[{"label":"colors: Black"},{"label":"colors: White"},{"label":"colors: Black-brown"}]` (stringify version, each object has also the clear function). 

The format 'facetName: facetValue' corresponds to the one declared in the refinementList metadata. 

While it's fine if the CurrentRefinements widget display the label directly this way (if we think it's the best way to display them), I think that for the connector, it's maybe not the easiest structure to manipulate. What I suggest, is that we don't provide a label and instead have a new key `values` with a structure like:  

`array.<{clear: function, values: array.<facetName: string, facetValues: array<string>}>.`

Also, the clear function is used internally by the refine function of the connector. If the user look at the item structure it may be confused and try to use that instead of the refine function to clear the refinements. Maybe we could rename it to '_clear', to make it clear that it's private? 

What do you think?

**Comment by mthuret** [comment]
@bobylito @vvo any opinion ? :)

**Comment by vvo** [comment]
Thanks for summing it up, what about we provide: `{attributeName, currentRefinement}` so that we are in line with the connector API?

About the `clear` method, denoting private is already a good move, I wonder if we could go further and not pass it down somehow. But given the current search state internals this might not be feasible.

**Comment by mthuret** [comment]
With your structure it means that we can have several objects with the same attributeName right?

**Comment by vvo** [comment]
Do we want to completely remove the `label`? All our `items` based connectors always provide `label` as a way to convey "This is what we recommend displaying by default"

**Comment by mthuret** [comment]
Indeed I add the label back. _clear must be for each currentRefinement. So in the end, currentRefinement is an object with a label (the currentRefinement value), and a _clear function. 
Is `label` right ? Or maybe `value` ?

**Comment by vvo** [comment]
A bit lost here can you put an example object so it's easier to understand where we are going?

As for `label` vs `value`, our rule for now is that anything that we consider "for display" is named `label`, `value` being a value to refine.

Example for refinementList:

```js
{
items: [{
  label: 'Black',
  count: ..
  value // state to be triggered, don't care about the internal value, just call refine(value)
}],
refine,
currentRefinement
}
```

So ultimately even for CurrentRefinement, if value was a function, we could have the exact same structure and add some metadata for the user to recompose the label if he wants to?

proposal:

```js
{
  items: [{
    label // we consider and use this for display
    value // this is a function that you will pass to refine(value), you actually do not care about the internal representation
    attributeName // metadata for the user
    currentRefinement // metadata for the user
  }],
  refine
}
```

With this we have something in line with the other list connectors. What do you think?
