### ISSUE TITLE
Bug: Hit not re-rendered when you modify the data in transformData

### ISSUE THREAD

**Issue by kokliKo** [algolia/instantsearch.js#1538]
When making two queries that return the same hit, but this hit is handled differently in transformData between the first and second query, the hit component won't be re-rendered.

Apparently, that comes from the fact that `shouldComponentUpdate` is based on the data retrieved by the API instead of the data sent after `transformData`.

An easy way to reproduce this is to add a timestamp to the hit object in `transformData`, and display it in the component.

**Comment by vvo** [comment]
We have found a solution for that: we would need to actually call transformData BEFORE it's passed to the Template component: makes sense, you want to do a shouldComponentUpdate on data that is fully computed.
