### ISSUE TITLE
Collapsed option and url synchronisation

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#1543]
When you use the collapsed option, if you refine a widget then reload the page, the widget will not be expanded even if it has some refinements.

Should we add an option for this? Should we make it the default behavior in the future?

**Comment by bobylito** [comment]
Just to be sure I understand @maxiloc you would like the following behavior: in a given page with a widget that has the collapsed option set to true, override the collapse if there are some refinements set for this widget? Would it be only for the initial load, or also at any time (as long as the widget has refinements we can't collapse it)?

**Comment by maxiloc** [comment]
Not really :), more: in a given page if I have a widget that is collapsed, I expand it, refine and refresh the page, I expect to have the refinement still there but also the widget expanded.
My bad the explanation was not good.

**Comment by bobylito** [comment]
I think I understand the same thing I understood the first time (but failed to reformulate it). I think it's quite nice of a behaviour!

**Comment by Haroenv** [comment]
Since the panel widget, you control the `collapsed` yourself, and can base it on applied refinements, so this is fixed.
