### ISSUE TITLE
Feature request: Ajax loading of results / endless scroll

### ISSUE THREAD

**Issue by synonymous1984** [algolia/instantsearch.js#1548]
It would be nice to be able to switch from paginated results to a endless scroll list of items (automatically load on page scroll).

**Comment by bobylito** [comment]
Hi @synonymous1984 thanks for taking the time to fill in this issue. Can you explain how it could work UX wise? What is the trigger of such switch of behavior?

**Comment by synonymous1984** [comment]
Hi @bobylito! You can read a study about infinite scroll at smashing magazine. Maybe a hybrid version is also a good idea: https://www.smashingmagazine.com/2013/05/infinite-scrolling-lets-get-to-the-bottom-of-this/

**Comment by vvo** [comment]
Heads up! There's no an infinite hits widget: https://community.algolia.com/instantsearch.js/documentation/#infinite-hits
