### ISSUE TITLE
refinementList: limit should be 1000 by default

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#155]
Current refinementList limit is always 100 which will lead to incomprehension, we should show all the facet values by default since the limit is already in the API server: 1000

So basically if no limit is passed there's nothing to do we just use the index settings. If a limit is passed then we limit it programmatically after receiving the data.

**Comment by redox** [comment]
Hmmm, I would rather go for 10 :) It doesn't make sense to display too much values. Also, what could be cool would be to set the `maxValuesPerFacet` query parameter to `max(all limit options)`.

**Comment by vvo** [comment]
> It doesn't make sense to display too much values.

agree but I prefer the user to see that there's a lot of values and he then has to limit it if he wants to. Rather than having himself thinking there's a bug somewhere because he cannot see all the values.

**Comment by redox** [comment]
Yes OK, that makes sense.

**Comment by agwisniewska** [comment]
Hi, 

I guess I'm experiencing an issue with this, take a look at the screenshots please:

![Screenshot 2023-03-02 at 13 34 48](https://user-images.githubusercontent.com/16926778/222430940-56963475-79d1-41f9-bb10-bfe63618a675.png)
![Screenshot 2023-03-02 at 13 34 57](https://user-images.githubusercontent.com/16926778/222430941-49aedd2d-24f5-4803-827f-87a3413560c6.png)
![Screenshot 2023-03-02 at 13 34 23](https://user-images.githubusercontent.com/16926778/222430932-c567973a-b565-4023-be51-497eb88d88da.png)

As you can see I have the list of country_iso as my facet values, and there are around 200 countries, so I set this limit, but all I can see both in the dashboard plus on the UI side (with Vue InstantSearch lib) is 100 values. 

Did I miss something?
