### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1560]
Some of those we may or may not want to fix them, just using the website and writing what seems missing.
- [x] No hover effect on any link in header
- [x] Website width is still very narrow compared to https://community.algolia.com/wordpress/customize-autocomplete.html
- [x] Some width break points have no left navigation showing, and you cannot access it
- [x] Hover effect on nav triggers line breaks if length is close to limit <details>![nav](https://cloud.githubusercontent.com/assets/123822/20346414/254c4446-abfc-11e6-923e-b7f9e596eca2.gif)</details>
- [x] Every first line of code snippets has a indent on it <details>![2016-11-16-125028_503x51_scrot](https://cloud.githubusercontent.com/assets/123822/20346227/4977d0de-abfb-11e6-8889-a934edfd4120.png)</details>
- [x] Examples page title is "examples introduction" should just be "examples"
- [x] Examples page should be designed a bit, a simple page showing screenshots as squares would do it (no need for examples introduction page)
- [x] Left nav issue (browser width: 624px)<details>![leftnav](https://cloud.githubusercontent.com/assets/123822/20346557/09e3307e-abfd-11e6-8ca9-a3da16361bee.gif)</details>
- [x] Full width API navigation dropdown can't be closed when clicking away
- [x] big atom logo does not scale with breakpoints, example: <details>![](https://cloud.githubusercontent.com/assets/123822/20347209/5373e564-ac00-11e6-8966-c56238035e31.png)</details>
- [ ] Left nav issue when going from small window to big window (left nav is messed up)<details>![2016-11-16-130411_1382x787_scrot](https://cloud.githubusercontent.com/assets/123822/20346587/320b8f06-abfd-11e6-986e-405ca5cab310.png)</details>
----- 

- [ ] Properly indent code sample <details>![](https://puu.sh/sl9KS/8d3f59161d.png)</details>

----- 
### done 
```diff
- No hover effect on any link in header
- Website width is still very narrow compared to 
- Some width break points have no left navigation showing, and you cannot access it
- Hover effect on nav triggers line breaks if length is close to limit
- Every first line of code snippets has a indent on it
- Examples page title is "examples introduction" should just be "examples"
- Examples page should be designed a bit, a simple page showing screenshots as squares would do it (no need for examples introduction page)
- Left nav issue (browser width: 624px)
- Full width API navigation dropdown can't be closed when clicking away
- Big atom logo does not scale with breakpoints
```

### doing 

```diff
+  Left nav issue when going from small window to big window (left nav is messed up)
````

<p align="center">
  <b>⚡️ Incoming Awesomeness ⚡️</b>
</p>

**Comment by LukyVj** [comment]
hey @vvo can you explain me more about that one please ? 
>  Full width API navigation dropdown can't be closed when clicking away

**Comment by LukyVj** [comment]
@Vvo For this one : 
> Left nav issue when going from small window to big window (left nav is messed up)

I don't think people will actually resize the browser window ? I will see what I can do tho.

**Comment by LukyVj** [comment]
>  Examples page should be designed a bit, a simple page showing screenshots as squares would do it (no need for examples introduction page)

@vvo But then I can remove the sidebar right ?

**Comment by LukyVj** [comment]
@mthuret @bobylito @vvo Where can I find the source of the code samples ? To fix the last task : 
> Properly indent code sample

**Comment by mthuret** [comment]
@LukyVj It depends: if it's one guide/getting started, you'll find them directly on the md files. Otherwise for API/Components it's directly on the .js file.

**Comment by LukyVj** [comment]
@vvo can't fix the "before last" task : 
> Left nav issue when going from small window to big window (left nav is messed up)

Can't reproduce it

**Comment by vvo** [comment]
Iteration is done
