### ISSUE TITLE
Avoid id collisions.

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1572]
Right now we use facets as ID's for internal widget identification. This might break when a facet is named with the same name as a static id (like pager / sortBy and so on).

Proposed solution: namespace the name of the facet with a key specific to the type of widget.

**Comment by vvo** [comment]
This is a discussion that could start drafting the shape of the eventual instantsearch-core.

**Comment by vvo** [comment]
We could right now do the obvious as per @bobylito, move the state from:

```js
{
  page: 0,
  attributeName: {
    // eventual refinements
  }
}
```

to:

```js
{
  page: 0,
  menu: {
    attributeName: {
      // eventual refinements
    }
  },
  refinementList: {
    attributeName: {
      // eventual refinements
    }
  }
}
```

**Comment by vvo** [comment]
moved to #1581
