### ISSUE TITLE
Generate a single CSS theme file and ask the user to load it

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1575]
Remove any CSS infrastructure and themeable code.

**Comment by vvo** [comment]
Hi @adlenafane I saw you :+1:, can you provide more context on why do you think what we want to do here is good? (Thanks!)

**Comment by adlenafane** [comment]
Hi @vvo, it's mainly related to https://github.com/algolia/instantsearch.js/issues/1489 in my situation. I'd like to use react-instantsearch with a server rendering first (I use https://www.reactstarterkit.com/) and I have an issue with `insert-css`.
I had a quicklook of the themeable and find it quite invasive in all components

**Comment by vvo** [comment]
Allright perfect then it's were we are aimed at, reducing the styling API surface to only CSS class names and exposing the generated CSS in a way so you can insert it.

**Comment by vvo** [comment]
Here are the steps I identified and propose to do:

  - apply CSS classes manually
  - remove theme, themeable
  - keep individual CSS files
  - make the theme a separate package (allows updating the theme without having to update react-instantsearch)
  - add necessary build step to allow
    import theme from react-instantsearch-themes-algolia
    insertCSS(theme)
    npmcdn CSS file
  - update documentation to point to npmcdn CSS file, show
  how to load it via npm too
  - update dev env to load default theme
