### ISSUE TITLE
contribution: check PR is done on develop

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#158]
We should ensure that our PRS follows this:
- [ ] pull request is done on develop

Travis is providing the targeted branch in env variable "TRAVIS_BRANCH" when in a PR.

**Comment by vvo** [comment]
Number of times this led to a "bad" merge: 1

**Comment by pixelastic** [comment]
What about adding checks on the jsdoc as well? Checking that we have jsdoc on all our widgets and that it matches the arguments. I think ESLint have rules for that through a plugin, or maybe try [jsdoced](https://github.com/jeromeetienne/jsdoced.js)

**Comment by vvo** [comment]
> I think ESLint have rules for that through a plugin

Yes we could start with an ESLINT check
