### ISSUE TITLE
Define and implement final shape of the state

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1581]
- [x] separate facet names from the root of instantsearch state to avoid ID collisions
- [x] document instantsearch state in a GUIDE
- [x] explain where to find state of a widget in instantsearch state in every widget doc
- [x] stop using minified tokens (p, q), this is the responsibility of state synchronisation

```js
{
  page: 0, // any widget handling a single parameter that is a direct mapping to an Algolia REST parameter should put the parameter at root level
  hitsPerPage: 10, // same here
  query: 'a', // same here, we use `q` I believe today, this needs to be changed, there's no reason to use minified parameters in the full state shape
  menu: {
    attributeName: 'refinement'
  },
  hierarchicalMenu: {
    attributeName: 'refinement'
  },
}
```

**Comment by mthuret** [comment]
@vvo, @bobylito: Here is an example of state with all of our connectors used. Is everything ok for you? 

```json
{
  "range": {
    "price": {
      "min": "200",
      "max": "500"
    }
  },
  "refinementList": {
    "colors": [
      "White",
      "High gloss gray",
      "Black-brown",
      "High gloss white",
      "Walnut effect"
    ]
  },
  "hierarchicalMenu": {
    "category": "Bathroom"
  },
  "hitsPerPage": "2",
  "menu": {
    "type": "High cabinet with mirror door, black-brown"
  },
  "multiRange": {
    "price": "100:500"
  },
  "toggle": {
    "materials": "on"
  },
  "sortBy": "index_name",
  "query": "chair",
  "page": 2
}
```

**Comment by vvo** [comment]
For a first iteration, this looks good. We will iterate if needed on it. go!

**Comment by mthuret** [comment]
It seems that only `toggle` as a state that differs from the format asked for `defaultRefinement`. 
state is `on` or `off` and `defaultRefinement` is a simple boolean. 
Do we want to change that?

**Comment by vvo** [comment]
> It seems that only toggle as a state that differs from the format asked for defaultRefinement.
> state is on or off and defaultRefinement is a simple boolean.
> Do we want to change that?

Yes this is not consistent right?

**Comment by vvo** [comment]
State for toggle should be 1 or 0 too, not "on" "off", "on" and "off" could be non relevant token givent the attribute name manipulated.
