### ISSUE TITLE
URL Routing: TypeError: Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1583]
I'm following URL Routing tutorial: https://community.algolia.com/instantsearch.js/react/guides/advanced-topics.html#url-routing

But I had this error:

```
TypeError: Cannot read property 'params' of undefined
ProxyComponent.render
webpack:///./~/react-router/lib/withRouter.js?:51:26
```

I suppose that is somethings related about how to setup react-router.

**Comment by mthuret** [comment]
Hi @Kikobeats!

This guide shows an example of url sync with [react-router](https://github.com/ReactTraining/react-router) but it assumes it [has already been configured](https://github.com/ReactTraining/react-router#whats-it-look-like). If you did configure react-router, maybe you can share some code samples?

Also did you add the react-router dependency only to introduce the url synchronization? If you won't use react-router other features, maybe you can simply use another solutions.
For instance, on our examples I simply use [the browser history api](https://github.com/algolia/instantsearch.js/blob/v2/docgen/src/examples/urlSync.js).
Another solution would be to use the [history library](https://github.com/mjackson/history). react-router uses it under the hood. 

Also, maybe we should update the guide to make it clearer that it exists different solutions based on different needs.

**Comment by Kikobeats** [comment]
hey,

I only read the Algolia guide because I hadn't previous `react-router` knowledge, so yea, looks that I need configure it first 😅.

IMHO, could be nice update the guide to setup URL Routing from the scratch, like how URL routings worked before beta-15

**Comment by vvo** [comment]
@marie is writing a full example that we will link from the guide to do just that

**Comment by vvo** [comment]
guide is done, will be released

**Comment by Kikobeats** [comment]
yay! Good job!
