### ISSUE TITLE
feat(error handling): add an `error` event

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#1585]
**Do you want to request a *feature* or report a *bug*?**
It would be good to have an `error` event triggered by instantsearch.js when an API/network error occurs.

**What is the current behavior?**
Right now there's no (official) way to react to any error form Algolia's side

**What is the expected behavior?**
Having the capability to register a handler, something like `search.on('error', (err) => { ... })`

**Comment by bobylito** [comment]
Would it be ok if we just forward the `error` even from the helper?

**Comment by olance** [comment]
I'm not sure we'd need more actually!
