### ISSUE TITLE
feat('error handling'): Add a SearchError widget

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#1586]
We should provide a widget to allow devs to display an error message to their users when something's gone wrong internally (network error/API error).

Not sure yet about the interface/options it should have... any ideas @vvo?

**Comment by bobylito** [comment]
I think it's good to have a widget for errors. However I would (as a developper) like to have a way to integrate such error feedback in my programmatic js (to implement popups logic or conditionnally display part of an instantsearch UI), which seems awkward with a widget. How do you think it could work @olance ?

**Comment by olance** [comment]
@bobylito coupled with the event in #1585, do you think you'd need more?

**Comment by bobylito** [comment]
Do we need both? How the use cases for each distinguishes?

**Comment by olance** [comment]
I think @vvo sees #1585 as a quick fix for the fact that we currently have no easy error handling in instantsearch.js... and the widget as a nice/convenient way to display an error when you're not doing too low-level things.

At least that's how I see it...
To me it's kind of the same as having a `render` event and a `hits` widget :)

**Comment by bobylito** [comment]
Humm not really the `render` event let you do stuff at a given time. The `hits` widget let you display results...

Ok for letting you display an error message with a declarative API using a widget 👍

**Comment by olance** [comment]
Hmm well wouldn't the `error` event let you do stuff at a given time (ie. error occurred) while the `error` widget would let you display errors?

Not trying to troll here but I don't see your point!

**Comment by vvo** [comment]
As for a default Error widget:

I see it as a developer tool rather than a production tool. In a production env Algolia is supposed to always work. The only generic message we could display would be "The search functionnality is not working, please try to reload your browser" (or something like that). And this message would probably never be shown (but if someone kills both of our DNS providers).

As as developer I would like to see the actual error message inlined, that would help me debugging things easily if my devtools are not opened and the API had an error.

```js
search.addWidget(instantsearch.widgets.onError({message: 'Sorry...'});
```

**Comment by bobylito** [comment]
> Hmm well wouldn't the error event let you do stuff at a given time (ie. error occurred) while the error widget would let you display errors?

No troll taken ;) I was just comparing hits vs render event with error event vs error widget. IMHO the error mechanism will let you do the same stuff, whereas the render event has a different purpose than the hits widget. That's details though :)

> I see it as a developer tool rather than a production tool.

For me too! And I agree with @vvo

**Comment by olance** [comment]
hmm I guess it works indeed :)

**Comment by bobylito** [comment]
Actually right now errors are not part of the widgets lifecycle: I propose we move on with the event and drop the idea of the widget for the moment. Feel free to reopen the issue or create a new one. Thanks 🙇
