### ISSUE TITLE
[hierarchical widget] add the alwaysGetRootLevel as an option

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#159]
cc @vvo

**Comment by vvo** [comment]
We need to map the helper option here, easy one

**Comment by vvo** [comment]
@maxiloc I cannot find the option name anymore in the helper, can you?

**Comment by maxiloc** [comment]
no :smile:

**Comment by vvo** [comment]
@maxiloc It was removed here: https://github.com/algolia/algoliasearch-helper-js/commit/01cb48da841f2a4e740fe5cc5f870bbc4f48b00b

When we fixed the default behavior to always get the root level because it made more sense.

**Comment by vvo** [comment]
So I do not completely understand your issue, try again :)

**Comment by maxiloc** [comment]
It's good now, if it's the default behavior
