### ISSUE TITLE
highlight not exported in dom.js

### ISSUE THREAD

**Issue by rahuldhawani** [algolia/instantsearch.js#1590]
`highlight` function is not exported in dom.js. The doc [here](https://community.algolia.com/instantsearch.js/react/gettingstarted.html#add-a-searchbox) says to import from `react-instantsearch/dom`. 

It gives an error when I am importing as given in doc.

**Comment by vvo** [comment]
Thanks this is definitely a bug. I am going to put it back for now and we will have to think twice about this helper because we need to make it compatible for react native too and for anyone not using our widgets too

**Comment by vvo** [comment]
Also see #1595

**Comment by vvo** [comment]
Will be solved via #1595
