### ISSUE TITLE
react-native and react compatible highlight method

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1595]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Right now we have a highlighting helper method that you can use like this:

```jsx
function Product({hit}) {
  return (
    <div>
      <span className="hit-name">{highlight('name', hit)}</span>
    </div>
  );
};
```

Given query is "co" and `name` is "coca", it will generate this:

```html
<div>
  <span className="hit-name">
  <em className="ais-highlightedValue" key="split-0-co">co</em>ca
  </span>
</div>
```

**What is the expected behavior?**

This is the only API entry we provide for highlighting. What if:
- I want to use another tag than `<em/>`
- I am not using the default theme and thus I don't want the classNames etc
- I am using react-native

Then you cannot really use this.

**Proposal**

```js
highlight({
  tagName:,
  pathToAttribute: 'desc.name'
  hit:,
  props: {
  
  }
});
```

As for having a specific widget for react-native, since we do not have any widget and I am not skilled into native, I have no proposal.

**Comment by bobylito** [comment]
For react native I did a component https://github.com/algolia/hn-reactnative-sample/blob/master/components/HighlightedText.js

What about leveraging the fact we can `createElement` instead of using JSX for custom tags?

**Comment by vvo** [comment]
> For react native I did a component https://github.com/algolia/hn-reactnative-sample/blob/master/components/HighlightedText.js

Ok so I guess we could do that in our native endpoint as our first component to help native devs.

> What about leveraging the fact we can createElement instead of using JSX for custom tags?

Not sure to follow what you meant.

**Comment by vvo** [comment]
We came up with:

```js
highlight({
  tagName:,
  attributeName:,
  hit:,
  props: {
  
  }
});
```

**Comment by vvo** [comment]
Issues description has been updated to provide the latest decision we came up with.

The main issues description is now what need to be done.
