### ISSUE TITLE
Reset page selection on query change

### ISSUE THREAD

**Issue by eyn** [algolia/instantsearch.js#1596]
USING REACT-INSTANTSEARCH.JS

**Do you want to request a *feature* or report a *bug*?**
Feature [maybe bug :)]

**What is the current behavior?**
When searching if I go to page 2/3 then change the query in the searchbox it doesn't reset to page 1 so when you then have less than page x * number_of_items_per_page results you get a blank search result. I've had a few users confused by this. 

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**
&p query parameter gets changed to 0 when SearchBox changes

**Comment by vvo** [comment]
Thanks! definitely a bug.

**Comment by mthuret** [comment]
Hi @eyn, I wasn't able to reproduce this bug locally. What version of react-instantsearch are you using?

**Comment by eyn** [comment]
Just upgraded to react-instantsearch@2.0.0-beta.18 and can confirm behaviour is now correct.

**Comment by SavageWilliam** [comment]
When changing the values of filters im also seeing the page number persist:

` "react-instantsearch": "^4.1.3",`

**Comment by Haroenv** [comment]
please open a new issue in React InstantSearch with reproducible example @SavageWilliam
