### ISSUE TITLE
connectHierarchicalMenu must forward items.items

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1605]
Right now it sends items.children. While we have widgets like CurrentRefinements sending items.items when nested on nested data.

Always easier to have a single way of dealing with nested structures.

(connectors consistency)

**Comment by bobylito** [comment]
@vvo should we settle for `items.items`? Or `items.children`?

**Comment by vvo** [comment]
> @vvo should we settle for items.items? Or items.children?

items.items then
