### ISSUE TITLE
Opening autocomplete results in new browser tabs

### ISSUE THREAD

**Issue by vlakoff** [algolia/instantsearch.js#1608]
Like many people, I'm a heavy user of middle click or ctrl+click to open links in new browser tabs.

Very sadly, this doesn't work for Algolia autocomplete suggestions… (demo search boxes: https://community.algolia.com/instantsearch.js/ – https://laravel.com/)

Maybe related: #323, #481

**Comment by vvo** [comment]
Hi @vlakoff, can you provide us a list of steps to reproduce the behavior you are experiencing? Thanks

**Comment by vlakoff** [comment]
1. Go to one of the websites mentioned above.
2. In the search box at top of the page, type some characters. Suggestions should be displayed below the box.
3. Middle-click on a suggestion: nothing happens.
4. Ctrl+click on a suggestion: opens in the same browser tab.

Expected: both middle-click and ctrl+click should open links in new browser tabs.

Tested on Firefox and Chrome.

**Comment by vvo** [comment]
@vlakoff Thanks for reporting this! Could you open an issue on DocSearch meanwhile? This seems to be a DocSearch issue: https://github.com/algolia/docsearch
