### ISSUE TITLE
Setting searchAsYouType as false results to search-as-you-type

### ISSUE THREAD

**Issue by rahuldhawani** [algolia/instantsearch.js#1609]
When using a connector, `connectSearchBox`, with prop `searchAsYouType` as `false`, the search box still behaves same as before, i.e. the queries are still performed as and when it's typed.

**Comment by vvo** [comment]
Hi @rahuldhawani this is an error on our side, connectors right now embeds the least amount of magic and so there's no searchAsYouType option nor autofocus or shortcuts.

I am removing this from the documentation. You will have to implement this for yourself, by binding a form submit event to the refine method.

**Comment by rahuldhawani** [comment]
👍

**Comment by alexandermckay** [comment]
**Implementation example:** 
```javascript
const SearchBox = connectSearchBox(({refine}) => {
  const [readValue, writeValue] = useState(emptyStr)
  const handleChange = ({currentTarget: {value}}: EventInput) => writeValue(value)
  const handleSubmit = () => readValue !== emptyStr && refine(readValue)
  const handleClear = () => {
    writeValue(emptyStr)
    refine(emptyStr)
  }
  return (
    <>
      <label htmlFor='search-input'>Search</label>
      <input id='search-input' type='search' value={readValue} onChange={handleChange} />
      <button onClick={handleSubmit}>Search</button>
      <button onClick={handleClear}>Clear</button>
    </>
```
