### ISSUE TITLE
Struggling with currentRefinedValues

### ISSUE THREAD

**Issue by synonymous1984** [algolia/instantsearch.js#1610]
Hi there, 

I´m trying to show the currentRefinedValues in the facet column with the currentRefinedValues widget. Displaying and functionality is fine, but I can´t customize the options for that widget. According to the documentation for my understanding this should work:

```
me.search.addWidget(
            instantsearch.widgets.currentRefinedValues({
                container: '#currentRefinedValues',
                clearAll: 'after',
                options: [{
                    cssClasses: [{
                        root: 'xxx',
                        body: 'bodytest',
                        clearAll: 'clearAllTest',
                        item: 'filter--active'
                    }],
                    templates: [{
                        header: '<h1>test</h1>'
                    }],
                }]
            })
        );
```

However, the "root" options (clearAll, container) work as expected but the parameters in the "options" array are completely ignored.

Has anybody a hint for me what is wrong with my configuration?

Thanks a lot,
Synonymous

**Comment by vvo** [comment]
Hi @synonymous1984, the syntax should be:

```
me.search.addWidget(
            instantsearch.widgets.currentRefinedValues({
                container: '#currentRefinedValues',
                clearAll: 'after',
                       cssClasses: {
                        root: 'xxx',
                        body: 'bodytest',
                        clearAll: 'clearAllTest',
                        item: 'filter--active'
                    },
                    templates: {
                        header: '<h1>test</h1>'
                    },
                }
            })
        );
```

**Comment by synonymous1984** [comment]
Hi! Thank you! For me the keyword "options" was the reason for my misunderstandig, cause to me it sounded like "create an array called options and set the parameters there".

Helpful would be an extended Example which shows some multidimensional options (like cssClasses).

**Comment by synonymous1984** [comment]
Another suggestion for the documentation: template.item does not name the variable which can be used. So how can the item data be shown? itemName, itemCount?

`me.search.addWidget(
            instantsearch.widgets.currentRefinedValues({
                container: '#currentRefinedValues',
                clearAll: 'after',
                cssClasses: {
                    clearAll: 'clear-all',
                    item: 'filter--active'
                },
                templates: {
                    header: '<div class="shop-sites--headline navigation--headline">Aktive Filter</div>',
                    item: '<span class="filter--active-icon"></span>'
                },
            })
        );`

**Comment by vvo** [comment]
Hi @synonymous1984, inside item template to easily see what are the options you can do item: function() {console.log(arguments)}

**Comment by bobylito** [comment]
Closing for now. The V2 documentation tries to be more exhaustive, if it's still not enough we'll work harder :)
