### ISSUE TITLE
Separate examples styles from docs header styles. 

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1614]
Since we added our doc header in all of our examples page, styles are collapsing.

We need to find a proper way to isolate both styles, otherwise, each time someone will change the design of our docs it could break our examples.

**Comment by vvo** [comment]
How do you want to do this @mthuret? Do you mean styles are being merged because there's no proper namespacing?

**Comment by mthuret** [comment]
Styles are being merged mainly because we are using bootstrap on both our docs website and our examples. 

We only need the header on our example, so one solution would be to split our documentation css file and only use the needed one on our example page.
