### ISSUE TITLE
Range onChange event causes search query corruption

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1617]
> on `v2` branch

This issue is a little strange but I decided open it because for me is not clear if something internally is wrong or I'm doing something weird.

Basically, the issue is, when I want to clear a query search, it cause a url routing corruption

![](https://d17oy1vhnax1f7.cloudfront.net/items/240I0m2g3z1s0x3q1C15/Screen%20Recording%202016-11-28%20at%2008.54%20pm.gif?v=2884f893)

Code implementation is [here](https://github.com/windtoday/windtoday-app/blob/master/src/app/SearchBox/index.js).

First time I tried with my custom Searchbox, but it also happens with your default Searchbox Component:

![](https://d17oy1vhnax1f7.cloudfront.net/items/421U3F3A1D0h140e282c/Screen%20Recording%202016-11-28%20at%2009.38%20pm.gif?v=3164c4f6)

I tried with the demo example and no corruption appeared, but not sure if they are updated.

You can try a live demo at https://windtoday.co

**Comment by Shipow** [comment]
Hey kikobeats, try this code https://github.com/Shipow/searchstone/blob/master/src/js/ui.js#L141

you'll need to expose search though 

> window.search = search;

**Comment by Kikobeats** [comment]
@Shipow sorry I didn't remember to mention that this issue is related with the `v2`branch.

**Comment by Kikobeats** [comment]
I investigated and is related with the `onChange` event of `Range` component:

![](https://d17oy1vhnax1f7.cloudfront.net/items/1J441r1c0n2r3Z1d0Q2J/Screen%20Recording%202016-11-29%20at%2011.25%20am.gif?v=d48cf007)

Specifically, I added a [log here](https://github.com/windtoday/windtoday-app/blob/master/src/app/Range/index.js#L37)

dafuq.

**Comment by Kikobeats** [comment]
Was a problem with the state, fixed! 

https://github.com/windtoday/windtoday-app/blob/d6623ccb2ae4e9f867847bc4a3c61a784956398c/src/app/Range/index.js

**Comment by Kikobeats** [comment]
BTW, could be nice update the Range example becase this is more complete

**Comment by Kikobeats** [comment]
I reopened that because I detected that with Range slider based on [rheostat](https://github.com/airbnb/rheostat) is not possible handle Float numbers.

For avoid that, I updated my current component implementation using `Math.trunc` to be ensure values are not floats: https://github.com/windtoday/windtoday-marketplace/commit/31f996ba3307ad2f4b040e60b6e35ae83239d701

Also [I answered in the rheostat repository](https://github.com/airbnb/rheostat/issues/67), I'm waiting response. I suppose handling float are not implemente based on the case of use of the component (just for price).

**Comment by mthuret** [comment]
Hey @Kikobeats, thanks for this information. Actually I had the same kind of issue with the `rc-slider` component. You need to truncate the min/max otherwise you endup with a warning. 

You would want the example updated to ensure that there's no float min/max values or you would it to handle 0.X step?

**Comment by Kikobeats** [comment]
Ideally, a way t handel 0.X values. 

My current approach using `Math.trunc` is more a workaround ¯\_(ツ)_/¯

**Comment by mthuret** [comment]
I'm closing this as today it depend of the component use on the user side (as we don't package one).

We should probably packaged a Range component in the end.
