### ISSUE TITLE
[hierarchical widget] add a fist-level class on the first level list to handle margin

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#162]
The thing is since have a generic code for facets I do not want to have a separate template but I need a way to put a different style for first level and other levels

cc @vvo

**Comment by vvo** [comment]
> The thing is since have a generic code for facets I do not want to have a separate template

First you will not be able to have a single template for refinement list and hierarchical facet because on one side you want checkboxes while you want menu on the other.

the current magento demo with instantsearch.js is using checkboxes for hierarchical facet and it looks weird of course.

Let's wait until you have the hierarchical menu with some good style, only missing what you need here and then we see how to solve it.

Ping me when it's ok.

**Comment by vvo** [comment]
@maxiloc Ping me when you can on this subject, we can definitely do something but I need to see the issue before having a good api proposal

**Comment by maxiloc** [comment]
yes ready on instantsearch.js branch, I will need this

**Comment by pixelastic** [comment]
Actually, can't you do something like this?

```css
.ais-hierarchical-menu--list {
}
.ais-hierarchical-menu--list .ais-hierarchical-menu--list {
  margin-left: 20px;
}
```

**Comment by vvo** [comment]
> .ais-hierarchical-menu--list .ais-hierarchical-menu--list {
>   margin-left: 20px;
> }

It will also target third level list right?

**Comment by pixelastic** [comment]
Yes, but you can also use specific styling on the third level with `.ais-hierarchical-menu--list .ais-hierarchical-menu--list .ais-hierarchical-menu--list`. You would rarely have more than three levels, and this issue was about distinguishing between first level and others.

**Comment by vvo** [comment]
So your solution would be to use ".ais-hierarchical-menu--list .ais-hierarchical-menu--list" style then remove the style with selectors like ".ais-hierarchical-menu--list .ais-hierarchical-menu--list .ais-hierarchical-menu--list"?

> You would rarely have more than three levels, and this issue was about distinguishing between first level and others.

In most cases yes. But don't you think it would feel to you as an API #fail to have to do like you proposed?

**Comment by pixelastic** [comment]
> So your solution would be to use ".ais-hierarchical-menu--list .ais-hierarchical-menu--list" style then remove the style with selectors like ".ais-hierarchical-menu--list .ais-hierarchical-menu--list .ais-hierarchical-menu--list"?

Yes. You override rules with more specific selectors. This is the `C` of `CSS` :)

In that specific case, most of the rules will be shared between the parent and child lists, but a few adjustements on padding/size/color will be needed, so it make sense to override the rules of the parent with those of the child.

I agree that providing the `-lvl` classes will make things easier and we should do it. I was just suggesting the usual way to do that (more an enhancement than a bug I mean).
