### ISSUE TITLE
{Help} Loading state before and after the query has run

### ISSUE THREAD

**Issue by rahuldhawani** [algolia/instantsearch.js#1623]
Hi, 
I am hacking with react-instantsearch, to make an e-commerce store. So far so good, except I am stuck on the part where you show loading whenever the query is running. 
Can you point me to some doc stating the above implementation?

**Comment by vvo** [comment]
> So far so good, except I am stuck on the part where you show loading whenever the query is running.

Could you detail a bit more "where you show loading whenever the query is running" => do you mean there's a documentation page where we show an interface displaying a "loading" mechanism and you do not understand how it works or smg else?

We do have a guide that explains how to read the search state: https://community.algolia.com/instantsearch.js/react/guides/conditional-display.html

And the state shape: https://community.algolia.com/instantsearch.js/react/guides/create-own-widget.html#getpropsprops-state-search-meta

But we have to make it better.

Here's an example:

```js
const Loading = createConnector({
    displayName: 'Loading',
    getProps(props, state, search) {
      return {loading: search.searching};
    },
 })(({loading}) => {
  console.log(loading);
 });
```

**Comment by rahuldhawani** [comment]
@vvo Thanks a lot. This is what I was looking for.

**Comment by vvo** [comment]
Awesome, this is now a guide in the upcoming website
