### ISSUE TITLE
searchBox eats characters

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#163]
![download](https://cloud.githubusercontent.com/assets/123822/10208452/c29d024e-67d3-11e5-9a2f-43a7538c1bf6.gif)

**Comment by bobylito** [comment]
Argh. Can you reproduce this bug with hash and modern API? I think we can do better but i will need a new API for the widgets

**Comment by vvo** [comment]
Did a PR and would like your "input" (:dancer:), #164
