### ISSUE TITLE
Cannot un-refine a selected Menu item

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#1634]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

When instantiating a `Menu` React component, I expect a click on a refined item to remove the refinement. It's not the case so far.

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

```js
<Menu attributeName="category" />
```

 - Click on an item -> refined
 - Click on the same item -> SHOULD un-refine

**Comment by redox** [comment]
> Are you using the latest npm release or the V2 branch?

`2.0.0-beta.18`

**Comment by vvo** [comment]
Confirmed bug on v2, thanks
