### ISSUE TITLE
Update styling guide to automatically inline current theme version to download

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1641]
Currently the styling guide refers to a static version of the Algolia theme, we need to be able to inject the last theme version automatically. Which means being able to use variables in the markdown file. This was doable using middleman, unsure with metalsmith how to do it well.

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
