### ISSUE TITLE
HitsPerPage widget width doesn't follow the content

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1643]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

![image](https://cloud.githubusercontent.com/assets/6885378/20833501/588f2576-b890-11e6-9a24-ea6fe5f76d7e.png)

Seems to do that only on certain content width and only on Chrome. 

**What is the expected behavior?**

The select width should follow the option content.

**Comment by vvo** [comment]
cc @LukyVj

**Comment by mthuret** [comment]
After investigating a little bit, it seems that is the font-weight usage the cause this behavior on chrome. Don't know yet if there's a workaround to keep the bold display.

**Comment by vvo** [comment]
This is old and needs to be re-checked, will do
