### ISSUE TITLE
Check and fix the example with the default theme

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1647]
Not sure if we have any dataset left, either we update one of the examples to use the new default widgets design or we create a new example.

We could also use the npm dataset: http://npmjs-instant-search-demo.heroku.com/

And also fix a few bugs:
 - [ ] hierarchical menu: based on float left, it breaks the margin top of the elements below
 - [ ] searchbox: no background
 - [ ] numeric range: inputs are too big

**Comment by bobylito** [comment]
That's a neat idea to revive this dataset :D This way I'll have a convenient to know where it is. Also it'll speak to users :)

**Comment by mthuret** [comment]
Isn't the dataset a little bit short about the widgets we can display?

**Comment by vvo** [comment]
Yes maybe,
keywords => refinement list
authors => refinement list
download group => sortBy
searchBox
hits

Is all I can think of right now

**Comment by bobylito** [comment]
There is an hidden example in which we can iterate : docgen/src/examples/default-theme

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
