### ISSUE TITLE
(Bug)(UX) - star rating - the cursor on the minimal value let me think that I can click (and it might unselect the value)

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1650]
**What is the current behavior?**

![2016-12-02 18 37 16](https://cloud.githubusercontent.com/assets/393765/20844286/572f053c-b8bf-11e6-84ea-94b046924bdb.gif)

In the gif, I am actually click on the minimal value.

**What is the expected behavior?**

When the minimal value is selected, the cursor should not have an appearance that let the user think that it is clickable.

**Comment by vvo** [comment]
Indeed this is a behavior that changed with react-instantsearch versus instantsearch.js. Basically we do display the minimum rating as being the default rating when you unselect/load the page to reflect the actual filter. What could we do to make it better here?

**Comment by bobylito** [comment]
The behavior is imho perfect right now. The proposes improvement is to set the cursor when hovering the minimal value (when it is selected) to the default, not the hand. Because the hand is for clickable items and when it is the current value, clicking on it does not do anything therefore it is not clickable. Does that make sense? It's hard to explain. I will provide a PR (simple css fix) it should be easier to get :)

**Comment by vvo** [comment]
Oh yes ok indeed shoot
