### ISSUE TITLE
question about hierarchicalMenu widget

### ISSUE THREAD

**Issue by chrisvidal** [algolia/instantsearch.js#1657]
**Do you want to request a *feature* or report a *bug*?**
question about hierarchicalMenu widget

Looking at the e-commerce example, can a product belong to many categories and sub-categories at the same time ?
If yes, how this is structured in the algolia indices ?

Thank you

**Comment by vvo** [comment]
Hi @chrisvidal sorry for late response already.

So yes it can be done, the structure to do this is described here: https://github.com/algolia/algoliasearch-helper-js#multiple-values-per-level
