### ISSUE TITLE
Check box are displaying incorrect(Algolia)

### ISSUE THREAD

**Issue by paruchurumohansa** [algolia/instantsearch.js#1663]
We are using instantsearch.js and our ApplicationID:AD6JRJWKK2.

Curerntly we are facing  issue with Checkbox(UI).

Some times it displaying correctly but in some times it displaying double checkbox instead of one.

Code for your reference.

search.addWidget(
  instantsearch.widgets.refinementList({
      container: '#aopPractice',
      attributeName: 'PracticeAreaName',
      operator: 'or',
      limit: 10,
      templates: {
          item: aopfacetTemplateCheckbox,
          header: '<h6 class="group-heading"><div class="facet-title">Areas of Practice</div class="facet-title"></div>'
      }
  })
);

Please find attachment.

Note:
Same problem in Sortby also.

Regards,
Mohan

![screenshot_13](https://cloud.githubusercontent.com/assets/24403373/20913419/c1fb2612-bb9d-11e6-857e-2962236b6a00.png)

**Comment by vvo** [comment]
Hi @paruchurumohansa as we never experienced this behavior, could you create a small https://jsfiddle.net/ or link us to a live implementation where we can trigger this issue at some point?

Thanks

**Comment by bobylito** [comment]
Seems stalled. If you see this behaviour again, please open a new issue thanks ❤️
