### ISSUE TITLE
InstantSearch props are not all updated when they change

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1673]
**Current behavior**

 the only props that are updated if changed on the `InstantSearch` component are `searchState`, `onSearchStateChange` and `createUrl`.

All the others: `appId`, `apiKey`, `indexName` and `searchParameters` can't be changed once the InstantSearch is mounted. 

This behavior is not natural as you expect changes in props to have repercussion on InstantSearch.

**Expected Behavior**

Props are updated accordingly in new ones are provided.

**Comment by mthuret** [comment]
See this also #1618

**Comment by bobylito** [comment]
Proposed plan:
 - [ ] make indexName configurable
 - [ ] create `<Configure />`
 - [ ] helper.setClient
 - [ ] helper.getClient
 - [ ] forward `setClient` in the InstantSearchManager
