### ISSUE TITLE
Server side rendering: being able to trigger the search server side

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1687]
Feature request

**What is the current behavior?**

Currently when rendering a react-instantsearch page with [next](https://zeit.co/blog/next) it doesn't send a page with results already fetched from Algolia.

**What is the expected behavior?**

It would be great if this could be achieved without any configuration. Otherwise, it would be enough to provide a guide that explains how to do it (and change the API or the internals to make it possible, if needed).

**Comment by VonD** [comment]
@bobylito what is the status on that ? Is there any work in progress ? maybe an API design ? Thanks!

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
