### ISSUE TITLE
[urlSync] create widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#17]
This widget should be able to keep the url in sync with the helper state.

## API

```javascript
// Setting some parameters
instant.addWidget(
  instantsearch.widgets.urlSync({
    // Parameters to be serialized and read from the URL
    trackedParameters : [
      // Any parameters of the SearchParameters can be chosen. Most likely to be chosen : 
      "query",
      "page",
      "hitsPerPage",
      // Also the index, as it can be changed for sorting purpose but is not in the SearchParameters
      "index",
      // Facets can be set through the usage of different widgets. But the user don't know much about that, only that it is based on an attribute
      "facet:myAttribute",
      // For simplicity sake, we can choose to track all the facets.
      "facet:*"
    ],
    // Minimum time after which we do a new serialization of the parameters into the URL
    timeout : 1000,
    useHash : false // should the url use #
  })
);
```

But with the use of default parameters, using the url sync is as simple as that : 

```javascript
instant.addWidget(instantsearch.widgets.urlSync());
```

### Init

The url sync needs to override the defaults parameter set by any other components. So it should always come last in the initialisation.

### Update of the URL

The update should take place each time there is an update of the SearchParameters. I'm not sure that the render would be the best time to update, and would prefer having it on the `change` of the helper (or any lifecycle we could implement that would mirror that event)

We could use _.debounce with the trailing and leading set to `true`.

## Previous work

There is already an initial implementation, that could be used for bootstraping this widget.

https://github.com/algolia/algolia-ui-kit/blob/master/src/setup/url.js

**Comment by bobylito** [comment]
API updated @vvo

**Comment by vvo** [comment]
Great, do we also do the `useHash` parameter in 0.0.1? There will be implementation that will only want to use the hash `#` and not the query string one (example: magento)

**Comment by bobylito** [comment]
that will have to be done I guess :)

**Comment by vvo** [comment]
So maybe in 1.0.0 :-)

**Comment by maxiloc** [comment]
Could be cool to have a function that is able to generate an url from a "state".

Ex for magento: for now I need to do something like :
```
'#q=&page=0&refinements=%5B%7B%22categories%22%3A%5B%22'.$path.'%22%5D%7D%5D&numerics_refinements=%7B%7D&index_name=%22'.$indexName.'%22';
```

Could be cool to say something like:
```php
generateUrl({
 'refinements':<?php echo json_encode(['categories' => $path]); ?>,
 'index_name': '<?php echo $indexName; ?>'
}
```

**Comment by maxiloc** [comment]
Also could be cool to have only what is needed in the hash/url.

**Comment by vvo** [comment]
I too would like to have this kind of feature @maxiloc. We discussed it in the helper and also with @bobylito but I can't remember why we decided not to do it.

What is your use case, where will you use it?

**Comment by bobylito** [comment]
I don't think why we couldn't do that. I think that it was related to the helper scope not the instantsearch.js scope...

**Comment by pixelastic** [comment]
I have a few remarks on this one.

> The url sync needs to override the defaults parameter set by any other components. So it should always come last in the initialisation.

Do you suggest we automatically push it last in the list, or that we educate users into adding the widget last in their code?

> The update should take place each time there is an update of the SearchParameters

I would have done it everytime we call `search` on the helper instead. This is a tiny difference but this makes more sense as the url should reflect the state of the current display of the page (which is not triggered until we `search()`)

Also, even if we use the default queryString, we should pack all our data in one variable, as to not collide with variables already defined in our customer implementation. 

I think the state->string and string->state logic should be in the helper, but the url synchronisation and load should be in the widget.

**Comment by redox** [comment]
> I think the state->string and string->state logic should be in the helper, but the url synchronisation and load should be in the widget.

:+1:

**Comment by bobylito** [comment]
> Do you suggest we automatically push it last in the list, or that we educate users into adding the widget last in their code?

Yes (I know it's kinda ugly :P)

> I think the state->string and string->state logic should be in the helper, but the url synchronisation and load should be in the widget.

I partially agree here. I think the helper should provide a way to get a meaningful subset of the state for serialization purpose, but not the serialization process itself. The serialization is part of the url mechanism as well. If we use other forms of storage, then the string wouldn't be meaningful but the sub object will always be.

state -> partial state + partial state -> state >> Helper
partial state -> string vice versa, >> Widget

**Comment by vvo** [comment]
> I partially agree here. I think the helper should provide a way to get a meaningful subset of the state for serialization purpose, but not the serialization process itself. The serialization is part of the url mechanism as well. If we use other forms of storage, then the string wouldn't be meaningful but the sub object will always be.

I would still add to the helper those two methods:
- setStateFromQueryString
- getStateAsQueryString

Mostly because this will allow us from the autocomplete.js project to generate urls that will be compatible with the urlsync widget of instantsearch.js

Otherwise we would have to tell the autocomplete.js to somehow use the instantsearch.js project (and make it a dependency or something) to generate urls.

There will also be a good usage from the server side to do server side rendering and burn instantsearch.js urls in the html.

All of this is also doable if the methods are somewhere in instantsearch.js but I would find it weird from a usage POV (maybe show how it would be used from the instantsearch.js @bobylito?).

I do not see why the state <-> querystring serialization mechanism should not be in the helper?

> state -> partial state + partial state -> state >> Helper
> partial state -> string vice versa, >> Widget

Did not get it.

**Comment by vvo** [comment]
> Do you suggest we automatically push it last in the list, or that we educate users into adding the widget last in their code?
> Yes (I know it's kinda ugly :P)

@pixelastic I also was for automatically pushing it somehow but that would be too much magic. Maybe that's the kind of widget that should be an instantsearch parameter instead?

**Comment by pixelastic** [comment]
> Yes (I know it's kinda ugly :P)

Yes to what? :)

As @vvo suggested, maybe a `urlSync: true` could be a better API for the widget that does not do any DOM manipulation or rendering

**Comment by maxiloc** [comment]
Just tested it, it looks great. I have 1 question and 1 issue.
Question: is that expected that even with a threshold on 5 seconds the url update instantly ?
Issue: When you type fast on the search input with url sync enable, sometimes you loose focus.

**Comment by redox** [comment]
We'll also need to avoid adding query parameters if they have no values (like `refinements=[]` or `numericRefinements={}`, `page=0`)

**Comment by vvo** [comment]
@redox Maybe we can open another issue here?

**Comment by vvo** [comment]
By default when loading I have this: `http://localhost:8080/#q=&idx=instant_search&p=0`

What would you want to remove? q and p ?

**Comment by redox** [comment]
> By default when loading I have this: http://localhost:8080/#q=&idx=instant_search&p=0

Just tested it on the Magento integration, and we had also all the `refinements`. I'm OK keeping `p` and `q`.

**Comment by redox** [comment]
> Just tested it on the Magento integration, and we had also all the refinements. I'm OK keeping p and q.

Wait, it seems to be caused by our PHP code actually :)

**Comment by vvo** [comment]
~~always bet on PHP~~
