### ISSUE TITLE
Create a banner for instantsearch.js main website

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1714]
![2016-12-08-143229_2395x284_scrot](https://cloud.githubusercontent.com/assets/123822/21011793/37fd4fa0-bd53-11e6-8b15-76e77f0f7e34.png)

We need to put a banner to react-instantsearch website on instantsearch.js website. A not too big one but Something like:

`Using React? Have a look at our react-instantsearch library (+ small logo)`

**Comment by vvo** [comment]
@LukyVj Any idea about this one?

**Comment by LukyVj** [comment]
I can do it today @vvo

**Comment by vvo** [comment]
🤘 Yes!

**Comment by LukyVj** [comment]
![](https://puu.sh/sMOI1/c6908e297f.gif)

**Comment by LukyVj** [comment]
I'll add it in the afternoon

**Comment by vvo** [comment]
Also add:
- top right menu item to react-instantsearch (with small logo if feasible)
- left nav documentation item speaking about react-instantsearch (same text than banne should be ok)

**Comment by LukyVj** [comment]
Will be fixed in #1737 1737
