### ISSUE TITLE
Restore RangeSlider initial position afeter clear query

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1722]
![](https://d17oy1vhnax1f7.cloudfront.net/items/090o0K1B1Q1o0L1y3n32/Screen%20Recording%202016-12-08%20at%2008.43%20pm.gif?v=f2e1c1ca)

When you type a query, the range slider adapt the `min` and `max` values based on the criteria, but, when you clear the query, it should be restoer the initial position (30 and 1500 repectively).

Could be easily checking the value of the `query` in the component, but I don't know how to.

Another thing: as you can see, in the first state, the value 30 and 1500 are the "base values" and they are not applied as a facet, but when you type a criteria, the new base values are applied as facet. Could be possible control that? this behavior is a little crazy, specially when you have more than one rangeSlider, check on https://windtoday.co/ what happens when you type something 😂

My [code](https://github.com/windtoday/windtoday-app/blob/master/src/app/Range/index.js) is based in the [rangeSlider code](https://community.algolia.com/instantsearch.js/react/widgets/RangeSlider.html).

Expected behavior: click [here](http://localhost:3001/?query=neylpride). It's have the query inside the URL, and the range sliders value are ok and not applied as facets.

**Comment by mthuret** [comment]
Hi @Kikobeats 

For your first issue, I noticed that you didn't update the slider when new props are given by InstantSearch. Adding something like this should do the trick:

```js
  componentWillReceiveProps(sliderState) {
    const value = {
      min: sliderState.currentRefinement.min,
      max: sliderState.currentRefinement.max
    }

    this.setState({
      min: sliderState.min,
      max: sliderState.max,
      value: value
    })
  },
```

For the second part, I'm sorry but can you also make a gif of the behavior that's bothering you, I have trouble to understand it correctly. 

Finally, when launching your application I noticed that sometimes, you can end-up with an infinite loop. The reason behind it is the usage of rheostat as a slider. When passing an equal min and max to rheostat, you got 'NaN' from it, and then `react-instantsearch` goes crazy. 

We will improve the behavior of `react-instantsearch` to avoid the infinite loop and I will open an issue on the rheostat side. 

In the meantime, if you want to fix this on your side, you can check for the current slider values and don't do a refine if those are `NaN`.

**Comment by Kikobeats** [comment]
woh, your `componentWillReceiveProps` solves the problem.

Thanks!
