### ISSUE TITLE
API Proposal(refinementList): add `hasRefinements` data to the template data

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#173]
To be able to generate such UI:

![screencast](https://cloud.githubusercontent.com/assets/123822/10284354/deb99998-6b83-11e5-8792-871a8a2e3564.gif)

Then we need to be able to access to some `hasRefinements` (boolean) in the template so that we can hide/show items based on both `isRefined` and `hasRefinements`.

What do you think?

**Comment by bobylito** [comment]
Isn't that the conjunctive refinement list?

**Comment by vvo** [comment]
I will have to try I may have too much rushed in doing the demo :-) thx

**Comment by vvo** [comment]
> Isn't that the conjunctive refinement list?

=> yes
