### ISSUE TITLE
expected a component class got object object

### ISSUE THREAD

**Issue by danielevz** [algolia/instantsearch.js#1730]
I get this error on react native "expected a component class got object object"

I'm just copy pasting thhe code that appears on the instantsearch guide of react native (InstantSearch)  to my new and clean project that appears in here: https://community.algolia.com/instantsearch.js/react/guide/React_native.html 

import React, {Component} from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ListView,
  TextInput,
  Image,
} from 'react-native';
import {InstantSearch} from 'react-instantsearch/native';
import {connectSearchBox, connectInfiniteHits} from 'react-instantsearch/connectors';

export default InfiniteSearch = () =>
  <View style={styles.maincontainer}>
    <InstantSearch
      className="container-fluid"
      appId="appId"
      apiKey="apiKey"
      indexName="indexName"
    >
      <SearchBox/>
      <Hits/>
    </InstantSearch>
  </View>;

const SearchBox = connectSearchBox(({currentRefinement, refine}) =>
  <TextInput
    style={{height: 40, borderColor: 'gray', borderWidth: 1}}
    onChangeText={(text) => refine(text)}
    value={currentRefinement}
  />
);

const Hits = connectInfiniteHits(React.createClass({
  onEndReached: function () {
    if (this.props.hasMore) {
      this.props.refine();
    }
  },

  render: function () {
    const dataSource = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    const hits = this.props.hits.length > 0 ?
      <View style={styles.maincontainer}>
        <ListView
        style={styles.list}
        dataSource={dataSource.cloneWithRows(this.props.hits)}
        renderRow={this._renderRow}
        onEndReached={this.onEndReached}/>
      </View> :
      null;

    return hits;
  },

  _renderRow: function (hit) {
    return (
      <View style={styles.item}>
        <Image
          style={{height: 100, width: 100}}
          source={{uri: hit.image}}
        />
        <Text>{hit.name}</Text>
      </View> );
    },
  }));

const styles = StyleSheet.create({
  maincontainer: {
    backgroundColor: 'white',
    flex: 1,
    paddingTop: 20,
    paddingBottom: 10,
    flexDirection: 'column',
  },
  list: {
    flex: 1,
    flexDirection: 'column',
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white'
  }
});

AppRegistry.registerComponent('InfiniteSearch', () => InfiniteSearch);

**Comment by iam4x** [comment]
@bobylito is working on a patch https://github.com/algolia/instantsearch.js/pull/1729 👍
