### ISSUE TITLE
[Docs] Feedback

### ISSUE THREAD

**Issue by rayrutjes** [algolia/instantsearch.js#1735]
The documentation is gorgeous!

Here are a few suggestions that would improve readability IMHO:

1. Decrease padding between header and the start of the content:
![image](https://cloud.githubusercontent.com/assets/5570853/21102996/d0c5b9b8-c080-11e6-9d71-ce567bdb053b.png)

2. Remove or ligthen the background pattern of the code examples. It looks very nice, but very disturbing when you actually try to read the code:
![image](https://cloud.githubusercontent.com/assets/5570853/21103016/ef456a64-c080-11e6-8ff6-7a20f4c8b884.png)

3. Increase the `<p>` line height a bit to make it inline code snippets "breathe":
![image](https://cloud.githubusercontent.com/assets/5570853/21103080/2bd08612-c081-11e6-9266-989d4ffb78cf.png)

4. Add some padding to the bottom of the sidebar:
![image](https://cloud.githubusercontent.com/assets/5570853/21103095/40036f64-c081-11e6-8437-41c555dac6ad.png)

WDYT?

**Comment by vvo** [comment]
> Remove or ligthen the background pattern of the code examples. It looks very nice, but very disturbing when you actually try to read the code:

We should use the github scheme from places:
![2016-12-14-162700_1013x295_scrot](https://cloud.githubusercontent.com/assets/123822/21187996/297413d0-c21a-11e6-89d0-e70beda2dc20.png)

Plain readable, line numbers, you read this all day already on github (well BUT dark theme users omg @rayrutjes :D).

As for the other feedbacks I agree. Thoughts @LukyVj?

(Thanks a lot @rayrutjes for this kind of detail killer issues)

**Comment by vvo** [comment]
Only missing are 1/ and 4/. Doing them today.
