### ISSUE TITLE
autocomplete is not disabled by default for our SearchBox

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1741]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

autocomplete is not disabled by default on our SearchBox

**Bug: What is the expected behavior?**

autocomplete is disabled by default on our SearchBox

**What project are you opening an issue for?**
- react-instantsearch

**Comment by rayrutjes** [comment]
@mthuret was a fix introduced, or was this a wrong negative?

**Comment by mthuret** [comment]
The Fix was merged this morning : #1742
