### ISSUE TITLE
How to implement search for facet values in react-instantsearch

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1743]
Goal of search for facet values: allow a user to search for specific values of a facet and select them. 

What's follow is a start to talk about our implementation of the search for facet values in react-instantsearch:

**1. Connectors**

a. Provide a `searchForFacetValues`function as a prop (like we do for `refine`) that will be in charge to trigger a search for facet values. If a connector must provide this feature, it will need to implement it by returning both the facetName and the query to use. 

b. add to the `getProvidedProps` function, a fifth parameters called for example `facetValues` which will contains the results of the search for facet values. (Those results will be stored into our store).
We can have an object with the following form: 

```js
const facetValues = {
  attributeName (the facetName): 
  {
      items: facetHits,
      query
  } 
}
```

The goal is to be able to retrieve the results inside the `getProvidedProps` function and format them to be used by the component (by returning along with `items` and `currentRefinement` a new `facetHits` prop). 

question: should we do that directly on the connectors that will support search for facet values, or should we create new connectors? 

**2. Widgets**

Same question as connectors: should we provide an option to activate the search for facet values inside our default widget or just create new ones (starting by the refinementList)? 

What do you think?

**Comment by vvo** [comment]
> a. Provide a searchForFacetValuesfunction as a prop (like we do for refine) that will be in charge to trigger a search for facet values. If a connector must provide this feature, it will need to implement it by returning both the facetName and the query to use.

Can you detail an example usage API of this using connectRefinementList?

**Comment by vvo** [comment]
> add to the getProvidedProps function, a fifth parameters called for example facetValues

Other names: `facetValuesSearchResults`

Can you write a complete example of API usage with connectRefinementList? Let's say I want to use this feature in my own refinement list.

**Comment by vvo** [comment]
> question: should we do that directly on the connectors that will support search for facet values, or should we create new connectors?

It should reuse the existing connectors to me. What would be the benefit of creating new connectors?

**Comment by vvo** [comment]
> Same question as connectors: should we provide an option to activate the search for facet values inside our default widget or just create new ones (starting by the refinementList)?

Same answer and question, is there a benefit in creating different widgets?

**Comment by mthuret** [comment]
So let's say you want to add searchForFacetValues to your refinement list: 

```js
render()
{
  this.props.facetHits.map(facet = > {
    return <label>
      <input type="checkbox"
             checked={facet.isRefined}
             onChange={() => {
               this.props.refine(facet.value)
             }}/>
      {facet.value}
    </label>
  }
)
  return (
    <div>
      <input onChange={e => {
        this.props.searchForFacetValues(e.target.value)
      }}
             type="search"/>
      {facetHits}
      {/* markup of the refinement list*/}
    </div>);
}
```

This is of course not a complete working example, it's just to give you an idea of the usage of the `searchforFacetValues` and how to retrieve the `facetsHits`.

IMO we should just modify our current connector and widget. As for the widget, displaying the input should be configurable through a prop.

**Comment by vvo** [comment]
:+1: understood. Now we have a pretty good idea of what we need to do. If we do not plan to do this right now but later on, then I would wrap it up in a complete proposal: changes to be made on which widgets, which connectors, new exposed props, new provided props).

An action plan so that when we get back to this in two weeks we know exactly what to do. What do you think?
