### ISSUE TITLE
How to implement a callback after execution of a widget

### ISSUE THREAD

**Issue by beHappyBeLindy** [algolia/instantsearch.js#1754]
Hi, 
I'm using a rangeSlider to filter the hits and I would like to display the interval price chosen by the user
<img width="334" alt="price-interval" src="https://cloud.githubusercontent.com/assets/24573118/21195570/9e80a0d4-c234-11e6-9785-913178940507.png">

To achieved that, I think I need a callback on the currentRefinedValues widget. Do you know How I could do that and if it is my best option?

**Comment by bobylito** [comment]
Hi @beHappyBeLindy thanks for contributing to the project with this issue. To customise the way the values are displayed you should use the CurrrentRefinenements connector: [connectCurrentRefinements](https://community.algolia.com/instantsearch.js/react/connectors/connectCurrentRefinements.html)

It is an higher order component that let you completely customize the view of this widget based on your understanding of your search interface.

**Comment by beHappyBeLindy** [comment]
Thanks a lot @bobylito for this quick answer. But unfortunately, I'm not using react in my project. 
Is there another existing solution with basic Js?

**Comment by vvo** [comment]
@Jerskouille I believe you solved a similar problem inside shopify? I do not remember the right way to do this (merging numeric refinements in this widget)

**Comment by Jerskouille** [comment]
Oh I didn't with Shopify, I just actually indexed price ranges as strings.
But I'm pretty sure this can be failry easily done with a custom widget that would call [`getNumericRefinements`](https://community.algolia.com/algoliasearch-helper-js/reference.html#SearchParameters#getNumericRefinements)`('price')`.

**Comment by beHappyBeLindy** [comment]
Thanks @Jerskouille, Helper is really powerfull, it helped a lot !

**Comment by Jerskouille** [comment]
Happy to have helped you! @bobylito is the one who did an awesome job with the helper.
I'll close the issue, feel free to reopen it any time. :)
