### ISSUE TITLE
Faceted values

### ISSUE THREAD

**Issue by agosssearch** [algolia/instantsearch.js#1755]
Just wondering if I am able to do this through a widget or something that is already built (new to this!)

The top section is a repeat of the second section. I want them to both to show the faceted values but the top section I want to link through to a different URL - so not act as a facet, but still show faceted values? And the URL to be generated from the category name and the current faceted values.

![image](https://cloud.githubusercontent.com/assets/24576147/21203478/77d6360a-c2b7-11e6-8d10-07ae732949dc.png)

**Comment by bobylito** [comment]
Hi @agosssearch Welcome to instantsearch!

If I understand correctly you want the first menu to be a navigation that will bring your users to pages related to the categories? Will those link based on a pattern that require only the name of the category? Are you using react-instantsearch?

**Comment by agosssearch** [comment]
Yes that is right the top section will be navigation but want it to relate the search already completed.
The URL can be generated just from the category name, and possibly one day link through the search term!  

I'm using the instantsearch.js library. It's not the React one.

**Comment by bobylito** [comment]
In order to do this you need to create a custom widget. The widget API is pretty accessible:

```js
var search = instantsearch(/*parameters*/);

var menuContainer = jQuery('.menu');
search.addWidget({
  render: function(opts) {
    var results = opts.results;
    var menuValues = results.getFacetValues('attribute');
    var html = menuValues.map(facetToHTML);
    menuContainer.html(html);
  }
});

function facetToHTML(facet) {
  return '<a href="#">'+facet.name+'</a>';
}
```

Every time there are new results in your search the method `render` of the widget will be called. It extracts the facet values and transform them into HTML string then add it to the DOM.

**Comment by bobylito** [comment]
I'm closing the issue for now @agosssearch Let me know if there is something missing from my previous message :)
