### ISSUE TITLE
Is there a way to hide the search results when clicking on a search result?

### ISSUE THREAD

**Issue by tedlin182** [algolia/instantsearch.js#1756]
I currently want the following behavior:
- When you click on a search result, it hides the result and ideally clears the input field
- When you type in the search field and then lose focus or click outside the search field or search results list, it hides the results list

Currently I'm just using `onBlur` to get the desired result, but unfortunately I had to change a lot of my handlers to `onMouseDown` since `onBlur` fires before `onClick`. Also when using the `InfiniteHits` widget, clicking on `Load More` automatically closes my results list and doesn't fire due to the `onBlur`.

I know you have a `ClearAll` widget, but it's a separate button and it would be nice to have access to a `clearField` method or something to manually trigger that when I want based on custom behavior.

Let me know if there is a way to take care of the above though.

Thanks!

Ted

**Comment by mthuret** [comment]
Hi @tedlin182, I will ask you the same thing than for your previous question, can you add a little gif showing the behavior you currently get and what is wrong with it? Can you also add a snippet of code to understand the element you are using?

To clear the query you have several options:
* if the `searchState` of `<InstantSearch/>` is externalized you can modify the `searchState` by resetting the key `query` to an empty string.
* You can use the connectSearchBox connector to build a custom component which will have the responsability to clear the query (by calling the refine function with an empty string).

**Comment by tedlin182** [comment]
Hi @mthuret 

Yeah I currently am just passing down a custom `clearSearchField` method from my parent search component down to the results components and triggering that `onClick` which just sets `query: ''`.

I wasn't sure if there was a less manual way of doing this, but for now this seems to work.

Thanks

**Comment by mthuret** [comment]
Alright, that's good to hear. I'll close this issue, don't hesitate to reopen it if something goes wrong.
