### ISSUE TITLE
Is there a way to display list of XX newest entries, but only up to 2 from each category?

### ISSUE THREAD

**Issue by virtuman** [algolia/instantsearch.js#1764]
**Do you want to request a *feature* or report a *bug*?**
feature

**Bug: What is the current behavior?**
don't know if exists

**Bug: What is the expected behavior?**
want to have an ability to display a widget that would include list of [most recent | any other sort] entries, but with option to include only up to X number of entries from each category

**Bug: What browsers are impacted? Which versions?**
n/a

**Feature: What is your use case for such a feature?**
ecommerce store - New Arrivals, but could easily be applied to any "Carousel-like" list of products, where output is limited

**Comment by vvo** [comment]
Hi @virtuman there's nothing to do that today inside instantsearch.js.

Doing faceting with Algolia you cannot enrich facet values by default.

If what you care about is new items, then you could add a "new_arrival:true" field to your hits inside Algolia then use this field in the custom ranking. Doing so will give a ranking boost to new arrivals. Combine this with sorting facet values by "count" then you should get a OK experience I guess.

Let us know

**Comment by bobylito** [comment]
Closing for now.
