### ISSUE TITLE
server side rendering

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#177]
I have no experience with server side rendering so I dunno what are the APIs available when you are doing pure react.

Here we have JavaScript wrappers bound to a helper, I wonder if we should and could propose some server side rendering utilities.

There seems to be two usecases:
- SEO, that's an easy one, you just get all the rendered html from the widgets and build a webpage out of it
- performance, sending a server-side rendered page that will be reused by us. But I am unsure that we can do this since we are wrapping react

**Comment by bobylito** [comment]
I think it's very unlikely that we can do anything with instantsearch.js for server side rendering. The strategy we are using is to slightly modify the page, not rendering the whole page. This gives us the ability to be easily be integrated in any webpages with very few modifications, but it also prevents us from being able to render a whole page.

On a more positive note, the Helper and React are pretty easy to run server side. ReactDom.renderToString will create the markup for any components. Maybe if we use have an already processed pages (let's say rendered with PHP or whatever) we could add a sort of layer filter / proxy that could interpret the page (like cheeryo or JSDOM) to inject some dom in it. I don't think it would that performant but that could be something to prototype.

It shouldn't part of instantsearch.js directly but could be a proxy that could understand a instantsearch configuration.

**Comment by vvo** [comment]
Lets close this for now
