### ISSUE TITLE
Is there a way to check if no results exist for multiple index searches?

### ISSUE THREAD

**Issue by tedlin182** [algolia/instantsearch.js#1771]
I have an overall "All Results" component that displays search results for multiple categories/index names and we want to display some "No results" text if no matching results are found in any category.

I know you can do that for each individual index, but is there a way to aggregate all of the results together? I'm currently just adding a temporary container that tracks each individual category results and checking if all are have no results but wasn't sure if there's a way to do this already in your plugin.

**Comment by mthuret** [comment]
Hi @tedlin182, we don't have something specific for it, so actually keeping track of each individual result and check if there is a global no results is a good way to achieve this :)

**Comment by vvo** [comment]
@tedlin182 Let us know if you need something more valuable or if you have any API ideas on how to do this.
