### ISSUE TITLE
Hits shown for empty search

### ISSUE THREAD

**Issue by smkhalsa** [algolia/instantsearch.js#1772]
I'm using react-instantsearch on react native. When I first open the search screen, the connected searchBox is empty, but my hits ListView is populated with results.

**Comment by vvo** [comment]
Hi @smkhalsa to solve this you can do:

```
import {Hits} from 'react-instantsearch/dom';
import {connectSearchBox} from 'react-instantsearch/connectors';

const Results = connectSearchBox(
  ({currentRefinement}) =>
  currentRefinement
  ? <Hits />
  : null
);
```

What it does is looking at the current query before trying to display Hits.

It's not perfect because it will still trigger a search, @mthuret any idea?

**Comment by mthuret** [comment]
The [Conditional Display trick] (https://community.algolia.com/instantsearch.js/react/guide/Conditional_display.html#displaying-content-when-the-query-is-empty) can also be used. But it will not solve the extra search issue.

**Comment by bobylito** [comment]
In the context of an app, you can decide not to display the whole instantsearch until you reach a specific route / state of the app. Would you like to display the search bar even though you are not searching? This first request is based on our experience of search, it initiates the conversation with the user and displays the items based on your metrics (custom ranking). This is usually recommended to do that @smkhalsa

**Comment by vvo** [comment]
@smkhalsa If you still need help on this, please reopen the issue.

**Comment by fatbattk** [comment]
There really should be an option to **NOT** have default hits on an empty search.

Using the autocomplete search box with _searchAsYouType_ and _debounce_ will always create a flicker of results since the initial hits is always filled. Tried force blanking out the results but the default hits always gets returned.

Or is this a separate issue that I should file?

**Comment by francoischalifour** [comment]
There's a section on our [Conditional Display](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-display/js/) page that talks about [handling empty queries](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-display/js/#handling-empty-queries). There are two workarounds for now. We are aware that those are not optimal though.
