### ISSUE TITLE
Adding an official Algolia Places widget for React InstantSearch

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#1773]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
I would like to have an official widget to incorporate Algolia Places into React InstantSearch, just like [we already have](https://community.algolia.com/places/examples.html#instantsearchjs) for "vanilla" InstantSearch.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
The behavior should be the same as the one presented here: https://community.algolia.com/places/examples.html#instantsearchjs

Basically, the widget should provide a textbox where I could do a Places query (with the possibility to instanciate it with any Places option), and upon selection of a result it shoud update the default geolocation point of the main InstantSearch query.

This would allow better compatibility into our various projects and help build more complex products. This feature request stems from this question on the Discoure instance: https://discourse.algolia.com/t/confused-about-appid-apikey-and-indexname/206/2

**What project are you opening an issue for?**
- react-instantsearch

**Comment by bobylito** [comment]
That's indeed a great idea !!

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
