### ISSUE TITLE
Trying to toggleRefinement() multiple facets

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [algolia/instantsearch.js#1777]
I'm trying to toggleRefinement multiple values while creating a custom widget:
```
...
init: function init(options) {
   var helper = options.helper;
   helper.toggleRefinement(attributeName, ['facet1,facet2']);
}
...
```
But they are returning no results, can you not use conjunctive faceting of the same category with multiple values?

**Comment by bobylito** [comment]
Hi @Giovanni-Mattucci It depends on your dataset. If you have arrays of values in your attribute then yes it makes sense to add multiple values with conjunctive facets. Can you give us an example of records?

**Comment by vvo** [comment]
Also, @Giovanni-Mattucci if your attributes are not storing arrays you will have to do this:

```js
helper.toggleRefinement(attributeName, 'value1');
helper.toggleRefinement(attributeName, 'value2');
```

Please reopen the issue if that's not what you were looking for
