### ISSUE TITLE
Allow Highlight to show when there is no highlighted value [react-instanctsearch]

### ISSUE THREAD

**Issue by l4u** [algolia/instantsearch.js#1790]
Can we add an option that allows no highlighted attribute?

1) the attribute might not exist.
2) the highlighted word might be in another attribute.

https://github.com/algolia/instantsearch.js/blob/e561c7b1865e8fa921b2e1e725c983aae7366861/packages/react-instantsearch/src/core/highlight.js#L27

**Comment by bobylito** [comment]
If the attribute exits in some records and not in others, then imho it's a bug. We should be able to declare different attributes and not fear the attributes to be unavailable.
