### ISSUE TITLE
div wrapper in Hits [react-instantsearch]

### ISSUE THREAD

**Issue by l4u** [algolia/instantsearch.js#1793]
Is there any way to remove the div wrapper in Hits?
It prevents me from using table rows with Hits.

**Comment by bobylito** [comment]
Hi @l4u 
You can have the full control of the rendering using the connectors. In this case, you can use the [connectHits](https://community.algolia.com/instantsearch.js/react/connectors/connectHits.html) and go wild :) Let me know if that fits what you're looking for.

**Comment by l4u** [comment]
Thanks @bobylito. It works.
