### ISSUE TITLE
url bug with search state change

### ISSUE THREAD

**Issue by terranboy** [algolia/instantsearch.js#1800]
![screen capture on 2017-01-04 at 19-47-55](https://cloud.githubusercontent.com/assets/2003834/21641482/0f20e58c-d2b7-11e6-90da-0682295fee6f.gif)

I followed this guide:
https://community.algolia.com/instantsearch.js/react/guide/Routing.html
and set up the example.
As you see, the first refinementList[colors] didn't disappear, but the second and the third disappeared.

And is there a way to rename the state to shorten the url, such as "refinementList"is too long.

**Comment by mthuret** [comment]
Hi @terranboy,

The routing example doesn't demonstrate what you are trying to achieve currently. It's up to you to decide how you want the `searchState` to be transformed as an url.

What you could add is a clean up function that will remove any empty objects and any empty strings from the `searchState`.

Ex:

```js
import {omitBy, toPairs, isEmpty, isObject} from 'lodash';

const searchState = toPairs(nextSearchState).reduce((acc, pair) => {
      const value = isObject(pair[1]) ? omitBy(pair[1], v => v === '') : pair[1];
      if (value !== '' && !isEmpty(value)) {
        acc[pair[0]] = value;
      }
      return acc;
    }, {});
```

Let me know if this help.

**Comment by terranboy** [comment]
@mthuret 
Thanks, it's solved.
 And is there a way to rename the state to shorten the url?
ex: 
refinementList => dFR
query => q

**Comment by mthuret** [comment]
That's nice to hear @terranboy :). 

If you want to shorten the url, you will have to code that function yourself (like you added the cleanup for empty values).

We might add an utility for this in the future, but nothing is planned yet.

**Comment by terranboy** [comment]
Thanks @mthuret.
