### ISSUE TITLE
API proposal: transformProvidedProps as a way to modify widgets providedProps. 

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1806]
Because we removed the sortBy option on several widgets, a user can't modify the sorting strategy if using our widgets. However we noticed that the sorting strategy was heavily depending on the use case and the amount of data, thus, a user should be able to modify it.

Because we don't want to provide an option that has a lack of flexibility and because other use cases might come up we should add an API entry that is being able to modify the props sent to a widget.

@vvo proposed to have a prop called `transformProvidedProps`. It will take the `providedProps` as a parameter, and expect to return the same `providedProps` structure.
This props, if exists, will be called each time a connector called its `getProvidedProps` function.

ex of usage:

```js
<RefinementList attributeName="category" 	
				transformProvidedProps={props => {
      				const items = orderBy(props.items, ['label'], ['asc']);
      				return {...props, items};
				}}
/>
```

**Comment by vvo** [comment]
This is good we can move on implementing,
also add a guide like "Sorting and filtering items" something like that?

**Comment by mthuret** [comment]
Yes good idea :)

**Comment by bobylito** [comment]
> After some second thoughts, why not restrict the scope of this function to only the items provided prop as it will be for now only used when filtering or sorting items.

I think I like this way more. The intention is clearer. Proposal for an other name: `transformProvidedProps`.

**Comment by mthuret** [comment]
why are you favoring `transformProvidedProps` over `transformItems`?
