### ISSUE TITLE
Query params should be omitted when possible for cleaner URLs

### ISSUE THREAD

**Issue by zeke** [algolia/instantsearch.js#1813]
This is a followup to https://github.com/yarnpkg/website/pull/322#issuecomment-270567447

**Do you want to request a *feature* or report a *bug*?**

A little bit of both. ⚡️ 🐞 ⚡️ 

**Bug: What is the current behavior?**

Conducting a search on [yarnpkg.com/search](https://yarnpkg.com/search) adds unneeded query params to the URL:  `?q=fetch&p=0&is_v=1`

**Bug: What is the expected behavior?**

Query should just be `q=fetch` by default, and only include the `p` and `is_v` values when their values are something other than their defaults.

**Bug: What browsers are impacted? Which versions?**

All browsers. 🌍 

**Feature: What is your use case for such a feature?**

Cleaner URLs are easier to read, edit, and share.

**Comment by Haroenv** [comment]
actionable items here: 

- [x] remove `is_v`
- [ ] consider if `index` is really necessary in the default urlSync
- [ ] make `p` only show up if it’s > 1
- [ ] make `p` start at 1

**Comment by bobylito** [comment]
This will be part of #2636

**Comment by zeke** [comment]
Thanks!
