### ISSUE TITLE
How to set a default / starting category to IS page

### ISSUE THREAD

**Issue by JanPetr** [algolia/instantsearch.js#1819]
**Do you want to request a *feature* or report a *bug*?**
**Bug** / **Question**

**Bug: What is the current behavior?**
I want to programatically set a starting / default category to a hierarchical widget.

Use-case:
Right now in our Magento extension, you can disable autocomplete menu and enabled instant search feature, which means when you search by using a search box in a header, you get the JadoPado experience with instant search page.
At the same time, you can replace category pages with instant search as well, so the users can benefit from Algolia filters even on category pages.
The issue is, that when you are on a category page, the search box in a header of the website searches only products within the category. (this is achieved by setting a `rootPath` in hierarchical widget)
And I want to give a user a possibility to remove the category refinement and search again in a whole catalog.

I try to do it via `searchParameters`:
```js
var attribute = 'categories.level' + algoliaConfig.request.level;

var facetRefinements = {};
facetRefinements[attribute] = [algoliaConfig.request.path];

var searchParameters = {
    facetsRefinements: facetRefinements,
    facets: [attribute]
}
```

It then appears in `currentRefinementValues`: 
<img width="317" alt="screenshot 2017-01-10 12 11 20" src="https://cloud.githubusercontent.com/assets/1058144/21826762/9bd6186e-d73d-11e6-8897-1f0d9809dcc1.png">

But when I click on a category in `hierarchicalWidget` it won’t replace the previously set category: 
<img width="298" alt="screenshot 2017-01-10 12 12 03" src="https://cloud.githubusercontent.com/assets/1058144/21826772/ac5cf374-d73d-11e6-90ac-77a2e3322bff.png">
(now I expect only “Sale” category to be displayed and used for filtering).

And another issue is when I remove all category filters by clicking them out from `currentRefinements` widget, then select a random category, and remove it by clicking on it again in hierarchical widget, it somehow returns the default category. Probably better to see it on GIF:
![06shnasqea](https://cloud.githubusercontent.com/assets/1058144/21826802/d11453e2-d73d-11e6-8b46-b080301c533a.gif)

I tried to achieve the behaviour even by using `rootPath` parameter of the hierarchical widget and not `searchParameters`. It works OK, refines data, shows the value in current refinements. But after removing the category from current refinements widget, the hierarchical widget is not displayed - seems to be empty.

**Bug: What is the expected behavior?**
The consistent behaviour between what is selected in hierarchical widget and displayed in current refinement values widget.
Possibility to somehow set a starting / default category for IS pages.

**Bug: What browsers are impacted? Which versions?**
Not browser related.

**jsFiddles**
Solution with `rootPath` - https://jsfiddle.net/JanPetr/0rbg8Lzt/
Solution with `searchParameters` - https://jsfiddle.net/JanPetr/pw2s7zcw/

Unfortunately I'm not able to reproduce the issue from posted GIF in jsFiddle (the issue which returns back the default category when category refinement is removed in hierarchical widget, not current refinements widget). I will add it when I'll manage to reproduce.

**What project are you opening an issue for?**
- instantsearch.js

**What is the version you are using? Always use the latest one before opening a bug issue.**
The latest one

**Comment by vvo** [comment]
@JanPetr have a look at this: https://jsfiddle.net/0rbg8Lzt/1/

Would that work for you? I think this is the right way to start a solution for this, rootPath is not what you want exactly.

You will still be able to hide every other element but I would not do it, provide context to the user is better.

**Comment by JanPetr** [comment]
That's perfect @vvo, thanks a lot. Totally works for me, feel free to close the issue if it's not relevant anymore.

**Comment by rayrutjes** [comment]
The solution as an overhead of 1 query though, but has the advantage of being simple.
Is there a way to avoid the first query?

**Comment by vvo** [comment]
Have a look here, seems ok: https://jsfiddle.net/vvoyer/pw2s7zcw/1/

**Comment by JanPetr** [comment]
Actually @vvo, the second version with `searchParameters` doesn't work as expected when you have enabled `urlSync`: https://jsfiddle.net/JanPetr/pw2s7zcw/3/

Try to switch category to "VIP" and then remove the "VIP" category by clicking on it again in `hierarchicalWidget`. Instead of just removing the category from refinements, it'll return back the "Shirt" category:
![4wxwmji5ta](https://cloud.githubusercontent.com/assets/1058144/21913036/a35a305a-d8de-11e6-8fdd-2ff0d500c9af.gif)

Is that expected? Is it bug and should be fixed?

**Comment by vvo** [comment]
Seems like a bug yes

**Comment by vvo** [comment]
@JanPetr I am not able to reproduce the issue now, can you?

**Comment by JanPetr** [comment]
@vvo I can still reproduce in linked JSFiddle - https://jsfiddle.net/JanPetr/pw2s7zcw/3/
Click for example on "Accessories" and then click on it again like you would like to remove it. Instead of just removing Category filter it puts back "Shirts" category filter.

**Comment by bobylito** [comment]
@vvo @janPetr whoah that's crazy I swear we couldn't reproduce it earlier but now I can. What's even weirder is that you can do other refinements before removing the removing the currently selected refinement and it still goes back to shirts :/

**Comment by JanPetr** [comment]
Yes ... And when you remove `urlSync` parameter from IS it works as expected :)

**Comment by bobylito** [comment]
@JanPetr i see that your level 0 attribute contains a separator, doesn't that mean it's a level 1 and not 0?

**Comment by JanPetr** [comment]
It does, but when I specify `level1` instead of `level0` in searchParamters it doesn't work at all. The current settings is based on @vvo's https://github.com/algolia/instantsearch.js/issues/1819#issuecomment-271842356 and https://github.com/algolia/instantsearch.js/issues/1819#issuecomment-272214050

**Comment by bobylito** [comment]
Oh ok... yes... It's a convention for the naming because of the parameters in the helper. That's not the problem it seems then. Let's dig deeper :)

**Comment by JanPetr** [comment]
Any news on this one @bobylito @vvo ?

**Comment by vvo** [comment]
@JanPetr Even if first solution does two queries, would that work for you now? https://github.com/algolia/instantsearch.js/issues/1819#issuecomment-271842356

**Comment by JanPetr** [comment]
@vvo Yes, I have it already implemented (https://github.com/algolia/algoliasearch-magento-2/pull/144), I was just waiting if you're going to fix it so I can do it in "not-hacky" way :) But I guess it would be feasible have it with 2 queries as temp solution.

**Comment by vvo** [comment]
Ok then let's do this, I don't think the second solution is fixable easily, this is the behavior of searchParameters for now.
