### ISSUE TITLE
instantjs always fires a search

### ISSUE THREAD

**Issue by proudlygeek** [algolia/instantsearch.js#182]
Hi,

I'm currently using a *searchBox* and a *hits* widget for a documentation search box.

Currently instantjs fires a search with an empty input on page load. It would be great to have some sort of switch or, even better, a **character threshold** parameter with a reasonable default value (*e.g. Don't fire a search request for less than three characters*) like Typeahead.js does.

A possible implementation could be adding a ```minLength``` parameter on the *searchBox* widget:

```javascript
search.addWidget({
  container: '#search-wrapper input',
  minLength: 3
});
```

**Comment by Shipow** [comment]
Empty query is used to warm up the connection, it resolves the DNS and init keep alive. Having a minLength can be useful in few cases but most of the time you can find your results before typing 3 chars. A mouseover event to trigger the empty query is probably a better approach.

**Comment by vvo** [comment]
> A mouseover event to trigger the empty query is probably a better approach.

what about mobile?

> Currently instantjs fires a search with an empty input on page load. It would be great to have some sort of switch or, even better, a character threshold parameter with a reasonable default value (e.g. Don't fire a search request for less than three characters) like Typeahead.js does.

One of the goal of instantsearch and Algolia is to be able to give meaningful results at the first keystroke, thanks to custom ranking (popularity) and speed!

Is it a better idea to only trigger after 3 characters? I am not sure, now that I am used to Algolia I expect all search engines to react at the first keystroke (if they can give good results).

As for this issue @proudlygeek is it a requirement? If so we could add an option to the searchBox widget to only trigger searches after the third character. But really we must ask ourselves: will it be a good UX?

**Comment by proudlygeek** [comment]
@Shipow Prefetching is a good idea but should be still configurable in my opinion. Starting at 1 character as a default is good enough but as a user, especially a mobile one, doesn't want an additional HTTP request fired with *no* inserted terms.

@vvo My use case is to replicate a documentation search box like [Laravel's][1]. As you can see no request are fired until at least one character is typed.

[1]: http://http://laravel.com/docs/5.1

**Comment by vvo** [comment]
Ok understood, makes sense. So what you would need here is be able to call `search.start()` when you are ready.

Maybe you can already do so: use your own `<input>`, bind events on it (DOM regular events), create the searchBox widget out of it, when you reach one character, call `search.start()`

**Comment by proudlygeek** [comment]
> Maybe you can already do so: use your own <input>, bind events on it (DOM regular events), create the searchBox widget out of it, when you reach one character, call search.start()

That's fine, I'm already doing this for my implementation :wink:

Just wondering if it was something we wanted *out of the box* without too much hassle. I was expecting ```.start()``` to behave more like an initializer, not actually searching without user's input / interaction.

**Comment by vvo** [comment]
> Just wondering if it was something we wanted out of the box without too much hassle. I was expecting .start() to behave more like an initializer, not actually searching without user's input / interaction.

Also wondering, there's #4. What we miss here is a good API Proposal to handle such things. Could be events (where you would then have to call .search) or API option on searchBox.

**Comment by bobylito** [comment]
I think we agree that we need to provide an API to disable this behavior. Move discussion to #185.
