### ISSUE TITLE
Create a guide for React InstantSearch here: https://www.algolia.com/doc/guides/search/instant-search/

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1823]
Steps:

- [x] create the same demo than https://demo.algolia.com/examples/instant-search/jquery/ but with react-instantsearch
- [x] create a new `react-instantsearch` section for the Instant Search Result Page guide using snippet from the previous demo.

**Comment by mikaa123** [comment]
i'm going to work with @mthuret on the guide :)
