### ISSUE TITLE
Duplicate elements using InfiniteScroll + HitsPerPage

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1839]
It appears in the last page. Looks like duplicate all the elements of the last page?

I checked the content directly in the index and just is a duplicate on the frontend level

<img width="1271" alt="windtoday__intelligent_windsurf_marketplace" src="https://cloud.githubusercontent.com/assets/2096101/21982874/a3d75f54-dbee-11e6-96d6-a97768abc03c.png">

**Comment by mthuret** [comment]
Hi @Kikobeats,

I saw that you have implemented your own `InfiniteHits connector`. What were the reasons of not using the one we provide? See: https://community.algolia.com/instantsearch.js/react/connectors/connectInfiniteHits.html

**Comment by Kikobeats** [comment]
Oh, I reimplemented the connector becuase I need to pass extra props, but basically is the same (I checked it before create the issue).

You can see the implementation here: https://github.com/windtoday/windtoday-marketplace/blob/master/src/app/Results/connector.js

**Comment by mthuret** [comment]
I look with our infinite example and wasn't able to reproduce the behavior you observed. 

Could you try to use directly the `InfiniteHits connector` directly under the `<InstantSearch/>` component just to see if you observe the same thing?

Also what do you mean by including the `HitsPerPage` in the title?

**Comment by Kikobeats** [comment]
It started working fine when I removed `hitsPerPage` prop from `InstantSearch` component. You can see it here: https://github.com/windtoday/windtoday-marketplace/commit/74d6caaa81d36297dd70f12680faa3996692c4e7

**Comment by mthuret** [comment]
I wasn't able to reproduce it using InfiniteHits + hitsPerPage setup with searchParameters. 

Can you try using directly `InfiniteHits`, even just the widget with raw values, just to see if you can observe the same behavior? Thanks @Kikobeats!

**Comment by Kikobeats** [comment]
sure, give me a little time try to be ensure with that 😄
