### ISSUE TITLE
API Proposal: transfer result, change, search events from the helper to instantsearch.js

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#184]
For our users to be able to build things like "hide the hits widget when the query is empty", we could just forward the helper events to the instantsearch instance.

So that the user could:

```js
search.on('change', function(state) {
  if (state.query === '') {
    hits.classList.add('hide');
  }

  // hits being the hits container you have a reference to already (from your code)
});
```

cc @proudlygeek what do you think?

**Comment by proudlygeek** [comment]
Yes, that would totally help my use case and more complex ones. :+1:

**Comment by bobylito** [comment]
Why about proposing some sort higher order widgets? Decorator?

```js
var hideOnEmpty = instantsearch.addons.hideOnEmptySearch;
search.addWidget(hideOnEmpty(instantsearch.widgets.searchBox({
    container: '#search-box',
    placeholder: 'Search for products',
    cssClass: 'form-control',
    poweredBy: true
  })
));
```

**Comment by vvo** [comment]
> Why about proposing some sort higher order widgets? Decorator?

Yes it works for this use case indeed. Wonder what's the best choice. Can you think of other high order widgets?

**Comment by bobylito** [comment]
Anything that could require some events of the helper in a widget context could be factorize in those. But no I don't see other case here ;)

**Comment by bobylito** [comment]
`showWhenNoResults`, could be done to implement the list of current refinement of the instant search demo.

**Comment by vvo** [comment]
Closing this, will reopen when really needed
