### ISSUE TITLE
[Question] startup ready event

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1841]
I followed your [Conditional Display](https://community.algolia.com/instantsearch.js/react/guide/Conditional_display.html#displaying-content-when-loading) tutorial for setup a full screen spinner at first time user enter in the website.

The problem is that the value suggested by the tutorial also is used under pagination, so first time the user ente rin the website yea, the spinner appear but also on pagination and looks weird xD

![](https://d17oy1vhnax1f7.cloudfront.net/items/0O2U003T382V3D3Q1k1K/Screen%20Recording%202017-01-16%20at%2007.56%20pm.gif?v=ae851dfa)

Exists something like an event at the startup time that means the system is ready and Can I associate my conditional spinner loader listening the event?

PS: The tutorial says `searchResults.loading`, but currently the value is `searchResults.searching`
PS2: I'm thinkin in use `searchResults.searching` for add a little spinner in the `Load More` button, but ideally could be nice complement that with a startup spinner.

**Comment by Kikobeats** [comment]
I fixed using a component with state and waiting the second `searching=true` event:

```
getInitialState () {
    return {loading: true, ready: false}
  },
  
  componentWillReceiveProps () {
    const {props, state} = this
    const {searching} = props
    const {ready} = state
    if (searching && !ready) this.setState({loading: false, ready: true})
  },
```

Maybe you are interested on include that in your code and emit a `ready` prop complementary to `searching`.

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
