### ISSUE TITLE
Create a light version without bundled dependencies

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#186]
We could do this:
- expose instantsearch.react/lodash/hogan => allow people building widgets reusing our dependencies
- declare react/lodash/hogan/algoliasearch/algoliasearch-helper as externals in a new build named instantsearch.without.deps[.min].js
  - this would mean that the user would have to include react/lodash/hogan/algoliasearch/.. in his own webpage

**Comment by vvo** [comment]
Can you precise how it would look like in term of html `<scripts>`? (an example of `<scripts>` tags).

What do you think the usecase is here? Something like a user already having `<script src=react/lodash` etc.. Wanting to share his `<script>` dependencies with us? If so we can make all big dependencies externals in a specific build but I am unsure of the usage.

I expect people in need of optimization to already use things like npm and not relying on script tags to include react/lodash..?

Do you need it somehow in shopify?

**Comment by Jerskouille** [comment]
Here is a standard example of the list of `<script>` tags that would make sense:

- `lodash`
- `hogan`
- `react`
- `jquery`
- `algoliasearch.jquery`
- `algoliasearch-helper`
- `autocomplete.jquery`
- `instantsearch`

I really think that creating bundles for each use case will become an unmaintanable mess, since we're just doing it for front-end implems where the dependencies have always been declared in sequence, and it isn't shocking.

Some users might already have `jquery`, `lodash`, or `hogan` and ok, `hogan` is nothing, but `jquery` or `lodash` are big. Sometimes, you need the JS client in addition to `instantsearch`. 

Moreover, it will really be needed as soon as we'll have people building *widgets*, because they might want to use lodash or hogan or whatever, and we shouldn't have each widget built with its dependency if not needed.

**Comment by vvo** [comment]
> On Shopify, it's really only about jQuery, and maybe lodash in some themes.

As for this immediate need, we do not use jQuery in instantsearch.js so you are good to go (neither algoliasearch.jquery, nor autocomplete.jquery).

> Moreover, it will really be needed as soon as we'll have people building widgets,

Yes this is an issue, we do not have any proposal right now to allow people building their own widget and reusing our react/hogan/lodash.

We could do this:
- expose instantsearch.react/lodash/hogan => allow people building widgets reusing our dependencies
- declare react/lodash/hogan/algoliasearch/algoliasearch-helper as externals in a new build named instantsearch.without.deps[.min].js
  - this would mean that the user would have to include react/lodash/hogan/algoliasearch/.. in his own webpage

What do you think?

**Comment by Jerskouille** [comment]
:+1: LGTM !

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is very old and not done, reopen if you have the need and want to fix it

**Comment by Jerskouille** [comment]
Reopening, I'm still using autocomplete.js and hence am already importing the JS client, we definitely don't need it twice.

**Comment by vvo** [comment]
> Reopening, I'm still using autocomplete.js and hence am already importing the JS client, we definitely don't need it twice.

You can generate a complete build like we do for magento, would that work? If so I can help you do it.

**Comment by Jerskouille** [comment]
Yes, it would work, but I still don't think that how our users will want it. Why force a build system if we don't have to?

**Comment by vvo** [comment]
We are not going to do it right away. For our usage, we are going to do bundles everytime.

After talking with @Jerskouille, this came up:
The use case "a `<script>` user is aware enough to be wanting to optimize the usage of his own `<script>` tags by sharing dependencies without using browserify/webpack AND he found the relevant documentation in our website" should be very rare or non-existent.

If I am wrong here I am happy to provide :beers: to both @Jerskouille and our user if that happen.

**Comment by xarg** [comment]
I have the same issue. Just moved to the cdn of instantsearch.js from webpack. You seem to be having lodash 2 times, one in algoliasearch and in instantsearch.js and we're loading lodash the 3rd time in our own project, but we're only loading what we need with webpack you seem to be loading everything. 

Even the CDN version is 400k minified.. (//cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.js)

**Comment by vvo** [comment]
Hi @xarg this seems like a different issue (multiple lodash). Can you open a new issue with a reusable repository using webpack where we can see duplicated dependencies? Thanks

**Comment by xarg** [comment]
@vvo: Right here #984
