### ISSUE TITLE
Add geo search guide using Configure

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1860]
Guide should explain how to change geo location of a search instance using Configure.

Ultimately adding recipes on how to plug google autocomplete and google maps to react-instantsearch would be awesome.

Recipes:
  - location autocomplete refines search
  - map move refines search

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
