### ISSUE TITLE
<Configure></Configure> should update the searchState inside a configure: {}

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1863]
Ref: https://twitter.com/zachcodes/status/821484313325740032

**Comment by zackify** [comment]
Oops, sorry. Just assumed there couldn't have been an issue already, my bad.

**Comment by zackify** [comment]
Want to point me in the right direction and I can try my hand at this for you?

**Comment by vvo** [comment]
In fact I think we are missing a bit of architecture needs to make this happen but you could give a try at:
- adding a refine() to https://github.com/algolia/instantsearch.js/blob/146b8e1c3d62ca6a462346f9c8a68d05cbc96f69/packages/react-instantsearch/src/connectors/connectConfigure.js that would add a configure: {} part to the state with all the query parameters used on the Configure (and merging with other configure widgets usages)
- add a cleanup that would clean only the relevant query parameters passed down for this particular widget https://github.com/algolia/instantsearch.js/blob/146b8e1c3d62ca6a462346f9c8a68d05cbc96f69/packages/react-instantsearch/src/connectors/connectConfigure.js
- call refine() as soon as possible in the Configure widget https://github.com/algolia/instantsearch.js/blob/146b8e1c3d62ca6a462346f9c8a68d05cbc96f69/packages/react-instantsearch/src/components/Configure.js. This is the tricky part as no widget today are doing this so dunno how it will go

Ultimately we may need a way to be able to enhance the search state as soon as possible without having to call refine manually immediately because that could lead to weird behaviors.

**Comment by zackify** [comment]
@vvo I'll have to get the repo running, but in regards to point 3, on `componentDidMount` and anytime `componentWillReceiveProps` has different props, we could call refine.

**Comment by zackify** [comment]
Awesome work! When will this be pushed to npm?

**Comment by vvo** [comment]
It has been pushed to npm (3.0.0): https://discourse.algolia.com/t/react-instantsearch-3-0-0/503/1
