### ISSUE TITLE
Update the build stack

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1866]

**Comment by vvo** [comment]
Done on react-instantsearch, to be done on instantsearch.js

**Comment by bobylito** [comment]
Webpack 2 or rollup. Seems like rollup is more fit to libraries cc @Haroenv @rayrutjes

**Comment by Haroenv** [comment]
my vote goes to rollup here

**Comment by vvo** [comment]
From the last experimentations of @rayrutjes, we should use rollup for libraries when feasible (= no heavy webpack loaders we depend on).

**Comment by bobylito** [comment]
Well we did some upgrade in v2. Let's revisit that later. Closing for now.
