### ISSUE TITLE
Update SearchState from <Configure />

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch.js#1876]
**Bug: What is the current behavior?**
When you pass an option to `<Configure />`, it is applied and works great! But onSearchStateChange isn't called. This means anyone sending someone else a url to a search will have different results if they used aroundLatLong or insideBoundingBox.

**Bug: What is the expected behavior?**
Pass any configure options to onSearchStateChange

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using?**
2.2.1

**Comment by vvo** [comment]
Yes we should do that, this is linked to #1863

**Comment by vvo** [comment]
I am closing this since I already had created the corresponding issue :).
