### ISSUE TITLE
Adding a <Panel/> component

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1881]
**Use case:**

You want to add a title to a refinement list and want to be able to hide it when there's no refinement to display. 

**Api:**

Having a  `<Panel/>` component accepting a prop `title`. When the encapsulated widget has no refinement to display, then we will add a class at the panel level. 

**Usage:**

```js
<Panel title="category">
    <RefinementList attributeName="category"/>
</Panel>
``` 

**Possible Implementation:**

The `<Panel/>` could pass to its child a function expecting a boolean. It will be the responsibility of the children to call it when needed, for example, when it is unmounted.

**Identified Widgets:**

* CurrentRefinements
* HierarchicalMenu
* Menu
* RangeInput
* RefinementList
* StarRating
* MultiRange

**Comment by vvo** [comment]
👍  I wonder how the implementation could look like, good luck!
