### ISSUE TITLE
Some links before titles cannot be clicked anymore

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1886]
On https://community.algolia.com/instantsearch.js/react/widgets/CurrentRefinements.html you cannot click on view in storybook, there's a big ::after rule that is blocking this.

CC @mikaa123 it's back :) Maybe you can pair with @LukyVj to solve this. Luckily there's now auto deployment of PRS so we can triple check before merging.

Thanks

- [x] links should work
- [x] anchors should scroll at the right position

**Comment by LukyVj** [comment]
I found out why. <details>
![](https://puu.sh/tsZU2/a80bb0e9ec.png)
</details>

--- 
I'm working on a fix 🙂

**Comment by vvo** [comment]
Awesome

**Comment by vvo** [comment]
fixed
