### ISSUE TITLE
How CurrentRefinements works

### ISSUE THREAD

**Issue by vinhlh** [algolia/instantsearch.js#1890]
**Do you want to request a *feature* or report a *bug*?**
Feature || Bug

**Bug: What is the current behavior?**
Assume that we have 2 refinements. Then current refinements can be:
A: A1, A2, A3
B: B1, B2

If I remove B1 (by clicking on CurrentRefinements component), then all A refinements (A1, A2, A3) will be removed automatically too.

**Bug: What is the expected behavior?**
It should only remove B1, right?

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**
2.1.0

**Comment by vinhlh** [comment]
This issue is already fixed in https://github.com/algolia/instantsearch.js/pull/1686

**Comment by vvo** [comment]
awesome
