### ISSUE TITLE
Insert div between hit results

### ISSUE THREAD

**Issue by spindriftwebs** [algolia/instantsearch.js#1891]
Hi, am developing a project using php and instantsearch.js

I'd like to be able to insert a div after every 4 hits that contains an image.  I'm not sure where to start with this but could someone post some sample code ?
I believe it can be achieved using the RenderHandler.

Any help appreciated.

Thanks in advance.  Guy

**Comment by vvo** [comment]
Here's an example doing so: https://jsfiddle.net/vvoyer/cgaoppoe/1/

Let me know if that's sufficient.

**Comment by spindriftwebs** [comment]
Hi, that's fantastic.  Thanks v much !

**Comment by spindriftwebs** [comment]
Thanks for your code but am struggling integrating it.  How would I implement it when using:

search.addWidget(instantsearch.widgets.hits({
    container: '#hits',
    hitsPerPage: 24,
    templates: {
        empty: noResultsTemplate,
        item: hitTemplate
    },
    transformData: function(hit) {
    return hit;
    }
}));

search.start();

var algoliaHelper = search.helper;

Thanks so much.

**Comment by vvo** [comment]
You cannot use it while using the regular hits widget, you will have to use the code I gave you on jsFiddle and work on it using jQuery.

If this is too much of a struggle then I would advise you to ask for general coding help on http://stackoverflow.com/.

RIght now the example is showing you how to implement it using instantsearch.js, if you have more code question StackOverflow is the place to ask them. Thanks!

**Comment by spindriftwebs** [comment]
No worries, I've implemented your solution, thanks v much.

**Comment by spindriftwebs** [comment]
Hi, using your fiddle - https://jsfiddle.net/vvoyer/cgaoppoe/1/

How would I add the pagination widget and specify the number of hits per page ?

Many thanks

Guy

**Comment by vvo** [comment]
@spindriftwebs Can you try to update the jsfiddle and add the pagination widget along with specifying the hitsPerPage parameter? Then if it's not working, let me know.

- pagination: https://community.algolia.com/instantsearch.js/documentation/#pagination see "example" tab
- hitsPerPage: https://community.algolia.com/instantsearch.js/documentation/#initialization see "searchParameters" option

**Comment by vvo** [comment]
If it's not working, please open a new issue.
