### ISSUE TITLE
Google places & radius search

### ISSUE THREAD

**Issue by spindriftwebs** [algolia/instantsearch.js#1892]
Would be great to include google places lookup with a mile radius option when using geo search with a google map that adjusts when searching different cities for example (and within say 100 miles of a particular city)

**Comment by vvo** [comment]
Hi @spindriftwebs thanks for the issue, could you detail a bit more what you want to achieve UX wise and how instantsearch.js is lacking features to do so nowadays?

Please ask your question on discourse: https://discourse.algolia.com/c/instantsearch

Thanks!
