### ISSUE TITLE
Better code formating

### ISSUE THREAD

**Issue by LukyVj** [algolia/instantsearch.js#1894]
I would like to see a better code formating related to the css classes. 

| This is the props  | This is the css classes |
| ------------- | ------------- |
| ![](https://puu.sh/twx6H/a6e7167021.png)  | ![](https://puu.sh/twx78/8e7501b5de.png) |

You can see that, it's really visually close and if you're looking for a particular css class, for example, it makes it hard to differenciate from a prop table or any other api-entry. 

| What we have  | What we should have |
| ------------- | ------------- |
|  ![](https://puu.sh/twx78/8e7501b5de.png) | ![](https://puu.sh/twxoj/4b120f3989.png) |

**Comment by vvo** [comment]
WFM, go for PR.
