### ISSUE TITLE
Should hide pagination whenever having 1 page or no results

### ISSUE THREAD

**Issue by vinhlh** [algolia/instantsearch.js#1897]
**Do you want to request a *feature* or report a *bug*?**
Maybe a Bug

**Bug: What is the current behavior?**
There are 2 contexts:
- Having only one page: should not display pagination, it has no meaning.
- Don't have any results: when users click on a link which in the past it has some results, but currently it doesn't; or navigate to a menu with 0 items.

**Bug: What is the expected behavior?**
Should not display page nagivation.

**Bug: What browsers are impacted? Which versions?**
Chrome latest.

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**
2.2.4

**Comment by vvo** [comment]
@vinhlh We are planing on adding a `noRefinement` css class to any widget that has a state where nothing can be clicked that will refine the search (no more items available, pagination has one page, things like that).

What do you think?

**Comment by vinhlh** [comment]
LGTM 👍

**Comment by vvo** [comment]
Merged, will go live this week, we will do announcement on https://discourse.algolia.com/c/instantsearch

**Comment by vvo** [comment]
Merged, will go live this week, we will do announcement on https://discourse.algolia.com/c/instantsearch
