### ISSUE TITLE
Is it possible to search multiple attributes or merge two attributes?

### ISSUE THREAD

**Issue by JonnyTurnerUK** [algolia/instantsearch.js#1899]
Bit of a confusing one so hopefully it makes sense. 

We have two attributes that need searching from one select dropdown (custom widget built by @vvo). These are modelSimple and selectVehicle.modelSimple. The way the index is set up, we need to use one dropdown to search values within both. Is this possible? The widget only has 'attributeName', not 'attributes'.

One theory is to get the value of a toggle in jQuery and then show / hide separate fields. Doing it this way we query whether or not the toggle item is active (hasClass). This triggers twice and doesn't appear to be reliable so we've reached a bit of a hurdle that we're working on.

Does anybody know if this is possible? Or which is the best approach for something like this?

Thanks!

**Comment by vvo** [comment]
@JonnyTurnerUK Can you provide UI mock up of what you are trying to build? That would help understand this issue. Thanks

**Comment by JonnyTurnerUK** [comment]
Hey @vvo, sorry, just realised this had been replied too. In this case, we've asked the client to modify their product feed to accommodate as it was quite a hacky approach. They basically want a radio group of three options, however, the three options are collected from two different elements. Definitely a unique case! ;)

**Comment by vvo** [comment]
Thanks!
