### ISSUE TITLE
Stats widget: query empty or doesn't exist

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#190]
I am not able to display the query with the stat widget with custom template.

**Comment by vvo** [comment]
I am sorry I did not get the issue here can you explain more what works/doesn't works? Are you saying that you miss the "results.query" data in the template passed to stats?

**Comment by vvo** [comment]
You should be able to access data.query, if not then there's a bug yes, let me know

**Comment by maxiloc** [comment]
{{query}} and {{data.query}} are both not working

**Comment by maxiloc** [comment]
I check in the code, the variable seems to be there, so I guess it's empty

**Comment by redox** [comment]
Please provide the associated code you've used to spot that issue; I cannot reproduce it with the following code:

```js
search.addWidget(
  instantsearch.widgets.stats({
    container: '#stats',
    templates: {
      body: require('./templates/stats.html')
    }
  })
);
```


```html
<div>
  XXXXX:
  {{query}}
  {{#hasNoResults}}No results{{/hasNoResults}}
  {{#hasOneResult}}1 result{{/hasOneResult}}
  {{#hasManyResults}}{{#helpers.formatNumber}}{{nbHits}}{{/helpers.formatNumber}} results{{/hasManyResults}}
  found in {{processingTimeMS}}ms
</div>
```

**Comment by maxiloc** [comment]
do not know why I had that, it is working now :smile:
