### ISSUE TITLE
How can I use the getQueryStringFromState function?

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#1901]
Hello,

I want to use the https://community.algolia.com/algoliasearch-helper-js/reference.html#algoliasearchHelper.module:url.getQueryStringFromState function but I keep getting the message that this function doesn't exist. 

I'm using it in the render function of a widget and when I console.log the args passed in the render function I can't find the url module in the helper data.

What am I doing wrong?

I'm trying to build a extension that handles the <link rel="next" and rel="prev" in the <head> but to do that I need to get the query string - so I can get the right url for the next pages with their filters. Im using instantsearch.js 1.10.3

Tried to add this to discourse.algolia.com but I keep getting 403 error.

**Comment by bobylito** [comment]
Hi @Maaark thanks for reporting this issue.

The url module of the JS Helper is not available on the Helper instance. Since the helper as a module is not accessible either, I doubt you'll be able to get the function you want. We could expose this package with instantsearch, maybe. Any thoughts on that @vvo ?

Can you tell us more about what you're trying to build?

**Comment by vvo** [comment]
> Can you tell us more about what you're trying to build?

Yep we need this also to understand more deeply the use case.

> We could expose this package with instantsearch, maybe. Any thoughts on that @vvo ?

Yes this could be exposed on the instantsearch module or just on the helper instance (search.helper...)

**Comment by Maaark** [comment]
@vvo You helped me to build a custom pagination module that works with a 'show more' button.  So when you click this button you will get the second page appended to the first page.

After this click there is a query string appended to the current url, but I need to get the query string for the current url so I can use it for my function to build the link rel="prev/next" elements (https://support.google.com/webmasters/answer/1663744?hl=en)

**Comment by vvo** [comment]
@Maaark Can you create a small jsFiddle describing where you are so far and what is the missing piece? An example load more demo with then a small comment saying "Here I would want to display/get .."

Thanks

**Comment by bobylito** [comment]
Closing this issue for now.
