### ISSUE TITLE
item.label not present for Range under CurrentRefinement

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1908]
<img width="550" alt="yep" src="https://cloud.githubusercontent.com/assets/2096101/22269726/ee69ec5e-e28c-11e6-9eea-2b20b56bdb7a.png">

My Range component is the same that the component provided in the documentation..

I suppose that we missed associate `label` field 😄

live demo at https://windtoday.co

**Comment by mthuret** [comment]
Hi @Kikobeats,

That's because the label is directly the string "25 <= price <=282" and for the `Range`, there's no child to display contrary to the `Refinement List`.

If this structure is not what you want, you can use the [`connectCurrentRefinements`](https://community.algolia.com/instantsearch.js/react/connectors/connectCurrentRefinements.html) connector to define your own. By using the connector, you will have access to the prop `items` that have a structure like: 

```json
[{
    "attributeName": "category",
    "label": "category: ",
    "currentRefinement": ["Sails"],
    "items": [{
        "label": "Sails"
    }]
}, {
    "label": "4.99 <= price <= 699",
    "currentRefinement": {
        "min": 4.99,
        "max": 699
    },
    "attributeName": "price"
}]
```

**Comment by Kikobeats** [comment]
Could be possible modify Range implementation to works as expected? looks a little tricky

**Comment by Kikobeats** [comment]
In the coded that you paste, `category` match with `attributeName` and also is present in the Range and not associated with the label so I suppose that something is wrong.

Also I checked  [CurrentRefinements#transformItems](https://github.com/algolia/instantsearch.js/blob/v2/packages/react-instantsearch/src/components/CurrentRefinements.js#L16) beacuse maybe I can use this method for make a workaround but currently is not being used in the implementation. Do you think that is a bug?

I saw that because also I want to avoid this case:

<img width="195" alt="screen shot 2017-01-25 at 19 45 17" src="https://cloud.githubusercontent.com/assets/2096101/22304218/d8119704-e336-11e6-9ce0-a37a15a5cf5a.png">

boom.type → "Boom Type"

**Comment by mthuret** [comment]
I'm not sure to follow you entirely on your first point. 

`transformItems` is used by the connector. Our widgets are using under the hood our connectors. 
If you're using the props and modify the list of items, then the modification should be taken into account. Did you try it?

**Comment by Kikobeats** [comment]
Oh sorry, I did something wrong but now `CurrentRefinements#transformItems` works as expected, I did this workaround:

```jsx
function isRange (item) {
  return item.currentRefinement.max && item.currentRefinement.min
}

function transform (item) {
  return {
    label: `${item.attributeName}: `,
    items: [{'label': item.label}]
  }
}

function transformItems (items) {
  return items.map(function (item) {
    if (isRange(item)) item = transform(item)
    return item
  })
}
```

My point is, could be possible encapsulate this inside `Range` component? Just the thing that I'm doing ins transforming the item from Range into the item expected by `CurrentRefinements` to be rendered as I expected.

I don't know if I can define something inside Range component for avoid that

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
