### ISSUE TITLE
Docs Website: when the site is resized in half, design issue occurs.

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1911]
Example: 

![image](https://cloud.githubusercontent.com/assets/6885378/22298328/68bd7dca-e320-11e6-8a43-115c09dc5d93.png)

**Comment by LukyVj** [comment]
My fix didn't worked ?

**Comment by mthuret** [comment]
Not entirely. I opened an issue. We need to list all the little glitch inside it.

**Comment by LukyVj** [comment]
Aight 
let me know

**Comment by vvo** [comment]
Cannot reproduce, only missing part is that the sidebar button is not working if you resize dynamically, well it's no big deal
