### ISSUE TITLE
API Proposal: automatically add classes for levels of RefinementList

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#192]
Following #162, we should provide a way to easily target a level of RefinementList (say, when using hierarchicalFacet) as a class.

So something like this:

```html
<div class="hierarchicalFacet-lvl0">
  <div class="hierarchicalFacet-item">Fruits
      <div class="hierarchicalFacet-lvl1">
          <div class="hierarchicalFacet-item">oranges</div>
          <div class="hierarchicalFacet-item">bananas</div>
      </div>
  </div>
</div>
```

cc @maxiloc would that fit?

**Comment by maxiloc** [comment]
:+1: yes works for me, maybe I would only put "lvl0" but I am ok with what you proposed

**Comment by pixelastic** [comment]
I wonder if this is really needed. Can't you nest your CSS classes to only target the level you want?

```css
.hierarchicalFacet {
}
.hierarchicalFacet .hierarchicalFacet {
  margin-left: 20px;
}
```
