### ISSUE TITLE
Not able to unselect item in MultiRange

### ISSUE THREAD

**Issue by RyanTheAllmighty** [algolia/instantsearch.js#1934]
**Do you want to request a *feature* or report a *bug*?**
Maybe both? May not be something considered before now or something that was missed out in testing.

**Bug: What is the current behavior?**
When an item in a `<MultiRange />` is selected it cannot be unselected by clicking the same item again.

**Bug: What is the expected behavior?**
When I click on an already selected item in a `<MultiRange />`
Then that item should unselect and no longer be filtering results based on it

**Bug: What browsers are impacted? Which versions?**
From what I can tell this is not something which is browser based

**Feature: What is your use case for such a feature?**
To be able to unselect an active Range without having to select another range

This issue can be seen on the [React Storybook](https://community.algolia.com/instantsearch.js/react/storybook/?selectedKind=MultiRange&selectedStory=default&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs) for the MultiRange component.

You can select one of the items (such as <$10) but then cannot unselect it.

While this could be unselected using the `<CurrentRefinements />` widget, I believe it's better suited to also have it available in the `<MultiRange />` component also.

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**
2.2.5

**Comment by RyanTheAllmighty** [comment]
Alright didn't test correctly and at least when manually connecting a `<MultiRange />` component you can simply run `this.props.refine()` which will remove the refinement on the MultiRange.

Not sure if this is something you guys wish to do for your own base implementation of MultiRange component or not, either way I'll leave it up to you guys as to if you close this or not.

**Comment by mthuret** [comment]
Hi @RyanTheAllmighty, thank you for reporting this 👍  I assume you were able to implement the behavior of your choice using our `connectMultiRange`connector? If you have a little gif to share it would be nice of you :)

As for should we implement this behaviour on our default `<MultiRange/>`, I agree it could be nice to be able to remove a selected range without being force to use <CurrentRefinements/>. Today you are able to do it by adding another item that will be the largest range. But maybe that's something we can compute on our side.

WDYT @vvo and @bobylito?

**Comment by vvo** [comment]
The storybook example is self convicing, we should be able to unselect one value. But I may not have the full picture in mind. Thoughts?
