### ISSUE TITLE
Custom Widgets

### ISSUE THREAD

**Issue by vinhlh** [algolia/instantsearch.js#1941]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
Example, I want to create a menu for `State` facet, I have to do these steps:
```js
// create a custom menu
const MenuContainer = connectMenu(Menu)

// then use it as
<MenuContainer attributeName="state" />
```
When I need to create a custom widget, I could only use this widget for a specified facet, not for all facets. It means `Menu` component is how to display my State facet (it should be named `StateMenu`)
Notice: that there are a repeat step `attributeName="state"`.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
It's great if providing an API option like this:
```js
// create a custom menu
const StateMenuContainer = connectMenu(StateMenu, { attributeName: 'state' })

// then use it as
<StateMenuContainer/>
```

**Comment by vvo** [comment]
@vinhlh Thanks for opening this issue.

We took this approach so one could do:

```jsx
const AwesomeRefinementList = connectRefinementList(AwesomeRefinementListComponent);

<AwesomeRefinementList attributeName="brands" />
<AwesomeRefinementList attributeName="materials" />
```

And this actually works, if it does not then we failed somewhere, open a bug.

instead of

```jsx
const Brands = connectRefinementList(AwesomeRefinementListComponent, {attributeName: 'brands'});
const Materials = connectRefinementList(AwesomeRefinementListComponent, {attributeName: 'materials'});

<Brands />
<Materials />
```

But if you like it, you could just do:

```jsx
const AwesomeRefinementList = connectRefinementList(AwesomeRefinementListComponent);
const Brands = <AwesomeRefinementList attributeName="brands" />;
const Materials = <AwesomeRefinementList attributeName="materials" />;

<Brands />
<Materials />
```

Is you proposal bringing or coming from anything else than syntax preference?

**Comment by vinhlh** [comment]
yep, only syntax
