### ISSUE TITLE
Example of overriding createURL for connectMultiRange

### ISSUE THREAD

**Issue by vinhlh** [algolia/instantsearch.js#1942]
as default, it creates a query param like `?date_created=1485878400%3A1488297599`
do we have any way to use label as query param? `?date_created=Today`

**Comment by bobylito** [comment]
What if you could set functions that let you change the object to the form you want? Something like:

```js
instantsearch({
  urlSync: {
    serialize: function(state) {
      var date_created = state.getNumericRefinement('date_created', '=');
      var isToday = isToday(date_created);
      return {
	date_created: isToday? 'Today' : date_created
      };
    },
    deserialize: function(urlAsObject, state) {
      if (!urlAsObject.date_created) return state;
      if (urlAsObject.date_created === 'Today') return state.addNumericRefinement('date_created', '=', today());
      else {
        return state.addNumericRefinement('date_created', '=', urlAsObject.date_created);
      }
    }
  }
});
```

The state being a [SearchParameters](https://community.algolia.com/algoliasearch-helper-js/reference.html#searchparameters) which is the the representation of the state of the search.

**Comment by bobylito** [comment]
@vinhlh Is it related to instantsearch.js or react-instantsearch? :D

**Comment by vinhlh** [comment]
@bobylito it's `react-instantsearch`

**Comment by bobylito** [comment]
👍 disregard my other comment then :D

**Comment by bobylito** [comment]
react-instantsearch does not provide any mechanisms for url handling, therefore this sort of logic needs to be implemented in your url mapping functions.

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
