### ISSUE TITLE
Recipe: lazy loading images

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1945]
Create a recipe that shows how to load images in an efficient way when dealing with an instant search interface in React.

**Comment by bobylito** [comment]
Isn't that beyond the scope of react-instantsearch?

**Comment by vvo** [comment]
Since we are providing a lib that refreshes a webpage at each keystroke I thought it would be nice to show people how to easily use a lazy loading lib with it. And prove that it's actually working.

**Comment by bobylito** [comment]
That's cool indeed!

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
