### ISSUE TITLE
Configure Bugs in React-Instantsearch

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch.js#1950]
**Bug: What is the current behavior?**

Configure throws errors on page changes when it has no props.

<img width="707" alt="screen shot 2017-02-06 at 1 14 20 pm" src="https://cloud.githubusercontent.com/assets/449136/22660086/37556a16-ec6e-11e6-8a82-a9c425817d6f.png">

Also, when you change the props passed to Configure, it does not call onSearchStateChanged, so the url isn't updated until changing the query or something else happens.

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**

v3.0.0

**Comment by mthuret** [comment]
Hi @zackify, 

I'll fix the cleanUp bug asap. For my understanding does that mean that in your use case, at some point, you have something like this: `<Configure />`? 

Also you're right, changing the props of `Configure` by modifying the `searchState` will not trigger `onSearchStateChange`. But it should trigger an update with the correct parameter? If that's not the case, can you detail your use case? 

Also can you confirm that if you change for example the aroundLatLng parameter directly in the URL and reload the page it's correctly taken into account? 

Thanks :)

**Comment by zackify** [comment]
Yes, it takes that into account. I have a location field that will set a bounding box or lat / long. When you clear it out, it removes the props on configure. So yes, at some points configure is rendered without anything. 

When I am setting a prop on configure, it is not calling onSearchStateChanged until I change the query field, that triggers onSearchStateChanged, and puts the configure params in the url. Hope that helps!

**Comment by mthuret** [comment]
Are you using the props `searchState` on the `<InstantSearch/>` root component? 

Here's a little example with pseudo code: 

```js
constructor() {
    super();
    this.state = {searchState: //parse the url here};
  }

  onSearchStateChange = searchState => {
    //change the configure values inside search state
    //update the URL
    this.setState({searchState});
  };

  render() {
    return <InstantSearch
      appId=""
      apiKey=""
      indexName=""
      searchState={this.state.searchState}
      createURL={this.createURL.bind(this)}
      onSearchStateChange={this.onSearchStateChange.bind(this)}
    >
      <Configure aroundLatLng="5, 2.3522" />
    </InstantSearch>;
  }

``` 

By doing that, you will first modify the search state according to your needs, then update the url with the new values and then do a `setState` on the `searchState` to trigger a new rendering of the page. Can this works for you?

**Comment by zackify** [comment]
I thought the whole point of configure is that you change the props on it
and your app updates with whatever props you pass to it. That's how it
worked in 2.2.5. It just didn't trigger onSesrchStateChanged. In v3 it
errors when you have it rendered with no props and doesn't trigger a search
state changed. Just confused as to why any time the props change it
wouldn't just call that function. Everything would work perfect. Your
example is doing exactly what my app is. Except I change the props on
configure if they add a location. And as I said, the app reflects that,
just no URL change. Hope that helps.

**Comment by mthuret** [comment]
You're right there's been some miscomprehension. 
I did develop something for the **controlled** mode of react-instantsearch. It's the mode I described earlier. 
It appears that for the **uncontrolled** mode, the one you are using, the `onSearchStateChange` is still not triggered. We're going to fix it.

**Comment by zackify** [comment]
Thanks!!

**Comment by zackify** [comment]
Can you let me know when a release is out? You guys are the best
