### ISSUE TITLE
Configure calls onSearchStateChange and locks up JS thread

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch.js#1960]
Bug: What is the current behavior?

Configure calls onSearchStateChanged nonstop and locks up the browser until a callstack exceeded error happens.

What project are you opening an issue for?

react-instantsearch
What is the version you are using? Always use the latest one before opening a bug issue.

v3.1.0

My guess is it triggers a render, and configure is rendered again, calls search state change again. It should just trigger it if the current configure object is different so this doesnt happen.

last issue: #1950

**Comment by mthuret** [comment]
Hi @zackify, this shouldn't happen normally as we perform a deepEqual when a component receive new props. So if the props didn't changed, the onSearchStateChange shouldn't be trigger infinitely. 

But sometimes depending on the upper component of the `<InstantSearch/>` root component, those infinite loops can still happen, for example in the `react-router v3` recipe I had to implement the `shouldComponentUpdate` lifecycle method. 

Any chance you can provide a small sample to help us understand what's happening with your use case? Maybe you can use this jsfiddle template https://jsfiddle.net/h3nus3gg/?

**Comment by zackify** [comment]
I'll look into this today. The thing is, this component worked perfectly
with no problems in 2.2.5 just never updated the search state. Every part
of my app works minus this now. I was in a rush when I made this issue
because I need it working next week. My bad on not giving you enough info!
I'll post here later today.

**Comment by zackify** [comment]
Here's the problem: I was doing:

```
if (this.state.lastPush && newPush - this.state.lastPush <= THRESHOLD) {
      router.replace(nextSearchState ? `?${string}` : '')
    } else {
      router.push(nextSearchState ? `?${string}` : '')
    }
```

Then set the search state from the location string:


```
<InstantSearch
          indexName={index}
          searchState={qs.parse(location.search.substring(1)}
      ....
```

For some reason this causes an infinite render. I don't think it should. The fix feels hacky. Setting the state on the search component, and blocking a state update when the location is updated:

```
shouldComponentUpdate (nextProps) {
    if(this.props.location.pathname === nextProps.location.pathname) return false
    return true
  }
```

Why would setting the state directly from the url cause problems?

**Comment by zackify** [comment]
This looks like a react router bug, traced it down to passing the location into the pagination connector. Weird, but fixed
