### ISSUE TITLE
Configure keeps values that no longer exist

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch.js#1964]
**Bug: What is the current behavior?**

- Pass { insideBoundingBox } to Configure
- Remove it and pass only { aroundLatLng }
- Configure is put into the url twice: 

```
"&configure[insideBoundingBox]=42.0095169,-114.131211,32.528832,-124.482003&configure[aroundLatLng]=33.7489954,-84.3879824"
```

I expect if there's no props on configure, the values will be removed from the search state :) 

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**

3.1.0

**Comment by bobylito** [comment]
@zackify thanks for submitting this issue. Indeed the configure is only adding new elements.

@mthuret What about we cache the previous configure props and create a delta that we would then apply? This mean that when a property is removed we will know it instead of being left in the state it was previously set.

In the meantime, @zackify, can you to force the value of `insideBoundingBox` to `''` at step 2?

**Comment by mthuret** [comment]
Yes right now, the configure props in the search state are cleaned only if the <Configure/> widget is unmounted. 

@bobylito Another possibility would be to pass the previous props to the transitionState method. 
Regarding the caching way, how will you handle the fact that we can have a multiple <Configure/> instance?

**Comment by bobylito** [comment]
@mthuret `this` is available and is "persisted" independently for each instance in `getProvidedProps`. This is used in [infinite-hits](https://github.com/algolia/instantsearch.js/blob/v2/packages/react-instantsearch/src/connectors/connectInfiniteHits.js)

**Comment by zackify** [comment]
Any progress on this? This is breaking a search feature we actually pushed to production. Why is it too hard to simply take the search state from the url on mount? Pretty sure this would fix the other issue I have about the location state not being there on a refresh. Thanks :)

**Comment by mthuret** [comment]
Hi @zackify,

As I mentioned here: https://github.com/algolia/instantsearch.js/pull/1967 it should work to read Configure props from the search state only when mounting a component, it's just that its needs further development and architecture. But be sure we are going to plan this.

In the mean time, can you tell me if reading the search state on your side and pass the right props to the Configure widget can work? I did a little geo search recipe illustrating it here: https://github.com/algolia/instantsearch.js/tree/v2/packages/react-instantsearch/examples/geo-search

Thanks :)

**Comment by zackify** [comment]
Thanks, I will try parsing it out of the search state myself which should
work for now! I'll reply when I do that.


Thanks,
Zach

-- 
Zach Silveira
Senior Partner
Encryption, Inc <https://encryption.io>
Office: 404-602-0322

**Comment by zackify** [comment]
This works just fine for now. Thanks

**Comment by mthuret** [comment]
Great that's nice to hear @zackify! 

I close this issue. You can follow this one instead regarding the mounting event for configure https://github.com/algolia/instantsearch.js/issues/1955).
