### ISSUE TITLE
Configure Values not applied on page refresh

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch.js#1965]
Bug: What is the current behavior?

- Set a value on configure
- Change is reflected:

<img width="1649" alt="screen shot 2017-02-09 at 1 13 06 pm" src="https://cloud.githubusercontent.com/assets/449136/22796761/9af5abfa-eec9-11e6-8745-3388ae5dc108.png">

- Refresh the page, results not using the value:

<img width="1646" alt="screen shot 2017-02-09 at 1 13 19 pm" src="https://cloud.githubusercontent.com/assets/449136/22796743/8ffa56d8-eec9-11e6-9f8f-c1adc68a0df5.png">

react-instantsearch

3.1.0

P.S. I know I said it was working before, but it's not currently. I might have accidentally thought it was working.

**Comment by mthuret** [comment]
@zackify: can you share a sample of code showing how you actually parse your configure parameters and build your `<InstantSearch/>` instance with `<Configure/>` ?

**Comment by vvo** [comment]
You can do so with this: https://jsfiddle.net/vvoyer/ar80rgpc/2/

**Comment by zackify** [comment]
Sorry, didn't notice the replies. The configure widget has no props on a page reload, the data is just in the search state in the url. Shouldn't it still be added to the search state even though configure is empty on a page load?

**Comment by vvo** [comment]
We made the Configure widget so that there's only one way to have parameters applied: you have to set props on it.

So the best option is to read them from the state then forward them to the Configure widget. I understand this is then not consistent with other widgets like Menu which will take the refined value into account.

We will have to revisit this later on then.

**Comment by mthuret** [comment]
The way configure behaved will be improved later, see https://github.com/algolia/instantsearch.js/issues/1955.

I'm closing this one in the mean time.
