### ISSUE TITLE
SearchBox doesn't have icons in Safari

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#1968]
**Bug: What is the current behavior?**

In Safari the icons of the search box don't show up

Visible in for example: https://community.algolia.com/instantsearch.js/react/storybook/?selectedKind=SearchBox&selectedStory=default&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs

<img width="318" alt="screen shot 2017-02-10 at 17 49 01" src="https://cloud.githubusercontent.com/assets/6270048/22835513/58f36332-efb9-11e6-8510-4646fd1ef4f1.png">

**Bug: What is the expected behavior?**

The search box has buttons with icons like in Chrome

<img width="321" alt="screen shot 2017-02-10 at 17 49 21" src="https://cloud.githubusercontent.com/assets/6270048/22835506/52829d1a-efb9-11e6-9b8a-3cae023471c8.png">

**Bug: What browsers are impacted? Which versions?**

All current Safari versions can't display svg inside a `<button>`, mve:

http://codepen.io/anon/pen/mRQMzW

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**

3.1.0

**Comment by vvo** [comment]
> All current Safari versions can't display svg inside a <button>, mve:

Thanks a lot you are the new safari detective! It's perfect :)

What about we use an `<img src=svg` instead?

**Comment by Haroenv** [comment]
I was missing the actual error and assuming svg was the problem, opening PR with the fix in a few minutes
