### ISSUE TITLE
hierarchicalMenu issue after check a subcategory

### ISSUE THREAD

**Issue by seulZarraga** [algolia/instantsearch.js#1969]
I have about 5 categories and each category has another 2 or 3 subcategories. If I check a category the search runs fine but when I check a subcategory the search restart and every category and subcategory appears unchecked.

This is my code:

search.addWidget(
            instantsearch.widgets.hierarchicalMenu({
                container: '#category',
                attributes: ['get_category.lvl1', 'get_category.lvl2', 'get_category.lvl3'],
                sortBy: ['name:asc'],
                templates: {
                    item: function (data) {

                        checked = ""

                        if (data.isRefined)
                            checked = "checked"

                        return '<label style="margin-left: 35px;" class="checkbox filter-checkbox"><input type="checkbox" value="' + data.name + '" data-toggle="checkbox" ' + checked + '> ' + data.name + '</label>'
                    }
                },
                cssClasses: {
                    body: 'filterCheckbox'
                }
            })
        );

**Comment by vvo** [comment]
Hi @seulZarraga, do you think you could create a live example here: https://jsfiddle.net/vvoyer/ar80rgpc/2/

**Comment by danielbarroso1989** [comment]
It was my fault, I was using checkbox instead a tags

**Comment by seulZarraga** [comment]
It was my fault, I was using checkobox intead a tags
