### ISSUE TITLE
infiniteHits remember previous pages

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1972]
I used the issues search and I didn't found a issue related with that

![](https://d3uepj124s5rcx.cloudfront.net/items/1r3I292U0q321Z2o193q/Screen%20Recording%202017-02-13%20at%2009.49%20am.gif?v=d13f7c0d)

In the current implementation, when I press `Load More` button the next page is fetched (and the query param in the url is updated) but previous pages are not remember in the url, so if you refresh now the browser, just the browser fetch the current page.

Could be possible remember the pages? Like yea, I'm in the 2 page, but under refresh I want to fetch all the previous page.

**Comment by bobylito** [comment]
Hi @Kikobeats thanks for the issue.

Actually I'm wondering what is the actual intent of a user when using an infinite hits based page. What does the user tries to do? On pinterest, users can't bookmark a page, they will only be able to get the URL for the first page.

WDYT @LucasC @mthuret @vvo ?

**Comment by Haroenv** [comment]
I think a good solution would be, instead of reloading everything, is to show a "load previous" if possible. Can we do that?

**Comment by LucasC** [comment]
Tough question; I had to do a bit of research and didn't find anything really conclusive. Most "Load More"/Infinite Scroll implementations don't keep tab on a current "page".
As long as we make sure we're not breaking the behavior of someone clicking a result and pressing the back button, we can indeed modify how our implementation works.

The "Load Previous" would generate too much confusion: where would the results go, how is it different from "Load Next", etc...

Kikobeats' suggestions sounds right: if you were to share the link to a colleague, you would expect him/her to see the same thing as you - thus loading all the previous content too.

**Comment by vvo** [comment]
I would say that on infinite like interfaces you should not try to sync the url with the current "page" (= scroll position). Twitter does not do it for instance and I think that's the right move here.

If you want bookmakable pages then use the load more button but without having an infinite scroll example, replace the results everytime.

What do you think?

**Comment by LucasC** [comment]
True @vvo; However, Twitter does not sound as a good example - it's a personalised feed, so sharing it w/ URL doesn't make sense.
But again, I don't have a strong recommendation on that one as long as we don't break the "Back" behavior.

**Comment by Kikobeats** [comment]
For me the point is:

> If you were to share the link to a colleague, you would expect him/her to see the same thing as you.

Ideally,  adding an additional parameter to `infiniteHits`, like:

```
<infiniteHits rememberPreviousPages />
```

This parameter enable remember the initial page in the query. Because you also have the current page, the url looks like:

```
https://windtoday.co/?initialPage=1&page=2
```

Then when you share the url, the engine determinate how many pages to fetch

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
