### ISSUE TITLE
docsearch doesn't show text in Safari

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#1976]
**Bug: What is the current behavior?**

The docsearch inputted text isn't visible.

I didn't immediately see any reason why it wasn't visible in the inspector

**Bug: What is the expected behavior?**

it should be visible

**Bug: What browsers are impacted? Which versions?**

Safari (I tested 10)

**What project are you opening an issue for?**
- react-instantsearch

safari | chrome
---|---
![screen shot 2017-02-14 at 09 48 18](https://cloud.githubusercontent.com/assets/6270048/22921753/342be0d0-f29b-11e6-98e7-d03919861469.png) | ![screen shot 2017-02-14 at 09 48 38](https://cloud.githubusercontent.com/assets/6270048/22921754/344a6e88-f29b-11e6-9cdb-dda9f288310e.png)

**Comment by vvo** [comment]
@LucasC Any idea why this is the case? Thanks

**Comment by LucasC** [comment]
@vvo I suppose you wanted to tag @LukyVj for this one?
