### ISSUE TITLE
docsearch has the old Algolia logo

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#1977]
**Bug: What is the current behavior?**

![screen shot 2017-02-14 at 09 48 38](https://cloud.githubusercontent.com/assets/6270048/22923550/3ae1205a-f2a2-11e6-86ad-9dd67b1a1bb0.png)

docsearch has the old logo

**Bug: What is the expected behavior?**

docsearch to have the new logo

**Bug: What browsers are impacted? Which versions?**

all

**What project are you opening an issue for?**
- react-instantsearch

**Comment by Haroenv** [comment]
probably fixed by updating docsearch

**Comment by vvo** [comment]
Is this the new logo? 
![image](https://cloud.githubusercontent.com/assets/123822/23279379/e7f24598-f9c9-11e6-8599-bee3e90b94db.png)

Header of react instantsearch has this:
![image](https://cloud.githubusercontent.com/assets/123822/23279679/0200c454-f9cb-11e6-942c-cee076575f7e.png)

Thought both should be the same.

**Comment by vvo** [comment]
Ok no it was never updated: https://github.com/algolia/docsearch

**Comment by Haroenv** [comment]
logo is updated in https://github.com/algolia/docsearch/blob/master/src/styles/_dropdown.scss#L477

**Comment by vvo** [comment]
@Haroenv Actually the logo we are using is inside our own sass files, crazy :D See https://github.com/algolia/instantsearch.js/commit/b116f23dfb247ff39b371512673cb0bd29e97bb7

I am releasing the website, should be fixed soon.
