### ISSUE TITLE
Components that aren't in the storyboard are still linked from the documentation

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#1979]
**Bug: What is the current behavior?**

All components have a link to "show in storyboard", which links to the storyboard without a selected component

**Bug: What is the expected behavior?**

Components that aren't featured in the storyboard don't have a "view in storyboard" link

**Bug: What browsers are impacted? Which versions?**

All

**What project are you opening an issue for?**
- react-instantsearch

**Comment by vvo** [comment]
I am sorry I fail at understanding exactly the issue, do we have bad links somewhere? If so please provide a bad link so I get it :D

**Comment by Haroenv** [comment]
[panel](https://community.algolia.com/instantsearch.js/react/widgets/Panel.html) for example doesn't have a dedicated story

**Comment by vvo** [comment]
> We don't illustrate them through other stories but in their own kind

Way to go for me.

**Comment by Haroenv** [comment]
The only problem is that that link goes to the storyboard at the first story, because `selectedKind=Panel` doesn't exist.

However probably this isn't really a big deal.

url: `https://community.algolia.com/instantsearch.js/react/storybook/?selectedKind=Panel&selectedStory=default`

**Comment by mthuret** [comment]
Alright, so let's create move some stories inside their own kind.

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
