### ISSUE TITLE
Connect* needs stories

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#1984]
**Feature: What is your use case for such a feature?**

using connect as a feature isn’t very easy, because the only example is a connectSearchBox.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

adding stories or other examples about each of the connectors would be very useful in understanding how they work, and how you “should” use them. 

**What project are you opening an issue for?**
- react-instantsearch

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
