### ISSUE TITLE
change isarray to Array.isArray

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#1985]
When installing `react-instantsearch`, you get a warning like this:

```
warning react-instantsearch > algoliasearch > isarray@2.0.1: Just use Array.isArray directly
```

[Array.isArray](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) is supported in IE8+, so this should cover all our users normally.

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**

3.2.0

**Comment by vvo** [comment]
Array.isArray is IE9+ and the algoliasearch client is still IE8+. So we are a bit stuck for now untill we deprectae IE8 completely and in a nice way

**Comment by Haroenv** [comment]
all right, will keep this in mind once we can move.

**Comment by vvo** [comment]
(still thanks for that kind of feedback, it reminds us we need to do some chores here!)
