### ISSUE TITLE
Expose onBlur, onFocus, onKeyDown events out of SearchBox

### ISSUE THREAD

**Issue by vinhlh** [algolia/instantsearch.js#1992]
**Do you want to request a *feature* or report a *bug*?**
Feature for SearchBox

**Feature: What is your use case for such a feature?**
All provided features are good for me, I don't need to create my custom one.
- I use this SearchBox for a Dashboard page, and also Auto Complete.
```js
<Layout>
  <Header>
    <SearchBox />
    <AutocompleteResults />
  </Header>
  <Content />
</Layout>
```
- Actually, I don't need react-autosuggest, as I tried your examples.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
When using this Search Box, I need to know whether users focus/ blur/ press keys (Up, Down, Enter, ...) to implement my own AutoComplete features.
The solution could be inputProps (type = object) property.

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**
3.1.0

What do you think @vvo?
Like https://github.com/vinhlh/instantsearch.js/commit/14cca027cc49e8d3ee23aba02f151e07ac2f61c1

**Comment by Haroenv** [comment]
It should have onInput etc too if it's being exposed

**Comment by bobylito** [comment]
@vinhlh What's the benefit of this approach compared to using the SearchBox connector?

**Comment by vinhlh** [comment]
@bobylito I don't have to duplicate `SearchBox` component to new custom one 💃 It contains a ton of things I need

**Comment by vvo** [comment]
@vinhlh Do you need to also get an event when the "clear" button is clicked?

**Comment by vinhlh** [comment]
Yes, I need @vvo

**Comment by vvo** [comment]
Moving to #2017
