### ISSUE TITLE
beforeSearch hook for SearchBox component

### ISSUE THREAD

**Issue by vinhlh** [algolia/instantsearch.js#1994]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
I saw a similar thing here,
https://github.com/algolia/instantsearch.js/issues/823

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
Could be
```js
this.props.modifyRefine = refine => newRefine
```

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**
3.1.0

**Comment by mthuret** [comment]
Hi @vinhlh 

Can you tell us what particular use case you are interested in that'll need this feature?

Thanks!

**Comment by vinhlh** [comment]
@mthuret I need to `debounce`/`throttle` search query.

**Comment by vvo** [comment]
We did add something similar in instantsearch.js to allow for refine debouncing. This could also be handled via state management at the top of React InstantSearch but it would be better having something closer to SearchBox.

refineHook could fit this, it would allow us to extend it to other widget if we ever want to.

@mthuret What do you think?

**Comment by mthuret** [comment]
@vvo Yes I guess we could have a refine hook that let's you decide to debounce or throttle when you need to. 
It could be at the InstantSearch level, but then you need a way to distinguish where does the event come from, so it might not be that easy to use comparing to a per widget hook.

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
