### ISSUE TITLE
[Question] How to persist Filters

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1996]
Hello folks,

Using an instantsearch application I detected as recurrent user that is a little tidious setup filter every time that I enter at the website. I want to improve the UX!

![](https://d3uepj124s5rcx.cloudfront.net/items/0K0m2f220j3R1f3p333s/Screen%20Recording%202017-02-21%20at%2006.00%20pm.gif?v=1fdf5346)

A simple strategy for that could be, every time that any filter is modified, serialized the value and store it at `localStorage`.

Then, the nex time that the user enter at the main endpoint of the website (this means, with no query params) retrieve the last filters value for localStorage.

Do you think that could be more or less easy to implement?
Do you think that have sense support this feature inside or out of the instantsearch core?

Any opinion is welcome 😄

**Comment by Haroenv** [comment]
this seems pretty similar to what you do when making a url, but instead you'd save it to localStorage, much like done at the Yarn site [here](https://github.com/algolia/yarnpkg-website/blob/use-instantsearch-react/js/src/lib/Search/withUrlSync.js#L40). To read out of it is pretty much the same, that's just setting the initial state (like [this](https://github.com/algolia/yarnpkg-website/blob/use-instantsearch-react/js/src/lib/Search/withUrlSync.js#L27)), but replace the url logic with localStorage logic. I think this should be a decision you make as a developer of a site, not as part of the library, what do you think of that?

**Comment by Kikobeats** [comment]
Thanks for the reference!

Yes, looks totally a decision out of the instantsearch core, just need a way to connect him.

I need to play with the code for understand better the workflow but definetly a good start point 👍

**Comment by vvo** [comment]
@Kikobeats You will have to forward the full saved search state in the searchState prop of the InstantSearch component. That should definitely do it.

It's basically the same thing than for urls as @Haroenv said, but adding another layer that saves it to localstorage.

Let me know if you need more directions and maybe a guide or if that's sufficient then close this issue

**Comment by Kikobeats** [comment]
Thanks for the references guys!

I think with the yarn example is enough. Finally I don't explore more this pattern because I need handle pagination and more stuff, so right now I prefer invest time in other part of the application 👍

**Comment by Haroenv** [comment]
Pagination actually is handled as the p parameter in the yarn example
