### ISSUE TITLE
chore(example): stop promoting the dev example as the gh-pages

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#200]
Everything we show on gh-pages should be easy to read as code, so no build.

Since we still want to keep an easily runnable dev environment and want to present nice things to our users viewing the source, we should stop publishing the example dev app on gh pages.

What we will present is the instantsearch-demo using instantsearch.js which do not have any build process but just regular js files.

TODO:
- [x] remove the gh pages link in the github project description
- [ ] modify the release process to stop pushing the example dev app to gh-pages 

Fixes #197

**Comment by redox** [comment]
I've started a jekyll website based with the content of @bobylito's documentation here: https://github.com/algolia/instantsearch.js/tree/feature/new-site/site

We'll probably host it on `https://community.algolia.com/instant-search/` or something similar.

Why Jekyll?
 - built-in search :) (cc @pixelastic)
 - gh-pages compliant
 - markdown <3
 - ease of development with SASS, live-reload & templates

**Comment by vvo** [comment]
> I've started a jekyll website based with the content of @bobylito's documentation

I wonder, where was this content before because I missed it? In a branch or something?

> We'll probably host it on https://community.algolia.com/instant-search/ or something similar.

What will be the difference with the https://github.com/algolia/instant-search-demo? Seems confusing names (yes we can change them).

I think what I miss is where will we advertise/guide our users towards either:
- github jsdoc
- live documentation
- website widget's documentation
- instant search demo

This seems many different ways to document and not sure we are 

> built-in search :) (cc @pixelastic)

What will be the use of the built-in search for the live documentation website?

> Why Jekyll?

Not against it, if it's easy to push updates and nice for our users that's it.

**Comment by redox** [comment]
I may have explained more what I had in mind.

So:
 - community.algolia.com <=> algolia.github.io  (CNAME): SEO purpose
 - the Github project top link will go to: http://(community.algolia.com|algolia.github.io)/intantsearch.js
 - the live-documentation is the list of widgets, it's the main/simple documentation hosted on the website. Yes this one was in `feat/live-doc` that @bobylito bootstarted
 - the jsdoc will be linked from the website menu as well but it's a reference documentation: only used by advanced users
 - the instant search demo should really stay in the Algolia.com's tutorial, we'll not link to it here. Or at least not in the "main" links

> What will be the use of the built-in search for the live documentation website?

To search for widgets, themes and all other sections we'll have.

**Comment by vvo** [comment]
> the live-documentation is the list of widgets, it's the main/simple documentation hosted on the website

Ok so the live documentation website that we are building in this repository will be the one available on algolia.com also. How will it integrate technically since it's a different codebase from the algolia.com website?

I feel this should live in his own repo in the end, what do you think?

**Comment by vvo** [comment]
Moved to #321
