### ISSUE TITLE
Range slider example in documentation is outdated

### ISSUE THREAD

**Issue by Kolyasya** [algolia/instantsearch.js#2001]
I've tried to use Range slider component example from docs (https://community.algolia.com/instantsearch.js/react/widgets/RangeSlider.html) but there were a lot of errors in a console.
So I found current Range component version in stories and it seems to work fine.

I think that docs component is just outdated, because it worked ok with previous algolia libs versions

**Comment by mthuret** [comment]
Hi @Kolyasya,

Thank you for detecting this. I updated the example with the #2003 PR. :)

**Comment by vvo** [comment]
deployed
