### ISSUE TITLE
The starRating widget doesn't return the right facet counts and results.

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#2002]
Using the starRating widget I've found that the facet counts and the hits returned don't match the selected number of stars.

For instance here, it says that there are 12 results with 4 stars and more, but in the end, when selecting this filter, it shows 14 hits, and not 12.
![image](http://g.recordit.co/TSuFW2ohub.gif)

The version with the bug can be accessed at http://educated-cherries.surge.sh/default_version/?q=go%20pro&hPP=10&idx=bestbuy&p=0&dFR%5Bfree_shipping%5D%5B0%5D=false&is_v=1

**Comment by bobylito** [comment]
Good news @seafoox I reproduced the bug while testing the new connector feature. I will fix it in this branch first but since it's not gonna be released this week, I'm gonna back port it and release a new version.

**Comment by bobylito** [comment]
The bottom of the problem is that the `max` limit attribute was not inclusive in the count. This means that all the values with 5 stars were actually discarded (`max` is set to 5 by default).
