### ISSUE TITLE
Cannot addDisjunctiveFacet from widget init method

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#2004]
I'm trying to add a `disjunctiveFacetRefinement` in my `init` method of a widget.

I initially got an error stating > productType.name is not defined in the disjunctiveFacets attribute of the helper configuration.

So, I tried to add it with `state.addDisjunctiveFacet('productType.name');`. No luck, same error.
However, if I manually `.push` that on to the array, it works. 

Why is that? Bug, or am I doing something wrong?

```
export let widget = function widget(options) {
  return {
    init: function({helper, state}) {

      // This doesn't work
      state.addDisjunctiveFacet('productType.name');

      // This works
      state.disjunctiveFacets.push('productType.name');
      
      helper.addDisjunctiveFacetRefinement('productType.name', 'Kayak');
    },
  };
};

```

>>>
"instantsearch.js": "^1.10.3",
"algoliasearch-helper": "^2.18.1",

**Comment by vvo** [comment]
@timkelty What you need to do:

```js
instantsearch({
  searchParameters: {
    disjunctiveFacets: ['facetName']
  }
})
```

Then you can just use helper. addDisjunctiveFacetRefinement.

That should do it.

**Comment by timkelty** [comment]
Right, I discovered I can do that in my `getConfiguration` method as well.

So I have it working, but still leaves me wondering when _can_ you use the `addDisjunctiveFacet` method?

**Comment by vvo** [comment]
You should be able to use helper.addDisjunctiveFacet in init method followed by helper.addDisjunctiveFacetRefinement in same init method but you'd have to call .search() also I guess.

**Comment by bobylito** [comment]
Ok for future reference, helper.state.addDisjunctiveFacet creates a new state that's why it's not working. To make it work, one should:

```js
helper.setState(helper.state.addDisjunctiveFacet);
```

When adding the disjunctive facet you don't need to do a `search()` in the init, a subsequent search will be done anyway.
