### ISSUE TITLE
jQuery pagination and hits per page

### ISSUE THREAD

**Issue by spindriftwebs** [algolia/instantsearch.js#2008]
Hi, using this fiddle created by Vincent - https://jsfiddle.net/vvoyer/cgaoppoe/1/

How would I add the pagination widget and specify the number of hits per page ?

Many thanks in advance for any help.

Guy

**Comment by vvo** [comment]
Answered here: https://github.com/algolia/instantsearch.js/issues/1891#issuecomment-283031853
