### ISSUE TITLE
Search box cursor is moved to the end with enabled urlSync

### ISSUE THREAD

**Issue by JanPetr** [algolia/instantsearch.js#2012]
**Do you want to request a *feature* or report a *bug*?**

*Bug*

**Bug: What is the current behavior?**
When the `urlSync` is enabled, every time URL is updated the cursor is moved to the end of the input field at each key press. So it's nearly impossible to edit query from it's beginning.

Reproduce-able on https://jsfiddle.net/JanPetr/pw2s7zcw/3/ - try to search for "a", then move the cursor on the beginning and add any character. Will see, that the cursor will jump to the end from it's current position.
When you disabled `urlSync` it works as expected.

The same happens on https://magento.algolia.com/catalogsearch/result/?q=shirt

Related Magento issue - https://github.com/algolia/algoliasearch-magento/issues/774

**Bug: What is the expected behavior?**
I expect the cursor to stay on the same position.

**Bug: What browsers are impacted? Which versions?**
At least Google Chrome 56.0.2924.87 (64-bit).
On Firefox 47.0.1 it works OK.

**What project are you opening an issue for?**
- instantsearch.js

**What is the version you are using? Always use the latest one before opening a bug issue.**
https://cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.js

**Comment by vvo** [comment]
Thx clearly a critical bug, tackling it now

**Comment by vvo** [comment]
fix incoming

**Comment by vvo** [comment]
released as 1.11.2

**Comment by bobylito** [comment]
@SenenLT any luck with the new version?

**Comment by SenenLT** [comment]
Works! Thanks Team
