### ISSUE TITLE
Pagination widget showNext and showLast disable problem

### ISSUE THREAD

**Issue by chriscalip** [algolia/instantsearch.js#2014]
Requesting to backport to v1 the bug fix (Pagination widget showNext and showLast disable problem #1938) found on v2 and v3.
https://github.com/algolia/instantsearch.js/issues/1938

Do you want to request a feature or report a bug?
bug
Bug: What is the current behavior?
In Pagination widget showNext and showLast are not disabled when number of hits is 0
Bug: What is the expected behavior?
To be disabled.
Bug: What browsers are impacted? Which versions?

Feature: What is your use case for such a feature?

Feature: What is your proposed API entry? The new option to add? What is the behavior?

Calculation for total pages:
https://github.com/algolia/instantsearch.js/blob/v2.2.5/packages/react-instantsearch/src/components/Pagination.js#L110
totalPages = 0 because number of hits is 0 ->
https://github.com/algolia/instantsearch.js/blob/v2.2.5/packages/react-instantsearch/src/connectors/connectPagination.js#L48

https://github.com/algolia/instantsearch.js/blob/v2.2.5/packages/react-instantsearch/src/components/Pagination.js#L110https://github.com/algolia/instantsearch.js/blob/v2.2.5/packages/react-instantsearch/src/components/Pagination.js#L111
lastPage = 0
https://github.com/algolia/instantsearch.js/blob/v2.2.5/packages/react-instantsearch/src/connectors/connectPagination.js#L11
in searchState there is no key = page ->
https://github.com/algolia/instantsearch.js/blob/v2.2.5/packages/react-instantsearch/src/connectors/connectPagination.js#L49
currentRefinement = 1

https://github.com/algolia/instantsearch.js/blob/v2.2.5/packages/react-instantsearch/src/components/Pagination.js#L153
https://github.com/algolia/instantsearch.js/blob/v2.2.5/packages/react-instantsearch/src/components/Pagination.js#L163
disabled = false
Possible solution:
disabled: currentRefinement === lastPage || lastPage <= 1

What is the version you are using? Always use the latest one before opening a bug issue.
v1.11.2

**Comment by chriscalip** [comment]
@vvo per your request.

**Comment by bobylito** [comment]
Could be reproduced in instantsearch.js v2: https://jsfiddle.net/bobylito/cq17ut1r/

As a side note, that's a bit of an outlier as the default behavior is to hide automatically the pagination when there are no results.
