### ISSUE TITLE
Explain how to make the best currentRefinedValue output

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#2015]
For now the currentRefinedValues widget only displays the values of the current active refinements. When used in conjunction with the toggleWidget or the priceRanges one for instance, the output is not usable as it is. And I haven't found any option to also retrieve the facet name / label in addition to the value.

![image](https://cloud.githubusercontent.com/assets/1101220/23415977/51a9d8b4-fde1-11e6-9a0b-df4aa64bcb10.png)

**Comment by Haroenv** [comment]
How did you fix it (for posterity)

**Comment by seafoox** [comment]
There is a lot of different type of refinements in the end. 
Using the template.item hook and passing a function that returns a template is totally possible, but because of the multiple filter type `disjunctive`, `numerical` there is a lot of use case to manage, and it doesn't feel as the most efficient way to do it, just in order to display the `attributeName` in addition to the refined value.

```js
search.addWidget(
    instantsearch.widgets.currentRefinedValues({
      container: '#active-filters',
      clearAll: 'after',
      transformData: function(data) {
        console.log(data);
        return data;
      },
      templates: {
        item: function(item) {
          var html = '';
          if (item.type === 'disjunctive' && item.name === 'false') {
            html = '';
          }
          else {
            html = `<span class="ais-current-refined-values--attribute-name">${item.attributeName}</span>: <span class="ais-current-refined-values--name">${item.name}</span> <span class="ais-current-refined-values--count">(${item.count})</span>`;
          }

          return html;
        }
      }
    })
  );
```

![image](https://cloud.githubusercontent.com/assets/1101220/23455677/bfc2a1a2-fe70-11e6-8159-eaf5228197e8.png)

**Comment by bobylito** [comment]
@seafoox Could a better name for this issue be: "display the attribute name along the value by default"?

**Comment by bobylito** [comment]
I think we can write a guide about that because each page is different and would need custom tailored solutions.

**Comment by Haroenv** [comment]
We now show key & value in the current refinement widget, so the default display looks good.
