### ISSUE TITLE
Allow listening for events on SearchBox

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2017]
The current SearchBox is not exposing any events while you may want to listen for them. The most obvious use case for now is being able to build an autocomplete menu reusing our SearchBox.

To solve this I propose to:
- allow onSubmit and onReset, those should be set on the wrapping `<form>`. They are standard DOM events. onSubmit: when hitting enter or clicking the magnifying glass icon. onReset: when clicking the clear icon (which is a button type=reset
- forward any other on* to the underlying input

**Comment by t0byman** [comment]
Can we get this in the regular JS / non-react version of instantsearch? I'm trying to make https://github.com/algolia/instantsearch.js/pull/1450#issuecomment-259118772 happen but that solution won't work. I'm guessing because there is already a preventDefault in instantsearch.js

**Comment by Haroenv** [comment]
Which events are you listening for? Could you list your use case you were thinking of in a new issue please so we don't forget about this in a closed issue @t0byman

**Comment by t0byman** [comment]
Thanks @Haroenv i created a new issue https://github.com/algolia/instantsearch.js/issues/3750
