### ISSUE TITLE
react-router v4 example outdated

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#2020]
Code Reference: https://github.com/algolia/instantsearch.js/tree/v2/packages/react-instantsearch/examples/react-router-v4

Looks like this implementation is based in a old react-router v4 proposition.

New version is under `react-router-dom@next`, more info here: https://reacttraining.com/react-router.

I tried to update and make a PR but my code doesn't work ¯\_(ツ)_/¯

In particular under `onSearchStateChange` the API is slightly different:

- `const {router} = this.context` is missing. maybe `this.props`?
- `.replaceWith` and `.transitionTo` not  #exists. maybe `.replace` and `.push`?

I think the old `context` object is now `this.props`: https://reacttraining.com/react-router/#contexthistory

**Comment by mthuret** [comment]
Thanks for spotting this @Kikobeats! 

This recipe was based on undocumented api entries, so that's not a surprise :)

I'll fix it.
