### ISSUE TITLE
<Highlight /> drops part of a string

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2022]
**Do you want to request a *feature* or report a *bug*?**

bug

**Bug: What is the current behavior?**

Using `<Highlight />` parts of a match *after* the highlighted tag will be dropped. Could be related to having a `-` directly after the last word.

Can be seen on <https://yarnpkg.com/en/packages?q=react-instant>, where the first three results are actually different packages (relatively `react-instantsearch`, `react-instantsearch-theme-algolia` and `react-instantsearch-vl`).

The whole string will show up when a query that ends at the dash is given (e.g. <https://yarnpkg.com/en/packages?q=react-instantsearch>)

**Bug: What is the expected behavior?**

The complete string to be visible.

**Bug: What browsers are impacted? Which versions?**

All browsers

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**

**Comment by Haroenv** [comment]
Awesome, this was an issue internal to the engine, and has been fixed by @speedblue @Nagriar and @ercolanelli-leo  💯

**Comment by iam4x** [comment]
Fixed on API side 👍
