### ISSUE TITLE
<Feature Request> React-IS: Multi-purpose Search Bar

### ISSUE THREAD

**Issue by thekar22** [algolia/instantsearch.js#2024]
New/modified Widget => Single search bar for handling:

- direct searching for facet values

- common textual search on rest of searchable attributes

Hacky example
https://jsfiddle.net/c9wbjzLy/1/

Explanation/Use Case:
Looking to implement a "guided search experience", where a single search bar will be responsible for both facet search and normal search. If a user types "exte", facet results for "External Battery Packs" should appear first; the normal search results should return as expected.

*The key difference is that default facets returned from a common textual search will be related, but not necessarily match exactly on the query. Widgets (perhaps current refinements) should give the option to display facet matches on both query match and on related facets.

Note: At the moment, the desired experience is easily achievable with the Algolia helper (make independent calls to search on facets and general search; append/combine results accordingly). This seems much more difficult using the provided props on existing widgets. 

Proposal to add external prop to toggle ability to run searchForItems on the global search query and provide the results in the provided props. From there, a user can discriminate/combine results as he/she wishes.

**Comment by mthuret** [comment]
Hi @thekar22,

Our current connector is not designed to do that right now. We need to think about a proper api to do so. 

Do you mind if I rename your issue as "add ability to search in facets and hits with the same query"?

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
