### ISSUE TITLE
search icon and hidden icon disappear

### ISSUE THREAD

**Issue by darrenfantasy** [algolia/instantsearch.js#2026]
![2017-03-03 7 02 40](https://cloud.githubusercontent.com/assets/11244782/23548779/17168494-0044-11e7-8677-8d21a1fd372c.png)
search icon and hidden icon disappear,who can help me?

**Comment by Haroenv** [comment]
Could you provide us with a jsfiddle with your setup, based on one of these?

- react-instantsearch: https://jsfiddle.net/ar80rgpc/6/
- instantsearch.js: https://jsfiddle.net/vvoyer/0wm3donb/4/

Also it's useful to know which version of instantsearch.js you're using.

Hope we can help!

**Comment by Haroenv** [comment]
I think you're missing the import of font-awesome, you can link it like this: <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

**Comment by darrenfantasy** [comment]
@Haroenv thank you,i fix this bug with you suggestion.
