### ISSUE TITLE
Clear Search Results on Close Button

### ISSUE THREAD

**Issue by SenenLT** [algolia/instantsearch.js#2028]
Hi,

I would like to clear the search field when I click on an "X" button

So far I'am able to clear the input field using jquery but the results are still there

When I use my backspace to empty the input field though the search results goes away

**Comment by vvo** [comment]
Hi @SenenLT, you should be able to do that via

```js
var search = instantsearch(/* ... */);

// bind any event with jQuery then call:
search.helper.setQuery('').search();
```

This should clear the query and refresh results. Thanks.

**Comment by SenenLT** [comment]
Thanks VVO - one doubt though, below is our code where can we put that?

-- --

//CLOSE AND CLEAR
	$('body #header-main .icon-close').on('click tap', function() {
	$('#header-search-form input#search').val('').focus().trigger({ type : 'keypress', which : 13 });
            		$('body').removeClass('search-init search-active filter-active');
            		$('#header-shopping-cart a.icon-cart').delay(300).queue(function(next) {
            		$('#header-shopping-cart a.icon-cart').css({'z-index':'1'});
            		next();
            });
        });

**Comment by iam4x** [comment]
@SenenLT your code should look like this:

```js
//CLOSE AND CLEAR
$('body #header-main .icon-close').on('click tap', function() {
  $('#header-search-form input#search')
    .val('')
    .focus()
    .trigger({ type: 'keypress', which: 13 });
  $('body').removeClass('search-init search-active filter-active');
  $('#header-shopping-cart a.icon-cart').delay(300).queue(function(next) {
    $('#header-shopping-cart a.icon-cart').css({ 'z-index': '1' });
    next();
  });
});
```

**Comment by Haroenv** [comment]
Hey @SenenLT, your search could look like this:

```js
//CLOSE AND CLEAR
$('body #header-main .icon-close').on('click tap', function() {
  $('#header-search-form input#search')
    .val('')
    .focus()
    .trigger({ type: 'keypress', which: 13 });
  search.helper.setQuery('').search(); // here is the resetting of the input
  $('body').removeClass('search-init search-active filter-active');
  $('#header-shopping-cart a.icon-cart').delay(300).queue(function(next) {
    $('#header-shopping-cart a.icon-cart').css({ 'z-index': '1' });
    next();
  });
});
```

**Comment by vvo** [comment]
Closing, comment if in need @SenenLT

**Comment by SenenLT** [comment]
Thanks Guys - all ok now

**Comment by Haroenv** [comment]
With pleasure!

**Comment by SenenLT** [comment]
Hi Guys,

A little follow up

Since we now able to successfully clear the input :)

Can we also return the URL state before a query is was done?

**Comment by Haroenv** [comment]
You can use `location.search` (a DOM API) to get the current querystring, see https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/search

**Comment by SenenLT** [comment]
Anyway we can utilize something here?

https://community.algolia.com/algoliasearch-helper-js/
