### ISSUE TITLE
Get total number of hits returned 

### ISSUE THREAD

**Issue by ledbetterljoshua** [algolia/instantsearch.js#2031]
My main reason for wanting this, is to be able to display a "no results" template when there are no results. This would be very easy to do if I were able to keep track of the number of Hits returned, but I do not see this available after going through the docs. What I would like to do is something similar to this: 

```
const SearchVideo = React.createClass({
  result({hit}) {
    if (!hit) return null;
    return (
      <Highlight attributeName="title" hit={hit} />
    );
  },

  render() {
    if(!this.props.active){ return <span/>; }
    return (
      <div className="w-clearfix">
        {
          hits.length > 0? (
            <Hits hitComponent={this.result}/>
          ) : <NoResults />
        }
      </div>
    )
  }
});
```

Any help you could provide would be very helpful.

**Comment by Haroenv** [comment]
The current recommended way to do that is using [`connectHits`](https://community.algolia.com/instantsearch.js/react/connectors/connectHits.html), which has an example doing just that ([link](https://community.algolia.com/instantsearch.js/react/guide/Conditional_display.html))

Basically that’s this:

```js
const content = createConnector({
    displayName: 'ConditionalResults',
    getProvidedProps(props, searchState, searchResults) {
      const noResults = searchResults.results ? searchResults.results.nbHits === 0 : false;
      return {query: searchState.query, noResults};
    },
 })(({noResults, query}) => {
    const content = noResults
      ? <div>No results found for {query}</div>
      : <div>Some results</div>;
    return <div>{content}</div>;
 });
```

**Comment by mthuret** [comment]
Hi @ledbetterljoshua, 

You can do that by using the [`connectHits` connector](https://community.algolia.com/instantsearch.js/react/connectors/connectHits.html). 

Basically you will have a function giving the hits, and you can do any rendering you want based on this. More information about the connector can be found on [our dedicated guide](https://community.algolia.com/instantsearch.js/react/guide/Connectors.html). 

Also, if you hit some limitations with only using `connectHits` you can use the `createConnector` function. More information on [our dedicated guide about conditional display](https://community.algolia.com/instantsearch.js/react/guide/Conditional_display.html).

**Comment by ledbetterljoshua** [comment]
This looks like it's exactly what I need. Thank you both @Haroenv and @mthuret
