### ISSUE TITLE
Configure doesn't update search state with new props

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch.js#2032]
**Bug: What is the current behavior?**
Changing props on configure does not update search state. In past issues, I was talking about how on mount the state is off, now it seems changing the props passed does not update the state. See the video example: https://www.youtube.com/watch?v=2NXGUqTAEpQ&feature=youtu.be

**What project are you opening an issue for?**
- react-instantsearch

**Comment by mthuret** [comment]
Hi @zackify,

Can you add a [jsfiddle](https://jsfiddle.net/vvoyer/ar80rgpc/2/) illustrating how you do it? 

Also can you[ run this recipe](https://github.com/algolia/instantsearch.js/tree/v2/packages/react-instantsearch/examples/geo-search) and tell me if the behaviour works for you? 
Basically each time you click on the map, you'll see the search state being updated with the new coordinates from the map (and by extension it will appear on the url).

**Comment by zackify** [comment]
I was in the process of making the jsfiddle but couldn't get the bug to happen. I was one minor version off on the project. Updating fixed this issue!

**Comment by mthuret** [comment]
@zackify Great :)
