### ISSUE TITLE
How can a widget prevent an initial search?

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#2038]
I know I can control the initial search using the [searchFunction](https://community.algolia.com/instantsearch.js/documentation/#hide-results-on-init) option.

What I'm wondering is if it is possible for a widget itself to somehow tap into this functionality.

Use-case is a widget that plots pins on a map. I want to delay in the initial search until I have the map bounds available. This can be achieved like so:

```
options.searchFunction = function(helper) {
  if (helper.getQueryParameter('insideBoundingBox')) {
    helper.search();
  }
};
```

However, I'd ideally like to bake this functionality into the widget itself if possible. So if my map widget was added to the instantsearch, the initial search would be blocked, without having to override `options.searchFunction`.

If it is possible, please clue me in. If not, I suppose this is a PR.

**Comment by vvo** [comment]
> I want to delay in the initial search until I have the map bounds available

Can you detail this, does it means you want, on first load, to delay instantiation of instantsearch.js interface to when you have the map initialised?

> Use-case is a widget that plots pins on a map. I want to delay in the initial search until I have the map bounds available.

This should be solved at your custom widget level:

- map.start()
- map.isReady => false
- search.start()
- map.isReady => false
- first results are coming
- custom widget renders
- map.isReady => false
- map.whenReady => plot results

So you own widget should be responsible for waiting for the map to be ready, which would mean plotting only when everything is ready. I think this is feasible but will require a bit of work on your side, what do you think?

**Comment by timkelty** [comment]
> Can you detail this, does it means you want, on first load, to delay instantiation of instantsearch.js interface to when you have the map initialised?

Your example makes sense, except for the fact that my map is rendered and initialized via my widget itself, so I'm not sure how I could init/render the widget without performing that initial search. Note that I can do this via `options.searchFunction`, but I think what I'm lobbying for is a way for a widget to control a similar option, so that I might prevent an initial search from my widget rather than the Instantsearch instance.

**Comment by bobylito** [comment]
Giving widgets control over the search means that any of them could mess up with the lifecycle of the other. It will be then very hard to reason about InstantSearch. And there is a solution for the problem. So I will close this issue for now (please open a new one if need be).

Thanks for your contribution, this is always appreciated.

**Comment by timkelty** [comment]
Makes sense, thanks for the explanation.
