### ISSUE TITLE
Custom Widget with AutoHideContainer

### ISSUE THREAD

**Issue by JonnyTurnerUK** [algolia/instantsearch.js#2040]
Hey guys! We have a custom widget that creates a select field and works great, however, I'm struggling to get autoHideContainer to work with it after trying many theories so I've resorted to asking here. :-/

Any chance someone can take a look and give some pointers on how this can be achieved? Below is the code I've got for the custom widget. Changing the type from 'customSelectorWidget' to a default widget works exactly as expected, just not the custom way.

    search.addWidget(
        instantsearch.widgets.customSelectorWidget({
            container: '#bodyType',
            attributeName: 'bodyType',
            limit: 50,
            title: 'Select Body Style',
            autoHideContainer: true,
        })
    );

Here's the widget itself:

    instantsearch.widgets.customSelectorWidget = function customSelectorWidget(options) {

        var container = options.container;
        var attributeName = options.attributeName;
        var limit = options.limit || 10;
        var title = options.title || 'All';

        container = document.querySelector(container);

        var selectElement = null;

        var currentlySelectedValue = null;

        return {

            getConfiguration: function getConfiguration() {

                return {
                    hierarchicalFacets: [{
                        name: attributeName,
                        attributes: [attributeName]
                    }]
                };

            },

            init: function init(options) {

                var helper = options.helper;
                container.innerHTML = '<label class="field select"><select></select><i class="arrow"></i></label>';
                selectElement = container.querySelector('select');

                selectElement.addEventListener('change', function() {

                    var selectedIndex = selectElement.selectedIndex;
                    var selectedValue = selectElement.options[selectedIndex].value;

                    if (selectedValue === '__EMPTY__') {
                        selectedValue = currentlySelectedValue;
                    }

                    helper.toggleRefinement(attributeName, selectedValue);

                    helper.search();

                    currentlySelectedValue = selectedValue;

                });

            },

            render: function render(options) {

                var results = options.results;
                // We get the list of possible values for this search and sort them in the
                // same order everytime (most popular first)
                var sortBy = ['name:asc', 'count:desc'];
                var facetValues = results.getFacetValues(attributeName, {sortBy: sortBy}).data;

                if(facetValues){

                    facetValues = facetValues.slice(0, limit);

                    var innerOptions = ['<option value="__EMPTY__">' + title + '</option>'];

                    facetValues.forEach(function(facetValue) {

                        var selected = facetValue.isRefined ? 'selected="selected"' : '';
                        innerOptions.push('<option value="' + facetValue.name + '" ' + selected + '>' + facetValue.name + " (" + facetValue.count + ')</option>');

                    });

                    selectElement.innerHTML = innerOptions.join('\n');

                }
            }
        }
    };

**Comment by JonnyTurnerUK** [comment]
For now, I've got a simple work around for the above although it feels like there should be more of a configurable way - hey ho! ;)

Just showing / hiding the container seems to work fine:

    if(facetValues){

                $(container).show();

                facetValues = facetValues.slice(0, limit);

                var innerOptions = ['<option value="__EMPTY__">' + title + '</option>'];

                facetValues.forEach(function(facetValue) {

                    var selected = facetValue.isRefined ? 'selected="selected"' : '';
                    innerOptions.push('<option value="' + facetValue.name + '" ' + selected + '>' + facetValue.name + " (" + facetValue.count + ')</option>');

                });

                selectElement.innerHTML = innerOptions.join('\n');

            } else {

                $(container).hide();

            }

**Comment by vvo** [comment]
This is the way to go! It does solve exactly your issue and provides the functionality you are looking for.

You could also display your widget without any option in a "disabled" state, that way your UI stay the same, just the widget is disabled and the user has the context that given his search, there's no menu items. It's better because you do not hide things automatically.

If this is ok to you, close the issue.

Thanks a lot for participating in this repo!
