### ISSUE TITLE
InfiniteHits Load More button translation

### ISSUE THREAD

**Issue by Kolyasya** [algolia/instantsearch.js#2047]
Hello, it seems like there is no way to change text in Load More button for InfiniteHits component?

There is no Translation Keys in [docs](https://community.algolia.com/instantsearch.js/react/widgets/InfiniteHits.html)

And I checked source code, it seems like `Load More` is hardcoded

**Comment by Haroenv** [comment]
Thanks a lot for your report! This can be fixed quite fast. Do you want to do a pull request?

**Comment by Kolyasya** [comment]
@Haroenv sorry, I'm not familiar with your project codebase :(

**Comment by Haroenv** [comment]
No problem, we will get it fixed!
