### ISSUE TITLE
Connected numerical MultiRange not hiding unfilterable values correctly

### ISSUE THREAD

**Issue by RyanTheAllmighty** [algolia/instantsearch.js#2049]
First a bit of an explanation of the bug.

Not sure if it's a bug, or the way I'm doing things is incorrect.

So we have an index, lets say called Events. Inside this index is a bunch of documents that look partially like below:

```json
{
    "startTime": "2017-03-15T00:55:00Z",
    "startTimeEpoch": 1489539300,
    "title": "Training Program",
    "trainer": "S Smith",
    "link": "/event/training-program/12345"
}
```

Now I'm trying to hook it up so that users can search these events. I have a custom MultiRange component to allow filtering based on some named days (today, tomorrow, Friday, Saturday and Sunday) with the last 3 days being the correct named days compared to now.

My component looks like below:

```js
import cx from 'classnames';
import React from 'react';
import { connectMultiRange } from 'react-instantsearch/connectors';

class DayList extends React.Component {
    /**
     * This will apply the provided refinement for the day list.
     *
     * This will either set the date range or if user has clicked the selected item it will remove that refinement.
     *
     * The value is in the form of `${item.min}:${item.max}`
     *
     * @param {string} value
     */
    handleFacetItemClick(value) {
        if (value === this.props.currentRefinement) {
            this.props.refine();
        } else {
            this.props.refine(value);
        }
    }

    render() {
        // only get the refinable facet items which are the ones valid to facet against
        const refinableFacetItemsToShow = this.state.items && this.state.items.filter((facetItem) => (!facetItem.noRefinement));

        const items = refinableFacetItemsToShow && refinableFacetItemsToShow.map((facetItem) => {
            return (
                <div className="srp-facet-item" title={item.label} onClick={this.handleFacetItemClick}>
                    <label className="srp-facet-item__name">
                        { item.label }
                    </label>
                </div>
            );
        });

        return (
            <div className="srp-facet">
                <div className="srp-facet__header">
                    <h1 className="srp-facet__header-title">
                        Days
                    </h1>
                </div>

                <div className={facetItemClasses}>
                    {items}
                </div>
            </div>
        );
    }
}

export default connectMultiRange(DayList);
```

Then used as:

```js
const items = [
    {"label":"Today","start":1489496400,"end":1489582800},
    {"label":"Tomorrow","start":1489582800,"end":1489669200},
    {"label":"Friday","start":1489669200,"end":1489755600},
    {"label":"Saturday","start":1489755600,"end":1489842000},
    {"label":"Sunday","start":1489842000,"end":1489928400}
];

<DayList items={items} attributeName="startTimeEpoch" />
```

This works as intended, showing the correct days passed in, but it has an issue when it comes to setting the `noRefinement` property on each of the items accessed by `this.props.items` in the `DayList` component.

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**Bug: What is the current behavior?**
When I have one Event which has `startTimeEpoch: 1489497400` (falls within Today) and then one event that has `startTimeEpoch: 1489846000` (falls within Sunday), then I currently see all items with the `noRefinement` property set to false so all items show up in my filter list.

```json
[
    {"label":"Today","value":"1489496400:1489582800","isRefined":false,"noRefinement":false},
    {"label":"Tomorrow","value":"1489582800:1489669200","isRefined":false,"noRefinement":false},
    {"label":"Friday","value":"1489669200:1489755600","isRefined":false,"noRefinement":false},
    {"label":"Saturday","value":"1489755600:1489842000","isRefined":false,"noRefinement":false},
    {"label":"Sunday","value":"1489842000:1489928400","isRefined":false,"noRefinement":false}
]
```

**Bug: What is the expected behavior?**
When I have one Event which has `startTimeEpoch: 1489497400` (falls within Today) and then one event that has `startTimeEpoch: 1489846000` (falls within Sunday), then I should see the `noRefinement` property set to false on items with a label of Tomorrow, Friday and Saturday with the items with a label of Today and Sunday having a `noRefinement` property set to true.

```json
[
    {"label":"Today","value":"1489496400:1489582800","isRefined":false,"noRefinement":false},
    {"label":"Tomorrow","value":"1489582800:1489669200","isRefined":false,"noRefinement":true},
    {"label":"Friday","value":"1489669200:1489755600","isRefined":false,"noRefinement":true},
    {"label":"Saturday","value":"1489755600:1489842000","isRefined":false,"noRefinement":true},
    {"label":"Sunday","value":"1489842000:1489928400","isRefined":false,"noRefinement":false}
]
```

This is caused by [itemHasRefinement](https://github.com/algolia/instantsearch.js/blob/v2/packages/react-instantsearch/src/connectors/connectMultiRange.js#L51) using the facets stats property to get the min and max values and basing the view on those rather than what the actual values are within the results.

**Bug: What browsers are impacted? Which versions?**
From what I can tell, all of them

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**
```
    "react-instantsearch": "~3.2.1"
```

**Comment by RyanTheAllmighty** [comment]
Looking at a way around this it looks like it wouldn't be possible to use the `data/values` provided by Algolia since it doesn't return all the possible values for numericAttributes:

```json
{
    "name":"startTimeEpoch",
    "data": {
        "1489581000":139,
        "1489581060":138,
        "1489581120":143,
        "1489581180":146,
        "1489581240":136,
        "1489581300":120,
        "1489581360":129,
        "1489581420":114,
        "1489581480":86,
        "1489581540":38,
        "1489585500":28,
        "1489589400":38,
        "1489722600":28,
        "1489788000":153,
        "1490997600":92,
        "1491606000":141,
        "1492250400":111,
        "1506124800":82,
        "1509145200":51,
        "1510009200":80
    },
    "exhaustive":true,
    "stats": {
        "min":1489543740,
        "max":1510009200,
        "avg":1490079779,
        "sum":17624663633760
    }
}
```

Since the list there is not an exact list containing every single `startTimeEpoch` in the index, I cannot use that to provide a more accurate list of days that are used.

**Comment by mthuret** [comment]
Hi @RyanTheAllmighty,

You're right, the `noRefinement` feature of the MultiRange was done with a different logic that the one you need. 

While we are thinking about this issue, maybe you can try those following workaround:

1. You can create your own connector by reusing the MultiRange one, and just changing the logic.
2. Maybe you could use the RefinementList instead. The RefinementList has a prop `transformItems` that can let you return an array that will contain days. And by increasing the limitMin, you can check if you have some date that falls in. 

What do you think?

**Comment by RyanTheAllmighty** [comment]
@mthuret I didn't even think about creating a custom connector, I'll give that a shot now and see how it goes and report back, but I think the issue I mentioned in my second comment, about the API not returning a full list of possible values in the `numericAtributes` response, but I'll do some digging.

**Comment by RyanTheAllmighty** [comment]
Yeah unfortunately as per my second comment, Algolia only provides 20 values which when there is a large amount of results will miss some days so this approach is not practical unfortunately.

Any other ideas on how to achieve this?

**Comment by mthuret** [comment]
@RyanTheAllmighty: did you try to use the refinementList along with `transformItems`?

**Comment by RyanTheAllmighty** [comment]
@mthuret 

I was able to get something working using `createConnector` and literally just copying the source of MultiRange and modifying the logic in `itemHasRefinement` to match that which we needed, which was to use the facet values rather that using the min and max of stats.

Not sure if this is something that you guys would like to solve to work with MultiRange or not. If not you can close this.

**Comment by mthuret** [comment]
@RyanTheAllmighty, can you share with us the code you use, that way, we can have a look at it? :)
