### ISSUE TITLE
gh-pages doesn’t update

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2057]
see https://discourse.algolia.com/t/documentation-old/757

>The react-instantsearch docs are missing tons of props that are in the examples. Something has gone wrong with the doc autogenerator.

Or is this because the examples use newer code than last released?

**Comment by Haroenv** [comment]
Actually this is not an issue, just that the changes mentioned in the discourse post aren't released yet.

**Comment by vvo** [comment]
@Haroenv since we now have beta releases + netlify auto deploy could we add to the discourse post the link to the newest documentation ("beta")? Thanks

**Comment by vvo** [comment]
Now udpated
