### ISSUE TITLE
Add possibility to clear searchBox value using the clearAllWidget

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#2058]
For now the clearAll widget only allows to clear facet refinements, but not the search query itself. Would be great to have a way that enables it, either:
- by having an new option in the widget configuration, and say true|false
- letting define a hook function that would be called once the user has clicked and in which we could call `search.helper.setQuery('').search()`

**Comment by bobylito** [comment]
Why not make it the default behavior? I don't remember the rationale behind this choice, but it does not seem to hold imho.

**Comment by Haroenv** [comment]
I agree, a *clear all* should clear everything by default (even if it'd require a minor version change)

**Comment by seafoox** [comment]
Not sure we can make it default without breaking backward compatibility. 
That being said, it would be great to be able to clear one, or the other, or both.

**Comment by iam4x** [comment]
I agree with you @bobylito, `clearAll` as it says should clear everything from state of search. Maybe we can introduce a `clearRefinements` widget to keep a way to achieve current behaviour?

**Comment by WinstonGFX** [comment]
Man oh man, I've been working all day on trying to set something like this up. I want to give my users to ability to click an "X" button on the search bar and 'clearAll' input text - not just selected facets - but it seems like this is not yet possible.

**Comment by bobylito** [comment]
Hi @WinstonGFX, this will be possible in v2, which is already in beta. Check out the new doc: https://community.algolia.com/instantsearch.js/v2

**Comment by bobylito** [comment]
Done in v2

**Comment by vvo** [comment]
> Done in v2

Here: https://community.algolia.com/instantsearch.js/v2/widgets/clearAll.html#struct-ClearAllWidgetOptions-clearsQuery
