### ISSUE TITLE
Scaffolding tooling for new instantsearch.js projects

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#206]
Would be nice to have a tool to bootstrap a new instantsearch.js. Simple command line stuff like `instantsearch new` that would ask a few questions (not mandatory in the beginning) : 
  - name of the project
  - which css framework to use : bootstrap / foundation / none
  - which build system : browserify / webpack / simple html (use script from jsDeliver)

**Comment by redox** [comment]
I would rather go for a (some) simple GitHub skeleton project(s) like `algolia/instantsearch-bootstrap-webpack-skeleton` rather than a command line tool. Or better: a [yeoman](http://yeoman.io/) template.

**Comment by vvo** [comment]
Building the `instantsearch-starter-kit` repo will in the end be useful if one want to create an instantsearch cli scafolding app. Because it can reuse the repo I guess.

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is very old and not done, reopen if you have the need and want to fix it
