### ISSUE TITLE
reafactor: determine if we can and should use React contexts for pre-binding all Template components with some data

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#207]
Still unsure it would be better because what we did really looks like how context are working.

https://facebook.github.io/react/docs/context.html

**Comment by vvo** [comment]
https://facebook.github.io/react/docs/context.html#when-not-to-use-context

```
The best use cases for context are for implicitly passing down the logged-in user, the current language, or theme information. All of these might otherwise be true globals, but context lets you scope them to a single React subtree.
```

seems like it would be good for us :)

**Comment by bobylito** [comment]
Not really ready for prime time
> Context is an advanced and experimental feature. The API is likely to change in future releases.

**Comment by vvo** [comment]
Yes the API might change but I guess they are trying to frighten people in not using it. The goal of context is clear, the API might change but as they removed .render() from react and we survived it so it should be good?

**Comment by redox** [comment]
That would help cleanup the `prepareTemplate` mess, I'm :100: in!

**Comment by vvo** [comment]
So react contexts are even more intrusive than the solution we have right now, see the new documentation: https://facebook.github.io/react/docs/context.html

**Comment by vvo** [comment]
Reopening this because combining HOC and context can work: https://medium.com/@bloodyowl/the-provider-and-higher-order-component-patterns-with-react-d16ab2d1636

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is very old and not done, reopen if you have the need and want to fix it
