### ISSUE TITLE
Is there a way to use searchFunction with react instantsearch?

### ISSUE THREAD

**Issue by robertgonzales** [algolia/instantsearch.js#2070]
The InstantSearch component doesn't appear to expose this option.

**Comment by vvo** [comment]
Hi, no but can you give me your usecase as for the need of a searchFunction like in react instantsearch? Maybe the already available API entries are sufficient.

Let me know.

**Comment by robertgonzales** [comment]
I'd like to avoid performing an initial empty query.

**Comment by mthuret** [comment]
Might be solved with this https://github.com/algolia/instantsearch.js/issues/1994 ?

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
