### ISSUE TITLE
Save Search instantsearchjs

### ISSUE THREAD

**Issue by spindriftwebs** [algolia/instantsearch.js#2074]
I would like to allow users to save their searches.  I have a system in place that parses the URL as an array which allows me to detect what users have been selecting in the facet menu.  I'm using window.location.href.toString() to get the url from the urlsync values.

Say I have a facet search of cars with BMW and Audi as selectable options.

if a user visits a page where BMW cars are shown.  If the user then selects Audi, the `window.location.href.toString()` does not update, it still shows BMW.  It's almost as if `window.location.href.toString()` is not being updated although the correct URL is displayed in the address bar.

```js
{
  url: "savesearch.php",
  type: "POST",
  data: {
    search_url: window.location.href.toString()
  }
}
```

Has anyone else come across this issue or is there a simpler way to achieve this ?

Many thanks

Guy

**Comment by bobylito** [comment]
Hi @spindriftwebs Do you have a web page where I can reproduce the issue?

**Comment by spindriftwebs** [comment]
Hi @bobylito Yes - you can view my page here: https://www.secondhandboards.com/used-surfboards

Underneath the reset search button there is a number 1.  If you click this you will see an alert which shows the URL.  The function simply grabs window.location.toString() 

Many thanks for looking into this.

**Comment by spindriftwebs** [comment]
Did you manage to have a look at this Alex ? @bobylito Thanks

**Comment by bobylito** [comment]
Hi @spindriftwebs Thanks for your patience. I can't reproduce the error. I selected funboard and the url is correctly updated. I can't manage to have a car as you proposed in the example. Can you give me the scenario that you follow on your page?

To sum up your use case, you want to store the URL of the current search so the users can go back to it?

What about you could save the complete state of the search and send it to your backend? You can do this with those lines:

```js
// extract the state
var state = search.helper.getState();

// initialize instantsearch with a state
var search = instantsearch({
  // ... other parameters here
  searchParameters: state
});
```

**Comment by spindriftwebs** [comment]
Hi Alex, I'm struggling a bit.  It's for this page: https://www.secondhandboards.com/used-surfboards?q=&iBB=59.19602992287059%2C35.03370844999995%2C45.97842659579084%2C-41.25535405000005&p=0&is_v=1 

I have  console.log(state); writing to the console but I can't see where the filtered items sit within the response or how I would extract this for saving into php variables.  I'm still trying to figure this out but if you have any pointers that would be great as it's causing me problems at the moment.

Would love to get this resolved.  Thanks  Guy

**Comment by bobylito** [comment]
Sorry about the late answer. I appreciate your patience, thanks.

So if you want to leverage the same search in the backend, you could use the JS Helper [getQuery](https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/algoliasearch.helper.js#L135-L138). It's not documented but it will give you the Algolia query that you can reuse in the backend for the hits.

However you won't be able to use that back in the front-end. You would have to save the state using `getState` for that.

**Comment by bobylito** [comment]
We'll write a guide about that: see #2189
