### ISSUE TITLE
Add numeric facet to searchParameters

### ISSUE THREAD

**Issue by ledbetterljoshua** [algolia/instantsearch.js#2075]
Hi there, 

Each of my search results has a publish date. I want to ensure that nothing with a publish date in the future shows in my results. Is there currently a way to do this using the searchParameters? Here is my current setup:

```js
const searchParametersVideo = {
  facetFilters: [["modelName:video"], ["locale:" + getAlgoliaLocale(locale)], ["publishDate:"+'<='+moment().format()]],
  hitsPerPage: 3
};

return (
  <InstantSearch
    appId={config.search.appId}
    apiKey={config.search.apiKey}
    searchParameters={searchParametersVideo}
    searchState={{query: this.props.searchState}}
    indexName={config.search.index}>
    <VirtualSearchBox/>
    <VideoResults />
  </InstantSearch>
)
```

As you can see, I have attempted to add a publishDate filter to my `facetFilters`, which does not seem to work. Does anyone know of the correct way to do this?

Thank you, 
Joshua

**Comment by mthuret** [comment]
Hi @ledbetterljoshua 

The `searchParameters` prop is now deprecated. You can use the `Configure` widget to apply any `searchParameters`. See: https://community.algolia.com/instantsearch.js/react/guide/Search_parameters.html

Then, you can use the `filters` search parameter which as an easier syntax than `facetFilters`.
See: https://www.algolia.com/doc/api-client/javascript/parameters/filters/

It would mean having something like this: 

    <Configure
             filters="publishDate <= timestamp"
             hitsPerPage = {3}
    />

**Comment by ledbetterljoshua** [comment]
Hi @mthuret, this helps greatly. Thank you very much.
