### ISSUE TITLE
Input cursor goes to the end - when removing text

### ISSUE THREAD

**Issue by SenenLT** [algolia/instantsearch.js#2077]
Hi,

We have been having this weird issue on our input bar

Whenever you search for something ex. "iphone", and remove a character "ipone", the cursor moves to the very end

You can try it here:
http://robotech.letstango.com

Any assistance would highly be appreciated

**Comment by Haroenv** [comment]
For reference to find which version this is using. The site imports: 

* [AlgoliaSearchBundle 4.3.4](http://robotech.letstango.com/js/algoliasearch/internals/frontend/algoliaBundle.min.js)

And it uses:

* [instantsearch.js](http://robotech.letstango.com/js/algoliasearch/instantsearch.js)
* [autocomplete.js](http://robotech.letstango.com/js/algoliasearch/autocomplete.js)

**Comment by SenenLT** [comment]
Do we have a version issue?

It appears to be happening on Chrome

**Comment by Haroenv** [comment]
see also #2012 I think

**Comment by bobylito** [comment]
@SenenLT Any luck with the new version?

**Comment by bobylito** [comment]
I tried on @SenenLT website, and I can't reproduce the issue anymore. Let's close this one for now.
