### ISSUE TITLE
Is there a way to reset a ionRangeSlider when a checkbox is ticked?

### ISSUE THREAD

**Issue by ryan4303** [algolia/instantsearch.js#2080]
We have a price slider on our search that we only want to show when a checkbox option is ticked, that works fine now but we need the price slider to reset/update if that option is unticked.

Is there a way to do this?

**Comment by Haroenv** [comment]
Which project are you talking about, and could you maybe link a jsfiddle (preferred) or if that isn't possible a live website where we can see what you mean?

**Comment by ryan4303** [comment]
We'll recreate it in jsfiddle as it's a live site on a hidden page at them moment, I'll comment the link when I've set it up.

Thanks for getting back to me so quickly.

**Comment by ryan4303** [comment]
Here is a jsfiddle of the search.

https://jsfiddle.net/h5dxLb1r/1/

So once you click "Approved Used" the monthly price slider shows, we need it so that if someone unticks "Approved Used" the monthly price slider values resets so the "New" option shows.

**Comment by bobylito** [comment]
When you want to update the parameters based on some widget update you need to rely on the internal state management: the JS Helper. This should be explained in a guide.

**Comment by bobylito** [comment]
Referenced in the meta issue for all guides :)
