### ISSUE TITLE
connectStats nbhits not returning correct count

### ISSUE THREAD

**Issue by imoby** [algolia/instantsearch.js#2082]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
nbHits for connectStats is returning more counts than what algolia index shows on the dashboard for that specific facet.

More specifically, for us we are getting around 9 additional hits than we should be compared to what is showing up in algolia dashboard.

**Bug: What is the expected behavior?**
nbHits for connectStats should return the same count as dashboard for a facet

**Bug: What browsers are impacted? Which versions?**
Tested on chrome

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**
v3.3.0

**Comment by mthuret** [comment]
Hi @imoby 

Can you please reach the Algolia support by mail as this might not be a react-instantsearch issue, having your APP_ID may help us.

Also can you precise in the mail if the results vary each time or not?

Thanks a lot!
