### ISSUE TITLE
[Feature] Add option to open collapsible based on isRefined

### ISSUE THREAD

**Issue by julienpa** [algolia/instantsearch.js#2083]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
Sometimes a refinement list might be collapsed by default, but if it has been refined and the user reloads the page, it would be nice to have it opened instead of collapsed.

![issue with collapsible refined](https://cl.ly/003T3V023G2r/Screen%20Recording%202017-03-29%20at%2006.17%20PM.gif)

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
Add a property in the `collapsible` object, like `collapsedIfRefined` with a boolean value (default `true` to not change existing behavior).
Expected usage based on current options would be something like this:
```js
search.addWidget(
  instantsearch.widgets.refinementList({
    ...
    collapsible: {
      collapsed: true,
      collapsedIfRefined: false
    }
  })
);
```

**What project are you opening an issue for?**
- instantsearch.js

**What is the version you are using? Always use the latest one before opening a bug issue.**
Latest

**Comment by Giovanni-Mattucci** [comment]
Totally want this feature. 
Any kind of work around to implement this behaviour with current instantsearch?

**Comment by bobylito** [comment]
The problem is that for the moment InstantSearch.js only stores search related parameters in the URL and since it's a direct mapping of the internal state (only search related), it means some deep modifications.

We can add the API proposed by @julienpa but that's external thus this will force the developer to do the integration themselves, which can be tricky.

**Comment by julienpa** [comment]
@bobylito what do you mean by:
> this will force the developer to do the integration themselves

You mean the logic or just the style?

**Comment by Giovanni-Mattucci** [comment]
My solution was to create a widget that checks each refinement widget for an active state, and if it has one, open it up:
```javascript
var openIfRefined = function openIfRefined() {
	return {
		render: function() {
			$(".search-refine > div").each((index, elem) => {
				let refineWidget = $(elem);
				let isOpen = refineWidget
					.find(".ais-refinement-list--item")
					.hasClass("ais-refinement-list--item__active");
				if (isOpen) {
					refineWidget
						.find(".ais-root__collapsible")
						.removeClass("ais-root__collapsed");
				}
			});
		}
	};
};

search.addWidget(
	openIfRefined()
);
```
