### ISSUE TITLE
Add a guide on opensearch

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2088]
OpenSearch provides search for websites from the url bar, you may have been using it without noticing it, works pretty well.

We should add a guide on opensearch in our community websites to show people what can be done when using instantsearch.js/react-instantsearch for OpenSearch.

If opensearch is a good pattern that would benefit our users, then we should have a guide about it.

Example: Try in your browser: "yarn [TAB] lodash", this is opensearch. https://github.com/yarnpkg/website/blob/master/opensearch.xml

It needs to be linked in the `head` like this:

https://github.com/yarnpkg/website/blob/66acf52e8f096bef1d74dce6895874f64b3f44d4/_layouts/default.html#L22

**Comment by Haroenv** [comment]
small guide: 

## OpenSearch

[ gif of opensearch on yarn https://twitter.com/haroenv/status/841938746626985985 ]

Another thing I learned about while making search for Yarn is the OpenSearch spec. It was developed by a9, a subsidiary of Amazon a long time ago, and deals with a lot of browser and search functionality. You can make your whole search available in the dropdown that comes up when you use “search in site”. Making your search available in the rss format that opensearch expects isn’t what Algolia is made for right now, but we can make browsers handle the “search in site” feature. To do that we have to add a `<link rel=search` to the `<head>` of every page. In that we add a `href="/opensearch.xml"` and `type="application/opensearchdescription+xml"`, a `title="name of your site"` is also added to show up in the UI of browsers correctly. The /opensearch.xml file should contain something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"xmlns:moz="http://www.mozilla.org/2006/browser/search/">
<ShortName>Yarn</ShortName>
<Description>Package Search</Description>
<Url type="text/html" method="get"template="https://www.yarnpkg.com/en/packages?q={searchTerms}"/>
<InputEncoding>UTF-8</InputEncoding>
<Image height="32" width="32" type="image/x-icon">https://yarnpkg.com/favicon.ico</Image>
</OpenSearchDescription>
```
