### ISSUE TITLE
Use a non-html tag as the default highlighting tag

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2093]
**Do you want to request a *feature* or report a *bug*?**

**Feature: What is your use case for such a feature?**

When trying to make sure that there are absolutely no XSS holes in a highlighted string, in the dashboard a text node is made, that then is filled with the content of the highlighting.

See also the function used in the dashboard exactly (tsx, not jsx): 

```tsx
export default function StringHighlighter({ hit, path }: { hit: Hit, path: string }) {
  const value = get(hit._highlightResult, path) as { value: string };
  const str = value.value.replace(/<(\/)?ais-highlight-(\d+)>/g, '{{{$1ais-highlight-$2}}}');
  const div = document.createElement('div');
  div.appendChild(document.createTextNode(str));
  const __html = div.innerHTML
    .replace(/{{{ais-highlight-\d+}}}/g, '<em>')
    .replace(/{{{\/ais-highlight-\d+}}}/g, '</em>');

  return (
    <span
      className="string"
      dangerouslySetInnerHTML={{ __html }}
    />
  );
}
```

The big difference between our `Highlighter` and this function is that we rely on React to do the escaping, while the solution in the dashboard will 

We will also need to test if this makes sense in benchmarking, and not make everything slower. 

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

```diff
//higlightTags.js
const timestamp = Date.now().toString();

export default {
-   highlightPreTag: `<ais-highlight-${timestamp}>`,
-   highlightPostTag: `</ais-highlight-${timestamp}>`,
+   highlightPreTag: `{{{ais-highlight-${timestamp}}}}`,
+   highlightPostTag: `{{{/ais-highlight-${timestamp}}}}`,
};
```

I tried this in a story, and it seems to still work.

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**

v4.0.0-beta.0

**Comment by vvo** [comment]
If I try to wrap my head around this, we want to avoid doing a regex? Or do we want to use dangerouslySetInnerHTML?

What is the real underlying issue we want to solve?

**Comment by rayrutjes** [comment]
I'm still not convinced by the use of the timestamp, it adds entropy for sure, but for what? 
Why don't we go with static pre/post tag easier to replace and to reason about.

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
