### ISSUE TITLE
Improve `docs` onboarding documentation

### ISSUE THREAD

**Issue by JonathanMontane** [algolia/instantsearch.js#2098]
**Do you want to request a *feature* or report a *bug*?**
Bug in `docs/README.md` (incomplete documentation).

**Bug: What is the current behavior?**
The `docs` app uses `rvm` to pin the `ruby` version to `2.3.3`. Its documentation, however, is not advocating for the use of `rvm` or any specific version of ruby, which causes the app to fail to build with `ruby@2.4` as some dependencies are not yet compatible with `2.4`.

<details>
  <summary>More details (Click to expand)</summary>
  <br/>
  <p>
    The <code>docs</code> app uses <code>yajl-ruby</code> which is not yet compatible with `2.4.x` (see: <a href="https://github.com/brianmario/yajl-ruby/issues/164">yajl-ruby#164</a>).
  </p>
  <p>
    On OSX, <code>brew install ruby</code> yields a <code>2.4.x</code> version, which naturally fails to build the app. The command <code>brew install ruby@2.3</code> will install the required version, but there can be issues with <code>$PATH</code>, that can be tedious. using <code>rvm</code> is much simpler and will yield cleaner environments for everyone.
  </p>
</details>

<br/>

**Bug: What is the expected behavior?**
The onboarding documentation (`docs/README.md`) details the 2.3.3 requirements for `ruby` and proposes steps to get this specific version.

**Note**
I see 3 ways of fixing this:
- [ ] add the `ruby@2.3.3` requirement
- [ ] add the `rvm` requirement
- [ ] add a `Dockerfile` and possibly a `docker-compose` file. The requirements become: Get Docker.

**Comment by JonathanMontane** [comment]
I can work on this tonight, once the preferred way of fixing has been chosen.

**Comment by bobylito** [comment]
Hi @JonathanMontane Thanks for the issue. We're currently working on making a new documentation website which will not rely on Ruby anymore.

Thanks again for taking the time to document and propose a solution ❤️

**Comment by JonathanMontane** [comment]
Thanks for the heads up!
