### ISSUE TITLE
Configure, check for null values?

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch.js#2099]
**Do you want to request a *feature* or report a *bug*?**

feature

**Bug: What is the current behavior?**
If one of these values is null, I get a bad request:
```
<Configure
            aroundLatLng={listing.aroundLatLng}
            insideBoundingBox={listing.insideBoundingBox}
          />
```

So I have to do:
```
  const configure = {}
    if(listing.aroundLatLng) configure.aroundLatLng = listing.aroundLatLng
    if(listing.insideBoundingBox) configure.insideBoundingBox = listing.aroundLatLng
```

**Bug: What is the expected behavior?**

To be able to pass null values and the component not pass them through to algolia

**What is the version you are using? Always use the latest one before opening a bug issue.**

react-instantsearch 3.3.1

**Comment by Haroenv** [comment]
closing in favour of https://github.com/algolia/react-instantsearch/issues/10

**Comment by zackify** [comment]
Sorry didn't see that this moved!

**Comment by Haroenv** [comment]
No problem, it's a very recent move, and we haven't moved the old issues to the new repository yet.
