### ISSUE TITLE
Aurelia Support?

### ISSUE THREAD

**Issue by dnndev** [algolia/instantsearch.js#2101]
I've been trying unsuccessfully to get instantsearch.js to integrate with the Aurelia (http://aurelia.io) library.  One of the committers for the Aurelia CLI said that instantsearch.js was particularly tricky and asked me to open an issue so they could investigate further. https://github.com/aurelia/cli/issues/593 

Is there any example of how to integrate it or would it be possible to provide support for Aurelia?

Thanks

**Comment by bobylito** [comment]
Hi @dnndev thanks for creating an issue 👍 

Aurelia is a complete framework and it could be quite tricky to integrate instantsearch.js in it. However you could probably use the lower level library that is used internally by instantsearch.js. This library is called the JS Helper and you can find its [documentation here](https://community.algolia.com/algoliasearch-helper-js/) and a few [examples with several frameworks here](https://community.algolia.com/algoliasearch-helper-js/examples.html#use-with-frameworks)
