### ISSUE TITLE
Implement a basic keyboard support

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2106]
To be able to navigate in an instantsearch.js UI and eventually select an item.

**Comment by flufab** [comment]
Quick & dirty...(you can write it better if you have a few mins ;) )

`
//SEARCH
var curr = -1;
$('body').on({

    'keyup': function(e){
        //down
        if(e.keyCode == 40){

            if($('.ais-results').length > 0){

                curr++;

                if(curr >= $('.ais-results h4 a').length){
                    curr = 0;
                }
                $('.ais-results h4 a').removeClass('hover');

                $('.ais-results h4:eq('+curr+')').find('a').addClass('hover');
            }
        }

        //up 
        if(e.keyCode == 38){

            if($('.ais-results').length > 0){

                curr--;

                if(curr < -1){
                    curr = $('.ais-results h4 a').length-2;
                }

                $('.ais-results h4 a').removeClass('hover');

                $('.ais-results h4:eq('+curr+')').find('a').addClass('hover');

            }

        }

        //enter
        if(e.keyCode == 13){
            if($('.ais-results h4 a.hover').length > 0){
                window.location.href =   $('.ais-results h4 a.hover').attr('href');
            }
        }

        e.preventDefault();
    }

},'.ais-input');

$('body').on('keyup',function(e){
    //tab => activate search
    if(e.keyCode == 9){
        e.preventDefault();
        $('.ais-input').focus();
    }
});

//CSS -> class .hover -> highlight focused element

`

**Comment by flufab** [comment]
Quick & dirty :) 
https://www.pastiebin.com/5bae28c67bde2

**Comment by Haroenv** [comment]
Keyboard navigation within search results usually means the actual links of the results. These are already available quite easily with tab if the search box and results are close together DOM-wise.

For real keyboard navigation, a combobox makes more sense for both sighted and non-sighted users, and for that we have autocomplete, which works together nicely with InstantSearch: https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/autocomplete/android/
