### ISSUE TITLE
Remove docs build from Travis

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2110]
**Do you want to request a *feature* or report a *bug*?**

both I guess

**Bug: What is the current behavior?**

Travis installs and runs the docs

**Bug: What is the expected behavior?**

Travis doesn’t care about the docs 

**Feature: What is your use case for such a feature?**

Have faster builds

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

Rely on Netlify for the build status of the docs

See also https://github.com/algolia/react-instantsearch/issues/33.

This can be done when we move towards the new docs in v2, since the docs don’t run yet :)

**Comment by bobylito** [comment]
We rely on netlify for PR's and we kept the build in travis for releasing from master. We'll open a new issue when we want to move completely to netlify
