### ISSUE TITLE
stats widget: Getting stats from DerivedHelper 

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#2115]
I have an InstantSearch with a `DerivedHelper`.

I'm trying to get the results of the `DerivedHelper` from the Stats widget.

Here's what I've tried (unsuccessfully):
```js
this.InstantSearch.widgets.stats({
  container: this.$container.find(this.config.selectors.stats)[0],
  transformData: {
    body: (data) => {
      let helper = this.instantSearch.helper;
      let locationsHelper = helper.derivedHelpers[0];

      return Object.assign(data, {locationsHelper});
    }
  },
  templates: {
    body: (stats) => {
      return stats.hasNoResults ? 'No trips found.' : `${stats.nbHits} ${pluralize('trip', stats.nbHits)} from ${pluralize('location', stats.locationsHelper.lastResults.nbHits)} locations`;
    }
  }
}),
```

It seems this happens too early, as `stats.locationsHelper` is always `null`. However, by the time I `console.log` it, I see my results. So it seems something is happening in the lifecycle of that helper that isn't propagated through the stats widget.

Is there any way to do this, short of making my own custom stats widget?

```
"algoliasearch-helper": "^2.18.1",
"instantsearch.js": "^1.10.3",
```

**Comment by bobylito** [comment]
Hi @timkelty thanks for pushing the API :) As of now we haven't done much work combining instantsearch.js and the derived helpers. The derived helpers generate their own events that instantsearch don't listen to. The easiest way to do what you want is to listen directly to the result event of the derived and update your UI accordingly without using a widget. How does that sound?

**Comment by timkelty** [comment]
@bobylito sounds good, that's what I figured. Would be a nice addition in the future, though!

I figured this wouldn't "just work", but I wondered if there was a way I could listen for the `DerivedHelper.result` and trigger some kind of `refresh()` on the stats widget specifically.

**Comment by bobylito** [comment]
What do you mean by `refresh()`? Trigger a new search, only for the derived helper?

**Comment by timkelty** [comment]
Sorry, no - I mean just trigger the update the stats widget component to update.

**Comment by bobylito** [comment]
I am sorry, I'm still not sure what it would imply? Is it a refresh of the values of the stats widget?

**Comment by timkelty** [comment]
I guess I was thinking if I could trigger the stats widget could re-render _after_ I got my derived result, then `locationsHelper.lastResults` would be populated by then (similar to how I can see the result if I `console.log`).

...then again, just spitballing.

**Comment by bobylito** [comment]
OK thanks, noted! :)
