### ISSUE TITLE
paginationLimitedTo is not recognised as a searchParameter

### ISSUE THREAD

**Issue by Ardakilic** [algolia/instantsearch.js#2118]
Hello,

We're using Algolia pro plan along with instantsearch.js in our project to make searches and show categories and contents inside them (category page and search pages are powered by Algolia). We are using instantsearch.js v1 is from cdn.

Our main issue is that search doesn't provide more than 1000 records which we need.

As far as I understand correctly, `browse()` method provides more results, but it's not usable in instantsearch.js.

Also, after reading docs, I found out that there's a new option called `paginationLimitedTo`, which allows displaying more than 1000 records:

https://www.algolia.com/doc/rest-api/search/#paginationlimitedto

So, setting this would allow displaying more than 1000 records.

Can you help us here, how would we achieve getting more than 1000 records, or if it'd achieve our goal, how do we set this `paginationLimitedTo` attribute in instantsearch.js ? We're okay if we need to build or edit instantsearch.js for the time being.

Thanks in advance,

**Comment by spinach** [comment]
Closing, as it is being answered [on SO](http://stackoverflow.com/questions/43518921/how-to-show-more-than-1000-records-in-algolia-instantsearch-js/43520525#43520525).

**Comment by Ardakilic** [comment]
Thank you, I can confirm the issue is solved:

Heads-up for future: 

I have created a custom ACL with `search` and `browse` features only, and injected a custom client to instantsearch, just like this:


```js
// custom client
var customClient = algoliasearch('appid', 'search_and_browse_only_custom_acl_key');
// Create instant_search index and set its settings
var customIndex = customClient.initIndex('my_index');
customIndex.setSettings({
  paginationLimitedTo: 10000000000
});
// / custom client

var search = instantsearch({
  appId: 'appid',
  apiKey: 'search_and_browse_only_custom_acl_key',
  indexName: '',
  createAlgoliaClient: function(algoliasearch, appId, apiKey) { 
    return customClient;
   }
  // my other custom settings / preferences for search...
});
```

**But, as suggested and mentioned in most places, try avoiding this if this is really not a must. This decreases overall performance of your search, also allows crawlers to scrape your site**

**Comment by Haroenv** [comment]
Just for reference, you can do this too: 


```js
var search = instantsearch({
  appId: 'appid',
  apiKey: 'search_and_browse_only_custom_acl_key',
  indexName: '',
  searchParameters: {
    paginationLimitedTo: 10000,
  },
  // my other custom settings / preferences for search...
});
```

Which has less overhead 😄

**Comment by Ardakilic** [comment]
@Haroenv Thank you again for the interest, however that didn't work on my case:

This is roughy my instantsearch.js:

```js
var search = instantsearch({
  appId: '',
  apiKey: '',
  indexName: '',
  urlSync: {
  useHash: false,
  mapping: {
    //...
  },
  trackedParameters: [
    //...
  ]
  },
  searchParameters: {
    paginationLimitedTo: 10000,
    hierarchicalFacetsRefinements: {
        'hierarchicalCategories.lv0': [category]
    },
    filters:'is_tr=1 AND status=1'
  }
});
```

Here's the issue on my Chrome console:

![image](https://cloud.githubusercontent.com/assets/2063957/25239062/b157556e-25f7-11e7-8d20-a64dc2feb1dc.png)

> Unknown parameter: paginationLimitedTo

Maybe the CDN is not updated ? ?

**Comment by Haroenv** [comment]
https://jsfiddle.net/vvoyer/0wm3donb/4/ is a simple replication of this. `paginationLimitedTo` isn't recognised as a correct option

**Comment by mthuret** [comment]
I believed that `paginationLimitedTo` have the scope `settings` and therefore can't be use as a search parameters? (it's not applied at query time).

**Comment by Ardakilic** [comment]
@mthuret Indeed, it doesn't work, saying it's an "unknown parameter: paginationLimitedTo". 

Any way to set it somewhere so we can use it?

**Comment by bobylito** [comment]
@Ardakilic Have you tried to set the configuration directly on the index, using a client and `setSettings`?

**Comment by Ardakilic** [comment]
@bobylito Hello, yes, but there's another issue regarding SortBySelector there: #2125

**Comment by bobylito** [comment]
This is not a query time parameter. It needs to be set when uploading the data to algolia.
