### ISSUE TITLE
transformData error message

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#212]
Can we put a more explicit error message when nothing is returned in the transformData function

**Comment by redox** [comment]
Yes indeed, not very clear.

**Comment by maxiloc** [comment]
I had the issue when trying to check the content passed to the widget with only a console.log, would it be possible to handle that by taking the original content if nothing is returned ?

**Comment by redox** [comment]
> taking the original content if nothing is returned ?

I decided to rather throw an explicit error message if you're not returning anything. Using the original data hides too much things. If you just want to debug, you can then just return the original data.

**Comment by maxiloc** [comment]
I totally fine with it, was just and idea :smile:
