### ISSUE TITLE
AutoComplete vs InstantSearch Result Count

### ISSUE THREAD

**Issue by brianO3world** [algolia/instantsearch.js#2127]
Afternoon,

Question I have on search result discrepancies between AutoComplete and InstantSearch. We're seeing a different count of results based on which tool is used.

The difference appears to be related to `&is_v=1` in the URL. I have read that this is for versioning, but I am seeing different results when this is present versus not.

For instance, a search using AutoComplete returns 14 results. The same search performed with InstantSearch (when that parameter is present) is 9. When I remove that parameter from the URL but perform the same search from InstantSearch I get 14 results.

Is there a way to normalize these results?

Thanks,
Brian

**Comment by bobylito** [comment]
That does not sound right. Do you have a URL with a link? (cf your support ticket :))

**Comment by brianO3world** [comment]
@bobylito It definitely struck me as a little strange as well. Is there a way to send a private message to you with the URL. This is a client dev environment, so I can't post publically.

**Comment by bobylito** [comment]
@brianO3world you can drop us an email via support@algolia.com and just mention that you are in contact with me via github.

**Comment by brianO3world** [comment]
Excellent. Thanks!
