### ISSUE TITLE
[Menu] Static values

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2130]
Right now the menu widget reacts on the result set to provide only the most meaningful facet values for the given search. However in the case of an editorial website, this can be out of the current practice of those websites where the menu is generally static.

What about adding an option or provide a new widget that would fetch the facet values during the init and use those values to always display options that may not be returned from the search?

**Comment by Haroenv** [comment]
I think an option `staticValues` would be the easiest to use, but might some extra complexity to the implementation, or would it be a simple one-time `if`?

**Comment by vvo** [comment]
Do we want to:

1. be able to provide manual values to a widget like menu?
example:

```js
menu({
  items: [{label: 'Oranges', value: 'orange'}]
})
```

Will then be the only values being displayed, and the counts would be also filled by reading the API.

2. add an option to express "even if count for this a facet value is 0, I want to keep it"

Are those two options in the scope/context of what you proposed?

About 1. We had the requirement/feature idea by @Shipow at some point to be able to just create a menu with predefined items where the order would just stick to this. But if we have other ways of answering 1. (for example, with transformItems in react-instantsearch), then we are fine I guess :)

**Comment by bobylito** [comment]
After discussing with @rayrutjes he seems to have a pretty solid implementation (without InstantSearch.js). His menu fetches first "all the values" with a request using search for facet values. There are no subsequent updates but we could imagine doing a rendering to display the counts. The order is based on the count (most used facet value first).

That could be the target behavior.

**Comment by mthuret** [comment]
@bobylito when reading @rayrutjes implementation it feels that it has in common with the "display facets with a count of zero" feature even though it's an alternate use case.

**Comment by vvo** [comment]
Another example where I wanted to submit items manually:
- https://discourse.algolia.com/t/defining-ranges-for-priceranges-widget/4219/4
- solution: https://codesandbox.io/s/mo0wrpm24x

The solution is not complete at all, it would require:
- graying option that are not relevant
- having the manual inputs

Which is why I believe this would make a good candidate for a true feature, ultimately I would have been pleased to be able to do:

```js
priceRanges({
  items: [{to: 12}, {from: 12, to: 30}, {to: 50}]
})
```

**Comment by francoischalifour** [comment]
We now explain all these solutions in the documentation section "[Modify the list of items in widgets](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/js/#modify-the-list-of-items-in-widgets)". They mostly leverage the `transformItems` option introduced in [2.10.0](https://github.com/algolia/instantsearch.js/blob/694c82b9a2230b160f6f5a47bb7da355066cdf85/CHANGELOG.md#2100-2018-08-08).

I'll close this issue – if you feel like this doesn't fully answer your needs for a specific use case, feel free to open a new issue.
