### ISSUE TITLE
Ability to change the namespaces of the BEM css classes

### ISSUE THREAD

**Issue by LukyVj** [algolia/instantsearch.js#2132]
For example : 

```
search.addWidget(
  instantsearch.widgets.whateverFeature({
    cssClasse: {
      nameSpace: 'foo-bar'
    }
  })
);
```
will change from :
`sbx-sffv__input`
to 
`foo-bar__input`

**Comment by bobylito** [comment]
Thanks for the proposal. With the move to instantsearch.css, I don't think we will go this way. Please open another if it is a big struggle. Thanks for participating 👍
