### ISSUE TITLE
V2 website review, updates

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2137]
Here's some feedback, I did compare the current website with one I worked heavily on (react-instantsearch). If there are things you absolutely don't want to add or change that's fine.

- [x] 1. **Edit this page**
![image](https://cloud.githubusercontent.com/assets/123822/25911411/fd3cdd5c-35b3-11e7-8723-f3ac7a9beeae.png)

This helped us many times with user doing PRs to quickly fix mistakes. The sooner we can get something like that even on the beta website, the sooner you will get free contributions!

- [x] 2. Syntax theme and copy to clipboard
![2017-05-10 19 10 59](https://cloud.githubusercontent.com/assets/123822/25911527/7842c9d0-35b4-11e7-99c0-cfc8abf85f64.gif)

We use the GitHub syntax theme. We have copy to clipboard button

- [x] 3. Migrating
![image](https://cloud.githubusercontent.com/assets/123822/25911663/0024743e-35b5-11e7-96e1-d66d0cdd04de.png) => "Migrating from V1"?

- [x] 4. InstantSearch.js instantsearch.js instantsearch
![image](https://cloud.githubusercontent.com/assets/123822/25911685/147e806e-35b5-11e7-9bc3-cbc3d98cadb6.png) => In many areas I spotted the usage of instantsearch.js and InstantSearch.js. This one could be written (`instantsearch` is the main component of InstantSearch.js)

- [ ] 5. API docs

Would you like to display it like this:

![image](https://cloud.githubusercontent.com/assets/123822/25911809/7d5ad3ee-35b5-11e7-91ee-0643668db946.png)

instead of

![image](https://cloud.githubusercontent.com/assets/123822/25911828/87a636d6-35b5-11e7-8c1d-27da2b49403b.png)

? Right now I have trouble identifying a bit the token around options (maybe just using underline like in the usage?). I do like the fact that it's very detailed though (with even links to mdn :D)

- [ ] 6. Cannot see the anchor when hovering: 
![image](https://cloud.githubusercontent.com/assets/123822/25911943/e9b4388c-35b5-11e7-94c1-5f80cf503f29.png)

**Comment by bobylito** [comment]
Thanks for the review. Lots of stuff that we actually wanted to add back :)

I personnally don't like the table layout, but there is plenty of rooms for improvement even without. (no designer has worked on that yet).

**Comment by bobylito** [comment]
5. and 6. will be done during the design part.
