### ISSUE TITLE
handle xss in templates

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2138]
cc @alexandremeunier

**Comment by rayrutjes** [comment]
Not sure if this is related, but here is what I did in WordPress to protect against XSS: https://github.com/algolia/algoliasearch-wordpress/commit/42ac2362155a7f90a9c00481d5e05cae107084dc

**Comment by bobylito** [comment]
Thanks @rayrutjes :) Any different view on the implementation is helpful. The main question is what API can we provide to the user? Do we try to magically do it for them? Do we provide hogan helpers?
