### ISSUE TITLE
[currentRefinements] clearsQuery

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2139]
## Current behaviour

When `clearsQuery` is `true`, the button for clearing the refinements also clears the query.

However if there are no other refinements, the button doesn't appear. Also the query is not considered a current refinement, therefore even though it would cleared by the button it doesn't appear.

## Proposed fix

Make the clearsQuery trigger the following changes:
 - the clear all button clears the query too (and is visible when only the query is set)
 - the query appears as a refinement

**Comment by bobylito** [comment]
cc @iam4x @mthuret @vvo @rayrutjes

**Comment by Haroenv** [comment]
What about making it show up when there’s a query, but not showing that in the refinements, it would look a bit weird.

**Comment by iam4x** [comment]
I'm good with your proposed fix 👍

**Comment by vvo** [comment]
I am fine with your proposal @bobylito. And if the user want to hide the query on display, what would he have to do?

**Comment by bobylito** [comment]
> And if the user want to hide the query on display, what would he have to do?

We have a white list mechanism which could be used. However it doesn't fit the usage of refinements that are not attribute based (query or any query parameters). Maybe we could extend the range of possibilities here?

**Comment by bobylito** [comment]
Ok that's too much of an edge case. Let's implement the clearsQuery that will only make the clear all button clear the query without any rendering of the query in the current refinements.

**Comment by fabregas4** [comment]
Hey guys, customer here... good discussion. Would including the search query as a refinement really be that weird? Consider the attached screenshot - I think this would be handy.
![alg-query-as-refinement](https://cloud.githubusercontent.com/assets/2221888/26114996/65d290dc-3a91-11e7-917e-8274ce23d1f9.png)

**Comment by bobylito** [comment]
> And if the user want to hide the query on display, what would he have to do?

Actually after thinking about it, if you've enabled `clearsQuery` isn't it reasonnable to have the whole package (the button is enabled when the query is not empty and the query appears in the refinements)?

**Comment by vvo** [comment]
I did not quite get what you proposed. If the question is is it ok to have the query appears in refinements then I would say yes, as @fabregas4 proposed and showed us.

With that said, let's see if anyone wants to hide the query afterwards and deal with that once it shows as a need/issue.

**Comment by bobylito** [comment]
What I propose is the following: when you choose to activate `clearsQuery`, we should display the query. On the other hand, if `clearsQuery` is `false` we don't display the query. This brings consistency to the feature: what you can see is what gets cleared.

**Comment by vvo** [comment]
Very good solution

**Comment by bobylito** [comment]
Fixed via #2414 and released in 2.2.0
