### ISSUE TITLE
[docs] Searching in docs does not jump to correct place in page

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#2141]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When on https://community.algolia.com/instantsearch.js/documentation/, If I search (eg. `label`), and click on the result or select it through the keyboard, nothing happens. I'm not redirected to the correct part of the doc.

![2017-05-16_11h26m07](https://cloud.githubusercontent.com/assets/283419/26099246/7dd6500e-3a2a-11e7-9551-69f716261cac.gif)

**Bug: What is the expected behavior?**
I would expect the page to jump to the selected part of the page/

**Bug: What browsers are impacted? Which versions?**
Tested on Chrome Version 57.0.2987.133 (64-bit) on Ubuntu

**Bug: What is the proposed solution?**
Selecting a result should jump to the correct part. Maybe it's time to use DocSearch on this website?

**Comment by Haroenv** [comment]
Will be fixed in v2 because the docs is completely different.

**Comment by pixelastic** [comment]
Won't we keep the v1 website up for people still using it?

**Comment by vvo** [comment]
Does work for me but I have seen situations of this happening even on GitHub where clicking on an anchors you are already in (from a url POV) does not work.

**Comment by pixelastic** [comment]
Can you try on [this url](https://community.algolia.com/instantsearch.js/documentation/) with `transf` as the search term and select the `transformData` answer? I tried on both Chrome and Firefox and I'm not redirected.

To be honest I'm not sure *where* I should be redirected, but having a search result that does nothing just looks bad

**Comment by Haroenv** [comment]
I can replicate your issue Tim, the `transformData` item goes towards /documentation/

**Comment by bobylito** [comment]
The index was not updated for a while sigh. The issue is no more with v2 (now using [docsearch by Algolia](https://community.algolia.com/docsearch/))
