### ISSUE TITLE
refinementList with a sub refinementList

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#2143]
Hello,

Is it possible to create a new widget that can handle sub refinements lists?

So for example we want to show brand + model in 1 refinement list like this:
- Brand 1
   - Model 1
   - Model 2
-Brand 2
   - Model 3
   - Model 4
- Brand 3
   - Model 5
etc.

Brand 1, 2 and 3 is generated by the attribute brand, model 1, 2, 3 etc by the attribute model but shows only the models that are available with the brandname that is listed above the models list.

Is this already available?

**Comment by Haroenv** [comment]
Did you take a look at [HierarchicalMenu](https://community.algolia.com/react-instantsearch/widgets/HierarchicalMenu.html)?

**Comment by Haroenv** [comment]
Not right now, because it has significant implications on lower levels of our libraries, but it is in our longer-term plan.

See also https://github.com/algolia/instantsearch.js/issues/2053

Have a great day!
