### ISSUE TITLE
Getting React errors in console

### ISSUE THREAD

**Issue by object505** [algolia/instantsearch.js#2154]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**Bug: What is the current behavior?**
Getting React warnings in console:
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**What is the version you are using? Always use the latest one before opening a bug issue.**
Latest, v1.11.11

**Comment by Haroenv** [comment]
This is only a warning, and will not impact your search experience, so you can ignore it. In 2.0.0-beta.1 this is no longer the case.

**Comment by timkelty** [comment]
@Haroenv I'm still getting this in `v2.0.0-beta.2`

**Comment by Haroenv** [comment]
You're right, we will fix it, but it doesn't have any impact on your app. It's a warning for when we switch to react 16

**Comment by Spone** [comment]
Hey, I have the following error in the console, when I load a page where I use instantsearch:

    Error: Invalid prop `hits` of type `array` supplied to `e`, expected `object`.

Is it connected to this issue? Should I open a new issue?

**Comment by timkelty** [comment]
@Spone I've seen the same warning with 1.x, however it isn't there in 2.x.

**Comment by bobylito** [comment]
Seems fixed :)
