### ISSUE TITLE
Disabling SFFV when there are few results visible keeps it disabled in some cases

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2156]
**Do you want to request a *feature* or report a *bug*?**

bug

Could you make a [jsfiddle](https://jsfiddle.net/vvoyer/0wm3donb/4/) that replicates this issue, it might be hard to find your exact use case otherwise @gabriel-kaam. Mostly how you load the extra facets.

**Bug: What is the current behavior?**

SFFV stays disabled when less than the maximum facets are visible, and more are loaded

**Bug: What is the expected behavior?**

SFFV to work when there are more than enough results

**Bug: What browsers are impacted? Which versions?**

all

**Bug: What is the proposed solution?**

Make the disabling of sffv opt-in instead of a default.

**What is the version you are using? Always use the latest one before opening a bug issue.**

v1.11.11 I guess, what version do you use @gabriel-kaam?

More detailed description at https://github.com/algolia/instantsearch.js/pull/2120#issuecomment-302405242

**Comment by Haroenv** [comment]
This is actually similar to the test case that was caught in https://github.com/algolia/instantsearch.js/pull/2120#pullrequestreview-33771811, but then not `isFromSearch`, but actually by scrolling.

**Comment by gabriel-kaam** [comment]
@Haroenv I use the CDN version https://cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.js .

The version live ATM is instantsearch.js **1.11.7**

**Comment by gabriel-kaam** [comment]
Here some extracts from our JS code
```javascript
// [...]

var facets_for_select = [{
    name: 'color',
    attribute_name: 'color_original',
    header_text: 'Couleurs',
    sort_by: ['isRefined', 'name:asc'],
    search_for_facet_values: {
      placeholder: 'Recherchez une couleur',
      no_results: 'Aucune couleur ne correspond'
    },
  },{

// [...]

  facets_for_select.forEach(function(facet_config) {
    // [...]
    try {
      search.addWidget(
        instantsearch.widgets.refinementList({
          autoHideContainer: true,
          container: '#filter-' + facet_config.name,
          attributeName: facet_config.attribute_name,
          sortBy: facet_config.sort_by ? facet_config.sort_by : ['isRefined', 'count:desc', 'name:asc'],
          limit: facet_config.limit ? facet_config.limit : 200,
          operator: 'or',
          cssClasses: cssClasses_for.filters,
          templates: {
            header: getHeader( facet_config.header_text ),
            item : facet_config.getItem ? facet_config.getItem : getItem,
          },
          searchForFacetValues: facet_config.search_for_facet_values && {
            placeholder: facet_config.search_for_facet_values.placeholder,
            templates: {
              noResults: '<div class="sffv_no-results">' +
                facet_config.search_for_facet_values.no_results +
                ' pour cette catégorie.</div>'
            }
          }
        })
      );
    } catch (e) {
      console.debug('Could not init widgets for: ' + facet_config.name)
    }
  });
```

**Comment by gabriel-kaam** [comment]
Quick update : downgraded to **v1.11.5** and got the searchboxes to work : https://www.shopsquare.fr/mode/femme/bomber

**Comment by bobylito** [comment]
@gabriel-kaam sorry it took so long for me to get back at you. Your use case of using a very big limit is not very often, we'll add a new option to opt-out of this mechanism.
