### ISSUE TITLE
RefinementListWidgetOptions.showMore should conditionally render

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#2160]
**Bug: What is the current behavior?**
`RefinementListWidgetOptions.showMore` template always renders, regardless of # of facets or `RefinementListWidgetOptions.limit`.

It should only render when the requested # of facets is greater than `RefinementListWidgetOptions.limit` (v1 behavior), or some sort of disabled class should be applied so it can be hidden with CSS.

https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html#struct-RefinementListWidgetOptions-showMore

Looks like it was brought up here, but I'm not seeing it fixed in `v2.0.0-beta.2`: https://github.com/algolia/instantsearch.js/issues/1455.

This works as expected in v1. The show more block isn't rendered at all if it is not applicable.

**What is the version you are using? Always use the latest one before opening a bug issue.**
`v2.0.0-beta.2`

**Comment by bobylito** [comment]
Thanks for the report @timkelty :)

Indeed we're missing an API in the connector that expresses the ability to actually do a toggle of the show more button. On it!

**Comment by bobylito** [comment]
I created a new build with the fix for this issue 2.0.0-beta.3 http://cdn.jsdelivr.net/npm/instantsearch.js@2.0.0-beta.3/dist/instantsearch.min.js
