### ISSUE TITLE
v2 rangeSlider/Rheostat: reinstate handle-lower/upper classes from v1

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#2162]
v1's slider had the following classes:
- `ais-range-slider--handle-lower`
- `ais-range-slider--handle-upper`

Without them, it can be annoying to style something like this, and makes migration from v1 to v2 more troublesome:

![screen shot 2017-05-23 at 8 23 07 am](https://cloud.githubusercontent.com/assets/18329/26354235/be2d3c64-3f91-11e7-96ff-c7b728970d06.png)

Would be great to have them back!

**What is the version you are using? Always use the latest one before opening a bug issue.**
v2.0.0-beta.2

**Comment by iam4x** [comment]
Fixed, will be released in next beta 👍
