### ISSUE TITLE
Currentrefinements widget should be able to sort numerical values as a number and not alphanumerically when multiple values for one facet are chosen and the facet value is a number.

### ISSUE THREAD

**Issue by Inwerpsel** [algolia/instantsearch.js#2164]
Refinement values are always sorted as strings and not as numbers when displaying multiple filters for one facet. In some cases, for example prices, it makes more sense to use the numerical value for sorting.

To reproduce:
- Go to [https://magento.algolia.com/home-decor/books-music.html#q=&idx=magento_default_products&p=0&hFR%5Bcategories.level0%5D%5B0%5D=Home%20%26%20Decor&is_v=1](https://magento.algolia.com/home-decor/books-music.html#q=&idx=magento_default_products&p=0&hFR%5Bcategories.level0%5D%5B0%5D=Home%20%26%20Decor&is_v=1)
- Use the price slider to apply a maximum price of $19.
- Use the price slider to apply a minimum price of $12 and see that refinements (under "Selected filters") are sorted by value.
- Change the minimum price to $7.
- The "maximum $19" price filter is now shown first because when sorted alphanumerically it comes before "$7".

**Comment by bobylito** [comment]
Hey @Inwerpsel thanks for opening this issue. We're not quite sure which API to apply but we're gonna think about it for one of the next release in v2.

Maybe we could provide a sortBy function for the refinements?

**Comment by francoischalifour** [comment]
We fixed this issue in InstantSearch v3 ([see example](https://instantsearchjs.netlify.com/stories/?path=/story/currentrefinements--with-rangeinput)).
