### ISSUE TITLE
InfiniteHits : specify CSS class for "show more" button

### ISSUE THREAD

**Issue by Spone** [algolia/instantsearch.js#2165]
**Do you want to request a *feature* or report a *bug*?**

A feature

**Feature: What is your use case for such a feature?**

I would like to be reuse an existing CSS class to style the button.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

You could add `options.cssClasses.showMoreButton` option, then the classes would be added to the `<button>` element.

**What is the version you are using? Always use the latest one before opening a bug issue.**

1.11.11

**Comment by bobylito** [comment]
That could be something that we should consider cc @mthuret @ronanlevesque

**Comment by mthuret** [comment]
If I'm not mistaken, with the IS.css new guidelines, the classname will be directly on the button and therefore the possibility of overriding it with an option will derive from it. Is it correct? @bobylito @ronanlevesque 
cf: https://instantsearch-css.netlify.com/widgets/infinite-hits/

**Comment by ronanlevesque** [comment]
That is correct. The available classes will be `.ais-InfiniteHits-loadMore` and `.ais-InfiniteHits-loadMore--disabled`.

**Comment by Spone** [comment]
Hey, it's been a year, and it's still something that I have to work-around... Any idea of when it'll be possible?

**Comment by samouss** [comment]
We are currently in the process to implement the IS.css guideline to InstantSearch. It will be possible to provide this CSS class in the upcoming version. But we don't have any ETA on it.

**Comment by Spone** [comment]
Would you accept a patch PR in the meantime?

**Comment by samouss** [comment]
Sure go for it!

**Comment by Spone** [comment]
Here you go: https://github.com/algolia/instantsearch.js/pull/3026

**Comment by samouss** [comment]
Close with #3026.
