### ISSUE TITLE
No CSS when installed with NPM since 1.11.9

### ISSUE THREAD

**Issue by cmalard** [algolia/instantsearch.js#2170]
**Do you want to request a *feature* or report a *bug*?**
bug

**Bug: What is the current behavior?**
On install with NPM as a dependency, `dist/instantsearch.css` contains only this :
```css
/*! instantsearch.js UNRELEASED | © Algolia Inc. and other contributors; Licensed MIT | github.com/algolia/instantsearch.js */

```
It seems to happen since v1.11.9 (940d635789deac6b197d8bc7e93b6c0fa6d6ad1f) wich removed `src/css/`.

**What is the version you are using? Always use the latest one before opening a bug issue.**
v1.11.11

**Comment by bobylito** [comment]
Thanks @cmalard for the report. Will look into that one :)

**Comment by vvo** [comment]
cc @iam4x Can we fix this for the v1.x track? This is breaking change for user loading the CSS if still present.

**Comment by iam4x** [comment]
CSS files are in the `/dist` folder with the correct content:

![image](https://cloud.githubusercontent.com/assets/893837/26824728/cd3f13ae-4ab2-11e7-9adb-b17f718b5430.png)

Can you try again with: `rm -rf node_modules/instantsearch.js && npm i instantsearch.js@^1.11.12` ?

**Comment by iam4x** [comment]
I can confirm that the bug is fixed with latest version, it was present in the version ranges you specified @cmalard.

Thank's @bobylito for the new version publish.
