### ISSUE TITLE
Proposal re. urlSync vs. custom URL params

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#2172]
`urlSync` makes it hard, if not impossible, to maintain custom parameters in a URL.

I have the example of a client who needs to keep a location label along with geo coordinates in the URL, along with the usual instantsearch.js search params.
Because of the debouncing delay that has been introduced, the workaround given in #960 does not work anymore: anything set on the URL is overriden after the debounce delay.

This is causing issues in implementations like this client's one, so I'd like to propose a solution to make it possible to have custom params living with the search ones in harmony ☮️ 

The main idea is to make `urlSync` the central point for handling URL params.

### Using a hook function
Considering the library's current design, it looks like the most sensible thing to do would be to have a hook in the `urlSync` config object, that allows one to provide extra parameters that should be serialized on the URL:

```js
const search = instantsearch({
  // ...
  urlSync: {
     customParameters: () => ({ location: "Paris, Ile de France", latLng: "48.864716,2.349014" })
  }
});
```
(yes, I know `aroundLatLng` can be serialized using  `trackedParameters`; it's just an example 🙂 )

The returned value from this hook would be used to enrich the URL params at the moment `urlSync` changes the History state and changes the URL.  
This allows anyone to maintain their own list of params very easily.

### An actual urlSync API
I'd love to see something more usable than this "throw everything in this function" hook.

What about making `urlSync` an actual object that has the role of managing the URL params for instantsearch? We could then have something like this:

```js
// Initialize...
const search = instantsearch(options);

// At some point, my custom param value changes:
search.urlSync.setParam('Location', 'Paris, Ile de France');
```

It would then provide an interface to set and get values from the URL, either custom or "official" one, and make it easier to manage in a large application.

Looking forward to your feedback!

**Comment by bobylito** [comment]
Thanks @olance on this one. This is very interesting, I don't have much to say on it yet because the current state of the url sync is buggy (plain buggy).

**Comment by bobylito** [comment]
The url sync is back to "normal", however it's still an open question.

**Comment by olance** [comment]
Happy to discuss further! :)

**Comment by bobylito** [comment]
Routing is out and let you customize the URL completely. More [information in the guide](https://community.algolia.com/instantsearch.js/v2/guides/routing.html)

**Comment by olance** [comment]
Cool stuff @bobylito, thanks! 🙂
