### ISSUE TITLE
v2: AlgoliaSearchHelper events not handled from widget methods

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#2176]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**Bug: What is the current behavior?**
Listening for events (`helper.on`) within a widget's `init` method does not work. Worked in v1.

- jsFiddle with 2.0.0.beta.5: https://jsfiddle.net/timkelty/ufaycett
- same jsFiddle, but with 1.x latest: https://jsfiddle.net/timkelty/4s70qkq0/

**What is the version you are using? Always use the latest one before opening a bug issue.**
2.0.0.beta.5

**Comment by bobylito** [comment]
I can even add that this happens when the search function is implemented. This was introduced with ba27df3bf3bc99efb5080a0dd1c9484236755214 because we now rely on prototypal inheritance to implement the `searchFunction` mechanics.

**Comment by bobylito** [comment]
fixed in v2.0.0
