### ISSUE TITLE
Question : use instant search with google map

### ISSUE THREAD

**Issue by odecharette** [algolia/instantsearch.js#2178]
Hi,

I'm using Algolia intantsearch and I think it's amaizing !
Now I'd like to add a goole map to search for items (map and refinment list has to be linked)

I found this example : https://community.algolia.com/instantsearch.js/examples/tourism/
This is exactlly what I want

**But I miss some functionnalities** 
- Style the map
- Add pop-up windows on markers

I've search for 2 hours in the internet and couldn't find any good answer.
It seams I have to build a custom widget ? How ?
Maybe is there a map plugin compatible with Algolia instantSearch (http://leafletjs.com, https://www.mapbox.com) ?

My website is developped with Symfony 3 and Jquery

Many thanks for your help
Olivia

**Comment by bobylito** [comment]
Hi @odecharette Are you using https://github.com/instantsearch/instantsearch-googlemaps?

**Comment by odecharette** [comment]
Yes I am but there is no option to style the map and create pop-up windows on marker..

**Comment by bobylito** [comment]
We plan to release a new widget that will fill this need in the v2 branch. In the mean, the best solution will be to create your [own custom widget](https://community.algolia.com/instantsearch.js/documentation/#custom-widgets). This way you'll be able to connect to any of the map rendering that you mentioned.

**Comment by odecharette** [comment]
Thanks 👍 
Do you have a date for the v2 branch ?
Could you give me a piece of code to create my own custom widget with the map ?

**Comment by vvo** [comment]
Hi @odecharette, we do have a jsFiddle that show the basics of connection google maps widget: https://jsfiddle.net/wkjyev3p/8/

It will get even easier with V2 (not hard ETA for now, but soon enough)

**Comment by odecharette** [comment]
Thanks a lot ! I'm gone try immediatly

**Comment by odecharette** [comment]
It's working :)
I close the issue

**Comment by vvo** [comment]
💥  I would love to see the results :D
