### ISSUE TITLE
Replay a search in the backend

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2189]
Sometimes we'd like the backend to generate a report, or do a recurring search in the backend. We should provide a guide on how to do that using helper.getQuery

**Comment by francoischalifour** [comment]
We wrote a guide about [InstantSearch on the Backend](https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/js/#introduction).

Note that we also provide [Analytics](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/improve-relevance-with-analytics/) now.
