### ISSUE TITLE
[v2 docs] run is not running 

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2192]
> Error: Container must be `string` or `HTMLElement`. Unable to find #categories

seems to be coming from 

```js

/**
 * Return the container. If it's a string, it is considered a
 * css selector and retrieves the first matching element. Otherwise
 * test if it validates that it's a correct DOMElement.
 * @param {string|DOMElement} selectorOrHTMLElement a selector or a node
 * @return {DOMElement} The resolved DOMElement
 * @throws Error when the type is not correct
 */
function getContainerNode(selectorOrHTMLElement) {
  const isFromString = typeof selectorOrHTMLElement === 'string';
  let domElement;
  if (isFromString) {
    domElement = document.querySelector(selectorOrHTMLElement);
  } else {
    domElement = selectorOrHTMLElement;
  }

  if (!isDomElement(domElement)) {
    let errorMessage = 'Container must be `string` or `HTMLElement`.';
    if (isFromString) {
      errorMessage += ` Unable to find ${selectorOrHTMLElement}`;
    }
    throw new Error(errorMessage);
  }

  return domElement;
}
```

https://community.algolia.com/instantsearch.js/v2/guides/migration.html

A container does get written but no instantsearch

<img width="868" alt="screen shot 2017-06-14 at 11 03 13" src="https://user-images.githubusercontent.com/6270048/27124338-16af9498-50f1-11e7-8024-fb6969e19a68.png">

**Comment by vvo** [comment]
On which page do you have this being triggered? That one is working for me: https://community.algolia.com/instantsearch.js/v2/guides/migration.html

**Comment by bobylito** [comment]
This one shouldn't have a run in the first place :)
