### ISSUE TITLE
SearchBox improvements

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2200]
Search should implement an easily identifiable input with the ability to clear the query.

Changes needed:
 - follow the same patterns as in http://shipow.github.io/searchbox/
 - provide a clear function in the connector
 - have templates for the magnifying glass (identifying the search field) and the cross (button to clear the query)

[Example on react-instantsearch](https://community.algolia.com/react-instantsearch/storybook/?selectedKind=SearchBox&selectedStory=default&full=0&down=1&left=1&panelRight=1&downPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by iam4x** [comment]
Merged in develop, published in v2.0.0-rc1 🎉
