### ISSUE TITLE
Add a widget showcase to the documentation

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2210]
The new v2 documentation keep and enhance most aspects of the previous aspects of the previous documentation. However it does not contain a page where we can see all the widgets in a single glance like we could in the previous documentation: discoverability of widgets is less easy.

## Proposal

Add a page where all the widgets are rendered. This page will be underneath the introduction page and before the widgets link (in the sidebar).

**Comment by bobylito** [comment]
It could also be the landing page of the widgets and we could rename `introduction` to `concepts`

**Comment by Haroenv** [comment]
My suggestion is actually deploying the dev-novel and then linking to it.

**Comment by bobylito** [comment]
Dev novel is awesome but that's not its main purpose. Using it as a showcase has a few problems:
 - does not fit in the website (which breaks the whole idea of a full integrated doc)
 - has many test cases which will be hard to grasp for users

That does not that we shouldn't publish it. I think it'll be a great resources for users to have online :)
