### ISSUE TITLE
Update version number automatically in content

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2211]
In v2 we have many reference to the current version number and we want from now on to only specify specific version number. But there are multiple instance of the version in the markdown: we need to update that automatically in the release process.

**Comment by Haroenv** [comment]
Can we have something like `{{ VERSION }}` in markdown, and if metalsmith does not have that feature yet, we can simply `.replace('{{ VERSION }}', theActualVersion)`  in the build, right?

**Comment by bobylito** [comment]
MetalSmith being very flexible we can add that to the pipeline :) 👍

**Comment by bobylito** [comment]
This one is too painful to wait for 2.1. Moving it to 2.0.x
