### ISSUE TITLE
Question: Change hitsPerPage when filtering?

### ISSUE THREAD

**Issue by dhduc** [algolia/instantsearch.js#2213]
Hello,
Just a question, how I can change the hitsPerPage parameter for hits widget each time I filtering.
Thanks.

**Comment by Haroenv** [comment]
Do you want a different hitsPerPage, depending on which filter is enabled?

**Comment by dhduc** [comment]
The number of hits depending on which filter is active, of course, but the number of hits on per page always is a value that was configured. And I want to change that value each time I filter, it will be depended on other parameters.

**Comment by Haroenv** [comment]
You can use the [`searchFunction`](https://community.algolia.com/instantsearch.js/v2/instantsearch.html#struct-InstantSearchOptions-searchFunction). In there you can use the helper [methods](https://community.algolia.com/algoliasearch-helper-js/reference.html) to get the currently refined options and finally set `hitsPerPage` to the value needed before searching. 

Feel free to reopen if you need more information.

**Comment by firestar300** [comment]
It is possible to do it with the last major version of Instant Search ? I would like to change the hits per page when the user filter on a "Menu" widget item like the demo https://www.algolia.com/search/
