### ISSUE TITLE
Angular 4 example of instantsearch.js

### ISSUE THREAD

**Issue by foufrix** [algolia/instantsearch.js#2214]
Hello, 

I discovered algolia and i love it.

The problem is my project is running in angular 4, and i've failed to make it work :/

Is there any way to have a simple example of instant search running with angular 4 so that i can see what i've done wrong ? 

Thanks in advance to algolia Team

**Comment by bobylito** [comment]
Hi @foufrix, thanks for opening this issue.

There is no angular 4 example at the moment. But we're working at what could a good strategy for going there.

**Comment by vvo** [comment]
Anyone willing to have support for Angular and Algolia's InstantSearch can 👍  this issue.

**Comment by foufrix** [comment]
@vvo Can you keep me inform as quick as possible if you plan to develop instantsarch for angular, as i use it mainly. I'm wondering if i should continue to use it and implement some functionalities by myself, to wait for instantsearchjs to come to angular OR i shall switch to react, but this mean that i have to restart praticly from start.

Thanks for your reaction on this issue

**Comment by iam4x** [comment]
Hello @foufrix 👋

Have you tried to use the connectors API https://community.algolia.com/instantsearch.js/v2/guides/customization.html ?

I've built recently components for [etch](https://github.com/atom/etch) (which is yet another framework for building webpages) using the connectors API and it was pretty straightforward 👍 

If not and if it doesn't fit your needs, I'll find some time to try Angular v4 and provide an example on how to use it with InstantSearch.js

Cheers, Max.

**Comment by vvo** [comment]
@foufrix InstantSearch Angular is not started today and will take time to build.

If you want to stick with Angular you should go for either the connectors API as @iam4x said. Or directly use the [JavaScript client](https://github.com/algolia/algoliasearch-client-javascript) and [the helper](https://community.algolia.com/algoliasearch-helper-js/).

**Comment by foufrix** [comment]
Thanks for your help, i finally manage to make results appears as i wanted by using the json i get back from algolia when i send a request. I did not try the connectors API but i'll take a look when i have the time. Thanks !

**Comment by dochecknow** [comment]
A possible short term solution is goto https://github.com/algolia/algoliasearch-client-javascript

**Comment by Haroenv** [comment]
We're currently reviewing a tutorial on how to make InstantSearch.js completely work with Angular without using the algoliasearch JavaScript client directly.

**Comment by iam4x** [comment]
This has been shipped with the v2.1.0, you can find the Angular guide [here](https://community.algolia.com/instantsearch.js/v2/guides/angular-integration.html)
