### ISSUE TITLE
doc: Broken links on Community > Examples

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/instantsearch.js#2217]
On the [Examples page of the online documentation](https://community.algolia.com/instantsearch.js/examples/), the "View code" links for all three demo applications are broken.

**Comment by Haroenv** [comment]
Should become `https://github.com/algolia/instantsearch.js/tree/master/docgen/src/examples/EXAMPLE_NAME`

**Comment by bobylito** [comment]
Nice catch!

**Comment by bobylito** [comment]
And it's fixed! :D
