### ISSUE TITLE
[ Design ] Mobile menu links redirect to a 404

### ISSUE THREAD

**Issue by LukyVj** [algolia/instantsearch.js#2220]
A few links of the mobile menu doesn't work when clicked, they redirect to a 404

![](https://puu.sh/wC3hl/b5212482ea.gif)

**Comment by bobylito** [comment]
Can you give more context here? Screenshots and scenario to reproduce are very welcome.

**Comment by Haroenv** [comment]
Yep, the mobile menu seems to link to /whatever instead of /is.js ...

**Comment by bobylito** [comment]
working on it :)
