### ISSUE TITLE
 Need to create analytical graphs of the instantsearch results

### ISSUE THREAD

**Issue by hajjoura11** [algolia/instantsearch.js#2222]
Is the the any way to create analytics graphs of the instantsearch resultats. For example, if we 
do a search on the films and we want to display some analytics graphs showing the istribution of films by category or year or ... 
I thought to add a custom widget that creates the graphics.  I've read through both instantsearch docs and the helper docs but just not getting it. I don't find how to get the resultas values !! Can anyone guide me on creating this? Or suggest me another solution ? 

Thank you and any help would be great!

**Comment by Haroenv** [comment]
Hey @hajjoura11,

Did you see the guide on customisation on the website? Your idea seems very interesting, what data do you want to create the graph, is it created with the hits? If so, you can use [connectHits](https://community.algolia.com/instantsearch.js/v2/connectors/connectHits.html), what is also interesting is the stats about the current search, you can find those in [connectStats](https://community.algolia.com/instantsearch.js/v2/connectors/connectStats.html). 

Does that give you help? Feel free to continue asking more information 

guide on connectors: https://community.algolia.com/instantsearch.js/v2/guides/customization.html

**Comment by hajjoura11** [comment]
Hey @Haroenv ,

Thank you so much for your super quick and helpfull response.
Yes I see the guide on customisation on the site but I don't get it. 
Concerning the data, I need the hits and the facet results. For example, if I do my search on the films. I will need the values of 'category' and 'year' attributes and their stats to show the distribution of films by category or year ..

The connectors seems to be a good solution, I will try it and tell you the results..

Thank you again for your help ..

**Comment by Haroenv** [comment]
Aha, for having the data on the facets, you can use [connectMenu](https://community.algolia.com/instantsearch.js/v2/connectors/connectMenu.html) or [connectRefinementList](https://community.algolia.com/instantsearch.js/v2/connectors/connectRefinementList.html)

I'll close this for now, but feel free to reopen if there's more information needed. 

It would also be helpful afterwards if you posted your stats solution (it's very innovative 🎉) on our [forum](https://discourse.algolia.com/c/show-tell)

**Comment by hajjoura11** [comment]
Ok thank you ! I will post my solution when when it turns well ...
