### ISSUE TITLE
remove `is_v=` from URL

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2233]
We thought in early v1, it would be great to have that to make URL easy to upgrade. After two years, we haven't a usage for it and it's cryptic. I propose to remove it.

Since nothing relies on it, it shouldn't be a breaking change.

Thoughts?

**Comment by Haroenv** [comment]
Overall I think we should review what to put in the URL together when we make a way to edit how the url sync editable by the user 

?q=&idx=airbnb&p=0&dFR%5Broom_type%5D%5B0%5D=Private%20room&nR%5Bperson_capacity%5D%5B%3E%3D%5D%5B0%5D=1&is_v=2

I think we can also leave out the things that are still the same value as set by default (index for example, or default refinements), that would make the URL cleaner.

Just removing the version as a first step is a definite 👍 from me

related issues: #2216, #2172, #1813, #1799, #1366

**Comment by rayrutjes** [comment]
Nice to see this move forward.
I think we should make this part re-usable outside of IS maybe. I'd love to allow users of Vue-InstantSearch to have some kind url-sync experience even if they don't use the router.

The current helper methods are not very easy to re-usable.

**Comment by Haroenv** [comment]
Yes, IMO url sync could very well work as a third party library based on the helper state!

**Comment by bobylito** [comment]
> Yes, IMO url sync could very well work as a third party library based on the helper state!

Yes indeed.
