### ISSUE TITLE
Make V2 the default homepage?

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2236]
V2 is officially out. Should we make the https://community.algolia.com/instantsearch.js/ homepage the V2 one and then display a banner for V1 docs (or just a top menu item so it's less intrusive)?

It's not a big priority. But could still be confusing for newcomers searching for InstantSearch.js and ending up on the V1 website.
It's very easy to dismiss a banner because it looks a bit like an ad ("This website use cookies..." effect)

The hierarchy could be:
- / => V2 homepage
- /v2/* v2 docs
- /* others, v1 docs (so there's no need to handle 301 etc. for now)

The goal being to push V2 even more.

**Comment by Haroenv** [comment]
/ should redirect to /v2/ IMO, rather than showing the homepage. Leaves more freedom for the future

**Comment by vvo** [comment]
Ideally yes, with the current setup that's not doable I think (GitHub pages has no redirect).

**Comment by bobylito** [comment]
> Ideally yes, with the current setup that's not doable I think (GitHub pages has no redirect).

But JS can

**Comment by vvo** [comment]
> But JS can

Yes, unsure how google will present it though, it will still have to load most of the HTML page. But if it's an easier change than trying to fit the V2 homepage on /. Then let's do it this way yes.

**Comment by Shipow** [comment]
I'd like to move V2 to root and keep the current under /v1/
it needs to handle clean redirection. Github doesn't allow .htaccess and I would avoid any js redirection.

Possibilities to explore.
- html files with HTTP-REFRESH meta tag
- cloudflare

We need clean 301.

**Comment by bobylito** [comment]
> I'd like to move V2 to root and keep the current under /v1/

Is there a way to prevent the broken links to the doc?

**Comment by Shipow** [comment]
I don't know yet.
We can't really afford a move that'd break it, so i guess we'll have to figure it out :p
Github starts to be painful here.

**Comment by Shipow** [comment]
We can go with @vvo solution meanwhile!

**Comment by vvo** [comment]
> Is there a way to prevent the broken links to the doc?

Manually put 301 redirects in Cloudflare is the only way

**Comment by bobylito** [comment]
Cool, @vvo wanna open a PR?
