### ISSUE TITLE
Default styling of search box has some issues

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2241]
**Do you want to request a *feature* or report a *bug*?**

bug

**Bug: What is the current behavior?**

Styling of the searchBox widget seems to have odd spacing/appearance: none issues

https://codepen.io/Haroenv/pen/7ea9fcf2b263fbf4c7884e04055c2d02

<img width="392" alt="screen shot 2017-07-17 at 16 47 33" src="https://user-images.githubusercontent.com/6270048/28274473-4dd09c08-6b11-11e7-802a-3ca31324416b.png">
<img width="395" alt="screen shot 2017-07-17 at 16 47 20" src="https://user-images.githubusercontent.com/6270048/28274472-4dcec5d6-6b11-11e7-9bf8-c8516e42cc3a.png">

**Bug: What is the expected behavior?**

look exactly the same as the React InstantSearch Searchbox

**Bug: What browsers are impacted? Which versions?**

chrome, safari, 2.x

**Bug: What is the proposed solution?**

fix the styling 😓

**Comment by iam4x** [comment]
Simple to fix, apply this CSS to instantsearch elements:

```css
*, *:after, *:before {
	box-sizing: border-box;
}
```

Will drop a PR, nice catch @Haroenv  👍
