### ISSUE TITLE
Algolia Instantsearch Ionrangeslider customization

### ISSUE THREAD

**Issue by divya2012** [algolia/instantsearch.js#2272]
We need to have a custom widget for Ionrangeslider with range input boxes. Input range box changes need to update the Ionrangeslider and viceversa. 

![slider-range](https://user-images.githubusercontent.com/3095507/28908366-f37274a6-7840-11e7-90dd-abdcfcca235f.png)

**Comment by Haroenv** [comment]
Hello @divya2012,

What you should do for that to work consistently, is making a `connectRangeSlider` widget. You can read up on how to make a connector in [this guide](https://community.algolia.com/instantsearch.js/v2/guides/customization.html) and read the specific documentation for [`connectRangeSlider`](https://community.algolia.com/instantsearch.js/v2/connectors/connectRangeSlider.html) to know which information is used exactly.

Does that help you enough?

**Comment by divya2012** [comment]
Hello @Haroenv ,

While I tried to use connectors for creating custom widget for sortselector using connectSortBySelector, I got an error "**connector not defined**", so I was not able to proceed further. I am using shopify algolia instantsearch.js for creating widgets, do we need to add any library for the connectors to use in instantsearch. 

I have tried to integrate the input box range with Ionrangeslider by another method, but the issue is that the rangeslider will not get updated on changing the input range values,the other way ie on changing the rangeslider the input range boxes gets updated. It would be helpful if we get a solution to update the Ionrangeslider on text field change event.

**Comment by Haroenv** [comment]
Ah, the method I described won't work in the Shopify extension, since it's still using InstantSearch v1. 

It's been a while since I used this, but we should also have a ionRange InstantSearch component ([link](https://github.com/instantsearch/instantsearch-ion.rangeSlider)).

**Comment by divya2012** [comment]
I am using the ionRange InstantSearch component for creating slider rather than the default instantsearch rangeslider widget. But there is no much information on using ionrange instantsearch component

**Comment by Haroenv** [comment]
Hi! This issue has been opened without reply for a while. I'll close it now, but feel free to reply to our initial questions, and we'll gladly reopen if the original issue isn't solved yet.

Have a nice day!
