### ISSUE TITLE
Link to the searching guides on the specific widgets/connectors doc

### ISSUE THREAD

**Issue by iam4x** [algolia/instantsearch.js#2274]
I had a live-chat today, where the user had an issue with the pagination because it did not calculate the correct number of pages.

In the end, it was a limitation from Algolia API documented here (https://www.algolia.com/doc/guides/searching/pagination/#pagination-limitations) in which its automatically limit the max nbPages to 34.

The user suggested to link this kind of searching guides to the connectors/widgets pages to learn more on how it works behind and avoid this kind of frustration thinking that Algolia is broken.

What do you think @Haroenv @bobylito ?

**Comment by Haroenv** [comment]
Yep, that seems perfect to me, a button to "read more on the API documentation" or something would fit. 

Things like `hierarchicalMenu` should then be linked to the helper documentation maybe?

**Comment by bobylito** [comment]
That seems fair to do that (and of great help for our users). Let's have that in mind for all the use cases, but here I don't see more links to add.
