### ISSUE TITLE
Small Datasets not working?

### ISSUE THREAD

**Issue by mindbits** [algolia/instantsearch.js#2280]
I found some more serious, breaking issues with the slider in V2. 

To demonstrate them I wanted to create a small subset but this only works with the search box but not the refinement list or more than one slider. 

Taking the full dataset (6000+ entries) is no problem besides the problems with the slider. 

So is there a minimum number of data points that instantsearch needs to work?

https://jsfiddle.net/bjav561j/

This is the dataset used:

```json
[
{
  "name": "Sandra",
  "year_of_birth": 1993, 
  "hair_color": "Blond",
  "height": 1, 
  "objectID": "Sandra"
},
{
  "name": "Michael",
  "year_of_birth": 1960, 
  "hair_color": "Brown",
  "height": 2, 
  "objectID": "Michael"
},
{
  "name": "Petra",
  "year_of_birth": 1985, 
  "hair_color": "Black",
  "height": 3, 
  "objectID": "Petra"
},
{
  "name": "Jim",
  "year_of_birth": 1975, 
  "hair_color": "Brown",
  "height": 4, 
  "objectID": "Jim"
},
{
  "name": "Marc",
  "year_of_birth": 1987, 
  "hair_color": "Blond",
  "height": 5, 
  "objectID": "Marc"
},
{
  "name": "John",
  "year_of_birth": 1960, 
  "hair_color": "Black",
  "height": 6, 
  "objectID": "Sandra"
},
{
  "name": "Kelly",
  "year_of_birth": 1998, 
  "hair_color": "Black",
  "height": 7, 
  "objectID": "Kelly"
},
{
  "name": "Adriana",
  "year_of_birth": 1990, 
  "hair_color": "Brown",
  "height": 8, 
  "objectID": "Adriana"
},
{
  "name": "Jennifer",
  "year_of_birth": 1978, 
  "hair_color": "Blond",
  "height": 9, 
  "objectID": "Jennifer"
},
{
  "name": "Sarah",
  "year_of_birth": 1988, 
  "hair_color": "Blonde",
  "height": 10, 
  "objectID": "Sarah"
},
{
  "name": "Otto",
  "year_of_birth": 1999, 
  "hair_color": "Red",
  "height": 11, 
  "objectID": "Otto"
},
{
  "name": "Paul",
  "year_of_birth": 1986, 
  "hair_color": "Brown",
  "height": 12, 
  "objectID": "Paul"
}]
```

**Comment by iam4x** [comment]
Thank you for the repro case, this is definitely a bug.

**Comment by iam4x** [comment]
Can you check that your index `slider_test` has `year_of_birth` and `hair_color` has attributes for faceting enabled in the dashboard?

**Comment by Haroenv** [comment]
I can confirm what @iam4x said, this works with your dataset when I set `year_of_birth` and `height` as `attributesForFaceting`

You can find that in the index settings in the dashboard (and via API clients too)

<img width="1198" alt="screen shot 2017-08-09 at 17 52 39" src="https://user-images.githubusercontent.com/6270048/29130974-a39254ca-7d2b-11e7-851e-e1837fef7d7d.png">
