### ISSUE TITLE
Make "run example" more visible 

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2281]
The contrast on the "run" button is pretty low, which causes it to be missed by people not familiar with the doc page. It should have more contrast, maybe a 🏃‍♀️ or 🚀 emoji there

**Comment by bobylito** [comment]
@auareyoualgolia Can you give us your insight on that?

**Comment by auareyoualgolia** [comment]
Sure!! Can I get screenshot please? :)

**Comment by bobylito** [comment]
Sure @auareyoualgolia :)

<img width="880" alt="screen shot 2017-08-29 at 10 58 54 am" src="https://user-images.githubusercontent.com/393765/29813068-18936f20-8ca9-11e7-8de1-92c1b459f6f6.png">

**Comment by auareyoualgolia** [comment]
I think the main issue is the position of the button, it should be on the very right to gain a bit more visibility, and if we fix the color like this I think it will really improve. 
![image](https://user-images.githubusercontent.com/26247132/29814048-4878c82c-8cac-11e7-8858-ada20d2ffc35.png)

Ignore the icon for copy, it's from the last iteration we did :)

**Comment by auareyoualgolia** [comment]
You could also go for this one, if you don't want it to be something that draws attention as you scroll: 
![image](https://user-images.githubusercontent.com/26247132/29814123-84003aec-8cac-11e7-8ea9-69bb8697fd56.png)

**Comment by francoischalifour** [comment]
Closed because the documentation has been migrated to the [Algolia documentation website](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/).
