### ISSUE TITLE
Allow faceting on non-scalar attributes (e.g. for refinementList)

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#2283]
**Do you want to request a *feature* or report a *bug*?**
*feature*

I have an attribute like so:

```js
{
  productCategories: {
    title: 'Kayak',
    value: 'kayak',
    level: 1,
  } 
}
```

Currently, I have a `refinementList` widget, with the `attributeName` set to `productCategories.title`.

Works, but isn't quite what I want. I _want_ to set the `attributeName` to simply `productCategories`, and the be able to use all of those properties to render (and filter) the template.

Here's my (non-working) attempt for configuring a `refinementList` widget:

```js
{
      attributeName: 'productCategories',
      templates: {
        item: (data) => {
          const template = Hogan.compile(defaultTemplates.item);

          if (data.level > 1) {
            return null;
          }
        
          return template.render(data);
        }
      },

      transformData: {
        item: (data) => {
          return Object.assign(data, {
            label: data.value.title,
            value: data.value.slug,
          });
        }
      }
}
```

↑ I'm attempting to set the `attributeName` to `productCategories`, hoping that that would pass the whole object as `data.value` to `transformData.item`. I'm also attempting to filter out items based on some other data in that object in in `templates.item`.

It seems like I need another method/option to prep the data?

Related: https://github.com/algolia/instantsearch.js/issues/739

**Comment by Haroenv** [comment]
Thanks for this very clear issue, I think I've heard of similar use cases before, and IIRC it's possible, but I'd have to research exactly how it's done. If meanwhile someone else finds the answer faster than me, that would be nice

**Comment by francoischalifour** [comment]
You can now use [`transformItems`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-transformitems), introduced in [2.10.0](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#2100-2018-08-08).

You can read more on how to migrate to this API in [our InstantSearch.js v3 migration guide](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/#transformdata-is-replaced-by-transformitems).
