### ISSUE TITLE
Pagination Widget autoHideContainer does not hide the entire element.

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [algolia/instantsearch.js#2287]
**Do you want to request a *feature* or report a *bug*?**
A Bug

**Bug: What is the current behavior?**
When no results returned, `autoHideContainer` on the Pagination widget doesn't hide the entire element. 

You can view this behaviour here by searching for something with no results: https://jsfiddle.net/gmattucc/qxhpm91j/

**Bug: What is the expected behavior?**
That the entire pagination element is hidden like the behaviour of other widgets.

**Bug: What browsers are impacted? Which versions?**
All

**Bug: What is the proposed solution?**
Have the data react root have `display=none` like all the other widgets.

**What is the version you are using? Always use the latest one before opening a bug issue.**
v2.0.2

**Comment by iam4x** [comment]
Thanks for reporting the issue @Giovanni-Mattucci
