### ISSUE TITLE
hitsPerPageSelector default value in v2 

### ISSUE THREAD

**Issue by denisjacquemin** [algolia/instantsearch.js#2288]
Hi,

No more hitsPerPage in hits since v2.

How do we set a default value for `hitsPerPageSelector` Widget in instantsearch v2?

Thanks

**Comment by Haroenv** [comment]
Just checked and I confirm that you can’t preselect a value, but I think this also wasn’t possible in v1 from reading the docs. We should probably add this option.

**Comment by vvo** [comment]
The solution is this:

```
instantsearch({searchParameters: {hitsPerPage: 3}})
```

So that no matter if you use our widgets you can always set it at the top level.

**Comment by denisjacquemin** [comment]
Perfect thanks, it works
