### ISSUE TITLE
Comma separated values in CustomFields

### ISSUE THREAD

**Issue by divya2012** [algolia/instantsearch.js#2290]
Can anyone provide a solution to represent comma separated values entered using customFields in shopify, as filters using algolia instantsearch.

![customfields](https://user-images.githubusercontent.com/3095507/29505474-305ea570-8664-11e7-91aa-91827797aa44.png)

**Comment by iam4x** [comment]
Hello @divya2012 I cannot understand your problem, is it related to Wordpress Advanced Custom Fields?

**Comment by divya2012** [comment]
Hi, @iam4x ,

Not Wordpress customfields, I am mentioning about the CustomField chrome extension, that is used to add customfields to products in shopify. This customfield extension uses shopify metafields to save values to products. For eg. refer the attached file. I need to show the customfileds as facets in algolia instantsearch UI. For eg, if I select ruby under filter, then all the products that contains ruby under other material field should come up.

**Comment by iam4x** [comment]
I'm sorry I won't be able to help you @divya2012 because I have no knowledge about Shopify.

But, we can help you through the specific Algolia here: https://www.algolia.com/doc/faq/basics/how-to-contact-support/

Just select issue and describe your issue, it will be forwarded to the right person 👍
