### ISSUE TITLE
Unpredictable range slider behaviour on mobile devices

### ISSUE THREAD

**Issue by gsenior** [algolia/instantsearch.js#2293]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**Bug: What is the current behaviour?**
The upper bound handle of the range slider widget is unpredictable and/or intermittently unresponsive on mobile devices. The lower bound handle appears to be unaffected.

Example available via [this fiddle](https://jsfiddle.net/gsenior/bLjtmzku/1/).

Also, when utilising multiple range sliders, the upper bound handle of slider A can occasionally be moved by the lower bound handle of slider B.

![slider-issue](https://user-images.githubusercontent.com/768967/29617623-5c2cda32-880d-11e7-9628-ec830183179d.gif)

**Bug: What browsers are impacted? Which versions?**
We have reproduced the issue on the following:

- Chrome v60 on Android 7.1.2
- Safari on iOS 10.3.3 
- Chrome v60 on iOS 10.3.3

It can also be replicated on desktop Chrome (v60) by using the Developer Tools -> Device Toolbar -> (e.g. Nexus 5X).

**Bug: What is the proposed solution?**
After a bit of hunting around, I _think_ this is related to Preact, Rheostat and event handling. I've created my own build of instantsearch.js, swapping out Preact for React and the issue is resolved. 

I wonder if it is related this bug - https://github.com/iam4x/preact-key0-repro-bug?

**Comment by iam4x** [comment]
Hello @gsenior 

Thanks a lot for the bug report and the whole investigation around it. This might be something really hard to fix.

I'll investigate more and will create an issue on the preact repository if I find the root cause.

I'll keep you updated.

**Comment by mindbits** [comment]
Is there an update to this? 

The slider is unusable on mobile.

The whole Slider in V2 is so annoying , useless and full of bugs. I have no idea why the ion slider was replaced.

**Comment by DeanMW** [comment]
Any updates here @iam4x? We're having the same issue on production at the moment.
