### ISSUE TITLE
Issue with button & ais-refinement-list

### ISSUE THREAD

**Issue by victoriasr** [algolia/instantsearch.js#2294]
Hi! I'm currently working with algolia/instantsearch and i would like checkbox buttons so i wrote this code : 
```
<ais-refinement-list attribute-name="Source_type" :type="checkbox">
</ais-refinement-list>
```
but i have this in return : 
![image](https://user-images.githubusercontent.com/31215695/29663352-edf7a6dc-88ca-11e7-932d-5baa9dfb5d68.png)

I'm suspecting a "-webkit-appearance" fault? Because when i'm in my console and i untick '-webkit-appearance=none' it worked...but when i deleted it in my  .css it didn't.
If you have any ideas or solutions ? Thank you.

**Comment by iam4x** [comment]
Hello @victoriasr 

What library are you using to integrate Algolia in your application? The code you shared does not look like something we provide with InstantSearch.js

I'll be happy to help :)

**Comment by victoriasr** [comment]
Hi and thanks for responding! I'm using trystack library, i changed some css and it seems to work but it's taking me so much time to change everything.

**Comment by iam4x** [comment]
I'm glad your issue is fixed. But I'm sorry I have never heard of trystack library, can you tell us more of what is it and how it's related with any Algolia InstantSearch library?

**Comment by victoriasr** [comment]
Sorry i misunderstood your question we're currently using Laravel and php.

**Comment by iam4x** [comment]
Alright, I'll recommend you to post your issues in this repo next time https://github.com/algolia/vue-instantsearch which is the library used by the laravel/php integration.

I'll close this issue, have a good day :)
