### ISSUE TITLE
When using TransformData on hits, the items are not redrawn

### ISSUE THREAD

**Issue by kokliKo** [algolia/instantsearch.js#2308]
When using transformData on the hits widget, there's an issue of caching that makes the item not being redrawn.

To reproduce, you can build a regular search where you use transformData to add a timestamp of Date.now and display this value on the hits-template.
Then, when you do another search, all of the results that were present in the previous result set in the same position won't be re-rendered, despite having a different timestamp.

We used to have the same issue on instantsearch v1, and @vvo had fixed it.

**Comment by vvo** [comment]
Some linked pointers:
- Bug: Hit not re-rendered when you modify the data in transformData #1538
- fix(transformData): always call transformData #1555

**Comment by bobylito** [comment]
@kokliKo I tried to reproduce on [jsFiddle](https://jsfiddle.net/bobylito/xefezpa8/). Can you help me? I might have missed one key element.

**Comment by bobylito** [comment]
@kokliKo based on this morning discussion I updated the jsFiddle to do the following: add a transformData for item that injects a Data.now() and use an hogan template to display the value.

**Comment by kokliKo** [comment]
Hey, thanks @bobylito for trying it!
I also tried multiple times to reproduce it and can't get it to work... :/ 
I can't explain what happened last time. 
Sorry for the time spent trying to troubleshoot this one.

**Comment by bobylito** [comment]
@kokliKo no worries ❤️. Don't hesitate to reopen the issue if you find something.
