### ISSUE TITLE
[docs] live example: allow editing

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2311]
**Do you want to request a *feature* or report a *bug*?**

feature

**Feature: What is your use case for such a feature?**

I want to play around with the options in a simple way. Something like simply making the example `contentEditable` will be a great start.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

1. allow code to be ran multiple times

https://github.com/algolia/instantsearch.js/blob/5cd002b0c2442cc952d59cecab335a55e61cbd35/docgen/assets/js/bindRunExamples.js#L71

2. clean up before running again

3. add `contenteditable` to the code block

4. ...

5. profit

**Comment by bobylito** [comment]
What about syntax highlighting with contentEditable?

**Comment by Haroenv** [comment]
as long as you make small edits, it worked for me (we're using `textContent`, so the DOM structure doesn't impact)
