### ISSUE TITLE
Guide on creating a custom calendar widget

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2319]
A calendar widget can be pretty important in certain use case. However there are many out there and adding one would have a direct impact on the library size. Also this requires to format data in a specific way.

As a first step we should provide a guide that explains how to integrate a calendar and format the data correctly so that it can be leverages using numeric filters. Maybe we should talk about the case when we want a range and a single date.

It should be possible to base the implementation on the connectors we currently have.

**Comment by bobylito** [comment]
This is live on the website https://community.algolia.com/instantsearch.js/v2/guides/calendar-widget.html (thanks to @francoischalifour)

**Comment by RodrigoTomeES** [comment]
Hi @bobylito @francoischalifour ,

I entered to the link of the demo but now it isn't avaliable, where can I find it now?

Thanks!

**Comment by Haroenv** [comment]
I don't think the guide still exists, but the example still does: https://github.com/algolia/instantsearch/tree/bdabdab6666568b4f67b8955391f1ec964c2579f/examples/js/calendar-widget

**Comment by RodrigoTomeES** [comment]
@Haroenv Hi, thanks I will check it

**Comment by RodrigoTomeES** [comment]
@Haroenv I checked it but it is an example to filter only by one date. Is there any example to filter by date when the data is an array of start and end dates? Or another structure to fix this problem? Thanks!

```js
const dates = [
  {
    start: "2023-06-10",
    end: "2023-06-20"
  },
  {
    start: "2023-06-25",
    end: "2023-07-10"
  },
  // More dates...
]
```

**Comment by Haroenv** [comment]
There shouldn't be any difference if the date is an array, you can then use `dates.start` as the attribute for example

**Comment by RodrigoTomeES** [comment]
@Haroenv Hi, thanks I tried that way but there is an unexpected problem. When I search by dates.start and dates.end Algolia doesn't search it as a pair so the result are wrong. For example:

![Captura de pantalla 2023-06-14 a las 17 23 44](https://github.com/algolia/instantsearch/assets/13077343/4cbb7bb7-d110-4037-aa09-fa6feeb4a301)

In this example the result is wrong because the pair of start and end they are not together.

**Comment by Haroenv** [comment]
the dates need to be timestamps to be able to use the guide :)

**Comment by Haroenv** [comment]
Here you're filtering on that specific item, not on ranges, have you seen the example?

**Comment by RodrigoTomeES** [comment]
@Haroenv Yes I saw it, but I am testing the query in the algolia dashboard and I didn't know how to make a range from the algolia dashboard

**Comment by RodrigoTomeES** [comment]
@Haroenv Hi think the dashboard has an issue with "AND" and "OR" queries, look:
![Captura de pantalla 2023-06-15 a las 16 47 09](https://github.com/algolia/instantsearch/assets/13077343/b25de5e1-7f5c-4902-9000-7f32d97d25f1)

But in this way it works
![Captura de pantalla 2023-06-15 a las 16 49 12](https://github.com/algolia/instantsearch/assets/13077343/f957e32b-6974-464c-a464-2b9b60725f02)
