### ISSUE TITLE
test lib/version.js

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#232]
not a joke :D

**Comment by bobylito** [comment]
Interesting... Why? :)

**Comment by vvo** [comment]
should contain the version from package.json, and expose it. It can also be tested from the instantsearch-test.js because it will be added to it.

But in the end since we test all files (unit) then there's no reason to not test this one?

**Comment by bobylito** [comment]
that's a test that can be useful to validate a package, no?
