### ISSUE TITLE
How can I display data on page form this?

### ISSUE THREAD

**Issue by sadamameer** [algolia/instantsearch.js#2321]
Hi, I am using this code. How can I display results on laravel blade.
search.addWidget(
        instantsearch.widgets.hits({
          container: '#hits',
          templates: {
            empty: 'No results',
            item: '{{hit.name}}'
          },
          hitsPerPage: 6,
          cssClasses: {
            root: 'row',
            item: 'col-lg-3 col-md-4 col-sm-6'
          }
        })
      );

I am getting error : Use of undefined constant hit - assumed 'hit'

please help.

**Comment by bobylito** [comment]
Your backend framework wants to evaluate what's inside the js part of the code because it uses the same `{{ }}` for variables. One way to get around that is to use a function instead of a string template. Here is an example based on yours:

```js
search.addWidget(
    instantsearch.widgets.hits({
	container: '#hits',
	templates: {
	    empty: 'No results',
	    item: function(hit){ return hit.name; }
	},
	hitsPerPage: 6,
	cssClasses: {
	    root: 'row',
	    item: 'col-lg-3 col-md-4 col-sm-6'
	}
    })
);
```

**Comment by Haroenv** [comment]
With Laravel Blade you can also use `@{{` instead of `{{` as an escape character
