### ISSUE TITLE
Query rules guide

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2328]
Query rules is a new feature in the Algolia engine. Even though most of the impact is in the engine and most of the answer modifications should be hidden, we have identified two cases where we need to provide some help on how to integrate them:
 - when a result is promoted
 - how to access custom data from the rules engine

The idea is to make a guide for that.

This is linked to https://github.com/algolia/algoliasearch-helper-js/issues/529 #

**Comment by francoischalifour** [comment]
We wrote a guide on the new [Algolia website](https://www.algolia.com/doc/guides/managing-results/refine-results/merchandising-and-promoting/how-to/add-banners/?language=instantsearchjs#retrieving-the-banner-data-in-the-search-ui).

A connector and two widgets for Query Rules are on their way! (#3597)
