### ISSUE TITLE
Slider V2 does not recover from no results, breaks Instantsearch

### ISSUE THREAD

**Issue by mindbits** [algolia/instantsearch.js#2331]
I do not understand why the slider was replaced for V2. I could spend so many hours writing about the issues we run into with this alpha version of a slider that is unusable on a touch device if I would have the time. 

Here is today's annoyance: 

The slider does not recover if there are no results found in a search

Perfectly working example with V1: https://jsfiddle.net/rata5eeo/

Slider V1 works like a charm , type Sandra into the search box => No Results => Slider goes to min value and beautifully recovers if you type in eg Sarah or at least press backspace

Braindead V2 slider: https://jsfiddle.net/3xkz0vq1/

Type Sandra into the search box => Instantsearch breaks, no way to recover from no results. The page has to be reloaded.

No need to fix this bug, there are so many more, the slider is unusable. Please just replace it.

**Comment by bobylito** [comment]
Thanks @mindbits for opening this issue. We'll work on it asap.
