### ISSUE TITLE
Hierarchical Menu style for the e-commerce v2 demos

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#2334]
Level of the hierarchical menu of the e-commerce v2 [demo](https://community.algolia.com/instantsearch.js/v2/examples/e-commerce/) are not marked.

See: 

![image](https://user-images.githubusercontent.com/6885378/30427658-e142e08c-9950-11e7-9bc5-625460777796.png)

**Comment by bobylito** [comment]
Seems fixed. Thanks a lot @mthuret 👍
