### ISSUE TITLE
Update the api key, after the initialization.

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2339]
We've had a user [asking how it was possible to change the API key after the initialization](https://discourse.algolia.com/t/is-there-a-way-to-switch-between-two-keys/2788) of instantsearch.js. Right now, it's not possible and I'm creating this issue in order to follow up on that issue.

**Comment by Haroenv** [comment]
If we're creating an API to change the keys after initialisation, we should also think about allowing to change other parameters in a similar way, WDYT?

**Comment by bobylito** [comment]
True. However there is a difference because the API key can't even be changed at the helper level. And what about the js client level?

**Comment by Haroenv** [comment]
I think that in v4 you should be able to pass it as a requestOption, but I'd have to test if it's actually possible.

**Comment by bobylito** [comment]
Now that we have a `searchClient` that can be passed to the paremeters, we could have a setSearchClient to update the client? (since that's the client that holds the credentials on Algolia, maybe that could be a good solution?). cc @algolia/instantsearch-for-websites

**Comment by Haroenv** [comment]
Seems possible, but not sure if that's the best API we can find

**Comment by francoischalifour** [comment]
A `setSearchClient()` method could also allow to change the endpoint depending on external events, it'd be quite powerful.

**Comment by Haroenv** [comment]
I agree about that, but it just seems odd to only allow updating of a search client, and none of the other parameters of `instantsearch()`, I'd rather have a fluid API for all of those use cases

**Comment by bobylito** [comment]
> I agree about that, but it just seems odd to only allow updating of a search client, and none of the other parameters of instantsearch(), I'd rather have a fluid API for all of those use cases

It's a work in progress :) We've added the means to update the widgets. @Haroenv 

Can you tell us more about a fluid API? Do you have something in mind already? :)

**Comment by Haroenv** [comment]
Right now you can do that by setting `instantSearchInstance.searchClient = newSearchClient`, this is not documented and supported, but will work.

We can rediscuss at a later point a good API to update parameters of all widgets, including the root, this doesn't seem like the correct issue to do that
