### ISSUE TITLE
Print hit object order

### ISSUE THREAD

**Issue by czmarcos** [algolia/instantsearch.js#2347]
I want to print the key order of the results shown inside my template, is there any way to do that? Is there any key index value to represent the order of the results (eg: "hitOrder")?

For example:

```
var hitTemplate =
  '<div class="hit" id="{{hitOrder}}">' +
   '<h1>#{{hitOrder}}: {{ title }}</h1>'+
  '</div>';
```

#1. Result 1...
#2. Result 2...
#3. Result 3...
....

**Comment by bobylito** [comment]
I'm not sure to get what you mean by `hitOrder`. Is it something from your records? Or should it be a computed value?

**Comment by Haroenv** [comment]
Do you want the index?

```
[ search box ] 
1. best result
2. second result 
...
9. last result
[1...9]
```

**Comment by czmarcos** [comment]
@Haroenv, yes! I'd like to display the index of results.

**Comment by bobylito** [comment]
The data is not available in the `item` template but you could use the `allItems` template instead which let you control all the output. And if you really need the full control, you can always use a function instead of a template.

**Comment by czmarcos** [comment]
-- SOLVED --
Just noticed that there is a hit index inside the object as __hitIndex 

Thus, the solution would be:

```
var hitTemplate =
  '<div class="hit" id="{{__hitIndex}}">' +
   '<h1>#{{__hitIndex}}: {{ title }}</h1>'+
  '</div>';
```

**Comment by bobylito** [comment]
I've never heard of that... that's weird :)
=

**Comment by czmarcos** [comment]
Yep, but solved my issue! :)

![image](https://user-images.githubusercontent.com/13335834/30655546-96781872-9e07-11e7-87f4-d1f8f2c10760.png)

**Comment by bobylito** [comment]
Ok so it's there since 1.6.0, and it was first introduced as __position (and it's there [in the code](https://github.com/algolia/instantsearch.js/blob/5cd002b0c2442cc952d59cecab335a55e61cbd35/src/components/Hits.js#L13)). Happy that you solved your issue :)

I'll open an issue to document that.
