### ISSUE TITLE
Expand hierarchicalMenu root item

### ISSUE THREAD

**Issue by kaleemullah** [algolia/instantsearch.js#2349]
By default, hierarchicalMenu items are collapsed and user has to click any item to see sub-items as you can see in below screenshot that _Category_ **Electric & Electronic** item collapsed.

<img width="278" alt="screen shot 2017-09-20 at 1 43 54 pm" src="https://user-images.githubusercontent.com/56748/30638051-396eca46-9e0b-11e7-862d-f052352fd793.png">

But as it is the only one root item(which has sub-items) so I want to expand it as soon as page loads so that user don't need to click on the item to see sub-items as below screenshot.

<img width="275" alt="screen shot 2017-09-20 at 1 41 59 pm" src="https://user-images.githubusercontent.com/56748/30638070-4690b0f4-9e0b-11e7-8dfe-8a91f61c65a8.png">

Here is the page: https://protenders.com/companies/bodet/products

Is it possible?

**Comment by bobylito** [comment]
You can use the `rootPath` option to have the root expanded. The only drawback is that it hides the name of this category. Would that fit your needs?

**Comment by kaleemullah** [comment]
Well, I need to show the category name and also how can i know that there is just one root item via instantSearch?

**Comment by bobylito** [comment]
Well in this case this is not possible. We only expand what is selected, and what is selected influence the search results.

**Comment by Haroenv** [comment]
I think you might be able to do this with one of following options: 

1. [this is a hack] in `searchFunction`, check how many facets there are, if it's only one, dispatch a click event on the root
2. with a connector, and displaying it as a single or collapsed interface
