### ISSUE TITLE
RangeSlider ignores min / max boundaries

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#2386]
If you set boundaries on a `RangeSlider` widget, there are ignored. In the given example the boundaries are set to `2` and `4`. The UI is align with the options but in the response we still have the movies with a rating greater than `4`.

The boundaries are also ignored when we change the current values of the slider, then reset to the initial state. For example set the slider minimum to `3`, reset it, make a research for `Bad Moon` and you will have some movies with rating lower than `2`.

https://jsfiddle.net/tksyn43f/

**Comment by bobylito** [comment]
Nice catch!

**Comment by iam4x** [comment]
Great catch @samouss you should probably look this method https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/range-slider/connectRangeSlider.js#L124-L166 👍
