### ISSUE TITLE
HitsPerPageSelector root css class being applied twice

### ISSUE THREAD

**Issue by Corys8646** [algolia/instantsearch.js#2397]
Apologies if this is intended behavior, but the docs make me believe this is possibly a bug. 
Using V2 of Instantsearch and adding a HitsPerPage selector, also adding a css class to the root cssClasses Object.

Problem is, the class is being added to the `<select>` item as well as the parent div.

Trying to add a bootstrap form-control to the select element.

I've got a fiddle here: <https://jsfiddle.net/Corys8646/8mhxqayf/1/>

**Comment by bobylito** [comment]
Hi @Corys8646 thanks for opening this issue. Are you reporting this issue for v2? Also I can't find your link to the jsFiddle you made :)

**Comment by bobylito** [comment]
This should have been fixed in the 2.2 release :)
