### ISSUE TITLE
[docs] Make the search results wider

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#2403]
Could be worth making the result div wider, so labels on the left don't get split into two lines.

![image](https://user-images.githubusercontent.com/1101220/30908547-e076f6fc-a34b-11e7-85ce-e86175cb6b45.png)

**Comment by bobylito** [comment]
To give more context, some label are split. With a wider left column we'd be able to display the whole label.

**Comment by francoischalifour** [comment]
Closed because the documentation has been migrated to the [Algolia documentation website](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/).
