### ISSUE TITLE
ClearAll widget remove configuration preset

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#2412]
On IS if you combine a `ClearAll` component with a widget who takes a preset configuration, the later will be remove by the widget. 

For example `RangeSlider` accept a `min` & `max` options to restrict the search on specific range. If we combine this widget with `ClearAll` the user will able to erase the preset range.

**Example:**

* the slider is set with a min value of `10` & max value of `500`
* update the min value of the slider (ex: `90`)
* click on clearAll
* trigger a search from the `SearchBox` (ex: `mg`)

The bounds has been erased.

https://jsfiddle.net/tksyn43f/2

**Comment by bobylito** [comment]
What if we could call the getConfigurations of all the widgets to get their initial configurations and then reset to default values instead of completely clearing the values? (like the removeWidget proposal will do?)

**Comment by samouss** [comment]
Sounds good to me! But we need to expose a way of compute the initial configuration on the IS instance, to be able to rebuild it from the connector.

**Comment by Haroenv** [comment]
I'm not really seeing the wrong behaviour here, so I guess it must have been fixed at some point?

- v2: https://codesandbox.io/s/fancy-tdd-xhokr?file=/src/app.js
- v4: https://codesandbox.io/s/frosty-goldberg-z5we4?file=/src/app.js
