### ISSUE TITLE
Add editorconfig configuration

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2429]
This ease collaboration and enforces things like:
- indentation style
- strip white space
- always add an empty line

Example:

```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

WDYT?

**Comment by Shipow** [comment]
tab!

**Comment by bobylito** [comment]
Can you explain explain the added value to prettier + eslint?

**Comment by Haroenv** [comment]
final newline I guess

**Comment by bobylito** [comment]
https://eslint.org/docs/rules/eol-last
https://eslint.org/docs/rules/no-trailing-spaces

Would that be good enough?

**Comment by vvo** [comment]
> Can you explain explain the added value to prettier + eslint?

Indeed good question. I thought about it and: It works on all files not just JavaScript files (so all md documentations even if eslint can also lint them, all README/contributing, package.json..)

WDYT?

**Comment by bobylito** [comment]
Well what about adding the eslint rules + editorconfig?

**Comment by vvo** [comment]
> Well what about adding the eslint rules + editorconfig?

I dunno about the rules, it can be "boring" to see errors icons for lines that you are currently writing or files that are not yet saved. While editorconfig just clean it for you when saving.

**Comment by bobylito** [comment]
Yes but not everybody uses editorconfig :) and it's style that must enforced :)

**Comment by vvo** [comment]
Checked to be clearer (and discussed with @bobylito), our [eslint rules](https://github.com/algolia/eslint-config-algolia) already enforces:
- spaces
- two spaces
- add a single empty line to files
- trim whitespace

And those will error and are checked but only for JavaScript files.

Thus this issue is mostly about having the same behavior for all other file types (md, html, txt), given that most editors have defaults, editorconfig solve that (install it on atom, it's by default on vs code, vim: you are a hacker, deal with it!)

**Comment by vvo** [comment]
Also: GitHub supports it and respects it in diffs (whatever that means) and their inline editor
