### ISSUE TITLE
*feature* option to show all refinementList options even when count is 0 if less than limit

### ISSUE THREAD

**Issue by erikbelusic** [algolia/instantsearch.js#2430]
**Feature: What is your use case for such a feature?**
We have a location preference facet with options NY, SF, Remote. We want all three of these to always be visible as choices (like a menu) but allow the user to select multiple like the refinementList

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
add showEmptyValues: [boolean] on refinementList OR multiselect: [boolean] on menu

A quick test made this seem impossible using the widgets as is, or using a connector.

attempted to use a connector, but RefinementListRenderingOptions.items doesnt contain refinements with a count of 0

A custom widget may be an option, but was looking for a simpler solution

**Comment by Haroenv** [comment]
Hey @erikbelusic, this isn't possible with Algolia, as mentioned before in https://github.com/algolia/algoliasearch-client-javascript/issues/541

Sorry to close this issue, but it's depending on something which would impact performance by magnitudes and needs to be done on the side of our engine. 

I did forward your request to our product team though

**Comment by Haroenv** [comment]
For now your workaround would be to have a static list of options
