### ISSUE TITLE
Generate github release during the release

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2442]
We could leverage https://developer.github.com/v3/repos/releases/#create-a-release to populate the releases automatically :)

**Comment by Haroenv** [comment]
Would be nice! I'd keep both a CHANGELOG.md and the releases though

**Comment by bobylito** [comment]
It would be just on top indeed :)

**Comment by Haroenv** [comment]
Would be automatically fixed when using shipjs, so will close this, since nobody upvoted it
