### ISSUE TITLE
Style / rangeslider: Problems with the alignements

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2449]
![screen shot 2017-10-04 at 12 24 47](https://user-images.githubusercontent.com/393765/31171411-e287db6e-a8ff-11e7-85c4-a4e18f3dca17.png)

I think the handles should not go beyond the verticals defined by the headers. Same goes for the labels.

**Comment by bobylito** [comment]
This is trickier than expected. Maybe we should rethink with good default when we move on with instantsearch.css? cc @ronanlevesque

**Comment by ronanlevesque** [comment]
Sorry for the late reply. Yes, this is tricky, not sure this can be done without JS.

**Comment by bobylito** [comment]
@ronanlevesque no worries. I think that either js or not, I think we want to know what it should look like visually and then we'll fix everything that need to be fixed. WDYT?

**Comment by Haroenv** [comment]
I wonder if some padding to the inner part could not fix it?

**Comment by ronanlevesque** [comment]
@bobylito agreed.

@Haroenv not really, because we want the tooltip/value to be horizontally centered to its handle/marker except when you get close to the edge. But if we add internal padding, it will have an impact on other slider elements as well.

**Comment by francoischalifour** [comment]
Closing since the styles now depend on [InstantSearch.css](https://yarnpkg.com/en/package/instantsearch.css).
