### ISSUE TITLE
documentation(hierarchicalWidget): give UX guidance on the number of levels

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#245]
When documenting the hierarchical widget, we should advise people to not go too far in terms of hierarchical levels. Because this will lead to UX fails, so two level deep should be sufficient for most instant search experiences.

TODO:
- [ ] on the website documentation, advise not to go too far

**Comment by pixelastic** [comment]
Agreed. Maybe add a few screenshots with one or two levels, so user can understand quickly what this will change?
