### ISSUE TITLE
Menu is too big

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2452]
<img width="1182" alt="screen shot 2017-10-05 at 14 08 27" src="https://user-images.githubusercontent.com/6270048/31226524-ade8503c-a9d6-11e7-947e-d6f4c46f0066.png">

**Comment by Haroenv** [comment]
Actually it's still too big, but now on mobile 😄 / screens smaller than 15"

**Comment by bobylito** [comment]
Maybe we could have more breakpoints than mobile / desktop? cc @JonasBa

**Comment by vvo** [comment]
> Actually it's still too big, but now on mobile 😄 / screens smaller than 15"

We could just hide it on mobile otherwise, usecase of getting the v1 docs should be rare..

**Comment by iam4x** [comment]
flex layout @JonasBa so it can takes the space remaining?

**Comment by Haroenv** [comment]
This seems to be closed in https://github.com/algolia/instantsearch.js/pull/2466
