### ISSUE TITLE
Wrong Parameters

### ISSUE THREAD

**Issue by timothyjblevins** [algolia/instantsearch.js#2453]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: -- 
The template parameters are incorrect. It says 'name' but uses 'label, value'
![https-community algolia com-instantsearch js-v2-widgets-menuselect html-struct-menuselecttransforms](https://user-images.githubusercontent.com/11906213/31228458-95dbeeb6-a9ab-11e7-8273-28b4131ec047.jpeg)

**Comment by Haroenv** [comment]
Thanks a lot! Feel free to click edit on that page and propose a pull request
