### ISSUE TITLE
[refinementList] label is undefined

### ISSUE THREAD

**Issue by cmalard** [algolia/instantsearch.js#2454]
Hello there,
The value `label` provided in refinementList - templates.item config disappear after a search.

This is the object provided at init:
```json
{
	"count": 8,
	"isRefined": false,
	"label": "Prine",
	"value": "Prine",
	"highlighted": "Prine",
	"url": "#",
	"cssClasses": {
		"root": "ais-refinement-list",
		"header": "ais-refinement-list--header",
		"body": "ais-refinement-list--body",
		"footer": "ais-refinement-list--footer",
		"list": "ais-refinement-list--list",
		"item": "ais-refinement-list--item",
		"active": "ais-refinement-list--item__active",
		"label": "ais-refinement-list--label",
		"checkbox": "ais-refinement-list--checkbox",
		"count": "ais-refinement-list--count"
	}
}
```

After a search, as sent by the API `http://hzp025yf0p-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.24.4%3Binstantsearch.js%202.1.6%3BJS%20Helper%202.21.2&x-algolia-application-id=...&x-algolia-api-key=...`:
```json
{
	"value": "Prine",
	"highlighted": "<em>P</em>rine",
	"count": 8,
	"isRefined": false,
	"url": "#",
	"cssClasses": {
		"root": "ais-refinement-list",
		"header": "ais-refinement-list--header",
		"body": "ais-refinement-list--body",
		"footer": "ais-refinement-list--footer",
		"list": "ais-refinement-list--list",
		"item": "ais-refinement-list--item",
		"active": "ais-refinement-list--item__active",
		"label": "ais-refinement-list--label",
		"checkbox": "ais-refinement-list--checkbox",
		"count": "ais-refinement-list--count"
	}
}
```

**Comment by bobylito** [comment]
Hello @cmalard Thanks for the issue. I have a hard localizing where this happens. Could you give me more info about the code you're using? Maybe a [jsFiddle](https://jsfiddle.net/bobylito/9h7sgo10/) test case?

**Comment by bobylito** [comment]
I'm closing this one for now. Feel free to reopen it if you have more infos. Thanks for contributing @cmalard 👍

**Comment by cmalard** [comment]
Hi there @bobylito,
I'm not using this value anymore, I switched to highlighted, hence my silence :-)

Here is a fiddle, was totaly lazy to do one, good point you gave me some bootstrap ;-)
https://jsfiddle.net/Lb6kuxpf/
(I'm not able to reopen by the way)

**Comment by bobylito** [comment]
Thanks @cmalard. I happen to be working on another related issue. I'll come up with something :) (thanks @Haroenv for reopening the issue)

**Comment by bobylito** [comment]
Fixed
