### ISSUE TITLE
Should we keep checkboxes as default styling?

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#246]
This is what the current default styling of the `refinementList` looks like:
![image](https://cloud.githubusercontent.com/assets/283419/10490683/a1fb2c26-72a2-11e5-922d-55c47d7e1bbb.png)
And here is the current default template:
```html
<label>
  <input type="checkbox" value="{{name}}" {{#isRefined}}checked{{/isRefined}} />{{name}} 
  <span>{{count}}</span>
</label>
```

I feel like using checkboxes for that is just one choice among many. What we really need is a way to tell which item is selected and which is not. Depending on the implementation, we could simply use bold text, or change the color, or add custom ✔ next to it, change its background, etc.

For me this is something for the end-user to decide. I would then remove the `checkbox` from the default template and use a simple `<a>Label</a><span>count</span>` instead, with a specific class added when the item is selected.

That way, the user will be able to style it as needed (and we could also provide themes to help). It is possible to replicate a checkbox using CSS only (we actually do that on the current instantsearch demo). If users really needs a real `checkbox` in its markup, they can define a custom template.

cc @Shipow @redox @andoche @kokliKo @vvo @proudlygeek @seafoox

**Comment by bobylito** [comment]
Imho checkbox is the way to go in vanilla html for multiple choices :)

**Comment by redox** [comment]
> Imho checkbox is the way to go in vanilla html for multiple choices :)

Agree, I think we really need to keep things simple and use vanilla checkboxes, it's too complex to use UTF-8 chars & CSS for that.

As soon as we have a question like that, we should just do like Amazon :)

**Comment by Shipow** [comment]
Oh noes please do not skin the checkbox :)

**Comment by pixelastic** [comment]
> it's too complex to use UTF-8 chars & CSS for that.

It is waaaaaaay easier to simulate a checkbox in CSS than trying to style an actual checkbox.

> As soon as we have a question like that, we should just do like Amazon :)

![image](https://cloud.githubusercontent.com/assets/283419/10492702/c2ca17cc-72ad-11e5-9aa6-90c0b5704a42.png)
![image](https://cloud.githubusercontent.com/assets/283419/10492721/d7077130-72ad-11e5-85da-c96af374c0a7.png)

No checkbox in markup

> Oh noes please do not skin the checkbox :)

You know we already use custom checkboxes in our current live instantsearch demo, right? ![image](https://cloud.githubusercontent.com/assets/283419/10492648/7f711f3e-72ad-11e5-8f29-7f7db8a50e8d.png)

**Comment by Shipow** [comment]
ok check box or style faking checkbox, but not skinned checkbox.

**Comment by redox** [comment]
> No checkbox in markup

Ah very nice :) :+1:

**Comment by vvo** [comment]
What would be the obvious choice to display a checkbox in a webpage? Use an `<input type="checkbox" />`. All other solutions are hacks we should not try them __first__.

Right now we are good with checkboxes and I fail at seeing one single reason to switch to any other solution. Checkboxes are native html elements and native is always the obvious first choice you would expect. If at some point we see it as a failure then we can move on to something else.

But again, I do not see one single advantage in switching to any other solution.

To be faire the current instant search demo is using unicode checkboxes since you did the change @pixelastic: https://github.com/algolia/instant-search-demo/commit/79f7d70303e40046a9d61d8ea907dbfd3ae6ff85.

We did this change because we were not able to make performant checbkboxes because of a weird jQuery plugin that we were using.

Amazon has use cases and needs that we cannot even think of, maybe they are using this technique and there's a ticket like "use real checkboxes" since 2 years in their tracker but they cannot change it because of weird reasons and historic decisions.

Using two separate images for a single checkbox is weird, counter-intuitive as an API user and worst: bad for performance.

We are good with checkboxes, for now.

**Comment by redox** [comment]
Hard to disagree, :100: @vvo

**Comment by Shipow** [comment]
@vvo Sometimes you need to unify ui across device and native checkboxs simply do not allow it, it's probably not a good practice but it's widely used and needed.

**Comment by vvo** [comment]
> Sometimes you need to unify ui across device and native checkboxs simply do not allow it, it's probably not a good practice but it's widely used and needed.

Yes I can understand that but I feel this is too soon for us to take this road, we are not even live

**Comment by pixelastic** [comment]
My main point is not even if we should use a checkbox in the HTML or in the CSS.

My main concern is about promoting the use of checkboxes as the right way to display a list of multiple elements. I feel that this is __one__ way of expressing it. That is not the best way. I don't feel there is a  best way. It really depends on the context and the website.

Here are two examples of other `refinementList` that do not use checkboxes.

![image](https://cloud.githubusercontent.com/assets/283419/10496639/0cd240ba-72c2-11e5-893f-4ea0b6268589.png)![image](https://cloud.githubusercontent.com/assets/283419/10496711/5528b542-72c2-11e5-8480-e5f579797d42.png)

Are we really 100% positive we want to promote the use of checkboxes as the default way of using multiple selections in our UI? I don't feel confortable with that. I would rather go with something more generic for the default, and allow styling on top of that (or using a custom template with a checkbox if you really need one).

My secondary concern is about the theming of the list using checkbox (being as a default or as a theme). The v1 of instantsearch would include a couple of themes (correct me if I'm wrong), and we need to have good looking UI themes. I don't think keeping the default ugly checkboxes in our themes will cut it. In the end we'll resort to CSS tricks for hiding the checkbox and using images for the states. So why putting the checkbox in the markup if we'll hide and replicate the behavior later?

The default instantsearch display, without theme should not be pushed to production directly. It is just here for debugging. One should either use one the pre-defined themes we offer, or code its own. Simply using a `font-weight:bold` to denote the current active items in that context seems enough to me.

**Comment by vvo** [comment]
Themes could be js files that:
- redefine default templates for all/certain widgets
- load the necessary css file for theming

Those could be builded and published on jsdelivr by us. You would them just have to load them before instantsearch.

So that you can do all you want and we do not need to settle on a not so obvious default refinementList template that will not use checkboxes, to implement css theming.

The default build will also load a default theme that is good for a start and that is also good for production if the user care about configuring/enhancing some of the css classes/default bem classes. Or provide his own classes. WDYT?

**Comment by redox** [comment]
> The default build will also load a default theme that is good for a start and that is also good for production if the user care about configuring/enhancing some of the css classes/default bem classes. Or provide his own classes. WDYT?

I'm convinced we need to split the JS code and the themes/CSS files. By default, if you don't include any theme CSS file it will look ugly and that's totally fine I think.

**Comment by vvo** [comment]
> I'm convinced we need to split the JS code and the themes/CSS files.

We definitely can but is that a need so that you can be able to view-source and see the css file?

Being able to override default templates AND load a css with a single file is handy also. Otherwise you will have to load:

```html
<link rel default theme css file>
<link rel theme css file>
<script theme templates>
<script instantsearch>
```

Versus:

```html
<script theme.js>
<script instantsearch.js>
```

**Comment by redox** [comment]
Yes, I'm OK with 2 (or 3 if you want to load a default theme + hack after) loads. Keep in mind we need to target the big majority of developers; it's really the simple way to deal with it.

**Comment by pixelastic** [comment]
I think @redox was talking about having the bare instantsearch.js having really bare styling (almost none) and all the theming in different files. But that new file could be a js that includes css like you suggested

**Comment by vvo** [comment]
Ok so unique CSS files as `<link>` for themes (and default theme also).

But being able to override default JS templates can be a builded file on jsdelivr right?

**Comment by pixelastic** [comment]
Maybe we should open a new issue for discussing the scope of themes...

**Comment by vvo** [comment]
> Maybe we should open a new issue for discussing the scope of themes...

Yes we need to draft what we want for theming

**Comment by vvo** [comment]
I think we are good here. We drafted #247 and #277

**Comment by privacyrepo** [comment]
> My main point is not even if we should use a checkbox in the HTML or in the CSS.
> 
> My main concern is about promoting the use of checkboxes as the right way to display a list of multiple elements. I feel that this is **one** way of expressing it. That is not the best way. I don't feel there is a best way. It really depends on the context and the website.
> 
> Here are two examples of other `refinementList` that do not use checkboxes.
> 
> ![image](https://cloud.githubusercontent.com/assets/283419/10496639/0cd240ba-72c2-11e5-893f-4ea0b6268589.png)![image](https://cloud.githubusercontent.com/assets/283419/10496711/5528b542-72c2-11e5-8480-e5f579797d42.png)
> 
> Are we really 100% positive we want to promote the use of checkboxes as the default way of using multiple selections in our UI? I don't feel confortable with that. I would rather go with something more generic for the default, and allow styling on top of that (or using a custom template with a checkbox if you really need one).
> 
> My secondary concern is about the theming of the list using checkbox (being as a default or as a theme). The v1 of instantsearch would include a couple of themes (correct me if I'm wrong), and we need to have good looking UI themes. I don't think keeping the default ugly checkboxes in our themes will cut it. In the end we'll resort to CSS tricks for hiding the checkbox and using images for the states. So why putting the checkbox in the markup if we'll hide and replicate the behavior later?
> 
> The default instantsearch display, without theme should not be pushed to production directly. It is just here for debugging. One should either use one the pre-defined themes we offer, or code its own. Simply using a `font-weight:bold` to denote the current active items in that context seems enough to me.

I have been looking for this style for several days, I cant find a way to get rid of the checkbox, how can I get it? is there a demo code for this? Thank you.

**Comment by Haroenv** [comment]
@privacyrepo you can use either templates.item in InstantSearch.js that don't render an input, or use the connector
