### ISSUE TITLE
Simplify the renderer for built-in widgets

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#2473]
When we create a widget we use a `renderer` with a signature like this:

```js
(subsetWidgetParameters) => (widgetParameters) => Element
```

We probably can simplify it to:

```js
(widgetParameters) => Element
```

All informations pass to `subsetWidgetParameters` are available in `widgetParameters` on the property `widgetParams`. You can take a look [at this PR](https://github.com/algolia/instantsearch.js/pull/2472) as an example, maybe I miss something! Inside the documentation we provide [some example](https://community.algolia.com/instantsearch.js/v2/connectors.html#reusability-of-connectors) that follow this pattern.

**Comment by Haroenv** [comment]
There's now some widgets with different parameters that have the same name as the connector parameter (like dynamic widgets), I don't really see how it can be done anymore unfortunately
