### ISSUE TITLE
SFFV in refinement list: when there is no result, the show more doesn't work afterwards

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2478]
A user on our [community forum](https://discourse.algolia.com/t/show-more-option-not-working-after-facet-value-search-in-instansearch-js/3204) found a bug when using "search for facet values" with "show more".

He did a video in which he shows [how to reproduce the bug](https://www.youtube.com/watch?v=q5gXj-hT2ws&feature=player_embedded).

Steps to reproduce the issue:
 - have a [refinement list with search for facet values and show more activated](https://jsfiddle.net/xe6drzyh/1/)
 - search until no results
 - remove the search
 - show more is not usable anymore

**Comment by cmalard** [comment]
Hello there, another case: `Show less` is displayed when it shouldn't

Steps to reproduce :
- https://jsfiddle.net/8bhvmfa6/2/
- paste in the global search : `abide` -> no `show less` :+1:
- clear global search
- click on the first `show more`
- paste in the global search : `abide` -> `show less` :-1:
![](https://user-images.githubusercontent.com/18403647/32664564-e8eb35f6-c631-11e7-8b3c-c4434f47d97e.gif)

With version 2.2.3

**Comment by Haroenv** [comment]
I think this was solved @francoischalifour, but I'm not sure anymore in which PR. @francoischalifour can you confirm?

**Comment by francoischalifour** [comment]
The issue has been addressed in #3082 but needs more tests to be validated.
