### ISSUE TITLE
Communication between widget?

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#248]
Hello I have a problem with our current widget API. I want to be able to generate a url in the RefinementList but anything related to URL's are in the dedicated widget. And because we have some configuration in the urlSync that will make the configuration look different, we need the RefinementList widget to be able to get infos about url generation.

Several options I have had in mind so far : 
 - pass the UrlSync widget manually / by the user, directly to the other widget factory (explicit and straightforward but let the user do stuff)
 - let the urlSync widget export a function with a name/key, and let the others access it using the key/name... Could look a bit like runtime dependency injection. (smell the magic yet ? ;) )

Do you have something else in mind? Better/nicer/less magic/less like a fat framework :P

**Comment by pixelastic** [comment]
Maybe the fact that the urlSync is currently thought as a widget was the wrong move initially. It is a very special widget, with no render, that must be called last (and we already add some code to ensure that).

Maybe we should move the whole url-generation part as a core part of instantsearch, so every widget can access it and be able to generate urls. In that case the `urlSync` widget would only do the synchronisation of the current helper state with the browser url, but all url-handling will be deported inside instantsearch directly.

**Comment by redox** [comment]
> Maybe the fact that the urlSync is currently thought as a widget was the wrong move initially. It is a very special widget, with no render, that must be called last (and we already add some code to ensure that).

Yes, happy to remove it from the widgets.

**Comment by bobylito** [comment]
OK cool, moving stuff in the instantsearch core makes things easier :+1:

**Comment by vvo** [comment]
> Maybe the fact that the urlSync is currently thought as a widget was the wrong move initially. 

Now that I think of yes this would be easier to have everything url inside the instantsearch.js. Basically it's about instantiating the urlSync widget if urlSync: {} is passed as instantsearch params.

This will allow us to remove the __init lifecycle trick that was only done for the urlSync widget (allow configuring/init order to be modified)

:+1:

**Comment by redox** [comment]
> This will allow us to remove the __init lifecycle trick that was only done for the urlSync widget (allow configuring/init order to be modified)

:100:

**Comment by pixelastic** [comment]
Go @bobylito, go :)
