### ISSUE TITLE
XSS protection on hits breaks searchForFacetValues

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2495]
When using both `escapeHits` on the hits widget and `searchForFacetValues` on a refinementList, the highlighted results of the SFFV will use the pre and post highlight tags of the hits.

![2017-10-17 15 08 14](https://user-images.githubusercontent.com/393765/31666615-22690f4e-b34d-11e7-99ef-4d2dde8d2b9e.gif)

Proposed solution:
 - make sure that the connectRefinementList implementations receives properly cleaned results
 - deprecate escapeHits at the widget level and move it to an instantsearch option

@iam4x what do you think?

**Comment by bobylito** [comment]
Or we could offer to have a separate option and have the parameter for the highlight tagging independantly configured 🤔 That could actually work nicely and let us not add yet another option to the main instantsearch factory.

**Comment by Haroenv** [comment]
Duplicate of #2474
