### ISSUE TITLE
Problem with sortBySelector cssClasses

### ISSUE THREAD

**Issue by renanbronchart** [algolia/instantsearch.js#2497]
Hi,
I have a problem on instant search v2, select classes in instantsearch.widgets.sortBySelector doesn't work.
I try
`    search.addWidget(
      instantsearch.widgets.sortBySelector({
        container: '#results-sort',
        indices: options.indices,
        cssClasses: {
           select: 'form-control'
        }
      })
    );
`

And form-control class is not display.
Please I need help 😩

**Comment by bobylito** [comment]
Thanks @renanbronchart for the issue. I am trying to reproduce the issue 👍

**Comment by bobylito** [comment]
Which version of InstantSearch.js are you using? I've tried with our latest version [and it seems to works](https://jsfiddle.net/bobylito/hgnnbhc6/).

**Comment by renanbronchart** [comment]
Thanks for response, I use gem algoliasearch-rails for ruby on rails application.
And I use cdn https://cdn.jsdelivr.net/npm/instantsearch.js@2.1.1/dist/instantsearch.min.js for instant search.

Can you show me on example to use select classes in sortBySelector

**Comment by renanbronchart** [comment]
I saw your example, actually this work at you, but not on my side :/

**Comment by bobylito** [comment]
Do you have a link where I can see the behaviour? Maybe a jsFiddle with your code? That would be very helpful, thanks a lot.

**Comment by bobylito** [comment]
My bad, actually this has been fixed in [2.2.0](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#220-2017-10-03) with https://github.com/algolia/instantsearch.js/pull/2423 

If you upgrade it should be fixed.

**Comment by renanbronchart** [comment]
Thanks a lot !! It work with [2.2.0](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#220-2017-10-03) !!
