### ISSUE TITLE
[searchBox] allow to instantiate on an <input>

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#25]
Following what [@redox said](https://github.com/algolia/instantsearch.js/commit/0881b02b69dcda820cfbd402a9711e500a74723e#commitcomment-12480725):

Current SearchBox instantiation API cannot work in this use case (common one):

```html
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
      <input type="text" class="form-control" placeholder="Search for..."> <!-- I cannot have a wrapping div here -->
    </div>
```

Because we always have a wrapping DIV in our current SearchBox instantiation. We render the `<input>` where we were asked for.

## TODO:
- [ ] reimplement the searchBox widget using vanilla JavaScript to allow enhancing an `input`
- [ ] automatically detect if the container is an <input> and bind to it, otherwise generate the DOM like right now

PS: We might be able at some point with REACT do also enhance an existing DOM node but that's not currently feasible unfortunately.

**Comment by bobylito** [comment]
React is not the good tool if we are to just manipulate an input. jQuery or VanillaJS? 

Truth is, do we even need rendering for a search input? Is the search box a widget, or an enhanced dom element? Do we want enhanced elements, wouldn't it create inconsistencies between the search box and the rest?

Imho, that's a very edge case and should be low priority.

**Comment by vvo** [comment]
As @bobylito maybe the best way to tackle this particular widget (it's an empty element we want to enhance) then using vanilla JS would be the best way and would allow all sort of usecases to be handled.

Let's do that soon?

**Comment by vvo** [comment]
Note concerning the solution where we replaceNode the provided container:
- for some people having already references to the <input>: they will be surprised
- it's not yet possible with react to render a component inside a dom fragment (and we will need one to replace the node)

So vanilla JS is the only obvious solution

**Comment by redox** [comment]
> Truth is, do we even need rendering for a search input? Is the search box a widget, or an enhanced dom element? Do we want enhanced elements, wouldn't it create inconsistencies between the search box and the rest?

I'm happy with it being something else than a widget, that's actually make a lot of sense to me. :+1: @bobylito

**Comment by bobylito** [comment]
Well I think we had a discussion about that with @vvo and it seems that using yet another semantic here  is tedious. Making it a vanilla JS based widget will work. But then we won't create any markup for this one (which makes it different from other widget)

**Comment by redox** [comment]
I don't thing not adding markup is an issue as soon as the search box is not a widget anymore, it makes a lot of sense to me to just be one of the argument of the `instantsearch` constructor.

**Comment by bobylito** [comment]
@redox, what is a widget anyway? We are creating our own vocabulary here, inspired by others and yet slightly different. And I think there is a space for widgets that are not rendered but attach itself to the dom. I created a ticket for that #44

**Comment by vvo** [comment]
I am against having a distinction on hosting our widgets in the .widgets namespace or in the instantsearch configuration.

searchBox is a widget, it's just that's it's an empty element, that's completely fine? I feel we are moving it in the instantsearch constructor because on the implementation side, it seems more obvious.

But on a usage side, I will look for the searchBox widget in .widgets, not in the instantSearch configuration.

What do you think?

**Comment by maxiloc** [comment]
One thing to consider is that for integration having both autocomplete and instant search make the input for the instant search generated after the page load. The one already in the page is for autocomplete.

**Comment by vvo** [comment]
> One thing to consider is that for integration having both autocomplete and instant search make the input for the instant search generated after the page load. The one already in the page is for autocomplete.

I am not sure to understand the issue your are talking about

**Comment by bobylito** [comment]
It's for magento integration. It would require to have the instant search input to be completely generated.

**Comment by vvo** [comment]
> It's for magento integration. It would require to have the instant search input to be completely generated.

I am sorry I am still not seeing the issue or question (maybe there is no question).

**Comment by bobylito** [comment]
Can we provide an option or another widget so the input is actually generated? (there is no input for instant search in the magento integration) :)

**Comment by vvo** [comment]
@maxiloc Can't you just create an `<input>` dynamically and then deal pass it to the instant search? Seems the best solution.

**Comment by pixelastic** [comment]
I would keep the searchBox in the .widget namespace.

Regarding the wrapping div/input discussion, what I would do is add a new input if the dom element given is not already an input, and directly enhance it with our listening events if it is. For this widget the only markup we need (an `input`) is one that is likely already in the page, let's use it.

**Comment by vvo** [comment]
I think we can just force people to provide us an input and if it's not an input, throw. I do not see the benefit right now of handling both cases?

**Comment by pixelastic** [comment]
Because all our others widgets already acts on a random div, this would seem weird to ask the user to add specific markup for this on if we can simply generate it
