### ISSUE TITLE
connectRefinementList::canToggleShowMore is always true when no limit is set

### ISSUE THREAD

**Issue by iam4x** [algolia/instantsearch.js#2504]
The condition for `canToggleShowMore` is the following `canToggleShowMore: isShowingMore || !hasExhaustiveItems`

And `hasExhaustiveItems` is computed this way:

```js
const hasExhaustiveItems = items.length < this.getLimit();
```

If `this.getLimit() === undefined` then `hasExhaustiveItems` will be false and at the end `canToggleShowMore` would be true even if no limit has been set and there is not others available items.

This is not happening with the bundled RefinementList widget because we set by default `limit` to 10 (https://github.com/algolia/instantsearch.js/blob/develop/src/widgets/refinement-list/refinement-list.js#L231)

Should we ensure we have a default limit in the connector and update the documentation or fix the way `hasExhaustiveItems` is computed?

**Comment by Haroenv** [comment]
Seems good to me to set the default value also to 10 in the connector
