### ISSUE TITLE
Negative values unsupported in range slider

### ISSUE THREAD

**Issue by 67ideas** [algolia/instantsearch.js#2511]
**Do you want to request a *feature* or report a *bug*?**
Bug. Example: https://jsfiddle.net/8zzvL5y1/

**Bug: What is the current behavior?**

Attributes with negative values do not show those negative values in the range slider. Additionally, explicitly setting a negative minimum doesn't seem to fix anything.

**Bug: What is the expected behavior?**

I'd expect any positive or negative numbers to be supported.

**Bug: What browsers are impacted? Which versions?**

Chrome (Mac) 61.0.3163.100

**Bug: What is the proposed solution?**

- support negative values in facets
- set range selection minimum appropriately

**What is the version you are using? Always use the latest one before opening a bug issue.**
https://cdn.jsdelivr.net/npm/instantsearch.js@1/dist/instantsearch.min.css

**Comment by bobylito** [comment]
That's for the maintenance version. AFAIK, this is a limitation of the previous implementation of the slider, and we changed it in v2. I'm not sure we're gonna be able to make something for this v1. Can you update?

**Comment by Haroenv** [comment]
We will not add new features to maintenance releases, as said :)
