### ISSUE TITLE
Add allItems template option to InifiniteHits

### ISSUE THREAD

**Issue by chadokruse** [algolia/instantsearch.js#2519]
The infiniteHits widget is almost at feature parity with the hits widget, with the exception of the [allItems template option](https://community.algolia.com/instantsearch.js/v2/widgets/infiniteHits.html#struct-InfiniteHitsTemplates).

This means using tabular data with infiniteHits requires either using a connector (more verbose) or, if using a front-end framework e.g. Bootstrap or Materialize) a bunch of extra markup to convert tables to an instantsearch-friendly structure.

My use case:
I'd like to use hits widget + pagination on desktop, but infinite scroll on mobile

Other use cases:
Enterprise'y customers using Tableau ([example](http://www.centralvalleycf.org/nonprofits/grants-overview/grants/))

**Comment by bobylito** [comment]
Have you considered using the [connector](https://community.algolia.com/instantsearch.js/v2/connectors/connectInfiniteHits.html)? By using a connector you have a complete control over the rendering.

**Comment by francoischalifour** [comment]
The `allItems` template was removed in v3 in favor of [`connectHits`](https://www.algolia.com/doc/api-reference/widgets/hits/js/#connector) ([see migration guide](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/?#options-4)). The same behavior can be achieved with [`connectInfiniteHits`](https://www.algolia.com/doc/api-reference/widgets/infinite-hits/js/#connector).
