### ISSUE TITLE
Allow PureTemplate to have a configurable element type

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#2525]
I'm working on a sortable data table widget and want to leverage the `PureTemplate` component: https://github.com/algolia/instantsearch.js/blob/develop/src/components/Template.js

Since this is rendering an actual html `<table>`, there are instances when I need render an element other than a `div` (eg `tr`, `td`).

Would be great if that were configurable.

@bobylito Any ideas welcome!

**Comment by Haroenv** [comment]
You could have a prop `RootTag = “div”` and when rendering switch div to RootTag

**Comment by bobylito** [comment]
Hi @timkelty thanks for challenging the APIs we propose.

The connectors were created in order to provide this kind of flexibility. As I see things right now, providing a new API that is so specifically dedicated to templates will reinforce their usage. I think the balance of power of the template API, the simplicity of it and the impact on the code of the project is right. I will however sync back with the whole InstantSearch team to get their feelings too.

**Comment by timkelty** [comment]
@bobylito sounds good, I'll stay tuned!

**Comment by bobylito** [comment]
Hi @timkelty if we were to implement this feature, how would it make your code better? Can you show us the 2 versions with and without a new option such as rootTag?

**Comment by timkelty** [comment]
@bobylito here's an example of how I would use `rootTag`:

```
const Template = 'instantsearch.js/es/components/Template.js';

class HitsTable extends React.Component {
  renderWithResults() {
    const renderedHits = map(this.props.hits, (hit, position) => {
      const data = {
        ...hit,
        __hitIndex: position,
      };
      return (
        <Template
          data={data}
          key={data.objectID}
          rootProps={{ className: this.props.cssClasses.item }}
          rootTag="tr"
          templateKey="item"
          {...this.props.templateProps}
        />
      );
    });

    return <table className={this.props.cssClasses.root}>{renderedHits}</table>;
  }
}
```

There really isn't an alternative - aside from duplicating the `Template` component with my own that allows this, or using a widget that renders a table as divs.

**Comment by francoischalifour** [comment]
FYI there's now a `rootTagName` prop on the `Template` component that allows to render in another element than a `div` (see #2757).

Keep in mind that this `Template` component was originally made for internal usage. We wouldn't recommend relying on it.
