### ISSUE TITLE
Add Search For Facet Values requirements

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#2539]
When using `searchForFacetValues`,  specific requirements for this options are not present, we should add them. 

See: 

![image](https://user-images.githubusercontent.com/6885378/32224831-4d99fa60-be43-11e7-94cd-5dffdabf0196.png)

![image](https://user-images.githubusercontent.com/6885378/32224853-5f8c31b6-be43-11e7-9772-f745ba687763.png)

**Comment by bobylito** [comment]
Thanks that's a good improvement of the doc :)
