### ISSUE TITLE
Split stories in different files

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#2540]
What do you think to split `stories` across multiple files? 
IMO it's easier to navigate instead of accumulate hundred of line inside the same file.

ex: `Menu.stories.js`, `RefinementList.stories.js`, ...

**Comment by Haroenv** [comment]
Would also be nice if the custom widgets would be visible on the site instead of only via a query param

**Comment by samouss** [comment]
@Haroenv Let's create an other issue for that! 👍
