### ISSUE TITLE
sortBySelector CSS classes not applying to select element

### ISSUE THREAD

**Issue by lukepearce** [algolia/instantsearch.js#2550]
When I add cssClasses to the sortBySelector widget, the classes on the select element don't apply. If I add classes to the root element, they apply to both the root and the select.

```js
cssClasses: {
    root: 'white ttu tracked f6 fw5 bg-colour-button pa2 pv105 br1',
    item: 'white'
},
```

**Comment by bobylito** [comment]
Hi there, thanks for opening this issue :)

Which version of InstantSearch.js are you using?

**Comment by lukepearce** [comment]
Hey, I'm using 2.1.4 from the cloudflare cdnjs

https://cdnjs.cloudflare.com/ajax/libs/instantsearch.js/2.1.4/instantsearch.min.js

**Comment by bobylito** [comment]
Hi @lukepearce can you try with 2.2.*?

**Comment by lukepearce** [comment]
That's got it working 👍
