### ISSUE TITLE
Using `undefined` as value doesn't remove the selection in NumericSelector

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2559]
https://jsfiddle.net/bobylito/jvm9ts9d/

related conversation on the community forum: https://discourse.algolia.com/t/no-default-selection-for-dropdown-numericselector-on-page-load/3611

**Comment by whitenazgul** [comment]
@bobylito - Just following up on this bug, we are suppose to go live soon and was wondering if you have an update for me. Thanks.

**Comment by bobylito** [comment]
This has been released as part of the 2.2.4 release. I updated the [documentation](https://community.algolia.com/instantsearch.js/v2/widgets/numericSelector.html#struct-NumericOption) accordingly.
