### ISSUE TITLE
Share this search widget

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#256]
Now that we have all the elements to create URLs for a given state of the search, we can implement a new widget that could let user easily share the URL with their friends or followers. I don't know if we want go full social, but at least a widget that could easily copy the current search that would be nice right?

**Comment by vvo** [comment]
That would be awesome :)

**Comment by redox** [comment]
Low-priority but good idea!

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it
