### ISSUE TITLE
I could not find what I was looking for a item is not an clickable 

### ISSUE THREAD

**Issue by roshandhabekar** [algolia/instantsearch.js#2563]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is:
On an item listing I am not able to click or select the item

**Comment by Haroenv** [comment]
Could you explain what you mean? If you want a way to go to a detail page from a result, you can simply add a link to that result in the item template. Does that make sense?

**Comment by bobylito** [comment]
Otherwise you can show us

**Comment by bobylito** [comment]
@roshandhabekar can you give us more details on what you're trying to achieve?

**Comment by bobylito** [comment]
@roshandhabekar I'm closing this issue for now. Please open a new one if you have more details :)
