### ISSUE TITLE
Adding multiple values to facets

### ISSUE THREAD

**Issue by MrMooky** [algolia/instantsearch.js#2568]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is how to implement a function to template > item in a refinementList as seen here: https://www.algolia.com/product

The actors have images attached to the names, I'm trying to archive this, but apparently the only options here are label, highlighted, value, count, isRefined, url (as documented).

This is my current refinementList. Within templates > item, all 3 (label, highlighted, value) output the same thing.

```
search.addWidget(
		instantsearch.widgets.refinementList({
			container: '#darsteller',
			attributeName: 'darsteller.name',
			sortBy: ["isRefined","name:asc"],
			operator: 'and',
			limit: 12,
			showMore: {
				templates: {
					active: '<div class="showless">weniger anzeigen</div>',
					inactive: '<div class="showmore">mehr anzeigen</div>'
				}
			},
			templates: {
				header: 'Darsteller',
				item: '{{label}}, {{highlighted}}, {{value}}'
			}
		})
	);
```

How do I accomplish something like shown in the demo (link provided on top)?

**Comment by bobylito** [comment]
Hi there,

Happy to see that our product page demo inspired you. In here, there is a bit of a magic trick, the facet data contains both the name and the URL of the image:

<img width="1018" alt="screen shot 2017-11-09 at 17 34 20" src="https://user-images.githubusercontent.com/393765/32617103-652540da-c574-11e7-9928-fa90bc69a6d7.png">

To be able to achieve this you can use `transformData` ([doc here](https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html#struct-RefinementListTransforms)) and in that function split the `value` in two: the url and the name.

It will look like:

```js
search.addWidget(
		instantsearch.widgets.refinementList({
			container: '#darsteller',
			attributeName: 'darsteller.name',
			sortBy: ["isRefined","name:asc"],
			operator: 'and',
			limit: 12,
			showMore: {
				templates: {
					active: '<div class="showless">weniger anzeigen</div>',
					inactive: '<div class="showmore">mehr anzeigen</div>'
				}
			},
			templates: {
				header: 'Darsteller',
				item: '{{label}}, {{highlighted}}, {{value}}'
			},
			templates: {
				item: function(item) {
				    var nameAndImage = item.value.split('|');
				    item.name = nameAndImage[0];
				    item.imageURL = nameAndImage[1];
				    return item;
				}
			}
		})
	);
```

Does that answer your question?

**Comment by MrMooky** [comment]
@bobylito That answers my question fully, yes. Thank you very much. :) Would have never thought about putting the values into one and splitting them. Neat workaround.
