### ISSUE TITLE
Website: long delays before instantsearch works

### ISSUE THREAD

**Issue by orlando21** [algolia/instantsearch.js#2582]
I'm implementing instantsearch.js in vanilla JavaScript in a way very similar to the e-commerce (2nd) example in https://community.algolia.com/instantsearch.js/v1/examples/

When it works, it works brilliantly. But often when I click in the search bar nothing happens. I must reload the page a few times and wait. Usually then somehow instantsearch begins to work.

I thought maybe it was a promise issue so I implemented that (see code below). This seems to have no effect however.
```
            window.onload = function() {
                let loadSearchPromise = search.start();
                document.getElementById('search__input').onclick = function() {
                    loadSearchPromise.then(() => {
                      document.getElementById('show-result').style.display = 'block';
                    })
                }
            }
```
It's frustrating when clicking in the search bar and reloading the first few times doesn't work, so I have some general questions:
- What could be causing this delay, and if so what can be done about it?
- Does a promise implementation for instantsearch.js make sense?

There are no slow network issues on my end.

**Comment by Haroenv** [comment]
Hey, could you try replicating that in a jsFiddle, that’s not normal behaviour. @vvo, you experimented in similar behaviour improvemets, no?

**Comment by orlando21** [comment]
Ok, I've isolated the problem. My web app uses both Algolia instantsearch and Firebase. Both of these are loaded by two different .js files and I've tried to keep the functionality of both apart. However both files have separate `onload()` functions: the Algolia file uses the code above (`windows.onload`) and the Firebase file uses `document.ready`).

1. Are there any known issues to using both instantsearch and Firebase in the same app?
2. Might it be more feasible to combine the functions of these two files into one file, for example to combine the instantiation of both instantsearch and Firebase inside one `window.onload`?

**Comment by orlando21** [comment]
After some careful debugging, the answer is yes, instantsearch and Firebase can coexist in the same app. `search.start()` was activated within `window.onload` which seemed to load after Firebase. When I instead put `search.start()` inside of `$(document).ready` then instantsearch works alongside Firebase.

**Comment by Haroenv** [comment]
The issue here was probably more to do with the fact of mixing document.ready and window.only since they'll be called at the same time almost, but not exactly, which might cause some undefined behaviour. If you have a project somewhere with this situation, it would be nice to see if we can work around the problem without changing your code
