### ISSUE TITLE
connectStateResults freezes with dynamic hitComponent

### ISSUE THREAD

**Issue by korroktheslavemaster** [algolia/instantsearch.js#2586]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Application freezes; most likely hit component is rendered in a loop

**What is the version you are using? Always use the latest one before opening a bug issue.**
4.1.3

Here is the example I'm testing on https://codesandbox.io/s/kxlq9608v3
I am using `connectStateResults` to wrap my `Hits` to conditionally render them based on search query.
I want to pass props to `hitComponent`, as mentioned here #2018 . Following the solution in that issue, I created a dynamic hitComponent, ie instead of 
```es6
const Content = connectStateResults(
  ({ searchState }) =>
    <Hits hitComponent={HitComponent}/>
);
```  
I tried
```es6
const Content = connectStateResults(
  ({ searchState }) =>
    <Hits hitComponent={({hit}) => (<HitComponent hit={hit}/>)}/>
);
```
This freezes the application. If I remove the `connectStateResults` wrapper, it works as expected. Also, this seems to be a problem with `connectStateResults` only; wrapping in `connectHits` works. Any help is appreciated!

**Comment by Haroenv** [comment]
Hey @korroktheslavemaster, I moved this issue to the correct repository: https://github.com/algolia/react-instantsearch/issues/629
