### ISSUE TITLE
[headerFooter]: CSS classes

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#259]
How do you imagine the CSS classes added to the various `root`, `header`, `body`, `footer` element created through the `headerFooter` decorator?

I imagine something like that:

```html
<div class="ais-widget-name {{cssClasses.root}}">
  <div class="ais-widget-name--header {{cssClasses.header}}"></div>
  <div class="ais-widget-name--body {{cssClasses.body}}"></div>
  <div class="ais-widget-name--footer {{cssClasses.footer}}"></div>
</div>
```

With `cssClasses` being the attribute passed to the widget so user can add custom classes. 

Do you think we should also add more generic `ais-header`, `ais-footer` classes everytime the decorator is called. This could help us always style headers the same way easily, but this also means we will have to add `ais-root` and `ais-body` classes that do not make a lot of sense.

I'm in favor of not adding the `ais-header` and `ais-footer` in a first version. Agreed?

**Comment by vvo** [comment]
> Do you think we should also add more generic ais-header, ais-footer classes everytime the decorator is called.

Yes we need so I believe.

Most of the time all the headers of widgets have the same rendering.

Even in our themes, not having it would mean that we would need to specify all the classes?

**Comment by pixelastic** [comment]
Without those classes, this would mean styling `ais-widget1--header, ais-widget2--header {}`. That might become painful really quick, you're right. I'll add them.

I'm unsure we need to add `ais-root` and `ais-body`, though. Because those elements will only be added if the widget uses the `headerFooter` decorator. Not all widget will have them.

**Comment by vvo** [comment]
> I'm unsure we need to add ais-root and ais-body, though. Because those elements will only be added if the widget uses the headerFooter decorator. Not all widget will have them.

Yes we can skip this one for now, if there's a need we will see
