### ISSUE TITLE
styling item with multiple values in a field

### ISSUE THREAD

**Issue by dfcn84** [algolia/instantsearch.js#2594]
Say I have index item with this structure:
   {
      "name": "alvinsee",
      "ra_list": [
         "Comparative Law",
         "Contract Law",
         "Equity & Trusts",
         "Unjust Enrichment & Restitution",
         "Tort Law",
         "Property Law",
         "Animal Law"
      ]
   }

I realise the output of {{ra_list}} is a comma separated output. How can I style this into <li> or <div>

**Comment by Haroenv** [comment]
Hey @dfcn84, glad that you solved this. Could you explain what the problem was and how you solved it, for future reference? 

Thanks!
