### ISSUE TITLE
instantsearch with Angular - How to Geo search ?

### ISSUE THREAD

**Issue by odecharette** [algolia/instantsearch.js#2596]
Hi! 
I'm using InstantSearch Service with Algolia V4 and it's working !

Now I'd like to filter results via IP.

**Details :**

My index has an attribute called "perimetre"
By default, I'd like to GEO filter all results depending on user IP

I found this : https://www.algolia.com/doc/tutorials/geo-search/filter-results-around-a-location/#filtering-around-the-current-user-location

How can I use this with Angular ?
Can I configure this directly in my Algolia Dashboard or should I implemente it in my code ? How ?

**This is my hits.component.ts :**

```typescript
export class HitsComponent implements OnInit {
  // Define how your component state will look like,
  // and intialize it with an empty hits array
  state: { hits: {}[] } = { hits: [] };

  nbResultToShow = 8;

  constructor(private instantSearchService: InstantSearchService) { }

  ngOnInit() {
    // Create a widget which will call `this.updateState` whenever
    // something changes on the search state itself
    const widget = connectHits(this.updateState);

    // Register the Hits widget into the instantSearchService search instance.
    this.instantSearchService.search.addWidget(widget());
  }

  updateState = (state, isFirstRendering) => {
    // asynchronous update of the state
    // avoid `ExpressionChangedAfterItHasBeenCheckedError`
    if (isFirstRendering) {
      return Promise.resolve().then(() => {
        this.state = state;
      });
    }

    this.state = state;
  }
}
```

Thanks !

**Comment by bobylito** [comment]
Hi @odecharette Thanks for opening this issue. 

First your records need to have a `_geoloc` attribute with their positions so that the engine understands where those records are geolocated. Then you need to configure the requests to use the IP for geolocating the user. This time you have to set it using the constructor of InstantSearch:

```js
var search = instantsearch({
  /* all credentials etc. */
  searchParameters: {
    aroundLatLngViaIP: true,
  }
});
```

You should use that in the Service definition. Let me know how it works for you.

As a side note, we also have a [brand new integration for Angular](https://algolia.gitbooks.io/angular-instantsearch) in beta. Have a look, we hope it'll help even more than the InstantSearch.js + Angular guide

**Comment by bobylito** [comment]
@odecharette let me know if I can close this issue.

**Comment by odecharette** [comment]
Hy @bobylito 

Many thanks for your answer
aroundLatLngViaIP is working !

How if I want to set the aroundRadius depending on data attribute ?
I managed to set it in the service : 

```
@Injectable()
export class InstantSearchService {
  search = instantsearch({
    appId: environment.algoliaAppId,
    apiKey: environment.algoliaApiKey,
    indexName: environment.algoliaIndexName,
    urlSync: environment.algoliaUrlSync,
    searchParameters: {
	    aroundLatLngViaIP: true,
	    aroundRadius: 40000 // 40km
	}
  });

  constructor() {}
}
```

But then, it's the same radius for all
However, I have an attribute called "perimetre" for each hit. How can use it ?

I'll have a look on your Angular beta link, looks awesome :)

**Comment by bobylito** [comment]
The aroundRadius is based on where the center of the center is, so I'm not quite sure how the "perimetre" of each result fits in this case. Maybe you could contact the support directly because it sounds like a broader question related to search and not InstantSearch.js specifically?

**Comment by odecharette** [comment]
OK no problem !
Thanks

**Comment by bryyyanribo** [comment]
@odecharette, how did you integrate geosearch with angular?

**Comment by samouss** [comment]
Hello @bryyyanribo, we have a dedicated guide about [geo search + Angular InstantSearch](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/geo-search/angular/) inside the documentation. Note that this guide apply to the version 3 of Angular InstantSearch that is currently in beta.

**Comment by bryyyanribo** [comment]
@samouss, I was having an issue as to how to pass the data from my current location on this one: 
https://www.algolia.com/doc/api-reference/api-parameters/aroundLatLng/

**Comment by samouss** [comment]
You can use the [`ais-configure`](https://www.algolia.com/doc/api-reference/widgets/configure/angular/) widget to provide the location to `aroundLatLng`.
