### ISSUE TITLE
No data/html in results for facets when the pages loads.

### ISSUE THREAD

**Issue by mdunbavan** [algolia/instantsearch.js#2598]
**Fiddle below**
https://jsfiddle.net/7z13xr2a/4/

**Bug: What is the current behavior?**
Current behaviour is that the site loads the correct number of hits but there is nothing in each result see below:

![screen shot 2017-11-24 at 16 48 49](https://user-images.githubusercontent.com/671281/33219019-0611c27e-d138-11e7-80b9-db9bb091ccb1.png)

![screen shot 2017-11-24 at 16 48 58](https://user-images.githubusercontent.com/671281/33219024-126f97b2-d138-11e7-9910-fef3044fdfcd.png)

![screen shot 2017-11-24 at 16 49 11](https://user-images.githubusercontent.com/671281/33219038-1b74349e-d138-11e7-851d-3781fa89bd1d.png)

**Bug: What is the expected behavior?**

What should be happening is that it loads all html into each result which it isn't doing!

**Bug: What browsers are impacted? Which versions?**

I am using Chrome latest and its happening on me not tested other browsers.

**Bug: What is the proposed solution?**

I think it should show the html in each result and not be blank.

**What is the version you are using? Always use the latest one before opening a bug issue.**

This is the version: https://cdn.jsdelivr.net/npm/instantsearch.js@2.2.5/dist/instantsearch.min.js

Here are some screenshots of the data being captured and the response and header data for you to look at:

![screen shot 2017-11-24 at 16 49 43](https://user-images.githubusercontent.com/671281/33219102-7b225da8-d138-11e7-8cd5-23d44d214d7b.png)
![screen shot 2017-11-24 at 16 50 49](https://user-images.githubusercontent.com/671281/33219103-7b36a9fc-d138-11e7-8e92-4dec1b0a386c.png)
![screen shot 2017-11-24 at 16 51 03](https://user-images.githubusercontent.com/671281/33219104-7b4a0164-d138-11e7-8022-4ccff8ba094c.png)
![screen shot 2017-11-24 at 16 51 31](https://user-images.githubusercontent.com/671281/33219105-7b600630-d138-11e7-81bf-27b1eb785452.png)

Thanks,
Mark

**Comment by bobylito** [comment]
Hi @mdunbavan. Thanks for opening this issues.

One thing that I notice that makes your display empty is that there are no attributes in your records, just highlighted values. There must be something wrong in your index configuration (have you set some unretrievable attributes?).

On the IS.js part, it actually adds your template markup to the document for each of your result (and in your jsFiddle there is only one result).

Let me know if I misunderstood something here.

**Comment by bobylito** [comment]
@mdunbavan have you been able to do anything here?

**Comment by bobylito** [comment]
No update since the last question. Closing this for now.
