### ISSUE TITLE
No results when searching for Angular in the docs

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2605]
![image](https://user-images.githubusercontent.com/123822/33289757-e366ca9a-d3c0-11e7-9ee0-6d7f480f46f6.png)

While there's a guide for it. Maybe there's some indexing issue?

**Comment by bobylito** [comment]
I've just checked and actually there are some results but they have no title :/

**Comment by bobylito** [comment]
Fixed (docsearch config)
