### ISSUE TITLE
Only include official release in CHANGELOG

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2609]
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**Bug: What is the current behavior?**

Every release is taken into account by conventional-changelog, but we don't update the changelog for betas. When releasing the final version, we only get the changelog for the latest changes since the last beta.

**Bug: What is the expected behavior?**

Only use non-beta for the changelog.

**Bug: What is the proposed solution?**

I'm not sure. It should be investigated.

**Comment by Haroenv** [comment]
What if we simply update the change log for betas on the master branch?

**Comment by bobylito** [comment]
> What if we simply update the change log for betas on the master branch?

Conventional-changelog expects the CHANGELOG to be generated at each release. So we'd need to update on the branch we do betas. Another solution is to regenerate the changelog completly every time we do a release on master.

**Comment by bobylito** [comment]
For now, we don't generate beta changelog anymore.
