### ISSUE TITLE
[docs] It would be nice to explain what syntax is used in templates for hits widget

### ISSUE THREAD

**Issue by rayrutjes** [algolia/instantsearch.js#2620]
https://community.algolia.com/instantsearch.js/v2/widgets/hits.html#example

Maybe a link or mention to Handlebar somewhere could help users figuring out where the syntax in the example comes from. Is it Handlebar?

**Comment by bobylito** [comment]
Actually it's another implementation of mustache called [hogan](http://twitter.github.io/hogan.js/)

**Comment by bobylito** [comment]
But you're totally right, we should mention that somewhere. (or even every time there is a template)

**Comment by bobylito** [comment]
It's only mentionned on the [concepts page](https://community.algolia.com/instantsearch.js/v2/widgets-common-api.html#templates).

**Comment by rayrutjes** [comment]
Thanks a lot, I was helping a user and at some point I realized I wasn't sure what the syntax or the language was ;)

**Comment by Haroenv** [comment]
should be easy to link it by every template :)

**Comment by francoischalifour** [comment]
We made it clearer on the [new Algolia website](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/js/?language=instantsearchjs#templating-your-ui). Feel free to reopen if you think we can make it better!
