### ISSUE TITLE
Provide i18n?

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#263]
What if a user want to implement a search for different countries? Based on the idea from https://github.com/algolia/algoliasearch-helper-js/issues/59

**Comment by vvo** [comment]
Can you precise the use case and the requirements we miss to fulfil it?

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it

**Comment by joel1di1** [comment]
Hi, 
I'm currently having some questions around this.
The simplest one: 
In the media exemple (https://community.algolia.com/instantsearch.js/examples/media/search.js), what is the best way to have the noResultsTemplate message internationalised?

**Comment by pixelastic** [comment]
Hey BLA :)

How do you handle the i18n on your side? Is that:

- Only defined through the browser locale and not changeable?
- A dropdown in the UI that changes the displayed language of the UI (but still use the same results from Algolia)
- A dropdown in the UI that change the index/filters of the results to target those of a specific language?

Depending on the use case there are several ways to do that, but most of them will involve defining a function as the template. If you define a function, it will be called on each render and you can then dynamically chose which error message to display.

**Comment by joel1di1** [comment]
Hey TIM :)

With handle I18N by "king of a dropdown", anyway you got the locale in the URL.
The results are always the same in algolia (ie: keys), then the client part in JS will handle the translation.

Thanks for your response, I didn't see that the template accept functions.
But in the case we provide a function, do we lose the format options like {{query}} ?

**Comment by pixelastic** [comment]
Yes, if you define your own function it completly bypass the Mustache/Hogan template compilation and you have to build the resulting string yourself.

That being said, if you are using ES6, you easily replicate the same behavior with the backtick and `${}` syntax of string interpolation.

**Comment by vvo** [comment]
Yes! ES6 template literals are a very simple and powerful way to do templating: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Available in all major browsers (which means > IE11)

**Comment by bobylito** [comment]
You can't put them in a function or even in a variable, as they are immediately interpreted...

**Comment by pixelastic** [comment]
Not sure I follow. You can use them in a template function like this:

```javascript
{
  templates: {
    item: (data) => {
      return `My name is ${data.name}`;
    }
}
```

**Comment by bobylito** [comment]
True! You can use them in a function.

But they can't be used as values. They are very much hardcoded inside the function that use them. You can't do:

```js
var myTemplate = `bar ${foo}`;
// already translated as a string using the context

var myRenderedTemplate = fn(`baz ${bar}`);
// Translated to string before the function call
```
