### ISSUE TITLE
Pressing enter in a searchbox reloads the page

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2630]
Steps to reproduce:
 - go to 
 - type something in the searchbar
 - press enter

Page is reloaded. The expected behavior is that the page should not be reloaded.

**Comment by bobylito** [comment]
Can't repro actually https://jsfiddle.net/bobylito/2dd9kw0t/

**Comment by Haroenv** [comment]
This could happen if it's in a form and the js isn't loaded yet, but that is not the case here I think

**Comment by bobylito** [comment]
That's what happened that's why I couldn't reproduce with a simple is.js v2 example.
