### ISSUE TITLE
Links to repo of the v1 examples are broken

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#2631]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When going to https://community.algolia.com/instantsearch.js/v1/examples/, the links to the repo of each example are erroring with a 404:
- https://github.com/algolia/instantsearch.js/tree/master/docs/examples/media
- https://github.com/algolia/instantsearch.js/tree/master/docs/examples/e-commerce
- https://github.com/algolia/instantsearch.js/tree/master/docs/examples/tourism

**Bug: What is the expected behavior?**
They should link to the GitHub directory holding the code (could not find it, sorry)

**Comment by Haroenv** [comment]
Links should be `/maintenance`

e.g. https://github.com/algolia/instantsearch.js/tree/maintenance/docs/examples/media

**Comment by vvo** [comment]
Took me 1 min to fix those, next time do not hesitate to fix them right away

**Comment by pixelastic** [comment]
I could not find where the examples were located, sorry :(

**Comment by bobylito** [comment]
Fixed, thanks @vvo  👍
