### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by debdeepsircar** [algolia/instantsearch.js#2634]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: -- PLEASE FILL IN HERE --

How to insert hierarchicalMenus into my Algolia index as well as facet settins?

An example is there , named 'ikea'.

Can I get ikea index data structure?

Thanks ,

DEBDEEP SIRCAR

**Comment by debdeepsircar** [comment]
plz anyone help me out

**Comment by Haroenv** [comment]
What have you tried? The explanation on the hierarchicalMenu page explains which data you should push

**Comment by bobylito** [comment]
Handled via gitter.
