### ISSUE TITLE
Sort order not working

### ISSUE THREAD

**Issue by sandycanonly** [algolia/instantsearch.js#2639]
Override default sort order for facet values at query time is not working
```
$results = $index->search('query', [
  'sortFacetValuesBy' => "alpha"
]);
```

**Comment by bobylito** [comment]
Isn't that PHP @sandycanonly ? At least, it does not look like JavaScript. Are you sure you added the issue to the right project?

**Comment by sandycanonly** [comment]
Yes that't PHP code from algolia documentation

https://www.algolia.com/doc/api-reference/api-parameters/sortFacetValuesBy/
for sortFacetValuesBy functionility

However the issue I faced with sorting the attribute value by alpha is done by modifying autocomplete.js
