### ISSUE TITLE
[theme] appearance doesn't get prefixed

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2644]
see http://shouldiprefix.com/#appearance, `-webkit-appearance: none` is necessary on selects and inputs to make them look normal. This doesn't seem to be applied by our autoprefixer

now| with `-webkit-appearance: none`
---|---
<img width="210" alt="screen shot 2017-12-29 at 16 26 12" src="https://user-images.githubusercontent.com/6270048/34440363-099c1500-ecb5-11e7-955c-6ef85558392d.png"> | <img width="187" alt="screen shot 2017-12-29 at 16 26 07" src="https://user-images.githubusercontent.com/6270048/34440379-15fb8768-ecb5-11e7-8adc-f4fe12beb372.png">

IIRC this was fixed by writing the prefix manually in input[type=search]

**Comment by bobylito** [comment]
Nice catch @Haroenv

**Comment by Haroenv** [comment]
The different theme, instantsearch.css, does not have this issue
