### ISSUE TITLE
Resolving to a separate instantsearch results page

### ISSUE THREAD

**Issue by nicosrugeris** [algolia/instantsearch.js#2647]
I have a results (/results) page that works perfectly with my indexing and is great!

I have a search bar on my home page (/) that i would like to resolve whatever is input and parse it through to the results page, filtering the results page accordingly.

Whats the best way to do this? Any help would be appreciated.
Thanks in advance.

**Comment by Haroenv** [comment]
There's two ways of doing this. First is to have the whole Instantsearch in a div on both the home page and on the results page. It can be `[hidden]` until someone first `focus`es the input. 

A second option is to make the input on the home page a `<form>` which has as action `/results` `type=get`. that can then be used on your `results` page to fill in the search bar. 

Does that help you?

**Comment by bobylito** [comment]
@nicosrugeris Does the answer from @Haroenv solve your problem?

**Comment by nicosrugeris** [comment]
Thank you very much @Haroenv for the solutions. The second option we went for worked perfectly. Thanks again.
