### ISSUE TITLE
I could not find what I was looking for filter with array value 

### ISSUE THREAD

**Issue by Marthinsp** [algolia/instantsearch.js#2653]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: -- PLEASE FILL IN HERE --

I have problem with use instantSearch function using date, but the attribute contain array of integer. So i want to filter the date with array value. 

This is my attribute that contains array of integer:

![image](https://user-images.githubusercontent.com/10026508/34753858-514c2202-f5f5-11e7-8dac-ba91ff92bf83.png)
NB: this array contains the value by date, index 0 means 1st january,  index 1 means 2nd january etc.

i have parameter of search is by date, so i want to manage my date to check availability.
Pleaseee helpp meee

Thank you

**Comment by bobylito** [comment]
It is not possible to filter by position in the array with Algolia. But you could use facets. I suggest that you reach out to the Algolia support directly because booking use cases can be tricky.

**Comment by bobylito** [comment]
I will close this issue as it is more related to the usage of Algolia itself and therefore the support might be of greater help. Feel free to open a new if you think that something could help you on InstantSearch.js side.
