### ISSUE TITLE
example for currentRefinedValues doesn't have any refinements to remove

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2654]
**Do you want to request a *feature* or report a *bug*?**

bug (docs)

**Bug: What is the current behavior?**

the widget is just shown, but not useful since there are no refinements

**Bug: What is the expected behavior?**

have some widgets shown so users can see what currentRefinedValues does

**Bug: What is the proposed solution?**

add some refined widgets into that example

**Comment by francoischalifour** [comment]
This is replaced by the [widget showcase](https://www.algolia.com/doc/guides/building-search-ui/widgets/showcase/js/).
