### ISSUE TITLE
connectInfiniteHits has undefined hits when updating state

### ISSUE THREAD

**Issue by udewilde** [algolia/instantsearch.js#2663]
Hi,

I have implemented connectInfiniteHits [react-infinite-scroller](https://github.com/CassetteRocks/react-infinite-scroller), and all is working almost perfectly.
But whenever the state of the React Component is modified (not related to the infiniteHits), the connector is re-rendered with value `undefined` for the `hits` prop, which breaks the page.

Inside the `connectInfinitHits` connector :
It looks like `refine` is firing whenever the state of the component changes, leading to the issue.
`this.previousPage` and `hits` are `undefined`, so following logic loop is ignored, and `this._allResults` is `undefined` as well.

```
if (page === 0) { 
  this._allResults = hits; 
} else if (page > this.previousPage) { 
  this._allResults = [].concat(_toConsumableArray(this._allResults), _toConsumableArray(hits)); 
} else if (page < this.previousPage) { 
  this._allResults = hits; 
}
```
Am I doing something wrong?

**Comment by Haroenv** [comment]
Hey @udewilde, since you're talking about React, I think you meant to open this issue in https://github.com/algolia/react-instantsearch/, I'm going to move the issue there. 

Follow up the resoution in https://github.com/algolia/react-instantsearch/issues/883
