### ISSUE TITLE
Link to Places docs?

### ISSUE THREAD

**Issue by Meschreiber** [algolia/instantsearch.js#2664]
A user was looking for how to integrate Places into instantsearch.js and said this
"It might be nice if you linked to that more prominently within the instantsearch.js documentation."

in reference to https://community.algolia.com/places/documentation.html#instantsearchjs

What do you think of adding a link to the bottom of 'wrapping up' for those curious on how to integrate Places?

**Comment by vvo** [comment]
Documentation feedback that must be incorporated in the documentation specs @mthuret is going to do in Q1, added the feedback label

**Comment by bobylito** [comment]
Feedback has been reported. Thanks again @Meschreiber
