### ISSUE TITLE
Doc website: Visible scrolling bars

### ISSUE THREAD

**Issue by ElPicador** [algolia/instantsearch.js#2667]
**Bug: What is the current behavior?**
The menu on the left has a horizontal scrollbar visible. It prevents to see all the content of the menu
<img width="409" alt="screenshot 2018-01-22 18 47 34" src="https://user-images.githubusercontent.com/16667/35235643-0505cb1e-ffa5-11e7-9582-a9a468d44063.png">

**Bug: What is the expected behavior?**
Not to see them

**Bug: What browsers are impacted? Which versions?**
FF 57

**Comment by Haroenv** [comment]
@lukyvj

**Comment by LukyVj** [comment]
Thanks for opening the issue @ElPicador ! 
So, there is so far no way to hide them easily in FF. 

Right now I don't have bandwidth to take care of this, I'll do it as soon as possible. 
Meanwhile, I encourage you to check this pen! https://codepen.io/JonAnderDev/pen/XJNOPr

It's a bulletproof way to hide them on every browsers

**Comment by ElPicador** [comment]
Thanks for the insights. I agree it's not a big deal.
But, IMHO, #2666 is far more an issue. Could you have a look?

**Comment by bobylito** [comment]
I use FF (beta) and the behavior is now similar to chrome. If it's not already the case in stable, it'll come soon.

As for the horizontal scrollbar, this is definitely doable. PR is proposed.
