### ISSUE TITLE
Add a warning if `addWidget` is called without ever calling start()

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2671]
**Do you want to request a *feature* or report a *bug*?**

feature

**Feature: What is the current behavior?**

you might lose a lot of time if you forget to call `search.start()`

**Feature: What is the expected behavior?**

A warning gets printed to the console if after X amount of time, the `search.start()`. was never called.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

A dev-only check if `instantsearch()` has been called, but it's `start` method hasn't been called. 
This should show a warning to the console to educate to type `.start()`

**What is the version you are using? Always use the latest one before opening a bug issue.**
2.4.1

**Comment by Haroenv** [comment]
This can be done with a `setTimeout` in DEV only let's say 5 seconds after the last addWidget call if search is not done

**Comment by francoischalifour** [comment]
Closing this issue – see https://github.com/algolia/instantsearch.js/pull/3238#issuecomment-457122597.
