### ISSUE TITLE
I could not find what I was looking for - Hierarchical Menu Sort

### ISSUE THREAD

**Issue by GT24---** [algolia/instantsearch.js#2673]
Hi Algolia, 

I'm looking through the documentation on InstantSearch.js and I couldn't find an example of how to sort an hierarchical menu using a sort function. 

What I want to achieve is sort the hierarchical menu based on the order I have decided on so it's on based on the name of them item or the number of items underneath it.

Can you please provide an example on how to achieve this?

Thanks Algolia!

**Comment by bobylito** [comment]
You can provide a function to the [sortBy](https://community.algolia.com/instantsearch.js/v2/widgets/hierarchicalMenu.html#struct-HierarchicalMenuWidgetOptions-sortBy) parameter. This provided function should be like a [compare function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description).

**Comment by bobylito** [comment]
@GT24--- Any luck here?

**Comment by GT24---** [comment]
Yup! I managed to get it at the end. 
Sorry for the late reply!

Thanks so much!

**Comment by Asahro** [comment]
I have same question, can it sort by choosen velue be first ?

**Comment by GT24---** [comment]
I switched over to refinement list from hierarchicalMenu but they both have the sortBy attribute. 
You could create a numeric  attribute to sort by and use for sorting. 

Here is some code: 

` S.addWidget(instantsearch.widgets.refinementList({
            container: "#search-facet-categories",
            attributeName: "AttributeToSortBy",
            sortBy: ["name:desc"],
            operator: "or",
            limit: 100,
            autoHideContainer: true,
            templates: {
                header: "Review Value",
               },            },
            cssClasses: {
                active: "selected"
            },
            transformData: function(e) {
                return e
            }
        }));`

**Comment by Asahro** [comment]
ohh, I see, i try another way using 
sortBy: function(a, b) {
      return -1;
    },
so the first (choosen) will show the first.
but i have another  problem now, is there any whay to hide the first parent in hierarchicalMenu ?
I try 
showParentLevel: false, 
but it just hide the second and else parent, but the first will always show up.

**Comment by GT24---** [comment]
Not sure if this is the best way to do it but you could inspect your DOM and hide the first parent using javascript.

Something like this in jQuery
$(".ais-refinement-list--header").css("display", "none");

Instead of ais-refinement-list--header, you would replace it with the class assigned to the first parent.

**Comment by Asahro** [comment]
I think the choosen one will display none too.
