### ISSUE TITLE
MenuSelect Widget in the WordPress Plugin?

### ISSUE THREAD

**Issue by andrewstephens** [algolia/instantsearch.js#2674]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: I'm running the WordPress plugin on a client's site and they want a dropdown menu for one of the facets, but when I try to add the MenuSelect widget, it throws an error that "menuSelect is not a function".

**Comment by Haroenv** [comment]
Wordpress has v1 of InstantSearch which doesn’t have this widget yet. You need to manually update InstantSearch in Wordpress, cc @rayrutjes

**Comment by rayrutjes** [comment]
There is currently no easy way to upgrade to instantsearch v2 in the wordpress plugin.

The easiest would be to do a fully custom search experience and re-use the existing indices.

**Comment by bobylito** [comment]
@andrewstephens If you want to make a menu select, you could [copy the menu connector](https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/menu/connectMenu.js) in your codebase and [follow the v2 guide](https://community.algolia.com/instantsearch.js/v2/guides/customization.html) (that should work with v1). The only dependency of the connector is over `checkRendering` in the utils of instantsearch, you can discard the use of this test to remove this dependency.

This is not the nicest solution, but this is the best we can offer until the plugin moves forward and  uses InstantSearch.js v2.

I am closing this issue. I suggest you add an issue in the plugin repo if you'd like the plug-in to support InstantSearch.js v2.
