### ISSUE TITLE
Proposal: Align menu and connectMenu behaviour with RIS Menu

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2676]
**Do you want to request a *feature* or report a *bug*?**

A feature/bug

**Bug: What is the current behavior?**

When using a **menu** with **React InstantSearch**, we get this behaviour:

![2018-01-25 14 41 37](https://user-images.githubusercontent.com/123822/35391093-ebcb53c2-01dd-11e8-80f2-7dd70862bb29.gif)

Steps to reproduce:
- Load the [HierarchicalMenu story](https://community.algolia.com/react-instantsearch/storybook/?selectedKind=HierarchicalMenu&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)
- Click on Lighting
- Type/search "boholmen"

**But** when using a **menu** with **InstantSearch.js**, we get this behaviour:

![2018-01-25 14 56 26](https://user-images.githubusercontent.com/123822/35391785-ff9b4e1e-01df-11e8-969c-39fcb7623c26.gif)

Steps to reproduce:
- Load the [example](https://codesandbox.io/s/8zpoxz7jw0)
- Click on Lighting
- Type/search "boholmen"

**Bug: What is the expected behavior?**

It should still show other matching categories as a way to allow the user to have more context.

**Feature: What is the proposed solution?**

Switch from hierarchical facet to disjunctive facet in the menu implementation.

**Comment by francoischalifour** [comment]
The behaviors are aligned with InstantSearch v3 ([see Menu stories](https://instantsearchjs.netlify.com/stories/?path=/story/menu--default)).
