### ISSUE TITLE
RFC: more complete connectPagination

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2680]
**Do you want to request a *feature* or report a *bug*?**

feature

**Feature: What is your use case for such a feature?**

Currently there's still a significant amount of code to write if you want to write your own `pagination` component.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

Deal with the whole clamping, +1 / -1 and padding issue in the connector rather than the view

**What is the version you are using? Always use the latest one before opening a bug issue.**

2.4.1

**Comment by Haroenv** [comment]
the connector should give me: 

1. current page
2. first / last, next / previous page (just the value)
3. array with padded pages (each with `active: bool` or something)
4. createURL
5. refine

**Comment by Haroenv** [comment]
This is probably mostly fixed by shipping https://github.com/algolia/instantsearch.js/blob/develop/src/components/Pagination/Paginator.js as part of the connector

**Comment by bobylito** [comment]
I'm in! I agree and it fits the ALLAPITV (as little logic as possible in the view) principle :) That's a breaking change though. Maybe a candidate for the v3?

**Comment by iam4x** [comment]
I'm not sure about it, this is view logic I think. 
We provide connectors so you can create your own pagination with the raw data.

Or do you want to enhance the current connector to have an array of already generated pages?
Like I do here: https://github.com/algolia/angular-instantsearch/blob/master/src/pagination/pagination.ts#L126-L166

**Comment by Haroenv** [comment]
IMO that's very brittle logic that I'd rather have in the connector than in the widget, the one you linked seems like another implementation than the one in IS.js with Pagination.js. for exactly that reason I'd like to have this info in the connector
