### ISSUE TITLE
Show Name of Matching Person Then Highlighted Result

### ISSUE THREAD

**Issue by IAmDragon** [algolia/instantsearch.js#2681]
Hey all,

So what I'm trying to do is have a search on my site that searches through users. It's supposed to search through a lot of attributes (about 10-12) and it's supposed to return matched users links to their profile using the hit item's `{{username}}` such as `<a href="mywebsite.com/{{username}}>{{name}}</a>`

What I'd like is that first part `<a href="mywebsite.com/{{username}}>{{name}}</a>: ` and then it would return the matched result

So part of my query might be searching for a movie credit for instance, where we would have something like this value in the backend `The Incredible Hulk, Co-Star, Steven Spielberg, Film`

So If I queried for "Hulk", I would want it to show, `<a href="mywebsite.com/{{username}}>{{name}}</a>: The Incredible _Hulk_, Co-Star, Steven Spielberg, Film`.

Edit: Hulk in the above was supposed to be italicized

I just don't know quite how to access the matched term

Thanks, I appreciate all you've done, this was the easiest setup for search that I've ever used

- Zach

**Comment by IAmDragon** [comment]
Adding as a comment as well

Is there a better way to display the search results?

Right now I'm using a default like `background: white; padding-top: 1em; padding-bottom: 1em;` style on the hits div, but I'm wondering if you've seen any really good basic UI implementations that look good, or maybe using the autocomplete? I've never messed with a search before and this is all new to me and styling the output I have no idea how to do it

**Comment by Haroenv** [comment]
Would be nice if you gave a codesandbox with what you have now, we’ll be able to give feedback then. Regardless of that, did you take a look at matchLevel and matchedWords in _highlightResult?

**Comment by IAmDragon** [comment]
Here's my current setup:
https://jsfiddle.net/frpb3ez4/1/

**Comment by bobylito** [comment]
Like @Haroenv, what you're looking for is _highlightResult. For example, after typing `j` in your search, you get hits with:

<img width="550" alt="screen shot 2018-01-30 at 14 47 33" src="https://user-images.githubusercontent.com/393765/35569595-c50bdbba-05cc-11e8-8e5b-958bc43794d9.png">

To build an autocomplete, I'd rather [autocomplete.js](https://github.com/algolia/autocomplete.js/) that comes with good default settings for this kind of use case.

**Comment by IAmDragon** [comment]
Right, I know of _highlightResult but it only matches the name, not the actual word that's matched as far as I can tell.

**Comment by Haroenv** [comment]
@IAmDragon, that's because you need to put it in `searchableAttributes` and `attributesToHighlight`

**Comment by IAmDragon** [comment]
@Haroenv They're in my searchable attributes now but _highlightResult.name.value is always equal to their name rather than the matched word (Added them to attributesToHighlight too)

**Comment by Haroenv** [comment]
Did you check “matchedWords”

**Comment by IAmDragon** [comment]
Here's what I have
```
item: '<a href="https://theareel.com/{{username}}">{{name}}</a>: {{{_highlightResult.name.value _highlightResult.actingcredits.value _highlightResult.specialskills.value}}}'
```

It still doesn't show anything, I'm probably confusing the variables but I want it to show only the matched result as in, if the query was 'Hulk' and the matched result was The Incredible Hulk, it should show 
```
'The Incredible <em>Hulk</em>'
```

But I can't seem to make it work, what am I doing wrong? I tried _highlightResult.actingcredits.matchedWords[0] as well and nothing shows still

**Comment by Haroenv** [comment]
So you want to show the name if it’s there and otherwise the actingvalue? In this case you should add an 

```js
if (name.matchedWords.length >0) // render name
else // render the other thing
```

That was just pseudocode, but it should be quite close

**Comment by IAmDragon** [comment]
Where do I put that? Can I use if's after item: ? I didn't think I could because it accepts an array
