### ISSUE TITLE
Add default values for display only widgets (currentRefinements, breadcrumb)

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#2683]
If you go here: https://community.algolia.com/instantsearch.js/v2/widgets/breadcrumb.html#example

And click on "run", then nothing appears. 

I would have expect to see the breadcrumb displayed (with a Hierarchical Menu if we want the user  to play with it).

**Comment by bobylito** [comment]
Displaying multiple widgets might be an issue though :/

**Comment by Haroenv** [comment]
I think this is an issue for currentRefinements too

**Comment by francoischalifour** [comment]
I think this issue is solved with the [widgets showcase](https://www.algolia.com/doc/guides/building-search-ui/widgets/showcase/js/). Feel free to reopen if not!
