### ISSUE TITLE
No analytics for v2 

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#2684]
When looking into Google Analytics, I can't find any of them for the v2. 
But I can see them for the v1. 

Usage for `googleTagManager` might be missing. (see: https://github.com/algolia/react-instantsearch/blob/fbbe9386e79acd4c36f03b54580321910b7a27a2/docgen/layouts/common/marketing.pug)

**Comment by bobylito** [comment]
This has been fixed and pushed on the doc.
