### ISSUE TITLE
Images don't have a `max-width` in the documentation container 

### ISSUE THREAD

**Issue by francoischalifour** [algolia/instantsearch.js#2685]
**Do you want to request a *feature* or report a *bug*?**

Bug

I'm writing a guide and wanted to add a screenshot. The image is 800px wide and overflows in most cases.

**Bug: What is the current behavior?**

Images in `.documentation-container` don't have any maximum size.

![localhost_3002_v2_guides_calendar-widget html ipad pro 1](https://user-images.githubusercontent.com/6137112/35627642-d475502c-0699-11e8-9df5-d620443ba1aa.png)

(rendered as an iPad Pro)

**Bug: What is the expected behavior?**

![localhost_3002_v2_guides_calendar-widget html ipad pro](https://user-images.githubusercontent.com/6137112/35627706-02e77b42-069a-11e8-8a6e-bc446c40f9bc.png)

**Bug: What browsers are impacted? Which versions?**

All

**Bug: What is the proposed solution?**

We should probably set `max-width: 100%;` to images inside `.documentation-container`.

cc @LukyVj probably

**Comment by bobylito** [comment]
Since @LukyVj is very busy, you could fix it on your end. And he will tell you if that's the incorrect way to fix :)

**Comment by francoischalifour** [comment]
Got it!
