### ISSUE TITLE
InstantSearch imports EventEmitter incorrectly

### ISSUE THREAD

**Issue by zenmumbler** [algolia/instantsearch.js#2730]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
We put the instantsearch.js module into our (rollup) build and got an error that internal node module "events" does not export `EventEmitter`.

When I looked there is an ES6 import:
https://github.com/algolia/instantsearch.js/blob/541699d900ca0a20e17c5624baa1a7ab085fbf9a/src/lib/InstantSearch.js#L9
Which is a named import.

But in the relevant module at `node_modules/instantsearch.js/node_modules/events/events.js`, which uses CommonJS exports, the exports is defined as such:
`module.exports = EventEmitter;`
Which is a default export.

I assume in your build system this got forced into resolving, but Rollup is strict with ES imports. To have the project build I quickly changed the line in InstantSearch.js to a default import:
`import EventEmitter from 'events';`
and it builds fine.

I also found a correct, default import being used in one of your tests: https://github.com/algolia/instantsearch.js/blob/3b659783cd659f82539d97aec2e3ca1e691797f5/src/widgets/search-box/__tests__/search-box-test.js#L2

**Bug: What is the proposed solution?**
Make the import in InstantSearch.js a default export as shown above for correctness and consistency with the test code.

**Comment by Haroenv** [comment]
Thanks a lot, this logic definitely makes sense. Are you up for making a PR with your changes?

**Comment by Haroenv** [comment]
I can finally replicate it (apparently only happened on a UMD build): 

```
src/instantsearch.umd.js → dist/vue-instantsearch.js...
[!] Error: 'EventEmitter' is not exported by node_modules/instantsearch.js/node_modules/events/events.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules/instantsearch.js/es/lib/InstantSearch.js (19:9)
17: import union from 'lodash/union';
18: import isPlainObject from 'lodash/isPlainObject';
19: import { EventEmitter } from 'events';
             ^
20: import urlSyncWidget from './url-sync.js';
21: import version from './version.js';
```

Made a PR too

**Comment by zenmumbler** [comment]
Thanks for fixing this, we had already changed to use another Algolia component and I completely forgot about this issue, my apologies.

**Comment by Haroenv** [comment]
Which other Algolia component do you use now @zenmumbler - just out of interest!

**Comment by zenmumbler** [comment]
@Haroenv Had to check a bit as this was a while ago, but we switched from direct use of `instantsearch.js` to `vue-instantsearch` which removed the `import "instantsearch.js"` statement from our code and made Rollup not have to resolve it (Rollup is configured with `esnext: true`). So we didn't actually change components, just the way it was imported in the app.

We now use the `ais-index` and `ais-results` components, with a custom combobox component that uses Component (algoliaComponent) as a mixin. Composed like so:

```
<ais-index :app-id="..." :api-key="..." :index-name="...">
    <stuff>...</stuff>
    <custom-combobox (template external but inlined here)>
        <more-stuff>...</more-stuff>
        <ais-results>
            <combo-item>...</combo-item>
        </ais-results>
    </custom-combobox>
</ais-index>
```

I also had to add an Object.assign (and ES Promise) polyfill as we have to support IE 11, but that worked fine with no other changes. Can't point to the repo sadly, but you can check the site here: https://suburbia.io/

Thanks!

**Comment by Haroenv** [comment]
Perfect! Thanks for Giving the info :)
