### ISSUE TITLE
I could not find what I was looking for - placeholders in priceRanges and last item in hierarhaicalMenu

### ISSUE THREAD

**Issue by SchmidtDawid** [algolia/instantsearch.js#2734]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: 

-How to add placeholders to priceRanges widget, 
-How to add class to LAST (last in depth) item in hierarchaicalMenu widget. I dont know how to add css style only to item which can't be collapsed.

**Comment by iam4x** [comment]
Hi @SchmidtDawid these options are not available, if you need to customise theses widgets in depth you will need to use the [connectors](https://community.algolia.com/instantsearch.js/v2/connectors.html) API.

There is a [guide](https://community.algolia.com/instantsearch.js/v2/guides/customization.html) explaining step by step how to customize widgets.
