### ISSUE TITLE
Toggle: Using the attributeName in the template

### ISSUE THREAD

**Issue by Braunson** [algolia/instantsearch.js#2740]
I'm trying to add use the `unique` `attributeName` for my Toggle in the custom template (to link the label to the input) but I can't seem to find any way to access it within the template.

```js
var toggleTemplate = '<div class="be-checkbox">' +
    '<input id="toggle_{{attributeName}}" type="checkbox" class="{{cssClasses.checkbox}}" value="{{name}}" {{#isRefined}}checked{{/isRefined}}>' +
    '<label for="toggle_{{attributeName}}">{{name}} <span class="{{cssClasses.count}}">{{#helpers.formatNumber}}{{count}}{{/helpers.formatNumber}}</span></label>' +
    '</div>';
search.addWidget(
    toggle({
        container: document.querySelector('#type-dinner-container'),
        attributeName: 'type_dinner',
        label: 'Dinner',
        autoHideContainer: false,
        templates: {
            item: toggleTemplate
        }
    })
);
```

Required: unique identifier for this element, using the label isn't ideal since it can include special characters and spaces.

## A (not ideal) solution

I can use `transformData` to do some less than ideal magic to achieve a similar result (excluding special characters in this case)

```js
transformData: function (item)
{
    item.attributeName = item.name.replace(/ /g,"_").toLowerCase();
    return item;
},
```

However since I have 12 toggles, adding this to every toggle widget object statement is not ideal as you can imagine..

Perhaps the `attributeName` should be passed into the render method?

**Comment by Haroenv** [comment]
There's multiple workarounds at least for this case:

1. wrap the input in the label and you don't need the brittle coupling of ids, which is more accessible
2. use `transformData` as you said
3. we add `attributeName` to all of the templates

I can see why you'd want this, but we haven't had any problems so far with this, so I'm not sure yet if it should be added.

If you have a lot of toggles, is it possible you really want a custom [refinementList](https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html) instead? That would be simpler I think. You can customise the rendering completely by using the connector if necessary

**Comment by Braunson** [comment]
@Haroenv Thanks for the options however `attributeName` was not accessible nor available in my custom template. The reason for the unique name was due to how the toggles were originally designed. Wrapping them does ruin the UI of it (tho that can be easily fixed by updating the CSS).

Also thanks for the tip on `refinementList`, I'll take a look!

**Comment by Haroenv** [comment]
Feel free to reopen this issue if you find a need for it again though, I'm totally open for the idea, just looking for usecases

**Comment by Braunson** [comment]
@Haroenv Yes I feel a unique identifier that could be passed to the template would be nice to have, as for use cases outside what I've explained I can't think of any

**Comment by Haroenv** [comment]
I'll leave this open for now because I can see the value

**Comment by bobylito** [comment]
Hi @Braunson 
I'd like to be sure to understand your need here: do you want a unique identifier of the widget items that is also usable in your template for markup identifier (and it should not contain any spaces or special characters)? This identifier should be provided as part of the values provided to the values?

**Comment by Braunson** [comment]
@bobylito Yep exactly, I was thinking of using the `attributeName` but having a unique one that could be set would work also.

**Comment by bobylito** [comment]
I've added the feedback to put the product team in the loop. I'm closing the issue for now.
