### ISSUE TITLE
Feature: Return helpers in hits > empty template

### ISSUE THREAD

**Issue by Braunson** [algolia/instantsearch.js#2742]
The use case is to display certain text only if there was a `query` given for a search, otherwise display a different message. Outside of using a closure there's no helpful methods. 

For example. the `Toggle` widget has a `isRefined` parameter that is passed to the template so you can use it like so:

```js
{{#isRefined}}checked{{/isRefined}}
```

It would be great to have a few like this for the hit>empty template to use like so..

```js
No recipes were found with that criteria {{#hasQuery}}matching the search term{{query}}{{/hasQuery}}
```

**Comment by Haroenv** [comment]
Good idea! Let’s think about how this can be implemented. Query, search parameters are useful features. For now you can work around it by using a function rather than a straight template.

**Comment by Haroenv** [comment]
Sorry for not seeing this earlier, but the query actually is returned in the empty template, which means it can be used like this:

https://codesandbox.io/s/admiring-tharp-6kf7p?file=/src/app.js


```
No recipes were found with that criteria {{#query}}matching the search term <q>{{query}}</q>{{/query}}
```
