### ISSUE TITLE
How to change operator in currentRefinedValues widget. 

### ISSUE THREAD

**Issue by SchmidtDawid** [algolia/instantsearch.js#2744]
I can't change operator . I use transformdata but it doesn't work. 

transformData: {
          item(item) {
            item.computedLabel = filterNameReplace(item.computedLabel);
            item.operator = "do"; //test
            console.log(item); //display item corectly
            return item;
          },
        },

function filterNameReplace(name){
  name2 = name.toString();
  name2 = name2.replace("≤" , "do");
  name2 = name2.replace("≥" , "od");
  return name2;
}

On page still is "≤" but console.log(item) show me correct values.

**Comment by SchmidtDawid** [comment]
SOLVED

transformData: {
          item(item) {
            if(item.displayOperator == '&ge;'){ item.displayOperator = "cena od"; item.name += ' zł'; };
            if(item.displayOperator == '&le;'){ item.displayOperator = "cena do"; item.name += ' zł'; };
            return item
          },
        },

**Comment by bobylito** [comment]
Sorry for the late answer :(
