### ISSUE TITLE
How to have a static list of options in menuSelect?

### ISSUE THREAD

**Issue by iapparatus** [algolia/instantsearch.js#2748]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: -- Is there any way to prevent one widget (menu) from refining categories in another widget (menuSelect). 

In my use case I want to have the list of categories in menuSelect widget to be static. --

**Comment by bobylito** [comment]
Thanks @iapparatus for opening this issue. Even though, we haven't implemented that yet, [we have it in mind](https://github.com/algolia/instantsearch.js/issues/2130).

In the meantime, I suggest you create your own menu widget widget using the [connectMenu](https://community.algolia.com/instantsearch.js/v2/connectors/connectMenu.html). Using it you can inject the static list of values that you want.

**Comment by bobylito** [comment]
Since we already have an other issue tracking this need, I'll close this one for now. Thanks for your reporting it @iapparatus

**Comment by iapparatus** [comment]
@bobylito Thanks! I was able to create the menu based on the connectMenu example. Is 'canRefine' option set to 'false' what I need to make the menu static? If so, how do I add it to this example code?

```
// custom `renderFn` to render the custom Menu widget
function renderFn(MenuRenderingOptions, isFirstRendering) {
  if (isFirstRendering) {
    MenuRenderingOptions.widgetParams.containerNode
      .html('<select></select');

    MenuRenderingOptions.widgetParams.containerNode
      .find('select')
      .on('change', function(event) {
        MenuRenderingOptions.refine(event.target.value);
      });
  }

  var options = MenuRenderingOptions.items.map(function(item) {
    return item.isRefined
      ? '<option value="' + item.value + '" selected>' + item.label + '</option>'
      : '<option value="' + item.value + '">' + item.label + '</option>';
  });

  MenuRenderingOptions.widgetParams.containerNode
    .find('select')
    .html(options);
}

// connect `renderFn` to Menu logic
var customMenu = instantsearch.connectors.connectMenu(renderFn);

// mount widget on the page
search.addWidget(
  customMenu({
    containerNode: $('#custom-menu-container'),
    attributeName: 'categories',
    limit: 10,
  })
);
```
