### ISSUE TITLE
All render methods of the widgets should read the state provided by instantsearch

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#275]
Because of the synchronisation problem that can occur, when a component updates itself based on searchparameters, it should use the one provided by the render parameters rather than using the one from the helper.

**Comment by bobylito** [comment]
Or at least the URL sync widget :)

**Comment by vvo** [comment]
@bobylito Is there any action we can do right now that would solve some issues we have? I fail to see if we currently have any issue from not doing what you are proposing.

If there is any action we need to do, create a new issue with clear goals and assign to milestone 1.0.0

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it
