### ISSUE TITLE
infinite-hits - show previous pages results 

### ISSUE THREAD

**Issue by kamilo81** [algolia/instantsearch.js#2750]
My initial page params:  ?q=&idx=items&p=2
it shows me only results from page 2 and i can not show result form page 1 and page 0.
I dont want to use pagination. Im only using infinite-hits with show more button.

There is a way to show results from p0 to p2 ?

**Comment by bobylito** [comment]
Hi @kamilo81 
So far, we've advised users with infinite hits UI to not synchronize the page with the URL. For now, we haven't changed our point of view. We might want to reconsider that but we have no plan yet.

**Comment by kamilo81** [comment]
Ok I dont expect ready solution but maybe can u give me some advice / workaround how can I make that?

**Comment by bobylito** [comment]
The infinite hits works by keeping the previous pages internally. Since you can't access these internal, the easiest would be to [have a look at the implementation](https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/infinite-hits/connectInfiniteHits.js) and create a new widget based on your requirements.

**Comment by bobylito** [comment]
@kamilo81 have you been able to do something here?

**Comment by kamilo81** [comment]
Hi. I switched to native algolia js api. It’s easier to match my needs.

**Comment by fujiii** [comment]
You can drop "page" parameter from urlSync, and use hitsPerPage (&hPP=) parameter instead increasing it by initial hitesPerPage number.

`var hitsPerPage = 12;`

`$('body').on('click', '.ais-infinite-hits--showmore', function () {`
    `hitsPerPage += 12;`
    `search.helper.setQueryParameter('hitsPerPage', hitsPerPage);`
`});`

**Comment by Haroenv** [comment]
Note we are working on this in https://github.com/algolia/instantsearch.js/pull/3645
