### ISSUE TITLE
Create the default.css theme

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#277]
Since we are starting to remove all require(.css) from the JS, to provide easy theming customization:

- [x] create it in themes/default.css (add BREAKING CHANGE note about CSS loading for integrators)
- [x] enhance build task to minify all css (scripts/build.sh) and put both unminified and minified in dist/themes/default.[min].css
- [x] update doc to inform on how to load it from jsdelivr
- [x] ~~update doc to inform on how to load it from npm (location: instantsearch.js/themes/default.css)~~
- [x] publish to jsdelivr (nothing to do here but a release, it will be automatically accessible on cdn.jsdelivr.net/instantsearch.js/0/themes/default.min.css)
- [x] remove webpack loaders linked to css loading (and shrinkwrap: https://gist.github.com/vvo/d3c1c3d4358309ed2619)

@pixelastic I had to write this out of my head, feel free to edit :)

**Comment by pixelastic** [comment]
Thanks. I just pushed https://github.com/algolia/instantsearch.js/pull/279 without seeing that first.

The PR is basically the first step in this `default.css` movement. It adds searchbox styling in default. I'll add all other widgets now. I've simply added symlinks from the `example` folder for now. I'll need your input for configuring webpack to build the CSS files.
