### ISSUE TITLE
Provide min / max value in slider headers and footer.

### ISSUE THREAD

**Issue by hugo-ruivo-dw** [algolia/instantsearch.js#2771]
It would be nice to have in the documentation some examples of the header and footer using function instead of string.

**Comment by bobylito** [comment]
Hi @hugo-ruivo-dw thanks for opening this issue.

Indeed this kind of information could be useful in the header / footer. However I'm not sure how feasible it is.

**Comment by Haroenv** [comment]
Do you mean adding the currently _selected_ minimum and maximum, or the values that you set while initialising the widget. If you mean the initialised values, you should be able to put them in a variable before writing the widget code, and use the same value, or just copy and paste the values.

**Comment by hugo-ruivo-dw** [comment]
I mean the currently selected minimum and maximum.

**Comment by oscarhandsome** [comment]
Somebody know an answer?

**Comment by francoischalifour** [comment]
@oscarhandsome This is currently not feasible with the current API. However, your feedback is greatly appreciated – we'll let you know if we make the bound values available.

**Comment by oscarhandsome** [comment]
> @oscarhandsome This is currently not feasible with the current API. However, your feedback is greatly appreciated – we'll let you know if we make the bound values available.

Thank you for the answer, but, now I don't understand how can I move values to another tag? https://prnt.sc/l55g2s
might do you know a way?

**Comment by francoischalifour** [comment]
Sorry for the late answer.

I'm not sure to understand the last question.

Assuming you're using InstantSearch.js v2, you can style the CSS class to move the price values:

```css
.ais-range-slider--tooltip {
  margin-top: 50px;
}
```

You can change the `margin-top` value at your convenience.
