### ISSUE TITLE
Facet values starting with `-` are considered exclusions by default

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2776]
**Do you want to request a *feature* or report a *bug*?**
bug

**Bug: What is the current behavior?**
When facet values displayed in a refinement list (or menu, hierarchical menu) are starting with a dash like temperature: -80C then clicking on those values will fail because it will be understood as a facet exclusion by the Algolia engine. 

Example: https://codesandbox.io/s/jpkzxoo20v

Clicking on any refinement won't change anything

**Bug: What is the expected behavior?**

Clicking on refinements should refine. Values should be automatically escaped.

**Bug: What is the proposed solution?**

We could automatically escape refinement values to "\-80C", since doing a refinement list with excludes is not today a feature. And if it is a feature at some point then it will be explicit not based on the data.

**What is the version you are using? Always use the latest one before opening a bug issue.**

Latest

**Comment by Haroenv** [comment]
I wonder if this is a method or option on the existing method in the Helper we could have, for example `escapeFacetValues`, in this case about things relevant for Algolia though, not about the option against XSS injection. Not sure what a better name can be and which other values need to be escaped
