### ISSUE TITLE
Questions about GeoSearch

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#2778]
> Amazing work! Great documentation, great examples, I'm loving it so far. ❤️ 
>
> **Question about InfoBox** : I am wondering how you make it work ([in this example](https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=GeoSearch.with%20built-in%20marker%20%26%20InfoBox)) without referencing [InfoBox](https://github.com/googlemaps/v3-utility-library/tree/master/infobox) in your script?
>
> **Question about MarkerClusterer** : I have been trying to add the [MarkerClusterer](https://github.com/googlemaps/v3-utility-library/tree/master/markerclusterer) with no success. Any tips?

https://github.com/algolia/places/issues/453#issuecomment-371224377

cc @philmarc

**Comment by samouss** [comment]
> **Question about InfoBox** : I am wondering how you make it work ([in this example](https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=GeoSearch.with%20built-in%20marker%20%26%20InfoBox)) without referencing [InfoBox](https://github.com/googlemaps/v3-utility-library/tree/master/infobox) in your script?

Actually we are using the `InfoBox` in the examples. It's just that we don't use Google Maps globally, in order to avoid to load the library on all the examples. So we created a [simple wrapper](https://github.com/algolia/instantsearch.js/blob/develop/dev/app/utils/create-info-box.js) around the `InfoBox` to allow the loading of Google Maps asynchronously.

> **Question about MarkerClusterer** : I have been trying to add the [MarkerClusterer](https://github.com/googlemaps/v3-utility-library/tree/master/markerclusterer) with no success. Any tips?

We don't support the clustering out of the box with the built-in widget. For now you can use [the connector API](https://community.algolia.com/instantsearch.js/v2/connectors.html) in order to implement your own rendering. You will have a full control of what is render. So you can easily plug the clustering support. You can find an example of an implementation with the [connectGeoSearch](https://community.algolia.com/instantsearch.js/v2/connectors/connectGeoSearch.html) connector in our documentation.

**Comment by philmarc** [comment]
Thanks for the clear answers.

Here is snippet of my `infobox`, I am not sure it is the right way but it does work, if it can help someone.
```
<!-- require infobox.js -->

var search = instantsearch({
  appId: xxx,
  apiKey: xxx,
  indexName: xxx
});

var o = new InfoBox({/*options*/});

var map = instantsearch.widgets.geoSearch({
  container: '#map',
  googleReference: window.google,
  customHTMLMarker: {
    template:  function(e) {
      return '<div>' + e.title + '</div>'
    },
    events: {
      click: function(e) {
        o.getMap() && o.close(), o.setContent('<div>' + e.item.title + '</div>'), o.open(e.map, e.marker)
      }
    }
  },
});

search.addWidget(map);
search.start();
```


**Question about Places with GeoSearch:**
I am now trying to display an _Algolia Places_ [search input](https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=GeoSearch.with%20position%20from%20Places) to my `geoSearch` widget. I gathered that the _Places_ script is already included in `instantsearch.js`, so I don't need to reference it.

But I am having hard times to understand how to implement it, could someone give me a simple example? 
_It could be nice if the [examples](https://community.algolia.com/instantsearch.js/v2/dev-novel) had a little snippet to copy._

**Comment by samouss** [comment]
> _It could be nice if the [examples](https://community.algolia.com/instantsearch.js/v2/dev-novel) had a little snippet to copy._

Yes, you are right we should provide some links & snippets for the examples. Thanks for your feedback! For now you can find all the examples on GitHub. Here is [the code](https://github.com/algolia/instantsearch.js/blob/develop/dev/app/builtin/stories/geo-search.stories.js) for the examples about the GeoSearch widget.

> **Question about Places with GeoSearch:**
I am now trying to display an _Algolia Places_ [search input](https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=GeoSearch.with%20position%20from%20Places) to my `geoSearch` widget. I gathered that the _Places_ script is already included in `instantsearch.js`, so I don't need to reference it.
>
>But I am having hard times to understand how to implement it, could someone give me a simple example? 

Actually no Places is not provided with InstantSearch. You need to install it on your own and then use the widget shipped with the library to use it with InstantSearch. You can find more informations about how to use it & integrate it in [the Places documentation](https://community.algolia.com/places/examples.html#instantsearchjs). There are [the lines](https://github.com/algolia/instantsearch.js/blob/develop/dev/app/builtin/stories/geo-search.stories.js#L197-L232) that create the Places example with the GeoSearch widget.

**Comment by vaughn-taylor** [comment]
@samouss -- Algolia is great and we're paying a ton of money for it. So, I don't think it's too much to have comprehensive examples all in one place with code snippets. The documentation is literally and figuratively all over the place. I'm trying to figure out how to add a geo search map to my site, and the example you provided above doesn't really fit the need. I looked on this page (https://community.algolia.com/instantsearch.js/v2/widgets/geoSearch.html), but the example is minimal and produces this error: "instantsearch.widgets.geoSearch is not a function". I'm honestly growing tired of trying to unravel other people's code just to get stuff done.

Any ideas of where I could find good examples, and why the code snippet from the widgets page does not work?

**Comment by samouss** [comment]
@vaughn-taylor I'm sorry that you have some issue with the GeoSearch widget. First of all thanks for your feedbacks, indeed you are right we should have code snippets or a guide that demonstrate the usage of the widget. All the sources of the examples in [our widget showcase](https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=GeoSearch.default) are available on [GitHub](https://github.com/algolia/instantsearch.js/blob/develop/dev/app/builtin/stories/geo-search.stories.js#L75-L81), we know that it's not the best place for discoverability but for now it's the solution that we have. 

About the error, you need to have the latest version ([v2.6.0](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#260-2018-03-06)) of InstantSearch in order to have the widget available. If the problem persist you can do a small example, I'll be happy to help you implement the widget. We have a template available for the example to avoid your all the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/InstantSearch.js).

**Comment by vaughn-taylor** [comment]
@samouss, I appreciate your response and I may need your help. However, Algolia really MUST work on their documentation. If you are going to present pages like this: https://community.algolia.com/instantsearch.js/v2/widgets/geoSearch.html the examples on the page should be functional and link to fully executed examples. Again, my frustration comes from paying a premium price for the product, and not being able to easily implement it. I'm burning up time just trying to make things work instead of being able to implement the product for our customers.

**Comment by bobylito** [comment]
Hi @vaughn-taylor have you been able to update the version of InstantSearch?

A guide is coming. Thanks for your patience.

**Comment by vaughn-taylor** [comment]
@bobylito @samouss, yes I've updated to the most current version. I have a codepen here if you have time to take a look: https://codepen.io/vaughndtaylor/pen/2431919cc9a8547ab36c019add338392/?editors=1010

Basically, the idea is to have a map that is populated with the locations each provider works at. Some providers have 1 location, some have multiple, so _geoloc is an array in my data set.

**Comment by samouss** [comment]
Hi @vaughn-taylor thanks for the example it helps a lot to understand the issue. The first problem that cause the map to not showing up is that Google Maps requires to set a height on the element where the map will be attached. We don't provide a default value for this because it can be hard to override. By adding this line of CSS the map should be displayed.

```css
#map {
  height: 350px;
}
```

But it will not display the results because the current widget doesn't support multiple locations for the `_geoloc` attribute. This is a limitation for now, I've opened [an issue](https://github.com/algolia/instantsearch.js/issues/2838) about that. A possible solution is to duplicate the records where you have multiple locations in order to have a single location for each of you records. Then you can use the `distinct` attribute to deduplicate your results. You can find more details about that [in our documentation](https://www.algolia.com/doc/guides/ranking/distinct). With this data structure you will be able to use the Geo Search widget.

**Comment by vaughn-taylor** [comment]
@samouss, I spent way too much time trying to figure this out -- this should have been in the documentation. Nearly 3 years ago (https://blog.algolia.com/geo-search-on-steroid/), Algolia touted the ability to pass an array of locations, so why is it not part of the widget?

**Comment by samouss** [comment]
You are right it should be in the documentation. We have added it in [the requirements section](https://community.algolia.com/instantsearch.js/v2/widgets/geoSearch.html#requirements) of the widget. We know that we don't cover all the use cases. But this is the first version of the geo widget. We are gathering feedback about his usage, it will help us to implement the proper features in a next version.

**Comment by parterburn** [comment]
@samouss how can we reference the map object created by the GeoSearch widget?

**Comment by samouss** [comment]
For the moment the only way to get a reference of the map instance is through [the events listeners on the markers](https://community.algolia.com/instantsearch.js/v2/widgets/geoSearch.html#struct-BuiltInMarkerOptions). The instance is provided as argument of the listener. We dot not provide a hook to access the instance directly otherwise. Could you give us a bit more context about your use case? It will help to better understand the issue and to find a possible solution. Thanks!

**Comment by parterburn** [comment]
@samouss a simple use case is getting the geolocation from the user's device and doing a map center based on it. e.g. even a simple `map.setCenter({lat: -34, lng: 151});` isn't possible with the current setup.

The biggest use case is the ability to have full control over the Places.js integration: it could function as a "zoom to location" from a map that starts out fully zoomed out (addressing this pull request: https://github.com/algolia/places/pull/554). It would allow you to process a search like "xyz near me".

**Comment by samouss** [comment]
For the first use case you can fetch the position from the device then mount the widget with the retrieved position. For the last use case we have already have [an issue opened](https://github.com/algolia/instantsearch.js/issues/2876) about the routing implementation. But I completely agree with you it could be handy to provide an access to the map instance (probably through an event). I've opened [an issue](https://github.com/algolia/instantsearch.js/issues/3059) about that.

For the moment a possible solution is to re-implement your own widget with [the connector API](https://community.algolia.com/instantsearch.js/v2/guides/customization.html). This API lets you have full control on the rendering. You can use the [`connectGeoSearch`](https://community.algolia.com/instantsearch.js/v2/connectors/connectGeoSearch.html) connector to implement the widget.

**Comment by samouss** [comment]
I'm closing this issue since it already covers different use cases. Please open a new one if you have other questions.
