### ISSUE TITLE
Cannot control + link refinement lists having links

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#278]
Right click open in new tab is ok. But control + click do not work, surely linked to the hacky code we have around click events.

See https://github.com/algolia/instantsearch.js/issues/278#issuecomment-149206895 for resolution

**Comment by redox** [comment]
Same bug on the Pagination widget, so probably not related to our hacky code :)

**Comment by vvo** [comment]
So this is a normal JavaScript behavior. If you attach an event handler on a `<a href` then:
- the event handler is first ran
- it opens a new tab if no preventDefault() was called

This means that we should do something like that:

```js
if (event.ctrlKey === true) {
  // do nothing and open a new tab
  return;
}

// else:
// event.preventDefault
// do the refinement
```

In widgets:
- menu
- hierarchicalMenu
- refinementList
- pagination

All of them can or have links in templates

**Comment by redox** [comment]
> This means that we should do something like that:

Keep in mind that on OS X, you need to use `metaKey`...

**Comment by vvo** [comment]
Doesn't React handle this you think?

**Comment by redox** [comment]
> Doesn't React handle this you think?

Nope, I just tested it.
