### ISSUE TITLE
ConnectRange exemple

### ISSUE THREAD

**Issue by cloughy** [algolia/instantsearch.js#2784]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: an exemple of use for connectRange.  Some exemples are available for others connectors but not this one.  Thank you for your help

**Comment by Haroenv** [comment]
You're right, there doesn't seem to be an example. The `rangeSlider` ([widget](https://github.com/algolia/instantsearch.js/blob/develop/src/widgets/range-slider/range-slider.js) using Rheostat) and `rangeInput` ([widget](https://github.com/algolia/instantsearch.js/blob/develop/src/widgets/range-input/range-input.js), [component](https://github.com/algolia/instantsearch.js/blob/develop/src/components/RangeInput/RangeInput.js)) use it though, which you can use as "documentation"

**Comment by cloughy** [comment]
thank you I might found I need there.

**Comment by Haroenv** [comment]
Perfect! Will leave open since a real example can not hurt

**Comment by timmetj** [comment]
bumping this 👍

**Comment by samouss** [comment]
Thanks for the feedback @timmetj! We are in the process to re-write all our documentation. Each connector will have a dedicated example in the next version.

**Comment by Haroenv** [comment]
This is now documented here: https://www.algolia.com/doc/api-reference/widgets/range-slider/js/?language=js#connector

**Comment by timmetj** [comment]
Great thanks!

**Comment by timmetj** [comment]
One more thing (this even might be for all connectors):
the autoHideContainer option doesn't seem to work in connectors?

**Comment by Haroenv** [comment]
autoHideContainer is part of widgets; meaning that you would implement that yourself in your custom widget. However; we do not even support autoHideContainer in the new widgets in fact
