### ISSUE TITLE
Not possible to test currentRefinedValues in the live example

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#2790]
The live example for the currentRefinedValues widget doesn't allow to set any refinement, and ultimatly doesn't show any active refinement 

![image](https://user-images.githubusercontent.com/1101220/37211532-8718d6fc-23ac-11e8-878a-5af2b459728b.png)

**Comment by bobylito** [comment]
Indeed :(

**Comment by bobylito** [comment]
We've added a link to the "story book" on every page. It's at the top of the page: https://community.algolia.com/instantsearch.js/v2/widgets/currentRefinedValues.html#live
