### ISSUE TITLE
Add possibility to refine the current breadcrumb path

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#2791]
For now the breadcrumb only shows a static path, it would be great like on Birchbox.fr  https://birchbox.fr/boutique/product-categories/corps?refinementList%5Bbrand%5D%5B0%5D=Cellu-Cup&page=0&configure%5Bfilters%5D=visible%20%3D%201
to let the users refine the navigation directly from it.

![image](https://user-images.githubusercontent.com/1101220/37211697-14f365b4-23ad-11e8-8194-1b05ea1cba05.png)

**Comment by bobylito** [comment]
That's an interesting UX.

**Comment by bobylito** [comment]
It could be an excellent candidate for a labs experiment cc @mthuret

**Comment by Haroenv** [comment]
I don’t really understand what’s meant; a curated hierarchical menu?

**Comment by Haroenv** [comment]
code isn't the cleanest, but there's an example that does something very similar (some minor style differences) here: https://codepen.io/Haroenv/pen/wrrrKj

I'll close this issue now, but you could solution-ize this component easily with the existing connector @seafoox
