### ISSUE TITLE
Laravel Webpack Instantsearchjs 2.6.* Reference Errors 

### ISSUE THREAD

**Issue by devprojectsapps** [algolia/instantsearch.js#2792]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: 
We ware using Instandsearch.js with Laravel and Webpack.
We made an update via npm to instantsearch.js 2.6.*.
If we restart our Laravel Application we get Reference Errors in our JavaScript Files for Example:
ReferenceError: $ is not defined in some other JS-Files.
If we open the Page with the instandsearch we get also this Error:
TypeError: window.instantsearch is not a function

If we downgrade to Version Instantsearch.js 2.0.2 everything is working fine.
Thats really strange and we have no idea what we can do that version 2.6. is working without these Errors in our other JS-Files.

**Comment by bobylito** [comment]
Hi @devprojectsapps. Thanks for taking the time to fill in this issue. Can you give an URL where we could see the behaviour? If your app is private, you can go through the Algolia support.

**Comment by devprojectsapps** [comment]
It is so strange. In our package.json i changed "instantsearch.js": "2.0.2" to "instantsearch.js": "^2.0.2". Then i made npm update. In our app.js we have:
`window.$ = require('jquery');
window.instantsearch = require('instantsearch.js');`

If i start the app we ware getting Reference Errors like "ReferenceError: $ is not defined" to this line "$(function()" in a different JS File.

If i got back to instantsearch.js 2.0.2 everything is working fine without any Reference Errors.

Thats soooo strange :-(

**Comment by bobylito** [comment]
It would help if you could at least provide us the steps to follow to reproduce your environment.

**Comment by devprojectsapps** [comment]
Yes i know, the problem is that our repository is a priave project hosted on bitbucket.
Its Laravel with Webpack and Laravel-mix like this:
[Using Laravel Mix with webpack](https://scotch.io/tutorials/using-laravel-mix-with-webpack-for-all-your-assets)
We are using npm for all the node_modules packaging stuff. Thats our actual package.json:

"devDependencies": {
    "axios": "^0.15.3",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.3",
    "bootstrap-sass": "^3.3.7",
    "bulma-start": "0.0.2",
    "cross-env": "^5.0.5",
    "css-loader": "^0.27.3",
    "laravel-mix": "^1.4.2",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.16.0",
    "uglify-js": "^2.8.15",
    "vue": "^2.5.13",
    "vue-router": "^3.0.1",
    "vue-select": "^2.4.0",
    "vue-slider-component": "^2.5.8",
    "vuex": "^3.0.1",
    "webpack": "^3.11.0",
    "webpack-hot-middleware": "^2.21.1"
  },
  "dependencies": {
    "algoliasearch": "^3.24.12",
    "blueimp-canvastoblob": "^2.1.0",
    "blueimp-file-upload-npm": "^9.12.3",
    "blueimp-load-image": "^2.18.0",
    "blueimp-tmpl": "^3.11.0",
    "bulma": "^0.6.2",
    "canvas-to-blob": "0.0.0",
    "clipboard": "^1.7.1",
    "dropzone": "^4.3.0",
    "font-awesome": "^4.7.0",
    "instantsearch.js": "2.0.2",
    "jquery": "3.2.1",
    "jquery-datetime-picker": "^2.5.11",
    "jquery-ui": "^1.12.1",
    "jquery.ui.widget": "^1.10.3",
    "modernizr": "^3.5.0",
    "moment": "^2.20.1",
    "nouislider": "^9.2.0",
    "slick-carousel": "^1.8.1",
    "sweetalert": "^1.1.3",
    "tmpl": "^1.0.4"
  },

Our webpack.mix.js is:

const mix = require('laravel-mix');
const webpack = require('webpack');

const extract = [
    'jquery',
    'sweetalert',
    'instantsearch.js',
    'slick-carousel'  
];

mix.autoload({
    //instantsearch: ['instantsearch'],
    jquery: ['$', 'jQuery', 'jquery']
});

and then comes all the mix.stuff like mix.sass/mix.copy/mix.js and so on

Our app.js starts with:

window.$ = require('jquery');
require('bootstrap-sass');
window.noUiSlider = require('nouislider');
window.instantsearch = require('instantsearch.js');
$(function(){ ...

If i change the line "instantsearch.js": "2.0.2" to "instantsearch.js": "^2.0.2" and make a npm update and the a npm run dev the compiling process is successful but if i reload the page in the browser i am getting these Reference errors "ReferenceError: $ is not defined" to this line "$(function()" in a different includes own JS File.

And on the Page with the Instantsearch we are getting the error the "window.instantsearch isnt existing" and so on.

**Comment by bobylito** [comment]
Thanks @devprojectsapps that's gonna be helpful :)

**Comment by devprojectsapps** [comment]
Hi.
Has something already happened in this case?

**Comment by Haroenv** [comment]
There was never an easy-to-reproduce example here, so I'll close this issue. Sorry!
