### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by mswilson4040** [algolia/instantsearch.js#2794]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: -- PLEASE FILL IN HERE --

I am trying to utilize instantsearch.js for something that doesn't appear to be very clear in the documentation or possible.

My use case is that I have a product catalog and using the connectors, I have refiners and a search box to get the correct results. However, what I need to do is add another filter to my query saying 'give me all the products that are missing the attribute 'device'.

Is it possible (using instantsearch.js preferably) to search my algolia indice for records that are missing an attribute?

**Comment by bobylito** [comment]
Hi there @mswilson4040 
Is it not possible to express that with an Algolia query. Sorry.

You could use a special facet like `__no_value__` instead of not having the attribute.
