### ISSUE TITLE
Ability to Provide sortBy compareFunction along with defaults

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [algolia/instantsearch.js#2810]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
You might want to have a compare function that also still respects the `isRefined` setting for sortBy.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
We could provide the ability to define a compareFunction, and [the various possible values](https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html#struct-RefinementListWidgetOptions-sortBy) provided as an object or otherwise: sortBy`[Array<string>|object{defaults: Array<string>, compareFunction: function}]`.

Potential way to define (not entirely sure the best way to approach):
```js
search.addWidget(
  instantsearch.widgets.refinementList({
    container: document.querySelector("#brand"),
    attributeName: "brand",
    sortBy: {
        defaults: ['isRefined', 'name:asc', 'count:desc'],
        compareFunction: (a, b) => {
        }
      }
  })
);
```

**Comment by bobylito** [comment]
Thanks @Giovanni-Mattucci we will investigate.

**Comment by Giovanni-Mattucci** [comment]
@bobylito no problem, just an update, I think I'm incorrect on this bug... I'm going to update this to a feature request instead.

**Comment by bobylito** [comment]
With the current implementation, it is not possible for us to provide such a feature. That being said, the combination of multiple sorts inside a single compare function is doable:

```js
const compare = function(a, b) {
  if (a.property1 < b.property1) return 1;
  if (a.property1 > b.property1) return -1;
  // property1 is equal for both
  if (a.property2 < b.property2) return 1;
  if (a.property2 > b.property2) return -1;
  // property2 is equal for both
  // ... and so on.

  return 0;
}
```
