### ISSUE TITLE
hierarchicalMenu widget sorts by isRefined if provided with sortBy compareFunction

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [algolia/instantsearch.js#2811]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Take a look at the two hirarchicalMenu Widgets I've created: 
https://codesandbox.io/s/jv145lmzn9

I've created a default one, and one with a sortBy function applied.
Notice that by default isRefined is not on. 
Once a sortBy function is provided, isRefined is on.

**Bug: What is the expected behavior?**
That the defaults for the widget remains consistent. If isRefined is not the default

**Bug: What browsers are impacted? Which versions?**
All browsers.

**Bug: What is the proposed solution?**
Have the widget remain isRefined=false in either case.
Additionally, provide way to refine if you want isRefined on or not in conjunction with a sortBy Function.
I've created this feature request regarding this: #2810

**What is the version you are using? Always use the latest one before opening a bug issue.**
Tested only on 2.x+

**Comment by bobylito** [comment]
In your example, you have actually no sort so yes it's expected that the original order order is preserved.

You should consider here that the API does not provide any information or guarantees in this case. If it appears to sorted by refined first it is just a side effect of the implementation, not something done on purpose.

I might have missed something but that's not a bug to me.

**Comment by Giovanni-Mattucci** [comment]
@bobylito ah I see, so it's just returning the data in the order returned, which I'm confusing for the "isRefined" sort.

Ok thanks sorry for the incorrect bug.

**Comment by bobylito** [comment]
No worries. Keep the issues coming. There might be a bug here, but the test is not enough, that's what I wanted to highlight. If you find something please open a new issue.
