### ISSUE TITLE
Search Operators

### ISSUE THREAD

**Issue by Brotakuu** [algolia/instantsearch.js#2813]
Does InstantSearch support search operators such as AND and OR? 

I found it in the docs, but doesn't seem to work for InstantSearch:
https://www.algolia.com/doc/guides/searching/filtering/#boolean-operators

**Comment by Haroenv** [comment]
Hey @Brotakuu, can you show what you've tried already? Search operators should work

**Comment by Brotakuu** [comment]
AND and OR operators in search box. I didn't find a setting to enable them in the dashboard. I tried a search such as "apple OR oranges" directly into the algolia dashboard "Browse" search box, and the operators are not enabled.

**Comment by Haroenv** [comment]
I’m not sure if this is what you mean, but try putting “advancedSyntax: true” in searchParameters on the constructor. See also: https://www.algolia.com/doc/api-reference/api-parameters/advancedSyntax/

**Comment by bobylito** [comment]
@Brotakuu have you been able to work something out?

**Comment by Haroenv** [comment]
I'll close this issue since there was no response. Feel free to continue commenting or open a new issue if there's more questions though!
