### ISSUE TITLE
The Pagination widget can generate wrong URLs

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#282]
For instance with `page=-1`. I'll disable the URL generation if `isDisabled`.

**Comment by vvo** [comment]
how was the bug triggered (what usage led to the bug?). How can I reproduce it?

**Comment by redox** [comment]
> how was the bug triggered (what usage led to the bug?). How can I reproduce it?

Check the link that is generated on the "«" previous button when you're already on the first page.
