### ISSUE TITLE
Using autocomplete.js as InstantSearch.js searchbox

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2833]
## copy of https://github.com/algolia/autocomplete.js/issues/216 by @SchmidtDawid

Hi i want to implement autocomplete but i can't make it work with instantsearch. 
When i have 2 inputs - one is for searchBox widget and the second is for autocomplete, everything works great (but of course autocomplete doesn't have impact on hits). 
But when autocomplete and searchbox pointing on same input i have an error. 
```
Uncaught TypeError: Cannot read property 'style' of null
    at search-box.js:130
    at Object.render (connectSearchBox.js:136)
    at InstantSearch.js:317
    at n (_arrayEach.js:15)
    at r (forEach.js:37)
    at t.value (InstantSearch.js:313)
    at r.n.emit (events.js:84)
    at algoliasearch.helper.js:1245
    at n (_arrayEach.js:15)
    at r (forEach.js:37)
```
error pointing on this line:    ` resetButton.style.display = query && query.trim() ? 'block' : 'none';`.

This is my script list:
```
  <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@2.3/dist/instantsearch.min.js"></script>
  <script src="/js/algolia_search.js"></script>
  <script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
  <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>
```
I tried every possible configuration, but is doesn't matter. 

I don't have idea how to solve it. Can you help?

**Comment by Haroenv** [comment]
relevant line is https://github.com/algolia/instantsearch.js/blob/c6ac146890ee1f34c644940ff7eb5a665d594048/src/widgets/search-box/search-box.js#L126

**Comment by Haroenv** [comment]
@SchmidtDawid, can you show how you wrote the widget and templates?

**Comment by SchmidtDawid** [comment]
algolia_search.js
```
search.addWidget(
    instantsearch.widgets.searchBox({
      container: '.pw_st_search_search',
      placeholder: '',
    })
  );
```
in php template:
```
<script>
    var client = algoliasearch('correct keyi', 'correct api');
    var index = client.initIndex('correct index');
    autocomplete('.pw_st_search_search',
    { hint: true }, {
    source: autocomplete.sources.hits(index, {hitsPerPage: 5}),
    displayKey: 'name',
    templates: {
        suggestion: function(suggestion) {
          //console.log(suggestion);
          return '<span>' + suggestion._highlightResult.name.value + '</span><span>';
        }
    }
});
</script>
```
I cant show you our original input because it is too dynamically generated but with this input is the same issue:
```
<div class="aa-input-container" id="aa-input-container">
          <input type="search" id="" class=".pw_st_search_search aa-input-search" placeholder="Search " name="search" autocomplete="on" />
      </div>
```

**Comment by Haroenv** [comment]
@SchmidtDawid, here's an example on how to combine both autocomplete an instantsearch, using connectors: 

https://codesandbox.io/s/x7v977n2mz

**Comment by SchmidtDawid** [comment]
Hmm i make it work but i don't know why ;). I move this part to our header, and autocomplete start working.
```
<script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
	 <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>
	 <script>
		var client = algoliasearch('NNWYKHZ90Y', 'd052c2a715d25707636e3a29d145e9e9');
		var index = client.initIndex('prod_query_suggestions');
		autocomplete('.pw_st_search_search',
		{ hint: true }, {
		source: autocomplete.sources.hits(index, {hitsPerPage: 5}),
		displayKey: 'query',
		templates: {
			suggestion: function(suggestion) {
			  console.log(suggestion);
			  return '<span>' + suggestion._highlightResult.query.value + '</span>';
			}
			}
		});
	</script>
```
But search box stop working then. i change widget container to another class of input like this:
```
search.addWidget(
    instantsearch.widgets.searchBox({
      container: '.aa-input',
      placeholder: '',
    })
  );
```
And now work autocomplete and searching simultaneously

**Comment by Haroenv** [comment]
@SchmidtDawid did you see my comment?

**Comment by SchmidtDawid** [comment]
Yes we write comments almost in same time. I'll try your solution tomorrow because selecting autocomplete items by arrows doesn't change input value.

**Comment by SchmidtDawid** [comment]
Hi. We cant use new jquery. We still have old solutions with jquery 1.7 and some of them crashes when I use ver3.3.1. But even ignoring it for a while it doesn't work anyway, but i don't get any error. 

on start I got error like "suggestionsIndex is not defined". I do somethink like that:
```
const client = algoliasearch(opts.appId, opts.apiKey);
const suggestionsIndex = client.initIndex("just_query_suggestions");
```
I don't get any errors but search and autocomplete doesn't' work. 

Then i disconnect jquery 3.3.1 and change $ to jQuery in autocompleteWidget. Ant there is same situation. No errors and no working widget.

**Comment by Haroenv** [comment]
you need to use the [query suggestions connector](https://www.algolia.com/doc/guides/analytics/query-suggestions/) to make an index to use it for the autocomplete first @SchmidtDawid. Regarding jQuery, you’ll need to change the usage yourself in `autocompleteWidget.js`

**Comment by SchmidtDawid** [comment]
Thank you very much for helping. It helps a lot. Now autocomplete works very well :)

**Comment by Haroenv** [comment]
Awesome!
