### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by yefeiyu** [algolia/instantsearch.js#2840]
I used algolia deploy my blog, the "_include/algolia.html" 's code is copied from official website. (see the attachment below)
The search address is [https://yefeiyu.github.io/search/](https://yefeiyu.github.io/search/)
But it didn't show search box on Safari or Chrome of iOS 9.0 in iphone 6s plus, and didn't appear on `Conkeror` explorer. ([download](http://conkeror.org/FrontPage#Installation_and_Startup))

Another blog which used previous version of instantsearch.js has the same error, the address is [http://gaeblogx.com/search/](http://gaeblogx.com/search/), which github project is `SeraphRoy/SeraphRoy.github.io`
Now, I put the comparision screenshots below, 5s with iOS 10.2 vs 6s plus with iOS 9.0.

the `_pages/3search.md` is:
```
---
layout: default
title: Search
permalink: /search/
icon: search
type: page
---
<div class="page clearfix" index>
   <div class="left">
      <div id="search-searchbar">
      </div>
      <hr>

      <div id="search-hits"> </div>
      {% include algolia.html %}
   </div>
</div>
```

the `_includes/algolia.html` is as same as official website:

```
<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@2.6.0/dist/instantsearch.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/instantsearch.js@2.6.0/dist/instantsearch.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/instantsearch.js@2.6.0/dist/instantsearch-theme-alg\
olia.min.css">

<script>
const search = instantsearch({
  appId: '{{ site.algolia.application_id }}',
  apiKey: '{{ site.algolia.search_only_api_key }}',
  indexName: '{{ site.algolia.index_name }}'
});

const hitTemplate = function(hit) {
  let date = '';
  if (hit.date) {
    date = moment.unix(hit.date).format('MMM D, YYYY');
  }

  let url = `{{ site.baseurl }}${hit.url}#${hit.anchor}`;

  const title = hit._highlightResult.title.value;

  let breadcrumbs = '';
  if (hit._highlightResult.headings) {
    breadcrumbs = hit._highlightResult.headings.map(match => {
      return `<span class="post-breadcrumb">${match.value}</span>`
    }).join(' > ')
  }

  const content = hit._highlightResult.html.value;

  return `
    <div class="post-item">
      <span class="post-meta">${date}</span>
      <h2><a class="post-link" href="${url}">${title}</a></h2>
      {{#breadcrumbs}}<a href="${url}" class="post-breadcrumbs">${breadcrumbs}</a>{{/breadcrumbs}}
      <div class="post-snippet">${content}</div>
    </div>
  `;
}


search.addWidget(
  instantsearch.widgets.searchBox({
    container: '#search-searchbar',
    placeholder: 'Search into posts...'
    poweredBy: true // This is required if you're on the free Community plan
  })
);

search.addWidget(
  instantsearch.widgets.hits({
    container: '#search-hits',
    templates: {
      item: hitTemplate
    }
  })
);

search.start();
</script>
```

![811357562](https://user-images.githubusercontent.com/4845104/38007550-78aa87e6-3239-11e8-8b1b-16e2c1b22b5c.jpg)
((((((((((((((((pic.1 6s plus, iOS 9.0)))))))))))))))
![5s1](https://user-images.githubusercontent.com/4845104/38007561-8ab462e0-3239-11e8-8455-37b4705a024e.jpg)
((((((((((((((((pic.2 5s ios 10.2)))))))))))))))))))
![1992292266](https://user-images.githubusercontent.com/4845104/38007591-b388aa50-3239-11e8-8f65-f1248b67be19.jpg)
((((((((((((((((pic.3 6s plus, iOS 9.0)))))))))))))))
![5s2](https://user-images.githubusercontent.com/4845104/38007624-d3c43fd2-3239-11e8-92eb-2efb50af3717.jpg)
((((((((((((((((pic.4 5s iOS 10.2)))))))))))))))))))

The conkeror's screenshots below:
![2018-03-29](https://user-images.githubusercontent.com/4845104/38067098-744c4560-32fa-11e8-9937-7093757b02fb.png)

![2018-03-29 1](https://user-images.githubusercontent.com/4845104/38067116-89ba6058-32fa-11e8-9aca-977f0c14a151.png)

**Comment by Haroenv** [comment]
You seem to be using `  const content = hit._highlightResult.html.value;` in your code (`hitTemplate`); but some hits don't have `html`, which causes the error to show up. You should try/catch that and instead give a default value of `""`. Can you try that?

**Comment by yefeiyu** [comment]
Thank you for your answer, by I didn't know how should I do, so I put my `_include/algolia.html` up, and rewrited my question.

**Comment by Haroenv** [comment]
Sorry if that wasn't clear, I meant to change that line to: 

```js
const content = hit._highlightResult.html && hit._highlightResult.html.value || "";
```

**Comment by pixelastic** [comment]
@yefeiyu Do you have any errors in the console?

**Comment by yefeiyu** [comment]
I feel sad, it still has no effect
Although the address of the blog ends with "...../search/", it's still a `.html` page.
Is it the cause of the `instantsearch.js`?

**Comment by yefeiyu** [comment]
@pixelastic @Haroenv :
When I open [https://algolia.github.io](https://algolia.github.io), I found it has the same error!
Error appear on iOS 9 and `conkeror` explorer[conkeror download](http://conkeror.org/FrontPage#Installation_and_Startup)
![2018-03-30](https://user-images.githubusercontent.com/4845104/38128090-aae3bc68-33e8-11e8-9b87-fe157ca0d556.png)
![2092611494](https://user-images.githubusercontent.com/4845104/38128098-afc73516-33e8-11e8-841b-c4ef57665eb5.jpg)
![1946497446](https://user-images.githubusercontent.com/4845104/38128102-b279c4d6-33e8-11e8-9e58-cf5c5138dfe1.jpg)

**Comment by Haroenv** [comment]
Aha, that will help track down the issue, thanks!

**Comment by Haroenv** [comment]
@yefeiyu, you're using `const` and other modern JavaScript, which isn't supported in older browsers like you're using (conkeror and iOS 9). For that you can take a look at [babel](https://babeljs.io). 

Feel free to open a new issue or continue here if that didn't help :)
