### ISSUE TITLE
rangeSlider bug on instantsearch v2

### ISSUE THREAD

**Issue by Sewake** [algolia/instantsearch.js#2848]
Hi ! :)

I found out a bug with the rangeSlider that we can reproduce on your Tourism website example.
![image](https://user-images.githubusercontent.com/23700548/38134700-8574d17a-3414-11e8-9f28-e8c5171c7b84.png)

This problem occurs [when we change the parameters in the url](https://community.algolia.com/instantsearch.js/v2/examples/tourism/?range%5Bprice%5D=-1000%3A2200).
Note that the behaviour is working correctly [with instantsearch v1 ](https://community.algolia.com/instantsearch.js/v1/examples/tourism/?q=&hPP=12&idx=airbnb&p=0&nR%5Bperson_capacity%5D%5B%3E%3D%5D%5B0%5D=1&nR%5Bprice%5D%5B%3C%3D%5D%5B0%5D=10000&nR%5Bprice%5D%5B%3E%3D%5D%5B0%5D=-350&is_v=1), using the exact same querystring.

Also, it seems that in your Tourism website with instantsearch v2 we don't have the possibility to move the slider (neither with Chrome of Firefox), but we can with version 1.

We found out this bug from our project and we tried to see if the behaviour was the same with instantsearch v1, we are looking for a solution or we would have to go back to v1 :/
This is kinda problematic for us because we are doing a redirection with prepopulated parameters based on the querystring and it result into a broken front rangeSlider.

Thanks for your work, we are using Algolia autocomplete & instantsearch a lot and we love it !
Hello from Bordeaux :smile:

**Comment by Haroenv** [comment]
Seems like this can cause an overflow too (open that link in Safari). 

The decoded URL has `nR`: 

```js
{ person_capacity: { '>=': [ '1' ] },
  price: { '<=': [ '10000' ], '>=': [ '-350' ] } }
```

Thanks for the bug report!

**Comment by bobylito** [comment]
If the problem is only about handles that can't move, we've released a new version that fixes it. It's the 2.6.3.

As for the values. Indeed the max and min values are not restricted to the values given by the API. We should probably fix that 😅

Thanks for your patience, we'll try to fix ASAP.

**Comment by bobylito** [comment]
@Sewake can you check that now you're able to drag the handles?

**Comment by Sewake** [comment]
@bobylito We are able to drag the handles now :) Well done !

To answer the comment above, the problem was mostly about the min/max values cap. In our project we were still using v2.2.3 and we could drag the handles without any problem, so I noticed the problem only by consulting the demo site.

Thank you for your prompt response !

**Comment by bobylito** [comment]
The problem here is the definition of the proper behavior.
Is your issue visual or on the behavior side? Is the visual overflow the problem, or is it that you are setting values beyond what's in the dataset?

**Comment by Sewake** [comment]
@bobylito My problem is the visual overflow, but it's due to the fact that we try to set values beyond what's in the dataset (which isn't a problem because it doesn't actually change the hits returned by the API)

I gave 2 urls with [instantsearch v2](https://community.algolia.com/instantsearch.js/v2/examples/tourism/?q=&hPP=12&idx=airbnb&p=0&nR%5Bperson_capacity%5D%5B%3E%3D%5D%5B0%5D=1&nR%5Bprice%5D%5B%3C%3D%5D%5B0%5D=10000&nR%5Bprice%5D%5B%3E%3D%5D%5B0%5D=-350&is_v=1) and [instantsearch v1](https://community.algolia.com/instantsearch.js/v1/examples/tourism/?q=&hPP=12&idx=airbnb&p=0&nR%5Bperson_capacity%5D%5B%3E%3D%5D%5B0%5D=1&nR%5Bprice%5D%5B%3C%3D%5D%5B0%5D=10000&nR%5Bprice%5D%5B%3E%3D%5D%5B0%5D=-350&is_v=1) using the same queryset, and I would like to have the behavior of version 1.

The behavior I would like to have is to set the rangeSlider to the min value (`10$`) if the one specified in the querystring is below (`nR[price][>=][0]=-350`), and same for the max (if `nR[price][<=][0]` is above `1750$`, set the rangeSlider max value facet to `1750$`)

Also, I'm not sure, but ideally, we should define the min and the max after applying all facets others than rangeSlider ([like here](https://community.algolia.com/instantsearch.js/v1/examples/tourism/?q=&hPP=12&idx=airbnb&p=0&dFR%5Broom_type%5D%5B0%5D=Shared%20room&nR%5Bperson_capacity%5D%5B%3E%3D%5D%5B0%5D=1&nR%5Bprice%5D%5B%3C%3D%5D%5B0%5D=10000&nR%5Bprice%5D%5B%3E%3D%5D%5B0%5D=-350&is_v=1), the max value become `200$` because of the Shared Rooms filter). But I'm not sure because it might be tricky in case where we are more than one rangeSlider widget.

**Comment by bobylito** [comment]
Hi @Sewake Sorry for not getting back to you earlier. It's a tough question. Maybe @sashaprok you could help us on that :)
