### ISSUE TITLE
React native Range slider or query between two fields

### ISSUE THREAD

**Issue by ramachandranv** [algolia/instantsearch.js#2855]
My scenario is I would like to get results between two fields. I have experience_from and experience_to attributes. I want to get results between these two attributes. How would I implement a custom filter refinement to accomplish this.

In algolia we do something like below
res = index.search("query term", { "filters" => "experience_from >=1 AND experience_to <=3"})

I would like the above implementation in React native algolia instant search.

**Comment by Haroenv** [comment]
@ramachandranv, you should be able to use [`connectRange`](https://community.algolia.com/react-instantsearch/connectors/connectRange.html) for this, feel free to open a new issue in https://github.com/algolia/react-instantsearch if you have more issues about this!
