### ISSUE TITLE
Range Slider & Geo search example for react native

### ISSUE THREAD

**Issue by ramachandranv** [algolia/instantsearch.js#2856]
Could you provide a working example for rangeSlider & geo search implementation for react native

**Comment by bobylito** [comment]
Hi @ramachandranv are you using instantsearch.js or [react-instantsearch](https://community.algolia.com/react-instantsearch/)?

**Comment by ramachandranv** [comment]
Hi @bobylito I'm using [react instantsearch](https://community.algolia.com/react-instantsearch/)

**Comment by bobylito** [comment]
Can you open an issue on [react-instantsearch repo](https://github.com/algolia/react-instantsearch)?
