### ISSUE TITLE
clearRefinements in react native

### ISSUE THREAD

**Issue by ramachandranv** [algolia/instantsearch.js#2857]
For react [clearRefinements](https://community.algolia.com/react-instantsearch/widgets/ClearRefinements.html) doc is given.

How to implement the same in react native?

**Comment by bobylito** [comment]
Hi @ramachandranv this is the wrong repo. You should open an issue on [react-instantsearch](https://github.com/algolia/react-instantsearch)

**Comment by ramachandranv** [comment]
@bobylito Yup sorry.. Will do it.

**Comment by bobylito** [comment]
@ramachandranv don't be :) Thanks for participating :)
