### ISSUE TITLE
priceRanges entered as floats being truncated to integers

### ISSUE THREAD

**Issue by perlDreamer** [algolia/instantsearch.js#2858]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

In instantsearch.js 1.11.7, the priceRanges and priceRange widgets truncate manually entered values to integers.  This makes it hard to search for small values in ranges like 0.00 to 0.50.

**Bug: What is the expected behavior?**

instantsearch.js accepts manually entered numbers as integers or floats.

**Bug: What browsers are impacted? Which versions?**

All.

**Bug: What is the proposed solution?**

I don't have a patch or test case for you.  You can use the instantsearch.js example on this page to see the problem:

https://community.algolia.com/instantsearch.js/v1/documentation/#priceranges

**What is the version you are using? Always use the latest one before opening a bug issue.**

1.11.7

**Comment by Haroenv** [comment]
Just checked and this is behaving the same in v2 https://community.algolia.com/instantsearch.js/v2/widgets/priceRanges.html

**Comment by Haroenv** [comment]
reason is because of the missing `step` attribute, and because of the `parseInt` instead of `parseFloat`.

I made a small demo showing the behaviour currently and proposed change

https://codepen.io/Haroenv/pen/Ovwaoa

**Comment by Haroenv** [comment]
priceRanges no longer exists, so this likely isn't valid anymore. Please open a new issue with reproduction if you see this
