### ISSUE TITLE
refactor: autoHide should be a widget shared behavior, not a component one

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#286]
The way [autoHide is written](https://github.com/algolia/instantsearch.js/blob/7f983d0d6c592de6a091ec2dc5b5df57da151a82/decorators/autoHide.js) is "broken".

It's acknowledging that the React Components are aware of the node they are mounted to (container). While they should not know about it.

It complexifies the implementation of the autoHide feature for nothing nad restrict us to use it on widgets that are bound to react only.

We should move this decorator as a "widget" decorator (shared behavior). And maybe do the right thing => move the decorator call outside of the widget.

**Comment by pixelastic** [comment]
I've been thinking about that and what we discussed yesterday. I still feel it weird and counter-intuitive that this behavior will hide the component parent and not the component itself (moving it to a widget behavior does not change that).

For me all the `container`s we define as attributes of the widgets are placeholder where we will add our widgets. The only exception is the `searchBox` widget that can use the container directly if it's an `input`, but this is a special case and not the norm.

A usual generated markup is currently like this (react intermediate `div`s omitted for brievety).

```html
<!-- Initial placeholder -->
<div class="placeholder" id="placeholder"></div>

<!-- With widget added to it -->
<div class="placeholder" id="placeholder">
  <div class="ais-widget-name">
    <div class="ais-widget-name--foo">Foo</div>
    <div class="ais-widget-name--bar">bar</div>
  </div>
</div>

<!-- With widget added to it with a header/footer -->
<div class="placeholder" id="placeholder">
  <div class="ais-widget-name--root">
    <div class="ais-widget-name--header ais-header">Header</div>
    <div class="ais-widget-name">
      <div class="ais-widget-name--foo">Foo</div>
      <div class="ais-widget-name--bar">bar</div>
    </div>
    <div class="ais-widget-name--footer ais-footer">Footer</div>
  </div>
</div>
```

If we want to continue the BEM way and remove all styling from the widgets, we will have to remove the `display:none` inline styling that we are currently doing on the `autoHide` decorator. This means adding a `ais-hidden` with `display:none` to the element we want to hide.

If we keep following what the code is currently doing, we will add the class to the parent element, the  `<div id="placeholder">`. This is what feels broken to me. In every other widget we're only manipulating the inner HTML nodes (wrapping them, adding classes), and never the parent one. Why should this one acces elements outside of its scope?

If I call an `hideWhenNoResults: true` I would expect the widget to be hidden, not it's container. The same way that by setting a `template.header` I expect a header to be added to the widget, not to its parent. Or by setting a `cssClasses.root` I expect the class to be added to the inner root element, not its parent.

I'm not saying hiding the parent element is a bad idea, I'm saying that is not currently consistent with all our other widgets. We can choose one way or the other, but we have to stay consistent and make it clear in the doc so our users know what to expect when they specify a `container`

**Comment by bobylito** [comment]
@vvo makes me think that maybe if we want to provide such tool on the widget, maybe we should have the render and other methods for the lifecycle be more like function (return something + no side effects) in order to make them composable. Right we can't do that, since we have no about what's going in those methods.

@pixelastic interesting but I don't have a favorite yet :P

**Comment by Jerskouille** [comment]
:+1: @pixelastic

**Comment by vvo** [comment]
Moved the autoHide feature discussion to #303 to avoid us talking too much different things. This one is really only about refactoring and option name change.

**Comment by vvo** [comment]
@bobylito I guess we should be able to do high order widgets like we do for components. You could wrap a widget and have a render method that call the underlying one when necessary. Dunno if that's possible.

**Comment by bobylito** [comment]
Hard for now I think. We don't have much control over the output, which is not the case when using React.

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it
