### ISSUE TITLE
Allow combining in hierarchicalMenu

### ISSUE THREAD

**Issue by MrMooky** [algolia/instantsearch.js#2862]
Based on the v2 docs I created a menu with 1 sublevel.

![screen shot 2018-04-05 at 2 10 40 pm](https://user-images.githubusercontent.com/3603346/38365052-2a8113ca-38db-11e8-8b33-4c45bac198f2.png)

Works so far. What I'd like to accomplish now is that I can select multiple menu items together (e.g. "Experten" and "Zentren"). Is this something I can do with the current API? If so, how? I could not find anything helpful.

Also, how can I sort the lvl0 list (maybe even manually) different to the lvl1 items (need to be name:asc).

![screen shot 2018-04-05 at 2 14 20 pm](https://user-images.githubusercontent.com/3603346/38365193-aa2f927c-38db-11e8-9edf-165c881686f4.png)

**Comment by MrMooky** [comment]
That's too bad. ._. Would it be possible to define the sorting manually, though? Aside from the 4 options (count|isRefined|name:asc|name:desc)? I need this sorting: Fachbereich / Zentren / Experten / Sprechstunden

I had my PHP indexer run in this order, but as soon as the items are imported, Algolia just ignores this order.

**Comment by MrMooky** [comment]
Follow-up question here, so I don't create a new issue:

With the helper, I am setting a query manually for some items: `lotse.helper.setQuery(searchItem).search();`
Is is possible to also preselect a specific hierarchicalMenu item?

**Comment by bobylito** [comment]
You can use a function instead of an array of strings, it will let give the order of items.

Yes you can set parameters with [`toggleFacetRefinement`](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#toggleFacetRefinement)

**Comment by MrMooky** [comment]
@bobylito I tried the `toggleFacetRefinement` helper, but nothing changes. And I get no error message either. Am I doing something wrong?

`lotse.helper.toggleFacetRefinement('menu.lvl0', 'Fachbereiche');`

![screen shot 2018-04-06 at 9 12 00 am](https://user-images.githubusercontent.com/3603346/38407653-a2b47a0e-397a-11e8-9ce1-eb79a49053a6.png)

**Comment by bobylito** [comment]
Can you share a URL to your implementation? You should probably contact the Algolia support to get some help.

**Comment by MrMooky** [comment]
> Can you share a URL to your implementation?

Unfortunately not. We signed a NDA with the project owner.

> You should probably contact the Algolia support to get some help.

Because toggleFacetRefinement is not part of instantsearch.js? Will do.

**Comment by bobylito** [comment]
> Because toggleFacetRefinement is not part of instantsearch.js? Will do.

Well no but it would give you a safer space where you could exchange more code privately.

**Comment by bobylito** [comment]
Any news @MrMooky? Can I close this issue?
