### ISSUE TITLE
Padding in Pagination stops working after update  2.3->2.6.3

### ISSUE THREAD

**Issue by SchmidtDawid** [algolia/instantsearch.js#2864]
I have 2 pagination widgets on site. 

```
search.addWidget(instantsearch.widgets.pagination({
    padding: 2, 
    container: '#pagination',
    scrollTo: '.pw_st_search_search'
  }));
  search.addWidget(instantsearch.widgets.pagination({
    padding: 4,
    container: '#pagination_bottom',
    scrollTo: '.pw_st_search_search'
  }));
```
Everything works well with instantsearch 2.3, but after update to 2.6.3 i got 3 padding on both widgets and cant change it. Is it bug?

**Comment by Haroenv** [comment]
might be related to #2741. The tests are still passing though, which is weird 🤔

**Comment by Haroenv** [comment]
Any version before 2.6.0 will not have this error, so you could use those as a workaround. Thanks for reporting this @SchmidtDawid !

**Comment by SchmidtDawid** [comment]
Thank you and your welcome ;)

**Comment by samouss** [comment]
We don't pass the `padding` to the connectors in the widgets.

https://github.com/algolia/instantsearch.js/blob/f5d1ab1bcd422ae8298dfd95ca8a617385025a59/src/widgets/pagination/pagination.js#L192
