### ISSUE TITLE
Routing: support for geosearch

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2876]
**Do you want to request a *feature* or report a *bug*?**
Feature fix

**Bug: What is the current behavior?**
The geosearch connector does not support the new routing API. We should support it.

**Bug: What is the expected behavior?**
The map should be in sync with the URL when using the routing.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
TBD @samouss

**Comment by samouss** [comment]
This has been fixed since 3.0.0.
