### ISSUE TITLE
Infer browser information when the user cannot find something on a page

### ISSUE THREAD

**Issue by francoischalifour** [algolia/instantsearch.js#2882]
*When a user needs more information on a specific documentation page, he is offered to [open an issue](https://github.com/algolia/instantsearch.js/issues/new?title=I%20could%20not%20find%20what%20I%20was%20looking%20for&body=Hi!%20I%20have%20a%20documentation%20issue%20on%20InstantSearch.js,%20I%20could%20not%20find%20what%20I%20was%20looking%20for%20which%20is:%20--%20PLEASE%20FILL%20IN%20HERE%20--).*

![Open an issue image](https://user-images.githubusercontent.com/6137112/38687254-8ae1ffea-3e76-11e8-9593-fb3225efd1d8.png)

[See bottom of a documentation page](https://community.algolia.com/instantsearch.js/v2/guides/no-result.html#conclusion)

---

## The problem

The problem to me is that all issues are by default named "_I could not find what I was looking for_" __without reference to the active page__. Besides, users don't necessarily edit the title. It brings confusion because we don't know what page they come from. It's also harder to find an issue after some time.

I propose we infer a few information for them and improve the message template.

## Example

[`https://github.com/algolia/instantsearch.js/issues/new?title=I%20need%20information%20on%20"Designing%20the%20no-result%20page"&body=Hi!%20I%20have%20a%20documentation%20issue%20on%20InstantSearch.js.%20I%20could%20not%20find%20what%20I%20was%20looking%20for%20on%20the%20page%20[_Designing%20the%20no-result%20page_](https://community.algolia.com/instantsearch.js/v2/guides/no-result.html).%0A%0A%3C!--%20Describe%20what%20you're%20looking%20for%20here.%20--%3E%0A&labels=❔%20Question`](https://github.com/algolia/instantsearch.js/issues/new?title=I%20need%20information%20on%20"Designing%20the%20no-result%20page"&body=Hi!%20I%20have%20a%20documentation%20issue%20on%20InstantSearch.js.%20I%20could%20not%20find%20what%20I%20was%20looking%20for%20on%20the%20page%20[_Designing%20the%20no-result%20page_](https://community.algolia.com/instantsearch.js/v2/guides/no-result.html).%0A%0A%3C!--%20Describe%20what%20you're%20looking%20for%20here.%20--%3E%0A&labels=❔%20Question)

### Preview

> #### I need information on "Designing the no-result page"
>
> Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page [_Designing the no-result page_](https://community.algolia.com/instantsearch.js/v2/guides/no-result.html).
>
> `<!-- Describe what you're looking for here. -->`

## How

The current file is https://github.com/algolia/instantsearch.js/blob/3f040463989a754461d4237a83df35a824426ae9/docgen/layouts/archetypes/content-with-menu.pug.

### Create a unique URL per page

We have access to the `title` variable given in the [frontmatter of the article](https://github.com/algolia/instantsearch.js/blob/183bf36fcf74569e0e7d01163c63daa947c201e3/docgen/src/guides/no-result.md).

Getting the URL is trickier without JavaScript. We can recreate the URL based on the `category` variable. If we want to use JavaScript to edit the link's `href` property, we can use `location.href` to get the current page.

Codes to format the URL:

* __Space__: `%20`
* __New line__: `%0A`

### Create a new label

A new label named `Doc: question` (or something like that) could be created for:

* Filtering questions coming from users not understanding our documentation (or users needing more information on a specific page)
* Stats to measure how relevant our documentation becomes over time (fewer issues tagged with this label, the better it gets)

---

Do you think it would facilitate this kind of support in the long run?

**Comment by Haroenv** [comment]
Actually the label is usually not necessary because the title is the same, however I wonder if it would work if url encoded?
