### ISSUE TITLE
Can't correctly deploy instantsearch on GitHub pages

### ISSUE THREAD

**Issue by fedemengo** [algolia/instantsearch.js#2883]
I have been trying to fix a problem I face when using instantsearch in my Jekyll blog hosted on GitHub-pages.

I use instantsearch with infiniteHits widgets and Travis for updating the index.

The problem is that on my machine it works fine but when I push everything on GitHub and I access my search page (https://fedemengo.github.io/search/) the search bar disappear and the whole infiniteHits layout seems to break.

This is the gist of my files: https://gist.github.com/fedemengo/54d4f4ce47f09caf677fd8eb41f71334, it also encludes the working HTML produced on my machine. I used babel to avoid the problems with the new feature of js but it still doesn't work.

It's weird because on my pc works very smoothly.

**Comment by Haroenv** [comment]
Did you see any errors?

**Comment by fedemengo** [comment]
None

**Comment by fedemengo** [comment]
Now I change some things and I get the error "_[Error] SyntaxError: Unexpected end of script (anonymous function) (search:1)_"

Here is the updated code https://gist.github.com/fedemengo/223a01d75765cec49e0b31cccda7b2c9

**Comment by fedemengo** [comment]
Turns out the script get somehow formatted in just one line and a comment was responsible for commenting out a good half of the script.
