### ISSUE TITLE
Enabling routing makes Instantsearch fail in IE-11

### ISSUE THREAD

**Issue by crsw** [algolia/instantsearch.js#2884]
**Bug: Enabling routing prevents instantsearch from loading in IE-11**

**Expected the result to be similar to using urlSync: true**

**Bug only affects IE-11**

test configuration:
`var search = instantsearch({
	appId: algolia_config.appId,
	apiKey: algolia_config.apiKey,
	indexName: algolia_config.index,
	routing: true
});`

The console in IE-11 shows:
`SCRIPT438: The object does not support the property or method 'assign'
instantsearch.js (30004,7)`

**Comment by bobylito** [comment]
Hi there,

Can you [try loading polyfill.io](https://polyfill.io/v2/docs/) polyfill?

**Comment by crsw** [comment]
loading polyfill.io solves the problem, thanks.
