### ISSUE TITLE
every href should be filled with a real url and synced with the helper state (no href="#")

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#29]
Every href generated by widgets should be a "real" href instead of our classical href="#".

The goal is to have this:

```html
<a href="?p=5&query=fsaf">Next page</a>
```

Instead of:

```html
<a href="#">Next page</a>
```

This is important to tackle this for the first release, it will save us some time. Having real links is important.

We will then see how we allow configuring this (example: #p=5 instead of query string).

What do you think?

**Comment by bobylito** [comment]
Like that! Already did something similar. But we need a url manager for that :

**Comment by redox** [comment]
:+1:
