### ISSUE TITLE
CSS: Use a post-processor

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#290]
Not needed right now for the `default.css` theme, but we're going to need some better tooling when we'll start doing more advanced themes (in order to handle cross-browser compatibility) and expose some colors/spacing as variable for users to build their own themes.

This should fit in the Webpack build process.

(I thought we had an issue about it already but could not find it)

**Comment by bobylito** [comment]
Agreed! PostCss? :D

**Comment by redox** [comment]
I'm in love with SASS but happy to give a try to PostCSS. We just need to ensure the resulting CSS file is "readable" -> I assume we'll have users that just want to hack it very quickly.

**Comment by vvo** [comment]
Yes it should be readable, it seems from the people I follow that are doing a lot of CSS that postprocessors are the way to go for modern CSS stacks.

They are the babel of CSS: write real CSS using latest CSS specs and compile to CSS.

So you won't have to re-learn CSS when new CSS features are released to browsers, you already know them.

I agree it can be a shift from being good at SASS.

**Comment by Jerskouille** [comment]
I'd love stylus, but no-one loves stylus. :'(

**Comment by vvo** [comment]
> I'd love stylus, but no-one loves stylus.

This solve the question on should we use stylus (just kidding). Stylus + jade are nice indeed if you are in your own environment (not a library).

**Comment by redox** [comment]
@pixelastic we'll also need to prepare some mixins/variables/helpers to efficiently work with BEM in the CSS :)

**Comment by redox** [comment]
> Yes it should be readable, it seems from the people I follow that are doing a lot of CSS that postprocessors are the way to go for modern CSS stacks.

I was speaking about the generated CSS of PostCSS, not the source :)

**Comment by vvo** [comment]
Both should be readable, it's just CSS. Since there's no nesting it should not go crazy

**Comment by redox** [comment]
I'll do a proposal with SASS

**Comment by redox** [comment]
We'll start with the working SASS version, open to move to PostCSS in the future.

**Comment by pixelastic** [comment]
Do we really want to use Sass and not Scss? Scss is Sass new generation. I personnally have much more experience with Scss and really prefer the new syntax. Scss is also retro-compatible with CSS so it will make building themes for non-experts much more easier.

**Comment by redox** [comment]
> Do we really want to use Sass and not Scss?

@Shipow and myself prefer SASS but I don't care that much. I'm just afraid we spend soooo much time on choosing a preprocessor, updating themes from one format to another, updating documentation. Just use the one you want and let's move forward.

**Comment by Shipow** [comment]
I'm ok with scss ofc

**Comment by pixelastic** [comment]
> I'm just afraid we spend soooo much time on choosing a preprocessor, updating themes from one format to another, updating documentation, etc...

Yeah, that was I was thinking as well. When you suggested Sass I did not even think you would go for Sass and not Scss, but as this already was a long discussion I'm ok with just picking something and build.

**Comment by redox** [comment]
> Yeah, that was I was thinking as well. When you suggested Sass I did not even think you would go for Sass and not Scss, but as this already was a long discussion I'm ok with just picking something and build.

Just go for it if it takes 15min @pixelastic, SCSS is definitely fine. As you said, removing curly braces is definitely a rubyist problem :)
