### ISSUE TITLE
Toggle refinement not working after facetFilters initialization

### ISSUE THREAD

**Issue by mfbx9da4** [algolia/instantsearch.js#2901]
**Do you want to request a *feature* or report a *bug*?**
bug

**Bug: What is the current behavior?**
Initial search filters 

```js
  searchParameters: {
    page: 0,
    hitsPerPage: 100,
    disjunctiveFacetsRefinements: {
      is_popular: [true, 'true'],
      is_full: [false, 'false']
    },
....
```
The above works as expected. Hits are filtered correctly. 

However, following this clicking on one of the prefiltered toggles e.g. `is_full` does not filter the search. 

Here is an example toggle filter setup

```js
search.addWidget(
  instantsearch.widgets.toggle({
    container: '#refinement-list4',
    attributeName: 'is_popular',
    label: 'Is Popular',
    values: {
      on: true
    },
    templates: {}
  })
)
```

Note if I remove initial filtering from the config the toggles work as expected. 

Here is a live demo:
http://sfhotevents.ml/

**Bug: What is the expected behavior?**
- Initial filters applied on first page load
- Toggles should work e.g. clicking `Is not full` see http://sfhotevents.ml/

**Bug: What browsers are impacted? Which versions?**
all, all

**Bug: What is the proposed solution?**
not sure

**Feature: What is your use case for such a feature?**
Have an initial facet refinement which can be removed by the user via toggles
http://sfhotevents.ml/

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
not sure

**What is the version you are using? Always use the latest one before opening a bug issue.**
https://cdn.jsdelivr.net/npm/instantsearch.js@2.3/dist/instantsearch.min.js

**Comment by Haroenv** [comment]
the source of that site: https://github.com/mfbx9da4/hotevents

**Comment by bobylito** [comment]
@mfbx9da4 you're initializing the disjunctive facets with two values. Can you try with only the strings and a single value?

**Comment by mfbx9da4** [comment]
Hi Still waiting on an answer. Help would be much appreciated. The site is back up. Thanks

**Comment by mfbx9da4** [comment]
Using one value and only strings as suggested I get zero results. 

![image](https://user-images.githubusercontent.com/1690659/39624545-a7bc940a-4f91-11e8-9367-d9d1a36a7f23.png)

Using one value and only booleans like so:
![image](https://user-images.githubusercontent.com/1690659/39624538-a265a3a2-4f91-11e8-95f7-b10f351294c2.png)

I get the following error:

![image](https://user-images.githubusercontent.com/1690659/39624537-9e7fe590-4f91-11e8-807e-610597325b84.png)

Although I do get results but they are not filtered as expected and the widgets appear mangled

![image](https://user-images.githubusercontent.com/1690659/39624795-875f539a-4f92-11e8-88b2-d40647669dbf.png)

Not using any initial configuration the filtering / toggling widgets work correctly but I need an initial filtering for my use case.

Starting to feel that instantsearch comes with too much magic. Is there a web client for doing all refinement myself?

Thank you for reading

**Comment by bobylito** [comment]
@mfbx9da4 I've contacted you directly through the Algolia support to help us further investigate what's going on here :) I'll reopen this ticket if we find an actual bug :)

**Comment by bobylito** [comment]
Here are two samples I've made:
- [reproducing the original issue](http://workable-camera.surge.sh/)
- [with the issue fixed](http://cut-song.surge.sh/)

In order to fix the issue, you need to only use a single value for the filter and use the string form of the value like so:

```js
var search = instantsearch({
  // Replace with your own values
  appId: 'JTH1JDTDFT',
  apiKey: '1d8e2d4aa2a19623ee5fc10fb0d85f83', // search only API key, no ADMIN key
  indexName: 'test-is-toggle',
  searchParameters: {
    disjunctiveFacetsRefinements: {
      "is-popular": ["true"],
    }
  }
});
```
