### ISSUE TITLE
connectCurrentRefinedValues should not display values min / max of connectRange

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#2909]
**Do you want to request a *feature* or report a *bug*?**

BUG

**Bug: What is the current behavior?**

When we provide min / max to `RangeSlider` (aka `connectRange`) those values are displayed in `CurrentRefinedValues`(aka `connectCurrentRefinedValues`) even when the user doesn't refine.

![screen shot 2018-04-30 at 14 50 29](https://user-images.githubusercontent.com/6513513/39427920-e02904b8-4c85-11e8-939c-87e748f91826.png)

Live version with [CodeSandbox](https://codesandbox.io/s/74w8yn6590).

**Bug: What is the expected behavior?**

Since those values are not "really" refined they should not appear.

**Bug: What is the proposed solution?**

It might be interesting to leverage the new API `getWidgetState ` combine with mapper to generate the list of refinements for `connectCurrentRefinedValues` (similar to what React InstantSearch does).

**What is the version you are using? Always use the latest one before opening a bug issue.**

2.7.1

**Comment by francoischalifour** [comment]
This is fixed with [`currentRefinements`](https://www.algolia.com/doc/api-reference/widgets/current-refinements/js/) and [`connectCurrentRefinements`](https://www.algolia.com/doc/api-reference/widgets/current-refinements/js/#connector) in v3.
