### ISSUE TITLE
setting the pagination number

### ISSUE THREAD

**Issue by Asahro** [algolia/instantsearch.js#2911]
I am in use algolia and search in the documentation about pagination but i didn't find it.
can we change the default show number of pagination from 7 to be 5 ?
other than maxPages

**Comment by Haroenv** [comment]
Hey @Asahro,

You can use [`padding: 2`](https://community.algolia.com/instantsearch.js/v2/widgets/pagination.html#struct-PaginationWidgetOptions-padding) in the widget options of pagination.

```js
search.addWidget(
  instantsearch.widgets.pagination({ 
    padding: 2, 
  })
);
```

**Comment by Asahro** [comment]
thanks
