### ISSUE TITLE
Uses urlSync

### ISSUE THREAD

**Issue by Asahro** [algolia/instantsearch.js#2916]
sorry for my bassic question.
I am in tryin to use urlSync lin in this demo https://preview.algolia.com/instantsearch/
I had try it but it didn't work like the sample.
this my code

```js
var search = instantsearch({
  urlSync: true,
  searchParameters: {
        hitsPerPage: 12,
    },
});

search.addWidget(
  instantsearch.widgets.refinementList({
    container: '#refi',
    attributeName: 'refi',
    operator: 'and',
    limit: 10,
    templates: {
      item: facetTemplateCheckbox2,
      header: ''
    }
  })
);
```

when I click the refi list it isn't add in url like ?dFR[refi][0]=195 and when I write the url with that the filter didn't checked. but the data has filtering. is there any worses in my code?

**Comment by Asahro** [comment]
Its Solved,
Thank.
by the way is there any way I can change the url code

**Comment by Haroenv** [comment]
hey, to change the url in code you can use the extended usage of the `routing` parameter (replaces `urlSync`. See the [guide](https://community.algolia.com/instantsearch.js/v2/guides/routing.html) about that. 

Feel free to ask more info if needed
