### ISSUE TITLE
How to implement such a widget with categories

### ISSUE THREAD

**Issue by a-kolesnikova** [algolia/instantsearch.js#2918]
Good afternoon. Please tell me how to implement such a widget with categories. There must also be an opportunity clear current refined values. 
![screenshot from 2018-05-11 14-51-23](https://user-images.githubusercontent.com/20166763/39923533-b9ca9ade-552c-11e8-8e66-1cf89d196163.png)

**Comment by samouss** [comment]
Hi, to implement the list you can use the [`RefinementList`](https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html) widget. To clear all the active refinements, you can use the [`ClearAll`](https://community.algolia.com/instantsearch.js/v2/widgets/clearAll.html) widget.

**Comment by a-kolesnikova** [comment]
Thanks for the answer. Can I implement a multi-level menu of this kind using the RefinementList widget?

**Comment by samouss** [comment]
The widget [`HierarchicalMenu`](https://community.algolia.com/instantsearch.js/v2/widgets/hierarchicalMenu.html) is designed to built such experience.
