### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by dimsav** [algolia/instantsearch.js#2920]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: how to use the render function in the [refinementList widget](https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html#struct-Widget)

From my understanding in the docs, this is what I should do:

```
search.addWidget(
        instantsearch.widgets.refinementList({
          container: '#tags-filter',
          attributeName: 'categories',
          render: function(foo){
            console.log(foo);
          }
        })
      );
```

However the render method is never executed.

Thank you 🙂

**Comment by Haroenv** [comment]
This might be an error in the documentation. The render method is for the [connector](https://community.algolia.com/instantsearch.js/v2/guides/customization.html) of the refinement list. That documentation is available at the page for [`connectRefinementList`](https://community.algolia.com/instantsearch.js/v2/connectors/connectRefinementList.html)

**Comment by bobylito** [comment]
I'm not sure how we can help here. Closing this for now.
