### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by dimsav** [algolia/instantsearch.js#2921]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: 

If we want to display the facet filters like the picture below, how can we get the values of the widgets after each time the results are rendered?

<img width="401" alt="image 2018-05-13 at 21 34 38" src="https://user-images.githubusercontent.com/1785686/39971071-9645125e-56f5-11e8-9927-4fb71aeb931f.png">

Thank you

**Comment by Haroenv** [comment]
You can use the [`currentRefinedValues`](https://community.algolia.com/instantsearch.js/v2/widgets/currentRefinedValues.html) widget for that!

**Comment by dimsav** [comment]
Thank you @Haroenv :-)
