### ISSUE TITLE
Decouple transformations from template

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2927]
When using the hits template, we have two transformations/templates that can't be used together: item and allItems. For example if you use an item template, you can't use the allItems transformation. 

The user can't know why it doesn't work, therefore we should make sure that this is possible.

However the problem is that the transformation is backed into the template component. If the transformation was part of the connectors, and set at precise rendering steps we would be able to document them more easily or even in the case of the hits drop the items transformation.

**Comment by Haroenv** [comment]
Would also be useful for the other InstantSearch flavours!

**Comment by bobylito** [comment]
> Would also be useful for the other InstantSearch flavours!

Yes indeed that would help with the standardization of the InstantSearch API over the different projects.

**Comment by Haroenv** [comment]
This has been solved with transformItems & removal of transformData in v3
