### ISSUE TITLE
duplicated inifinite hits with slow network

### ISSUE THREAD

**Issue by iam4x** [algolia/instantsearch.js#2928]
**Describe the bug 🐛**
When using the infinite hits widget on a slow network, clicking `show more` button may load duplicated hits.

**To Reproduce 🔍**
1. Go to https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=InfiniteHits.default
2. Force your network settings to a slow network (example 3G)
3. Click on "Show more"
4. Scroll down to the hits
5. See the duplicated entries

**Expected behavior 💭**
Do not load/display duplicated hits.

**Screenshots 🖥**
![image](https://user-images.githubusercontent.com/893837/40123967-be468a1a-5927-11e8-937d-f2ce455f17cc.png)

**Environment:**
Slow network

**Comment by bobylito** [comment]
Render is called if there are new results and if the search is stalled.  There are no checks in the implementation that prevents this new rendering: https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/infinite-hits/connectInfiniteHits.js#L105-L133 (This is a working hypothesis for now, I will double check)
