### ISSUE TITLE
Error: requiring unknown module "undefined" when app does not have internet

### ISSUE THREAD

**Issue by dereknelson** [algolia/instantsearch.js#2931]
**Describe the bug 🐛**
When the app is disconnected from any network, trying to import anything from `react-instantsearch/connectors` results in the app crashing with the following error message: 

**To Reproduce 🔍**

1. Import anything from `react-instantsearch/connectors`
2. Disconnect device from internet
3. Crash 

**Expected behavior 💭**
The app not to crash when using algolia's functions without internet

**Environment:**
 - OS: [e.g. iOS / mac / android]
 - Version 4.4.1

Screenshot: http://prntscr.com/jj9arb

**Comment by Haroenv** [comment]
Is this with React Native? Which version of RN are you using?

**Comment by Haroenv** [comment]
could you also give a reproduction @dereknelson ?

**Comment by dereknelson** [comment]
@Haroenv working on a repro, here's a relevant screenshot: http://prntscr.com/jlcnzl

**Comment by Haroenv** [comment]
Seems indeed that it’s related to that specific version of React Native and something that can be fixed by using a different. Version

**Comment by bobylito** [comment]
What's the status here @Haroenv ?

**Comment by Haroenv** [comment]
This should be fixed in React Native. If an upgrade or downgrade of the RN/ metro bundler version you're using doesn't fix it, please open a new issue with reproduction on [react-instantsearch](https://github.com/algolia/react-instantsearch/issues/new)
