### ISSUE TITLE
Filter by time

### ISSUE THREAD

**Issue by Asahro** [algolia/instantsearch.js#2934]
in my index has field contain time (yyyymmdd)
example( 20180518 )
can i filter the data by the time, example in one week from now  ( 20180518 - 20180525 ) using refinementList like this.

![image](https://user-images.githubusercontent.com/24727474/40228069-720eb5de-5aba-11e8-9232-a7d8ce0bc826.png)

**Comment by bobylito** [comment]
The best way to handle this is format your data as numeric. [This guide](https://community.algolia.com/instantsearch.js/v2/guides/calendar-widget.html) should give you some elements to get started.
