### ISSUE TITLE
clear searchbox button doesn't work !

### ISSUE THREAD

**Issue by mahdi-gh1373** [algolia/instantsearch.js#2936]
I have two instantsearch like this and  create one search box to search both of of them together.

```
var searchProduct = instantsearch({
  appId: '...',
  apiKey: '...', 
  indexName: 'market_products'
});

var searchShop = instantsearch({
  appId: '...',
  apiKey: '...',
  indexName: 'market_shops'
});

var searchBox = instantsearch.widgets.searchBox({
  container: '#searchBox2',
  placeholder: 'جستجو'
});

searchProduct.addWidget(searchBox);
searchShop.addWidget(searchBox);

```

when I want to clear search box the button works for **product** but it doesn't clear value for **shop**.
it seems that shop query doesn't work. what should I do ?

**Comment by mahdi-gh1373** [comment]
any help ?

**Comment by bobylito** [comment]
Hi there,

You can't reuse the same searchbox for two instances of InstantSearch. If you want to synchronize two InstantSearch together, you can follow [this example](https://jsfiddle.net/j9nwpz34/27/).

**Comment by mahdi-gh1373** [comment]
Thanks @bobylito , I write my code like this but I get error : 

> Uncaught TypeError: Cannot read property 'setQuery' of null
    at InstantSearch.searchFunction [as _searchFunction] (search.js:53)
    at AlgoliaSearchHelper.helper.search (instantsearch.js:13075)
    at InstantSearch.start (instantsearch.js:13089)
    at search.js:423

my code : 
```
var searchProduct = instantsearch({
  appId: 'RVCNA1DDA9',
  apiKey: '532a4f251441b704869f852da6616386', // search only API key, no ADMIN key
  indexName: 'market_products'
});

var searchShop = instantsearch({
  appId: 'RVCNA1DDA9',
  apiKey: '532a4f251441b704869f852da6616386', // search only API key, no ADMIN key
  indexName: 'market_shops',
  searchFunction: function(helper) {
    var query = searchShop.helper.state.query;
    searchProduct.helper.setQuery(query);
    searchProduct.helper.search();
    helper.search();
  }
});


// shared search box2
var searchBox2 = instantsearch.widgets.searchBox({
  container: '#searchBox2',
  placeholder: 'جستجو',
  reset: {
    template:'<img src="search/images/greenMultiply2.png" style="position: absolute;top: 20px;width: 25px;height: auto;left: 5px;" alt="">' }
});

searchShop.addWidget(searchBox2);
```

What should I do now?

**Comment by bobylito** [comment]
The helper in instantsearch is initialized after the start and the searchFunction is triggered during the start. Therefore, given the code you showed, you should start `searchProduct` before `searchShop`.

**Comment by mahdi-gh1373** [comment]
Thanks @bobylito It's working now.
