### ISSUE TITLE
Can I have custom reset button for searchbox?

### ISSUE THREAD

**Issue by mahdi-gh1373** [algolia/instantsearch.js#2937]
I need custom reset button to reset my searchbox. How can I have that?  I want write my own button for that.

**Comment by samouss** [comment]
You can use the `reset` option on the `SearchBox`. You can specify a custom template for this. You can find more informations about that [in our documentation](https://community.algolia.com/instantsearch.js/v2/widgets/searchBox.html#struct-SearchBoxResetOption).

**Comment by mahdi-gh1373** [comment]
Thanks @samouss , Is there any way that another button trigger reset ?

**Comment by Haroenv** [comment]
You can use the `connectSearchBox` connector if you want to customise it even further, or use the `clearAll` widget with `clearsQuery: true`

**Comment by mahdi-gh1373** [comment]
thanks @Haroenv  I will check that.
