### ISSUE TITLE
setting bottom price for dynamic price ranges

### ISSUE THREAD

**Issue by hilkeros** [algolia/instantsearch.js#2940]
Hi! I have a documentation issue on InstantSearch.js, I could not find what I was looking for which is: -- PLEASE FILL IN HERE --

I understand that the price ranges in the price ranges widget are set dynamically. However, this can give a rather ugly bottom price, especially because we are basically a high price range shop. But we have less expensive products too.

It would be cool to set 50 as the bottom price.

**Comment by bobylito** [comment]
Have you tried the [numeric refinement list](https://community.algolia.com/instantsearch.js/v2/widgets/numericRefinementList.html)?

**Comment by bobylito** [comment]
@hilkeros does this widget answers your need?

**Comment by hilkeros** [comment]
Hi Alex

Sorry for the long wait. I tried it out and it seems to be a good solution.
Thanks!

2018-05-30 16:13 GMT+02:00 Alex S <notifications@github.com>:

**Comment by bobylito** [comment]
Thanks @hilkeros Happy coding :)
