### ISSUE TITLE
Calendar widget

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#295]
Is calendar widget something that could be in the library at some point ? I have a magento customer that ask it. I am not sure it make sense for magento but for wordpress it will probably be needed anyway.

**Comment by pixelastic** [comment]
This is something that can be useful, for sure. I'm not sure I'd like this as part of the core widgets (a calendar library is a project by itself).

Maybe we should just provide the default widget that will work with HTML5 date elements, and show a few examples of plugging external calendar libraries (jQuery, etc).

**Comment by maxiloc** [comment]
Yes html5 date element is indeed a good idea.

**Comment by Shipow** [comment]
Actually I think a widget able to do numerical refinement and manipulate/display date from timestamp should be in the core widgets to address all the media/news use cases.
If we talk about predefined range, it also make sens to propose a manual range where the calendar seems to be the right UI elements.

This could be the really mandatory widget:
![screenshot 2015-10-18 21 55 22](https://cloud.githubusercontent.com/assets/976175/10609358/972d2a06-7743-11e5-94e8-0700731f7564.png)

**Comment by Shipow** [comment]
the html5 calendar is really poor and don't really allow to select range in a fun or intuitive way.

**Comment by vvo** [comment]
This can be done in an "external" widget (community)

**Comment by maxiloc** [comment]
I am currently writing an API proposal, I am ok to write it afterwards. I will need that anyway
