### ISSUE TITLE
Field value for cssClasses Item

### ISSUE THREAD

**Issue by codetopixels** [algolia/instantsearch.js#2960]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[refinementList](https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html)".

Is it possible to get the field value and assign this to the "item" cssClasses?

So for example;
 cssClasses: {
      list: 'nav nav-list',
      count: 'badge pull-right',
      active: 'active',
      item: {{field value}}
    }

Thanks.

**Comment by bobylito** [comment]
Unfortunately this is not possible. I will our product team know about it :) Thanks for your contribution.
