### ISSUE TITLE
Question on the page "hits"

### ISSUE THREAD

**Issue by neeteshpersonal** [algolia/instantsearch.js#2991]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[hits](https://community.algolia.com/instantsearch.js/v2/widgets/hits.html)".

I am using hit-template for results, but i am unable to apply condition. If record does not contain profile_image then my view gets disturb. How to use image thumbnail if profile_image does not exist.
Hits widget: 
search.addWidget(
  instantsearch.widgets.hits({
    container: '#hits',
    templates: {
      item: document.getElementById('hit-template').innerHTML,
      empty: "<div class='alert alert-info alert-margin'>We didn't find any results for the search <em>\"{{query}}\"</em></div>"
    }
  })
);
Hit Template:

		<a href="/search/{{x_id}}">
			<img src="{{profile_image}}" class="" style="margin-bottom: 0px;">
		
			<div class="caption">
				<p class="hit-name"><strong>{{{profile_name}}}</strong></p>
				<p class="hit-name">Age: {{{age}}} </p>
				<p><button class="btn btn-success btn-block btn-fill">View Profile</button></p>
			</div>
		</a>

**Comment by Haroenv** [comment]
Could you post your complete template please @neeteshpersonal ? 

```html
{{#profile_image}}
<img ...
{{^profile_image}}
````

this should work AFAICT, but to really help, a complete template is necessary

**Comment by neeteshpersonal** [comment]
Thanks for the reply, now I am using the custom widget for the condition. And it works for me. 
Any alternate way is always welcome.

**Comment by Haroenv** [comment]
Nice to hear you got it solved. My previous comment should be another way of solving it.
