### ISSUE TITLE
How use custom Query for filter facet ?

### ISSUE THREAD

**Issue by mahdi-gh1373** [algolia/instantsearch.js#2995]
I want to have my filter list and when I click on one of them query the facet . Is there any way to do that ?
I have a refinementlist that list my facets but I need another menu to query into facets.

**Comment by Haroenv** [comment]
Hey @mahdi-gh1373 do you mean [`searchForFacetValues: true`](https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html#struct-RefinementListWidgetOptions-searchForFacetValues)? I'm not sure if I completely understand the use case you had in mind. Maybe a small diagram would do wonders?

**Comment by mahdi-gh1373** [comment]
Hi @Haroenv , 
![12](https://user-images.githubusercontent.com/9510009/41086688-08e3f3e4-6a50-11e8-90f6-1397a8d2bc61.png)
I have a nav menu like this. each of SubCat items are my facets.I want to filter my result when I click on each of them.

**Comment by Haroenv** [comment]
For that you can make your own version of a [hierarchical menu](https://community.algolia.com/instantsearch.js/v2/widgets/hierarchicalMenu.html) using [`connectHierarchicalMenu`](https://community.algolia.com/instantsearch.js/v2/connectors/connectHierarchicalMenu.html). Read more about how to use the connectors in [this guide](https://community.algolia.com/instantsearch.js/v2/connectors.html)

**Comment by mahdi-gh1373** [comment]
Thanks @Haroenv  I will check that.
