### ISSUE TITLE
Reset of the searchbox in slow network

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2997]
**Describe the bug 🐛**
In slow network, the use input in the searchbox is reset if the user type before the search is started.

It seeems to be related to https://github.com/algolia/instantsearch.js/blob/c6ac146890ee1f34c644940ff7eb5a665d594048/src/widgets/search-box/search-box.js#L75-L77

This only happens on IE11.

**To Reproduce 🔍**
1. Go to https://community.algolia.com/instantsearch.js/v2/examples/e-commerce/
2. Simulate a bad network (on macos x you can use the network link conditioner)
3. Reload the page
4. Type in the searchbox as soon as the searchbox is visible
5. The searchbox is reset, but the search is done with what the user has typed

**Expected behavior 💭**
The searchbox should be consistent with the search, and best would be that the searchbox is not reset.

**Environment:**
 - OS: windows
 - Browser: IE
 - Version: 11

**Comment by Haroenv** [comment]
🤔 Do you know why we initially even had that event?

**Comment by bobylito** [comment]
> 🤔 Do you know why we initially even had that event?

To handle BFCache... I need to investigate further. It might be unrelated.

**Comment by bobylito** [comment]
It is very hard to reproduce. I could reproduce it a few times and now I can't. Because I don't feel confident in testing that any changes in the codebase would fix the behavior. If someone can reproduce that confidently then we can test if removing the BFcache related code will actually fix the issue.

The code is here https://github.com/algolia/instantsearch.js/tree/fix/2997

**Comment by bobylito** [comment]
Let's close this for now. If you are able to reproduce or have more infos, I'd be happy to reopen and dig further :)
