### ISSUE TITLE
Fix demos for IE11

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#3001]
**Describe the bug 🐛**
Demos do not work on IE11 and the solution we provide is not good enough (using polyfill.io)

However a user offered us a solution: everything is detailed in this [post](https://discourse.algolia.com/t/no-search-result-with-ie11-solved/5391). 

Let's fix that.

**Comment by bobylito** [comment]
@cforbesywam is it a problem that occurs when you are using polyfill.io?

**Comment by cforbesywam** [comment]
No I believe it is an issue related to instantsearch using Promises which IE11 does not support.  polyfill.io would be one way of fixing the issue.  I'm sorry I haven't done a lot of digging into this.  I only know that if I try to use the 'searchFunction' to do a multi index search it generates the 'Promise' error in IE11 but it doesn't do it in Chrome.  IE11 is fine as long as I don't use the 'searchFunction'.  However as soon as I try to use / define a 'searchFunction' IE11 starts producing the error and the search no longer functions as expected.

**Comment by bobylito** [comment]
> polyfill.io would be one way of fixing the issue

Actually we only support IE11 through the use of a polyfill, and we recommend polyfill.io.

**Comment by cforbesywam** [comment]
Ok - Thank you - polyfill.io works correctly as does instantsearch using a searchfunction in IE11 when polyfill.io is loaded.
