### ISSUE TITLE
Instantsearchjs v2 natural sort facets

### ISSUE THREAD

**Issue by spindriftwebs** [algolia/instantsearch.js#3002]
I have an issue where I am displaying a list of values in a hierarchical menu. The values are for example:

5ft
5ft 1 Inch
5ft 2 Inches
5ft 10 Inches

However, the sort order in incorrect as I am getting:

5ft
5ft 1 Inch
5ft 10 Inches
5ft 2 Inches

I have this existing sort function:

sortBy: function(a, b) {
return parseInt(a.name, 10) - parseInt(b.name, 10);
},

However, this is not sorting naturally. Is there a way with InstantSearch that I can get the order of these values displaying in the correct order, in a natural way ?

Any help would be much appreciated - thanks in advance.

Guy

**Comment by vvo** [comment]
Hi Guy, this repository is for bugs only, I did reply to you on discourse though. Thanks!
