### ISSUE TITLE
Restrict search hits base on one field

### ISSUE THREAD

**Issue by mahdi-gh1373** [algolia/instantsearch.js#3003]
I want to know how I can restrict hits to doesn't show if `isConfirmed` equal to zero
How I can do that?

**Comment by Haroenv** [comment]
Hey @mahdi-gh1373, 

```js
search.addWidget(
  instantsearch.widgets.configure({
    filters: 'isConfirmed > 0',
  });
);
```

Configure is a widget you can use to add arbitrary filters to the search without displaying it in any way.

Please reopen if that wasn't what you expected
