### ISSUE TITLE
Analytics IP filter

### ISSUE THREAD

**Issue by SchmidtDawid** [algolia/instantsearch.js#3004]
Is it possible to filter IP's from analytics? 
We don't want to collect data from our workers.

**Comment by Haroenv** [comment]
You can add `analytics: false` to the searchParameters if you know it's a certain user that shouldn't be counted. 

See [the doc](https://www.algolia.com/doc/api-reference/api-parameters/analytics/?language=javascript).

For more general questions you can contact support@algolia.com :)
