### ISSUE TITLE
soryBySelector is not sorting entries on the Front end.

### ISSUE THREAD

**Issue by mdunbavan** [algolia/instantsearch.js#3008]
I have setup a replica indice in Algolia dashboard as per what has been written on the algolia documentation.

![screen shot 2018-06-20 at 10 04 54](https://user-images.githubusercontent.com/671281/41648664-76114a40-7471-11e8-9774-f1ec1d3e4254.png)

On seeing the filter/sort in the frontend I go to click filter on Price high or price low and nothing happens, I have even checked the console and nothing is happening on the algolia api calls.

![screen shot 2018-06-20 at 10 06 46](https://user-images.githubusercontent.com/671281/41648739-aca15fdc-7471-11e8-941c-25ed7111b8bc.png)

https://viaduct.frb.io/products/bedroom-furniture

What I would expect to see is the items filtering

 - OS: mac
 - Browser chrome/safari/firefox
 - Version latest

Here is my code for the functionality:

```
		var searchProducts = instantsearch({
		  // Replace with your own values
		  appId: 'NHF40KMICV',
		  apiKey: '91615faeab7c9c7e761f22279d5d1513', // search only API key, no ADMIN key
		  indexName: 'www.viaduct.co.uk_allProducts',
		  urlSync: false,
		  searchParameters: {
    		hitsPerPage: 500
  		  }
		});

	// types.level2.title

	if( $('#types').length ){
		searchProducts.addWidget(
		  instantsearch.widgets.refinementList({
		    container: '#types',
		    attributeName: 'types.level2.title',
		    operator: 'or'
		  })
		);
	}
	if( $('#selectedFilters').length ){
		searchProducts.addWidget(
		  instantsearch.widgets.currentRefinedValues({
		    container: '#selectedFilters',
		    onlyListedAttributes: true,
			attributes: [{name: 'types', label: 'Types'},{name: 'types.level2.title', label: 'Type'},{name: 'productPrice', label: 'Price'},{name: 'material', label: 'Material'}],
		    clearAll: 'after'
		  })
		);
	}
	if( $('#price-refinement').length ){
		searchProducts.addWidget(
			instantsearch.widgets.sortBySelector({
			    container: '#price-refinement',
			    indices: [
			    	{ name: 'www.viaduct.co.uk_allProducts', label: 'Price' },
			      	{name: 'products_by_price_low', label: 'Price lowest'},
			      	{name: 'products_by_price_high', label: 'Price highest'}
			    ],
			    label: 'Price'
			  })
		);
	}
```

**Comment by Haroenv** [comment]
I can see requests being done, is the sort by different in the dashboard if you go to the different indices?

**Comment by mdunbavan** [comment]
Hmm really @Haroenv

**Comment by Haroenv** [comment]
Would it be possible to make a minimal reproduction in CodeSandbox and give access to your index for Algolia employees on your dashboard? Will be useful in finding what's going on here.

**Comment by mdunbavan** [comment]
Would it be possibly because the value we are sorting by is a string not an integer?

**Comment by mdunbavan** [comment]
![screen shot 2018-06-20 at 12 09 54](https://user-images.githubusercontent.com/671281/41654916-e2482042-7482-11e8-928e-14e05037b354.png)

**Comment by Haroenv** [comment]
Yes, to be able to sort on numbers it definitely needs to be a  number, otherwise the sorting is alphabetical

**Comment by mdunbavan** [comment]
Ah crap is there a way I can transform that data in the dashboard of Algolia or do I need to reupload all indexes?

**Comment by Haroenv** [comment]
Unfortunately there's no way to change that in the dashboard :(

**Comment by mdunbavan** [comment]
@Haroenv so I've changed the numbers to be integers like so:

![screen shot 2018-06-20 at 16 32 55](https://user-images.githubusercontent.com/671281/41668607-9e01779c-74a7-11e8-9196-e761e3741812.png)

I've added the correct attribute to sortBy in the Ranking for the main indice but in the replicas it does not seem to order/reorder by price here

![screen shot 2018-06-20 at 16 34 09](https://user-images.githubusercontent.com/671281/41668712-e1c9067a-74a7-11e8-939e-c2ab15090c29.png)

The js code has not changed at all from above and it still doesn't work:

https://viaduct.frb.io/products/bedroom-furniture

**Comment by Haroenv** [comment]
So looking at the requests it seems like they are actually completely correct (different results), but it doesn't update visually. What does your `hit` code look like? I guess it's custom.

**Comment by bobylito** [comment]
@mdunbavan any update? Thanks :)
