### ISSUE TITLE
Cannot Open Second hierarchicalMenu

### ISSUE THREAD

**Issue by Asahro** [algolia/instantsearch.js#3009]
I am trying to use this function but its did'nt work well,
I don't know why,it always show blank data themplate when i click the second layer hierarchicalMenu.
this my index
![image](https://user-images.githubusercontent.com/24727474/41706497-39b27c0e-7566-11e8-9dad-5029d08e93e0.png)
my code
![image](https://user-images.githubusercontent.com/24727474/41706579-58aa8700-7566-11e8-8636-07c00ce013e0.png)

can some body help me?

**Comment by bobylito** [comment]
Hi @Asahro any chance you could give a reproducible example?

**Comment by Asahro** [comment]
you can acces it in this url https://asahro.ukmindonesia.ga/cari-kamus-kbli

**Comment by Asahro** [comment]
i have found the solution. thank

**Comment by bobylito** [comment]
Thanks. Let us know if you have other feedback :)
