### ISSUE TITLE
Allow to configure NoUISlider "step" option in rangeSlider widget

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#301]
I have a dataset where numerical attribute are integers from 1 to 99 so I would like to avoid decimal in the slider's tooltip.

![image](https://cloud.githubusercontent.com/assets/976175/10615905/b9159cba-7762-11e5-9413-4cee08715956.png)

TODO:
- [ ] create the "step" option in rangeSlider, default to 1 unit
- [ ] pass the step option down to the NoUiSlider call in the Slider component

**Comment by bobylito** [comment]
Cool idea. Would it make sense to have this behavior as a separate widget?

**Comment by Jerskouille** [comment]
I would say it makes sense as a parameter, like `padding` for the pagination widget.

**Comment by vvo** [comment]
Yes :+1: it should be as easy as passing the "step" option from the widget to the NoUiSlider component: https://github.com/algolia/instantsearch.js/blob/73678b0d4277d0c3aef27e2c2d4fe4094a2e49f3/components/Slider/index.js

**Comment by vvo** [comment]
Moved to #307
