### ISSUE TITLE
Question on the page "rangeSlider"

### ISSUE THREAD

**Issue by nicogominet** [algolia/instantsearch.js#3016]
Hi,
I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[rangeSlider](https://community.algolia.com/instantsearch.js/v2/widgets/rangeSlider.html)".

I believe it is not possible to do a numeric filtering on an object key value for which I have a `rangeSlider`. Let's say this is the document stored in algolia:
```
{
  name: "product",
  price: 22,
  values: {
    length: 56,
    width: 34
  },
  objectID: "1"
}
```
`price > 20` works perfectly, but I cannot seem to do a `values.width > 30` for instance (I tried this on the dashboard as well).

Is there any way around this or all numeric filters have to be top level?

**Comment by bobylito** [comment]
Hi @nicogominet, thanks for opening the issue.

I could make it work [here](https://codesandbox.io/s/1r7pp6kk4). One thing is that you need to facet the value. In this case, you need to add `values` to the attributes for faceting.

Maybe I missed something, feel free to add more details.

**Comment by nicogominet** [comment]
Hi @bobylito , that's strange I tried `values`, even `values.width` yesterday and now but it doesn't work for me 🤔 

I mean even query using the dashboard query params in the interface doesn't return any [results](https://s33.postimg.cc/ke0ml2hjz/search_results.jpg) but I've got at least this [one matching product](https://s33.postimg.cc/a3y7ltjyn/products.jpg).

Let me know if I'm missing something please.

**Comment by nicogominet** [comment]
Yes, it's doing the same with the `Poids` attribute.

**Comment by bobylito** [comment]
Can you try to reproduce the issue on codesandbox ([we have a template here](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/InstantSearch.js)) using your dataset so we can have a look ?

**Comment by nicogominet** [comment]
I was able to [reproduce it here](https://codesandbox.io/s/3y5577p211) @bobylito .
Thanks

**Comment by nicogominet** [comment]
Yes you're right, I thought I checked that before but the quotes are a light grey and my eyes didn't catch it.
Sorry about that and thanks for the support!
