### ISSUE TITLE
Question on the page "hits"

### ISSUE THREAD

**Issue by sandipbhuyan** [algolia/instantsearch.js#3018]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[hits](https://community.algolia.com/instantsearch.js/v2/widgets/hits.html)".

I want to integrate instantsearch in Symfony 3 framework. I am facing a problem while rendering the hit results. The hit widget use `{{}}` to access the hit results and symfony use twig frontend engine in which `{{}}` is a default accessor for accessing data. So how can I change the configuration of hit result template to access the hit results

**Comment by bobylito** [comment]
If I understand correctly you need the raw twig tag : https://stackoverflow.com/a/6587888
