### ISSUE TITLE
Update the infinite hits guide to use the connector.

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#3020]
**Describe the bug 🐛**
The [guide in the doc](https://www.algolia.com/doc/tutorials/search-ui/instant-search/infinite-scroll/instantsearchjs/) is implemented as a custom widget.

**Expected behavior 💭**
It should be implemented using the connector because:
 - the connector hides part of the complexity, using it would make it easier to grasp
 - we want to promote connectors over custom widgets when possible

**Additional context**
The `render` can be tricky as it is triggered both when the search comes back or the search is considered stalled.

**Comment by Haroenv** [comment]
The guide has been updated!
