### ISSUE TITLE
Should autoHide hide the container or the inside of the container

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#303]
@pixelastic said:

>I've been thinking about that and what we discussed yesterday. I still feel it weird and counter-intuitive that this behavior will hide the component parent and not the component itself (moving it to a widget behavior does not change that).
>
>For me all the containers we define as attributes of the widgets are placeholder where we will add our widgets. The only exception is the searchBox widget that can use the container directly if it's an input, but this is a special case and not the norm.
>
>A usual generated markup is currently like this (react intermediate divs omitted for brievety).
>
>
><div class="placeholder" id="placeholder"></div>
>
>
><div class="placeholder" id="placeholder">
>  <div class="ais-widget-name">
>    <div class="ais-widget-name--foo">Foo</div>
>    <div class="ais-widget-name--bar">bar</div>
>  </div>
></div>
>
>
><div class="placeholder" id="placeholder">
>  <div class="ais-widget-name--root">
>    <div class="ais-widget-name--header ais-header">Header</div>
>    <div class="ais-widget-name">
>      <div class="ais-widget-name--foo">Foo</div>
>      <div class="ais-widget-name--bar">bar</div>
>    </div>
>    <div class="ais-widget-name--footer ais-footer">Footer</div>
>  </div>
></div>
>If we want to continue the BEM way and remove all styling from the widgets, we will have to remove the display:none inline styling that we are currently doing on the autoHide decorator. This means adding a ais-hidden with display:none to the element we want to hide.
>
>If we keep following what the code is currently doing, we will add the class to the parent element, the <div id="placeholder">. This is what feels broken to me. In every other widget we're only manipulating the inner HTML nodes (wrapping them, adding classes), and never the parent one. Why should this one acces elements outside of its scope?

>If I call an hideWhenNoResults: true I would expect the widget to be hidden, not it's container. The same way that by setting a template.header I expect a header to be added to the widget, not to its parent. Or by setting a cssClasses.root I expect the class to be added to the inner root element, not its parent.

>I'm not saying hiding the parent element is a bad idea, I'm saying that is not currently consistent with all our other widgets. We can choose one way or the other, but we have to stay consistent and make it clear in the doc so our users know what to expect when they specify a container

**Comment by vvo** [comment]
@Jerskouille said :+1: @pixelastic

**Comment by vvo** [comment]
As for the autoHide option. Right now I would rename it to autoHideContainer to be specific and move on.

Whereas its best to hide the container or what is inside we will experiment the option on a larger scale and see if it realy bring any issue the way it is right now.

good?

**Comment by pixelastic** [comment]
Good for me. We'll see with integrations how this goes.

**Comment by bobylito** [comment]
:+1:

**Comment by pixelastic** [comment]
@vvo: Where exactly would you like to rename to `autoHideContainer` ?

The documentation of every widget already says that ` * @param  {boolean} [hideWhenNoResults=true] Hide the container when there's no results`. Do you suggest we rename the decorator to `autoHideContainer` directly? Would work for me.

**Comment by vvo** [comment]
Yes I find it more explanatory no?

**Comment by pixelastic** [comment]
Yep, I was just checking if you were refering to renaming `hideWhenNoResults` to `hideContainerWhenNoResults`.

**Comment by vvo** [comment]
Ok we rename the option for now in #326 and move on. If there's a need for another option to hide the inside, we'll see then
