### ISSUE TITLE
menuSelect Widget: hide when only one option (other than seeAllOption)

### ISSUE THREAD

**Issue by davist11** [algolia/instantsearch.js#3031]
**Describe the bug 🐛**
When using a `menuSelect` widget, if there is only one option (other than the `seeAllOption`), this widget should be hidden since selecting that single option is the same as selecting the `seeAllOption`

**To Reproduce 🔍**
1. Add a `menuSelect` widget that will only have one option
2. See that selecting that option is the same as the `seeAllOption`

**Expected behavior 💭**
If there is only one option other than the `seeAllOption` this widget should be hidden.

**Screenshots 🖥**
<img width="315" alt="screen shot 2018-07-11 at 11 36 38 am" src="https://user-images.githubusercontent.com/199985/42583330-ba04bea6-84fe-11e8-9e6f-b95522d2a707.png">

**Comment by bobylito** [comment]
Thanks for the feedback. We're actually looking for revamping the conditions for the autohideContainer feature.

**Comment by davist11** [comment]
Is there any timeline for v3.0?

**Comment by bobylito** [comment]
Not at the moment @davist11

**Comment by davist11** [comment]
👍 

do you have any suggestions for how to handle this issue with the current version?

**Comment by bobylito** [comment]
The most straightforward and hacky way would be to use the helper, listen to the result event, check if there is only one value returned and hide the container of your menu:

```js
const search = instantsearch(/* config */);
// ...
search.start();
search.helper.on('result', (results) => {
  const values = results.getFacetValues('yourMenuFacet');
  if(values.length <= 1) hide();
  else show();
});
```

https://community.algolia.com/algoliasearch-helper-js/reference.html#SearchResults#getFacetValues

**Comment by davist11** [comment]
Awesome, thank you.

For reference for anyone else who needs something like this, I had to update the conditional like so:

```js
if (Array.isArray(values.data) && values.data.length <= 1) {
    hide()
} else {
    show()
}
```

**Comment by francoischalifour** [comment]
Since InstantSearch.js 3, you can use the `panel` widget like this:

```js
const brandSelectWithPanel = instantsearch.widgets.panel({
  hidden: ({ results }) => results.getFacetValues('brand').data.length <= 1,
})(instantsearch.widgets.menuSelect);

search.addWidget(
  brandSelectWithPanel({
    container: '#brand-list',
    attribute: 'brand',
  })
);
```
