### ISSUE TITLE
Question on the page "Designing the no-result page"

### ISSUE THREAD

**Issue by deepakgurung** [algolia/instantsearch.js#3033]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[Designing the no-result page](https://community.algolia.com/instantsearch.js/v2/guides/no-result.html)".

How do I show the popular searches in the No Result page?

**Comment by bobylito** [comment]
You could use the [analytics API](https://www.algolia.com/doc/rest-api/analytics/) but it's not meant for heavy traffic. So if you find a way to cache those results in your backend, you could serve them in your front-end.

The short answer is that we do not provide such feature at the moment.
