### ISSUE TITLE
Question on the page "infiniteHits"

### ISSUE THREAD

**Issue by sg-modlab** [algolia/instantsearch.js#3034]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[infiniteHits](https://community.algolia.com/instantsearch.js/v2/widgets/infiniteHits.html)".

How do I control the number of hits that are shown with the infiniteHits widget?

**Comment by samouss** [comment]
You have two possible solution to control the number of the hits. The first solution is to use the widget [`HitsPerPageSelector` ](https://community.algolia.com/instantsearch.js/v2/widgets/hitsPerPageSelector.html)it will display a select that lets the user control how many hits are displayed. But in case you don't want to let the user choose you can use the [`Configure`](https://community.algolia.com/instantsearch.js/v2/widgets/configure.html) widget. 

```jsx
search.addWidget(
  instantsearch.widgets.configure({
    hitsPerPage: 8,
  })
);
```

**Comment by samouss** [comment]
There is no difference but the former will be deprecated at some point for the latter.

**Comment by sg-modlab** [comment]
Confused — which is the former?

**Comment by Haroenv** [comment]
Searchparameters in the constructor will be deprecated at some point, configure widget will continue to exist

**Comment by sg-modlab** [comment]
Perfect, ty
