### ISSUE TITLE
Question on the page "menu"

### ISSUE THREAD

**Issue by mchao** [algolia/instantsearch.js#3035]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[menu](https://community.algolia.com/instantsearch.js/v2/widgets/menu.html

Hi-  Would it be possible for us to have two sets of filters for our search results? That is, use two menus at the same time on different facets?

**Comment by mchao** [comment]
And to clarify... This is what we're using:  https://community.algolia.com/react-instantsearch/connectors/connectMenu.html

**Comment by samouss** [comment]
Not sure to perfectly understand your issue. You can have as many menus as you want on a different facets. Here is an example:

```jsx
<div>
  <Menu attribute="brand" />
  <Menu attribute="categories" />
</div>
```

**Comment by Haroenv** [comment]
Samuel answered for React InstantSearch, but for IsntantSearch.js the same counts:

```js
search.addWidget(customMenu(...));
search.addWidget(customMenu(...))
```
