### ISSUE TITLE
Multiple search inputs collision

### ISSUE THREAD

**Issue by neeteshgupta95** [algolia/instantsearch.js#3040]
I have two input field that searches. First for text search, second search by zip code.
I have added a custom widget for the second input field for search, and I use helper.search(); for manually search.

Steps: 
Search result by zipcode => Click on result => click back browser button => I found first input field filled with zip code that I searched for the second input.
That is because query=98072 going internally and when I hit back button it comes back in URL and filled automatically. Please suggest me a solution either send "query" and "q" as the parameter or stop URL filled automatically.

**Comment by francoischalifour** [comment]
If I understand correctly, you would like InstantSearch to not fill the URL when the search state changes.

To do so, remove the options [`urlSync`](https://community.algolia.com/instantsearch.js/v2/instantsearch.html#struct-InstantSearchOptions-urlSync) or [`routing`](https://community.algolia.com/instantsearch.js/v2/instantsearch.html#struct-InstantSearchOptions-routing) that you may have in your [InstantSearch declaration](https://community.algolia.com/instantsearch.js/v2/instantsearch.html#usage).

**Comment by neeteshpersonal** [comment]
After removing the routing true from InstantSearch declaration, I still face issue the text of second input reaches to the first input. I am facing this issue because I am using two text input for search. Is there any way to use two input field for search efficiently. Or suggest me a solution to search results by zip code and text-based.

**Comment by francoischalifour** [comment]
Could you please reproduce what you currently have on [this template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js) and send the link back here?

It will make it easier to understand the problem and to help you fix it.

**Comment by neeteshpersonal** [comment]
Hi, friend.
Could you please help me. I have added my code to this template: https://codesandbox.io/s/lpnjk4p77m
If I click on view profile then if I hit back browser button then zip code automatically misplaced please help me.

**Comment by neeteshpersonal** [comment]
Hi, friend.
Could you please help me. I have added my code to this template: https://codesandbox.io/s/2vvz5q8nrn
If I click on view profile then if I hit back browser button then zip code automatically misplaced please help me. I want to keep my search history of the zip code in the text field if I hit back button after clicking to results.
