### ISSUE TITLE
MenuSelect max limit of 1000?

### ISSUE THREAD

**Issue by davist11** [algolia/instantsearch.js#3043]
**Describe the bug 🐛**
We have a menuSelect widget with a limit of `10000`, but it appears that `1000` is the max (although I couldn't find it documented anywhere)

**Expected behavior 💭**
I would expect it to respect whatever value passed into the limit option.

**Environment:**
 - OS: macOS High Sierra 10.13.5
 - Browser: chrome
 - Version: 67.0.3396.99

**Comment by Haroenv** [comment]
With this big of a number, `searchable` on the normal Menu widget would make more sense IMO. Then you can use the connector to make it into a `<select>` again quite easily.

You can try changing the `maxValuesPerFacet` ([doc](https://www.algolia.com/doc/api-reference/api-parameters/maxValuesPerFacet/?language=javascript)) option in the settings of the index, but it could also be an API limitation.

I'd like to see what kind of UI you're making where it makes sense to have 10k items in a single `<select>`

**Comment by bobylito** [comment]
Hi @davist11 and thanks for opening this issue. Facets are actually limited to 1000 elements https://www.algolia.com/doc/api-reference/api-parameters/maxValuesPerFacet/?language=javascript#how-to-use

From there, as @Haroenv said, the best would be to have a search in those values. 10k is a lot of values for a user to browse, and it's a lot of data to send on the network too (which makes the reactivity worse). With a search, you can have less values and still let your user access all of them.

The current problem is that menu (or menu select) does not support searchable / search for facet values. But the [refinement list](https://community.algolia.com/instantsearch.js/v2/widgets/refinementList.html) does, can you try with that widget and see if it could fit what you want?

**Comment by davist11** [comment]
It's actually not 10k, it's slightly over the 1000 limit, but I was trying to bump it so that we could never run into the problem again. Sounds like we should really go back and figure out the UX potentially for such a large filter.

**Comment by davist11** [comment]
If there is no plan to increase the limit, then yup.

**Comment by bobylito** [comment]
> If there is no plan to increase the limit, then yup.

The limit is on the engine side. I'm asking :)

**Comment by bobylito** [comment]
No plan at the moment, but we did provide the feedback to them :)
