### ISSUE TITLE
Get union of items when using multiple disjunctiveFacetsRefinements

### ISSUE THREAD

**Issue by shramee** [algolia/instantsearch.js#3044]
**Is your feature request related to a problem? Please describe 🙏**
Okay... so my case scenario is that I want to get all items (posts) which are either in a particular category or in a particular tag... I thought disjunctive facets would sort the issue for me... but they don't. Only posts that have one of the specified category *AND* one of the specified tags are returned.

**Describe the solution you'd like 🤔**
To solve this, would like union not intersection of all disjunctive facet refinements... i.e. All items that have any of the specified tags `UNION` all of the items that have any of the specified categories.

**Describe alternatives you've considered ✨**
Well, I have tried disjunctive facets 🙃

**Additional context**
Trying to replace WooCommerce' related product algorithm with Algolia instant search using current product's categories/tags.

**Comment by bobylito** [comment]
Thanks @shramee for opening  this issue. Unfortunately it's not possible for the moment. I'm forwarding your request to our product team.

**Comment by bobylito** [comment]
Hey @shramee I've reread your question and I'm wondering if you want to build a UI for the selection of filters or if it's gonna be a single request to fetch some recommendation?

**Comment by mthuret** [comment]
Hi @shramee, I think in your case you can leverage the `filters` search parameters to display those recommendations as its syntax is more permissive. 
You can find the documentation of that search parameters here: https://www.algolia.com/doc/api-reference/api-parameters/filters/
