### ISSUE TITLE
Hide the parent hierarchicalMenu when another parent choosen

### ISSUE THREAD

**Issue by Asahro** [algolia/instantsearch.js#3046]
is there any whay to hide the first parent in hierarchicalMenu ?
I try 
showParentLevel: false, 
but it just hide the second and else parent, but the first will always show.

**Comment by Asahro** [comment]
I aredy find the way, thank you

**Comment by Haroenv** [comment]
Awesome that you found it, sorry for not having answered yet. For future reference, could you write what you did to solve it? 

Have a nice day!

**Comment by Asahro** [comment]
I just using rander to check klick event and using simpel class css setting with js when the click happent
