### ISSUE TITLE
Question on the page "connectAutocomplete"

### ISSUE THREAD

**Issue by swann1444** [algolia/instantsearch.js#3048]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[connectAutocomplete](https://community.algolia.com/instantsearch.js/v2/connectors/connectAutocomplete.html)

I can't find any example... The link seems to be dead. In the documentation, we are talking about connectAutocomplete and CustomAutocompleteWidgetOptions but I don't understand what am I supposed to do with it... Any example of working code might be great. 

Thanks!

**Comment by Haroenv** [comment]
There's some examples here: https://community.algolia.com/instantsearch.js/v2/dev-novel/?widgets=jquery&selectedStory=Autocomplete.default, which have their code here: 
https://github.com/algolia/instantsearch.js/blob/develop/dev/app/jquery/stories/autocomplete.stories.js

**Comment by Haroenv** [comment]
Glad you found your solution there @swann1444 :) We are aware that this is still not super obvious and will make it more straightforward to use in the future

**Comment by swann1444** [comment]
Thank you, I will try to analyse how this example does the job. That is right something like tuto/snippets might be cool.
