### ISSUE TITLE
How should we version the themes?

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#305]
Should the themes have their own versionning or follow the version of the library? This is an open question, I'm not sure how to handle that.

Maybe following the main lib version, only updating the minor/patch depending on the severity of the CSS fix in a theme.

**Comment by vvo** [comment]
Once the theme is done we can only do css bug fixing indeed, or add new features (so minor/patch will have to be updated on instantsearch.js).

If we plan on completely revamping a theme then it might be named awesome.theme.v2.css. Or even a new theme name

**Comment by pixelastic** [comment]
Works for me. Keeping the same package will make things easier.
