### ISSUE TITLE
Move from DevNovel to Storybook

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3051]
In the next major release Storybook (v4 still in alpha) will support [HTML application](https://github.com/storybooks/storybook/blob/master/docs/src/pages/basics/guide-html/index.md). It can be a good opportunity to move our showcase from [DevNovel](https://github.com/algolia/dev-novel) to Storybook to leverage the community & plugins of Storybook. It also brings consistency across our different flavours since React & Vue are already on Storybook. 

Related https://github.com/algolia/angular-instantsearch/issues/226

**Comment by bobylito** [comment]
Good idea. Maybe it's worth considering the actual benefits of the community and plugins. Do you already have in mind some that would be great addition to the current experience? Do you know if plugins have restrictions based on the environment?

**Comment by bobylito** [comment]
One pro, dev-novel maintenance burden is completely on us and it would be better to have one less project to maintain (even we don't really do it)
