### ISSUE TITLE
Ability to customize pagination links

### ISSUE THREAD

**Issue by stinkysGTI** [algolia/instantsearch.js#3052]
Is there some way I can customize the pagination links? I didn't see anything in the options.

I found this and tried implementing it, but it breaks the entire results page:

https://community.algolia.com/instantsearch.js/v2/connectors/connectPagination.html

The following error is thrown: `Uncaught TypeError: Cannot read property 'map' of undefined`

**Comment by Haroenv** [comment]
This works for me in an isolated environment: https://codesandbox.io/s/lpv4ro78rq can you make a sandbox which throws that error please?

**Comment by stinkysGTI** [comment]
Hmm. Seems to be conflicting with something on the page then. No issue with the script
