### ISSUE TITLE
Avoid to rely on shouldComponentUpdate in component

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3056]
**Describe the bug 🐛**

The stats widget re-renders only when the `nbHits` or `processingTimeMS` changes. It can lead to issue when you are using the page number in the template for example. When you click on the next page with the Pagination widget only the page value changed not the other ones. The shouldComponentUpdate (sCU) function of the widget will return false and so prevent the re-render.

https://github.com/algolia/instantsearch.js/blob/33fa09835df8678085cb7f382b4973eaa1f9b20f/src/components/Stats/Stats.js#L9-L14

**To Reproduce 🔍**

1. Go to https://codesandbox.io/s/l51or5k9lz
2. Click on the pagination
4. Stats widget is not updated

**Expected behavior 💭**

We should trigger the re-render. The quick fix is to add more values inside the condition. But do we really need the sCU hook on those components? To have a better idea we can track the effect on the performance with / without the hook.

**Comment by bobylito** [comment]
What is SCU @samouss ?

**Comment by samouss** [comment]
I've update the title and the description.

**Comment by bobylito** [comment]
I'd go for removing the hook, as it is a very straightforward solution. If we find evidence that this particular widget is causing performance issues, we can work on it then.
