### ISSUE TITLE
Bad Interaction between Refinement List Search and Show More/Less

### ISSUE THREAD

**Issue by tim-reynolds-visionet** [algolia/instantsearch.js#3064]
**Describe the bug 🐛**
We are using the Magento 2 module for integrating Algolia but this issue is not limited to that. It exists in the core of your code. 
If you create a refinement list widget that has both a showMore/limit configuration and a searchForFacetValues configuration, the showMore/limit feature breaks as soon as any text is entered into the search box. 

**To Reproduce 🔍**
1. Create a refinementList widget
2. Define a limit (5) and a showMore (limit 10, template doesn't need to be defined)
3. Define a searchForFacetValues (placeholder can be anything, not important)
4. Load this in the browser.
5. Type anything into the search box, then remove the text there (type a, then hit backspace)
6. Try clicking on the "Show More" text at the bottom of the refinement. Nothing happens.

See this sandbox:
https://codesandbox.io/s/r4wxknv32n
The Show More/Show Less link works just fine until you perform a search. 

**Expected behavior 💭**
After removing the search text the show more and show less links should work again. 

**Additional context**
In the Magento 2 module we note that when you hit Show more, the searchForFacetValues box becomes disabled, and when you hit Show Less it becomes re-enabled. I didn't see that happening in the Codesandbox I linked. But in both environments I can see that once you type a single letter in the search box the event handler for clicking on the Show More/Show Less gets removed. I think this is a similar thing to what I saw with the search box. One thing is attempting to disable the other.

**Comment by bobylito** [comment]
Thanks @tim-reynolds-visionet and thank you very much for your thorough report.

**Comment by tim-reynolds-visionet** [comment]
@bobylito My pleasure. If and when this is fixed, and the M2 module is upgraded, is it unreasonable to request that the unminified version of algoliaBundle.js be included in the module? Switching to that would have made diagnosing this and other issues a lot easier for us. Just a thought.

**Comment by cloakedninjas** [comment]
Spotted this just now, but with a different replication path... If you use: https://instantsearchjs.netlify.com/stories/?selectedKind=RefinementList&selectedStory=with%20show%20more&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

- Observe the filter limit is 3
- Click show more
- enter enough chars into the search box to reduce filters, e.g. `samsungasd`

You will see `Show less` remains even though only 3 filters are present

This is my +1 ... hopefully someone can fix this soon :)

**Comment by Haroenv** [comment]
Thanks for pinging here too. Indeed this is an error in behaviour. For now I’d say the best course of action is to give a bigger limit and no showMore if you’re using searchable. Since you commented here, you’ll be notified when we close this
