### ISSUE TITLE
Star widget renders even when it shouldn't

### ISSUE THREAD

**Issue by thekar22** [algolia/instantsearch.js#3065]
**Describe the bug 🐛**
Come to our attention that when rendering a star widget; if there are no facet values associated, the widget still shows whereas all other facet widgets do not render.

**To Reproduce 🔍**
1. Create a facet for rating
2. Create a set of records where none of them have the facet value for rating
3. Create a star widget in instantsearch.js
4. Observe that the widget is visible even though there should be no associated facet values with the given search.

**Expected behavior 💭**
The widget should hide itself

**Comment by Haroenv** [comment]
This is likely since it's built up mostly on its own, and not based on the index data? I suspect a bug in `autoHideContainer` (you don't have that set to `false` right?)

**Comment by bobylito** [comment]
Thanks for opening the issue @thekar22. However I'm not sure how to reproduce it. I've tried with our demo here: https://community.algolia.com/instantsearch.js/v2/examples/media/ Do you have a link with a demo where it fails as you describe?
