### ISSUE TITLE
Allow debouncing image loading on hit templates

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#307]
Following #302, it seems that in some situations we could allow users to debounce the image loading.

One solution:

`hits({container, lazyloadImages})`

On the implementation side:
- Users will have to use `ais-src=real-src.jpg` on images + `src={helpers.lazySrc}`
- We listen to onload on main hits container
- If onload element === img && img.ais-src => load the image in 100ms
- If newsearch before 100ms, discard all previous images
- We can use classes and shit to allow displaying images with fadein fadeout

I think we should not try to lazyload for now (only load what's visible), this is a harder topic to include as an API

**Comment by bobylito** [comment]
That's not what I meant. You don't differ the whole rendering but only part of it (the image). This is a very special use case, hence it should be a special widget not an option.

**Comment by redox** [comment]
> You don't differ the whole rendering but only part of it (the image)

Yes I would definitely try to only debounce the images loading, it generally produces a nice visual effect with a bit of CSS3.

**Comment by vvo** [comment]
Ok I updated the issue with the discussions we had @pixelastic @redox and @bobylito after understanding what you meant. This should be doable :)

**Comment by pixelastic** [comment]
@redox: Something like that: http://slides.iamvdo.me/parisweb14/#/27 ?

**Comment by redox** [comment]
> @redox: Something like that: http://slides.iamvdo.me/parisweb14/#/27 ?

I was just thinking about a fade effect but if our users want to implement that, why not :) Not sure it's the ideal UX for e-commerce :p

**Comment by vvo** [comment]
Fadein is ok if image loading takes a lot of time, otherwise instant loading is better :)

**Comment by vvo** [comment]
Moving to #333
