### ISSUE TITLE
Question on the page "toggle"

### ISSUE THREAD

**Issue by lionel218** [algolia/instantsearch.js#3073]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[toggle](https://community.algolia.com/instantsearch.js/v2/widgets/toggle.html)".

How can I use toggle change event?
The toggle widget have not any callback event?

**Comment by bobylito** [comment]
Hi @lionel218, thanks for opening this issue. InstantSearch.js does not provide event listener per widget. But you can listen to changes of the search state using:

```js
const search = instantsearch(yourConfig);
search.start();
search.helper.on('change', (state) => {
  // here you can see the values of the search parameters
})
```

If you give us the use case, we might be able to give your a more specific answer.

**Comment by lionel218** [comment]
Hi @bobylito ,  Thanks for your kind response.
That is working well.

**Comment by Haroenv** [comment]
Feel free to open a new issue if you have any more questions!
