### ISSUE TITLE
Question on the page "connectPagination"

### ISSUE THREAD

**Issue by mvnnn** [algolia/instantsearch.js#3074]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[connectPagination](https://community.algolia.com/instantsearch.js/v2/connectors/connectPagination.html)".

How to implement pagination in ReactNative using connectPagination?

**Comment by bobylito** [comment]
Hi @mvnnn thanks for opening this issue. Have you tried using [react-instantsearch](https://community.algolia.com/react-instantsearch/Getting_started_React_native.html) rather that instantsearch.js? We have a [demo here](https://github.com/algolia/react-instantsearch/tree/master/examples/react-native)

**Comment by mvnnn** [comment]
I want to build Pagination like this.
![image](https://user-images.githubusercontent.com/12225578/44536182-8314ce80-a719-11e8-90fe-fea4bfb30819.png)

but it's seems like "connectPagination" have only support for next pages, It's supported previous page ?. Can you provide some example code for that.

**Comment by bobylito** [comment]
This contains a full implementation of a pagination using the connector:

https://community.algolia.com/instantsearch.js/v2/connectors/connectPagination.html#example

**Comment by kubido** [comment]
```javascript 
const InfiniteHits = ({ hits, hasMore, refine }) => {
  return <FlatList
    data={hits}
    keyExtractor={item => item.objectID}
    onEndReached={() => refine()}
    renderItem={({ item }) => (
      <CardItem hit={item} />      
    )}
  />
}
export const ConnectedHits = connectInfiniteHits(InfiniteHits);
`

in my case refine didn't work ? the function exists but not updating the results
