### ISSUE TITLE
Auto chang width using classes

### ISSUE THREAD

**Issue by Asahro** [algolia/instantsearch.js#3076]
I am trying to change width when one of filter click, I uses 
`var elements = document.getElementsByClassName("ais-hits--item");
           for (var i = 0; i < elements.length; i++) {
                elements[i].style.width="50%";
           }`

but always the last hit card didn't get update setting
![image](https://user-images.githubusercontent.com/24727474/44502563-4f578b80-a6bc-11e8-9f0e-c7e4380e4cae.png)
I dont know why, can you help me

**Comment by Asahro** [comment]
I have found the isues is because it render last datas,
thank you

**Comment by bobylito** [comment]
Ok cool @Asahro. Feel free to open new issues or give us any feedback :)
