### ISSUE TITLE
Error message of connector or widget only explains what the proper usage is, not what you used

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#3078]
**Is your feature request related to a problem? Please describe 🙏**
When I make a mistake, I often don't know what I _did_ pass

**Describe the solution you'd like 🤔**
The error message contains the parameters I passed

**Describe alternatives you've considered ✨**
Not specifically

**Additional context**
This happened when making Vue InstantSearch

**Comment by bobylito** [comment]
Yep agreed I have the same issue. We should step up our error message game here 🔥

**Comment by Haroenv** [comment]
(in this case it was accidentally passing a boolean to `showMoreLimit`)

**Comment by Haroenv** [comment]
Our error messages now link to the docs, and no longer have this issue as far as I can tell
