### ISSUE TITLE
Question on the page "Getting started"

### ISSUE THREAD

**Issue by JamesVanWaza** [algolia/instantsearch.js#3080]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[Getting started](https://community.algolia.com/instantsearch.js/v2/getting-started.html)".

**I am unable to initialize instant search.js**
- Steps I have done so far, add instantsearch.js, instantsearch.min.css, and instantsearch-theme-algolia.css in my index.html file. 

The Page does not show up when I run the page. 

My files, showing how I have done it so far. 
<img width="2560" alt="screen shot 2018-08-23 at 10 19 56 pm" src="https://user-images.githubusercontent.com/4000076/44561441-e1927a80-a722-11e8-9ee9-db4f34d07ce9.png">

The app.js file 
<img width="2560" alt="screen shot 2018-08-23 at 10 22 56 pm" src="https://user-images.githubusercontent.com/4000076/44561500-21596200-a723-11e8-839c-eeaa003164ce.png">
<img width="2560" alt="screen shot 2018-08-23 at 10 22 59 pm" src="https://user-images.githubusercontent.com/4000076/44561501-21596200-a723-11e8-8b42-10c5f93980e1.png">

**Comment by Haroenv** [comment]
In the beginning of `app.js` you're creating the `const search` two times, which will throw an error because you can't reassign `const` declarations. There's also a stray `2` there. 

This is likely what's going wrong. If you have more issues, please make a [codeSandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js)

**Comment by JamesVanWaza** [comment]
@bobylito   @Haroenv I removed the const second time but no luck. Do you have tutorials showing how to set it up? 

Your Sandbox is not working as well.

**Comment by Haroenv** [comment]
<img width="1440" alt="screen shot 2018-08-27 at 09 00 10" src="https://user-images.githubusercontent.com/6270048/44661125-a66ca180-a9d7-11e8-944b-96f63bef4633.png">


Sorry for closing, that was an accident. I see the example working perfectly. Which browser & OS are you trying this on? Could you try to give your code on a place where I can try it out as well, either via codeSandbox, or on GitHub?

The guide for getting started is [here](https://community.algolia.com/instantsearch.js/v2/guides/usage.html)

**Comment by JamesVanWaza** [comment]
@Haroenv 
Chrome 68
MacOS HighSierra

I created a sandbox here below https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js 

Test and see which file or item is missing.

**Comment by Haroenv** [comment]
That works perfectly for me, also on that version of Chrome. Did you try the standalone view? https://xo94wl403z.codesandbox.io/

Also, what was the result of following the regular getting started guide?

**Comment by JamesVanWaza** [comment]
Locally the page is blank but the standalone site is working perfectly. 

Can I send my zipped project so you can review?

**Comment by Haroenv** [comment]
sure, you can put it on a GitHub repository, so I can make a change recommendation directly

**Comment by JamesVanWaza** [comment]
This is my exact layout on desktop https://github.com/JamesVanWaza/algolia-instantsearch-demo

**Comment by Haroenv** [comment]
Hey @JamesVanWaza, I did https://github.com/JamesVanWaza/algolia-instantsearch-demo/pull/1 as a suggestion, but otherwise it works completely for me. You might have a different problem set up on your computer?

**Comment by JamesVanWaza** [comment]
@Haroenv it now works, The duplicate was the problem. Thank You so much for the help.

**Comment by Haroenv** [comment]
glad we got to the bottom of this, and sorry that it took so long!

**Comment by JamesVanWaza** [comment]
@Haroenv did you update the instantjs demo to use version 2.10.1
