### ISSUE TITLE
connectRefinementlist: hasExhaustiveItems is not documented

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#3083]
I don't know what `hasExhaustiveItems` does, since it's not in the documentation. Something to do with search for facet values I think

**Comment by bobylito** [comment]
Yes it indicates that the list of elements that you get are exhaustive. This mean that even though you could search, all the values that you could search for are already in the list.

**Comment by Haroenv** [comment]
Is that related to search for facet values?

**Comment by Haroenv** [comment]
This is still not documented in the new documentation.

**Comment by francoischalifour** [comment]
Before documenting `hasExhaustiveItems` (and probably other params), I think we should wait to migrate the connector to TypeScript so we have a stable API for the params. WDYT?
