### ISSUE TITLE
Don't assume the facet is available on results

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3084]
**Describe the bug 🐛**

Some of the connectors (at least `connectMenu` & `connectRefinementList` & `connectToggle`) assume that: at the render phase the provided attribute is a retrievable facet without checking that it actually exist (see below). Most of the time it is available, but it might happen that it doesn't. When it doesn't the helper will throw the following error: `FACET_NAME is not a retrieved facet.`.

https://github.com/algolia/instantsearch.js/blob/831c70bb93ddb47f09d8710a1632772998d35e3d/src/connectors/menu/connectMenu.js#L203-L214

**To Reproduce 🔍**

1. Open the [CodeSandbox](https://codesandbox.io/s/6v5rov5rqw)
2. Simulate a 3G connection
3. Click on the button "Switch the ..."
4. Open the console to see the error

Explanation: the Switch button remove / add widgets dynamically - without the slow network everything is fine. But with a search being stalled InstantSearch trigger a new render with the last retrieved results. In that case the last results was with `brand`  not `categories`. That's why when we tried to access it the error is thrown.

**Expected behavior 💭**

Avoid to throw an error, either:

- we should always assume that the results doesn't contain the current attribute. 
- we revamp the lifecycle to **always** have the expected state

**Comment by Haroenv** [comment]
This is fixed since V4
