### ISSUE TITLE
Question on the page "hits"

### ISSUE THREAD

**Issue by goldhat** [algolia/instantsearch.js#3087]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[hits](https://community.algolia.com/instantsearch.js/v2/widgets/hits.html)".

I'm trying to figure out how to customize the search snippets. I need to limit the results from {{{_highlightResult.question.value}}} and {{{_highlightResult.message.value}}} to a small number of characters. The full result of {{{_highlightResult.message.value}}} is a large page of text. 

I've found other documentation for snippeting, but the examples don't use instantsearch they seem to use the main api or the index, all the code examples are like index.addSetting(). 

Thanks.

**Comment by Haroenv** [comment]
What you should do is the following:


1. Add “attributesToSnippet” to a configure widget


The syntax is the same as using snippeting via settings, it’s an array of attributes. 

2. Use `_snippetResult`

This has the same shape as the highlighting. 

Hope that helps, feel free to continue commenting here if anything else is unclear. 

Have a nice day!
