### ISSUE TITLE
fix React `propTypes` warning in tests

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#309]
We are currently generating a bit of noise in the tests because of React warning on props.

```
Warning: Failed propType: Required prop `ariaLabel` was not specified in `PaginationLink`.
Warning: Failed propType: Required prop `range` was not specified in `Slider`.
Warning: Failed propType: Required prop `start` was not specified in `Slider`.
Warning: Failed propType: Required prop `range` was not specified in `Nouislider`.
Warning: Failed propType: Required prop `start` was not specified in `Nouislider`.
Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
Warning: Failed propType: Required prop `setIndex` was not specified in `IndexSelector`.
Warning: Failed propType: Required prop `hasResults` was not specified in `undefined-AutoHide`.
Warning: Failed propType: Required prop `hideWhenNoResults` was not specified in `undefined-AutoHide`.
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)
```

We'll have to clean that. I also think our propTypes checks are not really in sync with the code

**Comment by vvo** [comment]
Yes we should fix our proptypes to avoid warning (and not remove warnings :D)

**Comment by redox** [comment]
> Yes we should fix our proptypes to avoid warning (and not remove warnings :D)

About that, from what I understood those warnings are only there in dev/test. We really need to think about a way to have real errors/exceptions once in built because our users instantiating the widgets will otherwise have a hard time debugging the options.

**Comment by vvo** [comment]
> We really need to think about a way to have real errors/exceptions once in built because our users instantiating the widgets will otherwise have a hard time debugging the options.

Yes this is a feature of our library, we already have some usage warning. Every widget should be very clear when used in a bad way: show the usage.

**Comment by redox** [comment]
> Yes this is a feature of our library, we already have some usage warning. Every widget should be very clear when used in a bad way: show the usage.

The type checking/tooling of React is very powerful, I don't think we want to recode anything here. I understand we have those "basic" usage exceptions but maybe we could just have a look if/how we could use the React propTypes tooling to benefit from all the features they have.

**Comment by vvo** [comment]
> We really need to think about a way to have real errors/exceptions once in built because our users instantiating the widgets will otherwise have a hard time debugging the options.

This is another issue we should tackle yes. This one is only about fixing the warnings (= pass the right props in test)

**Comment by vvo** [comment]
We need to fix them, this is annoying and also not a good sign, I think it now contains a warning about a missing key=

**Comment by pixelastic** [comment]
Is there a way to toggle the warning on/off? Because some are expected to be fired in tests, when we test that we throw errors when some parameters are not here for example.

**Comment by vvo** [comment]
> Is there a way to toggle the warning on/off?

I don't know. But if we expect some of them that's ok to show them. Right now a lot are not expected I think

**Comment by pixelastic** [comment]
Seems weird to display warning in tests if we expect them. The test should stub the call to `console.log` and we should not see the result in the display.

**Comment by vvo** [comment]
> The test should stub the call to console.log and we should not see the result in the display.

If we manage to do so and if React did not do anything weird (like getting a ref to a bound console.log), then why not I would be ok too

**Comment by vvo** [comment]
For this task, it's about checking that the displayed warning are expected or if they should be fixed. We also have warnings in the main dev example that should be fixed for sure

**Comment by vvo** [comment]
we can get rid of those by calling NODE_ENV=production mocha.. in the test script, this should do it

**Comment by bobylito** [comment]
On it!
