### ISSUE TITLE
InfiniteHits "Show more" button not working when setting the "aroundRadius" query parameter

### ISSUE THREAD

**Issue by tdutreui** [algolia/instantsearch.js#3091]
**Describe the bug 🐛**
Setting the 'aroundRadius' param , the "Show more" button stops working (widget InfiniteHits).
Nothing is displayed in my FF Dev Console (not even the Http POST request querying Algolia servers, so no query is performed)

Commenting the following line solves the problem:
`helper.setQueryParameter('aroundRadius', 75000);`

```
const search = instantsearch({
  appId: 'latency',
  apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
  indexName: 'instant_search',
  searchParameters: {
    hitsPerPage: 8,
  },
  searchFunction: function (helper) {

    helper.setQueryParameter('aroundRadius', 75000);
    helper.search();
  }
});
```

Another `Search` instance (searching on a replica) on the same page still has its "Show more" button working while the bug is present for the first `Search` instance.

**To Reproduce 🔍**
Set the 'aroundRadius' parameter using the `setQueryParameter` function inside `searchFunction` definition
Example : https://codesandbox.io/s/43xr3jxk5x

**Comment by Haroenv** [comment]
While I'm not completely clear on what causes this issue, you can set that option on two other ways:

1. via `searchParameters`: https://codesandbox.io/s/j26wz0r6jw

```js
const search = instantsearch({
  appId: 'latency',
  apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
  indexName: 'instant_search',
  searchParameters: {
    hitsPerPage: 8,
    aroundRadius: 75000,
  },
});
```

2. via the `configure` widget: https://codesandbox.io/s/w6pjxo5kjk

```js
const search = instantsearch({
  appId: 'latency',
  apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
  indexName: 'instant_search',
});

search.addWidget(
  instantsearch.widgets.configure({
    hitsPerPage: 8,
    aroundRadius: 75000,
  })
);
```

**Comment by tdutreui** [comment]
Hi
Thank you for this answer
The first option suits me for the moment
Still, I will probably need to dynamically adjust `aroundRadius` in some days/weeks (at query time, i.e after loading the page)

**Comment by tdutreui** [comment]
good idea :)
will give it a try !

Le mer. 5 sept. 2018 16:00, Haroen Viaene <notifications@github.com> a
écrit :

**Comment by Haroenv** [comment]
setQueryParameter in the helper resets the page, so if you're setting it in searchFunction, you need to first get the page, then set the parameter, then reset the page to what it was before. The alternatives suggested don't have that problem
