### ISSUE TITLE
Rooting option not working with jekyll when url sync does

### ISSUE THREAD

**Issue by ETIBER** [algolia/instantsearch.js#3092]
**Describe the bug 🐛**
The bug is simple, the rooting option doesn't work with Jekyll but url sync work well.
My unworking conf:
```
export const search = instantsearch({
  searchClient: algoliasearch('******','********'),
  indexName: '*******',
  rooting: true,
  searchParameters: {
    hitsPerPage: 10
  }
});
```

My working conf:
```
export const search = instantsearch({
  searchClient: algoliasearch('******','********'),
  indexName: '*******',
  rooting: false,
  urlSync: {
    mapping: {
      q: 'query'
    }
  },
  searchParameters: {
    hitsPerPage: 10
  }
});
```

**To Reproduce 🔍**
Use the rooting option on a jekyll project

A live example helps a lot!   We have a simple online template for you to use for your explanations:
  https://test-dinsic.fr/rechercher/?query=test
(this is the dev access, they will be change in 7 days)
user: dinsic
pswd: supersecure

**Expected behavior 💭**
I wish rooting will work before url sync is deprecated

**Environment:**
 - OS: iOS 
 - Browser Chrome
 - Version 68

**Additional context**

**Comment by Haroenv** [comment]
note that the option is called `routing`, not `rooting`. Did that fix your problem?

**Comment by ETIBER** [comment]
Thank you so much, it solve the problem
