### ISSUE TITLE
Can't change price field

### ISSUE THREAD

**Issue by SchmidtDawid** [algolia/instantsearch.js#3093]
Is there any way to change "price" filed in price widgets?

I want to do it like this:

```
var countryPrice = "price" //default value
if(any logic){
  countryPrice = "price_gb"
}
-------
search.addWidget(instantsearch.widgets.rangeSlider({
    container: '#price',
    attributeName: countryPrice,
    (...)
}))
```

But it doesn't work. I've got that error: 
```
generate-ranges.js:11 Uncaught TypeError: Cannot read property 'min' of undefined
    at i (generate-ranges.js:11)
    at Object._generateRanges (connectPriceRanges.js:118)
    at Object.render (connectPriceRanges.js:183)
    at InstantSearch.js:317
    at n (_arrayEach.js:15)
    at r (forEach.js:37)
    at t.value (InstantSearch.js:313)
    at r.n.emit (events.js:84)
    at algoliasearch.helper.js:1245
    at n (_arrayEach.js:15)
```

What I am missing?

**Comment by Haroenv** [comment]
I'm not completely understanding how those two pieces of code relate to each other, could you make a sandbox with this please? That will make it a lot clearer, thanks!

**Comment by SchmidtDawid** [comment]
Maybe i complicate it unnecessary.
I will just pass to widgets as "attributeName:" variable with string. But variable is changed before algolia starts.
The problem is if I pass string "price" everything works. But if i pass string "price_gb" widgets doesn't starts. 
My records looks like that:
{
  "name": "Any name",
  "price": 45,
  "price_gb": 49,
  (...)
}
Both are numerical, every record has the same fileds. Have I to do something with index?

**Comment by francoischalifour** [comment]
Glad you solved your problem, @SchmidtDawid!

You can learn more about attributes for faceting on our [searching guide](https://www.algolia.com/doc/guides/searching/faceting/#declaring-attributes-for-faceting).
