### ISSUE TITLE
Modifying range widget with webcomponents.js included prevents render from being dispatched

### ISSUE THREAD

**Issue by rjsteinert** [algolia/instantsearch.js#3099]
**Describe the bug 🐛**
We use instantsearch.js in combination with the polyfill for webcomponents, webcomponents.js. Unfortunately when using the range slider in combination with the webcomponents polyfill, an error is thrown which prevents the render event from being dispatched, something our application depends on. We thought about just listening for error event and doing what we need to do but we have found there is some strange behavior in the range slider after error.

**To Reproduce 🔍**
1. Go to https://pyrite-skate.glitch.me/ in Firefox or IE11.
2. Open dev tools.
3. Modify range slider.
4. See error variable where the debugger statement should have just landed you in the dev tools.

**Expected behavior 💭**
We would expect the render event to be fired.

**Screenshots 🖥**
![screen shot 2018-09-07 at 12 05 26 pm](https://user-images.githubusercontent.com/156575/45230485-ffb9b800-b296-11e8-8c7e-87a445ffecf6.png)

**Environment:**
 - OS: mac / windows
 - Browser: Firefox / IE11
 - Version: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.1

**Additional context**
Error message: `Error: "Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."`

**Comment by Haroenv** [comment]
Sorry for never replying here! In the mean time a lot has changed, including preact version many times. As the script works without the web components polyfill, I'm inclined to say it's probably an issue on that side, or even on Preact's side. We can't do much about it
