### ISSUE TITLE
Ability to prevent the user from clearing certain CurrentRefinedValues

### ISSUE THREAD

**Issue by Kevin-Hamilton** [algolia/instantsearch.js#3113]
I am using instantsearch via the Algolia WooCommerce plugin in a WordPress website.  On product category pages - for instance the user navigates to Clothing > Mens > T-Shirts in the nav - the plugin will use a hierarchicalMenu widget to refine the list of products to those which match the current navigation category.  This is done on init via the code:
`
if(algolia.woocommerce.page === 'category') {
    options.helper.toggleRefine('taxonomies_hierarchical.product_cat.lvl0', algolia.woocommerce.category);
}
`
This refinement is then displayed in the sidebar as part of the currentRefinedValues widget, and other widgets are also displayed for selecting additional faceted refinements.

The problem I'm having is that within the currentRefinedValues widget, if the user clicks on the refined-values item, or clicks on "clear all", then they will still be in the "Clothing > Mens > T-Shirts" area of the site, but they will be faced with products from all categories, which is confusing.

I would like a way to allow users to add new refinements to the search, and to "clear all" of those new refinements, but for the hierarchical refinement which was automatically selected to be hidden, or be read-only.

Looking at the currentRefinedValues component, the template is **always** wrapped in a 'div' and an 'a' tag.  Through the template or the transformData props, I can make the refinement item's _content_ disappear, but the anchor element remains, and the user can click in the space where the element should appear, causing the refinement to be cleared.

If there is some way to achieve my goal with the current code, please let me know.  Otherwise, please consider this feature request.

**Comment by Haroenv** [comment]
Just to clarify, did you use `transformItems` to filter out that specific refinement and that didn't work, or am I misunderstanding what you tried? It would be useful to have a codesandbox with the Current code. There's an example here: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js

**Comment by Kevin-Hamilton** [comment]
Can you show me some example code for transformItems?  I saw it in the documentation but I couldn't get it to work.

I did try removing the item in transformData, but that doesn't work...it still renders a div and an anchor tag.

**Comment by Haroenv** [comment]
https://codesandbox.io/s/23yn717k0n here's a sample on how to use it. Note I used `transformItems`, which is the new version of `transformData`, which allows filtering out. 

I've also noticed making this that "clear all" still removes even though things are filtered out, that should probably be the other way around

**Comment by Kevin-Hamilton** [comment]
Thanks, that looks close to what I want and with these couple changes (using a clearAll widget with excludeItems prop) I think should work as I want:
https://codesandbox.io/s/6xno2wyo93

But unfortunately the [algoliasearch wordpress plugin](https://github.com/algolia/algoliasearch-wordpress) is packaging version 1.11.15 of instantsearch, where transformItems does not yet exist.  

I will experiment with loading the latest instantsearch in its place and see what happens.

**Comment by Haroenv** [comment]
Oh that's right, I forgot Wordpress was so far behind. Note that you can upgrade yourself though, while it's a long way behind, it should be _mostly_ straightforward if you follow the migration guide: https://community.algolia.com/instantsearch.js/v2/guides/migration.html

**Comment by francoischalifour** [comment]
Note that we also released [InstantSearch.js 3](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/) meanwhile.

Closing the issue – feel free to reopen.
