### ISSUE TITLE
Question on the page "hierarchicalMenu"

### ISSUE THREAD

**Issue by wasim-bajwa-rltsquare** [algolia/instantsearch.js#3118]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[hierarchicalMenu](https://community.algolia.com/instantsearch.js/v2/widgets/hierarchicalMenu.html)".

I'm wondering if there is a way to Show More functionality for Hierarchical Menu, just like it is there for Refinement List.

**Comment by francoischalifour** [comment]
Hey @wasim-bajwa-rltsquare, there's currently no way to add the "Show More" functionality to a hierarchical menu. This is something that we are working on for InstantSearch 3.

**Comment by wasim-bajwa-rltsquare** [comment]
Thanks.
