### ISSUE TITLE
Template for using instantsearch with Docsearch index

### ISSUE THREAD

**Issue by bildungsroman** [algolia/instantsearch.js#3144]
**Is your feature request related to a problem? Please describe 🙏**
Yes. Apologies if this already exists, but I couldn't find a solution anywhere. I'm trying to use instantsearch together with a Docsearch index on my documentation site. Docsearch is working great in the navbar, but in addition to the navbar search present on every page, I would like to have an instant search on just the homepage of the docs site.

**Describe the solution you'd like 🤔**
I need a template that parses the JSON object coming in from the Docsearch API. I had implemented instantsearch on an earlier version of my site using the following code:

```
  const search = instantsearch({
    appId: '{{ site.algolia.application_id }}',
    indexName: '{{ site.algolia.index_name }}',
    apiKey: '{{ site.algolia.search_only_api_key }}'
  });

  const hitTemplate = function (hit) {
    let url = `{{ site.baseurl }}${hit.url}`;
    const title = hit._highlightResult.title.value;
    const content = hit._highlightResult.content.value;

    return `
    <div class="post-item col-12">
      <a class="post-link" href="${url}"><h4>${title}</h4></a>
      <div class="search-article-description">${content}</div>
      <a href="${url}" class="read-more">Read More »</a>
    </div>
  `;
  }

  // Adding searchbar and results widgets
  search.addWidget(
    instantsearch.widgets.searchBox({
      container: '#sidenav-search',
      placeholder: 'Search',
      poweredBy: true
    })
  );

  search.addWidget(
    instantsearch.widgets.hits({
      container: '#search-hits',
      templates: {
        item: hitTemplate
      }
    })
  ); 
```

This worked fine with a standard Algolia index, but Docsearch's API returns a different JSON object than the standard one, so copy-pasting the above code shows no results.

**Describe alternatives you've considered ✨**
I've tried parsing the JSON myself but have been unsuccessful.

**Additional context**
A new sample template for parsing Docsearch results would be incredibly helpful! Right now, with no template my search looks like this :( 

<img width="1406" alt="test" src="https://user-images.githubusercontent.com/5382821/45968068-a49cfa80-bfe4-11e8-9e95-a95ac21fd7a4.png">

**Comment by Haroenv** [comment]
This should already be mostly answered in https://github.com/algolia/docsearch/issues/457, but a sync between both of the projects is already planned. However, it's something that will be implemented in Docsearch, and not in InstantSearch.js, so for that reason I'll close this issue and leave the discussion in the other issue. I hope that makes sense to you 😄 

I'm ready to help you more if needed

**Comment by bildungsroman** [comment]
@Haroenv Perfect, thank you for all of your help!
