### ISSUE TITLE
Refinement List - Shows wrong items when 'Show More' is enabled.

### ISSUE THREAD

**Issue by AlphaGeek509** [algolia/instantsearch.js#3145]
**Describe the bug 🐛**
It appears that the start index of items to display on a refinement list when 'Show More' is enabled is not at the top of the items list.  Rather near the middle or even bottom.

**To Reproduce 🔍**
View an example of this bug at my JSFiddle.  https://jsfiddle.net/jandk4014/aq9Laaew/234880/.  It wouldn't make sense for me to add my code to this ticket.

**Expected behavior 💭**
The expected result for this refinement list would be to start with the first item in the list.  In this example if would be 1/8".  However, as you can see it's starting near the bottom of the listed items.

**Screenshots 🖥**
What I currently show.  It shows 4 (1/4") as the first item.  This is incorrect.
<img width="303" alt="screen shot 2018-09-24 at 12 56 23 pm" src="https://user-images.githubusercontent.com/3721279/45975527-521a0900-bff9-11e8-80bb-d51f29567abb.png">

With the list fully expanded you can see that 1/8" is at the top of the list and should be shown as such.
<img width="319" alt="screen shot 2018-09-24 at 12 56 35 pm" src="https://user-images.githubusercontent.com/3721279/45975574-6cec7d80-bff9-11e8-82ef-1f219e61957d.png">

**Comment by tanmoyopenroot** [comment]
```javascript
function formatItemLabels($items) {
    var $arr = Array();

    $items.forEach(function($item, index) {
        if($item.highlighted.includes("_")) {
            $keyValue = $item.highlighted.split('_');
            $items[index].highlighted = $keyValue[1];
            $arr[$keyValue[0]] = $item;
        }
    });
    return $arr;
}
```

On taking a close look at the `formatItemLabels` from the `jsfilddle`, It seems like you are changing the position of the data in the array(` $arr[$keyValue[0]] = $item;`)

![Screenshot from 2019-10-16 22-02-41](https://user-images.githubusercontent.com/25791025/66939441-b2df0e00-f060-11e9-9556-3bc308235091.png)

You are splitting data from `highlighted` property and adding the `item` to the first value from the split
