### ISSUE TITLE
Question on the page "pagination"

### ISSUE THREAD

**Issue by claytoncollie** [algolia/instantsearch.js#3153]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[pagination](https://community.algolia.com/instantsearch.js/v2/widgets/pagination.html)".

I am only returning 1 or 2 hits but the pagination is still showing as a hyperlinked integer of "1". If you looked at the searchParameters.hitsPerPage and found that hits are less that this value, hide the pagination.

**Comment by Haroenv** [comment]
You can use the noRefinement css class to hide it
