### ISSUE TITLE
Question on the page "connectMenu"

### ISSUE THREAD

**Issue by alishanster** [algolia/instantsearch.js#3163]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[connectMenu](https://community.algolia.com/instantsearch.js/v2/connectors/connectMenu.html)".

Hello! I am using Algolia search in my WordPress website, however apparently wp plugin doesnot support menuSelect widget, yet. So I tried to create connectMenu using example [here](https://community.algolia.com/instantsearch.js/v2/connectors/connectMenu.html#example). It worked perfectly, however I would like to add a select option that will clear current selected refine value, just what menuSelect does (something similar to 'see all' default option).  
P.S. I also tried to create custom template and enqueue latest instantsearch.js files from cdn, yet menuSelect widget didnot work, not sure what could go wrong there. I disabled algolia front-end search in plugin settings. 
Thank you.

**Comment by Haroenv** [comment]
On the Wordpress plugin, you'll first need to update to InstantSearch v2. It comes with InstantSearch v1 which doesn't have that feature

**Comment by alishanster** [comment]
Thanks for the reply, could you hint me how to update InstantSearch to v2? I did enqueue (include) latest instantsearch.js file from [cdn](https://community.algolia.com/instantsearch.js/v2/getting-started.html#from-a-cdn) in my functions file, and it does load (can be found in view source code of the page).

**Comment by alishanster** [comment]
Those in header: 
`
<link rel='stylesheet' id='InstantSearchCss-css'  href='https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.2/dist/instantsearch.min.css?ver=4.9.8' type='text/css' media='all' />
--
 <link rel='stylesheet' id='AlgoliaInstantSearchCss-css'  href='https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.2/dist/instantsearch-theme-algolia.min.css?ver=4.9.8' type='text/css' media='all' />
`
This in footer: 
`<script type='text/javascript' src='https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.2'></script>`


                                `         <script type="text/javascript">
		jQuery(function() {
			if(jQuery('#algolia-search-box').length > 0) {

				if (algolia.indices.searchable_posts === undefined && jQuery('.admin-bar').length > 0) {
					alert('It looks like you haven\'t indexed the searchable posts index. Please head to the Indexing page of the Algolia Search plugin and index it.');
				}

				/* Instantiate instantsearch.js */
				var search = instantsearch({
					appId: algolia.application_id,
					apiKey: algolia.search_api_key,
					indexName: algolia.indices.searchable_posts.name,
					urlSync: {
						mapping: {'q': 's'},
						trackedParameters: ['query']
					},
					searchParameters: {
						facetingAfterDistinct: true,
			highlightPreTag: '__ais-highlight__',
			highlightPostTag: '__/ais-highlight__',
			filters: 'wpml.locale:"' + current_locale + '"',
					}
				});

				/* Search box widget */
				search.addWidget(
					instantsearch.widgets.searchBox({
						container: '#algolia-search-box',
						placeholder: 'Search for...',
						wrapInput: false,
						poweredBy: algolia.powered_by_enabled
					})
				);

				/* Stats widget */
				search.addWidget(
					instantsearch.widgets.stats({
						container: '#algolia-stats'
					})
				);

				/* Hits widget */
				search.addWidget(
					instantsearch.widgets.hits({
						container: '#algolia-hits',
						hitsPerPage: 9,
						templates: {
							empty: 'No results were found for "<strong>{{query}}</strong>".',
							item: wp.template('instantsearch-hit')
						},
						transformData: {
							item: function (hit) {

								function replace_highlights_recursive (item) {
								  if( item instanceof Object && item.hasOwnProperty('value')) {
									  item.value = _.escape(item.value);
									  item.value = item.value.replace(/__ais-highlight__/g, '<em>').replace(/__\/ais-highlight__/g, '</em>');
								  } else {
									  for (var key in item) {
										  item[key] = replace_highlights_recursive(item[key]);
									  }
								  }
								  return item;
								}

								hit._highlightResult = replace_highlights_recursive(hit._highlightResult);
								hit._snippetResult = replace_highlights_recursive(hit._snippetResult);

								return hit;
							}
						}
					})
				);

				/* Pagination widget */
				search.addWidget(
					instantsearch.widgets.pagination({
						container: '#algolia-pagination'
					})
				);

                                        search.addWidget(
						  instantsearch.widgets.menuSelect({
						    container: '#aligolia-condition',
						    attributeName: 'taxonomies.condition',
						    limit: 10,
						    templates: {
						      header: '<h3 class="widgettitle">Condition</h3>'
						    }
						  })
						);`
p.s. as a result I only have a h3 tag with Condition title, but no selec menu, no errors in console
