### ISSUE TITLE
View all option to put the limit at 1000

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#317]
It's the second time this week I have been ask to have a view all option in Magento and we currently have a pending pull request for that. Can we consider adding that in the core ?

**Comment by pixelastic** [comment]
Sorry, I don't understand what you're refering to. What options? Could you link to the PR?

**Comment by maxiloc** [comment]
Yes the PR is here https://github.com/algolia/algoliasearch-magento/pull/233 but it's not really explicit. Basically e-commerce guys want to let the ability for the user to remove the hitsPerPage by clicking on a "View All" button. For us this means having a button to set hitsPerPage to 1000

**Comment by maxiloc** [comment]
I think an option to add this in the pagination widget could be good

**Comment by redox** [comment]
> Yes the PR is here algolia/algoliasearch-magento#233 but it's not really explicit. Basically e-commerce guys want to let the ability for the user to remove the hitsPerPage by clicking on a "View All" button. For us this means having a button to set hitsPerPage to 1000

I don't think having hitsPerPage=1000 is a good idea, do you think an infinite scroll widget could help?

**Comment by maxiloc** [comment]
I guess that could do the trick, but as I understood it, it seems to be something the end user need to be able to choose.

**Comment by maxiloc** [comment]
But event without this, I think having a infinite scroll widget makes a lot of sense

**Comment by vvo** [comment]
widgets.infiniteHits :)

**Comment by pixelastic** [comment]
Yep infiniteHits would be fun to build :)

**Comment by pixelastic** [comment]
@maxiloc: Would an infinite scroll widget fit you need? If so I'll rename the issue.

**Comment by vvo** [comment]
@pixelastic You can also create a new one with your proposal in it. Also this is "next" :)

**Comment by maxiloc** [comment]
@pixelastic Yes infinite scroll would fit. Would it be switchable with the hits widget by the user on the fly ?

**Comment by pixelastic** [comment]
I've added a specific issue for the infiniteScroll here: https://github.com/algolia/instantsearch.js/issues/328

I don't think this is something we would want to let the user toggle on/off (so many corner cases).

Maybe what you need is something like the indexSelector widget but for hitsPerPage?

**Comment by maxiloc** [comment]
> Maybe what you need is something like the indexSelector widget but for hitsPerPage?

Yes that is better and would solve the issue better than the infinite scroll widget

**Comment by vvo** [comment]
> Yes that is better and would solve the issue better than the infinite scroll widget

But displaying 1000 hits on a single page will be a fail without a proper lazy loading right? 1000 divs + 1000 images = you kill the browser

**Comment by maxiloc** [comment]
Yes I know that fetching 1000 hits is not good, but having a widget to change the hitsPerPage seems good anyway. We just need to explain that fetching 1000 is not a good idea.

**Comment by pixelastic** [comment]
I've also added an issue for the `hitsPerPageSelector` here : https://github.com/algolia/instantsearch.js/issues/331

I close this one.
