### ISSUE TITLE
Question on the page "hits"

### ISSUE THREAD

**Issue by strategyagency** [algolia/instantsearch.js#3171]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[hits](https://community.algolia.com/instantsearch.js/v2/widgets/hits.html)".

How do I limit the length of text returned by Instant Search in JS?

`{{{_highlightResult.description.value}}}`

Is way too long.

**Comment by Haroenv** [comment]
You can use `_snippetResult` instead after setting up that on your index. https://www.algolia.com/doc/guides/searching/highlighting-snippeting/#snippeting-overview

Basically make sure that attribute is in `attributesToSnippet`

```js
search.addWidget(
  instantsearch.widgets.configure({
    attributesToSnippet: ['description:5'], // 5 words, still highlighted
  })
);
```

**Comment by strategyagency** [comment]
Can this be used with the Hits widget? Here's a rough outline of my code, the code you've linked to doesn't work as expected with my example"

```
const productSearch = instantsearch({
    appId: 'xxx',
    apiKey: 'xxx',
    indexName: 'products',
    routing: true
});
```

```
var hitsWidget = instantsearch.widgets.hits({
    container: '#product-results',
    autoHideContainer: true,
    searchParameters: {
        hitsPerPage: 4,
    },
    templates: {
        empty: 'No results',
        allItems: '{{{_highlightResult.description.value}}}'
    }
});
```

```
var configWidget = instantsearch.widgets.configure({
    attributesToSnippet: ['description:5'], // 5 words, still highlighted
});
```

```
var searchInput = instantsearch.widgets.searchBox({
    container: '#search',
    placeholder: 'Search for products'
});
```

```
productSearch.addWidget(hitsWidget);
productSearch.addWidget(configWidget);
productSearch.addWidget(searchInput);
productSearch.start();
```

**Comment by strategyagency** [comment]
Needed to also start using _snippetResult not _highlightResult
