### ISSUE TITLE
Question on the page "connectHitsPerPage"

### ISSUE THREAD

**Issue by sherazkhan302** [algolia/instantsearch.js#3177]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[connectHitsPerPage](https://community.algolia.com/instantsearch.js/v2/connectors/connectHitsPerPage.html)".

for the line ( const itemsHTML = items.map(({value, label, isRefined}) => )

Internet Explorer gives error (expecting '':")
But working fine for chrome etc

**Comment by samouss** [comment]
The code of the example is written with ES2015+ syntax. Internet Explorer does not support the this syntax you have to use a tool like [Babel](https://babeljs.io/) to output IE compatible code. The following code should work with IE:

```js
function renderFn(HitsPerPageRenderingOptions, isFirstRendering) {
  var containerNode = HitsPerPageRenderingOptions.widgetParams.containerNode;
  var items = HitsPerPageRenderingOptions.items;
  var refine = HitsPerPageRenderingOptions.refine;

  if (isFirstRendering) {
    var markup = "<select></select>";
    containerNode.append(markup);
  }

  const itemsHTML = items.map(function(item) {
    var element = '<option value="' + item.value + '"';
    element += (item.isRefined ? "selected" : "") + ">";
    element += item.label;
    element += "</option>";

    return element;
  });

  containerNode.find("select").html(itemsHTML);

  containerNode
    .find("select")
    .off("change")
    .on("change", function(event) {
      refine(event.target.value);
    });
}

// connect `renderFn` to HitsPerPage logic
var customHitsPerPage = instantsearch.connectors.connectHitsPerPage(renderFn);

// mount widget on the page
search.addWidget(
  customHitsPerPage({
    containerNode: $("#hits-per-page"),
    items: [
      { value: 6, label: "6 per page", default: true },
      { value: 12, label: "12 per page" },
      { value: 24, label: "24 per page" }
    ]
  })
);
```

**Comment by sherazkhan302** [comment]
> The code of the example is written with ES2015+ syntax. Internet Explorer does not support the this syntax you have to use a tool like [Babel](https://babeljs.io/) to output IE compatible code. The following code should work with IE:
> 
> ```js
> function renderFn(HitsPerPageRenderingOptions, isFirstRendering) {
>   var containerNode = HitsPerPageRenderingOptions.widgetParams.containerNode;
>   var items = HitsPerPageRenderingOptions.items;
>   var refine = HitsPerPageRenderingOptions.refine;
> 
>   if (isFirstRendering) {
>     var markup = "<select></select>";
>     containerNode.append(markup);
>   }
> 
>   const itemsHTML = items.map(function(item) {
>     var element = '<option value="' + item.value + '"';
>     element += (item.isRefined ? "selected" : "") + ">";
>     element += item.label;
>     element += "</option>";
> 
>     return element;
>   });
> 
>   containerNode.find("select").html(itemsHTML);
> 
>   containerNode
>     .find("select")
>     .off("change")
>     .on("change", function(event) {
>       refine(event.target.value);
>     });
> }
> 
> // connect `renderFn` to HitsPerPage logic
> var customHitsPerPage = instantsearch.connectors.connectHitsPerPage(renderFn);
> 
> // mount widget on the page
> search.addWidget(
>   customHitsPerPage({
>     containerNode: $("#hits-per-page"),
>     items: [
>       { value: 6, label: "6 per page", default: true },
>       { value: 12, label: "12 per page" },
>       { value: 24, label: "24 per page" }
>     ]
>   })
> );
> ```

<3
