### ISSUE TITLE
Focus on input after refining

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#319]
Can we focus back on the input after refining. This is the current behavior for magento => https://magento.algolia.com/catalogsearch/result/?q=__empty__#q=&page=0&refinements=%5B%5D&numerics_refinements=%7B%7D&index_name=%22magento_default_products%22

And I think this something good

**Comment by pixelastic** [comment]
We sere thinking of providing events (`on('refine')`), that could let you do that. I would not do that as a default behavior in the library, though. Focusing will scroll the page and this is something really dependent on the UI you're building (can be desirable or not).

**Comment by maxiloc** [comment]
I understand. on('refine') works for me

**Comment by redox** [comment]
> And I think this something good

Not sure about that; neither Google nor Amazon do it for instance.

**Comment by vvo** [comment]
Yes if you do that you are saying to the user "you were using your mouse? Lets switch  to keyboard! Yolo"

**Comment by maxiloc** [comment]
Amazon does not do it but they do not have instant search. Google is a bit different since it's not an e-commerce

I think it's good for e-commerce website and it goes with what we pitch which is going back and forth between search and navigation.
Probably this is not something to put by default. But I think we should be able to do it

**Comment by redox** [comment]
> it goes with what we pitch which is going back and forth between search and navigation.

Agree, but that doesn't mean we need to force the user to do it; focusing the search bar seems like a very strong suggestion :)

> But I think we should be able to do it easily

Sure.

**Comment by maxiloc** [comment]
Yep make sense. Maybe an option would indeed be better in magento

**Comment by redox** [comment]
Cool, let's close this issue then, we'll check how to eventually plug the `on("refine"....`
