### ISSUE TITLE
Slider widget, remove refinements when at min and max

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#320]
I thought there was an issue already opened for this but I am not able to find it.

The slider should remove the refinements when the min and max of the slider are equals to min and max of the dataset.

For wordpress, in instant search page we could have article, page, products. Product is the only one with price so if you refine with the price slider you won't be able to have article and page

**Comment by vvo** [comment]
@maxiloc I believe this is now fixed, it was not released sorry. Now released with 0.5.0 careful there are breaking changes: https://github.com/algolia/instantsearch.js/blob/master/CHANGELOG.md#050-2015-10-22
