### ISSUE TITLE
Can i use sortBySelector like a hierarchicalMenu?

### ISSUE THREAD

**Issue by oscarhandsome** [algolia/instantsearch.js#3201]
I have filters on the site, and it's using sortBySelector:
```
<select data-reactroot="" class="ais-sort-by-selector">
  <option class="ais-sort-by-selector--item navbar-nav" value="sa">Sort by</option>
...other options....
</select>
```

works perfect but i need filter in the hierarchicalMenu can i convert it to? 
```
<ul class="navbar-nav">
  <li class="nav-item">
    <div class="nav-link">Popular</div>
   </li>
...other li tags....
</ul>
```

Where can I see the example? https://prnt.sc/l69xrt
or this is unreal?

**Comment by Haroenv** [comment]
Is this what you mean? https://codepen.io/Haroenv/pen/wrrrKj

**Comment by oscarhandsome** [comment]
@Haroenv looks good but i think this is not what i want
i need this block https://prnt.sc/l69xrt
my select works prefect [here](https://www.almall.com/sa/en/women/arabic-fashion?sort=sa&page=1&q=&c=Women%3AClothing%3AArabic%20Fashion&b=&color=)
but i need ul li for sorting like [here ](http://almall.elbargo.ru/women1.html)

**Comment by Haroenv** [comment]
Then you need to follow the link I gave you and replace “select” by “ul”, “option” by “li”.

**Comment by oscarhandsome** [comment]
@Haroenv Hello, could you please copy to jsfiddle your exaple? https://prnt.sc/l6z90r

**Comment by Haroenv** [comment]
Sorry, I don't have access to codepen either; but here's a similar example, done with `menu`: https://jsfiddle.net/z5eoh1ov/

**Comment by oscarhandsome** [comment]
@Haroenv this is code based on ES6?

**Comment by Haroenv** [comment]
no, it seems to be mostly ES5 from what I saw. You can use babel to transform anyway :)

**Comment by oscarhandsome** [comment]
@Haroenv yeah but i have thousands line of another code,

**Comment by oscarhandsome** [comment]
@Haroenv 
i still not resolved this item
but i'm tried, and got issue

`Uncaught TypeError: Cannot read property 'connectMenu' of undefined
    at scritp.js?v=1.95:228`

do you know what it can be?

**Comment by Haroenv** [comment]
yes, connectors are only available in InstantSearch v2 :)
