### ISSUE TITLE
Usage of deprecated methods on the helper

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#3204]
**Describe the bug 🐛**

Among other things I haven't found yet, `helper.toggleRefinement` -> `helper.toggleFacetRefinement`

**To Reproduce 🔍**
In lots of places, one is in `connectMenu` for example, but it's best to do them all at once, also change the tests etc.

**Expected behavior 💭**
Replace all usage of deprecated helper functions, so we can remove them

**Comment by Haroenv** [comment]
(for Hacktoberfest, you can done one by one and it's still useful!)

**Comment by prudywsh** [comment]
I take it :)
