### ISSUE TITLE
There is no way to display the search query in currentRefinedValues while `onlyListedAttributes: true`

### ISSUE THREAD

**Issue by stianmartinsen** [algolia/instantsearch.js#3205]
**Describe the bug 🐛**
The search query is not shown in the *currentRefinedValues* widget when `onlyListedAttributes` is set to true.

**To Reproduce 🔍**
1. Go to https://codesandbox.io/s/8y2jrkz8o9
2. Filter by brand and see the brand is shown in the *currentRefinedValues* widget.
3. Enter a custom search query
4. See error, the search query is not displayed in the *currentRefinedValues* widget.

**Expected behavior 💭**
The search query should show up in the *currentRefinedValues* widget even when whitelisting the other shown attributes with `onlyListedAttributes: true`. If not by default, we should have a way of enabling it.

_Originally posted by @stianmartinsen in https://github.com/algolia/instantsearch.js/pull/2414#issuecomment-430514274_

**Comment by samouss** [comment]
Thanks for reporting the issue. We can probably fix this issue by providing an attributeName to the query refinement when we create it (see below).

https://github.com/algolia/instantsearch.js/blob/84b65210add282af5962a133a71139124a95f9b6/src/lib/utils.js#L231-L235

**Comment by francoischalifour** [comment]
Hey @stianmartinsen, the next release will contain a fix for this. It will get published in the coming days. Thank you!
