### ISSUE TITLE
Differenciate the dev app/examples

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#321]
We need to put ourselves in a more realistic dev situation: without bootstrap.

To see if we need some more default styling, like active refinement and spacing around inputs/checkboxes (cc @redox)

We need to present more examples to our users (bootstrap, jquery widget..).

For this, I propose to move the example dev app to dev/, keep using webpack for our needs.
Then make the bootstrap example using only pure html/css/js (and jsdelivr).

TODO:
- [x] move the dev example to dev/
- [x] stop publishing the dev example to gh-pages
- [x] create examples/ dir
- [ ] create examples/bootstrap.html and redo the same example, without any webpack involved
- [x] the new dev app will be ugly, then we can have our own dev "theme" in dev/style.css

Examples will at first not be accessible, we should make them accessible at some point in our documentation website (algolia.github.io/instantsearch.js)

**Comment by pixelastic** [comment]
:100: on that one

**Comment by vvo** [comment]
I think we could have a dev/ and examples/ (using the releases not the build)

**Comment by redox** [comment]
I think we can close this one; it's mostly done with our new website. I'll remove the `gh-pages` branch for now as well.
