### ISSUE TITLE
Question on the page "rangeSlider"

### ISSUE THREAD

**Issue by hamidm** [algolia/instantsearch.js#3227]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[rangeSlider](https://community.algolia.com/instantsearch.js/v2/widgets/rangeSlider.html)".

I have an issue with the rangeSlider widget where it only works on the price field.
I have included the taxonomy for my field ABV to my indices and I can see the choices as checkbox option on the site but when I try to use the rangeSlider widget similar to price field, it won’t return any hits from the API

**Comment by Haroenv** [comment]
Hey @hamidm, is it possible that the attribute you used for that widget is formatted as strings, and not as numbers? Could it be possible to create a sandbox with the behaviour you mean? There's an example here: http://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js

**Comment by Haroenv** [comment]
Since there has been no response in a while, I'll close this issue, feel free however to comment further with more information and we can reopen this issue or a new one.
