### ISSUE TITLE
Question on InfiniteHits history

### ISSUE THREAD

**Issue by stockholmz** [algolia/instantsearch.js#3229]
Hi! We've recently fully implemented instantsearch.js on an e-commerce website.
We use infiniteHits as widget (with hidden button and custom triggering new hits when scrolling) for product-listings to provide a seamless stream of products.

However we're facing some issues when navigating into a product, and using browser back.
**The scenario here is** that the user would likely have scrolled down ex. 20 "pages", and of course the user expects to land the same place when going back.

To get to that point, we've done some customizing with routing like this:
https://gist.github.com/stockholmz/a411a56aab4e6435d2ec73dd9823dc23
Explained flow:
- User scrolls down 20 pages with infiniteHits
- User navigates to a product
- User navigates back to list, using browser back.
We know from URL sync / routing that User was on page 20, and we always show 6 hits per page.
- Tells instantsearch to get (6 * 20) hits on page 1. (routeState.hitsPerPage = 120)
-- To get the amount of hits User had before
- After first result set retrieved, we count rendered items / 6 and update the page it would be on. (uiState.page = Math.round(items_rendered / 6))
- User might scroll further (getting more pages)

**The issue is** that when loading the next pages afterwards, Algolia or Instantsearch.js seems to get lost. For page 21 we would get some duplicate hits or even just hits thats not related.

I've read https://github.com/algolia/instantsearch.js/issues/2835 which adresses the issue a bit, but seems to have stalled.

It would be very helpful having this as core functionality to enable, that instantsearch remembers the list from URL sync, and reproduces it on load.
From my (and my customers) point of view, its an expected behavior. 

Perhaps anyone got a suggestion on how to solve it better.

**Comment by Haroenv** [comment]
The main reason why #2835 was not resolved is because it's unclear which decision we should take, if we load all pages, you could break an implementation, simply by putting a really big page number. The best solution likely is allowing pagination also to "navigate back", or to put a limit on "preloaded pages". 

For now this is not a feature `connectInfiniteHits` has unfortunately

**Comment by Haroenv** [comment]
We still see this as a good use case to investigate further, but have not made further progress in this yet. To keep things going smooth, we try to close duplicate issues. More info can be found in #2835, where you can upvote the original comment to show your interest.
