### ISSUE TITLE
numericSelector throws an error with routing

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3231]
**Describe the bug 🐛**

The method `getWidgetSearchParameters` of the connector [`connectNumericSelector`](https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/numeric-selector/connectNumericSelector.js#L193-L213) throws an error when one of the provided options don't have a an associated value. We have to handle the case where an option don't have a value.

**To Reproduce 🔍**

https://codesandbox.io/s/zq7pm74q43

**Additional context**

https://discourse.algolia.com/t/numeric-selector-default-value/6378

**Comment by samouss** [comment]
Duplicate of https://github.com/algolia/instantsearch.js/pull/3139.

**Comment by Haroenv** [comment]
Duplicate of a PR?
