### ISSUE TITLE
Only wrap the `autoHide` decorator when needed

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#324]
Our current pattern in widgets that expose the `hideWhenNoResults` attribute is to wrap the React component inside an `autoHide` decorator, even if set to `false`. We then need to pass two new elements in the props: `hasResults` and `hideWhenNoResults`.

I think this could be simplified by only wrapping with `autoHide` when the `hideWhenNoResults` attribute is set to `true` in the widget. We'll then only have to pass `hasResults` to the component. One less props to pass all the way down, will make things easier.

I already tested that in a (now deleted) branch, this works well

**Comment by pixelastic** [comment]
Acually this might not be needed if we do #286.

**Comment by vvo** [comment]
Yes we better do #286 here, do we still need this issue?

**Comment by pixelastic** [comment]
I think we will first do this one (much easier), and then move the decorators to the widget level (much harder).
