### ISSUE TITLE
Hits: escapeHits should happen after transformItems

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#3250]
**Describe the bug 🐛**

If a transformItems which modifies `_highlightResult` in a way which makes it fail the regex to give classes is used, it will not apply the regex anymore

**To Reproduce 🔍**

https://codesandbox.io/s/kxvqkx7j5v?module=%2Fsrc%2Fapp.js

workaround needed for now: 

https://codesandbox.io/s/2vwml193j?module=%2Fsrc%2Fapp.js

**Expected behavior 💭**

Elements are already escaped and transformed, __before__ transformItems.

**Environment:**

 - Version: 2.10.3

**Comment by francoischalifour** [comment]
Does it need a fix for InstantSearh.js 2?

We'll definitely fix that in InstantSearch.js 3.

**Comment by Haroenv** [comment]
IMO this is a breaking change, and can thus be done only in InstantSearch.js v3

**Comment by francoischalifour** [comment]
Closed in #3251.
