### ISSUE TITLE
Question: best practice when using infinite scrolling while the content is being modified

### ISSUE THREAD

**Issue by tstehle** [algolia/instantsearch.js#3267]
I was wondering what the best practice was supposed to be when I use infinite scrolling, and the content changes server-side while a user is navigating, which leads to duplicates in the results displayed to the user.

Suppose I store news articles in Algolia and a user asks for the first 10 results (index 0 to 9) ordered by creation date (newest first).
After the user obtains the first 10 results, a different user creates a new article.
Since the article is new, it is inserted at index 0 in the ordered list of articles.
Therefore, the article that was previously at index 9 is now moved to index 10.
When the first user asks for the next page of results, he will obtain 10 results, index 10 to 19.
The user will see a duplicate, as the result he got at index 9 is also visible at index 10.

This is problematic for infinite scrolling, as the duplicates are visually right next to each other.

To stop this from happening, I use lodash
`const uniqueHits = _.uniqBy(hits, 'objectID');`
in the function I pass to connectInfiniteHits.

Is this best practice? Should this be handled transparently by the connector instead?

**Comment by Haroenv** [comment]
Feel free to comment further on this issue if you have more questions and you feel like this should be reopened.
