### ISSUE TITLE
dev app should use a different price facet for `priceRanges` widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#327]
Both the slider and `priceRanges` widget are using the same facetName, thus the behavior of both widgets is weird: slider limit is updated dynamically when you use it.

TODO:
- [ ] modify the import script of the instant search index to add priceForPriceRanges
- [ ] regenerate the indec
- [ ] use this new attribute in our dev app

**Comment by redox** [comment]
I think we'll anyway not manage to have all the widgets working at the same time in the future with this dataset. I would just move to another randomly-generated dataset with plenty of numerical/facets to handle it easier for the dev.

**Comment by bobylito** [comment]
I think all the widgets should be able to live on the same page.

**Comment by vvo** [comment]
> I think all the widgets should be able to live on the same page.

Yes me too but for this particular one (priceRange and rangeSlider, on the same attribute), the result will always be weird. Given that priceRange has a specific behavior that breaks the slider.

Having a slider and priceRange on different attribute is fine of course.

Was that your question @bobylito?
