### ISSUE TITLE
`connectInfiniteHits` doesn't support routing

### ISSUE THREAD

**Issue by francoischalifour** [algolia/instantsearch.js#3271]
**Describe the bug 🐛**

`connectInfiniteHits` doesn't implement `getWidgetState()` and `getWidgetSearchParameters()` to support routing (introduced in #2829).

As a result, it's not possible to retrieve the page number for the router on the hits (except when having another widget mounted, such as `pagination`).

**To Reproduce 🔍**

1. Go to [this sandbox](https://codesandbox.io/s/6jqxxmjr0r)
1. Scroll down to "Show more results"
1. Click on "Show more results"
1. Notice that the URL doesn't change (the page doesn't appear)
1. Uncomment the `pagination` widget line 39
1. Reiterate steps 2-3
1. The URL does update with the page number

**Expected behavior 💭**

The page number should be accessible without the `pagination` widget.

**Environment:**

 - InstantSearch.js ≤ 2.10.4

**Comment by samouss** [comment]
I don't think the `connectHits` connector is a concern for this issue since it doesn't let the user refine the page. Only the `connectInfiniteHits` connector have this feature. Did I miss something?

**Comment by francoischalifour** [comment]
Indeed, I edited the issue.

**Comment by samouss** [comment]
Fixed in `3.4.0` with the introduction of the previous button on `infiniteHits`.

https://github.com/algolia/instantsearch.js/blob/fa02bed4eefbb40365d74a1f35dfd4adf32f6758/src/connectors/infinite-hits/connectInfiniteHits.ts#L232-L253
