### ISSUE TITLE
New widget: infiniteHits

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#328]
Based on proposal in #317.

We could provide an `infiniteHits` widget, based on the default `Hits` that will allow the user infinite scrolling.

- We first display the `n` first results (taken from `hitsPerPage`), wrapped in their own DOM element
- We detect when the user is scrolling a tiny bit before the last results
- We fetch the next page of results and display it (in its own new wrapper DOM element) below the first one
- Whenever the user updates its query string or its filters, we jump back to the top of the page

The tricky part will be to accurately know when we need to clear the list and jump back on top.

I also guess we'll need to tell users that this should not be used in conjunction with the pagination widgets (this will yield to weird UI and results).

**Comment by redox** [comment]
Also to consider: after scrolling down to the Nth page, if I share the URL of the search page; I want it to load the N pages if I open the URL in a new tab.

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it

**Comment by hkdobrev** [comment]
Is there any development on this? Either in the API or as a planned new widget?

**Comment by vvo** [comment]
@hkdobrev No, are you interested in building an infinite hits widget? That would be awesome!
