### ISSUE TITLE
[hits]: allow configuring the hitsPerPage in the hits widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#33]
I first allowed configuring the hitsPerPage in the pagination widget because it made sense to have pagination <=> hitsPerPage BUT after speaking with @bobylito it makes more sense to have it in the hits widget.

Mostly because you can have a hits widget without pagination and not the other way round.

So:
- [ ] remove the hitsPerPage config from the pagination widget
- [ ] add hitsPerPage config to the hits widget

**Comment by redox** [comment]
:+1: @bobylito

**Comment by vvo** [comment]
This is done in #35 and waiting for review @bobylito :dancer:

**Comment by bobylito** [comment]
Will do asap :)


—

**Comment by bobylito** [comment]
Merged!
