### ISSUE TITLE
Silence React dev warnings

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#330]
After started using v0.5.0, I'm getting a console log with  "Download the React DevTools for a better development experience: https://fb.me/react-devtools", which is a bit annoying.

It seems like `browserify`ing with `NODE_ENV=production` makes these warning messages disappear (See https://github.com/facebook/react/issues/3877 ).

Could we do that for our releases?

**Comment by vvo** [comment]
Yes we need so

**Comment by Jerskouille** [comment]
It seems like we might also need to define a webpack plugin : https://github.com/facebook/react/issues/3877#issuecomment-141776722 .

**Comment by Jerskouille** [comment]
:+1: @vvo

**Comment by bobylito** [comment]
We could also the dev issues...

**Comment by vvo** [comment]
@bobylito The dev issues we have we will still see them, always in dev mode and tests and we have #309 to track them
