### ISSUE TITLE
disjunctive facets change to conjunctive when I set searchParameters.facetsExcludes

### ISSUE THREAD

**Issue by eddyparkinson** [algolia/instantsearch.js#3309]
My disjunctive facets become conjunctive when I set searchParameters.facetsExcludes

Example
---

Click the sony checkbox here:    https://codesandbox.io/s/l598wkxoy7

my code
---

I added this:

```
  excludeVendors = ["Entity Brands","JS Supplies"];
  var searchParameters = {};
  if(excludeVendors && excludeVendors.length>0) {
    searchParameters =  {
        facets: ['vendor'],
        "facetsExcludes": {
            "vendor": excludeVendors
        }
      };
  }

```

to this standard shopify code:

```
  var _ = algolia._,
      $ = algolia.jQuery;

  algolia.config.results_selector += ', .algolia-shopify-instantsearch';

  var $hiding = $('<style>' + algolia.config.results_selector + ' { visibility: hidden }</style>');
  $hiding.appendTo($('head'));

  algolia.facetsWidgets.forEach(function(element) { if(!element.params.sortBy) element.params.showMore = true; });
  
  var instant = algolia.instantsearch = {
    colors: algolia.config.colors,
    distinct: !!algolia.config.show_products,
    facets: {
      hidden: algolia.hiddenFacets,
      shown: algolia.shownFacets,
      list: algolia.facets,
      widgets: algolia.facetsWidgets
    },
    hitsPerPage: algolia.config.products_full_results_hits_per_page,
    poweredBy: algolia.config.powered_by,
    search: instantsearch({
      appId: algolia.config.app_id,
      apiKey: algolia.config.search_api_key,
      indexName: '' + algolia.config.index_prefix + 'products',
      searchParameters: searchParameters,
      urlSync: {},
      searchFunction: function (searchFunctionHelper) {
        // Set query parameters here because they're not kept when someone
        // presses the Back button if set in the `init` function of a custom widget
        var helper = instant.search.helper;
        var page = helper.getPage();
        helper.setQueryParameter('highlightPreTag', '<span class="ais-highlight">');
        helper.setQueryParameter('highlightPostTag', '</span>');
        helper.setQueryParameter('distinct', instant.distinct);
        helper.setPage(page);
        searchFunctionHelper.search();
      }
    }),
    selector: algolia.config.results_selector + ', .algolia-shopify-instantsearch',
    sortOrders: algolia.sortOrders,
    storeName: algolia.storeName,
    templates: {
      currentItem: algolia.getTemplate('instant_search_current_refined_values_item'),
      empty: algolia.getTemplate('instant_search_no_result'),
      page: algolia.compileTemplate('instant_search'),
      product: algolia.getTemplate('instant_search_product'),
      stats: algolia.getTemplate('instant_search_stats'),
      style: algolia.compileTemplate('instant_search.css')
    }
  };


```

**Comment by eddyparkinson** [comment]
Shopify version of instasearch
----

Looks like I have an old version, as I found a solution https://codesandbox.io/s/1rvmqq5jm4
But it does not work on my version. How to upgrade?


Docs issue
---
Docs for facetsExcludes say " Each facet must be properly defined in the facets attribute."
See https://community.algolia.com/algoliasearch-helper-js/reference.html#SearchParameters#facetsExcludes

this works without  the facets attribute:  https://codesandbox.io/s/1rvmqq5jm4


```
  searchParameters: {
    facetsExcludes: {
      brand: ["Sony"]
    },
    hitsPerPage: 8
  }

```

**Comment by Haroenv** [comment]
While this clearly is something that is going wrong, you can use `transformItems` to hide an item from a list, instead of doing it with helper parameters:

```js
search.addWidget(
  instantsearch.widgets.refinementList({
    container: '#brand-list',
    attributeName: 'brand',
    transformItems: items => items.filter(item => item.label !== 'Sony'),
  })
);
```

https://codesandbox.io/s/8k9wqo53pl?module=%2Fsrc%2Fapp.js

**Comment by Haroenv** [comment]
Note that InstantSearch v1 is no longer supported, and since this is a feature not working rather than a bug, we will not fix it for v1

**Comment by eddyparkinson** [comment]
@Haroenv  I have a problem, my system is unusable for my customers.  How to upgrade to InstantSearch v2 with shopify?

**Comment by Haroenv** [comment]
Sorry, I missed the part where you said it was a Shopify app, which is an exception

**Comment by pagealexandre** [comment]
Hey @eddyparkinson , I am Alex, developer working on the Shopify Project. @Haroenv is right, we are using instant search v1 which is not supported any more. We have a conversation going on about this topic for Shopify, but this has not be defined as a goal for the following weeks / months at least. That having said, thanks for the heads up, we have more and more requests about this topic and this is exactly this type of initiative that will make us want to choose to update for IS2. Please reach out our support if you have technical question about Shopify.

cc @wittydeveloper

**Comment by Haroenv** [comment]
This is the workaround I see for v1:

```js
search.addWidget(
  instantsearch.widgets.refinementList({
    container: '#brand-list',
    attributeName: 'brand',
    // v2 version:
    // transformItems: items => items.filter(item => item.label !== 'Sony'),
    transformData: {
      item(item) {
        if (item.name === 'Sony') {
          // uses a bug in InstantSearch v1,
          // which will not add the classes on empty items
          return {};
        }
        return item;
      },
    },
  })
);
```

Then you can hide it with css:

```css
.ais-refinement-list--item label:not(.ais-refinement-list--label) {
  display: none;
}
```

I updated the sandbox: https://codesandbox.io/s/8k9wqo53pl?module=%2Fsrc%2Fapp.js

**Comment by eddyparkinson** [comment]
Re-open - workaround
---

@Haroenv The issue is not about hiding. it is about combining disjunctive facets with excluded facets (.facetsExcludes). Please re-open, maybe someone will post a workaround.

I suspect some workaround is possible. The facetsExcludes is only needed when no disjunctive facet items are selected, when a disjunctive facet item is selected facetsExcludes is not required.

Hide facets item
---
This worked, but did not help. I was hoping it would solve another issue with "Show More".
"Show more" shows the items in the facetsExcludes, which I did not want. So I just got rid of the show more for now.

Instant Search v2
---
@pagealexandre  looking foward to IS2. Looks to fix several on my current issues.

I did try switching to IS2, is it possible?. It looks like a lot of work. Am not sure if it is even possible to switch but am keen to use it.

**Comment by Haroenv** [comment]
As using facetsExcludes is very rare, I have not seen other occurrences of this behaviour. Will close now, but if someone else needs to use excluded facets, please open a new issue with reproduction.
