### ISSUE TITLE
Question on the page "Routing and urls"

### ISSUE THREAD

**Issue by fvoverscan** [algolia/instantsearch.js#3310]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[Routing and urls](https://community.algolia.com/instantsearch.js/v2/guides/routing.html)".

My attributeName is on an object, for exemple 'merchant.name'.
The widget work great with `attributeName: 'merchant.name',` but when i would like change the routing, it seems not possible.

When i refine, the url look like : `?refinementList%5Bmerchant.name%5D%5B0%5D=aaaaaaaaa`

So i try  `uiState.refinementList.merchant.name` or `uiState.refinementList.[merchant.name][0]` or `uiState.refinementList.[merchant.name]` or `uiState.refinementList['merchant.name']`  but it generate errors.

Do you have any idea, how i could do this ?

Thanks

**Comment by fvoverscan** [comment]
Humm sorry, I found that it work with `uiState.refinementList['merchant.name']`

**Comment by Haroenv** [comment]
Perfect!
