### ISSUE TITLE
Question : Distinct on widget rather then globaly

### ISSUE THREAD

**Issue by fvoverscan** [algolia/instantsearch.js#3321]
Hi,

I would like to know if it's possible to distinct the query at widget level or to undistinct at widget level ?

Use case :
My index represents all the offers of my shop. Unfortunatly, i have to use this index to build my search UI for listing products.
my datas are structured like this :
```
[
  {
    merchant: {
        id : 1,
        name: "Merchant 1"
     },
    product: {
        id: 1,
        name: "Product 1",
        category: "Category 1"
    },
    price: 50
  },
  {
    merchant: {
        id : 2,
        name: "Merchant 2"
     },
    product: {
        id: 1,
        name: "Product 1",
        category: "Category 1"
    },
    price: 50
   },
  {
    merchant: {
        id : 1,
        name: "Merchant 1"
     },
    product: {
        id: 2,
        name: "Product 2",
        category: "Category 1"
    },
    price: 100
   },
  {
    merchant: {
        id : 2,
        name: "Merchant 2"
     },
    product: {
        id: 2,
        name: "Product 2",
        category: "Category 1"
    },
    price: 100
   },
]
```

I have to use the distinct = 1 to show only the two products. I have to use also facetAfterDistinct = true otherwise the count is not good for the refinement category.

The actual result is :

nb Hits = 2 (Product 1 and Product 2)

Categories List :
- Categorie 1 (2) <--- If facetAfterDistinct = false the count will be 4 (wrong because we want 2 like the hits)

Merchant List :
- Merchant 1 (2)  <--- there is no "Merchant 2" because of facetAfterDistinct=true, if we use facetAfterDistinct=false, there is the two merchants.  

The distinct parameter keep the first data of all products but we would like to have all merchants available for refinement...

We would like this result : 

nb Hits = 2 (Product 1 and Product 2)

Categories List :
- Categorie 1 (2) 

Merchant List :
- Merchant 1 (2)  
- Merchant 2 (2)

So is it possible to bypass the distinct at widget level ? or facetAfterDistinct ?

Maybe you have a better idea ?

Thanks

**Comment by fvoverscan** [comment]
Nobody ?

**Comment by samouss** [comment]
Hi @fvoverscan, sorry for the delayed answer. You can imagine the way how InstantSearch.js works with this: one instance / one request to Algolia. This is not true but you got the idea. That's why you cannot provide distinct at the widget level because each widget is one "parameter" of the search.

With the given record structure I'm not sure this is something achievable. But why do you have to duplicate the content for both the merchant and the product? You can store all the merchants inside the product. Then you can to declare the `merchants.name` as facet, it should solve the issue.

**Comment by fvoverscan** [comment]
Hi @samouss,
The structure is given to me, i could not change it.
Maybe i could do 2 requests... One for the merchant and the other for the list of product (using the result of the first one) ?

**Comment by samouss** [comment]
Yes the solution with two requests could work but not with InstantSearch. The library doesn't let you create a dependency between multiple requests. With the provided structure I don't think there is an easy solution (at least I didn't found one).

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
