### ISSUE TITLE
Allow debouncing the image loading of the hits template

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#333]
Following #302 and #307

It seems that in some situations we could allow users to debounce the image loading.

One solution:

hits({container, lazyloadImages})

On the implementation side:

Users will have to use ais-src=real-src.jpg on images + src={helpers.lazySrc}
We listen to onload on main hits container
If onload element === img && img.ais-src => load the image in 100ms
If newsearch before 100ms, discard all previous images
We can use classes and shit to allow displaying images with fadein fadeout
I think we should not try to lazyload for now (only load what's visible), this is a harder topic to include as an API

**Comment by redox** [comment]
> I think we should not try to lazyload for now (only load what's visible)

Definitely on the same page.

So do we name it `lazyloadImages: true/false` or not?

**Comment by vvo** [comment]
> So do we name it lazyloadImages: true/false or not?

delayImages: bool/number (ms)?

**Comment by vvo** [comment]
It's not really lazyloading per se, we do not check the viewport (that would be another option I guess)

**Comment by vvo** [comment]
otherwise, we can have lazyloadImages:true/false that would mean:
- delay loading to 50-100ms by default, cancel src change (thus download) if updated search state
- also handle right away the viewport, so that we can keep the lazyload option name

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it
