### ISSUE TITLE
priceRangeConnector doesn't display values

### ISSUE THREAD

**Issue by MarcoTroost** [algolia/instantsearch.js#3337]
We're using the jQuery-connector for priceRanges, to gain more control over the look and feel of the element. 

When using the example given @ https://github.com/algolia/instantsearch.js/blob/develop/dev/app/jquery/widgets/priceRanges.js, all is well (RefinedValues are shown and resultset changes) except for the fact that the input boxes aren't updated with the value entered.

One would expect that the entered value remains visible.

![schermafbeelding 2018-12-12 om 11 03 32](https://user-images.githubusercontent.com/16369103/49862218-f98b2880-fdfd-11e8-9bbf-aed2f80c3c11.png)

kind regards, Marco

p.s. The demo @ https://community.algolia.com/instantsearch.js/v2/dev-novel/?widgets=jquery&selectedStory=PriceRanges.default doesn't work either ...

**Comment by Haroenv** [comment]
priceRanges no longer exists, so this likely isn't valid anymore. Please open a new issue with reproduction if you see this. Sorry for not responding earlier
