### ISSUE TITLE
Set a default price range

### ISSUE THREAD

**Issue by benjing** [algolia/instantsearch.js#3341]
I was wondering if there is a way to set a default price range. E.G showing a page with gifts under $100. i don't want the user to have to click on a little button on the side. I want the instant to load with only products under $100. dynamically.

**Comment by Haroenv** [comment]
Right now we do not have a way to manually set a refinement on the components themselves, however we do have the `configure` widget you can add. In this case the search parameter `numericFilters` would be set to the value, e.g. `numericFilters: ["price>=290","price<=570"]`. 

If it needs to be added dynamically, it might be best to use `connectRange` to make a widget which doesn't render, but sets the parameter on initialisation. With either the connectRange solution or with the configure solution; you then need to use `addWidget` and `removeWidget` when your button would be clicked or navigation would be changed.

If any issues happen with the implementation of this, pleas

**Comment by Haroenv** [comment]
A completely alternative, and maybe simpler now that I think of it, solution would be to do:

1. enable routing
2. add a link to the search, but with that parameter preselected.

**Comment by Haroenv** [comment]
See https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/js/#apply-default-value-to-a-widget on how to set default values, in this case with `numericFilters`
