### ISSUE TITLE
HierarchicalMenu click on the parent element behaviour

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3349]
**Is your feature request related to a problem? Please describe 🙏**

With the current implementation of the `hierarchicalMenu` a click on the parent level removes the current level but also the parent. But actually it's maybe not the expected behaviour. You can take a look at [this example](https://v3--instantsearchjs.netlify.com/stories/?selectedStory=HierarchicalMenu.default):

- click on  "Audio > Docks, Radios & Boomboxes > Radios"
- click on "Audio > Docks, Radios & Boomboxes"

We could expect to be at the level "Docks, Radios & Boomboxes" (this is how [Amazon](https://www.amazon.com/s//www.amazon.com/s/ref=sr_nr_n_1?fst=as%3Aoff&rh=n%3A2335752011%2Cn%3A2407749011%2Ck%3Aiphone&keywords=iphone&ie=UTF8&qid=1544795775&rnid=2335753011&ajr=0&ajr=0) works) but we are at the "Audio" level.

**Describe the solution you'd like 🤔**

Rather than removing the current and parent level we could let the parent level refined.

**Additional context**

https://github.com/algolia/instantsearch.js/issues/2016#issuecomment-447324757

**Comment by dhayab** [comment]
Closing it, this behaves as expected.
