### ISSUE TITLE
Create a default Algolia theme

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#336]
Now that we have the default theme skeleton, we need to build a default Algolia theme.

 * [ ] No bootstrap dependencies
 * [ ] No extra `cssClasses` required on the widgets
 * [ ] Avoid showy colors to fit with most websites
 * [ ] Ability to change the colors easily

**Comment by pixelastic** [comment]
We currently have a `themes/default.css` (the skeleton) that only adds basic bold and margin. Are you talking about a new theme?

**Comment by redox** [comment]
This has been postponed and replaced by a mandatory `instantsearch.css` file to require. We'll open a new issue once we'll work on themes.
