### ISSUE TITLE
Question on the page "Getting started"

### ISSUE THREAD

**Issue by binhaifgs1** [algolia/instantsearch.js#3361]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[Getting started](https://community.algolia.com/instantsearch.js/v2/getting-started.html)".

**Comment by binhaifgs1** [comment]
which file shall i put the codes in？

**Comment by Haroenv** [comment]
Hi @binhaifgs1, you can look at https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js for an example which files to put where. 

I hope that helps, and have a nice day!
