### ISSUE TITLE
Question on the page "connectGeoSearch"

### ISSUE THREAD

**Issue by combs** [algolia/instantsearch.js#3368]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[connectGeoSearch](https://community.algolia.com/instantsearch.js/v2/connectors/connectGeoSearch.html)".

Could you help me understand how to use the `refine` and `setMapMoveSinceLastRefine` functions to enable map-move refinement with a Leaflet implementation? 

The example doesn't deal with this, and I wasn't able to understand how to use it from the test fixture or source code. 

Thank you!
Chris

**Comment by samouss** [comment]
You don't have to use the `setMapMoveSinceLastRefine` to enable map-move refinement. Its usage is mostly for non map-move refinement (the users have to click on a button to trigger refine). Here is [an example](https://codesandbox.io/s/62n7okrkyr) that implements map-move refinement with Leaflet. 

The example is built with latest version of InstantSearch (version 3).  It's a beta version but the stable come soon. Take a look [at the migration guide](https://v3--instantsearchjs.netlify.com/guides/v3-migration.html) in case you want to update. Note that the example is basic and might not handle all the edge cases.
