### ISSUE TITLE
Merge props given both in Configure and other widgets

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3384]
> Original issue in Vue InstantSearch: https://github.com/algolia/vue-instantsearch/issues/599

**Is your feature request related to a problem? Please describe 🙏**

When we use `configure` to set a managed refinement like `numericFilters` we should merge them rather than throw an error at the helper level. It can be done either inside InstantSearch or at the helper level.

**Additional context**

> https://codesandbox.io/s/jzxx689jqy

> https://github.com/algolia/react-instantsearch/issues/725

**Comment by Haroenv** [comment]
as far as I can tell this is fixed with https://github.com/algolia/instantsearch.js/pull/4085
