### ISSUE TITLE
Panel should receive the same render options than the wrapped widget

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3385]
**Is your feature request related to a problem? Please describe 🙏**

The current implementation of `panel` receives the raw results inside the `hidden` option. It makes it very difficult for users to implement the removed option `autoHideContainer`.

**Describe the solution you'd like 🤔**

We should investigate how we could provide the render options of the connector directly rather than the raw results.

**Describe alternatives you've considered ✨**

None at the moment.

**Additional context**

> https://secure.helpscout.net/conversation/741036895/113536

**Comment by Haroenv** [comment]
This is actually done now with the addition of getWidgetRenderState (https://github.com/algolia/instantsearch.js/blob/master/CHANGELOG.md#490-2020-12-01), however the documentation still needs to be updated: https://www.algolia.com/doc/api-reference/widgets/panel/js/#widget-param-hidden
