### ISSUE TITLE
[pagination]: error message displays stalled value

### ISSUE THREAD

**Issue by jonathantribouharet** [algolia/instantsearch.js#3390]
Hi,
just to let you know that the documentation for cssClasses for the pagination widget is not correct.

https://github.com/algolia/instantsearch.js/blob/afc507c276fac38c0371f7fbb704383115631046/src/widgets/pagination/pagination.js#L92

The documentation say the parameter is named `itemNextPage` and in the code it's `nextPageItem`, same for `itemPreviousPage` which is `previousPageItem`.

I think you may have others typo like these.

**Comment by samouss** [comment]
The documentation for the version 3 of InstantSearch is not generated from the source code anymore, that why some inconsistencies are present. Those comments will be removed in the coming weeks. We still have an issue inside the message for the usage though. Any PRs is welcome!

https://github.com/algolia/instantsearch.js/blob/afc507c276fac38c0371f7fbb704383115631046/src/widgets/pagination/pagination.js#L83
