### ISSUE TITLE
IE11 doesn't work  anymore

### ISSUE THREAD

**Issue by fvoverscan** [algolia/instantsearch.js#3391]
Hi,

It seems that InstantSearch doesn't work anymore with IE 11.
I try to use polyfill (like on the doc) but it doesn't work...

It work well before i change the rooting config. Previously i was using urlsync. 

I have a console error `":" expected` on the line of the stateToRoute function.

Polyfill never works when i was using urlsync. So i had to block the website for IE < 11.

Now it seems that i have to block it for all IE, that i don't want.

Thanks for your help.

I use :
https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js
https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js
https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.includes

**Comment by samouss** [comment]
I didn't manage to reproduce the issue on IE11. Could you please provide an example that throws an error, it will help us to better understand where the issue come from. Thanks!

**Comment by JonnyTurnerUK** [comment]
I've just had similar issues but managed to get the search functions working fine in IE11. In my case, the fixes were template literals and string concatenation (replace ` with ' and also form strings as 'something' +).

**Comment by Haroenv** [comment]
Yes, keep in mind that the code examples of what we write ourselves in the documentation doesn't necessarily work in older browsers. Feel free to check out [babel](https://babeljs.io) to transform your own code to work in older browsers. The library itself will work in IE11 (or whatever is mentioned in the readme)
