### ISSUE TITLE
Eventhandler when finished/rendered

### ISSUE THREAD

**Issue by timmetj** [algolia/instantsearch.js#3392]
**Is your feature request related to a problem? Please describe 🙏**

There is no "finished/rendered" event to do something after the hits are loaded/refreshed. The only available event is the `on.render` or `searchFunction`, but this is too early if you want to do something with the new DOM hits/filters or show something after everything is loaded

**Describe the solution you'd like 🤔**

A new event to be called after the search/hits are done and build. Simple `on.finished/rendered` function.

**Describe alternatives you've considered ✨**

With the current `on.render` or `searchFunction` this can't be achieved

**Additional context**

https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/?language=js#events

**Comment by samouss** [comment]
Could you give a bit more context about your use case? The `render` event is emitter once all the widgets are rendered on the screen. The DOM elements created by the widgets should be available from the `render` event (see [example](https://codesandbox.io/s/rjy4nm42kq)).

**Comment by timmetj** [comment]
Hmm yes, i'm a bit confused now.. I added an alert box to show it:
https://codesandbox.io/s/920j6qw65r
The alert is fired before the console (while console is first) But this shows that the rendering is not completed since you still see the old data, although the DOM does seem the be changed already. So i would also expect a function that would show the alert box after the rendering is finished for some cases.
Just came across this and sounds like it could contribute for some cases where you would want to do something after rendering.

**Comment by samouss** [comment]
I've update [your example](https://0x1zjk06k0.codesandbox.io/) to print the text rather than the DOM element. You can see that the text is printed before the alert is shown (use the example outside of CodeSandbox to see the difference). The UI is not updated yet but the DOM is up to date. The `alert` block the UI of the browser, the render of the page included. It should be safe to use the `render` event to perform operations since the DOM is already updated.

**Comment by timmetj** [comment]
Yes ok, maybe it wouldn't make that much difference if the UI isn't changed yet. I was aiming for when the UI is also changed idd.
