### ISSUE TITLE
"instantsearch.connectors" are not available from the ES build.

### ISSUE THREAD

**Issue by tnylea** [algolia/instantsearch.js#3419]
**Describe the bug 🐛**
I'm trying to implement the AutoComplete functionality using the Vanilla JS InstantSearch. I'm using webpack and I'm getting the following error in my console:

```
app.js:36248 Uncaught ReferenceError: "instantsearch.connectors" are not available from the ES build.

To import the connectors:

import { connectSearchBox } from 'instantsearch.js/es/connectors'
```

I've already done as described:

```
import { connectSearchBox } from 'instantsearch.js/es/connectors'
```

but the error still exists.

Here is my code:

```
import algoliasearch from 'algoliasearch/lite';
import instantsearch from 'instantsearch.js/es'
import { searchBox, hits } from 'instantsearch.js/es/widgets';
import { connectAutocomplete } from 'instantsearch.js/es/connectors';


const search = instantsearch({
  indexName: 'posts',
  searchClient: algoliasearch(
    'XH97EKBGNS',
    'ffd2b688a4c9d620a2ee506cd4f340e4'
  ),
});

search.start();


// Helper for the render function
const renderIndexListItem = ({ label, hits }) => `
  <li>
    Index: ${label}
    <ol>
      ${hits
        .map(
          hit =>
            `<li>${instantsearch.highlight({ attribute: 'name', hit })}</li>`
        )
        .join('')}
    </ol>
  </li>
`;

// Create the render function
const renderAutocomplete = (renderOptions, isFirstRender) => {
  const { indices, currentRefinement, refine, widgetParams } = renderOptions;

  if (isFirstRender) {
    const input = document.createElement('input');
    const ul = document.createElement('ul');

    input.addEventListener('input', event => {
      refine(event.currentTarget.value);
    });

    widgetParams.container.appendChild(input);
    widgetParams.container.appendChild(ul);
  }

  widgetParams.container.querySelector('input').value = currentRefinement;
  widgetParams.container.querySelector('ul').innerHTML = indices
    .map(renderIndexListItem)
    .join('');
};

// Create the custom widget
const customAutocomplete = instantsearch.connectors.connectAutocomplete(
  renderAutocomplete
);

// Instantiate the custom widget
search.addWidget(
  customAutocomplete({
    container: document.querySelector('#searchBox'),
    indices: [
      { label: 'Featured', value: 'bestbuy' },
      { label: 'Price (desc)', value: 'instant_search_price_desc' },
    ],
  })
);

```

I have copied and pasted the example from this page: https://www.algolia.com/doc/api-reference/widgets/autocomplete/js/ and I'm still getting that error

**Environment:**
 - OS: Mac OS Mojave
 - Browser: Chrome
 - Version: Latest

**Additional context**
I would really appreciate any assistance on this. I've been digging around the docs and the github issues without any luck. Thanks 🙏

**Comment by tnylea** [comment]
And... I got it figured out 10 minutes after posting this.

I needed to include the autocomplete import like so:

```
import { connectAutocomplete } from 'instantsearch.js/es/connectors';
```

Then I needed to call the renderAutocomplete like so:

```
const customAutocomplete = connectAutocomplete(
  renderAutocomplete
);
```

The docs currently show to use it like this:

```
const customAutocomplete = instantsearch.connectors.connectAutocomplete(
  renderAutocomplete
);
```

Which was not working for me, so make sure to call `connectAutocomplete` by itself. Thought I would post my solution here in case anyone else ran into the same issue 👍

**Comment by brootle** [comment]
this error still in docs, see https://www.algolia.com/doc/api-reference/widgets/configure/js/#connector-param-render-refine

need to import connectConfigure, this fix below worked for me

`import { connectConfigure } from 'instantsearch.js/es/connectors';`

`const customConfigure = connectConfigure(
  renderConfigure,
  () => {}
);`
