### ISSUE TITLE
Arbitrary template variables

### ISSUE THREAD

**Issue by cloakedninjas** [algolia/instantsearch.js#3476]
**Feature request 🙏**
I would like to be able to pass an object of template variables into custom templates so I don't need to write custom render functions for widgets

Something that would look like this:

```
refinementList({
  container: '.container',
  templates: {
    item: myItemTemplate,
    templateData: {
      foo: 'bar'
    }
  }
});
```

Where `foo` is exposed for use inside the Handlebars template along with existing vars:

```
// myItemTemplate.hbs
<p>{{label}} ({{count}}) - {{ foo }}</p>
```

**Comment by francoischalifour** [comment]
I'll close this issue – feel free to reopen.
