### ISSUE TITLE
Question: Is there a way to know is it has a selected menu? 

### ISSUE THREAD

**Issue by danilowoz** [algolia/instantsearch.js#3480]
I don't know if it is a **feature request** or just a **question**, so: 
I want to make a different layout state if the user selects a menu, but I can't find a way to know if the menu is selected or not. I would like to keep it in an inner state in my search component. 

Is there any `onChange` or `onSelect` to handle it? 

Thanks

**Comment by danilowoz** [comment]
Sorry I'm using React, which repo should I report this question?

**Comment by francoischalifour** [comment]
Indeed, I removed the `react` topic.
