### ISSUE TITLE
Browser crash when going three levels deep in hierarchical

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#351]
An image is worth a thousand words:
![2015-10-26_12h20m41](https://cloud.githubusercontent.com/assets/283419/10727697/1b9665ea-7bdc-11e5-905e-be161df0d13d.gif)

No errors in console.

**Comment by redox** [comment]
I cannot reproduce it but it smells like an infinite loop while trying to iterate over the parents :) @pixelastic could you profile it?

**Comment by pixelastic** [comment]
Not right now, but yes, I'll have a look.

**Comment by vvo** [comment]
Cannot reproduce it also

**Comment by vvo** [comment]
Was able to reproduce it by clicking the exact same things than you :)

**Comment by vvo** [comment]
@pixelastic found the relevant loop, will let @redox handle it
