### ISSUE TITLE
Wrap the searchBox input in a BEM div

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#352]
I'm currently trying to replicate our magento styling into its own theme. Here is the current searchBox on Magento.

![image](https://cloud.githubusercontent.com/assets/283419/10729399/312de402-7be9-11e5-91ee-149faa05d6b6.png)

I wanted to add the small magnifying glass using `:after` pseudo-element, but it is not available on `input` elements.

I suggest we always wrap the `searchBox` inside its own `<div class="ais-search-box">`, so styling is made easier (and is more consistent with our other widgets).

WDYT?

**Comment by vvo** [comment]
You mean when the searchBox is generated by us we should wrap it?

**Comment by pixelastic** [comment]
I mean, with this html:

```html
<div id="search-parent" class="user-style">
  <input type="text" id="search" />
</div>
```

And this js:

```javascript
search.addWidget(
  instantsearch.widgets.searchBox({
    container: '#search',
    placeholder: 'Search for products'
  })
);
```

or this one:
```javascript
search.addWidget(
  instantsearch.widgets.searchBox({
    container: '#search-parent',
    placeholder: 'Search for products'
  })
);
```

The following markup should be generated:
```html
<div id="search-parent" class="user-style">
  <div class="ais-search-box">
    <input type="text" id="search" placeholder="Search for products" class="ais-search-box--input" />
  </div>
</div>
```

(Currently the `<div class="ais-search-box">` is missing, and that is what I want to add)

**Comment by vvo** [comment]
Careful, we decided to have a mode where we would not wrap the searchBox to specifically target a bug @redox was facing:
- https://github.com/algolia/instantsearch.js/issues/113
- https://github.com/algolia/instantsearch.js/issues/25

**Comment by pixelastic** [comment]
After discussing with @redox and @vvo we came to the conclusion that we should wrap the widget in its own div by default, but also create an option (`addDivWrapper: false`?) to disable this behavior if needed.

**Comment by vvo** [comment]
`wrapInput:true|false`?

I find it hard to reason "add: false" :)

**Comment by redox** [comment]
> wrapInput:true|false

:+1:
