### ISSUE TITLE
Can't resolve components/PoweredBy/PoweredBy.tsx

### ISSUE THREAD

**Issue by Spone** [algolia/instantsearch.js#3528]
**Describe the bug 🐛**
I can't import widgets with webpack, I get the following error:

    Failed to compile.
    
    ./node_modules/instantsearch.js/es/widgets/powered-by/powered-by.js Module not found: Error: Can't resolve '../../components/PoweredBy/PoweredBy.tsx'

**To Reproduce 🔍**

`yarn add instantsearch.js algoliasearch`

Add the following to my JS bundle, as explained in the docs:

    import algoliasearch from "algoliasearch/lite";
    import instantsearch from "instantsearch.js";
    import { searchBox, hits } from "instantsearch.js/es/widgets";

Try to bundle with webpack (I don't use TypeScript)

I get the following error:

    Failed to compile.
    
    ./node_modules/instantsearch.js/es/widgets/powered-by/powered-by.js Module not found: Error: Can't resolve '../../components/PoweredBy/PoweredBy.tsx' in '/home/hans/projects/myproject/node_modules/instantsearch.js/es/widgets/powered-by'
    @ ./node_modules/instantsearch.js/es/widgets/powered-by/powered-by.js 3:0-65
    @ ./node_modules/instantsearch.js/es/widgets/index.js
    @ ./frontend/packs/application.js
    @ multi (webpack)-dev-server/client?http://localhost:3035 ./frontend/packs/admin.js

It works if I comment out this line in `node_modules/instantsearch.js/es/widgets/index.js`

    // export { default as poweredBy } from './powered-by/powered-by';

I think you forgot a `tsx` import ;)

**Expected behavior 💭**
I should be able to use instantsearch.js with this basic setup.

**Environment:**
 - OS: Ubuntu
 - Browser: Firefox
 - Version 64

**Comment by francoischalifour** [comment]
Thank you for reporting the issue.

#3530 should fix this.

**Comment by francoischalifour** [comment]
Released in [3.1.1](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#311-2019-02-14).
