### ISSUE TITLE
getting output in json format

### ISSUE THREAD

**Issue by theshashiverma** [algolia/instantsearch.js#3529]
Hi I used this article https://community.algolia.com/instantsearch.js/v2/getting-started.html to add instansearch on my ruby on rails project, Everything is working fine, but its not loading the theme or the design, I am getting data in json format can you tell me how to show the css.
If you need any file let me know. Thanks

**Comment by Haroenv** [comment]
It would also be very useful to create what you have so far in a sandbox environment. We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

**Comment by francoischalifour** [comment]
If you're getting started with InstantSearch.js, we recommend using [InstantSearch.js 3](https://www.algolia.com/doc/guides/building-search-ui/installation/js/). There's a section explaining [how to load the style](https://www.algolia.com/doc/guides/building-search-ui/installation/js/#load-the-style).
