### ISSUE TITLE
Widget Event

### ISSUE THREAD

**Issue by fvoverscan** [algolia/instantsearch.js#3531]
HI,

I need to do something when user change element on menuSelect (or for exemple when user refine an element on refinementList).

Is there an event trigger that i could use ?

I don't want to create a custom menuSelect just for this... 

I see this https://github.com/algolia/instantsearch.js/issues/83 but it's close and not really answer the question.

Thanks

**Comment by samouss** [comment]
At the moment there is no event triggered by InstantSearch each time something is refined. A possible solution is to leverage [the routing system](https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/?language=js#widget-param-routing) to detect changes. But keep in mind that it was not designed for that and might not completely solve your use case. The safer solution would be unfortunately to build a custom widget.

**Comment by fvoverscan** [comment]
@samouss 

I have a workaround for the menuSelect : 

```
search.on('render', function(){
// target.event here
})
```

I could target the select event when rendering.

But it's not really clean...

Thanks,
