### ISSUE TITLE
Applying CSS styles to connectMenu item removes "isRefined" functionality

### ISSUE THREAD

**Issue by fujiii** [algolia/instantsearch.js#3548]
Hi! I took for example this tutorial from official documentation: [Customize widgets](https://community.algolia.com/instantsearch.js/v2/guides/customization.html)

Remade it to suit my needs, basically just changed `<select>` to `<ul>` and `<option>` to `<li>`.

Now when trying to customize `<li>` (which is connectMenu Item) through CSS, somehow magically "isRefined" stop working and does not apply class to `<li>`. I spent like 2 days figuring out and coming up to this point.

**Comment by fujiii** [comment]
Super funny and frustrating, since applying example to me needs (ul, li), I made this part in the code:

`MenuRenderingOptions.refine(event.target.innerText);`

And in styles I actually transformed this to uppercase and that's why everything failed...

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

**Comment by fujiii** [comment]
> Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

Hi, not sure what was that, maybe just tiredness, then everything worked with uppercased values as well. Sorry for the fake alarm :)

**Comment by fujiii** [comment]
> Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

Hi, not sure what was that, maybe just tiredness... Sorry for the fake alarm :)
