### ISSUE TITLE
Guidance: Re-render InfiniteHits based on time without calling search api

### ISSUE THREAD

**Issue by reedyrm** [algolia/instantsearch.js#3560]
**Is your feature request related to a problem? Please describe 🙏**
I have an index that contains Restaurants where each restaurant has a specific open/close time and location which depending on the day of week/time in the object.  Depending on the time when the Restaurant object is rendered, it may appear in my results or not.  I'm looking for a way to re-render my current results as the time changes without making a new API call.

**Describe the solution you'd like 🤔**
I want to re-render a Custom Component that is wrapped in the connectInfiniteHits without making an additional call to the Algolia API.

**Describe alternatives you've considered ✨**
My first reaction is to use a piece of state that is updated every minute that is used as part of the key in the render, but I think that would call the Algolia API to get more results

**Additional context**

I'm looking for guidance on how I would re-render a Custom Component using connectInfiniteHits.

**Comment by samouss** [comment]
The easy way to re-render is indeed to call the Algolia API every N seconds/minutes. If you don't want to go that path you can save the last `renderOptions` and call the `render` function with the saved values + the updated value. Here is [an example](https://codesandbox.io/s/882lr0v159) that show how to implement this solution. It's not the more elegant solution but it works.

**Comment by reedyrm** [comment]
This is perfect.  Thanks for your response!
