### ISSUE TITLE
Add typings for TypeScript

### ISSUE THREAD

**Issue by denysovkos** [algolia/instantsearch.js#3562]
Hi!
It is mostly impossible to use instantsearch.js without typing in Angular4+
Please, add them to @types

**Comment by Haroenv** [comment]
You can add empty typings in your own project in the mean time. Eventually we will publish typings here when we migrated to typescript in a sufficient manner. 

You can also use Angular InstantSearch which is typed (and inside of it it has minimal definition for InstantSearch.js too)

**Comment by denysovkos** [comment]
I added declare module 'instantsearch.js/es/connectors' , but:

ERROR in component.ts(3,39): error TS7016: Could not find a declaration file for module 'instantsearch.js/es/connectors'. /node_modules/instantsearch.js/es/connectors/index.js' implicitly has an 'any' type.
  Try `npm install @types/instantsearch.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'instantsearch.js/es/connectors';`

**Comment by Haroenv** [comment]
This will be done starting on an experimental tag, explanations here will follow

**Comment by mohamednaleem** [comment]
I am also facing the same error. please let me know, Do we have the fix without using the experimental tag in the package.json.

**Comment by Haroenv** [comment]
You should use the experimental tag for now @mohamednaleem, it's almost complete
