### ISSUE TITLE
partialUpdateObject is not a function

### ISSUE THREAD

**Issue by Lovely-Fellow** [algolia/instantsearch.js#3580]
I'm going to use partialUpdateObject for updating one attribute by ObjectID.
But not working.
"TypeError: index.partialUpdateObject is not a function" is occured.
But index.search is working.
Following code shows my code.
JS:
const client = algoliasearch(API_ID, AdminAPIKey);

  // 1. Initialize the target and temporary indices
  const index = client.initIndex(INDEXNAME);

index.search({ query: 'query string' }, (err, content) => {
  if (err) {
    console.log(err);
    console.log(err.debugData);
    return;
  }
  console.log(content.hits);
});

index.partialUpdateObject({
  test_attribute: 'testvalue',
  objectID: 'XXX'
}, function (err, content) {
  if (err) throw err;

  console.log(content);
});

HTML:
    <script src="https://cdn.jsdelivr.net/npm/algoliasearch@3.32.0/dist/algoliasearchLite.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@3.0.0"></script>

What do I have to do for partialUpdateObject?
Do I have to run following npm commands? If then, where do I have to run?
npm install --save algoliasearch
npm install --save-dev @types/algoliasearch

Thank you.

**Comment by tkrugg** [comment]
Hi there!

You are using the lighter version of the client: `algoliasearchLite.min.js`. 
```html
<script src="https://cdn.jsdelivr.net/npm/algoliasearch@3.32.0/dist/algoliasearchLite.min.js"></script>
```
That one allows only to search in an index as explained [here](https://www.algolia.com/doc/api-client/getting-started/install/javascript/?language=javascript#search-onlylite-client). Just use `algoliasearch.min.js`  and it should work as expect.

⚠️ Side note: I suspect you're using your Admin API key in client side code. This key is very sensitive and using it in code that runs on the client leaks it.

Please refer to our docs to make sure you're using it right: https://www.algolia.com/doc/guides/security/api-keys/?language=javascript#admin-api-key

I hope this helps. I'm closing this for now but feel free to reopen it!
Thank you for reaching out.

**Comment by Lovely-Fellow** [comment]
Hi, tkrugg.

Working now by using algoliasearch.min.js.
Thank you for your help.
