### ISSUE TITLE
Issue while using getObject.

### ISSUE THREAD

**Issue by Lovely-Fellow** [algolia/instantsearch.js#3582]
Hi.
Please check my code.

```js
var gotObject = 0;
var objectID = 131280480;
var client = algoliasearch('B1G2GM9NG0', 'aadef574be1f9252bb48d4ea09b5cfe5');
var index = client.initIndex('demo_ecommerce');
function did_read() {
  index.getObject(objectID, ['name'], function(err, content) {
    console.log(content);
    gotObject = 1;
  });
  return gotObject;
}

console.log(did_read());
```

I want to print console log like follwoing.
Apple - iPhone 7 32GB - Black (Verizon)
1

But now I can see the console log like following
0
Apple - iPhone 7 32GB - Black (Verizon)

https://codesandbox.io/s/wyo47o6vp8

I also try to use 'waitTask', but also not working.
https://codesandbox.io/s/k26nvlvy13

**Comment by Haroenv** [comment]
The code you are trying to do is mixing asynchronous and synchronous code. You can use the callback form or the promise form of `getObject`, but you'll always have the same issue. You can read up on that concept here: https://eloquentjavascript.net/11_async.html
