### ISSUE TITLE
Question: using 'numericMenu' for date range

### ISSUE THREAD

**Issue by daanvosdewael** [algolia/instantsearch.js#3584]
I have a layout that displays Agenda items based on a start and end date. What I would like to have is a `<select>` element to filter the items on:

- All
- This week
- This month

The widget [numericMenu](https://www.algolia.com/doc/api-reference/widgets/numeric-menu/js/) looks like the right candidate for the job, as it can be used to set specific bounds for each option. In my case that would be the beginning and ending of the current week or month. The problem is that it only accepts an `attribute` as a string for a single value. I have two values, start and end date.

So for example:
> An Agenda item starts at **March 4, 2019** and ends at **March 15, 2019**
> When selecting 'This week' the item should only show in **week number 10 & 11**
> When selecting 'This month' the item should only show in **March**

Is there a way to accomplish this?

**Comment by Haroenv** [comment]
This is indeed a very complex and interesting use case that we currently don't cover. We've made an example on how to do this kind of use case with React InstantSearch, but not yet with InstantSearch.js. Does the behaviour in https://codesandbox.io/s/kwklo3rz63 describe your use case? You can make something similar to this with InstantSearch.js connectors.

When you are talking about start and end date, do you expect the filtering to be overlapping that date completely, or just including?

**Comment by francoischalifour** [comment]
We made a [calendar widget demo](https://instantsearchjs.netlify.com/examples/calendar-widget/) ([see source code](https://github.com/algolia/instantsearch.js/blob/0a816c684407c421acd7244fab23736b29ea0d1b/website/examples/calendar-widget/app.js)).

You should be able to achieve this behavior with the [`connectRange`](https://www.algolia.com/doc/api-reference/widgets/range-input/react/#connector) connector. The main constraint being that the dates must be timestamp numbers.

**Comment by dhayab** [comment]
Closing this issue as the exact behavior (refining on both a start and end date) is unlikely to be implemented in a widget. This can likely be achieved using a custom widget.
