### ISSUE TITLE
Widget proposal: clearAll

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#359]
It would be good to be able to have a very simple widget that allows you to clear all the refinements and current query.

It's like a "start over" button in case of emergency/lost user.

# API

```js
search.addWidget(
  instantsearch.widgets.hitsPerPageSelector({
    container: '#clear-all-selector',
    // cssClasses: {root, header, body, link, footer}
    // templates: {header, body, footer}
    // label: clear all
    // hideContainerWhenNoRefinements: true
  })
);
```

Default rendering output:

```html
<div class="ais-clear-all">
  <div class="ais-clear-all--header ais-header">[custom header template]</div>
  <div class="ais-clear-all--body">
      <a class="ais-clear-all--link" href={url}>clear all</a>
  </div>
  <div class="ais-clear-all--footer ais-footer">[custom footer template]</div>
</div>
```

Data passed to the item template:
- url, in case you want to have a link instead of a button
- label

Put the onClick on the item template, like it's done for toggle

**Comment by vvo** [comment]
@pixelastic I would like your input on this one :)

**Comment by Shipow** [comment]
I would prefer a span for the icon (and template for class or content). That should help css to use font icons easier.
<button class="ais-clear-all--button"><span class="ais-clear-all--icon">❌</span> clear all</button>

**Comment by vvo** [comment]
^ updated with this, very nice

**Comment by pixelastic** [comment]
I'm ok with creating this widget, this is definitely needed.

1. I don't think the wrapping `<div class="ais-clear-all--item">` is needed. The `--item` class is used when there is several elements (like for a refinement list). When there is only one button, I would get rid of it.
2. I would not add a `span` or a `i` for the icon, and let the `theme.css` handle that (using `:before`). If people really want to add an icon, they could add it in a custom template. We need to have the bare minimum markup to make the `default.css` theme usable, no more.
3. I'd rather pu a `a` than a `button` (we already have `a` everywhere)
4. Not sure we need the header/footer for that one.

**Comment by vvo** [comment]
> I don't think the wrapping <div class="ais-clear-all--item"> is needed. The --item class is used when there is several elements (like for a refinement list). When there is only one button, I would get rid of it.

I also thought the same but toggle has label + item and found that maybe we should do the same here?

> I'd rather pu a a than a button (we already have a everywhere)

Indeed, passing a `<a>` to a button is only some css while passing a button to an `<a>` is tricky.

> Not sure we need the header/footer for that one.

Since it could be located on the left top refinement list, maybe we still need it. Also more consistent to have it everywhere (but the hits).

> I would not add a span or a i for the icon, and let the theme.css handle that (using :before). If people really want to add an icon, they could add it in a custom template. We need to have the bare minimum markup to make the default.css theme usable, no more.

Not sure about your proposition

**Comment by maxiloc** [comment]
Could we add an option to be able to clear:
- Refinements only
- Query only
- Refinements and Query

**Comment by vvo** [comment]
> Query only

Not sure about clearing the query only

**Comment by Shipow** [comment]
If we are talking about clearing the query, I may have an idea for the search box :)

**Comment by vvo** [comment]
> If we are talking about clearing the query, I may have an idea for the search box :)

Yes clearing only the query seems like a searchBox option

**Comment by maxiloc** [comment]
:+1:

**Comment by pixelastic** [comment]
> I also thought the same but toggle has label + item and found that maybe we should do the same here?

Toggle has an item wrapper because it internally uses the `refinementList` component (but only display one item). I'd rather we fix it in toggle than adding it in this widget :)

Makes sense to keep the header/footer, I agree.

Regarding the `span`/`i` for the icon: I think the icon is a secondary concern for this widget. It is not needed to make the widget work, it is only styling. So I would not add any markup for it in the default template. Like we would no add a `strong` node around active element in default template, we should not add a `span` to denote a possible icon in the default template. This can be handled through either CSS or custom templates.

**Comment by vvo** [comment]
> Like we would no add a strong node around active element in default template, we should not add a span to denote a possible icon in the default template. This can be handled through either CSS or custom templates.

Ok right makes sense

**Comment by vvo** [comment]
> Toggle has an item wrapper because it internally uses the refinementList component (but only display one item). I'd rather we fix it in toggle than adding it in this widget :)

Hm I think it did not have one at first and then we made it so for consistency (https://github.com/algolia/instantsearch.js/commit/498bad6a299b9997a3fe12985b52b44e246c5fde). We had the discussion together I believe.

**Comment by vvo** [comment]
> Like we would no add a strong node around active element in default template, we should not add a span to denote a possible icon in the default template. This can be handled through either CSS or custom templates.
> Ok right makes sense

On the other hand, if by default there's a cross, should it be in default.css or in the default template? (much like the css/input checkbox discussion we had).

**Comment by pixelastic** [comment]
> Hm I think it did not have one at first and then we made it so for consistency (498bad6). We had the discussion together I believe.

In my head the consistency was more about naming it `item` instead of `body`. If there is to be a list of one `item`, let it at least be named `item`. I can understand there is some display consistency between a `toggle` and a `refinementList`, so using the same markup makes sense. But for a `clearAll`, I would go without the superfluous `item` here.

> On the other hand, if by default there's a cross, should it be in default.css or in the default template? (much like the css/input checkbox discussion we had).

There's a bit of déjà-vu here :). I also think the icon is not mandatory for the widget to work, nor for the user to understand how it works. A simple link/button with "Remove all filters" is more explicit than the icon. So I would put it in the themes.

**Comment by vvo** [comment]
> There's a bit of déjà-vu here :). I also think the icon is not mandatory for the widget to work, nor for the user to understand how it works. A simple link/button with "Remove all filters" is more explicit than the icon. So I would put it in the themes.

WFM

**Comment by vvo** [comment]
@pixelastic I updated the widget proposal, let me know

**Comment by pixelastic** [comment]
WFM regarding the markup.

But I do not understand the difference between `disableWhenNoRefinements` and `hideContainerWhenNoRefinements`.

**Comment by vvo** [comment]
Yep sorry, updated

**Comment by pixelastic** [comment]
Looks good :+1:

**Comment by redox** [comment]
I think that widget should be merged with #112 -> it's very similar & you generally have that "clear all" button next to the active refinements..

**Comment by vvo** [comment]
> I think that widget should be merged with #112 -> it's very similar & you generally have that "clear all" button next to the active refinements..

Not against it, we only need a precise api proposal for this one and then we are good

**Comment by Jerskouille** [comment]
Here is the API I'm going for (using #378) :

```js
instantsearch.widgets.clearAll({
  container: '#clear-all-link',
  cssClasses: {root, header, item, link, footer},
  templates: {
    header: '',
    item: '<a class="{{ cssClasses.link }}" href="{{url}}">Clear all</a>', // Called with {cssClasses, url}
    footer: ''
  },
  hideContainerWhenNoRefinements: true
})
```

I didn't include the `label` parameter from the main API proposal because we don't have it in the stats widget.

**Comment by redox** [comment]
Oh I would rename `clearAll` to `clearAllRefinedValues` to make it more clear (and fit the other widget's naming).

**Comment by pixelastic** [comment]
@redox :+1:, making it clearer

Still not sure we need to wrap the link in an `item` element, but WFM anyway.

**Comment by Jerskouille** [comment]
:+1:

**Comment by vvo** [comment]
Is this issue still the one we are working on? The API proposal seems outdated.

**Comment by vvo** [comment]
If you have a final widget proposal, best option is to reopen a new issue and close this one to avoid confusions
