### ISSUE TITLE
[pagination]: allow specifying labels as html

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#36]

**Comment by pixelastic** [comment]
I'm not sure I get what this issue is about. Is that the ability to use "Next" and "Previous" strings instead of ">" and "<"?

**Comment by redox** [comment]
> I'm not sure I get what this issue is about. Is that the ability to use "Next" and "Previous" strings instead of ">" and "<"?

Yes, or even more complex like: `<i class="fa fa-chevron-right"></i> Next`

**Comment by pixelastic** [comment]
This should be handled by some custom templates, but we need to find a way to define several templates for one element.

Maybe the `template` key for this widget could be an object like this:

```javascript
{
  first: '<a href="{{url}}"><i class="fa fa-chevron-right"></i></a>',
  previous: '...',
  page: <a href="{{url}}">{{page}}</a>',
  next: '...',
  last: '...'
}
```

**Comment by vvo** [comment]
I think I already allowed html in pagination widget :)

**Comment by vvo** [comment]
I meant, you can already provide html code for labels so we can close this one.

Proof: https://github.com/algolia/instantsearch.js/blob/3cc80f565dec97d5f4ecd6f7f8bcdfbebfd6c1ac/components/Pagination/PaginationLink/index.js#L26
