### ISSUE TITLE
Module not found: Error: Can't resolve '../../components/SearchBox/SearchBox'

### ISSUE THREAD

**Issue by daanvosdewael** [algolia/instantsearch.js#3611]
**Describe the bug 🐛**
In PR #3489 the `SearchBox` component was renamed from lowercase **'b'** to uppercase:

```diff
-src/components/SearchBox/Searchbox.js
+src/components/SearchBox/SearchBox.js
```

This is reflected in the repo but not when the package is pulled down from NPM. This results on Linux in a `Module not found` error. Strangely on macOS the file *is* found and the file mismatch doesn't trigger an error.

**To Reproduce 🔍**
1. Install `instantsearch.js` package with either npm or yarn
2. Check that the `SearchBox` component file in `node_modules` is with lowercase **'b'**

**Comment by francoischalifour** [comment]
This is indeed very annoying.

None of the [CJS](https://unpkg.com/instantsearch.js@3.2.0/cjs/components/SearchBox/) or [ES](https://unpkg.com/instantsearch.js@3.2.0/es/components/SearchBox/) export names were updated on the npm registry.

I'll have a deeper look tomorrow.

**Comment by Haroenv** [comment]
This was likely because the name change didn't change in git? I know changing a name where only the casing changes on Mac is easy to have errors

**Comment by francoischalifour** [comment]
The [file is correctly named](https://github.com/algolia/instantsearch.js/blob/ac669699d2436cf52955186935bb542e2b3ab42e/src/components/SearchBox/SearchBox.js) on GitHub so I would expect npm to behave the same way.

When cloning the repo or running `yarn build`, the files also are named correctly.

**Comment by francoischalifour** [comment]
You can upgrade to version 3.2.1 to fix the issue (see [ES](https://unpkg.com/instantsearch.js@3.2.1/es/components/SearchBox/) and [CJS](https://unpkg.com/instantsearch.js@3.2.1/cjs/components/SearchBox/) `SearchBox` exports).

Thank you for reporting!
