### ISSUE TITLE
sortBySelector not working anymore when set customRanking

### ISSUE THREAD

**Issue by fvoverscan** [algolia/instantsearch.js#3615]
Hi,
I have setSetting my index to update customRanking field.

I have updated from 
```
customRanking: [
            "desc(best_offer.last_modified)"
        ],
```
To
```
customRanking: [
             "desc(stock)",
             "desc(created_on)",
             "desc(last_modified)"
        ],
```
I have this parameters enable :
```
forwardToReplicas: true
```

My initial index work great with this parameters but when i change the index with sortBySelector widget, it don't sort anymore  !

I reverse to the original customRanking config but now it don't sort too...

Could you help me please ?

**Environment:**
 - I use the CDN version of algoliasearch : https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js
 - Version instantsearch.min.js 2.10.3

Thanks

**Comment by Haroenv** [comment]
It doesn't look like your issue is with InstantSearch.js, but rather with Algolia in general. Could you however tell the difference between the two indices? I assume maybe there is no longer a difference between your sorted index, and the regular one

**Comment by fvoverscan** [comment]
My replicas are sorting the index by price asc and desc...

**Comment by Haroenv** [comment]
If the change shouldn't be forwarded to the replicas, then you shouldn't check that indeed

**Comment by fvoverscan** [comment]
Yes it was the forwardToReplicas...

Thanks... issue resolved
