### ISSUE TITLE
How to make show-more button in hierarchicalMenu?

### ISSUE THREAD

**Issue by SchmidtDawid** [algolia/instantsearch.js#3628]
I tried like this:
```
var CustomHierarchicalMenuWidgetOptions = {
    container: '#hierarchical-categories',
    attributes: ['hierarchicalCategories.lvl0', 'hierarchicalCategories.lvl1', 'hierarchicalCategories.lvl2', 'hierarchicalCategories.lvl3', 'hierarchicalCategories.lvl4'],
    limit: 100, 
    showParentLevel: true,
    autoHideContainer: true,
    templates: {
      header: getHeader('Kategorie'),
      item: '<a href="{{url}}" class="facet-item "><span class="facet-name"><span class="icon"></span><span>{{label}}</span></span></a>'
    }
  }
  function renderFn3(HierarchicalMenuRenderingOptions) {
    var container = HierarchicalMenuRenderingOptions.widgetParams.container;
    console.log(HierarchicalMenuRenderingOptions)
    console.log(container)
  }
  var makeHierarchicalMenu= instantsearch.connectors.connectHierarchicalMenu(renderFn3);
  
  var  customHierarchicalMenu = makeHierarchicalMenu(CustomHierarchicalMenuWidgetOptions);
  search.addWidget(customHierarchicalMenu);
```
console.log(HierarchicalMenuRenderingOptions) looks nice, but it does not render anyway. I dont have idea why. 
Link to complete example is 404..
I don't have idea what to do next after render custom widget anyway. Can you help?

**Comment by Haroenv** [comment]
There's a full example here, where did you get a 404? https://www.algolia.com/doc/api-reference/widgets/hierarchical-menu/js/#full-example

**Comment by SchmidtDawid** [comment]
On this page: https://community.algolia.com/instantsearch.js/v2/connectors/connectHierarchicalMenu.html
This link: https://github.com/algolia/instantsearch.js/blob/develop/dev/app/jquery/widgets/hierarchicalMenu.js

**Comment by francoischalifour** [comment]
We need to update the links in the v2 documentation indeed.

The link is available on the `v2` branch: https://github.com/algolia/instantsearch.js/blob/v2/dev/app/jquery/widgets/hierarchicalMenu.js.

**Comment by Haroenv** [comment]
So to be clear, is the information you got working for you now @SchmidtDawid ?

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
