### ISSUE TITLE
The URL and widgets out of sync

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3629]
**Describe the bug 🐛**

Currently, the URL and the state of the UI became out of sync after a page refresh.

**To Reproduce 🔍**

1. Go to https://87b2c.codesandbox.io/
2. Search for "Phone"
3. Click on "Speck"
4. Click on "OtterBox"
5. Reload the page
6. Click on the browser back button
7. Click on the browser back button
8. The state of the URL is not synced with the widgets

The `refinementList` contains two refinements but the URL only contains the `query`. The URL should drive the search and the UI but it's not the case. The issue occurs for two reasons:

1. We're not able to compute the parameters of a widget with only `getWidgetSearchParameters` function. We also depend on the `getConfiguration` lifecycle. That's why we use [the state of the first render](https://github.com/algolia/instantsearch.js/blob/ca8ae5018b93b98e663b623c2ba829b01a7f2861/src/lib/RoutingManager.js#L60-L64) to create the new `SearchParameters` on `router.update` (`popstate`). Note that we capture it on the first render and we never update it. It leads to issue once we remove a refinement that was part of this initial state. We could always use the latest up to date state (`helper.state`) but it won't completely solve the issue because of the point below.
2. The function `getWidgetSearchParameters` don't use the `uiState` as source of truth. At step 8 the `uiState` does not contain anything related to the `refinementList` [so we return the `SearchParameters` untouched](https://github.com/algolia/instantsearch.js/blob/ca8ae5018b93b98e663b623c2ba829b01a7f2861/src/connectors/refinement-list/connectRefinementList.js#L412). Since we get the state of a previous render the refinements are still applied on the `SearchParameters`. We should [clear the refinement](https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/refinement-list/connectRefinementList.js#L418) for the attribute in any cases and re-apply the refinement from the values in the `uiState`. 

**Ideas to fix the issue:**

An intermediate solution to fix this issue is to:

1. always use the latest state inside the `router.update` callback (like we already do inside [`onHistoryChange`](https://github.com/algolia/instantsearch.js/blob/ca8ae5018b93b98e663b623c2ba829b01a7f2861/src/lib/RoutingManager.js#L162))
2. update the `getWidgetSearchParameters` lifecycle to clear the previous state of the part that is controlled by the widget. We can safely then re-apply the refinement with the value stored inside the `uiState`.

The optimal solution would be to have a `getWidgetSearchParameters` that is self-contained. Right now it's not the case, the widget depends on `getConfiguration` + `getWidgetSearchParameters` to compute the `SearchParameters`. But with a self-contained function we could compute the `SearchParameters` from a fresh state and avoid the issue describe above (which also means that we can get rid of `getConfiguration` at the same time). It requires a breaking change.

**Environment:**

The issue occurs with all the version of InstantSearch that supports `routing`.

**Comment by Haroenv** [comment]
This is fixed in v4, since we redesigned connectors to be self-contained with getWidgetSearchParameters & getWidgetState.
