### ISSUE TITLE
Issue with Selector rendering

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#365]
On Firefox 41.0.2, I get this weird issue on a value selection where it displays: 
- The selected option
- The first option for a fraction of a sec
- The selected option back again

![selector bug](https://cloud.githubusercontent.com/assets/5095856/10756357/d62e3f00-7ca3-11e5-9eae-a754f518dcc6.gif)

It seems like `render` is only called once, but I believe the issue might be caused by the replacement of the select in the DOM.

**Comment by vvo** [comment]
Maybe linked to the state change/url sync where both the widget/url are fighting to render. But if render is called once, weird

**Comment by redox** [comment]
I rather think it's because the `<option>` tag doesn't have any `selected` attribute at first, what do you think?

**Comment by Jerskouille** [comment]
I agree with that @redox , I was thinking of adding `selected`, but @pixelastic was thinking that we should let React handle this.

**Comment by vvo** [comment]
Ah yes indeed on first load we need the selected attribute to be present, it seems a good practice. But we should not have to then update it.

**Comment by Jerskouille** [comment]
Actually, the `select` is replaced at each selection since it causes the state to be modified and triggers a `render`, so I believe we should have it all the time if we choose to add it.

**Comment by Jerskouille** [comment]
I've just tried using `selected` on the option, React sends back a warning: `Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.`.

**Comment by Jerskouille** [comment]
Oh and when I said only "once", it was once per selection.

**Comment by vvo** [comment]
Relevant? https://facebook.github.io/react/docs/forms.html#why-select-value

> Actually, the select is replaced at each selection since it causes the state to be modified and triggers a render, so I believe we should have it all the time if we choose to add it.

That's really weird if we are removing/replacing a whole select each time a value is selected, it means we are doing it wrong right?

**Comment by vvo** [comment]
There should be no need to call ReactDOM.render if the currently selected option in the select is the same from the helper state. Maybe we can try this

**Comment by Jerskouille** [comment]
I'd love to get some input from @bobylito because I'm making a lot of guesses here.

**Comment by bobylito** [comment]
This is the classic controlled component effect that the widgets suffer of because we only update after the result of the search. The lag is due to the time we wait for the answer.

**Comment by redox** [comment]
> This is the classic controlled component effect that the widgets suffer of because we only update after the result of the search. The lag is due to the time we wait for the answer.

But if we go for a hard-coded "selected" option, it will "work/fix"; right?

**Comment by bobylito** [comment]
We should use `defaultValue` https://facebook.github.io/react/docs/forms.html#uncontrolled-components

**Comment by bobylito** [comment]
Actually the true fix would be to have a lifecycle bind to the state change so that we could continue to use controlled component with minimun lag.

**Comment by vvo** [comment]
@maxiloc do you know what is the state of this one? (I saw you added "to be released" while I am unsure what we need to do here..)

**Comment by vvo** [comment]
Ok we need another issue if there's still something to do, too hard to get what's going on for now here.
