### ISSUE TITLE
Render called twice with number values + urlSync

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#366]
The `hitsPerPageSelector` widget uses `helper.setQueryParameter('hitsPerPage', value)` with `value` being a `Number`.
The issue is that it causes `render` of the widget to be called twice, once with the `Number` value and the other time with a `String` value.
The easy workaround would be to use `helper.setQueryParameter('hitsPerPage', '' + value)`, but it might maybe make sense to set up expected types in the helper and automatically cast.
What do you think?

**Comment by vvo** [comment]
> The issue is that it causes render of the widget to be called twice, once with the Number value and the other time with a String value.

But why does it does that?

**Comment by Jerskouille** [comment]
I believe that this is how it goes:
- We're setting the local state with `hitsPerPage: 6`
- The URL gets updated with `hPP=6`
- The URL was updated, so the URL sync widget checks if the state of the URL matches the local state
- It doesn't, since the state from the URL is `hitsPerPage: "6"`
- The local state gets updated with `hitsPerPage: "6"`, this triggers a `render` on all widgets

**Comment by vvo** [comment]
This one seems like an helper issue indeed.

**Comment by bobylito** [comment]
Yep it can be fixed in the helper. On it!

**Comment by bobylito** [comment]
I've tested with the branch. Just need the PR on the helper to be merged https://github.com/algolia/algoliasearch-helper-js/pull/246
