### ISSUE TITLE
windowTitle does not trigger when page loads

### ISSUE THREAD

**Issue by sparanoid** [algolia/instantsearch.js#3667]
**Describe the bug 🐛**
The `windowTitle` option for routing does not trigger when the page first loads.

**To Reproduce 🔍**
This issue can be easily reproduced via official SEO friendly URLs demo

1. Open demo via [CodeSandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/routing-seo-friendly)
2. Run the demo and click "Open in New Window"
3. Type something to search, notice the title change
4. Refresh the page using browser reload.
5. Title does not change.

**Expected behavior 💭**
The page title should contains correct queries from `windowTitle` after page reload.

**Screencast 🎬**
https://www.useloom.com/share/96c3c8f3329041c7bc6d74e232812ad4

**Environment:**
 - OS: macOS
 - Browser: Google Chrome
 - Version: 73.0.3683.86

**Additional context**

**Comment by francoischalifour** [comment]
Thank you for reporting the issue. This is address in #3669.
