### ISSUE TITLE
Question : How do you use queryParameters with url routing ?

### ISSUE THREAD

**Issue by tdutreui** [algolia/instantsearch.js#3692]
Hi

I created a simple widget to set the 'aroundRadius' query parameter.
It works well except when it comes to use `stateMapping` :
* in stateToRoute, `aroundRadius` is missing from the argument, so I get to set it that way : 
```
      stateToRoute: uiState => {
          return {
            q: uiState.query,
            r: this.mainSearch.helper.state.aroundRadius //sadly, uiState.aroundRadius is undefined
          };
        },
```
* in routeToState, I'm just unable to map the http parameter back to the state : 
```
routeToState: routeState => {
          return {
            query: routeState.q,
            aroundRadius: routeState.r // this does not work as when refreshing the page with the "r" param, the aroundRadius query param sticks set to its default value. 
          };
        }
```
As a result, I manually parse the http parameter and set the 'aroundRadius' parameter on the page initialization.
What is the proper way to handle query parameters with url routing ?
Thanks 
Thomas

**Comment by Haroenv** [comment]
Data will only appear in the URL if the custom connector has the following two life cycles too:

- `getWidgetState(uiState, { helper, searchParameters }): UIState` (merged with existing UIState)
- `getWidgetSearchParameters(searchParameters, { uiState }): SearchParameters` (merged with existing search parameters, usually using helper methods)

**Comment by tdutreui** [comment]
Oh, I need to upgrade to v3 for that, I'm still using v2. Any solution in v2 ?
I created the widget following the v2 guide https://community.algolia.com/instantsearch.js/v2/guides/custom-widget.html

**Comment by Haroenv** [comment]
This should also work with v2, as long as you're using `routing`

**Comment by tdutreui** [comment]
Excellent ! It works well, maybe it's necessary to complete the v2 documentation ? (maybe not, anyway v2 will soon be obsolete I guess)

Congrats to the team & community for this library, it rocks!

**Comment by Haroenv** [comment]
V2 documentation is indeed something we will no longer work on, but the migration to v3 should be fairly smooth: 

https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/#upgrade-from-v2-to-v3
