### ISSUE TITLE
[pagination]: show `<<, <, >, >>` by default (even when not clickable), provide an option to hide them

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#37]
One issue with the current implementation is that when we automatically hide the `<<, <, >, >>` if not needed.

This might be a problem in some implementations where the user do not want this behavior.

What we can do:
- when not needed, render `<<, <, >, >>` without a wrapper `<a></a>` (so, not a link)
- provide an option (`autoHideNavigation`) to automatically hide them (visibility:hidden to maintain horizontal space, we still need to render them).

**Comment by pixelastic** [comment]
I would keep the same generic markup for both cases (ie. adding a `<a href="#"></a>` when no such page  ), but would disable them using CSS.

I think the `pointer-events:none` will disable the click on the element while `cursor: not-allowed` will visually show that this will not work (see a [bootstrap example](https://bootstrap.algolia.com/components/#disabled-and-active-states).

But agreed that we should let the user choose its favored behavior in the widget configuration. We could even provide several values, like `hide` or `showDisabled`. The display behavior would simply be changed with a switch of a css class on the widget.
