### ISSUE TITLE
headerFooter adds too much markup

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#370]
Currently, all the widgets that implement the `headerFooter` decorator will generate a `<div class="ais-header">` and `<div class="ais-footer">` markup before and after. This occurs even if the said header and footer templates are empty.

While implementing the ecommerce theme, I tried to replicate the default `header` style like this:
![image](https://cloud.githubusercontent.com/assets/283419/10763274/a15a532e-7cc9-11e5-9b8c-a7d6b36d4f95.png)

This works well for any widget that should appear in an e-commerce sidebar but does not work with other widgets like the `stats`:
![image](https://cloud.githubusercontent.com/assets/283419/10763294/b00abd46-7cc9-11e5-80da-01ff9da8c0ce.png)

I'm not sure how to tackle that one. Maybe only adding the markup if a template for header/footer is passed as well? This would work for me, but do you see any issue in doing it that way?

**Comment by vvo** [comment]
No indeed it should be ok to do so (not adding the header/footer markup if no need to). Try it

**Comment by pixelastic** [comment]
Will give it a go then.
