### ISSUE TITLE
Url generation from parameters

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#372]
For some integration like Magento, to load the instant search page with good params, the easiest way is to generate the (url) hash of the query and redirect to it. That way instantsearch will load on it's on.

Right now the url is hardcoded in the code which is not the cleaner way to do it.

A solution can be to instantiate a helper but that's not perfect to.
Adding this function to instantsearch could be useful

For a set of refinements like ```{query: "madison}``` or ```[{query: "", refinements: ["category:Shirt"]}``` the idea would be to generate something like ```#q=madison&idx=...```

Also if this could be done without instantiating instantsearch it would be even better

**Comment by redox** [comment]
Yes, the widgets are already using a `createURL` method to handle such use-case. @bobylito any chance we could expose it in the `instantsearch` object we're returning?

**Comment by redox** [comment]
So the resulting instantsearch instance has already a `createURL` method; the only limitation is that it takes a `SearchParameters` (state) instance in argument. I'll propose something.

**Comment by redox** [comment]
So you can do something like:

```js
// with an instantsearch instance:
var search = instantsearch(....);
search.createURL({facetsRefinements: {category: 'Home'}});

// or by just calling the static method:
window.location.href = '....' + instantsearch.createQueryString({facetsRefinements: {category: 'Home'}});
```
