### ISSUE TITLE
render "hierarchicalMenu"

### ISSUE THREAD

**Issue by eliprodigy** [algolia/instantsearch.js#3726]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[hierarchicalMenu](https://community.algolia.com/instantsearch.js/v2/widgets/hierarchicalMenu.html)".

**Comment by Haroenv** [comment]
Hi @eliprodigy, you didn't give any information in this issue. What do you have an issue with?

Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

**Comment by eliprodigy** [comment]
how can i catch click event on ais-hierarchical-menu--link

**Comment by Haroenv** [comment]
This isn't possible with the default widget, because we stop propagation of the event. The way to go here is to make your own custom hierarchical menu, or solving it without event listeners on the elements

**Comment by eliprodigy** [comment]
do you have example for custom hierarchical menu please ?

**Comment by Haroenv** [comment]
https://www.algolia.com/doc/api-reference/widgets/hierarchical-menu/js/?language=js#connector

**Comment by eliprodigy** [comment]
do you have version without typescript ?

**Comment by Haroenv** [comment]
That doesn't use TypeScript

**Comment by eliprodigy** [comment]
on custom hierarchical menu i cant define "rootPath" do you know why please?

**Comment by Haroenv** [comment]
Maybe let's go over why you needed a custom widget in the first place. Why did you want to listen to the click events?

**Comment by eliprodigy** [comment]
i want to get the path

**Comment by Haroenv** [comment]
rootPath applies on a custom widget like it does on the default widgets, we do no custom logic in the component. 

If you are still struggling with this widget, 
can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!
