### ISSUE TITLE
instantsearch.js@3.2.0:2 Uncaught EvalError: Refused to evaluate a string as JavaScript

### ISSUE THREAD

**Issue by GiacomoSilli** [algolia/instantsearch.js#3736]
Hi, I've implemented algolia on my website.

I imported the following scripts:
```
<script src="https://cdn.jsdelivr.net/npm/algoliasearch@3.32.1/dist/algoliasearchLite.js" integrity="sha256-pMaJf0I78weeXGkRMBDO6jSulxC/q3sb0aPdtV2N8n0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@3.2.0" integrity="sha256-/8usMtTwZ01jujD7KAZctG0UMk2S2NDNirGFVBbBZCM=" crossorigin="anonymous"></script>
```

I add the following value to the nginx configuration file:
`add_header "Content-Security-Policy" script-src 'unsafe-inline' cdn.jsdelivr.net [...]`

The same procedure I did with all the other scripts. I find this error only with algolia

I get the following error:
`VM10446 instantsearch.js@3.2.0:2 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'unsafe-inline' .....`

How to solve?

**Comment by Haroenv** [comment]
You need to add that CSP to your headers, we use unsafe-eval (for now, it's tracked in #2868). Chrome is preventing you from executing the code at all

**Comment by Haroenv** [comment]
`unsafe_eval` needs to be added as well, because of our templating framework. This is something we will eventually move off of, but is too much of a breaking change to do now

**Comment by GiacomoSilli** [comment]
if I use `unsafe-eval `instead of `unsafe-inline` I get countless errors from all the other scripts.
How can I solve the problem?
Is there a way to specify `unsafe-eval` only for algolia and `unsafe-inline` for all others?
