### ISSUE TITLE
Replace `facetName` by a facet object

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#375]
I'd like to replace the `facetName`  prop by a `facet` prop, with a `name` attribute but possibly other ones.

The issue this would solve here would be to be able to have a label associated to the facet name and be able to display it in the header.

Currently, here is what we're using:

```js
for facet in facets:
  myWidget({
    facetName: facet.name,
    templates: {
      header:  '<div class="my-header">' + facet.title + '</div>'
  });
```

I'd like us to be able to have:

```js
var headerTemplate = '<div class="my-header">{{ facet.title }}</div>';

for facet in facets:
  myWidget({
    facet: facet,
    templates: {
      header:  headerTemplate
  });
```

which would feel more in adequation with what `headerFooter` has been designed for.

**Comment by redox** [comment]
Not sure we want to change the `facetName` behavior, it's more complex to use with an object because you can pass whatever you want.

I think what you want is the ability to add more data to the underlying templates, so maybe we could just do something like:

```js
for facet in facets:
  myWidget({
    facetName: facet.name,
    templatesData: facet,
    templates: {
      header: headerTemplate
  });
```

or 

```js
for facet in facets:
  myWidget({
    facetName: facet.name,
    templates: {
      header: prepare(headerTemplate, facet) //  replace(/FACET_TITLE/g, facet.title) or something
  });
```

What do you think?

**Comment by vvo** [comment]
> I'd like to replace the facetName prop by a facet prop, with a name attribute but possibly other ones.

If your question comes from the fact that you are going to need to ask for a facetName => facetLabel/Title mapping in the upcoming clear-refinements proposal then I would say thats not a need we need to fill.

That's not a problem if one widget is asking for the facetName <=> facetLabel/Title mapping.

**Comment by Jerskouille** [comment]
I just referenced the new issue to explain what I was asking this for.

**Comment by redox** [comment]
@Jerskouille Should we close this one?

**Comment by Jerskouille** [comment]
As you want, it was for consistency across widgets, but if it's not  an issue, yes we can definitely close it.
