### ISSUE TITLE
Allow listening for events on searchBox (regular JS / non-react version)

### ISSUE THREAD

**Issue by t0byman** [algolia/instantsearch.js#3750]
**Is your feature request related to a problem? Please describe 🙏**
It is related to https://github.com/algolia/instantsearch.js/issues/2017

**Describe the solution you'd like 🤔**
I would like to be able to use onSubmit in the regular JS / non-react version of instantsearch.js

**Describe alternatives you've considered ✨**
I'm trying to make https://github.com/algolia/instantsearch.js/pull/1450#issuecomment-259118772 happen so I tried to do 

```js
document.querySelector('.ais-SearchBox-form').addEventListener('submit', function(e) {
    console.log('tried to submit');
    e.preventDefault();
    document.querySelector('.ais-SearchBox-input').blur();
});
```

but it won't work. I'm guessing because there is already a preventDefault in instantsearch.js but I also tried it without a preventDefault and it still won't work.

**Additional context**
Thank you @Haroenv for suggesting I'd make a new issue

**Comment by tkrugg** [comment]
Hi @t0byman, yes you're right: https://github.com/algolia/instantsearch.js/blob/develop/src/components/SearchBox/SearchBox.js#L80

But you can create your own search box with full control over the DOM elements. Than you can setup your own listeners.
I would recommend looking into our docs where there many examples showcasing this
https://www.algolia.com/doc/api-reference/widgets/search-box/js/?language=js#full-example

Let us know if this helps.
