### ISSUE TITLE
connectNumericRefinementList as a Select Field

### ISSUE THREAD

**Issue by JonnyTurnerUK** [algolia/instantsearch.js#3764]
Hi All! 

I read a post here about using 'connectNumericRefinementList' as a select field so I've been on that for a while trying to change the usage from UL to a select element but can't seem to get the select field to stay selected. On the first change, it goes back to index, on the 2nd and 3rd changes, the field remembers the state and works great. After the 3rd, it starts again.

Has anyone got an example of successfully using 'connectNumericRefinementList' as a select field? Below is my code so far so I'm sure it's something I'm stupidly missing / doing.

Any guidance would be massively appreciated. 

Below is my code but 

    function renderFn(NumericRefinementListRenderingOptions, isFirstRendering) {
    if (isFirstRendering) {
       NumericRefinementListRenderingOptions.widgetParams.containerNode.html('<select>   </select>');
     }

     NumericRefinementListRenderingOptions.widgetParams.containerNode.find('option[value]').each(function() { $(this).off('select'); });

     var list = NumericRefinementListRenderingOptions.items.map(function(item) {
       return '<option value="' + item.value + '" ' + (item.isRefined ? ' selected' : '') + ' >' +
         item.label + '</option>';
     });

     NumericRefinementListRenderingOptions.widgetParams.containerNode.find('select').html(list);
     NumericRefinementListRenderingOptions.widgetParams.containerNode
       .find("select")
       .each(function() {
         $(this).on('change', function(event) {
           event.preventDefault();
           event.stopPropagation();
           NumericRefinementListRenderingOptions.refine($(this).val());
         });
      });
      }

      var customNumericRefinementList = instantsearch.connectors.connectNumericRefinementList(renderFn);

      search.addWidget(
        customNumericRefinementList({
          containerNode: $('#advPayment'),
          attributeName: 'advPayment',
          options: [
              {start: 0, name: 'Any Adv. Payment'},
              {start: 1, end: 99, name: 'Up to £99'},
              {start: 100, end: 250, name: '100 - £250'},
              {start: 251, end: 500, name: '£250 - £500'},
              {start: 501, end: 1000, name: '£500 - £1,000'},
              {start: 1001, end: 2500, name: '£1,000 - £2,500'},

          ],
        })
      );

**Comment by Haroenv** [comment]
You were not setting up the event listeners correctly, this is a correct version: https://codesandbox.io/s/rmvw0nj01n

**Comment by JonnyTurnerUK** [comment]
@Haroenv Ah, perfect! Thanks a lot for that. I'll do some reading on that and get up to speed. Thanks again!

**Comment by Haroenv** [comment]
No problem!
