### ISSUE TITLE
API proposal: current refinements list + how to clear

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#378]
I have a proposal to for listing current refinements and allowing to clear them.

Here is a list of some use cases linked to clearing:

1. A clear button/link after a refinement list
2. A clear button/link before a refinement list
3. A clear button/link next to the title of the refinements list
4. A clear all button/link anywhere on the page
5. A list with all current refinements displaying like this:

    ```js
    - Brand: Brand 1 (count)
    - Brand: Brand 2 (count)
    - Category: Cat 1 (count)
    - Category: Cat 2 (count)
    - Type: Type 1 (count)
    ```

6. A list with all current refinements displaying like this:

    ```
    Brand:
    | Brand 1 (count) X
    | Brand 2 (count) X
    Category:
    | Cat 1 (count) X
    | Cat 2 (count) X
    Type:
    | Type 1 (count) X
    ```

7. 5 and 6 but with only a subset of these (For example without a numericRefinements facet)
8. 5, 6 and 7. but with different displays depending on the facet
9. 5, 6, 7 and 8. with the cross displayed before/not displayed
10. 5, 6, 7, 8. and 9. with a clear all button/link before
11. 5, 6, 7, 8 and 9. with a clear all button/link after

And that's only what I could think of.

So in the end we would go with:
- `clearAll` : Link / button to clear all (See #359)
- `currentRefinedValues`: List of refinements (optionally with a clear button added with CSS) (See #112) and a `clearAll` (See #359)

Clearing specific facet refinements would probably need to go in the facet related widgets.

Here are the API proposals (they're using #375):

*clearAll* (See #359)
```js
instantsearch.widgets.clearAll({
  container: '#clear-all-link',
  cssClasses: {root, header, item, link, footer},
  templates: {
    header: '',
    item: '<a class="{{ cssClasses.link }}" href="{{url}}">Clear all</a>', // Called with {cssClasses, url}
    footer: ''
  },
  hideContainerWhenNoRefinements: true
})
```

*currentRefinementList* (See #112)
```js
search.addWidget(
  instantsearch.widgets.currentRefinedValues({
    container: '#current-refinements-list',
    cssClasses: {root, header, body, clearAll, item, clearItem, footer},
    facets: [ // Optional, if not specified, takes all of the facets
      { name: 'category'[, transformData: function (data) { /* ... */ return data; }]},
      { name: 'brand'[, transformData: function (data) { /* ... */ return data; }]}
    ],
    templates: {
      header: '',
      item: '' + // Called with this.facets[current_facet.name].transformData({cssClasses, facet: {name[, label(||= facet.name)]}, name, count})
        '<label class="{{ cssClasses.label }}">' +
        '  {{ name }}' +
        '  <span class="{{ cssClasses.count }}">' +
        '    {{ count }}' +
        '  </span>' +
        '</label>',
      clearAll: '' +
        '<a class="{{ cssClasses.clearAll }}" href="{{ url }}">' +
        '  Clear all' +
        '</a>',
      footer: ''
    },
    clearAll: 'after', // [true, false, 'before', 'after'] (true == 'before')
    hideContainerWhenNoRefinements: true
  })
);
```

I chose to ask the user to explicitly specify which facets he wants to consider through the `facets` param for multiple reasons:
- Being able to order the refinements
- Giving him the ability to give us the same transformData than the one used in refinementList/menu/...
- Possibility to set clear differently between facets
- Give the ability to pass extra info specific to the facet (`label`)

If we end up agreeing on this, I will create issues for each of them.

What do you think?

**Comment by vvo** [comment]
That's pretty nice.

allCurrentRefinementList => allCurrentRefinement**s**List

We should focus on the big one (allCurrentRefinementList) for 1.0.0.

Also I would not introduce the clear.after/before notation, like we saw in clearAll discussions (#359) discussions, the easiest way is to create only links and let the theme handle the (x) position with :before/:after.

WDYT?

**Comment by Jerskouille** [comment]
I would agree on the `allCurrentRefinementsList`, but we chose `refinementList`, isn't there a small inconsistency?

Alright for the CSS selectors, I missed that part in #359, I'll update the main post to reflect this.

**Comment by Jerskouille** [comment]
I removed the `clear: ['before', 'after', false]` for the items, but I think that we need it for the `clearAll` link.

**Comment by vvo** [comment]
> I would agree on the allCurrentRefinementsList, but we chose refinementList, isn't there a small inconsistency?

Indeed :)

**Comment by vvo** [comment]
> but I think that we need it for the clearAll link.

Even that, for a first version I would put it on top and see what people are doing with it/needs.

**Comment by redox** [comment]
I think it looks a bit complex, not sure we need to deal with so many details.

Regarding the "position" of the clear button, shouldn't that be a templating/layout customization rather than an option in the widget?

I think the `clearSpecificRefinements` should actually be an option of the `refinementList` widget; I don't think we want an extra widget for that.

I also think we should just expose the `allCurrentRefinementList`, if the user wants to restrict to a single refinement, he could just pass an array of 1 element. I would also rename it to `currentRefinementsList` (plural).

And if we go that way, I would then transform the `clearAll` widget to an option of the `currentRefinementsList` one.

So at the end, it's a single `currentRefinementsList` widget + the addition of a `clearAll` option in that widget + `refinementList` one :) If the user doesn't want to see the list of refined values but just the "clear all button", he can set the `templates.item` to `''`.

**Comment by Jerskouille** [comment]
@vvo 

> Even that, for a first version I would put it on top and see what people are doing with it/needs.

I actually want the "Clear all" link after the list, I find it less logical to have it before the other ones. So I'm the one having the use-case. :)

@redox 

>Regarding the "position" of the clear button, shouldn't that be a templating/layout customization rather than an option in the widget?

I agree, but I think we chose not too as soon as we started to expose `item`, `header`, `footer` templates instead of `body` ones. If we begin to expose the full template to chose the position, then we probably need to expose the full template for `refinementList` and everything, which means getting rid of `React` in the end in favor of templates + a custom made event API alongside.

> I think the clearSpecificRefinements should actually be an option of the refinementList widget; I don't think we want an extra widget for that.

Why not, but it means we'll need to add it to each and every one of the new widgets using facets. Are we sure we want to do this?
What if we want to put it in the header of the `refinementList` ?

> I also think we should just expose the allCurrentRefinementList, if the user wants to restrict to a single refinement, he could just pass an array of 1 element. I would also rename it to currentRefinementsList (plural).

Makes sense. Agreed. :+1: 

> And if we go that way, I would then transform the clearAll widget to an option of the currentRefinementsList one.
> So at the end, it's a single currentRefinementsList widget + the addition of a clearAll option in that widget + refinementList one :) If the user doesn't want to see the list of refined values but just the "clear all button", he can set the templates.item to ''.

It already is an option of the big one.
About using the big one to display it, I strongly disagree though. First we'd be using un-needed resources to retrieve the list of refinements at each state update for nothing, and in
```js
  instantsearch.widgets.allCurrentRefinementList({
    container: '#clear-all-link,
    templates: {
      item: ''
    },
    clearAll: true, // Will work as 'before'
    hideContainerWhenNoRefinements: true
  })
```
the name feels completely unrelated to the action to me.

I updated the main post to reflect these.

**Comment by Jerskouille** [comment]
> > I think the clearSpecificRefinements should actually be an option of the refinementList widget; I don't think we want an extra widget for that.
>
> Why not, but it means we'll need to add it to each and every one of the new widgets using facets. Are we sure we want to do this?
> What if we want to put it in the header of the refinementList ?

About this, I would propose to have a clearRefinements taking an optional `facets` parameter. If not provided, we clear everything, if provided, we clear only the ones specified (usually only one).

**Comment by vvo** [comment]
> I actually want the "Clear all" link after the list, I find it less logical to have it before the other ones. So I'm the one having the use-case. :)

WFM if on a UX side you tested it and it makes more sense lets go. We can adjust if we need to.

**Comment by redox** [comment]
> Why not, but it means we'll need to add it to each and every one of the new widgets using facets. Are we sure we want to do this?

Yes, but we can factorize the code like we do for header/footer for instance.

> About using the big one to display it, I strongly disagree though.

Hmmm, if it's for "performance" reason I would say it's a bad reason (until we actually detect one, but iterating over <5 refinements shouldn't be that intense + we could optimize the code if the underlying template it blank).

That being said, I agree it's not very developer-friendly; so I would maybe go for 2 widgets, but definitely use the same underlying components.

> I updated the main post to reflect these.

Actually, re-reading it I think `refinementList` is confusing here, we need to speak about the *refined*  values themselves. So either `currentRefinedValues` or `currentRefinements`.

**Comment by vvo** [comment]
> currentRefinedValues

:+1:

**Comment by Jerskouille** [comment]
Alright, fire ! I like `currentRefinements` a bit more than `currentRefinedValues`, but both express the same thing, so I'm happy to settle on `currentRefinedValues`.

**Comment by Jerskouille** [comment]
Closing in favor of the two original issues.
