### ISSUE TITLE
[indexSelector] create widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#38]
This widget needs to be able to render this:

![2015-08-05-102322_312x86_scrot](https://cloud.githubusercontent.com/assets/123822/9081372/0fb2c3ba-3b5c-11e5-9043-3e88d1b240aa.png)

## API

Given this html:

```html
<div id="sort-results"></div>
```

And JavaScript:

```js
instant.addWidget(
  instant.widgets.indexSelector({
    container : "#sort-results",
    indices: [{
      name: 'index', label: 'Relevance'
    }, {
      name: 'index_priceASC', label: 'Highest price'
    }, {
      name: 'index_priceDESC', label: 'Lowest price'
    }]
  })
);
```

We render:

```html
<select>
  <option value="index">Relevance</option>
  <option value="index_priceASC">Highest price</option>
  <option value="index_priceDESC">Lowest price</option>
</select>
```

### Options

* `container` string or DOMElement
* `indices` array of objects
* `cssClass` string (comma separated list of css classes to apply to root element)

### Behavior

The selected index is the one set in the helper as the current one.

If the selected index is not one from the list, then we should throw an error.

**Comment by vvo** [comment]
API updated

**Comment by vvo** [comment]
To provide a higher level of customization we will be able to enhance this widget in the future.

So that people could pass their own template (so that they can use bootstrap dropdown components for example).

For this, we only need to provide an API to the instantiated widget, something like:

```js
### Drawbacks

Cannot pass your own template, because we would not know when do you want to change the index.

What we can do is provide an API to the instanciated widget like:

```js
var selector =   instant.widgets.indexSelector({
  container : "#sort-results",
  indices: [{
    name: 'index', label: 'Relevance'
  }, {
    name: 'index_priceASC', label: 'Highest price'
  }, {
    name: 'index_priceDESC', label: 'Lowest price'
  }],
  template: 'Your template, you will receive an array of indices and one of them will have the `selected` property set'
});
```

But that's for 1.0.0.

For people wishing to use complex switch widgets like bootstrap widgets we should put this in userland (= do the widget ourselves in another repo, or let the community do it).

If you agree with this I will open another issue with this enhancement.

**Comment by bobylito** [comment]
No support for string in the array of indices?

**Comment by vvo** [comment]
> No support for string in the array of indices?

You mean only specifying the index names like: `index, index_priceASC, ..`?

I don't see it as an easier way or sugar. When would you not want a label that is different from the index name? Using the algolia index name as a direct displaying string is a bit weird, did you see any implementation doing it?

**Comment by bobylito** [comment]
makes sense! WFM!

**Comment by vvo** [comment]
We need a better name than `indexSelector` because what we are really providing is a sort results widget.

The fact that sorting the results are implemented by having multiple indexes should not be the reason to name this widget "indexSelector".

**Comment by pixelastic** [comment]
Also, not sure the `cssClass` is useful. The user can simply add a css class to the container element to style the inner `select`.

We also do not provide such a mechanism on the other widgets, I think we can find a more generic way to allow user to styles the widgets (cf. #47)

**Comment by vvo** [comment]
> The user can simply add a css class to the container element to style the inner select

We do have it in some other places (like the searchBox), mostly because sometimes (like when using bootstrap), adding a class on the wrapper element does not allows you to style your form element accordingly.

If you find a way on the API side to provide a full template then maybe it would solve the `cssClass` thing

**Comment by pixelastic** [comment]
I think we can let the user define its own custom `template` for this widget (and the searchBox) so they can add whatever classes or attributes they want, but we need to check that they are resp. `<select>` and `<input type="text">` elements.

This way, we can still correctly bind our click event to the correct dom element, while letting the user customize it.

**Comment by vvo** [comment]
Yes this should work indeed, let's try to do it on the searchBox first. If you wanna try it @pixelastic after the stats template, do it! :)

**Comment by pixelastic** [comment]
Will do :)

**Comment by pixelastic** [comment]
What about `sortOrderSelector` for this widget name?

**Comment by redox** [comment]
> We need a better name than indexSelector because what we are really providing is a sort results widget.
> What about `sortOrderSelector` for this widget name?

I've been thinking about it and:
 - the sorting is really not a UI thing with Algolia: it appears very confusing to me to have a "sort" widget because what this widget will do is update the targeted index and will not deal at all with sorts
 - I'm not sure we need to make it display the "Sort by:" label

At the end it's really an `indexSelector` and the user is free to use it to configure the sort orders if he built the slaves to do it.

**Comment by pixelastic** [comment]
Do we have use-cases where an implementation uses this kind of widget for something else than sort order?
