### ISSUE TITLE
Hierarchical ais-hierarchical-menu--link__active class

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#380]
For design like magento it could be useful to have ais-hierarchical-menu--link__active

Right now I am only able to do this

![image](https://cloud.githubusercontent.com/assets/1689007/10792049/62d961fe-7d8b-11e5-9768-f5db5f77da02.png)

With ais-hierarchical-menu--link__active we would be able to put the blue border only for one link in the level 1

**Comment by redox** [comment]
That's doable already: http://algolia.github.io/instantsearch.js/#q=&hPP=6&idx=instant_search&p=0&hFR[hierarchicalCategories.lvl0][0]=Cameras%20%26%20Camcorders%20%3E%20Digital%20Cameras&is_v=0

**Comment by maxiloc** [comment]
@redox yes cool
