### ISSUE TITLE
Upgrade preact-compat

### ISSUE THREAD

**Issue by cloakedninjas** [algolia/instantsearch.js#3828]
**Is your feature request related to a problem? Please describe 🙏**
This is by no means urgent, but integrating instantsearch into a project using Preact X (e.g. 10.0.0-beta.1) causes issues during page load (see https://github.com/preactjs/preact/issues/1655)

So just raising a potential issue that might arise more often as and when Preact X is released and more Algolia consumers upgrade. And I expect it will be taken up quickly given it adds support for latest React 16 features (hooks, context)

**Describe the solution you'd like 🤔**
Move to new `preact/compat` instead of `preact-compat` (perhaps when X is stable)

**Describe alternatives you've considered ✨**
Our interim solution was to alias `preact-compat` to `preact/compat`

**Comment by Haroenv** [comment]
We indeed will move to preact X as soon as it's out of beta 🔥 (and really looking forward to it)

**Comment by francoischalifour** [comment]
I keep checking the [Preact releases page](https://github.com/preactjs/preact/releases) every day to upgrade as soon as it's stable haha.

**Comment by Haroenv** [comment]
done in v4!
