### ISSUE TITLE
Question on the page "hits"

### ISSUE THREAD

**Issue by fujiii** [algolia/instantsearch.js#3829]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[hits](https://community.algolia.com/instantsearch.js/v2/widgets/hits.html)".

I think example on bottom of the page doesn't work, at least when trying to transform items inside transformItems method -- nothing happens. While debugging, it doesn't even goes inside there.

**Comment by yannickcr** [comment]
What version of InstantSearch are you using? (this documentation is for the v2).

In my tests `transformItems` seems to be working correctly. One issue with the example is that it's using `{{{_highlightResult.name.value}}}` and this highlight helper only works on the original `hit` value (even if it was transformed). I agree that it can be confusing and we should fix this example.

**Comment by fujiii** [comment]
I use 2.7.1 version.

This works in your codesandbox, but not in my environment:

        search.addWidget(
            instantsearch.widgets.hits({
                container: '.hits',
                templates: {
                    empty: 'No results',
                    item: '<strong>Hit {{objectID}}</strong>: {{{_highlightResult.name.value}}}'
                },
                escapeHits: true,
                transformItems: function (items) {
                    return items.map(function (item) {
                        console.log(item);
                        return item;
                    });
                },
            })
        );

Is it just because of a version difference? Or it have to do with Indexes "Ranking and Sorting" configurations?

**Comment by yannickcr** [comment]
`transformItems` was added in `2.10.0` ([Changelog](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#2100-2018-08-08)), so you'll need to upgrade to use it.

This is only a minor upgrade (we're following [semver](https://semver.org/)) so you should be able to upgrade without any problem.

**Comment by fujiii** [comment]
Thank you a lot!
