### ISSUE TITLE
Replace `stylelint` with a Sass-aware linter

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#384]
Our `stylelint` check is useless now that we are using Sass. We should use a linter aware of Sass syntax.

https://github.com/brigade/scss-lint should work.

Any other in mind?

**Comment by redox** [comment]
LGTM :+1:

**Comment by pixelastic** [comment]
Actually scsslint only works with `.scss` syntax. We could use [sasslint](https://github.com/sasstools/sass-lint) but I'll first wait to see if we stay on Sass or move to Scss (cf. #290)

**Comment by redox** [comment]
> https://github.com/brigade/scss-lint should work.

Actually, this is a ruby gem and the NPM package requires you tu have it -> so I don't think it's a good move. What about https://github.com/sasstools/sass-lint (compliant with SCSS) ?

**Comment by pixelastic** [comment]
@redox That's what I just said one message above :)

**Comment by vvo** [comment]
was done and moving to waiting for release
