### ISSUE TITLE
Something breaks the hierarchical menu

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#385]
![image](https://cloud.githubusercontent.com/assets/976175/10815478/ab1c3cc4-7e2c-11e5-8194-df03c5d90f4a.png)

When the attribute 'chapter' is added to the hierarchical menu, it crashs on the lvl3

It maybe be caused by 'null' value in the dataset.

![image](https://cloud.githubusercontent.com/assets/976175/10815470/9b88110c-7e2c-11e5-99e9-f1cc2e81f439.png)

![image](https://cloud.githubusercontent.com/assets/976175/10815530/017f5f56-7e2d-11e5-94a1-1313ec10f379.png)

**Comment by maxiloc** [comment]
It seems to be related to the helper. On https://magento.algolia.com instant search (not based on instantsearch.js) when you do:

1) select Accessories puis “Bags & Luggage”
2) enter “d”
3) type "ress" after the "d"

you encounter the same issue.

**Comment by redox** [comment]
You can reproduce with `npm run dev` and `http://localhost:8080/#q=er&hPP=6&idx=instant_search&p=0&hFR[hierarchicalCategories.lvl0][0]=Appliances%20%3E%20Ranges%2C%20Cooktops%20%26%20Ovens%20%3E%20Range%20Hoods&is_v=0` -> it's indeed in the helper.

**Comment by vvo** [comment]
Was solved by @maxiloc in the helper: https://github.com/algolia/algoliasearch-helper-js/commit/d0337d3fb2916550f157696909532a973f1cced2

Will do a release helper tomorrow morning (so that if we have more fixes we embark them also)
