### ISSUE TITLE
Sharing styling of `refinementList` items

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#386]
I feel like in most implementation we do, most of the `refinementList`-type widgets (menu, hierarchical, priceRange) share the same base styling.

![image](https://cloud.githubusercontent.com/assets/283419/10815905/3b0abade-7e2f-11e5-95c9-13a13bf4c283.png)![image](https://cloud.githubusercontent.com/assets/283419/10815906/3ee215ee-7e2f-11e5-90bc-5b5a16ac0a3d.png)

^ Here the blue border, bold and grey underline.

With the way themes are currently handled, we have to duplicate this styling for every widget (`ais-menu--item`, `ais-hierarchical-menu--item`, etc).

I see two ways to fix that:

1. Using Sass mixins. We create a base `@refinement-item` for example and we then use it in every widget, allowing us to easily re-use some code. This will help factorize some code, but might make it less readable.
2. We add a `ais-default--item` class to every item, and style this one. This is consistent with how we handle header and footers, but puts all the responsability of defining what is a `refinementList`-like widget and what is not on the library and not on the themes.

I'm unsure which one to chose. Feedbacks welcome.

**Comment by redox** [comment]
What about making the hierarchical widgets to have the same classes than the regular one, plus a hierarchical extra class. Something like:

```css
<div class="ais-menu">
  <!-- [...] -->
  <div class="ais-menu-item">
    <!-- [...] -->
  </div>
  <!-- [...] -->
</div>

<div class="ais-menu ais-hierarchical-menu">
  <!-- [...] -->
  <div class="ais-menu-item ais-hierarchical-menu-item">
    <!-- [...] -->
  </div>
  <!-- [...] -->
</div>
```

**Comment by pixelastic** [comment]
So `menu` would be the default one, and all others inherit classes from it ? That could make sense, but it means we will no longer be able to independently style the menu. Everything added to it will also be applied to other widgets.

**Comment by redox** [comment]
> but it means we will no longer be able to independently style the menu.

Yes true :/ I dont think we should do with `ais-default--item` however -> the `default` looks very weird.

Maybe we just need to tackle that using mixings.

**Comment by pixelastic** [comment]
@Shipow @kokliKo: As you're also integrating themes, what are your thoughts?

**Comment by Jerskouille** [comment]
What about `ais-item`, `ais-body`, etc., exactly as we're doing for header and footer?

**Comment by redox** [comment]
> What about ais-item, ais-body, etc., exactly as we're doing for header and footer?

That would definitely be a more acceptable option. Maybe something like:

```html
<div class="ais-list ais-menu">
  <!-- [...] -->
  <div class="ais-item ais-menu-item">
    <!-- [...] -->
  </div>
  <!-- [...] -->
</div>

<div class="ais-list ais-hierarchical-menu">
  <!-- [...] -->
  <div class="ais-item ais-hierarchical-menu-item">
    <!-- [...] -->
  </div>
  <!-- [...] -->
</div>
```

**Comment by pixelastic** [comment]
:+1: for `ais-item`, obvious and simple.

Not sure what you have in mind for `ais-list`, though. What should it target? Same elements as `ais-widget-name--list`?

**Comment by redox** [comment]
> What should it target? Same elements as ais-widget-name--list

Yes?

**Comment by pixelastic** [comment]
I wasn't sure, your previous example seems to target the root level of the widget.

Makes sens, I'll work on that.

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it
