### ISSUE TITLE
priceRanges: Making BEM classes more consistent

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#387]
I was looking at theming the priceRanges widget, and there are a few things that needs to be updated.

It currently generates the following markup:

```html
<div class="ais-price-ranges">
  <div class="ais-price-ranges--header ais-header">Header</div>
  <div class="ais-price-ranges--body">
    <a class="ais-price-ranges--range" href="...">
      $3 - $13
      <span></span>
    </a>
    <a class="ais-price-ranges--range ais-price-ranges--range__active" href="...">
      $13 - $40
      <span></span>
    </a>
    <form class="ais-price-ranges--form">
      <label><span>$</span><span> </span><input class="ais-price-ranges--input" /></label>
      <span> </span><span>to</span><span> </span>
      <label><span>$</span><span> </span><input class="ais-price-ranges--input" /></label>
      <span> </span><button class="ais-price-ranges--button">Go</button>
    </form>
  </div>
  <div class="ais-price-ranges--footer ais-footer">Footer</div>
</div>
```

First, it seems that we have two issues:

1. The count is not displayed in the `ais-price-range--range`.
2. It seems there are way too many useless `span`s here. Do you have any idea what they are for?

And I would also:

- [x] Rename the `ais-price-ranges--range` to `ais-price-ranges--item`
- [x] Wrap them in a `ais-price-ranges--list`, to stay consistent with other widgets (and being able to share styling easily).
- [x] Add `ais-price-ranges--form-label` (?) to the `label` inside the bottom `form`.

**Comment by redox** [comment]
:+1:

**Comment by redox** [comment]
> The count is not displayed in the ais-price-range--range.

yes indeed, no count for now on this widget (ranges are computed locally).

> It seems there are way too many useless spans here. Do you have any idea what they are for?

I think that's because of the inline text + spaces I've used -> added by React I assume.

**Comment by pixelastic** [comment]
I've been working on that, I'll push a PR tomorrow (need to rebase and cleanup)

**Comment by vvo** [comment]
Adding this for next release, was done @pixelastic ?

**Comment by pixelastic** [comment]
Yes, it was in https://github.com/algolia/instantsearch.js/pull/390

Still a few details to handle in the PR comments, but the main feature is ok. Go next release.
