### ISSUE TITLE
How to use InstantSearch with no UI?

### ISSUE THREAD

**Issue by alexherbo2** [algolia/instantsearch.js#3881]
Hello,

I was wondering how Algolia’s InstantSearch operates on non webpage based applications.  My use case is to create a search experience with the [Chrome omnibox], for example to search on the [MDN].  I only care about the query, which contents comes from the omnibox, and the response, to access and display the candidates in the omnibox.  How to do that?

[Chrome omnibox]: https://developer.chrome.com/extensions/omnibox
[MDN]: https://developer.mozilla.org

**Comment by Haroenv** [comment]
Hey   @alexherbo2, this can be done using the connectors, you can find more information on that here: 

https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/js/?language=vue#customize-the-complete-ui-of-the-widgets

https://www.algolia.com/doc/api-reference/widgets/autocomplete/js/#connector

There you will render to your preferred non-dom output

**Comment by alexherbo2** [comment]
@Haroenv It’s also possible with [search] and [query]?

[search]: https://algolia.com/doc/api-reference/api-methods/search/
[query]: https://algolia.com/doc/api-reference/api-methods/search#method-param-query

**Comment by francoischalifour** [comment]
Using the [JavaScript API client](https://www.algolia.com/doc/api-client/getting-started/install/javascript/) as you mentioned is what InstantSearch does under the hood. InstantSearch comes handy when you want to build an application and manage the state of the search in your page. From what I understand of your usage, using the [API client](https://www.algolia.com/doc/api-client/getting-started/install/javascript/) would be enough.
