### ISSUE TITLE
Dynamically change search config based on current refinements

### ISSUE THREAD

**Issue by caseys** [algolia/instantsearch.js#3888]
**Is your feature request related to a problem? Please describe 🙏**

In our UI, when users select different categories, we want add/alter filters, optionalFilters and maybe other config attributes to the search.

I understand that Query Rules can accomplish some of this.... I was hoping for another option at query time using Instantsearch.

**Describe the solution you'd like 🤔**

I would like to alter search config based on current refinements.   I tried nesting ais-config inside ais-current-refinements... hoping to use refinement items slot scope in ais-config... this doesn't work of course and I'm probably in fantasy land even trying.

**Describe alternatives you've considered ✨**

Query Rules comes close...  It feels wrong, to put some filters in query rules and some in Instantsearch config... but I may be overthinking it.   I don't believe Query Rules can use query-time data in Consequences.... so maybe that's one reason to consider a different solution

**Additional context**

Instantsearch Docs say "In order to dynamically update the search parameters, you should create a new custom widget."   ...so I'm not the only one considering this.

**Comment by eunjae-lee** [comment]
Hello @caseys , thanks for reaching us.
If I understand correctly, your issue can be solved easily with `searchFunction`.
You can see the description and usage [here](https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/?language=js#widget-param-searchfunction).
For more details about helper, please refer to [this](https://github.com/algolia/algoliasearch-helper-js).

I'm closing this issue, assuming my comment answers you.
However, you can open it again if you need more information.
Please feel free to ask any further question if you have any.
