### ISSUE TITLE
How to prevent HTML escaping of a field?

### ISSUE THREAD

**Issue by alexherbo2** [algolia/instantsearch.js#3898]
There is [escapeHTML] but it’s global and doesn’t play well combined with [transformItems].

[escapeHTML]: https://algolia.com/doc/api-reference/widgets/hits/js#widget-param-escapehtml
[transformItems]: https://algolia.com/doc/api-reference/widgets/hits/js#widget-param-transformitems

**Comment by francoischalifour** [comment]
Why is it an issue to have `escapeHTML` set globally and what are you trying to achieve with `transformItems`?

**Comment by alexherbo2** [comment]
I have _name_ attributes, for instance `<angle>`, and _description_ attributes in an HTML format.  By setting `escapeHTML` to false, attributes are recognized as HTML, but I only want the description to be HTML.

For `transformItems`, I actually stored the descriptions in a Markdown format, and tried to convert Markdown to HTML, but `escapeHTML` is not honored and items escaped.  I think `transformItems` cannot be used to control the format output.

**Comment by francoischalifour** [comment]
`transformItems` allows you to update the hits before displaying them on screen.

Reproducing what you currently have and explaining what you want instead in this [InstantSearch.js sandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js) will make it easier to help you.

**Comment by Haroenv** [comment]
escapeHTML is a global flag, as you already found in the other issue
