### ISSUE TITLE
Is there a way to store and display an attribute in another markup language than HTML, like Markdown?

### ISSUE THREAD

**Issue by alexherbo2** [algolia/instantsearch.js#3899]
I tried with [escapeHTML] to false and [transformItems] using [Showdown], but it still produces escaped HTML.

[escapeHTML] is also global, while I only wanted the escaping disabled for a particular attribute (description).  I have for example name attributes like `<angle>` which are not displayable due to the escaping being unset for all attributes.

[escapeHTML]: https://algolia.com/doc/api-reference/widgets/hits/js#widget-param-escapehtml
[transformItems]: https://algolia.com/doc/api-reference/widgets/hits/js#widget-param-transformitems
[Showdown]: http://showdownjs.com

**Comment by francoischalifour** [comment]
Can you please reproduce the issue in this [InstantSearch.js template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js)? It'd be easier to understand the problem and to help you find a solution.

**Comment by Haroenv** [comment]
The best  way to deal with markdown where you want to keep the attributes is:

1. escapeHTML: false
2. run your markdown changing
3. escape again to prevent XSS, depending on which tags you want to allow

A  fairly similar mechanism is done for the yarn website (however that one is done with React InstantSearch) https://github.com/yarnpkg/website/blob/master/js/src/lib/util.js#L196

At the end, we found that while trying to do this, we often broke markdown tags by highlighting, so more complex logic is necessary for that, which should also be done with escapeHTML false.

You can see an example html escape we use here https://github.com/algolia/instantsearch.js/blob/develop/src/lib/utils/escape.ts
