### ISSUE TITLE
Basic integration tests

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#39]
TODO:
- [x] create the necessary stack to do some integration tests
- [x] write some integration tests
- [x] make them run in saucelabs on major browsers
- [x] provide a good dev environment to develop them (local selenium)

Ideas:
- automatically wait between XHRS, so that no need to .wait() with selenium
- have a look at https://github.com/cucumber/cucumber-js

**Comment by redox** [comment]
Is that issue out-dated @vvo ?

**Comment by vvo** [comment]
Nope we will need integration testing after unit testing

**Comment by pixelastic** [comment]
Yep, +1 on this one. Integration tests are a must-have here

**Comment by vvo** [comment]
This is my next testing task after #16

**Comment by vvo** [comment]
Ideas:
- automatically wait between XHRS, so that no need to .wait() with selenium
- have a look at https://github.com/cucumber/cucumber-js
