### ISSUE TITLE
Aren't we using `let` the wrong way?

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#391]
In some widgets, `let` is used at the same level as `var`, and if I understood correctly it doesn't make sense.

Except if I didn't get the real purpose of `let` (which is, for me, to be used in conditions and loops), can we make it consistent?

**Comment by pixelastic** [comment]
`let` is not hoisted like `var` is. I think we keep using `var` because we're used to it, but we can surely switch to `let` most of the times.

Feel free to code using `let` as much as you want.

**Comment by Jerskouille** [comment]
Alright, so I can do a `s/var/let/` without an issue?

**Comment by pixelastic** [comment]
I'm not sure. I would say yes. See if the tests still pass.

**Comment by vvo** [comment]
this was done, moving for next release
