### ISSUE TITLE
Check usages of all widgets

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#396]
Many are inconsistent.

Please check that all of the "options" are stated as "options.optionName" in the jsdoc of widgets, for them to render well in the website documentation.

**Comment by pixelastic** [comment]
We should fix them when we see it, or at least dump the list here so we can make sure we fix them all.

**Comment by vvo** [comment]
What does it mean to check usage of all widgets? Do you mean checking the user input and reporting accordingly?

**Comment by Jerskouille** [comment]
No, it just means that the usages (`throw new Error(usage)`)  are not up to date in some widgets.

**Comment by vvo** [comment]
Ok we can do it by hand right now but in the end this could all be factorized into a module that check usage/report/throw.

Something like.. https://github.com/hapijs/joi

**Comment by pixelastic** [comment]
:+1: for a library helping us do it and not copy-paste

**Comment by Jerskouille** [comment]
:+1:

**Comment by bobylito** [comment]
On it!
