### ISSUE TITLE
Ignore facet

### ISSUE THREAD

**Issue by MrMooky** [algolia/instantsearch.js#3980]
I checked the [docs](https://www.algolia.com/doc/api-reference/search-api-parameters/) but was not able to find a solution in v3 to exclude a certain facet using `searchParameters`.

What I'm basically trying to accomplish is that when a user is logged into our system (TYPO3), a special class is added to the body. If this class is set, I want to display every record there is (regular search). But if that class is not set, I need to **exclude the facet `intern` which is set to 1**.

Since `facetsExcludes` has been removed I'd like to know how I can accomplish such behaviour.

<img width="265" alt="Screen Shot 2019-07-23 at 14 07 39" src="https://user-images.githubusercontent.com/3603346/61710982-3e434e80-ad53-11e9-9d51-9b14dfb1dd35.png">

```
if ( $('body').hasClass('intern') !== true ){
var search = instantsearch({
    indexName: 'indexname',
    searchClient,
    routing: false,
    searchParameters: {
        WHAT-SHOULD-I-PUT-HERE-TO-IGNORE-INTERN-1: {
            "intern": 1
        }
    }
});
}
```

I don't want to prefilter anything, though.

**Comment by francoischalifour** [comment]
The API parameter [`filters`](https://www.algolia.com/doc/api-reference/api-parameters/filters/) is what you're looking for.

This should work:

```js
var search = instantsearch({
  indexName: 'indexname',
  searchClient,
  searchParameters: {
    filters: 'NOT intern:1',
  },
});
```

**Comment by MrMooky** [comment]
That was too simple. :) Thanks a lot.
