### ISSUE TITLE
Problem with hot addWidget

### ISSUE THREAD

**Issue by Sirbuland** [algolia/instantsearch.js#3992]
Hi all!

I got an error while working with `nuxt.js`, `ais-sort-by`, `ais-instant-search-ssr` and url routing. When page is loaded, I get items in `ais-hits` but afterwards (with some delay) I get errors which are related to addWidget and SortBy. I was looking into code and found out that this functionality can be buggy because this feature is experimental as mentioned in InstantSearch.js file. 

On frontend I get this error: [url](https://drive.google.com/file/d/1x7MaX9T-ZRfhcwaWr3sZ0ezrtXw1XgR-/view?usp=sharing)

I inspected by adding console.log(this.searchParameters) inside `addWidgets` (function of instantSearch lib) and found out that index is `undefined`. [url](https://drive.google.com/file/d/1LWmV1HRrZ3lv5KtfD1MOeIUWkN_WNkEA/view?usp=sharing)

Here I'm getting error: [url](https://drive.google.com/file/d/1NszlT9g3_T4XVq95uyFhnFcBk6Ita3iA/view?usp=sharing)

I've done configs and defined index at almost all possible places. In 2nd shared image, you can see that facets (also set by me) are present but index became undefined. I don't know why this is happening.

Index was present previously but it becomes undefined afterwards. **_Btw if I just comment out ais-sort-by then error do not occurs._**

Here is my code for ais-sort-by:

`<ais-sort-by :items=indexConfig />`

```
indexConfig() 
{
return [{ value: process.env.vueAppAlgoliaIndexName, label: this.$t('product_search_list.Relevance')},

{ value: `${process.env.vueAppAlgoliaIndexName}_preis_asc`, label: this.$t('product_search_list.PriceAsc') },

 { value: `${process.env.vueAppAlgoliaIndexName}_preis_desc`, label: this.$t('product_search_list.PriceDesc') },
]
},
```
These are my configs for instant search:

```
import algoliasearch from "algoliasearch/lite";
import { createInstantSearch } from "vue-instantsearch";
import { history as historyRouter } from 'instantsearch.js/es/lib/routers';
import { simple as simpleStateMapping } from 'instantsearch.js/es/lib/stateMappings';

import algolia from '~/services/algoliaClient';

export default function VueInstantSearchPlugin(_, inject) {

  const { instantsearch } = createInstantSearch({
    indexName: process.env.vueAppAlgoliaIndexName,
    searchClient: algolia.algoliaClient,
    routing: {
      router: historyRouter(),
      stateMapping: simpleStateMapping(),
    },
    async searchFunction(helper) {
      // I even tried to set index using helper here but it didn't worked
      await helper.setIndex(process.env.vueAppAlgoliaIndexName);
      helper.state.index;
      helper.search();
    },
    searchParameters: {
      query: _.app.router.query,
      index: process.env.vueAppAlgoliaIndexName,
      disjunctiveFacets: [
        'preis',
        'companyName',
        'productCondition_de',
        'serviceType_de',
        'kategorie',
        'baujahr',
        'priceNumber'
      ],
    },
  });

  inject("instantsearch", instantsearch);
}
```

In nuxt.js we have layouts/default.vue file. In that file I've hydrated instant search inside beforeMount().
Here is the code for it:

```
async beforeMount() {
    const uiState = this.$route.query || {};
    const query = uiState.query || '';
    const page = uiState.page - 1 || 0;
    const $instantsearch = this.$instantsearch;
    let searchState = await this.$instantsearch.findResultsState({
      query,
      page,
      index: process.env.vueAppAlgoliaIndexName,
      facets: [
        'preis',
        'companyName',
        'productCondition_de',
        'serviceType_de',
        'kategorie',
        'baujahr',
        'priceNumber'
      ],
      disjunctiveFacets: [
        'preis',
        'companyName',
        'productCondition_de',
        'serviceType_de',
        'kategorie',
        'baujahr',
        'priceNumber'
      ]
    });
    let algoliaState =  await this.$instantsearch.getState();
    this.$instantsearch.hydrate(algoliaState);
    this.setLoading(false);
```

**Comment by Haroenv** [comment]
Hi @Sirbuland, thanks for getting this to our attention, this indeed is a bug, which we managed to reduce thanks to your example. It's happening because 3.5.1 we made a change in how we deal with default values coming from URLs. 

Can you try this out in 3.4.0 of InstantSearch.js? You can use yarn resolutions to force that version to be used.

**Comment by Sirbuland** [comment]
Hi @Haroenv !
Thanks for your reply. I'll try using version 3.4.0 and update here about its results.

**Comment by Sirbuland** [comment]
Yep, moving to version 3.4.0 resolved this issue `Index not present`.

**Comment by Sirbuland** [comment]
Hi @Haroenv !
Its still problematic with version 3.4.0. It do not give errors but the sort by is not still working fine. This widget disappears (dropdown menu) after some delay i-e 2-3 seconds. When page loads it is like this: [https://drive.google.com/file/d/16lTszOQHoNhUTPdVe63CmUmqpt-wK0G_/view?usp=sharing](dropdownPresent)

After some time span it disappears: [https://drive.google.com/file/d/1EIGzJDuUNK9CdMZhXQccle73MXjoLRUk/view?usp=sharing](dropdownDisappears)

This was also happening previously when created this issue, but also give errors on browser's console. Now there is no error on console.

I shifted to previous version of instantsearch.js by using resolutions in package.json.

```
"resolutions": {
 "instantsearch.js": "3.4.0",
},
```

**Comment by Haroenv** [comment]
Sorry for not getting back here, but I think this has been fixed since. Please feel free to open a new issue with reproduction if this still happens now
