### ISSUE TITLE
RefinementList widget shows dups when case type differs b/w facet and record

### ISSUE THREAD

**Issue by chadokruse** [algolia/instantsearch.js#3999]
**Describe the bug 🐛**
The RefinementList widget shows duplicate listings in edge cases where the case type of a selected facet differs from the case type of the related record item (e.g. TitleCase vs UPPERCASE).

The bug appears when the facet is selected outside the normal InstantSearch flow (e.g. manually via the helper instead of directly in the refinementList widget).

**To Reproduce 🔍**

1. Using the default "basic routing" template, select `Samsung`:
https://lyw7mov3ql.csb.app/?refinementList%5Bbrand%5D%5B0%5D=Samsung

2. Mimic a manual facet selection by changing the url from TitleCase `Samsung` to UPPERCASE `SAMSUNG`
https://lyw7mov3ql.csb.app/?refinementList%5Bbrand%5D%5B0%5D=SAMSUNG

3. Refresh the page

4. Observe the correct results appear, but the refinementList shows duplicates (one for each case type)

**Expected behavior 💭**
RefinementList should only show one listing.

**Screenshots 🖥**
<img width="881" alt="Screen Shot 2019-07-29 at 5 03 27 PM" src="https://user-images.githubusercontent.com/314653/62136052-f8354000-b2a8-11e9-8680-a407fa642431.png">

**Environment:**
All

**Additional context**
Most definitely an edge case. Everything works as expected if the facet is selected via the refinementList widget itself. It's only when the facet is changed manually elsewhere AND the records contain multiple case types that the bug appears.

I believe this stems from the Algolia engine using the case type of the first record indexed when defining each facet. So if record 1 shows TitleCase `key: Value` and record 2 shows UPPERCASE `key: VALUE`, the facet will be recorded as TitleCase for all records containing any version of `key: value`.

In my scenario, visitors can refine facets by clicking directly on the results item (see screenshot below). InstantSearch produces the correct results, but now the UPPERCASE version of the facet starts polluting the client producing the unintended results.

The upstream fix for most folks is to ensure records are normalized prior to indexing, but in my scenario the records need to be presented as-is.
 
![Screen Shot 2019-07-30 at 9 28 09 AM](https://user-images.githubusercontent.com/314653/62138293-09804b80-b2ad-11e9-915f-7f5e90f3b120.png)

**Comment by samouss** [comment]
Unfortunately, InstantSearch can't do anything about that. The engine treats facet in as case-insensitive. Indeed like you said the fix for this is to ensure that the data sent to Algolia always share the same case.

Since it's not an InstantSearch related problem, I'll close the issue. You can write a message to [Algolia support](https://www.algolia.com/support/). It's always interesting for us to have feedback on the product, especially on corner case like this one.
