### ISSUE TITLE
0.0.1 Roadmap

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#40]
We aim for a 0.0.1 release.

We have a [0.0.1 milestone](https://github.com/algolia/instantsearch.js/milestones/0.0.1). This issue was made to easily track and comment on the 0.0.1 roadmap.

## Goals

Being able to reproduce the [instant search demo](http://demos.algolia.com/instant-search-demo/) using instantsearch.js.

Get CSE and integrators (magento, wordpress) to use and give us feedback on the instantsearch.js API.

The library should be hosted on jsDelivr. Even if we are at the prototype state where we will break the API.

[Check the 0.0.1 milestone](https://github.com/algolia/instantsearch.js/milestones/0.0.1) on github to get a good idea of what's required for the release.

## New widgets

Here are all the widgets and related issues we need to do for 0.0.1:

- [x] hits
- [x] pagination #13
- [x] multipleChoiceList #42 
- [x] menu #49 
- [x] toggle #41
- [x] slider #11 
- [x] stats #12 
- [x] indexSelector #38 
- [x] urlSync #17 

See all the [new widget](https://github.com/algolia/instantsearch.js/issues?q=is%3Aopen+label%3A%22new+widget%22+milestone%3A0.0.1) related issues for 0.0.1.

We should also make sure that we document each widget API in the project readme (for now), like we did for the first widgets.

## Bug fixes and enhancements

[Check the 0.0.1 milestone](https://github.com/algolia/instantsearch.js/milestones/0.0.1) to see other remaining bugs and enhancements we should do.

**Comment by vvo** [comment]
Ok we have detailed most APIS but the slider, we can start implementing like beasts!

**Comment by bobylito** [comment]
GoGoGOOOO!

**Comment by redox** [comment]
:+1:
