### ISSUE TITLE
Error "cannot read property query of undefined" Angular-instant search V2.2.2 + Algoliasearch 3.30.0

### ISSUE THREAD

**Issue by ReaperTech** [algolia/instantsearch.js#4006]
Trying to implement this sandbox [https://codesandbox.io/s/angular-instantsearch-app-4n4yv](url) to prevent search on an empty query using Angular Instant Search v2.2.2 + Algoliasearch 3.30.0 but I'm getting this error. The error occurs as soon as I open the component that uses the angular instant sarch. Please can you help?
![image](https://user-images.githubusercontent.com/43549638/62226486-95cc6480-b3ba-11e9-8391-22159eda6493.png)
![image](https://user-images.githubusercontent.com/43549638/62225383-9cf27300-b3b8-11e9-9152-0e396b0986d7.png)
![image](https://user-images.githubusercontent.com/43549638/62225403-a8459e80-b3b8-11e9-83c0-4584db8e36ec.png)

**Environment:**
 - OS: W10
 - Browser chrome 75.0

**Comment by francoischalifour** [comment]
_I answered by email but also answering here for visibility._
​
​Mocking the request when there is no query should work.

```ts
const algoliaClient = algoliasearch(
  "latency",
  "6be0576ff61c053d5f9a3225e2a90f76"
);

const searchClient = {
  search(requests) {
    if (requests.every(({ params }) => !params.query)) {
      return Promise.resolve({
        results: requests.map(() => ({
          hits: [],
          nbHits: 0,
          processingTimeMS: 0,
        })),
      });
    }

    return algoliaClient.search(requests);
  },
};
```

If you only want the very first empty query to be skipped, you can add a boolean flag to ignore the check for the next searches.​

**Comment by ReaperTech** [comment]
**Solution**: My error is now gone thanks to this solution from Francois at Algolia who replied in an email thread:

"Mocking the request when there is no query" 

Here is an example:
```
const algoliaClient = algoliasearch(
  "latency",
  "6be0576ff61c053d5f9a3225e2a90f76"
);

const searchClient = {
  search(requests) {
    if (requests.every(({ params }) => !params.query)) {
      return Promise.resolve({
        results: requests.map(() => ({
          hits: [],
          nbHits: 0,
          processingTimeMS: 0,
        })),
      });
    }

    return algoliaClient.search(requests);
  },
};
```

**Comment by ReaperTech** [comment]
I just want to comment on the fantastic support from Algolia. I always get a reply from the Algolia team, sometimes within a couple of hours. If you post a commment on algolia.com (at the bottom of their pages) where it asks "Did you find this page helpful?", they will definitely reply if you provide an email address. Algolia have replied at least 15 times to email and here on Github in the last 3 days! By the way I'm only on the free trial! Thanks guys!
