### ISSUE TITLE
RefinementList improvement: "show XX more"

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#401]
Below the list of X refinements, it would be cool to have a "Show Y more" toggling hidden values.

![image](https://cloud.githubusercontent.com/assets/29529/10883225/c7c0fbb6-8170-11e5-9ae0-27b54987bc1e.png)

### Need

Let the user display more choices in a single `refinementList` widget. Those will be actually fetched each time but they are hidden. We would need the max number of items to display when not hidden, and also the max number of items to fetch at each search result to avoid loading too much items. We also need two templates for the 'show more' link/button so that we have the display for each of its state.

### Proposal

Here are the following new options for the `refinementList` widget : 
  - options.templates.showmore-active : template used when we displayed more facets values
  - options.templates.showmore-inactive : template used when the more facets are hidden
  - options.showmore
  - options.showmore.maxDefaultDisplayItems : number of items displayed when the state is inactive
  - options.showmore.maxFetchedFacetValues : the number of facet values fetched at each request

### Behaviour specifics

This feature relies on `maxValuesPerFacet` which is common to all the facets retrieved. If two `refinementList` use showmore, the value used in configuration should be the max() of the two.

**Comment by vvo** [comment]
I feel this one could be done, a lot of our implementations have it.

**Comment by chrisvidal** [comment]
my project need this 'show more' link as well, defintely a must have>
In the same range of idea, a input filter, kind of auto-complete, would help the user to find his filter as well. 
So i imagine an input text ( hidden per default) where the user can 'search' in the facet list directly instead of clicking 10 times on the 'show more' link to find his value.
Yes in my scenario, we have a lots of possilbie filter values (up to 36 000 for the projects for example)
hence the requirements.

does it makes sense ?

**Comment by bobylito** [comment]
@chrisvidal well it makes sense but Algolia can only retrieve a certain of values. The best would be a dedicated index for your facet values which is out of the scope of this issue. Can you make an other issue for that?

**Comment by chrisvidal** [comment]
ok thanks, done here https://github.com/algolia/instantsearch.js/issues/757

**Comment by vvo** [comment]
@bobylito We have a new API proposal can you update it here so that people will not comment on the previous one. thx
