### ISSUE TITLE
Toggle issue

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#408]
Related to #219 .

The `toggle` widget doesn't really do what it does : it just checks, when enabled, that a facet is true.
However, there is no way to toggle it to false, making its behaviour different from what its name could make us think.

The behaviour I expect from a toggle button is a binary behaviour: http://www.bootstrap-switch.org/examples.html , and right now when the checkbox is unchecked, we're actually in the *Indeterminate* example of this page.

**Comment by vvo** [comment]
Relevant discussions also: https://github.com/algolia/instantsearch.js/issues/41#issuecomment-128375498

We had trouble naming this one or finding a good API that allow both use cases in an easy to understand way.

Do you have any idea how to make it clearer/better. For sure this issue will be raised by people :)

**Comment by Jerskouille** [comment]
What about something like `constantFilter` ?
This would allow this one to be more generic, and could even maybe even accept an optional operator to handle use cases like `Past week`, `Past month`, etc. or `My favorites` (which would be `favorited_by_ids:my_id`), etc.
WDYT ?

**Comment by Jerskouille** [comment]
Actually, `Past week`, `past month` would require a list so it should probably go in another widget. But `My favorites` still makes sense to me.

**Comment by vvo** [comment]
Clsoing in favor of #409
