### ISSUE TITLE
Allow choosing on and off values to the toggle

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#409]
Following #408 we had an idea with @Jerskouille to allow the toggle to be really usable in various toggling situations.

We can add "on value" and "off value" feature to the current toggle API.

Handle "free_shipping" being either `true` or nothing (nothing = free + non free shipping)
```js
toggle({
  facetName: 'free_shipping',
  values: {
    on: true
  }
})
```

Handle "archived" being either `true` or `false`:

```js
toggle({
  facetName: 'archived',
  values: {
    on: true
    off: false
  }
})
```

Handle "fruit" being `banana` or `oranges`:

```js
toggle({
  facetName: 'fruit',
  values: {
    on: 'banana',
    off: 'orange'
  }
})
```

Handle "only my favorites" or "everything":

```js
toggle({
  facetName: '_tags',
  values: {
    on: 'user42'
  }
})
```

Be careful about the default count we send, it's right now not accurate (showing "false" values instead of true)

**Comment by redox** [comment]
Maybe I would go for a nested `values` object to keep the same naming strategy than `templates` and `cssClasses`. WDYT?

```js
toggle({
  facetName: '_tags',
  values: {
    on: 'myON',
    off: 'myOFF'
  }
})

**Comment by vvo** [comment]
> WDYT?

yes I was unsure also about the on/off**Value** thing. Maybe it makes more sense what you wrote.

**Comment by vvo** [comment]
Updated the proposal

**Comment by Jerskouille** [comment]
:+1: I really like it, but would love to have the input of @pixelastic and @kokliKo on this one too.

**Comment by kokliKo** [comment]
LGTM

**Comment by pixelastic** [comment]
What happens on first load with:

```javascript
values: {
  on: 'banana',
  off: 'orange'
}
```

Will it be in an undefined state or directly set to `orange`? I would set it to `orange`

**Comment by vvo** [comment]
It should be an option and forcing the user to provide the default value (explicit)

**Comment by Jerskouille** [comment]
I would go for a default to the `offValue` if provided, and add an optional `defaultState: ['on', 'off', null/undefined]`.
