### ISSUE TITLE
[switch] create widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#41]
This widget needs to be able to render this:

![2015-08-05-110722_497x143_scrot](https://cloud.githubusercontent.com/assets/123822/9082132/2f0f3b0c-3b62-11e5-9cd4-1ef7a5a88849.png)

Well not exactly since this current UI is bad: you cannot tell if you are looking for free shipping items or not.

For a first iteration I would opt for a simple `checkbox`. Checked means true, unchecked means no specific filter.

### Index requirement

The targeted attribute should be a `boolean`.

### Behavior

- When checked, it means that we send a facetfilter with `attributeName: true`
- When not checked it means we will not send any facetFilter for the attribute (true + false)

### Usage

Given this html:

```html
<div id="free-shipping"></div>
```

And JavaScript:

```js
instant.addWidget(
  instantsearch.widgets.switch({
    container: '#free-shipping',
    facet: 'freeShipping',
    label: 'Free shipping'
  })
)
```

We default to render:

```html
<div><label><input type="checkbox" checked />Free shipping</label></div>
```

### Options

* `container` string or DOMElement
* `facet` string
* `label` string
* `template` string (hogan) or function
* `cssClass` string (space separated css classes to apply to root element)

### Available data when passing your own template

* `isRefined` boolean

**Comment by bobylito** [comment]
I think switch would be the most appropriate name and UI concept : http://www.google.fr/design/spec/components/selection-controls.html#selection-controls-switch

**Comment by vvo** [comment]
only concerned about having widget.switch (switch being a reserved keyword), do you think it's an issue?

**Comment by vvo** [comment]
About the purpose of the widget: what do it means to have a "free shipping" toggle?

- when on: show me only the free shipping items
- when off: does'nt care about free shipping, but keep showing me both free and not free shipping

The thing is that for some other properties it does not works.

If I have an `archives` boolean attribute for my store, does the toggle means:

- when on: show me only the archived items
- when off: show me only the active items

Or does it means:

- when on: show me only the archived items
- when off: show me both

**Comment by vvo** [comment]
API descri[ption updated

**Comment by bobylito** [comment]
Lgtm!

**Comment by pixelastic** [comment]
I'm not yet sold on the switch or toggle naming. We are not really switching from true to false, we are switching from true to undefined.

The name does not really reflect that and will lead to confusion. Maybe `restrictToggle` or `restrictSwitch` instead.

**Comment by vvo** [comment]
> I'm not yet sold on the switch or toggle naming. We are not really switching from true to false, we are switching from true to undefined.
> 
> The name does not really reflect that and will lead to confusion. Maybe restrictToggle or restrictSwitch instead.

Yes the fact that toggles/switch can have to different behavior is tricky I dunno how to handle it.
