### ISSUE TITLE
Use a more typesafe pattern for "static" values in render parameters

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#4102]
Currently we use three patterns for storing functions like `refine` etc. to both init and render. We need to make sure we never reassign the function reference directly, because that means if someone with a custom connector has an event listener in a conditional, they "lose" the reference (this is the same problem as with useEffect in React, for which they have the dependency array).

```js
const customWidget = connectSomething(
  ({ refine, widgetParams: { container } }, firstRender) => {
    if (firstRender) {
      const btn = document.createElement('button');
      container.appendChild(btn);
      btn.addEventListener('click', () => refine());
    }
  }
);
```

this previous code only works, because we make sure the "refine" reference can become state without issue, and always stays the same for us.

The problem is that we use many methods to do this. As far as I can tell we have the following methods:

1. "public" method & reassign private method

```js
const widget = {
  _refine() {
    return refine();
  },
  init() {
    refine = xxx;
    renderFn({
      refine: this._refine,
    });
  },
  render() {
    renderFn({
      refine: this._refine,
    });
  },
};
```

2. "private" container & reassign within that

I'm not actually sure if this works as we think it does, we need to check that this doesn't erase the reference

```js
const createWidget = () => {
  const connectorState = {};
  return {
    init() {
      connectorState.refine = xxx;
      renderFn({
        refine: connectorState.refine,
      });
    },
    render() {
      renderFn({
        refine: connectorState.refine,
      });
    },
  };
};
```

3. Set in `init` and never override

```js
const widget = {
  init() {
    this._refine = xxx;
    renderFn({
      refine: this._refine,
    });
  },
  render() {
    renderFn({
      refine: this._refine,
    });
  },
};
```

---

Personally I think that all of these methods have big flaws, because they're:

1. inconsistent
2. hard to remember
3. hard to test for

A good solution would be more automatic, harder to forget, easy to convert all functions to.

There's two suggestions I have:

1. remove `init`

We don't really have much use for it (we don't use this function to render in vanilla, Vue, nor Angular), and could do with the simplicity of purely a render function. The downside is that this would become hard to pass `isFirstRender`, but that can be solved like this:

```js
const createWidget = () => {
  let isFirstRender = true;
  return {
    render() {
      renderFn({}, isFirstRender);
      // maybe this can be done more efficient if we see it hurts perf
      isFirstRender = true;
    },
  };
};
```

1. return an object in `init`.

This object can then be passed to `render` as well, and will contain all cached methods, instead of on the instance, which is definitely confusing (the less `this`, the more happy IMHO).

```js
const widget = {
  init() {
    const connectorState = {
      refine: xxx
    }
    renderFn({
      refine: refine,
    });
    return connectorState
  },
  render(stuff, connectorState) {
    renderFn({
      refine: connectorState.refine,
    });
  },
};
```

This is close to method 2, which is used in the TypeScript connectors, because it avoid pitfalls with `this`, but avoids the fact that we need to type the "connectorState", as `Partial<ConnectorState>`, even though everything is always defined when we are using it in `render`

This also avoids issues where we implicitly need the order between init & render, but aren't able to enforce that in any way, if the output becomes an argument, it becomes clear when rendering is out-of-order.

---
---

Now that I've written all of this, I'm realising it probably should have been an RFC, I'll convert it once we have a first bit of feedback here :)

**Comment by eunjae-lee** [comment]
I agree with this.
Personally I prefer the first suggestion as long as `init` itself doesn't bring us much value.
If we can merge the usage of `init` and `render` into one `render` function, we can do in `render` what `init` used to do, for example, assigning variables using `helper`. And they will be done only once by using `isFirstRender`.

**Comment by Haroenv** [comment]
this is solved in all connectors now that they're migrated
