### ISSUE TITLE
Documentation: bottom left links are redundant/taking too much space?

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#411]
![2015-11-02-184805_335x670_scrot](https://cloud.githubusercontent.com/assets/123822/10889432/4ca10436-8192-11e5-954a-531ce8de2c18.png)

I am talking about the octocat/fork/stackoverflow icons.

Right now they are sticky to the documentation and are taking a good visual spot/place. But as a developer I would only need to see the octocat in the top right of the top menu.

Also the fork and octocat are redirecting to the same thing, and even "fixing" the fork button to actually fork the project would be weird.

You never really want to fork from a website that is not github, you just want to see the github project and browse it first.

I would put the octocat in top right and allow this space to be used for the left menu. Also the left menu will at some point take more height space so it will start looking weird as a fixed position menu.

What do you think?

**Comment by bobylito** [comment]
Will change that to something integrated in the flow of the menu as you proposed @vvo :)

**Comment by redox** [comment]
Not convinced by the proposal. I like seeing the version in that fixed zone; happy to have the fork/github icons as well. I agree we could have the octocat on every pages however (so maybe move it to top right).

That being said, if we don't put the icons there (fixed, bottom), we should remove them from the menu because it doesn't make sense to have them in the menu flow.

**Comment by bobylito** [comment]
Ok I can remove that completely. To be honest, when I started moving around stuff, I wasn't sure myself and it felt weird.

Let's  change that and  remove the links completely and add the icons on the right as you proposed. 

What about the version number though? I feel it's important to have it.

**Comment by vvo** [comment]
Version could be shown here:

![2015-11-02-224318_553x208_scrot](https://cloud.githubusercontent.com/assets/123822/10895245/7a67d252-81b3-11e5-9fda-05a0c7fabb14.png)

(top right of the logo)

**Comment by bobylito** [comment]
WFM
