### ISSUE TITLE
Documentation: too much scroll bars when not the right width/height

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#412]
![2015-11-02-185233_1297x809_scrot](https://cloud.githubusercontent.com/assets/123822/10889544/e85a5206-8192-11e5-9f4d-8461540ba6f1.png)

I have a lot of scrollbars showing up when browsing the doc. This may be because of my browser width/height but that's not a good indicator of our CSS because it will fail in other setups also?

**Comment by bobylito** [comment]
On it!
