### ISSUE TITLE
connectNumericMenu not working with same `start` value in `items`

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/instantsearch.js#4121]
**Describe the bug 🐛**

connectNumericMenu is not working when there are more than one items with same `start` value in `items`.

**To Reproduce 🔍**
1. Open `numeric-menu.stories.js`
2. Add the following story:
```js
  .add(
    'same start value',
    withHits(({ search, container, instantsearch }) => {
      search.addWidget(
        instantsearch.widgets.numericMenu({
          container,
          attribute: 'price',
          items: [
            { label: 'All' },
            { start: 1, end: 2, label: '1-2' },
            { start: 1, end: 10, label: '1-10' },
          ],
        })
      );
    })
  )
```

3. Click `1-2`.
4. `1-10` is selected instead.

**Expected behavior 💭**
`1-2` is supposed to be selected

**Screenshots 🖥**

![Kapture 2019-09-17 at 14 14 45](https://user-images.githubusercontent.com/499898/65040805-88ad0a00-d955-11e9-9c10-31658b4e55c9.gif)

**Comment by msassa** [comment]
I will be waiting for a solution to this bug, I also found the same problem. Thanks !

**Comment by msassa** [comment]
Any solution about this issue? Thanks.

**Comment by Haroenv** [comment]
Hi @msassa, this issue has not been prioritized yet, sorry! We have found out about it two weeks ago, but its behaviour has been like this for much longer.

A workaround for now can be to use float values which are just slightly different, which would avoid the issue

**Comment by msassa** [comment]
Hi @Haroenv .
What do you mean with use float values?
Something like this:

```
    [
        { label: 'Max Kms' },
        { label: '9,999 or less', start: 1.0, end: 9999.0 },
        { label: '19,999', start: 1.0, end: 19999.0 },
        { label: '34,999', start: 1.0, end: 34999.0 },
        { label: '44,999', start: 1.0, end: 44999.0 },
        { label: '54,999', start: 1.0, end: 54999.0 },
        { label: '99,999', start: 1.0, end: 99999.0 },
        { label: 'Over 100,000', start: 100000 },
    ]
```

neither does it work.

**Comment by Haroenv** [comment]
I meant different ones for the identical values, 1.001, 0.99999 as a workaround

**Comment by antoinewg** [comment]
Hello @Haroenv. I've tried to tackle this bug in the following PR: https://github.com/algolia/instantsearch.js/pull/4951.
Hope this looks good
