### ISSUE TITLE
Allow routing without a search box (regular JS / non-react version)

### ISSUE THREAD

**Issue by t0byman** [algolia/instantsearch.js#4129]
**Is your feature request related to a problem? Please describe 🙏**
No.

**Describe the solution you'd like 🤔**
I would like to be able to do routing without having a search box on my page.

**Describe alternatives you've considered ✨**
I added routing using the parseURL method. It works great, but only when I have a search box on my page. This is because of `const { query = queryName } = qsModule.parse(
                            location.search.slice(1)
                        );` the location.search part is telling the query to go into the search box so that my results can be filtered. But I want them to be filtered without a search box, when the page loads. Is this possible? If not, here is my feature request :)

**Additional context**
Here is my complete routing code:
```js
routing: {
                router: instantsearch.routers.history({
                    parseURL({ qsModule, location }) {
                        const pathnameMatches = location.pathname.match(/zoeken\/(.*?)\/?$/);
                        const queryName = getQueryName(
                            (pathnameMatches && pathnameMatches[1]) || ''
                        );
                        const { query = queryName } = qsModule.parse(
                            location.search.slice(1)
                        );

                        return {
                            query: decodeURIComponent(query),
                        };
                    }
                }),

                stateMapping: {
                    stateToRoute(uiState) {
                        return {
                            query: uiState.query,
                        };
                    },

                    routeToState(routeState) {
                        return {
                            query: routeState.query,
                        };
                    }
                }
            }
```

**Comment by francoischalifour** [comment]
Mounting a search box widget on the page is necessary for the `query` search parameter to be sent to Algolia. Widgets drive search parameters.

You don't have to display a search box though, you can create a virtual widget without rendering with [`connectSearchBox`](https://www.algolia.com/doc/api-reference/widgets/search-box/js/#connector).

**Comment by t0byman** [comment]
Thanks!
