### ISSUE TITLE
Ability to preselect min and max SELECTED values on rangeSlider, not to be confused with the rangeSlider min and max values

### ISSUE THREAD

**Issue by michaelstoffer** [algolia/instantsearch.js#4135]
There seems to be a simple way to preselect values on a refinement list like so:

`const search = instantsearch({
	searchParameters: {
		disjunctiveFacetsRefinements: {
			refinement1: ['data1'],
			refinement2: ['data2', 'data3']
		}
	}
});`
I'm looking for a way to be able to do this with a rangeSlider like so:

`const search = instantsearch({
	searchParameters: {
		disjunctiveFacetsRefinements: {
			refinement1: ['data1'],
			refinement2: ['data2', 'data3'],
			rangeSlider1: {
				min: 15,
				max: 115
			}
		}
	}
});`

This would be able to maintain the ACTUAL min and max values, but move the selection of the rangeSlider to the above values.

If someone knows of a way to do this, it would be greatly appreciated.

**Comment by francoischalifour** [comment]
The `rangeSlider` widget reacts to `numericRefinements`. Here's an example with the `price` attribute:

```js
const search = instantsearch({
  indexName: 'instant_search',
  searchClient,
  searchParameters: {
    numericRefinements: {
      price: {
        '>=': [15],
        '<=': [115],
      },
    },
  },
});
```

Note that in the upcoming InstantSearch v4, this will be more straightforward with the concept of `uiState`:

```js
// Available from InstantSearch v4
const search = instantsearch({
  indexName: 'instant_search',
  searchClient,
  initialUiState: {
    range: {
      price: '15:115',
    },
  },
});
```
