### ISSUE TITLE
I need a widget for list and grid view on same page

### ISSUE THREAD

**Issue by amit4106udale** [algolia/instantsearch.js#4155]
I need a widget which have two options of gird and list view. based on the selections the view will change.

**Comment by Haroenv** [comment]
This can be done with css in an `ais-hits` template. How would you expect this to be handled by the library?

**Comment by Haroenv** [comment]
Sorry, thought it was Vue InstantSearch, you should do it with an external toggle which changes a css class containing the hits.

**Comment by Haroenv** [comment]
https://github.com/Shipow/searchstone/blob/master/src/js/is-custom/layout-picker.js Can also be used as inspiration if it needs to be tracked in the url

**Comment by Haroenv** [comment]
@amit4106udale, can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!
