### ISSUE TITLE
How do i map my tranformed data json returned from promise to my hits 

### ISSUE THREAD

**Issue by amit4106udale** [algolia/instantsearch.js#4166]
I have done an ajax call on tranformItems

		instantsearch.widgets.hits({
			container: '#hits',
			  transformItems(items) {
				  a =  hitsTransformation(items);
                       }
              });

        function hitsTransformation(data)
         {
		return jQuery.ajax({
			url: xyz url,
			type: 'POST',
			data:  {hits},
			dataType: 'json',
			success: hits
			});
          }

I need to map the ajax returned JSON to my hits.

Help me out, please.

**Comment by Haroenv** [comment]
For this it might make more sense to hook this into your search client itself. In rough terms this would be:

```js
const algoliaSearchClient = algolisearch('...', '...');

const searchClient = {
  search: function(requests) {
    return algoliaSearchClient.search(requests).then(result => {
      // do your api call here
    })
  },
  searchForFacetValues: function(requests) {
    return algoliaSearchClient.searchForFacetValues(requests)
  }
};
```

**Comment by amit4106udale** [comment]
> For this it might make more sense to hook this into your search client itself. In rough terms this would be:
> 
> ```js
> const algoliaSearchClient = algolisearch('...', '...');
> 
> const searchClient = {
>   search: function(requests) {
>     return algoliaSearchClient.search(requests).then(result => {
>       // do your api call here
>     })
>   },
>   searchForFacetValues: function(requests) {
>     return algoliaSearchClient.searchForFacetValues(requests)
>   }
> };
> ```
> 
> You then pass `searchClient` as an argument to `instantsearch({ searchClient })`

Will this automatically map the transformed json to hits?

**Comment by amit4106udale** [comment]
What if i use
     	search.addWidget({
		  render: function(data) {
			a = hitsTransformation(data.results.hits)
		    console.log(a);
		  }
		})

**Comment by amit4106udale** [comment]
> > For this it might make more sense to hook this into your search client itself. In rough terms this would be:
> > ```js
> > const algoliaSearchClient = algolisearch('...', '...');
> > 
> > const searchClient = {
> >   search: function(requests) {
> >     return algoliaSearchClient.search(requests).then(result => {
> >       // do your api call here
> >     })
> >   },
> >   searchForFacetValues: function(requests) {
> >     return algoliaSearchClient.searchForFacetValues(requests)
> >   }
> > };
> > ```
> > 
> > 
> > You then pass `searchClient` as an argument to `instantsearch({ searchClient })`
> 
> Will this automatically map the transformed json to hits?

I dont need anything based on search,
I just need to transfrom my hits json onBefore or onAfter the hits are rendered.

Sorry to bother you but i am fresher in this.

**Comment by amit4106udale** [comment]
@Haroenv Also i need to show transformed json data on client side

**Comment by Haroenv** [comment]
Yes, if you modify the response it will be directly taken in account for the hits. I made an example for you here:

https://codesandbox.io/s/instantsearchjs-app-l3dft

```js
const searchClient = {
  search: function(requests) {
    return algoliaSearchClient.search(requests).then(content => {
      // do your api call here
      const hits = content.results[0].hits;
      console.log(hits);
      return $.ajax('https://httpbin.org/anything', {
        method: 'POST',
        content: { hits },
      }).then(res => {
        // return from request
        // content.results[0].hits = res
        return content;
      });
    });
  },
  searchForFacetValues: function(requests) {
    return algoliaSearchClient.searchForFacetValues(requests);
  },
};
```

as you can see, you need to make sure you "modify" the response from the regular js client

**Comment by amit4106udale** [comment]
> Yes, if you modify the response it will be directly taken in account for the hits. I made an example for you here:
> 
> https://codesandbox.io/s/instantsearchjs-app-l3dft
> 
> ```js
> const searchClient = {
>   search: function(requests) {
>     return algoliaSearchClient.search(requests).then(content => {
>       // do your api call here
>       const hits = content.results[0].hits;
>       console.log(hits);
>       return $.ajax('https://httpbin.org/anything', {
>         method: 'POST',
>         content: { hits },
>       }).then(res => {
>         // return from request
>         // content.results[0].hits = res
>         return content;
>       });
>     });
>   },
>   searchForFacetValues: function(requests) {
>     return algoliaSearchClient.searchForFacetValues(requests);
>   },
> };
> ```
> 
> as you can see, you need to make sure you "modify" the response from the regular js client

Thank you so much this worked

**Comment by amit4106udale** [comment]
Will this  work for 

	search.addWidget({
		  render: function(hits) {
		      return $.ajax('https://httpbin.org/anything', {
        method: 'POST',
        content: { hits },
      }).then(res => {
        // return from request
        // content.results[0].hits = res
        return content;
      });
		  }
		})

**Comment by amit4106udale** [comment]
The rendering of widgets are now taking time, So i think this will be better if it after the content is rendered. What do you say @Haroenv

**Comment by amit4106udale** [comment]
I have done somthing like this
	search.addWidget({
		  render: function(data) {
			      // do your api call here
			      const hits = data.results.hits;
			      return jQuery.ajax({
					url:asdnkas,
					type: 'POST',
					data:  {hits},
			      }).then(res => {
			        // return from request
			    	  data.results.hits = JSON.parse(res)
			        return data;
			      });
		  }
		});


Unable to map the data to hits

**Comment by Haroenv** [comment]
Asynchronous work needs to be done in the search client, the widgets themselves are synchronous :)

**Comment by amit4106udale** [comment]
@Haroenv We onRender event can we do it using that?

**Comment by Haroenv** [comment]
InstantSearch will not wait to render for any asynchronous behaviour, the only place you can make a response stall is using the method I described.

**Comment by amit4106udale** [comment]
ohk thanks.

**Comment by Haroenv** [comment]
I'll close this issue now, since I think the resolution is clear, but if you have more issues, please create what you have so far in a sandbox environment. We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

**Comment by amit4106udale** [comment]
I just need to lower the loading time by transforming data on after rendering the content. Still searching for solution

**Comment by Haroenv** [comment]
If loading time is essential, I'd suggest you do the transforming before indexing your data

**Comment by amit4106udale** [comment]
@Haroenv - I agree with your comment, but the data based on which we are transforming some data is  logged in user. So I can't transform it before indexing. I need to transform is while rendering only

**Comment by Haroenv** [comment]
I'm not exactly sure what you mean, but please make a sandbox with the code so we can understand your use case
