### ISSUE TITLE
The template "InstantSearch.js" does not support the version 4.0.0.

### ISSUE THREAD

**Issue by core-code** [algolia/instantsearch.js#4171]
i get this whether running the 

`npx create-instantsearch-app ais-ecommerce-demo-app \
`
command recommended in the docs or when running interactively:

`The template "InstantSearch.js" does not support the version 4.0.0.
`

**Comment by francoischalifour** [comment]
This issue was fixed in algolia/create-instantsearch-app#442 which will be released tomorrow morning, France time.
