### ISSUE TITLE
How can i use the my absolute urls in algolia?

### ISSUE THREAD

**Issue by amit4106udale** [algolia/instantsearch.js#4188]
Currently, the relative URLs are getting appended in the base url. But, if we need the absolute urls to be used how can is use it from hit data.

**Comment by amit4106udale** [comment]
@Haroenv - Can you please help me out with this?

**Comment by Haroenv** [comment]
I don't understand your question, please give a sandbox. We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

**Comment by amit4106udale** [comment]
@Haroenv - As per your sandbox "**https://xo94wl403z.csb.app/**" is your base url so, if i want to 
redirect the user to another page after clicking on hit i.e "**Amazon - Fire TV Stick with Alexa Voice Remote - Black**". At that time whatever the url of that hit is, it get appended to the base url 
for example:-

If my url for that hit (specific entity) is :-  https://github.com/algolia/instantsearch.js/issues/4188

Once i click on that hit , Url gets appended to the bas url 
https://xo94wl403z.csb.app/https://github.com/algolia/instantsearch.js/issues/4188
like this.

I just dont want that to happen.

**Comment by Haroenv** [comment]
Why is the `href` in your example https://www.algolia.com/users/sign_in instead of the link you want to go to? e.g. if the url you put in Algolia are complete urls, then do:

```
<a href="{{href}}">
```

or whatever the name of the attribute is. If the URL is relative, then:

```
<a href="https://base.com/{{path}}">
```

Is that what you meant?

**Comment by amit4106udale** [comment]
@Haroenv - Thanks

**Comment by amit4106udale** [comment]
> Why is the `href` in your example https://www.algolia.com/users/sign_in instead of the link you want to go to? e.g. if the url you put in Algolia are complete urls, then do:
> 
> ```
> <a href="{{href}}">
> ```
> 
> or whatever the name of the attribute is. If the URL is relative, then:
> 
> ```
> <a href="https://base.com/{{path}}">
> ```
> 
> Is that what you meant?

@Haroenv - Yes i tried the same. But this works when i create my template of hit js

instantsearch.widgets.hits({
	container: '#hits',
	escapeHTML: false,
	templates: {
		item: "**Hit design**"

But when i create my **Hit design** (tepmlate) in another Html file within the script tags, and accessing that as given below It does not work.

**instantsearch.widgets.hits({
	container: '#hits',
	escapeHTML: false,
	templates: {
item :document.getElementById('hit-template-row').innerHTML

**Comment by Haroenv** [comment]
I don't understand the issue, those should behave the same. Could you try to reproduce the exact issue in code please?
