### ISSUE TITLE
How can i modify the search query before rendering the data?

### ISSUE THREAD

**Issue by amit4106udale** [algolia/instantsearch.js#4192]
For example,

I have

```
[
  {
    "name": "Chicken Stuffed Baked Avocados",
    "restaurant": "The Hive",
    "_tags": ["low-carb"]
  },
  {
    "name": "Spinach Quiche",
    "restaurant": "Bert's Inn",
    "_tags": ["low-carb", "vegetarian"]
  },
  {
    "name": "Pizza Chicken Bake",
    "restaurant": "Millbrook Deli",
    "_tags": ["cheese"]
  },
  {
    "name": "Strawberry Sorbet",
    "restaurant": "The Hive",
    "_tags": ["low-fat", "vegetarian", "vegan"]
  }
]
```

i want to show only the restaurants "The Hive" by modifying the query through my js

**Comment by tkrugg** [comment]
Hey @amit4106udale I can't make any real suggestions here, as I know very little about your stack.
I'll assume you're using InstantSearch.js, in case which what's you want can be accomplished with a [refinementList](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/).

Here are the steps, roughly:

1. in your Algolia Dashboard, make sure `restaurant` attribute is added as a facet. (see [our docs](https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/how-to/declaring-attributes-for-faceting/) if you don't know how to do this)

2. add a refinementList widget with attribute `restaurant`, very much like we do it on this example with attribute `brand` in this example: https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/how-to/declaring-attributes-for-faceting/

I hope this helps. Closing but feel free to reopen if this doesn't answer your question.

**Comment by amit4106udale** [comment]
@tkrugg - Yes i am using InstantSearch.js,

I know about the faceting but i want the data to be changed based on user logging in. So, 
If user A logges in i want to show all 
if user B logges in i want to show specefic.

That's why is want to modify the query dynamically.

**Comment by tkrugg** [comment]
oh ok, in that case I would advise to use different API keys, specific to a user.
We call them ses specific API keys: [Secured API keys](https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/). I hope this helps.
