### ISSUE TITLE
[multipleChoiceList] create widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#42]
This widget needs to be able to render this:

![2015-08-05-111518_457x464_scrot](https://cloud.githubusercontent.com/assets/123822/9082292/453e14ce-3b63-11e5-9efb-6fa09e2485ab.png)

## API

Given this html:

```html
<div id="manufacturer"></div>
```

And this JavaScript:

```js
instant.addWidget(
  instantsearch.widgets.multipleChoiceList({
    container: '#manufacturer',
    facetName: 'manufacturer'
  })
)
```

Default rendering output (no provided template):

```
<ul class="as--multipleChoiceList">
  <li><label><input type="checkbox" value="Sony" checked />Sony <span>302</span></label></li>
  <li><label><input type="checkbox" value="Microsoft" />Microsoft <span>120</span></label></li>
</ul>
```

`<label>` is important to allow clicking on the "Sony" label rather than just the checkbox. This is also the standard way bootstrap advocates writing checkboxes.

I did not detail css classes but there should be css classes  aroud elements for people to style them. Following #47?

### Options

* `container` string or DOMElement
* `facetName` string
* `template` string (hogan) or function

### Available data when passing your own template

Template will be inserted `<li>HERE</li>`

* `value` string
* `count` number
* `selected` boolean

### Default sort

By default we can sort by name.

Once we are able to sort the facet values (https://github.com/algolia/algoliasearch-helper-js/issues/178) then we can provide the option here.

**Comment by vvo** [comment]
We need to be able to indicate

```js
instant.addWidget(
  instantsearch.widgets.chooseMany({
    attribute: 'category.name',
    type: 'AND' // conjunctive
    // type: 'OR' // disjunctive
  })
)
```

cc @maxiloc

**Comment by maxiloc** [comment]
For me it makes more sense to separate conjunctive and disjunctive into to separate widget. As it might not be the same template.

**Comment by bobylito** [comment]
This component is a list so the name should reflect that. Also the final user make multiple choices. So I propose to rename it to multipleChoiceList

**Comment by bobylito** [comment]
Humm the and/or question is tricky. On one hand I would say that it's not the user concern, he only wants to do the UI. But on the other hand they might want to do it when (very borderline case) they have arrays for the conjuctive facet attribute...

Imho, for now let's now provide the option and consider it's for disjunctive facetting only.

What do you think? (no strong feelings :P)

**Comment by redox** [comment]
I think we should really not include a new wording here. All UI components I used were always speaking about "facet" (that's definitely not too technical). I'm OK to not expose the "conjunctive/disjunctive" words which are hard to understand but I would really not use "chooseMany".

**Comment by vvo** [comment]
> For me it makes more sense to separate conjunctive and disjunctive into two widgets. As it might not be the same template.

@maxiloc You will be able to pass a template to the widget of course.

**Comment by vvo** [comment]
> All UI components I used were always speaking about "facet"

Which one @redox. I am not against having `facetList` but everything is a facet (slider, switch) so I am not sure it makes more sense.

Also I am against `type: 'checkbox'` or link, radio. Because it will not answer all use cases. We can have checkboxes by default then provide a template option that will be able to solve all other use cases.

What do you think?

**Comment by vvo** [comment]
> So I propose to rename it to multipleChoiceList

This is a good name and I like it. Very descriptive, no question about the usage of the widget.

I am going to update the API Proposal (top description of this page) for this widget, please read it before replying.

**Comment by bobylito** [comment]
Ok for me!

**Comment by pixelastic** [comment]
As https://github.com/algolia/algoliasearch-helper-js/issues/178 seems to be done, I think we should order by isRefined/count/name instead of just name by default. Seems closer to the most common use case of such a widget.

**Comment by redox** [comment]
> Seems closer to the most common use case of such a widget.

When using checkboxes, I'm still very confused when I click and the lists is reordered putting the refined values on top. But it makes sense to have the ability to do it.

**Comment by redox** [comment]
> I think we should really not include a new wording here

And what about `refinementsList`? :boom:

**Comment by vvo** [comment]
> And what about refinementList?

Like :+1:

**Comment by vvo** [comment]
But what about menu, it's just a refinementList also, and facetList is a refinement list and a menu.

**Comment by redox** [comment]
I would merge all refinements widgets. It's really the same from a lot of POV.

I was a bit confused by the `menu` naming, which is actually a widget refining on one (and only one) value: if one value is selected and you click another value, it first unselects the first one.

Something like:
```js
// conjunctive faceting: 
instantsearch.widgets.refinementList({
  attribute: 'my_attr'
});

// disjunctive faceting:
instantsearch.widgets.refinementList({
  attribute: 'my_attr',
  conjunction: false
});

// menu (single value faceting):
instantsearch.widgets.refinementList({
  attribute: 'my_attr',
  conjunction: false,
  multiple: false // not super happy about that one, however
});
```

**Comment by vvo** [comment]
As discussed briefly, still not convinced merging both multipleChoiceList and menu (#49) in a single widget would help our user understand and build an instant search.

If I was to build the https://blog.algolia.com/ menu or the http://magento.algolia.com/catalogsearch/result/?q=__empty__ left menu then if I need to do this:

```js
instantsearch.widgets.menu({
  attribute: 'my_attr',
  conjunction: false,
  multiple: false // not super happy about that one, however
});
```

I would be confused.

If I can do this:

```js
instantsearch.widgets.menu({
  facetName: 'categories'
});
```

Then I would prefer using this API.

After using and implementing multipleChoiceList, I do agree that the name is not the most obvious but it's currently still our best option I find.

**Comment by redox** [comment]
I'm OK keeping the `menu`, so now it's just about "disjunctive" VS "conjunctive" in a single `refinementList` widget :/

**Comment by pixelastic** [comment]
I would split the disjunctive/conjunctive in two different widgets (at least on the public facing API, so the building blocks are easy to understand, even if the underlying private code is shared).

**Comment by vvo** [comment]
I would keep a single widget be it refinementList or multipleChoiceList and add this:

```js
instantsearch.widgets.refinementList({
  facetName: 'anAttribute',
  mode: 'AND', // or type: 'AND' or smg like that
});
```

**Comment by vvo** [comment]
I would not split because we struggle naming only one widget so two widgets should be hard. If we manage to find two good names then yes otherwise refinementList or multipleChoiceList is ok.

**Comment by redox** [comment]
`refinementList` :+1: 

What about `operator` instead of `mode`?

**Comment by vvo** [comment]
I am ok with refinementList mostly because it does give a better hint on the purpose of the widget (to refine, like any widget but explicitly for this one).

operator seems good too, now multipleChoiceList was found by @bobylito, what do you think!? Agree to move to refinementList?

**Comment by pixelastic** [comment]
> When using checkboxes, I'm still very confused when I click and the lists is reordered putting the refined values on top. But it makes sense to have the ability to do it.

Something like `reorderOnSelection`?

**Comment by redox** [comment]
> Something like reorderOnSelection?

Not sure how it must look like in the `instantsearch.js`; but the underlying code should either generate:

```js
sortBy: ['isRefined:desc', 'count:desc', 'name:asc']
```

or 

```js
sortBy: ['count:desc', 'name:asc']
```

**Comment by vvo** [comment]
in instantSearch.js we could just provide `sortBy` option in this widget for example..

**Comment by pixelastic** [comment]
Agreed for an overridable `sortBy` option in the widget
