### ISSUE TITLE
filter not being properly applied in federated search

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/instantsearch.js#4225]
**Describe the bug 🐛**
A facet filter is not applied to another index.

**To Reproduce 🔍**
1. Go to https://codesandbox.io/s/ais-ecommerce-demo-app-6hxt7
2. Click "blue" on the refinement list
3. Confirm there're non-blue items on `banners` index.

**Expected behavior 💭**
There should be only "blue" items.

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/499898/69816933-b76b1a80-11f9-11ea-89a7-0c3da7449e90.png)

**Environment:**
N/A

**Additional context**
```
ㄴ index `products`
    ㄴ index `products`
        ㄴ refinementList
        ㄴ hits
    ㄴ index `banners`
        ㄴ hits
```

When "blue" is refined, it should apply to all the indices.

**Comment by francoischalifour** [comment]
For `blue` to be applied to all indices, it needs to be at the top level. Only child indices receive the refinements, not scoped indices. This is therefore by design.

```ts
search.addWidgets([
  instantsearch.widgets.refinementList({
    container: '#color-list',
    attribute: 'color',
  }),
  instantsearch.widgets.index({ indexName: 'products' }).addWidgets([
    instantsearch.widgets.hits({
      container: '#hits-products',
      templates: {
        item: `
        <div>
          <div class="hit-name">
            {{#helpers.highlight}}{ "attribute": "name" }{{/helpers.highlight}} // {{color}}
          </div>
        </div>
      `,
      },
    }),
  ]),
  instantsearch.widgets.index({ indexName: 'banners' }).addWidgets([
    instantsearch.widgets.hits({
      container: '#hits-banners',
      templates: {
        item: `
        <div>
          <div class="hit-name">
            {{#helpers.highlight}}{ "attribute": "name" }{{/helpers.highlight}} // {{color}}
            </div>
          </div>
        </div>
      `,
      },
    }),
  ]),
]);
```

**Comment by eunjae-lee** [comment]
@francoischalifour Thanks for the comment.
I misunderstood it.
Closing the issue 👍
