### ISSUE TITLE
Add Ship.js as a release tool

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/instantsearch.js#4234]
**Purpose**
- A unified tool over all the InstantSearch repositories
- Less chore & less mistakes

**Description**
I've forked this repository and put changes there to simulate how it will look like on this repository.

1. Not to ruin anything accidentally, I've change the package name: https://github.com/eunjae-lee/instantsearch.js/commit/c5dd2d3069c6d5ae9caf133860e8137baed03a19
2. This commit adds Ship.js to the repository.  I've left comments to the commit: https://github.com/eunjae-lee/instantsearch.js/commit/2efc50e381f54f73dcb8d4cf963a635891cb3705
3. After that, I ran `yarn release:prepare` and it created this PR: https://github.com/eunjae-lee/instantsearch.js/pull/1
4. Assuming this repository is configured on CircleCI, merging the PR will trigger `yarn release:trigger` and it will publish it to NPM.

**Prerequisite**
Branching strategy still needs to be discussed.
Currently, InstantSearch.js uses `develop` and `master`.
The description above assumes we keep the strategy.
If we decide to change it to have only `master`, I will update this issue.

Please leave your feedback or any concern.

**Comment by francoischalifour** [comment]
That looks great! On my side I'm ready to try experimenting with Ship.js on this repo.

We can start without the weekly releases and opt-in whenever we feel like we need this strategy.

Note that all team members will need to follow the guide to add the right tokens.

**Comment by eunjae-lee** [comment]
To clarify that,
if we start without the weekly releases,
we're going to run `yarn release:prepare` on our local machine and it requires us to have a `.env` file with `GITHUB_TOKEN` in it.

(And we don't need `NPM_AUTH_TOKEN` on our local machine because it will be taken care of by CircleCI.)

I will give you all a simple guide again later when it's time.
