### ISSUE TITLE
menu/hierarchicalMenu: add a "All" entry

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#428]
We should add a showAll fake facet value.

![image](https://cloud.githubusercontent.com/assets/283419/10905503/f7fdd984-821a-11e5-9640-a919bb072a65.png)

This could be a `showAll` flag (along with `templates.showAll` and `labels.showAll`)

```javascript
search.addWidget(
  instantsearch.widgets.menu({
    container: '#menu',
    facetName: 'categories',
    showAll: true,
    labels: {
      showAll: 'All'
    },
    cssClasses: {
      showAll: 'show-all'
    },
    templates: {
      showAll: '...'
    }
  })
);
```

**Comment by redox** [comment]
:+1:

**Comment by vvo** [comment]
Would be nice yes, for hierachical widget also

**Comment by vvo** [comment]
This did not make it to 1.0.0 sadly and would require a breaking change OR hidden behind a feature-flag.

We do the feature flag @pixelastic?

**Comment by redox** [comment]
> This did not make it to 1.0.0 sadly and would require a breaking change OR hidden behind a feature-flag.

Let's default the `showAll` flag to `false` then :)

**Comment by pixelastic** [comment]
Yep, I think this should be a opt-in. I'll need that one for a demo in the coming weeks anyway.

**Comment by vvo** [comment]
doable in react-instantsearch, will be added in IS V2
