### ISSUE TITLE
[chooseOne] create widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#43]
This widget needs to be able to render this:

![2015-08-05-120454_484x325_scrot](https://cloud.githubusercontent.com/assets/123822/9083382/33a24b5c-3b6a-11e5-9036-828ccd043e74.png)

**Maybe not needed**, what this widget is here is a navigation menu, thus we should expose it as so: widgets.navigation, see #26**

## API

TODO, detail the initiailization API like we do in the readme for other widgets

**Comment by vvo** [comment]
The name of the widget is bad yes, any idea welcomed.

Also this widget can be implemented easily using hierarchical facet, because it's a hierarchical facet with only one level shown.

And you only have to hide what you do not want (what's not refined).

I wonder if we even need this widget or if it should be handled by #26.

**Comment by maxiloc** [comment]
Is that supposed to be handle by the conjunctive facet ? For me the only difference is the dataset

**Comment by vvo** [comment]
> Isn't that supposed to be handle by the conjunctive facet ?

Yes this is a conjuctive facet. The thing is that in instantsearch.js we want to talk about search UI and "conjuctive facet" is obscure, you need a good understanding of 1. conjuctive 2. facet

**Comment by maxiloc** [comment]
Ok so singleChoice is definitely bad :)

**Comment by vvo** [comment]
> Ok so singleChoice is definitely bad :)

Yes! Do you have any idea?

**Comment by vvo** [comment]
widgets.chooseOne, widgets.chooseMany?

**Comment by vvo** [comment]
Renamed to `chooseOne` for now

**Comment by vvo** [comment]
Ok So I am not at all convinced we need `chooseOne` what the users will need is #26 : widgets.navigation

**Comment by vvo** [comment]
what do you think?

**Comment by bobylito** [comment]
SingleChoiceList vs MultipleChoiceList

**Comment by redox** [comment]
Same feedback than https://github.com/algolia/instantsearch.js/issues/42#issuecomment-128098592

But also: I don't think we should separate "one" and "many" -> it's only a matter of data, it will "auto-magically" display 1 or several items.

**Comment by vvo** [comment]
Ok I have badly expressed this widget. I wanted to express a list where you can select only one item.

But this is exactly what a menu is. The "type" of the instant search demo (please look at the demo or screenshot in the description) IS a menu. Then we could either hide or show the values that are not selected.

I propose for this use case to expose the `widgets.menu`.

@redox We had a good chat with @bobylito about how to implement the "type" list fomr the instant seearch demo (see the screenshot or the demo). And what we do here is constructing a menu where you can select one of the item.

So I am closing this.
