### ISSUE TITLE
Widget proposal: numericRefinementList

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#430]
Following #295. Here a first draft of api proposal

# API

```
search.addWidget(
  instantsearch.widgets.numericRefinementList({
    container: '#refinement-date-selector',
    attributeName: 'age'
    options: [
      {name: 'All'},
      {end: 4, name: 'less than 4'},
      {start: 4, end: 4, name: '4'},
      {start: 5, end: 10, name: 'between 5 and 9'},
      {start: 11, name: 'more than 10'},
    ]
    // cssClasses: {root, header, body, footer, list, item, active, label, checkbox, count}
    // templates: {header, item, footer}
    // label: "Age"
    // hideContainerWhenNoRefinements: true
    // options.operator='or'
  })
);
```

The rendering would be the same as refinement list the thing that will change is how we handle the refiements

I did an example with age but this widget would be able to be use for date and handle things like:
 
![](https://cloud.githubusercontent.com/assets/976175/10609358/972d2a06-7743-11e5-94e8-0700731f7564.png)

**Comment by vvo** [comment]
That's nice!

**Comment by redox** [comment]
Go @maxiloc ! :+1: 

Only question I have is: do we do to use `numericAttributeName` or could we just go for `attributeName` (we already make it clear it's about numeric refinements)?

**Comment by redox** [comment]
I assume we can easily reuse the `RefinementList` component, and just create a new widget, right?

**Comment by maxiloc** [comment]
> could we just go for attributeName

Yes it's better
> I assume we can easily reuse the RefinementList component, and just create a new widget, right?

Yes I guess so

**Comment by vvo** [comment]
> I assume we can easily reuse the RefinementList component, and just create a new widget, right?

Yes also, as long as it's not modifying too much the refinement list component, should not since it's just about sending the right facetValues to it and the right refine function :)

**Comment by Shipow** [comment]
my hero
