### ISSUE TITLE
Remove the pass an array as cssClasses option?

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#432]
Seems we never needed it for now. We are not testing against it nor handling it I believe.

TODO:
- [ ] remove the cssClasses: ['string'] option from widgets, plain string is enough

Thoughts?

**Comment by redox** [comment]
> Thoughts?

I'm happy with both. Such minor change has actually a huge impact everywhere (doc, propTypes, code...) and since `cx(` is taking care of it, I would just keep it like it is.

**Comment by vvo** [comment]
> since cx( is taking care of it, I would just keep it like it is.

Yes indeed, we miss it in few places I will submit a PR

**Comment by redox** [comment]
> Yes indeed, we miss it (or wrongly configured) in few places, I will submit a PR

:+1:
