### ISSUE TITLE
Load instantsearch with hierarchicalFacetsRefinements

### ISSUE THREAD

**Issue by ergra** [algolia/instantsearch.js#4331]
Hello!

I am trying to initialize instantsearch with some pre checked filters. Basically I have a hierarchical menu with categories, and when the user visit for example /music/genre/rock i wanna make the "rock" value checked by default. I've tried this but with no luck: https://github.com/algolia/instantsearch.js/issues/830

My code looks like this:
```
var search = instantsearch({
	...
	searchParameters: {
		hierarchicalFacetsRefinements: {
			'music.genre': ['Rock']
		},
		facetingAfterDistinct: true,
		highlightPreTag: '__ais-highlight__',
		highlightPostTag: '__/ais-highlight__'
	}
});
```
and the hierarchical menu:
```
search.addWidget(
	instantsearch.widgets.hierarchicalMenu({
		container: '#genres',
		separator: ' > ',
		sortBy: ['count'],
		attributes: ['music_hierarchical.genre.lvl0', 'music_hierarchical.genre.lvl1', 'music_hierarchical.genre.lvl2'],
	})
);
```
Without this part everything works fine:
```
hierarchicalFacetsRefinements: {
	'music.genre': ['Rock']
},
```
But when I add that part I am getting:
**Cannot read property 'separator' of undefined at i._getHierarchicalFacetSeparator (instantsearch-preact.min.js?ver=1.2.0:4)**

Does anybody know what is going on here? Any help is very appreciated.

**Comment by Haroenv** [comment]
you also need to set `hierarchicalFacets` on the initialisation:

```js
var search = instantsearch({
  //	...
  searchParameters: {
    hierarchicalFacets: [
      {
        name: "music_hierarchical.genre.lvl0",
        attributes: [
          "music_hierarchical.genre.lvl0",
          "music_hierarchical.genre.lvl1",
          "music_hierarchical.genre.lvl2"
        ],
        separator: " > "
      }
    ],
    hierarchicalFacetsRefinements: {
      "music_hierarchical.genre.lvl0": ["Rock"]
    },
    facetingAfterDistinct: true,
    highlightPreTag: "__ais-highlight__",
    highlightPostTag: "__/ais-highlight__"
  }
});
```

Note also that the key of the refinement should be the same as the first level.

**Comment by ergra** [comment]
Amazing! Thank you so much for the quick reply. Works like a charm

**Comment by Haroenv** [comment]
Note that if you're using InstantSearch v4+ (you seem to be using v1, which is why I gave this solution), you can instead use `initialUiState` like this:

```js
const search = instantsearch({
  indexName: 'instant_search',
  searchClient,
  initialUiState: {
    instant_search: {
      hierarchicalMenu: {
        'hierarchicalCategories.lvl0': ['Appliances'],
      },
    },
  },
});
```

demo: https://codesandbox.io/s/eloquent-frost-inib5
