### ISSUE TITLE
Formatting rangeSlider pips with (prefix/suffix)

### ISSUE THREAD

**Issue by ergra** [algolia/instantsearch.js#4334]
Hey!

I'm trying to format the pips in my rangeSlider but cant get it to work.
I've looked a little bit at this https://github.com/algolia/instantsearch.js/issues/1436
But I am just getting "Function wNumb not definied", and i dont know what should be inside this function.

I've managed to format the tooltips like this:
```
tooltips: {
      format: function(rawValue) {
            return '$' . rawValue;
      }
},
```
However, If i am doing similar to the Pips, its not working. Any ideas on how i can do this?

**Comment by francoischalifour** [comment]
What do you mean by "formatting the pips"?

I prepared a [sandbox](https://codesandbox.io/s/instantsearchjs-3-playground-wofuc) where you can replicate what you currently have. Please send back the link so that we can work from here.

**Comment by ergra** [comment]
Yeap i was a little bit unclear. Thanks for the quick reply, take a look at this:
https://codesandbox.io/s/instantsearchjs-3-playground-60t34?fontsize=14&hidenavigation=1&theme=dark

As you can see i've added a dollar sign to the tooltips. I would like to do the same to the pips, i.e
I want:
$1 - $2500 - $5000
Under the slider

**Comment by francoischalifour** [comment]
You can check how we did it in the [E-commerce demo](https://instantsearchjs.netlify.com/examples/e-commerce/search/). Since there's no JavaScript API, you can use the [`::after` CSS property](https://github.com/algolia/instantsearch.js/blob/ece0aa60f05c2c687a23f9219d62ace0d5b866f9/examples/e-commerce/src/widgets/PriceSlider.css#L1-L6).

**Comment by lspoor** [comment]
Just following up on this, seems there is no need for CSS now as you can provide a function for tooltips. But there is still no way to control the format for the pips. Currently it just accepts a boolean to show/hide.
