### ISSUE TITLE
Type definitions for Typescript

### ISSUE THREAD

**Issue by Malthdk** [algolia/instantsearch.js#4340]
Hi! How far are you with type checking the project? Cause I am currently trying to integrate instantsearch for a project utilizing a typescript front-end framework and getting a lot of type errors when building the frontend.

**Comment by Haroenv** [comment]
Hi Malthdk,

You can try the `experimental-typescript` tag on npm, however there are still ±10 issues that prevent compilation, and ±200 warnings we haven't yet gotten to.

If the issues you're seeing are easy to fix  (usually from jsDoc), PRs are definitely welcome!
