### ISSUE TITLE
Marker clustering for geosearch

### ISSUE THREAD

**Issue by allyraza** [algolia/instantsearch.js#4346]
**Describe the bug 🐛**

We are currently using algolia for search feature in our product, we are currently in process of adding map search to our product, we have lot of documents would like to make use of marker clustering, but it seems inefficient as it would require us to query algolia for all the documents to render the markers with counts would like to know if it is possible to do with algolia without quering all the documents.

**To Reproduce 🔍**

A live example helps a lot!   We have a simple online template for you to use for your explanations:

https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js

**Expected behavior 💭**

**Screenshots 🖥**

**Environment:**
 - OS: [e.g. iOS / windows / mac / android]

**Additional context**

**Comment by francoischalifour** [comment]
InstantSearch's geo search implementation only loads the results within the provided bounds.

Here are more resources:

- [Example](https://instantsearchjs.netlify.com/examples/tourism/)
- [Example code](https://github.com/algolia/instantsearch.js/tree/b331cef9d8bc8683dd988daf40c5dc077f708548/examples/tourism)
- [Guide](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/geo-search/js/?language=javascript)
- [API reference](https://www.algolia.com/doc/api-reference/widgets/geo-search/js/)

**Comment by spindriftwebs** [comment]
Hi, 

We've implemented something similar here: https://www.secondhandboards.com/used-surfboards

It uses marker clustering, updates search based on refinements and uses Mapbox instead of Google maps.

**Comment by dharitmn** [comment]
> Hi,
> 
> We've implemented something similar here: https://www.secondhandboards.com/used-surfboards
> 
> It uses marker clustering, updates search based on refinements and uses Mapbox instead of Google maps.

Can you provide me github code link

**Comment by chazzaoui** [comment]
@spindriftwebs I am also curious as to how you have solved this codewise

**Comment by dhayab** [comment]
Closing this issue. As mentioned, results are queried from within the provided bounds, which should prioritize retrieving documents to be used in a chosen marker clustering implementation.
