### ISSUE TITLE
Custom widget : using facets as hierarchicalFacets

### ISSUE THREAD

**Issue by tdutreui** [algolia/instantsearch.js#4377]
**Describe the bug 🐛**
Calling addHierarchicalFacet() does nothing.

I noticed that using the "breadcrumb" widget, the targeted attribute is moved from the "facets" property to the "hierarchicalFacets" property.
I would like to implement the same behavior in my custom widget, but nothing seems to happen when using addHierarchicalFacet() :

**To Reproduce 🔍**
```
//in my custom widget implementation
init: function (initOptions) {
initOptions.helper.state.addHierarchicalFacet({
          name: 'filter_category.lvl0',
          attributes: [ "filter_category.lvl0", "filter_category.lvl1" ],
          separator: " > ",
          rootPath: null
        });
}
console.log(initOptions.helper.state.hierarchicalFacets) //empty

```
The last line here prints an empty Array.
Also, calling addHierarchicalFacet 2 times with the same name do not raise an error, but calling it 1 time after adding the "breadcrumb" widget does.

Could you explain me how to flag a facet as a hierarchicalFacet ?

Versions :
instantsearch.js@4.3.0
algoliasearch-helper@3.1.1:

**workaround**
I found a workaround, noticing the state was returned by the function :
```
initOptions.helper.state=initOptions.helper.state.addHierarchicalFacet({
          name: 'filter_category.lvl0',
          attributes: [ "filter_category.lvl0", "filter_category.lvl1" ],
          separator: " > ",
          rootPath: null
        });
```

**Comment by francoischalifour** [comment]
Algolia doesn't (yet) support the concept of "hierarchical facets". A hierarchical facet is a concept that exists at the Helper level. It adds the facet to the `facets` search parameter.

You should therefore be able to see your hierarchical facet attribute in `initOptions.helper.state.facets`.

**Comment by tdutreui** [comment]
Hi @francoischalifour 
Thank you for this answer.
I indeed notice it in `helper.state.facets`, but the issue is that it *disappears* from there when you mount the `breadcrumb` widget.
I need to avoid cross-widget dependency.

**Comment by francoischalifour** [comment]
Can you please reproduce the behavior in this [InstantSearch.js sandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js)?

**Comment by tdutreui** [comment]
@francoischalifour done, but unexpectedly I hit the following error on `breadcrumb` mount:
```
TypeError
B(...)[0] is undefined
```
This error do not prevent us to reproduce the bug : You just have to comment lines from 46 to 55 to see the console output change

**Comment by francoischalifour** [comment]
Sorry, I forgot to mention, can you send the link back here? (it created a forked sandbox)

**Comment by tdutreui** [comment]
here you go : https://codesandbox.io/s/gifted-khorana-l4rf8

**Comment by francoischalifour** [comment]
You can use an [`index` widget](https://www.algolia.com/doc/api-reference/widgets/index-widget/js/) so that the search parameters computed are independent from the `breadcrumb` widget.

I built an example [in this sandbox](https://codesandbox.io/s/focused-cherry-910no). I hope this helps!

**Comment by tdutreui** [comment]
@francoischalifour That would not resolve the problem, being that I want to implement a custom widget that can be applied to any search object through `addWidgets()`, regardless if they are already using the `breadcrumb` widget or not. For the moment I use the workaround stated in the description at the `init` step, is it the correct way to proceed?

**Comment by dhayab** [comment]
Hi! We're doing a round of clean up in this repository. Is this still an issue for you or does the workaround works well enough?

**Comment by tdutreui** [comment]
Hi !
I no longer work with Algolia, please close this issue if you wish to
