### ISSUE TITLE
onStateChange does not receive page update from infinite hits

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#4409]
## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/dark-river-27qdw?file=/src/app.js:229-242
2. Click on "show more"
4. See console.log onStateChange was called
5. see that page did not change

**Live reproduction:**

https://codesandbox.io/s/dark-river-27qdw?file=/src/app.js:229-242

## 💭 Expected behavior

page should change, like it does when you don't use `onStateChange`

## Environment

- Version: 4.4.0

**Comment by giojkd** [comment]
Cannot to make onStateChange at all

`
        const search = instantsearch({
            indexName: 'myindex',
            searchClient,
            initialUiState: {
                myindex: {
                    query: keyword,
                    refinementList:presetFacets,
                    toggle:{
                        is_on_sale: onlyOnSale
                    }
                },
            },
            onStateChange({ uiState, setUiState }) {
                console.log(uiState);
                setUiState(uiState);
            },
        });`

Any idea ?

**Comment by Haroenv** [comment]
can you open a new issue with reproduction in a sandbox please? I'm not sure what is meant to happen with just the InstantSearch constructor @giojkd

**Comment by logan-jobzmall** [comment]
This is still happening unfortunately.

**Comment by Haroenv** [comment]
@logan-jobzmall, do you have a reproduction? The original sandbox works as expected as far as I can tell
