### ISSUE TITLE
Creating a custom range facet with `connectRange` AND using routing fires an incorrect warning

### ISSUE THREAD

**Issue by yonguelink** [algolia/instantsearch.js#4437]
## 🐛 Bug description

Using any form of routing with a custom range facet created using `connectRange` will fire a warning about `range` needing either `rangeInput` or `rangeSlider`.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://g2vyw.csb.app/?instant_search%5Brange%5D%5Bprice%5D=22%3A321321
1. Open your console
1. See incorrect warning

**Live reproduction:**

https://codesandbox.io/s/objective-darwin-g2vyw?file=/src/app.js

## 💭 Expected behavior

No warning should be fired

## Environment

- OS: macOS
- Browser: Chrome 
- Version: 83
- `InstantSearch.js` Version 4.7.0

**Comment by yonguelink** [comment]
It seems to come from the fact that `connectRange` always set the `$$type` to `ais.range`.

https://github.com/algolia/instantsearch.js/blob/ada37ae054275d46cc2edaee0081562b6c35cbc8/src/connectors/range/connectRange.js#L74-L75

and `checkIndexUiState` assumes that a `range` can only have `ais.rangeInput` or `ais.rangeSlider` NOT `ais.range`

https://github.com/algolia/instantsearch.js/blob/ada37ae054275d46cc2edaee0081562b6c35cbc8/src/lib/utils/checkIndexUiState.ts#L57-L60

**Comment by yonguelink** [comment]
I've also tried the version with the virtual widget and the same warning is fired.

See the sandbox: https://codesandbox.io/s/modern-mountain-8ggjc?file=/src/app.js

or the live example: https://8ggjc.csb.app/?instant_search%5Brange%5D%5Bprice%5D=22%3A321321

**Comment by Haroenv** [comment]
Ah this is a great catch! in the widgets we provide the $$type directly, but `ais.range` should be accepted too https://github.com/algolia/instantsearch.js/blob/master/src/widgets/range-input/range-input.js#L170
