### ISSUE TITLE
Search Facet Filter value with . in name

### ISSUE THREAD

**Issue by sonalmahajan01** [algolia/instantsearch.js#4484]
## 🐛 Bug description

I have a facet filer for organization names in my index. It works perfectly fine for all values except those with '.' in their names. I have a name like 'Film.ua group'. I tried searching it in algolia facet search directly and it does not return the name. 

## 🔍 Bug reproduction

1. Add a facet filer names organization.name
2. Add a value with a . like "Film.ua group".
2. Go to the index page on algolia and click on the search icon besides the facet filer. Type the above name. No result is returned.

## 🖥 Screenshots

![Capture1Updated](https://user-images.githubusercontent.com/11632461/90711969-92ad5a80-e2d4-11ea-93a8-8f4c48282c23.png)
![Capture2Updated](https://user-images.githubusercontent.com/11632461/90712131-e91a9900-e2d4-11ea-9211-06b949c4e24e.png)
![Capture3](https://user-images.githubusercontent.com/11632461/90712137-eae45c80-e2d4-11ea-86af-b8e9d9e8590a.PNG)

**Comment by Haroenv** [comment]
While this isn't fixed, this isn't the best way to keep track of it, and can best be considered as a limitation of the search engine for now. You can always replace . with a different token that would not occur in your dataset, let's say `~`, and display that as `.` using transformItems.
