### ISSUE TITLE
How can I pass another hit attribute field into onchange not the selected value

### ISSUE THREAD

**Issue by mikebhart** [algolia/instantsearch.js#4485]
const autocomplete = instantsearch.connectors.connectAutocomplete(
  ({ indices, refine, widgetParams }, isFirstRendering) => {
    const { container, onSelectChange } = widgetParams;

    if (isFirstRendering) {
      container.html('<select id="ais-autocomplete"></select>');

      container.find('select').selectize({
        options: [],
        valueField: 'spell',
        labelField: 'spell',
        searchField: 'spell',

        highlight: false,
        onType: refine,
         onBlur() {
         refine(this.getValue());
        },
      
         score() {
            return function() {
             return 1;
           };
         },

         onChange(value) {

           //// *** here I want to get the value of a hit attribute field not value

           onSelectChange(value);
           refine(value);
         },
      });

      return;
    }

    const [select] = container.find('select');

    indices.forEach(index => {
      select.selectize.clearOptions();
      index.results.hits.forEach(h => select.selectize.addOption(h));
      select.selectize.refreshOptions(select.selectize.isOpen);
    });

  }
);

**Comment by francoischalifour** [comment]
Can you please replicate your example in this [InstantSearch.js sandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js) so we better understand what you're expecting?

**Comment by mikebhart** [comment]
Hi there what I'm trying to do is a simple select dropdown. 

I have list of website names they can choose from.  When the user selects one I want it do redirect to the website url. ( an attribute field)

Currently Im just getting the text value of the selected option. 

https://codesandbox.io/s/great-haze-mm88y

**Comment by mikebhart** [comment]
Anybody that wants the front end css styling code:-

input[type=checkbox] {
	position: relative;
	cursor: pointer;
}

input[type=checkbox]::before {
	position: absolute;
	top: 0;
	left: 0;
	display: block;
	width: 16px;
	height: 16px;
	border: 1px solid orange;
	background-color: blue;
	content: "";
}

input[type=checkbox]:checked::after {
	position: absolute;
	top: 1px;
	left: 6px;
	display: block;
	width: 5px;
	height: 10px;
	border: solid blue;
	border-width: 0 2px 2px 0;
	content: "";
	-webkit-transform: rotate(45deg);
	-ms-transform: rotate(45deg);
	transform: rotate(45deg);
}

**Comment by Haroenv** [comment]
This is actually a selectize question, not related to InstantSearch, but you can do it like this: https://codesandbox.io/s/funny-wildflower-x3u79?file=/src/app.js

You have to read `selectize.options[value]` to get to the "raw" option, which has the URL

(edited your sandbox to actually work, you forgot some jquery parts)

relevant selectize option: https://github.com/selectize/selectize.js/issues/699
