### ISSUE TITLE
Rendering special characters in templating

### ISSUE THREAD

**Issue by drano** [algolia/instantsearch.js#4501]
## 🐛 Bug description

Entities characters (ie: &amp;), provided by search results, are not displayed correctly when using templating in instantsearch.js (v4.7.1) and using { "attribute" : "text" } syntax

**Comment by francoischalifour** [comment]
Can you please replicate the behavior in this [InstantSearch.js sandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js)?

**Comment by Haroenv** [comment]
I tried to reproduce it, but couldn't: https://codesandbox.io/s/amazing-dhawan-f6rv9?file=/src/app.js. Before v4 we used to have an issue where escapeHTML was called multiple times, but I don't think that's possible here, so yes @drano, could you show how and when this happens?

**Comment by drano** [comment]
By example, I've received from algolia this text "Something  &amp; Something", and "&amp;" is displayed directly in html

**Comment by Haroenv** [comment]
do you mean you have html entities in your records? Could you send a screenshot of the record in question on the algolia dashboard @drano?

**Comment by drano** [comment]
I cannot show you a screenshot. But yes, I can see  "Something & Something" on algolia dashboard

**Comment by drano** [comment]
And I confirm that Algolia rest api returns the &amp;amp; character

**Comment by Haroenv** [comment]
could you show this in an example? I can't reproduce this unfortunately? You can create a new free application to show it :)

**Comment by Haroenv** [comment]
Could not reproduce this unfortunately. If the Algolia engine returned `&amp;`, that normally means the records also contained `&amp;`, which as expected will show as the literal text `&amp;` in the InstantSearch frontend (unless escapeHTML is false, which is not recommended)
