### ISSUE TITLE
Searching for facet can throw an error when a refinement list is expanded with more than 100 items.

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/instantsearch.js#4521]
## 🐛 Bug description

Searching for facet can throw an error when a refinement list is expanded with more than 100 items.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/admiring-haslett-ipfw1?file=/src/app.js
2. Click on "Show more" button on the refinement list
3. Type any key on the facet search bar

## The problematic configuration

```js
  instantsearch.widgets.refinementList({
    container: '#brand-list',
    attribute: 'brand',
    searchable: true,
    limit: 10,
    showMore: true,
    showMoreLimit: 1000,
  }),
```

## 💭 Expected behavior

We should be able to search. Although we have `showMoreLimit: 1000`, facet search shouldn't use `1000` as is. We should cap it (probably to 100?).

## 🖥 Screenshots

![image](https://user-images.githubusercontent.com/499898/93888367-3630c700-fce8-11ea-9023-c18fe8b7fc9f.png)

## Environment

- OS: macOS 10.15.6
- Browser: FireFox
- Version: 80.0.1

**Comment by Haroenv** [comment]
I think capping to 100 makes most sense, since the API otherwise returns with an error
