### ISSUE TITLE
ParseURL not called on every back or forward button click

### ISSUE THREAD

**Issue by AlexandreSi** [algolia/instantsearch.js#4528]
## 🐛 Bug description

parseURL is not called on every back or forward button click.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/algolia-bad-behaviour-b5ed6
2. Select HP
3. Select Samsung
4. Hit Back button
5. Hit Forward button
6. See in the console that parseURL is not called at each back or forward button blick

**Live reproduction:**

In this sandbox, the url path is mapped to selected brands through parseURL, createURL, stateToRoute and routeToState.

https://codesandbox.io/s/algolia-bad-behaviour-b5ed6

## 💭 Expected behavior

I was expecting, as described in your documentation, that parseURL is called on every back or forward button click.

## Environment

- OS: Linux, MacOS Windows
- Browser: Chrome, Safari at least
- Version: latest

## Additional context

Originally thought it was a problem of interactions with turbolinks (#2998).

**Comment by AlexandreSi** [comment]
I may have found something:

https://github.com/algolia/instantsearch.js/blob/9296022fecadfbf82f15e837c215a1356eac4bc5/src/lib/routers/history.ts#L153

The callback `onPopState` uses `event.state` to know if it should read the URL or not.

The thing is I don't know where `state` comes from but in my case, hitting back button to a previous search gives `routeState = {}`, that is a truthy value but I am not sure that it is the behaviour we should expect from it?

**Comment by AlexandreSi** [comment]
Well, I figured out that our `createURL` function was deleting items of `routeState` after supposedly copying the object into another one, storing in history an incomplete `routeState`.

Sorry for the inconvenience and I hope that it will be useful to someone else in the future: don't touch `routeState` in places you shouldn't be.

**Comment by Haroenv** [comment]
No worries, glad you found this on your own!
