### ISSUE TITLE
InfiniteHits cache cannot get invalidated

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/instantsearch.js#4531]
## 🐛 Bug description

We have `cache` object passed to InfiniteHits, but we store the hits in `cachedHits`. So `cachedHits` becomes the second layer of cache, which cannot be invalidated. InfiniteHits always should reflect the status of `cache`.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/compassionate-goldberg-bmltl?file=/src/app.js
2. Click on "Clear Cache" button
3. The hits are not refreshed.

## 💭 Expected behavior

We should either get rid of `cachedHits` or make it up-to-date with `cache`.

## Environment

- OS: macOS 10.15.7
- Browser: FireFox
- Version: 81.0.1 (64-bit)

**Comment by Haroenv** [comment]
I think the way to go is to get rid of cachedHits (but maybe only when `cache` is given, otherwise the default experience might fail?)

**Comment by eunjae-lee** [comment]
> I think the way to go is to get rid of cachedHits (but maybe only when `cache` is given, otherwise the default experience might fail?)

`cache` is always given (`getInMemoryCache()` by default), so it should be okay.
