### ISSUE TITLE
hierarchical menu is not returning sub level data

### ISSUE THREAD

**Issue by jonadeline** [algolia/instantsearch.js#4543]
## 🐛 Bug description

I'm implementing a custom hierarchical menu with Svelte  leveraging the connectHierarchicalMenu connector.
I'm able to display the first level of the menu but not the second when I click on a first level entry. 
At init, I'm getting the following error :

```
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at Object.render (connectHierarchicalMenu.js:182)
    at index.js:372
    at Array.forEach (<anonymous>)
    at Object.render (index.js:364)
    at InstantSearch.js:105
    at defer.js:24
```

And when I'm console.log the items returned by Algolia, the data property is always null whereas I guess it should be filled with the information of the sub level if relevant. 
Here is a console.log exemple below after clicking on Vegetables (root level entry). I assume that data should be filled with the sub level information. 

```
0: {count: 11, isRefined: false, exhaustive: true, data: null, label: "Baby Food", …}
1: {count: 2, isRefined: false, exhaustive: true, data: null, label: "Bakery", …}
2: {count: 21, isRefined: false, exhaustive: true, data: null, label: "Beverages", …}
3: {count: 74, isRefined: false, exhaustive: true, data: null, label: "Eggs & Dairy", …}
4: {count: 69, isRefined: false, exhaustive: true, data: null, label: "Fruits", …}
5: {count: 7, isRefined: false, exhaustive: true, data: null, label: "Meat & Fish", …}
6: {count: 117, isRefined: false, exhaustive: true, data: null, label: "Pantry", …}
7: {count: 137, isRefined: true, exhaustive: true, data: null, label: "Vegetables", …}
``` 

## Additional context

Here is my component code 

```
//hierarchical-menu.svelte

<script>
  import { connectHierarchicalMenu } from "instantsearch.js/es/connectors";
  import HierarchicalList from "./hierarchical-list.svelte";
  import { onMount } from "svelte";

  let items = [];
  let isShowingMore;
  let refine;
  let toggleShowMore;
  let createURL;
  let widgetParams;
  let containerEl;

  const renderHierarchicalMenu = (renderOptions, isFirstRender) => {
    items = renderOptions.items;
    isShowingMore = renderOptions.isShowingMore;
    refine = renderOptions.refine;
    toggleShowMore = renderOptions.toggleShowMore;
    createURL = renderOptions.createURL;
    widgetParams = renderOptions.widgetParams;

    console.log(items);
  };

  const algoliaHierarchicalMenu = connectHierarchicalMenu(
    renderHierarchicalMenu
  );

  onMount(async () => {
    const algoliaModule = await import("../../modules/algolia");
    const { algoliaSearch } = algoliaModule;
    algoliaSearch.addWidgets([
      algoliaHierarchicalMenu({
        container: containerEl,
        attributes: [
          "hierarchical_categories_en.lvl0",
          "hierarchical_categories_en.lvl1",
        ],
      }),
    ]);
  });
</script>

<div bind:this={containerEl}>
  <HierarchicalList {items} {createURL} {refine} />
</div>
``` 

```
//hierarchical-list.svelte

<script>
  export let items = [];
  export let refine;
  export let createURL;

  const handleClick = (event) => {
    refine(event.target.dataset.value);
  };
</script>

<ul>
  {#each items as item}
    <li>
      <a
        href={createURL(item.value)}
        on:click={handleClick}
        data-value={item.value}
        class:font-medium={item.isRefined}>
        {item.label} ({item.count})
      </a>
      {#if item.data}
        <div class="pl-2">
          <svelte:self items={item.data} {createURL} {refine} />
        </div>
      {/if}
    </li>
  {/each}
</ul>
```

And here is how are stored the hierarchical categories on Algolia : 
```
{
  "hierarchical_categories_en": {
    "lvl0": "Vegetables",
    "lvl1": "Vegetables > Mediterranean"
  }
}
```
 I also activated the facets  in the dashboard. 

I'm using instantsearch v4.7.2

**Comment by Haroenv** [comment]
Hey! could you make this in a sandbox, I think this might possibly be related to how you are mounting the widget. There's a svelte starter here: https://codesandbox.io/s/svelte-forked-enk4e?file=/App.svelte

**Comment by Haroenv** [comment]
However note that the sub-level will only be filled once the item is refined, since we can not fetch _all possible_ facets on every query, only those relevant to this current query, otherwise this would need exponentially more requests

**Comment by jonadeline** [comment]
hi @Haroenv,
Thanks for your quick feedback.
After further testing, it happens that some times it works (but most of the time its not) but Im not to figure out why. 
And yes I notice that the sub-level should be filled once a first level value is refined.

Also I forget to mention that Im using the onMount svelte hook cause I'm in a SSR environment with Sapper and as instantsearch is not supporting SSR, I have to import it only on the frontend side which is done by the onMount. 

I come back to you with a sandbox ;) Thanks again.

**Comment by jonadeline** [comment]
Here is the sandbox @Haroenv : 
https://codesandbox.io/s/svelte-forked-13ymr

**Comment by jonadeline** [comment]
I get ride of the JS error I mentioned by delaying the initialisation of Algolia Search. 
But still struggling to get sub-level data 🤔 and I cannot reproduce in the sandbox 😭

**Comment by Haroenv** [comment]
I was just going to suggest calling start after the widget has been mounted. Something seems to go wrong tick-wise with this set of tools together where you add a hierarchical widget and it seems like the `render` is called before the widget is added / before the result of its call is in. It can be solved by doing:

```
setTimeout(() => {
  search.start();
}, 0);
```

Note also you need to `preventDefault` the click on the event: https://codesandbox.io/s/svelte-forked-5e9d3?file=/hierarchical-list.svelte

**Comment by jonadeline** [comment]
Ok finally figured out the problem.
It's because I have on the same view a menu widget (the single level one) using the same attribute (hierarchical_categories_en.lvl0) than the hierarchical menu. 
Is that a bug or is it my UX implementation that shouldn't exist having those 2 widgets in parallel  😅 ?

**Comment by Haroenv** [comment]
ah yes unfortunately using both in the same view will cause an error if they have a different value, since they use the same parameter (we have an open issue somewhere to throw an error when an attribute is used more than once, but it used to be hard to throw, I think it might be possible now)

**Comment by jonadeline** [comment]
Ok I see. I close the issue.
Thanks for the quick support @Haroenv. 🤙

**Comment by Haroenv** [comment]
Excited to see your svelte InstantSearch, don't hesitate to share on https://discourse.algolia.com once you're done!
