### ISSUE TITLE
instantsearch.routers is undefined 

### ISSUE THREAD

**Issue by jonadeline** [algolia/instantsearch.js#4545]
## 🐛 Bug description

I wanted to play with Algolia routing but I'm getting an error when calling `instantsearch.routers.history()`

```
algolia.js:13 Uncaught (in promise) TypeError: Cannot read property 'history' of undefined
    at algolia.js:13
```

**Live reproduction:**

https://codesandbox.io/s/svelte-forked-13ymr

**Comment by Haroenv** [comment]
In the esm build, there's no properties added to InstantSearch itself, router should be imported like this: 

```js
import { history } from "instantsearch.js/es/lib/routers";
```

https://codesandbox.io/s/svelte-forked-c8q96
