### ISSUE TITLE
Feature Request: Connector for Algolia Places widget

### ISSUE THREAD

**Issue by yesezra** [algolia/instantsearch.js#4589]
Hello! I'm hoping to customize the Algolia Places widget in my instantsearch.js project. (I need to add some behavior when a location is first set, and when the widget is cleared.) I've been able to customize other widgets (such as hits and refinementlist) using a connector, but no connector class exists for Places and it looks like I'll need to create a custom widget.

Apologies if this is the incorrect place to post a feature request; I was directed here by the note on [this page](https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/js/#introduction).

**Comment by francoischalifour** [comment]
Hey @yesezra—we don't plan to create a Places connector. I recommend creating your own Places widget based on [the one that we provide](https://github.com/algolia/instantsearch.js/blob/dd0ad2ca8f7db5017c90f05dc1cd22bc1f3dcab4/src/widgets/places/places.ts).

You can copy/paste it (minus the TypeScript specifics), you'll have access to the `init` and `dispose` lifecycle methods.

Closing this but feel free to reopen if you need further guidance.
