### ISSUE TITLE
InstantSearch.js slows down the site

### ISSUE THREAD

**Issue by blogi-kriptovalyut** [algolia/instantsearch.js#4641]
Hello.

i use [minimal-mistakes](https://github.com/mmistakes/minimal-mistakes) jekyll theme.

InstantSearch.js loads 20 (!) images for quick search. But it slows down lighthouse and google core web vitals.
Can this feature be removed or configured so that images are requested only at the moment of clicking on the search?

Or maybe there is an opportunity to tell him to load not 20, but 5 images?

source: https://github.com/mmistakes/minimal-mistakes/blob/d6444412c63aea5e47241ef536509fb1bfef4830/_includes/search/algolia-search-scripts.html

my blog page: [https://bitkoinblog.ru/novye-kriptovalyuty/dogecoin/](https://bitkoinblog.ru/novye-kriptovalyuty/dogecoin/)

<a href="https://ibb.co/r5q3Lcg"><img src="https://i.ibb.co/TPJ1nbZ/img-2021-01-29-19-50-37.png" alt="img-2021-01-29-19-50-37" border="0"></a>

> The ideal solution would be to defer the load of InstantSearch until the moment the user clicks on the search.
Or postpone rendering of images until the window.onload event is fully fired.
It might be possible to do just loading-lazy, but Lazy-load plugin does not take images from InstantSearch, so they are loaded on the main thread anyway.

However, 90% of my users will never click on search. So yes, I think we need to think of something.

**Comment by Haroenv** [comment]
if you want less images to load, you can use `configure({ hitsPerPage: 5 })` to show only five hits, is that what you want? 

Otherwise if you're looking for lazy-loading, InstantSearch isn't opinionated around that, there's many solutions that exist for it that, even one builtin to the browser now (loading=lazy on the image) https://web.dev/browser-level-image-lazy-loading/

**Comment by blogi-kriptovalyut** [comment]
> if you want less images to load, you can use `configure({ hitsPerPage: 5 })` to show only five hits, is that what you want?
> 
> Otherwise if you're looking for lazy-loading, InstantSearch isn't opinionated around that, there's many solutions that exist for it that, even one builtin to the browser now (loading=lazy on the image) https://web.dev/browser-level-image-lazy-loading/

I don’t understand in which file you need to register this?
`loading=lazy` doesn't work in my case because the plugin does not substitute lazy value for js content.

The ideal solution would be to defer the load of InstantSearch  **until the moment the user clicks on the search**.

**Comment by Haroenv** [comment]
if you wait to call `search.start()` until the user shows intent to search, it will not do any requests early, is that what you're looking for?

**Comment by blogi-kriptovalyut** [comment]
> if you wait to call `search.start()` until the user shows intent to search, it will not do any requests early, is that what you're looking for?

Yes, how can I use this with [minimal-mistakes](https://github.com/mmistakes/minimal-mistakes) jekyll theme?

**Comment by Haroenv** [comment]
I don't know, can you not change the JavaScript code?

**Comment by blogi-kriptovalyut** [comment]
> I don't know, can you not change the JavaScript code?

I can, 
I see an inline script on the page, do I need to add something here?
```
<script>
--
// Instanciating InstantSearch.js with Algolia credentials
const search = instantsearch({
appId: 'myid',
apiKey: 'mykey',
indexName: 'myindex',
searchParameters: {
restrictSearchableAttributes: [
'title',
'content'
]
}
});
 
const hitTemplate = function(hit) {
const url = hit.url;
const title = hit._highlightResult.title.value;
const content = hit._highlightResult.html.value;
 
return `
<div class="list__item">
<article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
<h2 class="archive__item-title" itemprop="headline"><a href="${url}">${title}</a></h2>
<div class="archive__item-excerpt" itemprop="description">${content}</div>
</article>
</div>
`;
}
 
// Adding searchbar and results widgets
search.addWidget(
instantsearch.widgets.searchBox({
container: '.search-searchbar',
poweredBy: true,
placeholder: 'Введите поисковый запрос...'
})
);
search.addWidget(
instantsearch.widgets.hits({
container: '.search-hits',
templates: {
item: hitTemplate
}
})
);
 
// Starting the search
search.start();
</script>
```

**Comment by Haroenv** [comment]
in that code you have `search.start` at the end, which can be done at a different time

**Comment by blogi-kriptovalyut** [comment]
> in that code you have `search.start` at the end, which can be done at a different time

and what needs to be written to postpone the appearance of the search?

**Comment by Haroenv** [comment]
you put `myButtonThatTriggersTheSearch.addEventListener('click', () => search.start())` (or whatever other condition)
