### ISSUE TITLE
InfiniteHits doesn't disable "Show more" button when it loaded the whole hits from the sessionStorage cache.

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/instantsearch.js#4643]
## 🐛 Bug description

After the whole hits to the last page have been loaded in InfiniteHits and are stored in sessionStorage cache, when reload the page, it successfully load the hits from the cache, but fail to disable "Show more" button.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/autumn-butterfly-5jlzc?file=/src/app.js
2. Search for any query that gives small amounts of hits (for easy reproduction, eg. "non existing")
3. Scroll down to the bottom and click show more until you reach to the end.
4. Remove the `page` query parameter from the URL and reload the page.
5. You see all the hits are successfully rendered from the cache.
6. However "Show more" button is still enabled, and if you click it, it tries to load non-existing page.

**Live reproduction:**

https://codesandbox.io/s/autumn-butterfly-5jlzc?file=/src/app.js

## 💭 Expected behavior

"Show more" button is supposed to be disabled.

## 🖥 Screenshots

https://user-images.githubusercontent.com/499898/107229357-03306b00-6a1e-11eb-97ee-2fa501e3ec9a.mp4

## Environment

- OS: macOS 10.15.7
- Browser: FireFox 85.0

## Additional context
This issue came in from HelpScout.
Once this is fixed, we should apply the update in the Magento extension.
Then, search for "https://github.com/algolia/instantsearch.js/issues/4643" in HS, and reply to them about the fix.

**Comment by Haroenv** [comment]
the part that's wrong must be related to these parts of the code:

https://github.com/algolia/instantsearch.js/blob/dd033fc58ff11027e4f4b6157aedf0aea0326af3/src/connectors/infinite-hits/connectInfiniteHits.ts#L303

https://github.com/algolia/instantsearch.js/blob/dd033fc58ff11027e4f4b6157aedf0aea0326af3/src/connectors/infinite-hits/connectInfiniteHits.ts#L178-L189

I'm not seeing what's wrong with it thogh

**Comment by eunjae-lee** [comment]
Yeah that must be the part, but I need to reproduce it with debugger to see what's really going on.

**Comment by eunjae-lee** [comment]
I just confirmed this has been fixed since 4.8.1 by https://github.com/algolia/instantsearch.js/pull/4509

**Comment by Haroenv** [comment]
the sandbox in the issue topic is using 4.8.1 though @eunjae-lee, are you sure it's fixed?

**Comment by eunjae-lee** [comment]
> the sandbox in the issue topic is using 4.8.1 though @eunjae-lee, are you sure it's fixed?

ah, initially the version in the issue topic was 4.7.1. I forgot to fork it before trying to change it. I just put it back.

* 4.7.1 (bug) -> https://5jlzc.csb.app/
* 4.8.1 (fixed) -> https://0gfp4.csb.app/
