### ISSUE TITLE
SSR fails due to call of window.encodeURI in numeric menu component

### ISSUE THREAD

**Issue by reinoldus** [algolia/instantsearch.js#4650]
## 🐛 Bug description

The following call to window from https://github.com/algolia/instantsearch.js/blob/ccf159efcb94e9c8c04c558fcb69e2e3d8d79729/src/connectors/numeric-menu/connectNumericMenu.ts

    const prepareItems = (state: SearchParameters) =>
      items.map(({ start, end, label }) => ({
        label,
        value: (window as any).encodeURI(JSON.stringify({ start, end })),
        isRefined: isRefined(state, attribute, { start, end, label }),
      }));

causes SSR to fail when using the numeric menu

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

This live example is for vue-instantsearch which I am using, but I assume it happens for all flavors.

https://codesandbox.io/s/goofy-northcutt-kttko?file=/pages/search.vue

## 💭 Expected behavior

No call to window

## Environment
I assume all

**Comment by Haroenv** [comment]
looks like if we leave out the `window.` it should work in node too, since it's also a global

**Comment by reinoldus** [comment]
Thank you for taking care of it so quickly!

Will this be released with scheduled released on Tuesday or is there any chance to get it out earlier?

**Comment by Haroenv** [comment]
Most of us are off tomorrow and we prefer not to have weekend releases, it'll be next Tuesday or Monday!

**Comment by eunjae-lee** [comment]
@reinoldus it's just released in 4.14.1 :)
