### ISSUE TITLE
Grouping widgets in a Panel

### ISSUE THREAD

**Issue by FraukeVdz** [algolia/instantsearch.js#4666]
I would like to group different ToggleRefinement Widgets in 1 panel, so they have 1 header and the header isn't shown when all the toffleRefinement counts are 0.

**Comment by Haroenv** [comment]
At the moment we don't have this feature as part of the panel widget unfortunately, and panel is a quite complex widget, so I'm not sure what way it could wrap multiple widgets. The DOM wouldn't be exactly what you want, but could you have a header only for the first widget, but use the same condition to hide the widgets?

**Comment by FraukeVdz** [comment]
I don't think that would work.
In my DOM I have a header and a container. Together it forms an accordion. So clicking on the header would open or close the accordeon.

In my JS, I have a loop that creates toggleRefinment Widgets and adds it to the container only when the count is > 0.
But in order not to show an empty accordion I would have to check if all toggleRefinment Widgets have a count that equals 0.
But I don't know how I can do this.

**Comment by Haroenv** [comment]
I think this should follow your use case: https://codesandbox.io/s/amazing-ganguly-69jxx?file=/src/app.js

1. loop to add all widgets
2. conditionally do css in a custom widget's `render` function

```js
const toggles = [
  { attribute: 'brand', value: 'Apple' },
  { attribute: 'brand', value: 'Samsung' },
  { attribute: 'brand', value: 'Samsung' },
  { attribute: 'brand', value: 'Samsung' },
];

function superPanel({ container, values }) {
  const containerNode = document.querySelector(container);
  return [
    ...values.map(({ attribute, value }) => {
      const toggleContainer = document.createElement('div');
      containerNode.appendChild(toggleContainer);

      return instantsearch.widgets.toggleRefinement({
        container: toggleContainer,
        attribute,
        templates: {
          labelText: `${value} {{count}}`,
        },
        on: value,
      });
    }),
    {
      init() {},
      render({ results }) {
        const facetValues = values.map(({ attribute, value }) => {
          const allValues = results.getFacetValues(attribute);
          return allValues.find(({ name }) => name === value) || {};
        });

        const shouldShow = facetValues.some(({ count }) => count > 0);

        containerNode.style.opacity = shouldShow ? 1 : 0.5;
        // alternative style:
        // containerNode.hidden = !shouldShow;
      },
    },
  ];
}

search.addWidgets(...superPanel({container: ".search-panel__filters", values}))
```

**Comment by FraukeVdz** [comment]
Thanks for the quick response.
I'll try it out and let you know how I go ;-)

**Comment by FraukeVdz** [comment]
Worked like a charm.
Thank you very much, you are a life saver :smile:
