### ISSUE TITLE
Handle paste events in searchBox

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#467]
As detected by @dustincoates in instant search demo, we should also handle paste events in instantsearch.js in our searchBox.

Right now if you copy paste with the mouse in the searchBox then it will not trigger a search.

@dustincoates If you want to take this one, feel free!

**Comment by maxiloc** [comment]
Not sure to understand this one, you mean copy pasting ?

**Comment by vvo** [comment]
> Not sure to understand this one, you mean copy pasting ?

Yes added a sentence in description: "Right now if you copy paste with the mouse in the searchBox then it will not trigger a search."

**Comment by maxiloc** [comment]
ok I am on it
