### ISSUE TITLE
Change `cssClasses` jsdoc from `{string|string[]}` to `{string}`

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#468]
The jsdoc usage of our widgets on the accepted types of `cssClasses` is inconsistent. We sometimes use `{string|string[]}` and sometimes `{string}`.

We have absolutly no tests that ensure that the array syntax works and we did not even used it once in our demos. I suggest we update all the jsdocs to only use `{string}`

**Comment by vvo** [comment]
> We have absolutly no tests that ensure that the array syntax works and we did not even used it once in our demos. I suggest we update all the jsdocs to only use {string}

@pixelastic Careful we did discuss this in another issue and found out that it would be a lot of work to update everything. https://github.com/algolia/instantsearch.js/issues/432

Let's not do this right now, there's no real need to do so?

**Comment by pixelastic** [comment]
Sorry, I missed this issue. I'm two days late on my GitHub notifications and a lot happened!

Closing this one
