### ISSUE TITLE
Implement CSS BEM in instantsearch.js

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#47]
## Goals

- To allow easy customisation of our elements
- While following a convention that was made for components/widgets/blocks

What do you think?

**Comment by seafoox** [comment]
Sounds like a good idea to normalize the way we write our different projects. Maybe it could be interesting to also evaluate alternatives to BEM. 
Whatever the metho, I think we should also use the same rule for our website, and eventually the demo we build (but BEM might be too complexe at some point for people to read the code)

**Comment by vvo** [comment]
Yes @seafoox. For now we will only implement it in instantsearch.js and then when building demos you will have to overwrite some of them.

**Comment by pixelastic** [comment]
Regarding BEM, [this article](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/) was an eye opener for me. 

This goes a step further than BEM but more importantly explains why BEM is designed this way and suggest a naming convention for common components, modifier classes, layout classes and so on.

In a nutshell, they suggest adding a one-letter prefix to our BEM classes, to explain what this kind of class this is. The more important prefixes are:

- `c-` for a component, like a piece of UI. Modifications in those classes should not leak to other components.
- `o-` for a (meta) object which is more an abstraction of a concept, shared accross several components. Change in those classes will have important impact in different parts. Dangerous.
- `u-` for utility classes. Theses can be easily added to the HTML markup to slightly change a display, and can be used in any components. This include classes like `u-disabled` or `u-clearfix` for example.
- `t-` is for theming. Those are purely cosmetic changes. Ideally, you can remove all `t-` classes and still have a usable component. Changing the `t-` classes will result in a new look'n'feel but to do alter behavior.
- `is-` and `has-` are here to signify a state of a current piece of ui. Something like `has-results`, `is-loading`.
- `_` is for hacks. Anything prefixed with this is to avoid a brower bug, or do something ugly. We might do this kind of hack, but better mark them as such.
- `js-` is for marking DOM-element for JavaScript. It is not used in any CSS file, it is just here to provide an easy selector for JS bindings.


I'm not saying we should use those prefixes as-is, but those are important separation we need to keep in mind to:

- Share common classes accross several widgets
- Use specific styling for specific widgets that do not leak into the global css namespace and collide with user-defined styles
- Separate styling (css) from behavior (js)
- Allow users to customise the appearance without breaking the behavior

**Comment by pixelastic** [comment]
We discussed it a bit with @vvo, and here what came out (not final):

- Each widget should have a default template that does the very minimal markup for the behavior, but no specific styling
- Each widget should let the user define its own template so they have complete power on how to render/style it if they want to go deeper

We should also aim to provide widgets that looks good out-of-the-box. For that, I suggest each default template should, at least, provide a `t-` class on the top wrapper element (for theming). We will provide a `theme.css` file along with our widgets that users can include to have the same look'n'feel than on the instant search.

Users that want to simply tweak the display can use this file as a base for their rewrite, while more advanced users can simply change the template.

WDYT?

**Comment by redox** [comment]
LGTM @pixelastic  :+1:

**Comment by vvo** [comment]
Just to clarify a bit more what @pixelastic said. I don't think the instantsearch.js module should style components (meaning manipulating the style of widgets).

Why? Because it's always a fail and people will want to either remove all style, provide templates following other methodologies (like bootstrap). Thus if the JS is doing some style by default then it will be hard to overwrite it/provide a good API for it.

We rather go the jqueryUI way (or any UI library) by having some methodologies for class names (BEM) and providing a way to load stylesheets (but no default stylesheet will be loaded).

It will either load it via JS or the user will have to put it in a <link rel... JS loading seems the most easiest way right now.

Also I have set it to milestone "1.0.0" because for now, to build the 0.0.1 (instant search demo), we do not need that much and we are not sure how much of CSS intelligence we need until we have the complete demo/start to implement the might magento extension.

**Comment by pixelastic** [comment]
I've moved this issue to 0.5.0 (Magento + Shopify). I'll have a go at it on the instantsearch demo

**Comment by pixelastic** [comment]
I plan to start on this one soon, one widget at a time to iterate on it. But here are the main points that I'm seeing:

## 1. Basic template and rendering

All our widgets should have sensible defaults in term of template and rendering so we understand how they work. This can be hiding unused links in pagination, or displaying our logo with the correct margin in the poweredBy or setting the currently selected facets in bold.

I see this part as embedded CSS using the weird `require('style?prepend!raw!./index.css');` syntax. All the elements we need to style will have a unique class (following the BEM model), so we can do a simple `.ais-{block}__{element}--{modifier}` selector in our CSS file to style them.

## 2. Adding custom classes to element

Users will want to override our styles with their own, or some they already have from popular libraries like Bootstrap. We should let them add a `form-control` class to an `input` if they want to.

For that, we will expose a `cssClasses` object on every object where user can define the CSS classes they want to add to the markup we generate.

## 3. Styling each element indiviually

For people that do not like big fat frameworks like Bootstrap that adds classes everywhere and would like more granularity on what is styled, we need a way to individually target any piece of markup we add. Fortunatly, we already kind of did that in __1__. 

We'll just continue adding BEM classes to the markup we generate, even if we do not directly use it in the basic styling, this will in turn be usable by anyone. It means we'll have element with classes like `ais-pagination__link--disabled`, `ais-pagination__link-next`, `ais-pagination__wrapper`, etc.

## 4. Provide themes

Once we have all our elements that can easily be targeted with CSS, we can easily create themes, in the form of one `.css` file to be dropped in the page, to style all the widgets. We will use that to style instantsearch for a Magento or Shopify shop.

**Comment by bobylito** [comment]
Sounds like a plan @pixelastic :)

**Comment by vvo** [comment]
Nice that we now have a detailed overview.

We should also keep in mind to insert the least default CSS styling needed. Every css style we insert will be one that the users will need to override.

The styling default you proposed are the good ones (and doing them with BEM will be cool), dunno if we need more.

Providing no style (or very few) and `cssClasses` allows our users to just re-add or add classes they already have.

We added quite a lot of css style for the slider because that's one that do not work without any style.

**Comment by pixelastic** [comment]
I think we're good with that now, it's implemented in every widget.

**Comment by vvo** [comment]
Awesome work @pixelastic, a lot of small things and attention to details is not so easy to handle!!
