### ISSUE TITLE
Mobile documentation website is currently unusable

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#472]
I tried to show the instantsearch website at lunch but on mobile it was not unusable.

What can we do for the 1.0.0 release that is not too hard to do but still gives the right experience on mobile?

People WILL access our documentation on mobile, especially at launch when it's all new.

**Comment by redox** [comment]
I was waiting the total end of our iterations do work on it, I'm pretty confident about it.

**Comment by bobylito** [comment]
I had a look at the stripe doc and what they do. I will have a try on it.
