### ISSUE TITLE
load previous button doesnt work properly

### ISSUE THREAD

**Issue by slaetthult** [algolia/instantsearch.js#4729]
I'm using the ais-infinite-hits widget and I have integrated the refinePrevious button and the refineNext button. If im starting on page 2 and click at the refinePrevious button everything works so far. But if i want to click on the refineNext button afterwards, nothing happens. I have to click the refineNext button twice to get the next results.

**Comment by Haroenv** [comment]
This was fixed in https://github.com/algolia/instantsearch.js/pull/4725, but not yet released, I'll cut a release now :)

**Comment by slaetthult** [comment]
awesome, will it be fixed for vue as well?

**Comment by Haroenv** [comment]
Yes, this will automatically be fixed for Vue once you update the dependencies!

**Comment by Haroenv** [comment]
Released in 4.21.0 now!
