### ISSUE TITLE
Incorrect behavior on back action of browser history

### ISSUE THREAD

**Issue by pliusnin** [algolia/instantsearch.js#4740]
## 🐛 Bug description

Incorrect behavior of the browser history on back action: User should click twice to get to previous page in browser history.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to `https://instantsearchjs.netlify.app/examples/e-commerce/`
2. Scroll down to pagination and click on second page.
3. After that, click on third page
4. Now try to click on browser's back button - it navigates to previous state (second page) correctly.
5. Try to click on browser's back button again - now it doesn't works correctly. In the result you will be still on the second page instead of first one.

## 💭 Expected behavior

Using browser's back button I expects previous state on each click.

## Environment

- OS: Linux / macOS
- Browser: any
- Version: instantsearch.js 4.20

## Additional context

Look at the flow in `window.addEventListener('popstate', this._onPopState);`. The issue causes because in `AlgoliaSearchHelper.prototype.setState` new instance of SearchParameters is created, so it will be always true for `if (state !== this.state) {` in `AlgoliaSearchHelper.prototype._change`. After that pushState is called.

**Comment by eunjae-lee** [comment]
Thanks for reporting, @pliusnin!

I confirm it's reproducible in the ecommerce example and also in here: (https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/routing-seo-friendly) (for our reference).
And, it doesn't happen when `routing: true` is given to instantsearch().

I'll keep you updated.

**Comment by pliusnin** [comment]
Thanks @eunjae-lee !
Yeah, I forgot to specify that issue reproduces only if `routing` has custom configuration.

**Comment by Haroenv** [comment]
I seem to be hitting into some browser bugs trying it out (back button never appears even though history has a length), but could it be solved like this:

https://codesandbox.io/s/laughing-goldberg-y33l7?file=/src/search-routing.js
