### ISSUE TITLE
Multi-index search of the same index prevents routing from working

### ISSUE THREAD

**Issue by BenTScott** [algolia/instantsearch.js#4773]
## 🐛 Bug description

Using multi-index search prevents routing from updating the URL when searching on the same index.

## 🔍 Bug reproduction

1. Go to https://codesandbox.io/s/github/algolia/doc-code-samples/tree/isjs-v4/InstantSearch.js/multi-index-hits?file=/src/app.js
2. Change the second index to "instant_search"
3. Add routing to the search
4. Type and search term and the URL does not update

**Live reproduction:**

https://codesandbox.io/s/multi-index-hits-forked-xeby6

## 💭 Expected behavior

Expect the URL to be updated with the search term.

**Comment by eunjae-lee** [comment]
Hi @BenTScott 

If you have the same index name more than once, you need to specify `indexId`:

```js
.index({ indexName: 'instant_search', indexId: 'second' })
```

Let me know how it goes.

**Comment by BenTScott** [comment]
That worked, thank you.

**Comment by Haroenv** [comment]
From https://github.com/algolia/instantsearch.js/pull/5134 this is fixed with repeated indexId as well
