### ISSUE TITLE
Feature Request: Google places autocomplete widget to replace places widget

### ISSUE THREAD

**Issue by stevenvandemoortele** [algolia/instantsearch.js#4775]
Algolia places is being removed in may 2022 so a replacement widget using google maps autocomplete, for users who are not javascript wizards that can build their own widgets, would be much appreciated.

**Comment by shortcuts** [comment]
Hi @stevenvandemoortele,

Thanks for the suggestion.

In the first place, we plan to provide a sandbox of our new [Autocomplete](https://github.com/algolia/autocomplete) library with Google Maps in a near future.

It is not planned yet to provide a widget for InstantSearch but we will definitely keep that in mind!

**Comment by Haroenv** [comment]
For now, https://github.com/algolia/instantsearch.js/discussions/4764 and https://github.com/algolia/instantsearch.js/discussions/4904 will be where this would be discussed. In a future major version, the places widget will be removed, but likely without an alternative, as it had low usage
