### ISSUE TITLE
Should we provide an option to include default bootstrap classes?

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#48]
Since bootstrap is heavily used by the web industry. It may be a good idea to provide an option that would automatically add the bootstrap css classes that are making sense for our widgets.

For example, when dealing with #42, the default rendering would be something like this (with more BEM classes):

```html
<div class="as--multipleChoiceList">
  <div><label><input type="checkbox" value="Sony" checked />Sony <span>302</span></label></div>
  <div><label><input type="checkbox" value="Microsoft" />Microsoft <span>120</span></label></div>
</div>
```

This is good because:
- it does not tie us to any css library
- it provides a good isolation of css classes (no conflicts)
- it provides an easy way to style them

**BUT** for bootstrap users this is not so good because they would like something like this:

```html
<div class="as--multipleChoiceList ">
  <div class="checkbox"><label><input type="checkbox" value="Sony" checked />Sony <span class="badge">302</span></label></div>
  <div class="checkbox"><label><input type="checkbox" value="Microsoft" />Microsoft <span class="badge">120</span></label></li>
</div>
```

 (added checkbox and badge classes)

So having an option somewhere to automatically add relevant bootstrap classes would be interesting.

?

**Comment by bobylito** [comment]
Isn't that the purpose of template?

**Comment by vvo** [comment]
Yes that's it, it's just that I do have the feeling that this will annoy bootstrap users to have to provide a template for everything while providing the option would ease their lives a lot.

Let's see how the first CSE and integrators are going to use the library. Then we will see if that's really a need.

**Comment by pixelastic** [comment]
I'd go the template way as well. If we start doing special code for Bootstrap we're going into a maintenance nightmare. There will be several Bootstrap version out, and why not also support Foundation, and so on. But more importantly, Bootstrap also requires you to add some specific wrapping divs which will be more complex to handle than simply css classes.

So definitely, let's keep this css framework agnostic. If we really have a demand for Bootstrap styling, we'll just define and share bootstrap-aware templates.

**Comment by vvo** [comment]
Then we all agree! :)
