### ISSUE TITLE
Website and µblock

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#482]
`$ is undefined` when I activate µblock. This makes the whole animation on the right never appear.
I've never had any issue with jQuery + µblock before,  so I might be missing something here.

Here are my filters (in French):

![cap](https://cloud.githubusercontent.com/assets/5095856/10998773/fedeb398-8497-11e5-91c8-3ddb2e9bf607.PNG)

**Comment by pixelastic** [comment]
I'm using µblock as well and I'm not having the issue. Which page did you test?

**Comment by Jerskouille** [comment]
The homepage with the scroll animation. The failing script is `home.js`. And I think it really depends on the activated lists.

**Comment by vvo** [comment]
I have more and more webpage failing with ublock recently, wonder if we need to dig this one

**Comment by vvo** [comment]
> And I think it really depends on the activated lists.

Maybe first set the default lists, I am not sure a lot of users have tuned their lists

**Comment by vvo** [comment]
I have ublock and it works, dont mess too much with all those lists :D
