### ISSUE TITLE
Rename indexSelector to sortBySelector

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#485]
I want to rename this widget before 1.0.0 mostly because that's the only widget having a name that is based on the internal implementation of sorts in Algolia.

Basically we may find it really nice to be named "indexSelector" because we know that to order results we need multiple indexes.

But for a new user this will look weird at first glance I am sure.

I would prefer to name it sortBySelector and in the documentation clearly state that the requirement is to have multiple indices. This will be enough.

WDYT?

**Comment by pixelastic** [comment]
I'm ok with that. The fact that we need several indices for several sort order should appear in the "Algolia requirements" part of the doc.

**Comment by redox** [comment]
Go for it.
