### ISSUE TITLE
commonJS jQuery custom widget boilerplate

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#487]
Much like https://github.com/instantsearch/instantsearch-ion.rangeSlider but simpler because a simple boilerplate (not an actual widget, just an empty boilerplate to copy paste)

**Comment by bobylito** [comment]
there is no need (@vvo said it)

**Comment by vvo** [comment]
=> we expect people using jQuery AND npm/browserify/webpack to figure out how to do it easily. They can also read the jquery ionrange slider plugin
