### ISSUE TITLE
Ability to pre-set min/max values of a rangeslider on render

### ISSUE THREAD

**Issue by Braunson** [algolia/instantsearch.js#4896]
Looking to set the default values for a range slider on render. For example min:0, max:500 but I want to set the first "start" slider value to 200, and the "end" slider value to 400.

I did see mention of "start" in the docs a few places but it doesn't seem to have taken any effect and that's only for the "start" slider?

**Comment by tkrugg** [comment]
Hi there, thanks for reaching out. 
You should be able to achieve this with initialUiState.
Roughly, for the price attribute:
 
```js
const search = instantsearch({
  indexName: 'my_index',
  initialUiState: {
    my_index: {
      range: {
        price: '200:400',
      },
    },
  },
});
```

Here is an example: https://codesandbox.io/s/affectionate-colden-cj7k9?file=/src/app.js:42-292
I hope it helps!

**Comment by Braunson** [comment]
@tkrugg Thanks, any idea on how to do this on the fly, said as a data attribute on the div element for the slider OR in some sort of stored state on the page. Use case: each user has their own range set.
