### ISSUE TITLE
Question on the page "pagination"

### ISSUE THREAD

**Issue by tojoandria** [algolia/instantsearch.js#4902]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[pagination](https://community.algolia.com/instantsearch.js/v2/widgets/pagination.html)".

How to add  rel="prev"  attribute to "<a ... " pagination previous ?

**Comment by francoischalifour** [comment]
Hey! You need to use [`connectPagination`](https://www.algolia.com/doc/api-reference/widgets/pagination/js/#connector) to control the DOM output. You can see an example on that page.
