### ISSUE TITLE
Question on the page "priceRanges"

### ISSUE THREAD

**Issue by Bhavin1010** [algolia/instantsearch.js#4910]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[priceRanges](https://community.algolia.com/instantsearch.js/v2/widgets/priceRanges.html)".

I am trying to implement code for priceRanges but i am getting error. 

"AlgoliaSearchError: Invalid syntax for numeric condition:price0NaN\n  "

here is my code-

search.addWidget(
	instantsearch.widgets.priceRanges({
		container: '#facet-price',
		attributeName: 'price',
		collapsible: {
			collapsed: is_collapsed
		},
		labels: {
			currency: '$',
			separator: 'to',
			button: 'Go'
		},
		templates: {
			header: '<h3 class="widgettitle">Price</h3>'
		}
	})
);

**Comment by tkrugg** [comment]
HI @Bhavin1010. You're linking to InstantSearch.js v2 docs. Can you confirm you're using InstantSearch v2?
Here is a working example of priceRanges with InstantSearch.js v2:
https://jsfiddle.net/63saqt5w/10/


If you are indeed using v2, I cannot recommend enough to update: the upgrade guides are sitting here: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/angular/#migration-from-v2-to-v3.

I'll close for now, but if you still have an issue, please do reopen and provide a code sample so I can help troubleshoot.
