### ISSUE TITLE
Using InstantSearch in typescript requires to install algoliasearch

### ISSUE THREAD

**Issue by HamzaInPerth** [algolia/instantsearch.js#4911]
I'am trying to import types from instantsearch.js to create a custom client but unfortunately when I import any type I'm getting the following errors.

```
 Cannot find module 'algoliasearch' or its corresponding type declarations.

15 } from 'algoliasearch';
          ~~~~~~~~~~~~~~~


Error: ../../node_modules/instantsearch.js/es/lib/InstantSearch.d.ts:3:8 - error TS1259: Module '"events"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

3 import EventEmitter from 'events';
         ~~~~~~~~~~~~

  node_modules/@types/node/events.d.ts:82:5
    82     export = EventEmitter;
           ~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.


Error: ../../node_modules/instantsearch.js/es/types/algoliasearch.d.ts:1:32 - error TS2307: Cannot find module 'algoliasearch/lite' or its corresponding type declarations.

1 import type algoliasearch from 'algoliasearch/lite';
                                 ~~~~~~~~~~~~~~~~~~~~


Error: ../../node_modules/instantsearch.js/es/types/algoliasearch.d.ts:2:37 - error TS2307: Cannot find module 'algoliasearch/lite' or its corresponding type declarations.

2 import type * as AlgoliaSearch from 'algoliasearch/lite';
                                      ~~~~~~~~~~~~~~~~~~~~
```

EDIT:

**About the `algoliasearch/lite` error:**

It seems that when I add the `algoliasearch` package the `algoliasearch/lite` errors disapear. Is it possible to use instantsearch.js in typescript without having to add algoliasearch npm package?

I feel like this makes instantSearch bound to AlgoliaSearch officially in a TypeScript env. I'm not sure if this was intended though.

**About the `eventEmitter` errors:**

When I change my tsconfig.json by adding `"allowSyntheticDefaultImports": true` the error disapears.

**Comment by tkrugg** [comment]
Hi there @HamzaInPerth, thanks for reaching out.
`algoliasearch/lite` is part of the `algoliasearch` npm package. I think you're right, InstantSearch types are using the client's types, so either it should reimplement them to be fully independent, or list the client as a peer dependency.
@Haroenv do you agree with this?

Question to @HamzaInPerth : are you not reusing the client types for your custom client?

**Comment by Haroenv** [comment]
Yes, this is expected, the types otherwise would have to be fully retyped here, which would be a source of confusion and possible errors. We might need to think of a special solution, as it's not really a dependency, but maybe it can be considered one. algoliasearch is required to be installed when using typescript, but doesn't need to be used. 

Synthetic default imports are needed indeed.

**Comment by HamzaInPerth** [comment]
Hello @tkrugg I'm using the client types for my custom client but I need to import it from algoliasearch. 

Hello @Haroenv this stackoverflow might help to determine where to add the dependency: https://stackoverflow.com/a/63905376

**Comment by Haroenv** [comment]
Peer dependencies are listed now
