### ISSUE TITLE
Type conflict between algoliasearch client and its usage in instantSearch

### ISSUE THREAD

**Issue by bidoubiwa** [algolia/instantsearch.js#4916]
## 🐛 Bug description

related to: #4911 

The InstantSearch client returns upon search with the geo widget the `insideBoundingBox` field containing a string. 

See the following test: 
 
https://github.com/algolia/instantsearch.js/blob/6e6293046de82f90336bc857efa9d0f5fcb8e62b/src/widgets/geo-search/__tests__/geo-search-test.ts#L1717-L1721

Nonetheless the declared type dictates that it should return an array of array of numbers: 

see [SearchOptions](https://github.com/algolia/algoliasearch-client-javascript/blob/00ad9246a9f7822b97c96b14d5627862c15050f3/packages/client-search/src/types/SearchOptions.ts#L295) types. 

```ts
readonly insideBoundingBox?: ReadonlyArray<readonly number[]>;
```

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Create a custom searchClient for instantSearch
2. Try to adapt `insideBoundingBox`
3. TypeError

```
Argument of type 'readonly (readonly number[])[] | undefined' is not assignable to parameter of type 'string'.
```

## 💭 Expected behavior

They should be of same type

## Environment
-  "algoliasearch": "^4.10.5",
-   "instantsearch.js": "^4.30.1",

**Comment by Haroenv** [comment]
yes, it's really the client type that is a little more restrictive than needed. Does having a ts-ignore have an impact on any site though?

The correct type is ```ReadonlyArray<readonly number[]> | `${number},${number},${number},${number}`;```, and then the ts-ignore could be ignored, when the algoliasearch requirement is set to the version in which that fix is done

**Comment by bidoubiwa** [comment]
```
Does having a ts-ignore have an impact on any site though?
```

It creates a bit of magic code/technical debt as you'll have to remember that somewhere in your code lies a `ts-ignore` that may create bugs if instantSearch decides to change the type of `insindeBoundingBox`.

It is the reason I think why you use TypeScript, to avoid manipulating variables in another type.  

> The correct type is ReadonlyArray<readonly number[]> | `${number},${number},${number},${number}`;, and then the ts-ignore could be ignored, when the algoliasearch requirement is set to the version in which that fix is done

Thats cool 😊 Is the fix planned for a near release?

**Comment by Haroenv** [comment]
I'd need to check whether the typescript version required in algoliasearch is modern enough to allow template strings, but otherwise, feel free to make a pull request and then it will be fixed @bidoubiwa :)

**Comment by bidoubiwa** [comment]
I will do that! Thanks a lot for your answers :) I thought you might not want to change the types of algoliasearch-client-client as they are independent of instantsearch 😅. But If it's oke and if it does not break the whole package, I will absolutely do the PR!
