### ISSUE TITLE
Experiencing a Syntax Error with Latest InstantSearch 4.33.0 version with NextJS / Javascript

### ISSUE THREAD

**Issue by sgrobert** [algolia/instantsearch.js#4949]
Hi there,

I'm new to Algolia Search and was trying to install and run Instantsearch.js on my NextJS installation.

However, after installing v4.33.0, or even trying to backtrack to v4.32.0, but both versions seemed to be throwing this `SyntaxError: Unexpected token 'export'` every time I attempted to run my setup. 

Attaching the screenshots on what I'm seeing:

<img width="1010" alt="Screenshot 2021-10-30 at 8 36 33 AM" src="https://user-images.githubusercontent.com/759805/139514024-2d2e7049-af9e-474c-a898-e954d9a07d0f.png">
<img width="656" alt="Screenshot 2021-10-30 at 8 28 18 AM" src="https://user-images.githubusercontent.com/759805/139514019-c8be1697-e355-41ae-80c6-5c73b0d0684c.png">

---

Hope someone can help assist or redirect me at potentially what I might be doing wrong? Thank you.

---

"algoliasearch": "^4.11.0",
"instantsearch.js": "^4.33.0",
"next": "latest",

**Comment by sgrobert** [comment]
Hi there,

At the moment, since I'm on NextJS / React, I've found the `React InstantSearch` as a working workaround. So will be discarding Instantsearch as much current option. 

Thanks so much for reading and building this! Cheers!

**Comment by francoischalifour** [comment]
Hey @sgrobert, thanks for reporting. We're aware that the bundling of InstantSearch.js causes problems with Next.js. We'll work on fixing this in the coming weeks.
