### ISSUE TITLE
In console - Error: Uncaught (in promise): Error: <attribute> is not a retrieved facet. 

### ISSUE THREAD

**Issue by brew-danica** [algolia/instantsearch.js#4953]
Hello, 
I'm currently running Angular instantsearch on v3.0.0-beta.5 as that is the best fit for our current angular version. However, despite extending the the refinementList component with the BaseWidget, and getting it to work, there is a persistent error in the console for the facets.

`Error: Uncaught (in promise): Error: <attribute> is not a retrieved facet.`
This is even though the facets are retrieved and functional to sort the data returned. My thoughts are that this error could be being thrown as the page is loading, but i'm unsure. 

In the console a warning is also flagged:
`angular-instantsearch.js:865 Could not find attribute [<attribute>] into hit object, will display an empty string.`

How would we go about rectifying this error?

Below are the details of the set up:

**Angular CLI: 8.3.29
Node: 14.17.1
Angular: 8.2.14**

 **"algoliasearch": "^3.35.1",
 "angular-instantsearch": "3.0.0-beta.5",
 "instantsearch.css": "^7.4.5",
 "instantsearch.js": "3.7.0",**
<img width="1172" alt="Screenshot 2021-11-08 at 12 11 12" src="https://user-images.githubusercontent.com/49677508/140739968-0d373f65-0556-4984-be79-74311c5f39d4.png">

**Additional**
This is how we configured the refinementList custom widget with the BaseWidget
<img width="513" alt="Screenshot 2021-11-08 at 12 45 07" src="https://user-images.githubusercontent.com/49677508/140744384-44080936-379c-4a15-8d3e-aaf71ce3975b.png">

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch). Thanks!

**Comment by brew-danica** [comment]
> Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch). Thanks!
> 
> Did you set the attribute you used for the refinementList as an attributeForFaceting via settings or the dashboard?

Hiya! Thanks! I'm just setting that up. Yes the attributes are all set for faceting in the dashboard

**Comment by brew-danica** [comment]
Hiya :) There was an issue trying to recreate the project with the sandbox, but was receiving the error that the instantsearch.css package was [missing a semi colon](https://github.com/codesandbox/codesandbox-client/issues/6235). At the moment we are using the version 3.0.0.beta-5 and were wondering whether there were plans to release a stable version 3, otherwise we are looking into upgrading our angular app to use algolia instant search v4.

**Comment by Haroenv** [comment]
there are no plans to release a stable v3, but v4 is released as stable now @brew-danica, note that there's a fair amount of breaking changes regarding custom widgets, so follow the migration guide

**Comment by brew-danica** [comment]
Thank you @Haroenv, yes it seems like that is the route we will have to go down. Thanks for your help :)

**Comment by Haroenv** [comment]
I will close this for the time being then, but feel free to open a new issue if you get stuck in v4

**Comment by tkrugg** [comment]
@brew-danica if it helps at all, you can start off this example. 
It should be easy to update to angular-instantsearch@3.0.0-beta.5. I'm not sure it's matching your Angular version however. 

https://codesandbox.io/s/github/algolia/doc-code-samples/tree/96de9145e0e65d80a5308de0b2a877a6df7057e3/Angular%20InstantSearch/getting-started?file=/src/main.ts
