### ISSUE TITLE
Applying a sort removes all widgets in dynamicWidgets

### ISSUE THREAD

**Issue by grizzm0** [algolia/instantsearch.js#4954]
## 🐛 Bug description

When applying a sort by using the `sortBy()` widget all widgets in `dynamicWidgets()` becomes empty. After doing some debugging locally I can see that the items are still being rendered but the parent container is removed from the DOM.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to `https://codesandbox.io/s/distracted-wu-8p3cr`
2. Click on `Price (desc) in sort dropdown`
3. Scroll down to `...`

**Live reproduction:**

https://codesandbox.io/s/distracted-wu-8p3cr

## 💭 Expected behavior

The facets should not disappear.

## Environment

- OS: macOS
- Browser: Chrome
- Version: 95

**Comment by grizzm0** [comment]
Doesn't look like a bug. Apparently you need to copy all facets to your virtual indices.

**Comment by tkrugg** [comment]
@grizzm0 Correct! you replica index needs to have facets configured, and most likely with the same exact configuration in this case. Glad you figured it out.
