### ISSUE TITLE
searchBox reset button is broken

### ISSUE THREAD

**Issue by giilby** [algolia/instantsearch.js#4979]
## 🐛 Bug description

As of v4.34.0, `searchBox`'s reset button is broken: it clears the search input but does not fire a new search. Downgrading to v4.33.2 fixes the issue.

## 🔍 Bug reproduction

1. Perform a search, preferably for something with no results (e.g. "whendidtimebegin") so that the issue can be clearly seen.
2. Click the reset button (the "X" on the right side of the search input).
3. Note that the search results are not refreshed.

**Live reproduction:**

The issue is reproducible via Algolia's official Storybook: https://instantsearchjs.netlify.app/stories/?path=/story/basics-searchbox--default

## 💭 Expected behavior

When `searchBox`'s reset button is clicked, the search input is cleared and search results are refreshed.

## 🖥 Screenshots

N/A, as it's easily reproducible via the Storybook.

## Environment

- OS: macOS
- Browser: Chrome, Safari (browser doesn't seem to be the issue)
- Version: Chrome 96.0.4664.110, Safari 15.1 (17612.2.9.1.20)

**Comment by Haroenv** [comment]
Not sure yet what the exact cause is, but I suspect https://github.com/algolia/instantsearch.js/commit/50068417e5e7211802bc717b582946f6e630d7ac#diff-f40b1a6178ae2c51eb738408b7bbe911aba8e2a74219d220388bf72f5e1a6194L144-R145 is related

**Comment by Haroenv** [comment]
The fix has been released in 4.37.2, thanks for reporting!

**Comment by giilby** [comment]
@Haroenv No problem...thanks for the prompt bugfix!
