### ISSUE TITLE
documentation: back button is not working when on documentation page

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#498]
Load documentation, click on searchBox, click on back: nothing happens (expecting to go to top).

Load documentation, click on searchBox, click on setup, click on back: nothing happens (expecting to go to searchBox).

Weird as this should be a standard behavior of the browser (= nothing special to do to handle it). So we did something that broke it.

Maybe that since we are adding anchors dynamically (with name=..) then maybe it breaks. Dunno here.

**Comment by Shipow** [comment]
fixed with responsive/mobile branch
