### ISSUE TITLE
Connect Infinite Hits Makes Network Requests Despite Retrieving Results From Cache

### ISSUE THREAD

**Issue by matt-savage** [algolia/instantsearch.js#4994]
## 🐛 Bug description
I have an instance of connectInfiniteHits with a custom cache. The custom cache is working and confirmed by modifying the data before the cache is written. The modified data is what gets rendered, not what is directly returned from the server. However, InstantSearch continues to make network requests for each page regardless of whether the cache.read method returns data from cache.

## 🔍 Bug reproduction
Create an instance of InstantSearch, set the cache to instantsearch.createInfiniteHitsSessionStorageCache(), watch for network requests regardless of whether or not we have hydrated cache.

**Steps to reproduce the behavior:**
1. Create an instance of InstantSearch
2. Set cache to instantsearch.createInfiniteHitsSessionStorageCache()
3. Fresh page reload sees cache get written
4. Second page load sees cache get read, and network request made for the same data.

## 💭 Expected behavior
InstantSearch only performs network requests if the cache read method returns null

## 🖥 Screenshots
Successfully written to cache:
<img width="831" alt="Screenshot 2022-01-16 at 10 38 37" src="https://user-images.githubusercontent.com/87069715/149656684-af68a600-8e78-40ea-bc56-976220d9642b.png">

Requests page data anyway:
<img width="832" alt="Screenshot 2022-01-16 at 10 41 01" src="https://user-images.githubusercontent.com/87069715/149656733-60c614d3-fdf0-4c9b-831e-13290c2bbc1d.png">

## Environment
- Browser: Chrome, Safari
- Version: [e.g. 22]
- InstantSearch 4.23.0
- Vanilla JS (no framework)

**Comment by Haroenv** [comment]
Unfortunately I fear this would be quite complicated to achieve. There are two levels of cache:

- search client: this is to prevent the request of already-requested queries
- infinite hits: this is for display of pages that weren't in the current network request mostly

the infinite hits cache isn't in control of whether a network request happens, as that happens on every interaction with the search.


A completely different design could solve this where the search client cache instead was saved in session storage, and infinite hits would call as many network requests (or cache as needed), but that's not possible easily right now. 

What I can see as a solution for you now is to pass the responsesCache: sessionStorageCache (that you can write based on https://github.com/algolia/algoliasearch-client-javascript/tree/master/packages/cache-browser-local-storage) in combination with your existing infinite hits cache. The information will then be cached twice, but it will avoid the initial network request.


Hope that helps, before we take the time to redesign this feature

**Comment by Haroenv** [comment]
While we might revisit this, for the time being this issue is solved I think. If you have any more questions, don't hesitate to open a different issue. Have a great day!
