### ISSUE TITLE
Move widget spec to wiki once inplemented

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#50]
While working on the widget it's good to iterate fast. But then, we need to keep them up to date and revisionned so might as well to a wiki for those

**Comment by bobylito** [comment]
While working on the widget it's good to iterate fast. But then, we need to keep them up to date and revisionned so might as well to a wiki for those

**Comment by vvo** [comment]
Yes for this workflow:
- while in heavy dev mode (prototype), using issues is ok since we are going to FIX them
- when released or implemented, then move to wiki
- every API enhancement change should still be an issue then translated to a wiki change

**Comment by bobylito** [comment]
:+1:

**Comment by bobylito** [comment]
Wiki is the readme for now, and will be the live documentation afterwards.

**Comment by vvo** [comment]
:+1:
