### ISSUE TITLE
Sending events to Insights middleware too early in connectHit

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/instantsearch.js#5013]
## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/laughing-kare-d7e0bo?file=/src/app.js
2. Search for `e`
3. Check the console log
4. When `onEvent` of Insights middleware is triggered, DOM is not updated yet, while `hits` passed from `connectHits` are up-to-date.

**Live reproduction:**

https://codesandbox.io/s/laughing-kare-d7e0bo?file=/src/app.js

## 💭 Expected behavior

https://github.com/algolia/instantsearch.js/blob/9209954594b048e9db3a91490002ae75522bceb2/src/connectors/hits/connectHits.ts#L107

↑ When you look at the code, the connector sends event before rendering. Although it passes the correct `hits` along with the event, but the DOM isn't up-to-date.

I think it can simply be like the following.

```diff
-       renderState.sendEvent('view', renderState.hits);

        renderFn(
          {
            ...renderState,
            instantSearchInstance: renderOptions.instantSearchInstance,
          },
          false
        );

+       renderState.sendEvent('view', renderState.hits);
```

https://codesandbox.io/s/objective-haze-25e8fi?file=/src/app.js

↑ this is a modified version, where `onEvent` is called after rendering.

## Context

This was discovered in the context of Google Tag Manager. On the GTM doc, we guide to use Insights middleware as "Hits Viewed" hook. When it's triggered, it notifies GTM so that it can track events. However, at that time, the DOM isn't up-to-date, so it went wrong.

**Comment by Haroenv** [comment]
That sounds like a correct fix. Are you willing to make a pull request? I'm assuming this needs to be done in the other widgets (infinite hits, autocomplete) as well.

**Comment by eunjae-lee** [comment]
Yeah I couldn't think of any other side effect, so I assume it's correct too. I'll send a PR whenever I have some time. Thanks in advance for the review!
