### ISSUE TITLE
defining max in a RangeSlider automatically filters results to that max value

### ISSUE THREAD

**Issue by dianos** [algolia/instantsearch.js#5037]
## 🐛 Bug description

Defining max in a RangeSlider automatically filters results to that max value

## 💭 Expected behavior

All results to come in until the user actually filters them.

## 🖥 Screenshots

![image](https://user-images.githubusercontent.com/4541410/160559876-7f6185b7-f3cd-4cdf-b168-0ba7ff7ee295.png)

## Additional context

```
rangeSlider({
    container: '#price-range-slider',
    attribute: 'price',
    max:8000,
  }),

```

Adding the filter automatically is a nice future to have in some scenarios. The default should be to work with all results until the end user actually interacts with the widget.   The way instantsearch works now how do I go about removing that max filter optimaly?

**Comment by Haroenv** [comment]
Could you clarify which behaviour you want for the max? Would it not apply the filter, but in the UI still show as 8000 as the highest value?

**Comment by dianos** [comment]
Exactly.  The reason to put in the max is to make the range slider usable when there is large price outliers.   But we don't want to limit the initial search results.   When the end user drags the upper bound then the upper filter should be applied.

**Comment by Haroenv** [comment]
I can't think of a good solution for that problem right now without forking the library, the concept of min and max encodes both the visual and filter range. What I can think of is transforming the response to filter out the outliers instead of setting min and max:

```
const originalSearch = searchClient.search;
searchClient.search = function (requests) {
  return originalSearch(requests).then(({ results }) => ({
    results: results.map((result) => {
      if (!result.facets_stats || !result.facets_stats.price) {
        return result;
      }

      return {
        ...result,
        facets_stats: {
          ...result.facets_stats,
          price: {
            ...result.facets_stats.price,
            // override the maximum
            max: 2000,
          },
        },
      };
    }),
  }));
};
```

https://codesandbox.io/s/busy-goodall-ktjqt1?file=/src/app.js:139-683

**Comment by dianos** [comment]
Thanks, that works well.
