### ISSUE TITLE
showMore() is not a function

### ISSUE THREAD

**Issue by Romain-BASE-GVA** [algolia/instantsearch.js#5043]
I'm trying to implement a custom infiniteHits with a showMore button:

on https://www.algolia.com/doc/api-reference/widgets/infinite-hits/js/#connector

at the showMore section, there is an example with a custom item rendering, I have copy/past that example without changing anything. It works fine, by that I mean it shows my items, but as soon as I click on showMore button it return : showMore is not a function.

**Comment by Haroenv** [comment]
Did you copy the code exactly? When I add it to a sandbox it seems to work: https://codesandbox.io/s/gracious-voice-ycyuix?file=/src/app.js

Don't hesitate getting back to us sharing your code and we can figure out why showMore isn't a function in your case
