### ISSUE TITLE
Tourism example missing a script

### ISSUE THREAD

**Issue by benlower** [algolia/instantsearch.js#5050]
## 🐛 Bug description

In the tourism example, the index.html file makes reference to instantsearch.production.min.js. This file is no where to be found in the example files.

**Comment by Haroenv** [comment]
That file gets created in `npm run build` (https://github.com/algolia/instantsearch.js/blob/master/examples/tourism/package.json#L6), but I'm indeed not sure if that's the best option. It would be better if more organised like the e-commerce example
