### ISSUE TITLE
documentation: Missing some widget icons

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#506]
Some widgets do not have a specific icon in the documentation, they are re-using other icons. Here is the list of icons to add:

- [ ] hitsPerPageSelector
- [ ] hierarchicalMenu
- [ ] numericRefinementList
- [ ] priceRanges

I also do not understand the `hits` icon. This looks like a graph to me.
![image](https://cloud.githubusercontent.com/assets/283419/11030263/42d729a4-86cd-11e5-9f22-973edd35b4a0.png).

cc @Shipow

**Comment by Shipow** [comment]
@pixelastic 
![image](https://cloud.githubusercontent.com/assets/976175/11105710/015120ec-88d1-11e5-89be-9645d5874b24.png)

**Comment by Shipow** [comment]
proposal for new icons

![image](https://cloud.githubusercontent.com/assets/976175/11106966/94070f16-88d9-11e5-97e8-95748c15c8fa.png)

**Comment by redox** [comment]
:+1: @Shipow

**Comment by Jerskouille** [comment]
:+1: @Shipow !

**Comment by pixelastic** [comment]
Oh ok, but the fact that it limits the number of results to 3 does not convey the way I usually picture a list of records returned.

I like the hierarchical one, but I'm not sure which is which for the others

**Comment by Jerskouille** [comment]
I'd say:
- `hierarchicalMenu`
- `numericRefinementList`
- `priceRanges`
- `hitsPerPageSelector`: this is the only one that doesn't fully convince me.
- `clearAll`

**Comment by pixelastic** [comment]
Oh ok, yeah, with the name alongside this will be understandable.
