### ISSUE TITLE
On event example code given in the docs throws error in typescript

### ISSUE THREAD

**Issue by VitorTS** [algolia/instantsearch.js#5129]
## 🐛 Bug description

Example given in the docs throws error due to mismatched types

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://www.algolia.com/doc/api-reference/widgets/insights/js/#widget-param-onevent
2. Copy and run the example code like this:
```
createInsightsMiddleware({
  insightsClient: window.aa,
  onEvent: (event, aa) => {
    const { insightsMethod, payload } = event;

    // Send the event to Algolia
    aa(insightsMethod, payload);
  }
});
```
4. You will see the error `Argument of type 'InsightsClientMethod | undefined' is not assignable to parameter of type 'InsightsClientMethod'.`

## 💭 Expected behavior
Code compiles with no error 

## Environment

- OS: MacOs 12.2.1
- Browser: Chrome 106

**Comment by Haroenv** [comment]
I've made a pull request to the documentation with that conditional added, this issue will automatically close once that PR is merged
