### ISSUE TITLE
ie9 compatibility rangeSlider

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#514]
![image](https://cloud.githubusercontent.com/assets/1689007/11035534/61eecf56-86f3-11e5-9e8a-5e2a8898b78e.png)

This is caused by this line https://github.com/algolia/instantsearch.js/blob/master/widgets/range-slider/range-slider.js#L90

**Comment by Shipow** [comment]
did you apply the breaking change facetName -> attributeName ?

**Comment by maxiloc** [comment]
yep

**Comment by vvo** [comment]
I had the issue, move to attributeName and it works, can you double check?

**Comment by maxiloc** [comment]
yes it's working, my bad
