### ISSUE TITLE
Algolia Analytics with react native 

### ISSUE THREAD

**Issue by alifarajj** [algolia/instantsearch.js#5148]
Hey ,
When I tried use middleware with react native I got this error 
<img width="924" alt="Screenshot 2022-10-12 at 5 43 32 PM" src="https://user-images.githubusercontent.com/110973043/197796776-41a30797-6bf8-4f18-af90-3b82ff257322.png">
![unnamed](https://user-images.githubusercontent.com/110973043/197796793-dd2c0359-5673-4781-9322-077cb572c9e8.png)

**Comment by alifarajj** [comment]
I am not using document in react native @Haroenv

**Comment by Haroenv** [comment]
I've made a pull request https://github.com/algolia/instantsearch.js/pull/5149 to fix this, you can try it out locally by using the codesandbox instructions for resolutions of instantsearch.js

**Comment by alifarajj** [comment]
Thank you , I tried it locally with these changes and worked fine ... waiting for new version
