### ISSUE TITLE
Large bundle size with ES module

### ISSUE THREAD

**Issue by xXCalleManXx** [algolia/instantsearch.js#5222]
### 🐛 Current behavior

I have just created a new Svelte project using Vite.

Created a super simple page without any templating and no added widgets.

Thre result is a large bundle size that includes alot of unused packages.
![main_full (2)](https://user-images.githubusercontent.com/7306904/208679088-8d7469ab-8d35-4d70-a77a-45998a46d70b.png)

Some examples of unused code (maybe?):
- Hogan.js
- @algolia/events
- all connectors in the picture
- all components in the picture

See this for rollup: https://codesandbox.io/s/dawn-waterfall-sbvly9?file=/index.html

I think the reason for this is because of inproper imports. Examples:
- https://github.com/algolia/instantsearch.js/blob/master/packages/instantsearch.js/src/lib/InstantSearch.ts#L2
- https://github.com/algolia/instantsearch.js/blob/master/packages/instantsearch.js/src/lib/InstantSearch.ts#L3

### 🔍 Steps to reproduce

```
$ npm init vite
$ cd new-vite-project
$ yarn add algoliasearch instantsearch.js
```

init instantsearch without adding any widgets
```
<script lang="ts">
  import algoliasearch from "algoliasearch/lite";
  import instantsearch from "instantsearch.js/es";
  const searchClient = algoliasearch('APP_ID', 'APP_KEY');
  const search = instantsearch({
    indexName: 'INDEX',
    searchClient,
  });
  search.start();

</script>

<main>
    <p>EMPTY PAGE</p>
</main>
```

### Live reproduction

https://codesandbox.io/s/dawn-waterfall-sbvly9?file=/index.html

### 💭 Expected behavior

Hogan.js should not be bundled and the same with unused connectors, widgets and templates.

### Package version

algoliasearch 4.14.3, instantsearch.js 4.49.2, vite 4.0.0, svelte 3.54.0

### Operating system

Ubuntu

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment]
We'll look more in detail, but a first quick answer around helper and events is that they are required for InstantSearch to function, so can't be tree-shaken. 

Hogan could be aliased to empty module if you know you aren't using any string templates, we might be able to make that an option/entry point, but I'm not sure how yet

The widgets and connectors should not have been included, I'm not sure what causes them to be imported, as the /es entry point purposely avoids adding it, but I wonder if vite somehow resolves the source instead of the list files

**Comment by xXCalleManXx** [comment]
I used `rollup-plugin-visualizer`.

Add `rollup-plugin-visualizer`: `yarn add -D rollup-plugin-visualizer`

If you edit your `vite.config.ts` file so it looks like this:
```
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import { visualizer } from "rollup-plugin-visualizer";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    svelte(),
    visualizer({
      filename: 'stats/index.html',
      emitFile: true
    })
  ],
})
```


then run `yarn build` and you will have the html file inside the newly created stats folder

**Comment by Haroenv** [comment]
Hm, there must be something else going on, as the bundle is different for me:

<img width="1388" alt="Screenshot 2022-12-20 at 16 23 32" src="https://user-images.githubusercontent.com/6270048/208702602-ea97970a-d0f6-41c0-9336-d40e6d94b4df.png">

**Comment by xXCalleManXx** [comment]
Oh.. wow.. I'm an idiot 😂🤦‍♂️
I was looking at an old html file. The connectors are gone now.

I think that it's still weird that genereate-hierarchical-tree.js and RefinementList.js is bundled, but I guess that's something releated to algoliasearch-helper using CommonJS

**Comment by Haroenv** [comment]
Yes, more than it being CommonJS, it's written in a way that doesn't allow for tree shaking, with a single class being in charge of all functionality. We have future plans of changing that, but it's very complicated (lots of legacy code in that part).

Glad tree shaking isn't broken!
