### ISSUE TITLE
Setting `initialUiState` for a custom widget (negativeRefinementList) throws an exception

### ISSUE THREAD

**Issue by abusada** [algolia/instantsearch.js#5234]
## 🐛 Bug description

I followed the docs [here](https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/react-hooks/?client=TypeScript) to build a negative refinement list widget, the article is clear and the widget is working as expected, except when I needed to have one item selected by default (or when I try to use routing).

To make an item selected by default I'm passing an `initialUiState` to `<InstantSearch.. ` component like this:

```
initialUiState={{
  demo: {
    negativeRefinementList: {
      categories: ["Technology"]
    }
  }
}}
```

When the app is rendered I get the following error: 
> Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading 'categories')

Source

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Create a custom widget
2. Use the widget
3. Set InitialUiState for the widget

**Live reproduction:**
https://replit.com/@FarisAbusada/InstantSearchCustomWidget#pages/index.tsx

## 💭 Expected behavior

"Technology" checkbox to be selected by default

## 🖥 Screenshots
![screenshot- 2022-12-13 at 15 03 11@2x](https://user-images.githubusercontent.com/2572320/207353344-fdd8346f-d0eb-456a-9e21-f0ab6e4f5ed4.jpg)

## Environment

- React InstantSearch version: 6.38.1
- React version: "18.2.0"

**Comment by Haroenv** [comment]
I've investigated this issue, and it's actually a bug in the algoliasearch-helper where exclude refinement doesn't first check if there are facets at all, before reading from the result. I've tracked it in https://github.com/algolia/algoliasearch-helper-js/issues/921, so this issue can be closed
