### ISSUE TITLE
documentation: rangeSlider demo display is buggy

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#527]
This is the current display of the rangeSlider on the documentation page:

![image](https://cloud.githubusercontent.com/assets/283419/11062911/397deba4-87b3-11e5-92fe-e10680be6eca.png)

As you can see, handlers are too big. I think I caused that when I loaded the `instantsearch.css` in the documentation page. We'll have to de-duplicate the rules between that file and `default-theme.css` that might be causing the issue.

**Comment by redox** [comment]
Part of #554
