### ISSUE TITLE
documentation: the Template part of the page is cut

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#528]
![image](https://cloud.githubusercontent.com/assets/283419/11062956/88eabf96-87b3-11e5-8757-85690551bb79.png)
![image](https://cloud.githubusercontent.com/assets/283419/11062965/933c6bb6-87b3-11e5-8c8d-bd21abd4d90b.png)

There might be a missing closing `div` somewhere.

**Comment by redox** [comment]
I think it has been fixed with ce32aa9.
