### ISSUE TITLE
[hierarchical widget] error when no results

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#532]
Steps to reproduce:

- empty query
- refine on hierarchical widget
- type a random character until there is an error

**Comment by maxiloc** [comment]
seems to be an issue of the helper

**Comment by vvo** [comment]
linked to https://github.com/algolia/instantsearch.js/pull/440?

**Comment by maxiloc** [comment]
not sure this one is in master already, no ?

**Comment by vvo** [comment]
> not sure this one is in master already, no ?

Yes it was fixed so you have another issue maybe

**Comment by pixelastic** [comment]
@maxiloc Do you still have the issue? Can we close this one?

**Comment by maxiloc** [comment]
Yes if the helper have been updated we can close it

**Comment by bobylito** [comment]
We didn't do a release of the helper. Will do that.

**Comment by bobylito** [comment]
Humm didn't we

**Comment by bobylito** [comment]
I think this one is fixed. Can you check @maxiloc ?
