### ISSUE TITLE
Demo Link in 2nd paragraph is 404

### ISSUE THREAD

**Issue by winkler1** [algolia/instantsearch.js#535]
"To get started, check out algolia.github.com/instantsearch.js!"

**Comment by vvo** [comment]
Awesome thanks, we are not even live but already getting feedback. Thanks a lot, fixing

**Comment by winkler1** [comment]
Great! Really curious about this... I've done faceted search with ElasticSearch before. The GIF on your testing slides looked amazing :)

**Comment by vvo** [comment]
Done: https://github.com/algolia/instantsearch.js#instantsearchjs

we will brag about the release soon, stay tuned :D
