### ISSUE TITLE
style: Lint documentation scss files

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#538]
The linting task is currently only applied to the main code, not the documentation. This already created code regressions (https://github.com/algolia/instantsearch.js/pull/534), so we should enforce the same standard as in the main code.

**Comment by redox** [comment]
I just spent 1 hour and it's really more complex than expected:
 - because of Jekyll, the main S{A,C}SS files have a triple-dash `---` header -> breaks parsing
 - I got plenty of error because of some bugs of the `sass-lint` tool (undefined exceptions)

Not sure what to do in the short term.

**Comment by pixelastic** [comment]
Yes, me too. I spent some hours on it, I have a branch with part of the fix. I managed to fix the jekyll/front-matter issue and making all run, but now I have a huge list of linting errors in our doc scss files.

I'll push the branch shortly so you can have a look.

**Comment by pixelastic** [comment]
Pushed to #566. Linting of scss doc is enabled on this branch but fails loudly (176 errors detected)

**Comment by redox** [comment]
OK, I would keep that out of 1.0 then; it looks like we're gonna spend days on it :)

**Comment by pixelastic** [comment]
Yep, I realized as well that this was going to take some time so I dumped it here as a WIP so you could see it.

We'll have to be extra careful in the CSS editing of the docs because we have no linting on it.

**Comment by Shipow** [comment]
What I don't understand is that guard will scream if there is some error. no?

**Comment by pixelastic** [comment]
Apparently not. I managed to commit `sass` files in the past that could not compile correctly

**Comment by Shipow** [comment]
I won't prevent you to commit, but the terminal will say that the the sass compile is broken.

**Comment by pixelastic** [comment]
Yep, and we would like Travis to catch that

**Comment by vvo** [comment]
Yes all checks on travis otherwise it's only working if the dev has ran the good commands (= we do not trust DEVS :D)

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it
