### ISSUE TITLE
Add an option to show facets anyway if there is no results

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#54]
You can see the behavior here.

https://magento.algolia.com/catalogsearch/result/?q=__empty__#q=dd&page=0&refinements=%5B%7B%22color%22%3A%5B%22Purple%22%5D%7D%2C%7B%22categories%22%3A%5B%22Sale%22%5D%7D%5D&numerics_refinements=%7B%7D&index_name=%22magento_default_products%22

**Comment by vvo** [comment]
How do you do it in magento?

**Comment by maxiloc** [comment]
For now I have no nice way to handle that.

So :
- I created a second helper that just do an empty query if no results are found in the first helper
- Re-display only the facet block and adding a empty class on each facet refinements
- When I click on a facet if an empty class is here, I set the query to ""

That's why I ask for algolia/algoliasearch-helper-js#146 to avoid this double helper.

**Comment by maxiloc** [comment]
No I don't think so because we want the count for an empty query with the current refinements, which is not always the last state

**Comment by pixelastic** [comment]
> The other option would be to always keep the last state and avoid replacing the facets block if there are no results. Isn't it?

"last state" seems too broad to me. Do you mean the last helper state or an inner state of the widget. I'm not even sure this would fix the issue.

**Comment by bobylito** [comment]
> "last state" seems too broad to me. Do you mean the last helper state or an inner state of the widget. I'm not even sure this would fix the issue.

The helper state should be enough to display any widget (Famous last words)

**Comment by redox** [comment]
> "last state" seems too broad to me. Do you mean the last helper state or an inner state of the widget. I'm not even sure this would fix the issue.

I mean, the last state returning results :)

**Comment by vvo** [comment]
Still unsure if this is a good practice or not, the "last state returning results" being not so easy to grasp for a user. I do prefer the simple "start over" or "hit back" method.

**Comment by vvo** [comment]
@maxiloc @Jerskouille As we discussed maybe showing the current refinements (user selected refinements) even when there's no results, to allow the user to deselect some of them would be best?

If so we need another issue and an API proposal in every refinements (true by default) to do it.

Let me know if you want to deal with it.

**Comment by Jerskouille** [comment]
`currentRefinedValues` (#404) will solve part of the problem, so I think we shouldn't think about it for the v1, but it might make sense to implement this on faceting widgets, let's wait until we see if there is a demand for this.

**Comment by maxiloc** [comment]
It's fairly easy to implement, just tried it with refinement list, it's working well. 
One thing to note is that it needs autoHide to be true to have a good experience

For reference this is the code needed to do it
```
if (facetValues.length === 0) {
        facetValues = helper.getRefinements(facetName).map(function(facet) {
          return {
            count: 0,
            isRefined: true,
            name: facet.value,
            url: //fixme
          };
        });
      }
```

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is very old and not done, reopen if you have the need and want to fix it

**Comment by netgusto** [comment]
This use case is now documented: https://discourse.algolia.com/t/keep-all-filters-even-if-no-results/493/16?u=jerome.schneider
