### ISSUE TITLE
documentation: webpage performance

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#547]
After we release 1.0.0, we can optimize again the documentation (by order of importance):
- [ ] use an svg sprite (can be generated on https://icomoon.io/) =>  -- requests for small things
  There are also gulp/grunt tasks to automate this I believe. Like https://github.com/jkphl/svg-sprite
- [ ] use minified versions for JS and CSS (currently using unminified main.css, home.js, default-theme.css)
- [ ] combine jquery plugins from jsdelivr in a single jsdelivr tag => -- requests for small things
- [ ] optimize svg sprite in the build step (svgo sprite.png)
- [ ] optimize remaining img on build
- [ ] minify html
Any other idea, add it here

**Comment by Shipow** [comment]
Here is a quick list of small optimisation I've already made

- Imported all scripts from CDN js-deliver (so we can merge them)
- Custom build of boostrap.js with only the collapse component.
- Custom font with font-icons (5 icons)
- Removed all boostrap unused import in scss
- Deferred script at the bottom and optimized loading sequence
- Leanified all assets https://github.com/JayXon/Leanify it use svgo on svg ( I had to revert one icon so I don't like no more the idea of build script )

Ideas
- Dust css or similar (the website is simple the parser should be ok)
- some fixes in sass for overqualified selector
- an illustration of the doc is still in png
- include more svg, so less call but bigger html


@vvo I'm not sure to understand the sprite.png? If you want to convert svg in png it's a bad idea.

**Comment by vvo** [comment]
@Shipow no I was talking about an actual svg spritesheet, not png

**Comment by bobylito** [comment]
I need to do some minification/packing for the js of a new animation for the front page, so I will do the minification part of the js :) (and try to integrate that with the build we have with guard :) )

**Comment by vvo** [comment]
I will active some of optimizations with cloudflare right now it should be sufficient, we can dig more into performance when released. Right now it's not so bad.

**Comment by vvo** [comment]
> Here is a quick list of small optimisations I've already made

Good that you did all this, right now its pretty good

**Comment by vvo** [comment]
This is not critical, the website is currently not that big and the doc website itself is not the product even if really important! If there's some optimization to do, that should be in the instantsearch build itself.

:horse: CLOSING BOT SAYS:
> This is old and not done, reopen if you have the need and want to fix it

**Comment by vvo** [comment]
minification was done for js css
