### ISSUE TITLE
documentation: force using cdn.jsdelivr.net/instantsearch.js/specific.version/

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#548]
Because when doing a new release, we want to be sure to use the version we just deployed. While /0/ /1/ are subject to clearing the jsdelivr cache which can take 30 minutes server side and multiple days to appear in the browser of returning users.

**Comment by vvo** [comment]
So its more complex than that.

Currently we use jsdelivr /0/ so there's always a version on this endpoint. It may not be the latest one we want but at least there's one

While if we use a specific version then it NEEDS to be on jsdelivr once we update gh-pages, which may or may not be the case and will do more harm than good.

Stick with the current way for now, let's see if we have issues at any moment.

The solution will be to use a specific version AND decorelate the gh-pages update from the new version release. (so no more gh pages in release.sh, wait for jsdelivr to pull us)

**Comment by redox** [comment]
> Stick with the current way for now, let's see if we have issues at any moment.

:+1:
