### ISSUE TITLE
handle container: '.sortResults' (multiple container elements)

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#55]
What happens when the container is a class selector like '.stats' if you want to display stats in multiple places?

**Comment by pixelastic** [comment]
To be more explicit: What should happen when the specified `container` key resolve to several DOM elements. Should they all get rendered or only the first one.

Use-case is adding several widgets such as "XXX result in YYY ms" or "Order by" at the top and bottom of the search results.

I'd go with all the matching elements

**Comment by vvo** [comment]
I wonder if we should handle this case or disable it. Maybe let's wait for it to happen because I am not even sure I have seen such use cases.. ?

**Comment by pixelastic** [comment]
I had it on some of the demos I built, but ok for postponing it until we see it live

**Comment by vvo** [comment]
Will be reopened when there's a clear need for it
