### ISSUE TITLE
API proposal: numeric selector

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#563]
The idea is to create a new widget that allows you to build the Airbnb-like "Guests" select:

![](http://g.recordit.co/L9jtqnAZ2b.gif)

I was thinking about something like:

```js
search.addWidget(
  instantsearch.widgets.numericSelector({
    container: '#guests',
    attributeName: 'person_capacity',
    operator: '>=',
    options: [
      { label: '1 guest', value: 1 },
      { label: '2 guests', value: 2 },
      { label: '3 guests', value: 3 },
      { label: '4 guests', value: 4 },
      { label: '5 guests', value: 5 },
      { label: '6 guests', value: 6 }
    ]
  })
);
```

**Comment by pixelastic** [comment]
Why is it limited to numeric values? The use case looks like it could use any kind of refinement (strings).

**Comment by redox** [comment]
> Why is it limited to numeric values? The use case looks like it could use any kind of refinement (strings).

We could probably build a `facetSelector` as well but not sure we want to mix it in a single widget: I think it's easier to understand not mixing the `operator` VS `disjunctive` VS .... Also the underlying code would be pretty different because of that `operator`. WDYT?

**Comment by pixelastic** [comment]
Yes, makes sense. It would be much easier to have two widgets, otherwise the underlyong code will get too messy.

You should make sure that it is possible to "undo" this filter, like allowing a `value` of `undefined` to remove the filter.

**Comment by redox** [comment]
> I'll add comments on the PR

:+1:
