### ISSUE TITLE
Make test not requiring -test suffix

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#565]
This is artificial and not necessary since we are already putting all the tests in a `__tests__` subfolder. The advantage is that then we can have direct relation between test files and files being tested.

**Comment by vvo** [comment]
> This is artificial and not necessary since we are already putting all the tests in a __tests__

I think the use case is when you have fixtures that are not tests but still .js files then it's easier to have -test.js only for test files.

**Comment by bobylito** [comment]
We don't have any ;) But I get the point ;)
