### ISSUE TITLE
widget.init implementation change

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#575]
```js
widget.init(state, helper, this.templatesConfig);
```

should be

```js
widget.init({state, helper, templatesConfig});
```

To be consistent with render(). I wonder how we missed that :D

This is needed for 1.0.0, mostly search and replace here. Not a lot of widgets are using init.

**Comment by redox** [comment]
> widget.init({state, helper, templatesConfig});

About that, I think it's not so nice to have object-based parameters for those 3 "public" methods. As soon as you don't use ES6, it looks weird: https://github.com/instantsearch/instantsearch-ion.rangeSlider/blob/master/src/widget.js#L26-L28

**Comment by vvo** [comment]
> As soon as you don't use ES6

Agree. But if you do not use ES6 then you should not have strong opinions on whether the interface is good or not? (Not trying to isolate people but really imagine if they would be frustrated). I guess it's ok.

**Comment by bobylito** [comment]
I'm not a huge advocate of object options but truth is that is widely used. I don't think anyone would be that frustrated. So I also guess it's ok :)

**Comment by vvo** [comment]
was done
