### ISSUE TITLE
test: manually test instantsearch.js documentation, examples, lib on supported browsers

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#576]
Desktop: IE11 > Chrome
Mobile: iPhone Android recent ones

**Comment by pixelastic** [comment]
I'm adding notes here while testing:

## Fairphone (Android 4.2.2, Chrome 44)

- The "widget display" in the documentation do not get displayed
- Selecting a element in the menu select dropdown does not scroll to the correct part of the page
- None of the examples are working

JS must be broken somewhere. I'll be doing remote debugging on my Fairphone, but I first need to install the latest Chromium version...

**Comment by pixelastic** [comment]
Ok, that was simply the issue with loading scripts from various ports :)

**Comment by pixelastic** [comment]
Tested on IE11, working fine excepte for the small issues fixed in #628.

Still some issues in the e-commerce example to fix:
![image](https://cloud.githubusercontent.com/assets/283419/11210255/18bd13e4-8d27-11e5-97f8-772e66bf406b.png)

**Comment by pixelastic** [comment]
Ok on IE12 and IE11. Now testing the iPad...

**Comment by pixelastic** [comment]
Works on iPad as well.

**Comment by pixelastic** [comment]
I'm considering this one closed until we have more devices to test
