### ISSUE TITLE
Change doc url to /doc/ ?

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#579]
![image](https://cloud.githubusercontent.com/assets/976175/11127333/27c22cbe-8974-11e5-8940-07a7bf0234e4.png)

**Comment by redox** [comment]
You think it's better for SEO? or just because it's shorter?

Can be done by patching:
 - https://github.com/algolia/instantsearch.js/blob/master/docs/_config.yml#L11
 - and https://github.com/algolia/instantsearch.js/blob/master/docs/documentation.md#L4

**Comment by Shipow** [comment]
Just because it's simplier ... but I guess that only few geeks type 'documentation' when searching in google =)

**Comment by vvo** [comment]
Google does the autocomplete for me and I select it :D

**Comment by vvo** [comment]
React uses "docs"

**Comment by pixelastic** [comment]
So, do we rename or not?

**Comment by vvo** [comment]
No need
