### ISSUE TITLE
I have an issue with hierarchicalMenu

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#581]
I've an error when I click on second level link, any idea?

![image](https://cloud.githubusercontent.com/assets/976175/11135920/15ba1104-89aa-11e5-9a00-57cecb64447b.png)

Here is my declaration
![image](https://cloud.githubusercontent.com/assets/976175/11135937/3a5c4090-89aa-11e5-825c-c388ce174597.png)

**Comment by Shipow** [comment]
And limit option doesn't seem to be applied:
![image](https://cloud.githubusercontent.com/assets/976175/11136133/2c7fdb4c-89ac-11e5-815b-05efb22942fa.png)

**Comment by vvo** [comment]
Can you send an ngrok to the failing website? So we can debug it.

**Comment by vvo** [comment]
Removed the limit option not working, will create another issue (confirmed).

**Comment by Shipow** [comment]
the failling website is the ecommerce demo on feature/example-page branch

**Comment by redox** [comment]
> the failling website is the ecommerce demo on feature/example-page branch

I don't think you published it @Shipow

**Comment by pixelastic** [comment]
@vvo: You said you're opening another issue. Do we still need this one?

**Comment by vvo** [comment]
This is an issue with the data of the example, tracked in 1.0.0 issue
