### ISSUE TITLE
It's difficult to add a label to the index selector

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#582]
like 'sort by'

I think that adding a label should be allowed by the widget same way as refinementList allows header.

![image](https://cloud.githubusercontent.com/assets/976175/11136336/c3bb22cc-89ad-11e5-9e03-74ede4c4fb32.png)

**Comment by redox** [comment]
Cannot do something like https://github.com/algolia/instantsearch.js/blob/master/dev/index.html#L45-L46 ?

**Comment by Shipow** [comment]
in your example the 'for' attribute doesn't match the input (should have a name/id) and it breaks the bootstrap structure label.control-label + div > input.form-control.
So we still do some magic but I'had the feeling that is wansn't handy enough

**Comment by Shipow** [comment]
If facet widgets support title, I think select widget should support labels.

**Comment by Shipow** [comment]
Hmm.. I was wrong, structure is good so the only remaining problem is 'for' attribute of the label.

**Comment by redox** [comment]
> the only remaining problem is 'for' attribute of the label.

Yes indeed, and we'll have the same issue for the `numericalSelector`. Easy to add the `label`, but I'm still worried about the way we'll generate the underlying `id`s to bind the `for`.

**Comment by pixelastic** [comment]
I'm not sure I get the issue. Why can't we do a `<label>Sort by: <div id="index-selector"></div></label>`?

Anyway, we do not have to be Bootstrap compliant (at least, not for v1.0.0). If we really need to have the select outside of the label, I would simply allow passing a `selectId` option to the widget, and let the user correctly set the same `for` on the label.

**Comment by Shipow** [comment]
Input inside the label is wrong on both semantical and W3c aspect.
"we do not have to be Bootstrap compliant" <- No, we have to be compliant with EVERYTHING (so, seek an destroy this kind of small incompatibility).
Your proposition break the logic (User just added tittle of his facets, he won't understand why labels are not supported for a simple select) + it's made to be easy so if I have to read the doc to make a valid markup, it's not cool.

**Comment by vvo** [comment]
> Input inside the label is wrong on both semantical and W3c aspect.

Just for the sake of it, can you link to the W3C issue? I only found this: http://www.w3.org/TR/html401/interact/forms.html#h-17.9 and they actually say that one or the other is feasible. Maybe I miss a link

**Comment by Shipow** [comment]
ok right, it works for w3C.. It's still ugly and doesn't make much sense semantically but ok.

**Comment by pixelastic** [comment]
> Input inside the label is wrong on both semantical and W3c aspect.
Hmm, that's how Bootstrap does it for checkbox/radio. Wrapping an input in a label works the same as linking them through `for`/`id`, but this can actually be really helpful when styling.

> Your proposition break the logic (User just added tittle of his facets, he won't understand why labels are not supported for a simple select)+ it's made to be easy so if I have to read the doc to make a valid markup, it's not cool.

Oh ok, you mean we should provide the API directly in the widget to add a label, to stay consistent with the fact that we already provide a way to add headers. Sorry, I did not get that. But yeah, that could be a nice improvement.

**Comment by pixelastic** [comment]
But still... I'm not confortable with adding too many markup from the widget. If I take the Bootstrap example of doing selects in form this is:

```html
<div class="form-group">
      <label for="selector">Select menu</label>
      <select id="selector" class="form-control">
        <option>Option</option>
      </select>
</div>
```

Which will translate in instantsearch to

```html
<div class="form-group">
  <label for="selector">Select menu</label>
  <div id="selector-menu"></div>
</div>
```
```javascript
search.addWidget(
  instantsearch.widgets.hitsPerPageSelector({
    container: '#selector-menu',
    options: [{},{}, ...],
    selectId: 'selector',
    cssClasses: {
      root: 'form-control'
    }
  })
);
```

I've only added the `selectId` option, that should add an `id` to the `select`, so it is correctly bound to the `label`. I don't think we should wrap the `select` in a `label` from the widget (not anybody would want a wrapped element). I'm not sure we should automatically add a label before the select (users not using Bootstrap might want it somewhere else, or wrapped in their own div).

**Comment by vvo** [comment]
> I've only added the selectId option, that should add an id to the select, so it is correctly bound to the label. I don't think we should wrap the select in a label from the widget (not anybody would want a wrapped element).

Yes me too, for other widgets we do have some automatic labels but they are in a template you can change. While here you cannot change the structure once done.

**Comment by vvo** [comment]
> I've only added the selectId option, that should add an id to the select,

I like it so, simple API change for power users.

**Comment by Shipow** [comment]
wfm

**Comment by redox** [comment]
Go :+1:

**Comment by vvo** [comment]
moved to #679

**Comment by olance** [comment]
I understand the will not to add too much markup from the widget itself, but I have a question then: how is one supposed to hide the `<select>` label when `autoHideContainer` is set to `true` on the widget and the search returns no hits?

**Comment by olance** [comment]
Just had an idea: what about imitating what's been done with HTML?
We don't want a hard-coded `<label>` inside each widget, but we could have a generic `label` widget that is given a reference to the widget it relates to using a `for` option/prop.

We should then have a way to synchronize the `display: none` between the widget and its label?

**Comment by redox** [comment]
> how is one supposed to hide the <label> when autoHideContainer is set to true

Yes you're right; we need to find something.

**Comment by pixelastic** [comment]
@olance Good point about the `autoHideContainer`. The previous suggested solution of `selectId` won't cut it.

**Comment by vvo** [comment]
@olance about your proposition yes it would work but it would be cool if we could find a simpler way to do it because it look like a lot of code for a simple `<label>`

I would want to be able as a user to say `{label: 'select smg' }` in the option of the sort by selector.

If anyone has an idea on how to do it without breaking things for people that would be cool

**Comment by olance** [comment]
Hmmm yes, it's simpler though limited. Unless we have a template option to which the `label` option value is passed so that it can be placed at any other place than the default one without having to create a custom widget just for that.

**Comment by vvo** [comment]
Moving to #1057
