### ISSUE TITLE
It's a bit weird to find and override the previous page hidden class

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#583]
maybe we can find something easier

![image](https://cloud.githubusercontent.com/assets/976175/11142260/3ff40cee-89ec-11e5-8011-b0948dec929f.png)

**Comment by Shipow** [comment]
And I didn't find how to put a disabled attribute on the link instead of hiding it

**Comment by vvo** [comment]
> And I didn't find how to put a disabled attribute on the link instead of hiding it

Indeed you can't I think because the surrouding link is not a template, only what's inside (label)

**Comment by Shipow** [comment]
it leads to ugly css to do something really basic

![image](https://cloud.githubusercontent.com/assets/976175/11142703/b99ea452-89ef-11e5-90a7-3e7f7443806f.png)

**Comment by pixelastic** [comment]
Sorry, not sure I get the issue. Which part do you find ugly? You can remove the `#pagination` selector as this is overspecific, this will make the selector easier to understand. Do you suggest we add a `disabled` class to the link as well as the parent?

**Comment by vvo** [comment]
The underlying issue I think is that we automatically hide the previous link if you are on first page. If you want to disable this behavior there's no API for that.

We could provide one, works?

**Comment by pixelastic** [comment]
Yes, we could provide an option to not mark previous link as disabled.

But I think the issue @Shipow was refering to was more about styling the disabled links with gray color and disabled cursor (for example) instead of hiding them.

**Comment by Shipow** [comment]
Yes I don't think hidding the link is the bullet silver so it should be easy to change behavoir.

**Comment by vvo** [comment]
@Shipow Aside from providing an option to still see the link, you will have to style it. Does adding ais-pagination--link__disabled would work for you?

**Comment by Shipow** [comment]
if default markup is a link <a class="ais-pagination--link__disabled" disabled>Previous</a> it's easy to customize/hide

**Comment by pixelastic** [comment]
This can definitely be done, but we have the same kind of issues in the refinementList for the active links. 

As a side note, is `.ais-pagination--link__disabled` really needed when we have `.ais-pagination--item__disabled a`?

I'm ok with adding the disabled class to the link in the end, we just need to be consistent with the other widgets.

**Comment by Shipow** [comment]
nope

**Comment by Shipow** [comment]
and you can probaly use a[disabled=disabled] but not the most obvious

**Comment by pixelastic** [comment]
So, do we need to do something on this one or is it ok?

cc @Shipow

**Comment by vvo** [comment]
For now .ais-pagination--item__disabled a is sufficient. @Shipow if it's really bothering reopen
