### ISSUE TITLE
rename all facetName to attributeName

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#590]
Problem: some of the widgets are exposing facetName, some are exposing attributeName

Solution: rename everything to attributeName

why?

+ multiple people reported the distinction was not necessary
+ @seafoox has a good point is that even for the slider, you need the numeric attribute to be a facet to get min and max, so it's no "attributeName"
+ the original goal was to say "if they see 'facetName', they will know they need to add as an attribute for faceting" Which is not true at all and an easy generalization
+ in the end, all of them are attributes
+ hierarchicalMenu already uses the "attributes" (array of attributes)
+ the #589 is already taking care of explaining to the user that it needs to be a facet sometime
+ we will be able to show good errors in the console if a widget was created and the facet is not found in the result = we miss some configuration

**Comment by bobylito** [comment]
:+1:

**Comment by vvo** [comment]
was done
