### ISSUE TITLE
do our best to inform the user on some missing index configuration

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#591]
Let's say I add any widget that need to have a particular attribute configured as a facet, I would want the code after the first result is received to tell me "Error: you must add ... as an attribute for faceting" if I did not do it.

What do you think?

What are the others guesses we can make?

Original idea by @seafoox 

Warn when:
- asking for any widget that requires some attribute to be an attributeForFaceting and the attribute is not
- asking for a numeric refinement and the attribute values are not numeric
- using a toggle with something than is not a boolean attribute where we expect one

**Comment by pixelastic** [comment]
How would you do that? By doing a call to get the index settings?

**Comment by vvo** [comment]
Depends on the use case, the most common error being "I want a filter on attribute `color`".

So the index must be configured with attributes for faceting "color". We can find from the answer that there's no response for "color" because it's not configured.

I only wonder if we can distinguish "not configured" from "no facet values given the context"

**Comment by pixelastic** [comment]
Yep, I don't think we can tell one from the other only from the response.

**Comment by pixelastic** [comment]
> asking for a numeric refinement and the attribute values are not numeric

We could do the same for toggle and boolean attributes.

**Comment by vvo** [comment]
Yes, any idea you can add it to the main description of the issue, I am adding this good idea too

**Comment by Jerskouille** [comment]
What about doing a call on instantiation when a `debug: true` parameter is passed and have a method that takes the setting as an attribute and returns a boolean to say if it's valid, like `checkIndexConfiguration(settings)` in each widget that could check something?

**Comment by pixelastic** [comment]
Maybe check with @kokliKo who did something similar for the advice on the dashboard.

I'm 100% ok for adding this kind of auto-debug tool to instantsearch, but maybe only in a specific `instantsearch.debug.js` build?

**Comment by vvo** [comment]
No progress made on this for now, closing.
