### ISSUE TITLE
Feedback / Suggestions on documentation

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#593]
The overall documentation looks really good - well done! Just wanted to share with you a few feedback / suggestions / questions:

- **Home page hero illustration.** Don't you think it would be more interesting to have another illustration on the hompage. I’m not sure that “Drones” talk to people as much as much as it does to some of us. I think we could rather go for something more generic, or even eventually, have 2-3 rolling pictures for instance: media, e-commerce, misc
- **Social buttons** Could be nice to add some social buttons, even if it should be at the bottom of the page

![image](https://cloud.githubusercontent.com/assets/1101220/11146231/c21a330e-8a0c-11e5-8207-013346d978be.png)

- **Navigation home page**: Could be nice to have small links on the right side to jump from each section of the page. Like in a vertical carousel

- **Not only about search, but also about navigation / browsing**My understanding is that InstantSearch.js not only help people to build slick search UX, but also Browsing / navigation UX. When we pitch it to our users, we say that its actually something that comes together. With the speed our of API, the frontier between both is more and more blurred.

- **Documentation's navigation**. For now, everything seems to be in bold, using less font-weight on some level could make it look more polished.

![image](https://cloud.githubusercontent.com/assets/1101220/11146754/4a4f9ce2-8a11-11e5-834e-7ffe4582ed26.png)

- **Documentation's navigation current position**. Could be nice to use something like Bootstrap scrollspy https://bootstrap.algolia.com/javascript/#scrollspy in order to ease the navigation

- **Title's auto anchor**. Like in the API documentation, it could be nice adding auto anchor, so people can refer to specific part of the documentation. Maybe using something like https://github.com/bryanbraun/anchorjs

- **Blank space under From a CDN  / NPM section** It seems weird to have that much space there. I understand that we want to put the code on the right side, but maybe for those two we could make an exception and put it underneath.
![image](https://cloud.githubusercontent.com/assets/1101220/11146840/0d1b4bcc-8a12-11e5-8b35-e87df97d2066.png)

- **Inline code block color too light**. It's diffucult to read light colored text on light background. Don't you think so? Would be great increasing the contrast.

![image](https://cloud.githubusercontent.com/assets/1101220/11147700/1efb5372-8a18-11e5-87cf-4e9e0ca58f8a.png)

- Is there any plan to also make it available on Bower, which is guess is widely used for front-end packed management? Or maybe, not anymore?

Looking forward to get your thoughts, and exchange about all those points.

**Comment by redox** [comment]
:+1: @seafoox, I like your ideas.

About bower, I think it still makes sense to add it, even if it's slowly dying.

**Comment by pixelastic** [comment]
I'm ok with drones. It's both generic and specific at the same time, showing that you can use it to build your own search on any items. But I don't mind changing if you have another idea. I would not like a more generic e-commerce website, though.

Ok for the anchors as well. We need to be careful because some of the ids in the markup are used as placeholders by the instantsearch demos.

And finally, let's push it to bower, but not as the main/default way of grabbing it.

**Comment by vvo** [comment]
@seafoox following your proposal, I submitted #765 which change:

- social github button
- lower down big white blank space by adding more text
- use font-weight normal on widget names in doc
- low contrast on code in white background areas
- various text fixes formatting that we missed or introduced recently

Also anchors were already done in the doc webpage.

There's an issue for bower already #351 

And as for the links on the homepage I think we are good as we want people to really scroll and get the effect

Thanks a lot for the feedback and sorry for the verrrrrrrrrrry late reply.
