### ISSUE TITLE
Pagination should probably not have a "Last" button

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#594]
**Google** doesn't do it. They don't even provide a first
[Page 15 on Google](https://www.google.fr/#q=te&start=140)

**Amazon** doesn't do it. However, they explicitely show that they only display 20 pages.
[Page 15 on Amazon](http://www.amazon.com/s/?page=15&keywords=te)

We have a 1000 hits limitation that will confuse people if they click `>>` and end up on page let's say 20 when we say "100 000 results found".

So in the end, I think we should probably hide it by default or just completely remove it.

**Comment by bobylito** [comment]
hiding it by default is nice indeed.

**Comment by redox** [comment]
:+1:

**Comment by vvo** [comment]
Hiding by default is good, if you have one for the start of the pagination, people needing the end will ask for it.

**Comment by vvo** [comment]
This needs an API proposal because hiding it by adding display: none is not an option: it would require the user to override the display property somehow.

So better have a "showLastButton" bool that will add/remove a hidden class?

**Comment by Jerskouille** [comment]
> So better have a "showLastButton" bool that will add/remove a hidden class?

:+1: I would just remove it from the DOM though, some people might use `display: xxx` hacks otherwise if they missed the option in the documentation.

**Comment by vvo** [comment]
Ah yes so `showLastButton:false` would remove the last pagination from the DOM, wfm

**Comment by vvo** [comment]
moved to #883
