### ISSUE TITLE
Find a simpler initialisation pattern

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#6]
Current implementation:

```js
var instant = new instantSearch.InstantSearch(appId, apiKey, indexName);
```

Most of our libraries are using:

```js
var instance = someFunction(appId, apiKey);
```

It could be good to have the same pattern? @redox @pixelastic @bobylito

**Comment by pixelastic** [comment]
Yep, I'd rather have a `var instance = instantSearch(foo, bar)`. Not sure if we need to pass the indexName when creating the instance or later (do we handle search in multiple indices at once?)

**Comment by vvo** [comment]
> Yep, I'd rather have a var instance = instantSearch(foo, bar). Not sure if we need to pass the indexName when creating the instance or later (do we handle search in multiple indices at once?)

We do need at least one indexName since one instant search interface is always targeting an index.

Then some widgets like sortOrder (sort by popularity, price ..) will need to use other indexes but it's in their APIs.

**Comment by bobylito** [comment]
Why don't we have something like : 
```javascript
var instantsearch = require('instantsearch').make;
var search = instantsearch(appId, apiKey, indexName);
```

I'm not sure about the key used here (make) but I think that's easy to instanciate and use. Don't you think?

**Comment by vvo** [comment]
Honestly I would be a bit surprised by this kind of API.

Documentation tooling aside, given our previous modules, I would advocate for something like:

```js
var instantsearch = require('instantsearch');
var search = instantsearch(appId, apiKey, indexName);
```

I know @bobylito this is not what you prefer, adding it because I feel this is straightforward.

**Comment by vvo** [comment]
@algolia/javascript Are you ok with switching to:

```js
var instantsearch = require('instantsearch');
var search = instantsearch(appId, apiKey, indexName);
```

Instead of:

```js
var instantsearch = require('instantsearch');
var search = new instantsearch.InstantSearch(appId, apiKey, indexName);
```

**Comment by bobylito** [comment]
Ok go :D
