### ISSUE TITLE
Automatically generate the widget usages

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#601]
I think we could make our JSDoc parser generate the `usage` as well to ensure we keep them always synchronized and DRY.

```js
const usage = require('./usage');
```

```js
module.exports = `Usage:
@function({
  @mandatoryArg,
  [...]
  [ @optionalArg=@defaultValue ],
  [ [...] ]
})`;
```

**Comment by bobylito** [comment]
Yes! We could have everything in the js doc :)

**Comment by vvo** [comment]
Nobody showed up to build this and we never had to revisit it: not a true blocker
