### ISSUE TITLE
documentation: clicking on pagination links scroll to top of the page

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#618]
Clicking on pagination links in the documentation page scroll the user to the top of the page.

I realize this can be useful in a real world scenario, but this is weird in the doc. Not sure how to fix that, though.

**Comment by vvo** [comment]
Yep: scrollTo: false. BUT it should not be shown inside the copy paste code for the user, since its true by default

**Comment by pixelastic** [comment]
Why not? Especially if it's `true` by default, we can show that the option can be overridable.

**Comment by vvo** [comment]
WFM thats also what @bobylito proposed
