### ISSUE TITLE
documentation: missing trailing slash redirects to algolia.github.io

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#624]
Click [here](https://community.algolia.com/instantsearch.js)

**Comment by vvo** [comment]
fixing this right now

**Comment by vvo** [comment]
Ok cool, fixed. Two benefits: our new default github pages (org wise) is community.algolia.com.

People trying to access algolia.github.io on purpose will be redirected to community.algolia.com (301, good for SEO too).

Solved by:
- adding a CNAME file to https://github.com/algolia/algolia.github.io
- removing the cloudflare host override (otherwise infinite redirect loop)

**Comment by Shipow** [comment]
:+1:
