### ISSUE TITLE
remove cssClasses: {header: '', item: ''} from the docs snippets

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#634]
I think already having them pretty much everywhere else (all options, html output) makes it not mandatory to have them in the code snippets. People will dig the options if they are curious/interested.

So we need to give them the right level of information at every level/context

**Comment by vvo** [comment]
What do you think?

**Comment by Jerskouille** [comment]
I agree, you gave a good reason to remove them: people will copy paste the snippets.

**Comment by pixelastic** [comment]
> people will copy paste the snippets

Ok, this convinced me

**Comment by pixelastic** [comment]
Sorry @vvo, did not see you were assigned on it, my bad

**Comment by vvo** [comment]
Do it @pixelastic wfm

**Comment by vvo** [comment]
was done
