### ISSUE TITLE
Issue in the /examples/ rendering on mobile

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#636]
The might(e-) is back cc @Shipow @lae25c 

![2015-11-17 14 51 59](https://cloud.githubusercontent.com/assets/123822/11213584/05509b58-8d3d-11e5-8897-4e0f6b619c8f.png)

**Comment by pixelastic** [comment]
We might need a new breakpoint here, and put the image on top of the text

**Comment by vvo** [comment]
still an issue, can be easily triggered with chrome dev tools and selecting a mobile device
