### ISSUE TITLE
widget icons in /examples/ are cryptic

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#637]
I know they are beautiful but on the /examples/ page they are raising the [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty_and_doubt).

What do you think?

I would remove them, even adding a tooltip etc won't do it I think (mobile being another reason). Too much level and quantity of information at once I feel.

(I had to say it :D)

![2015-11-17 14 51 59](https://cloud.githubusercontent.com/assets/123822/11213621/314f08fc-8d3d-11e5-92a8-7f5456ab8b9e.png)

**Comment by pixelastic** [comment]
Yep, not sure if this is needed. I don't mind keeping them because they are pretty :p but it's hard to get what they mean without tooltips.

**Comment by bobylito** [comment]
It's up for 1.0.0. Let's wait for negative feedback on this point to decide if we move forward, ok?

**Comment by vvo** [comment]
I am ok closing this one, not a big deal
