### ISSUE TITLE
Amazing example display issue on Firefox

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#638]
`height: inherit` seems to behave differently between firefox and chrome. Removing it fixes it to 150px which ensures it displays fine but doesn't scale.

![cap](https://cloud.githubusercontent.com/assets/5095856/11213794/4885e68e-8d3e-11e5-9c15-579b0e566211.PNG)

**Comment by pixelastic** [comment]
Could you check if the bug is still here. I fixed a similar issue on IE11 here: https://github.com/algolia/instantsearch.js/pull/631

**Comment by vvo** [comment]
Seems ok for me
