### ISSUE TITLE
Rename multipleChoiceList to refinementList 

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#64]
Should we rename multipleChoiceList to refinementList?

One of the argument : `singleRefine` in multipleChoiceList allows you to do a list of refinements with only one possible refinement (like a list of radio buttons to select a shipping method).

So I guess `multipleChoiceList` is no more the best name now that we have the possibility to do a single refine.

**Comment by redox** [comment]
:+1: for the renaming.

**Comment by vvo** [comment]
So .. we .. will .. rename it

**Comment by bobylito** [comment]
WFM

**Comment by pixelastic** [comment]
Sound good too
