### ISSUE TITLE
Potential naming conflict in `React.component`

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#65]
We're currently defining our React modules with `class Foobar extends React.Component {}`.

As we're using pretty generic names (`Stats` comes to mind), we will surely have conflict with userland components. Is there a way to namespace components (`InstantSearch.Stats`) in React?

**Comment by vvo** [comment]
Isn't the class name private to our code? Does it goes inside some register in react? If so that's really strange from react to do so!

**Comment by pixelastic** [comment]
I'm not sure. I didn't see any namespace defined so I assumes this went to global `React` somewhere. Will have to check.

**Comment by vvo** [comment]
From an ES6 POV, doing `Class extends MainClass`.. does not store any token in a global namespace or in `MainClass`

**Comment by pixelastic** [comment]
Oh, yes, agreed.

But my point was more about the `Stats` widget and any widget with a generic name. I assume that if we have users building their website with React, they might already have a `Stats` widget on their side which will collide with our own.

**Comment by vvo** [comment]
> I assume that if we have users building their website with React, they might already have a Stats widget on their side which will collide with our own.

Writing copy of the discussion we had with Tim: if we expose our React components in a namespace somewhere at some point like `instansearch.components.Stats` then it should be ok.

@pixelastic If you want to try to trigger a conflict with app.js and a custom Stats + using our Stats widget try it, should be ok. Otherwise close

**Comment by pixelastic** [comment]
I didn't manage to create a conflict, so we're good.
