### ISSUE TITLE
Refinement list seems not able to handle 'composed'(?) facets

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#673]
![image](https://cloud.githubusercontent.com/assets/976175/11308349/0c1353d0-8fbe-11e5-8e9a-2b9f82c717b0.png)

![image](https://cloud.githubusercontent.com/assets/976175/11308340/ffb71ed2-8fbd-11e5-806e-da4fe6763e67.png)

![image](https://cloud.githubusercontent.com/assets/976175/11308333/ee521372-8fbd-11e5-83b2-e9ded76f3f74.png)

![image](https://cloud.githubusercontent.com/assets/976175/11308362/19cf7814-8fbe-11e5-8e32-17d2017001f2.png)

resuts = no error, but nothing displayed

**Comment by Shipow** [comment]
haha, noob

**Comment by vvo** [comment]
WAT

**Comment by vvo** [comment]
missing attributeForFaceting?

**Comment by Shipow** [comment]
nop 'anwsers' :gun:
