### ISSUE TITLE
documentation: anchors are not showing anymore

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#676]
At some point we had small anchors showing up when hovering titles, it seem they disappeared because we removed it from the font bundle?

**Comment by redox** [comment]
cc @Shipow (https://github.com/algolia/instantsearch.js/blob/master/docs/js/doc.js#L133)

**Comment by Shipow** [comment]
ha yes good catch @vvo

**Comment by Shipow** [comment]
fixed
