### ISSUE TITLE
numericRefinementList issue with strings

### ISSUE THREAD

**Issue by bluespore** [algolia/instantsearch.js#678]
Hi guys,

Just a small one. I was setting up a test implementation of Algolia to demo for a client in the Travel space using some of their data. The entries contain a "price" field, so I was using the `numericRefinementList` widget to filter, only, it wasn't working.

I edited a single entry from the Algolia interface to remove the quotes from around the price value, and now it's fine.

My question is: should the onus be on always ensuring the data is correctly structured before being indexed, or is it possible the widget can perform a simple regex to determine if that string, is in fact just an integer/float, anyway?

I'm considering situations where one of your customers may not be technically equipped to change their data structure themselves, or unable to do so due to system privileges - it would be painful for them to realise the predefined widgets don't work.

Cheers,
Sean.

**Comment by vvo** [comment]
Hi @bluespore awesome that you tested Algolia, indeed this is an issue we should more proactively warn our users about.

For instance if you ask for a numericRefinementList and the underlying attribute is not an integer then you should get a clear warning (your usecase).

We have already an issue about it: #591 and we will work on this pretty soon to avoid our users to waste more time.

On a side note, you may be one of the first users of instantsearch.js I would love to have some feedback on your experience. Can I contact you for a skype/hangout/text chat/email (your preference)?

Thanks

**Comment by vvo** [comment]
Moved to #591
