### ISSUE TITLE
Widget presentation text overlapping with the 3D example

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#680]
An image is better than words here:
![cap](https://cloud.githubusercontent.com/assets/5095856/11362161/4038053a-9292-11e5-8dad-be0f382eb2ad.PNG)

Windows 10 - Firefox 44 (nightly build)
Also reproduced with Fedora - Firefox 42 (stable)

**Comment by vvo** [comment]
Seems like a firefox bug unfortunately
