### ISSUE TITLE
Deep clone the object passed to transformData

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#683]
For now, I've mostly used `transformData` to modify a specific attribute.
I think it makes more sense to pass a deep cloned version of the data object than the original one.

For instance, to make sure we're not messing with internal variables, for a price facet refinement, we'd have to do:

```js
{
  transformData: function(data) {
    return {
      isRefined: data.isRefined,
      name: '$' + data.name,
      count: data.count,
      etc.
    }
  }
}
```

or

```js
{
  transformData: function(data) {
    data = whatevercloningmethodwewant(data);
    data.name = '$' + data.name;
    return data;
  }
}
```

I'd like to easily be able to do:
```js
{
  transformData: function(data) {
    data.name = '$' + data.name;
    return data;
  }
}
```

It would be less error prone, and probably not resource consuming since we're using the original data if `transformData` hasn't been specified.
I'm opening this issue since I've been affected in my `currentRefinedValues` implementation, I modified the `name` value for the display and ended up screwing up my `onClick` handler which was using it.

**Comment by vvo** [comment]
Indeed every data we pass to user functions should be cloned. An easy and performant cloning mechanism is JSON.parse(JSON.stringify()).

Spots:
- https://github.com/algolia/instantsearch.js/blob/6ce160b7505a21fd16b3207b8f37b658c2e120b5/src/components/Template.js#L100
- https://github.com/algolia/instantsearch.js/blob/6ce160b7505a21fd16b3207b8f37b658c2e120b5/src/components/Template.js#L71
- https://github.com/algolia/instantsearch.js/blob/6ce160b7505a21fd16b3207b8f37b658c2e120b5/src/components/Template.js#L75

**Comment by vvo** [comment]
> I'm opening this issue since I've been affected in my currentRefinedValues implementation, I modified the name value for the display and ended up screwing up my onClick handler which was using it.

Even if we should clone data, I wonder how this can happen

**Comment by Jerskouille** [comment]
Really simplified:
```
function clearRefinement(helper, refinement) {
  helper.clearRefinement(refinement.attributeName, refinement.name);
}
let refinement = { name: 'val' };
let handleClick = clearRefinement.bind(helper, refinement);
<Template onClick={handleClick} templateData={refinement} transformData={(data) => { data.name = 'notval'; return data; }}
```

**Comment by Jerskouille** [comment]
Here is my diff for this:

```
@@ -1,6 +1,7 @@
 let React = require('react');
 let mapValues = require('lodash/object/mapValues');
 let curry = require('lodash/function/curry');
+let cloneDeep = require('lodash/lang/cloneDeep');
 let hogan = require('hogan.js');

 class Template extends React.Component {
@@ -66,17 +67,19 @@ function transformData(fn, templateKey, originalData) {
     return originalData;
   }

+  let clonedData = cloneDeep(originalData);
+
   let data;
   if (typeof fn === 'function') {
-    data = fn(originalData);
+    data = fn(clonedData);
   } else if (typeof fn === 'object') {
     // ex: transformData: {hit, empty}
     if (fn[templateKey]) {
-      data = fn[templateKey](originalData);
+      data = fn[templateKey](clonedData);
     } else {
       // if the templateKey doesn't exist, just use the
       // original data
-      data = originalData;
+      data = clonedData;
     }
   } else {
     throw new Error('`transformData` must be a function or an object');
```

**Comment by Jerskouille** [comment]
Here is my diff for this:
```
@@ -1,6 +1,7 @@
 let React = require('react');
 let mapValues = require('lodash/object/mapValues');
 let curry = require('lodash/function/curry');
+let cloneDeep = require('lodash/lang/cloneDeep');
 let hogan = require('hogan.js');

 class Template extends React.Component {
@@ -66,13 +67,15 @@ function transformData(fn, templateKey, originalData) {
     return originalData;
   }

+  let clonedData = cloneDeep(originalData);
+
   let data;
   if (typeof fn === 'function') {
-    data = fn(originalData);
+    data = fn(clonedData);
   } else if (typeof fn === 'object') {
     // ex: transformData: {hit, empty}
     if (fn[templateKey]) {
-      data = fn[templateKey](originalData);
+      data = fn[templateKey](clonedData);
     } else {
       // if the templateKey doesn't exist, just use the
       // original data
``

**Comment by vvo** [comment]
> function clearRefinement(helper, refinement) {
>   helper.clearRefinement(refinement.attributeName, refinement.name);
> }
> let refinement = { name: 'val' };
> let handleClick = clearRefinement.bind(helper, refinement);

You can get out of any cloning issue here by directly passing the right value instead of an object reference. We do this in some components/widgets I believe.

**Comment by Jerskouille** [comment]
True, but should we really have to worry about this?

**Comment by vvo** [comment]
Let's see once you submit the PR, it will be easier to discuss there indeed. The issue you brought still need to be taken care of that's for sure

**Comment by redox** [comment]
:+1: @Jerskouille
