### ISSUE TITLE
rangeSlider: hide the tooltip when it's equal to upper/lower bound

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#694]
It doesn't make sense to display the tooltip when it's on the min/max:

![screen shot 2015-11-26 at 11 35 38](https://cloud.githubusercontent.com/assets/29529/11420970/eb35e772-9431-11e5-812f-2ac41fe85c7f.png)

**Comment by redox** [comment]
cc @maxiloc

**Comment by vvo** [comment]
moved to #1069
