### ISSUE TITLE
Looks like autoprefixer is not applied

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#696]
![image](https://cloud.githubusercontent.com/assets/976175/11448861/bbea53c2-9562-11e5-8722-7aa61741f16a.png)

I removed my keyframe mixin

**Comment by vvo** [comment]
> I removed my keyframe mixin

You mean we removed something and the icons are not showing up anymore? And that we now need to run autoprefixer on the docs css? If so I will add it.

**Comment by Shipow** [comment]
I had a mixin to write vendor prefix for every keyframe and I removed it because I thought we where using autoprefixer. And obviously we are not.

**Comment by redox** [comment]
Hmmm, weird because we do use autoprefixer https://github.com/algolia/instantsearch.js/blob/master/scripts/build.sh#L32

**Comment by redox** [comment]
Oh wait, we use autoprefixer for the example CSS but not for the main website's one. On it.

**Comment by Shipow** [comment]
My keyframes declarations was wrong. Fixed in [#704](https://github.com/algolia/instantsearch.js/pull/704)
