### ISSUE TITLE
instantSearch() or instantsearch()

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#7]
current global export is `instantsearch`, should we go `instantSearch`?

**Comment by pixelastic** [comment]
I'll go with the more readable `instantSearch`

**Comment by dethi** [comment]
For a module name, I prefer all lower case, so `instantsearch`.

**Comment by vvo** [comment]
> For a module name, I prefer all lower case, so instantsearch.

The module in npm will be named `instantsearch.js` but we have to decide what's the name of the exports in window when loaded with a `<script>` (window.algoliasearch or window.algoliaSearch)

**Comment by dethi** [comment]
Yes, and I prefer `instantsearch`, like we use `algoliasearch` and not `algoliaSearch`.

**Comment by bobylito** [comment]
:+1: for instantsearch as the module and global name for me

**Comment by vvo** [comment]
Ok I was for instantSearch but since we already have algoliasearch then we should use instantsearch. Thanks. @pixelastic are you ok?

**Comment by pixelastic** [comment]
Yep, better stay consistent.

**Comment by redox** [comment]
:+1:
