### ISSUE TITLE
Store the major (X.x.x) instantsearch version in the url to handle url backward compat 

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#70]
Since we are going to have a urlSync widget that will generate URLS in some way with a defined format.

Since those urls will endup being referenced by google at some point.

We should store the major version token of the instantsearch.js library in the url so that we always now how to serialize/deserialize even when we build change the format at some point.

It will allow us to update the url serialization without breaking any existing link.

It's an edge case, yes. But storing v=1 in the url in not a big deal

**Comment by pixelastic** [comment]
OK for doing it, this is not much data to add. But I wonder how feasible the old url / new url reconciliation will actually be. But at least with this data we'll have a starting point.

**Comment by vvo** [comment]
> But I wonder how feasible the old url / new url reconciliation will actually be

A big pile of spaghetti code and ifs at first I guess. :dancer:

**Comment by vvo** [comment]
(with tests)
