### ISSUE TITLE
Tourism Git is down

### ISSUE THREAD

**Issue by kaona** [algolia/instantsearch.js#702]
On the examples page: https://community.algolia.com/instantsearch.js/examples/ the tourism and all other example gits at the following link are down. https://community.algolia.com/instantsearch.js/examples/tourism/

Any ideas on where it can be found?

Thank you.

**Comment by vvo** [comment]
Sorry about it, fixing this right now

**Comment by vvo** [comment]
Should be fixed now, let us know! 
![2015-11-30-162349_696x333_scrot](https://cloud.githubusercontent.com/assets/123822/11475685/e29f4266-977e-11e5-9c65-2ea9be630f40.png)

**Comment by kaona** [comment]
Affirmative. Thank you.
