### ISSUE TITLE
Customize hits template

### ISSUE THREAD

**Issue by proudlygeek** [algolia/instantsearch.js#707]
Hi,

The current hits widgets only allows to provide a template per hit, I would like to provide a global template so that I can add any HTML attribute I need.

It could make sense to make it overridable with something like:

```javascript
search.addWidget(instantsearch.widgets.hits({
   container: '#hits',
   templates: {
        empty: '<div class="text-center">No results found matching <strong>{{query}}</strong>.</div>',
        items: '<div class="hits">{{#hits}}Hello {{hit.name}}{{/hits}}</div>'
   }
});
```

What do you think about it?

**Comment by redox** [comment]
@proudlygeek Not sure I'm following; what would be the difference with the current version?

```html
<div id="hits" class="hits"></div>'
<script>
search.addWidget(instantsearch.widgets.hits({
   container: '#hits',
   templates: {
        empty: '<div class="text-center">No results found matching <strong>{{query}}</strong>.</div>',
        item: 'Hello {{hit.name}}'
   }
});
</script>
```

**Comment by vvo** [comment]
@redox The goal is for the user to iterate on the hits in a hogan template rather than being only able to provide an item template.

**Comment by bobylito** [comment]
Both ways are acceptable, and have tradeoffs. What is your use case @proudlygeek ?

**Comment by proudlygeek** [comment]
@bobylito @redox currently is impossible to use external plugins which relies on *data-* attributes for configuration. An example is [Masonry][1] (see also issue #736).

Right now the only *clean* way to achieve this is to write a custom widgets which basically wraps the hits one. I think it could make sense to add an esclusive ```items``` template property to override the inner react map.

[1]: http://masonry.desandro.com/

**Comment by pixelastic** [comment]
I think the idea fits the `hits` widget scope. This is an advanced option because users will then have to handle everything themselves, but I see how this can be useful.

Regarding Masonry, I'm not sure a jQuery plugin that reorders DOM elements (if that's what it's doing) will play well with React, though.

**Comment by proudlygeek** [comment]
@pixelastic I think the point here is to make Masonry or similar reorder our React components on the DOM. It shouldn't make any assumptions on the underlying technology stack. It should treat them as black boxes.

**Comment by pixelastic** [comment]
@proudlygeek yep, I agree, but React can get really picky with what other libraries are doing with its DOM. But still, I agree that we should to make it work with Masonry. We can tackle that together after the holydays if you'd like.

**Comment by bobylito** [comment]
As seen with #748 we may want to use tables, which is impossible right now and would be doable with the `hits` template property.

**Comment by vvo** [comment]
Moved to #771
