### ISSUE TITLE
PoweredBy and utmz

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#711]
To be able to easily track where the users are coming from when clicking PoweredBy link, we should:

- default poweredBy link should go to: https://www.algolia.com/?utm_source=instantsearch.js&utm_medium=website&utm_content=$location.hostname&utm_campaign=poweredby (where $location.hostname is the current domain name)
- provide an option to configure the powered by link to go anywhere we want (configure the full href)

**Comment by redox** [comment]
:+1:

**Comment by Jerskouille** [comment]
Could we do it through a redirect as we're doing with https://www.algolia.com/console ? I'd be really less enclined to click a link where I see utm parameters.

**Comment by vvo** [comment]
> Could we do it through a redirect as we're doing with https://www.algolia.com/console ?

It would require us to create redirects for each poweredBy implem, why won't you be good with clicking an utm link?

**Comment by Jerskouille** [comment]
No, it just requires us to create a route that will check the referer.

**Comment by vvo** [comment]
> The fact that I'll be the product of a company I don't know yet (or I wouldn't click the link).

Yes but you will be in the end even with a redirect, so hiding it might make it look worse?

> Furthermore, as a webmaster, I'd be more willing to accept to have a link to another website on my website without marketing content in it.

I am not sure this has been an issue with our previous poweredBy implems, you got free search, you accept a logo, then a link yes that's the "contract" we can force people to without any friction I think

**Comment by Jerskouille** [comment]
> Yes but you will be in the end even with a redirect, so hiding it might make it look worse?

I agree on this. I remember it didn't shock me when I first clicked http://algolia.com/console (although I do remember it).
About the contract, why not.

**Comment by pixelastic** [comment]
I agree with @Jerskouille. I always check the url of the logo links I click. If I see some marketing elements in it, I might avoid clicking it, or copy-pasting the like, remove the tracking and going on.

I agree that in the end this is the exact same thing, but I'd rather we go the `/console` (or any other route) way, and funnel the analytics through the referer. If we can do it back-end, on our side, this is better than doing it client-side.

**Comment by vvo** [comment]
Really not seeing this as an issue, we should do the simplest thing for now by being transparent to everyone and not hiding the fact that yes we are tracking people: utmz etc..

**Comment by pixelastic** [comment]
I'm also thinking about that :)
![image](https://cloud.githubusercontent.com/assets/283419/11769726/11787ac0-a1ee-11e5-9903-85d07d60f01a.png)

**Comment by vvo** [comment]
implemented the default poweredBy link computation, not passing options. Not worth it
