### ISSUE TITLE
API Proposal: `onHit` callback in hits widget

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#72]
We need to be able to reformat the hit before it's passed to the template. One use case is when you have your whole content being splitted in multiple parts (h1, h2, .. wordpress blog post) and you want to provide your user a clean data structure for his templates.

Example: https://github.com/algolia/algoliasearch-wordpress/blob/2e7742d7c631ac402415e7fcb1488eb6690db1bd/templates/default/template.js#L223

Then you need something like `onHit` to be able to reformat (map) every hit in another form.

So:

```js
search.addWidget(
  instantsearch.widgets.hits({
    container: '#hits',
    templates: {
      empty: require('./templates/no-results.html'),
      hit: require('./templates/hit.html')
    },
    onHit: function(hit) {
      return anotherObject;
    }
  })
);
```

Since templates can be string or functions we should be good but then what if you want to use our hogan.js along with just reformating the hit before it's passed to the

**Comment by pixelastic** [comment]
Agreed with the feature, but not with the name. `onHit` hints as an event (like `.on('results')`), I would go for something that hints at a hook or callback. Maybe `beforeRender` or `transformHit`.

**Comment by vvo** [comment]
Maybe `transform` or `transformData` alone would be good? So that we can reuse it for other widgets?

Dunno if `transformData` is really native-compliant :D

**Comment by pixelastic** [comment]
I would expect `transformData` to pass the whole API response, `transformHits` to only pass the `.hits` part and `transformHit` to pass me only one hit. It really depend on what we want to expose (I personnaly prefer `transformHit` here).

**Comment by vvo** [comment]
Ok so `transformHit` looks good but what about other widgets? `transformFacetValue` `transformData` (stats) `transformXX`?

I like `transformHit` only worried that we will then need a lot of other tokens.

Maybe `transformData` (full data, stats, toggle..) and `transformItems` (any list-based)?

**Comment by pixelastic** [comment]
I think we only need it for the `hits` widget today. Maybe just wait for the need on other widgets before merging?

**Comment by vvo** [comment]
Allright

**Comment by vvo** [comment]
So to tackle the "update the data" case. What we could do is this:

```js
template: function(data, hoganTemplateFn) {
  var newData = data.map()..
  return hoganTemplateFn(data)
}
```

So the "trick" is to send the default hogan templating function when we get a function as a template. This way the user can reformat the data and still use the default hogan templating system.

Thoughts @algolia/javascript ?

**Comment by redox** [comment]
Works for me :+1:  (I would not mention `hogan` in the parameter name however)

**Comment by vvo** [comment]
> (I would not mention hogan in the parameter name however)

Well but it will always be a hogan function here, I mean you need to pass a hogan template (or a mustache one).

**Comment by redox** [comment]
> Well but it will always be a hogan function here, I mean you need to pass a hogan template (or a mustache one).

Yes, rather `mustache` than `hogan` then :)

**Comment by Jerskouille** [comment]
@pixelastic 

> Maybe just wait for the need on other widgets before merging?

I have one! Right now, I'm using an optional  `displayFunction` for my facets. It is actually only used in one case of weirdly formatted data : price ranges, but could be needed with other types of attributes.

I'm not found of modifying the data within the `template` function, because to me we should just expect a template to be returned here.

On the other hand, I really like the `transformData` idea of a callback to call just before the template rendering. We're always passing an object when rendering a Hogan template, so we would always have the same prototype.

To me, this:
```js
{
  transformData: function (hit) {
    return { name: hit.first_name + ' ' + hit.last_name };
  },
  template: '{{ name }}'
}
```
makes more sense than this:
```js
{
  template: function(hit, hoganTemplateFn) {
    return hoganTemplateFn({ name: hit.first_name + ' ' + hit.last_name; });
  }
}
```

**Comment by vvo** [comment]
> To me, this:
> 
> {
>   transformData: function (hit) {
>     return { name: hit.first_name + ' ' + hit.last_name };
>   },
>   template: '{{ name }}'
> }
> makes more sense than this:

I like transformData too :+1:

**Comment by pixelastic** [comment]
Yes, I like the transformData too. @Jerskouille care to submit an issue with API proposal?

**Comment by vvo** [comment]
supersed by #116
