### ISSUE TITLE
search-box is not updated when input has focus and back button pressed

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#729]
![bug](https://cloud.githubusercontent.com/assets/123822/11691037/92255d1c-9e99-11e5-83e0-b088396feb22.gif)

This is not a new bug since 1.0.0, it was already here. I guess it depends on the browser/OS but for me clicking on back button does not focus out the input. Thus it is not updated.

I think we need to have a way to know when the query was updated from the outside rather than from the input itself.

Right now we use [helper.on('change')](https://github.com/algolia/instantsearch.js/blob/fix/update-search-box-on-helper-state/src/widgets/search-box/search-box.js#L163-L166) and then see if the input is focused.

But there are cases where the input is focused and the query might change still:
- custom widget modifying the query based on a timer for example (weird but ok)
- back button while the input is focused and stay focused
- back navigation shortcut while focused (fails)

I wonder how could we change the searchbox so that we really update it and distinguish when the event comes from the outside.

I feel this is something REACT solved for instance :D

**Comment by pixelastic** [comment]
Should emitting a `urlchanged` event solve it?

**Comment by vvo** [comment]
> Should emitting a urlchanged event solve it?

No I think we can solve it if we solve #730, then using some naive flag state memorizing if the render call was due to a search from the input should be sufficient
