### ISSUE TITLE
API proposal: pagination widget should scroll to top by default

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#73]
In most situations you want to scroll to top when a pagination element is clicked.

To disable it:
```js
search.addWidget(
  instantsearch.widgets.pagination({
    container: '#pagination',
    cssClass: 'pagination',
    maxPages: 20,
    scrollTo: '#top'
  })
);
```

We will later on need to be able to get an event when a pagination element is clicked so that the user can scroll to a specific element (like no to top but a little below the header).

For now it's not necessary to add this.

**Comment by redox** [comment]
That's a boolean that we'll need in a lot of widgets I think. Maybe we could think about how to share the behavior across multiple of them now?

**Comment by bobylito** [comment]
First thing first :) Now in the pagination, then everywhere !! (and conquer the world)

**Comment by vvo** [comment]
I am still unsure (even if that's we do today) that ALWAYS scrolling to top is better. It really depends on the website height and the widgets we have.

Slider should not automatically scroll to top.

refinementList should not automatically scroll to top because I may want to select "red" and "blue" checkboxes. While the behavior will make me angry because it did something I did not want.

So only for the pagination should be ok for now.

We still can have a proposal of an `.on('refine')` event allowing users to do anything they want.

**Comment by pixelastic** [comment]
I'm not sure this is a safe default. I don't always want to scroll to top when paginating. Maybe the page header is tall, and I've already correctly scrolled my page to only have the hits in my view port. Scrolling to top will break that.

I'd be more in favor of a more generic `.on('refine')` to let users do what they want

**Comment by vvo** [comment]
@pixelastic As for the refine: #79 
As for default to scrollToTop in here: really unsure too. Let's do some integrations

**Comment by pixelastic** [comment]
> As for default to scrollToTop in here: really unsure too. Let's do some integrations

Moving to `backlog` milestone, then.

**Comment by vvo** [comment]
Ok I need this for instant search demo now :)

**Comment by maxiloc** [comment]
Currently doing the implementation on Magento.
It seems it affects not only the pagination, when I click on a facet it scrolls to top.

**Comment by maxiloc** [comment]
Disabling it in pagination works
