### ISSUE TITLE
render calls order is bad when urlSync is used

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#730]
I managed to break the render calls result order.

Using the standard dev app on develop, by typing "mp3" (fast), you can manage to have results for the query "mp".

This is linked to the url-sync feature since without it it works well.

What I did is add a "render" method to the search box widget and console.log inside it. Render calls and the query are bad given the current search box value.

It seems the url sync is re-triggering a search somewhere?

Any idea welcomed, this is linked with #729 because a naive approach with flags to solve #729 can't work if the render call order is not good.

![bug2](https://cloud.githubusercontent.com/assets/123822/11692253/f0e97950-9e9e-11e5-819a-5ea0ec826bf6.gif)

**Comment by bobylito** [comment]
Seems related, but could be deeper as well. Need to figure this one out.

**Comment by pixelastic** [comment]
Hmm, yes, bad bug indeed.
