### ISSUE TITLE
Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

### ISSUE THREAD

**Issue by ricktbaker** [algolia/instantsearch.js#731]
I've disabled all of our other javascript, so we are just using the instantsearch.js code as in the examples.  No matter what I do (search, click a page, etc) I am always getting this error.    This error is coming from the invariant.js script.   Unsure if this is just a configuration issue or what.   Just trying to do a pretty basic setup with a search box, hits container, and pagination.

Should mention that the initial render works fine, it's populating the first page of results as it should.  Just can't do anything from there.

**Comment by vvo** [comment]
Hi @ricktbaker are you able to share with us a setup where we can see the issue?

**Comment by ricktbaker** [comment]
Unfortunately not at the moment as it's in our private dev environment.    But I will see if I can get it on a public server to share.

**Comment by vvo** [comment]
Can you give me some more details about your setup:
- are you using browserify or webpack?
- what is the version of instantsearch.js (either from your node_modules/instantsearch.js or instantsearch.version in window)

**Comment by vvo** [comment]
This may be related: http://stackoverflow.com/questions/29586928/react-minified-exception-occurred

**Comment by ricktbaker** [comment]
No on browserify and webpack:

Versions, just copying direct from the algolia website documentation:

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.css">
    <script src="//cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.js"></script>

**Comment by ricktbaker** [comment]
Will take a look at that stackoverflow.   Thanks!

**Comment by vvo** [comment]
If you are able to provide us an [ngrok](https://ngrok.com/) url for us to see your issue (via support maybe: support@algolia.com) it would be good so that we can see the issue

**Comment by ricktbaker** [comment]
Ok, if I can't get it resolved here in a bit, then I'll go that route and send to support.  Thanks again.

**Comment by ricktbaker** [comment]
Just sent an email with a fwd to my local dev.

**Comment by vvo** [comment]
thanks, received, now investigatin

**Comment by vvo** [comment]
This issue was due to a missing `</div>` in a template. For reference when using React's dangerouslySetInnerHTML, the html should we well formed: https://facebook.github.io/react/tips/dangerously-set-inner-html.html

Thanks!
