### ISSUE TITLE
Add a optional cross on the searchBox

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#735]
![mthgdbsoen](https://cloud.githubusercontent.com/assets/1689007/11787187/b2a3bf58-a28a-11e5-9ff2-83cbf5e58b1d.gif)

**Comment by vvo** [comment]
:+1: * :100:

**Comment by pixelastic** [comment]
Yep, agreed this could be really nice

**Comment by vvo** [comment]
This is part of the searchbox redesign for instantsearch future

**Comment by vvo** [comment]
The searchbox will follow http://shipow.github.io/searchbox/ in V2, closing
