### ISSUE TITLE
Possible to add custom data attribute & ID in hits template root element?

### ISSUE THREAD

**Issue by jthcc** [algolia/instantsearch.js#736]
Hello,

I'd like to put search results into a [Salvattore Masonry Grid](http://salvattore.com/) , but am having trouble getting the "data-columns" attribute & element ID added to the "ais-hits" root container. 

Currently I'm getting:
```html
<div id="hits-container">
    <div class="ais-hits">
        <div class="ais-hits--item">ITEM CONTENT<div>
    </div>
</div>
```

What I need to acheive is:
```html
<div id="hits-container">
    <div id="itemGrid" class="ais-hits" data-colums>
        <div class="ais-hits--item">ITEM CONTENT<div>
    </div>
</div>
```

Is this possible?

Thanks kindly!

**Comment by vvo** [comment]
@proudlygeek I think you did it also? Can you share us the way you did?

**Comment by vvo** [comment]
Hi @jthcc we currently only supports giving a template per hits.

We are thinking about giving the users the possibility to provide their own full hits template (so you will have to iterate yourself the hits in the template).

We are not sure right now this would be the best solution.

In the meantime what you can do is create a custom widget:

```js
var myHitsWidget = {
  _container: $('#myHits'),
  getConfiguration: function() {
    return {
      hitsPerPage: 50
    }
  },
  init: function() {
    // if you need some jQuery code here, do it
  },
  render: function(args) {
    var out = '';
    args.results.hits.forEach(function(hit) {
      out += '...'; // do whatever you want here, any html structure
    });
    this._container.html(html);
  }
};

search.addWidget(myHitsWidget);
```

**Comment by vvo** [comment]
moved to #771
