### ISSUE TITLE
Use of active class and templates

### ISSUE THREAD

**Issue by reinaris** [algolia/instantsearch.js#737]
In the example I see a widget with an active class defined but the widget also uses a custom template, see:
https://github.com/algolia/instantsearch.js/blob/master/docs/examples/e-commerce/search.js#L100

I tested this and the template is overruling the active class (see https://github.com/algolia/instantsearch.js/blob/master/docs/examples/e-commerce/search.js#L51).
I think this is the right behaviour, but maybe clean up the example so it is more clear which active class is working.

Let me know, I would love the send in a PR.

**Comment by vvo** [comment]
Ah yes indeed we are defining an active class that in the end is overriden by a custom template.

Can you send a PR?

**Comment by reinaris** [comment]
@vvo would love too! Give me a sec :)

**Comment by reinaris** [comment]
Here you go! https://github.com/algolia/instantsearch.js/pull/741
