### ISSUE TITLE
Filtering some facet values

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#739]
While displaying my facets, I would like to filter out some of them without removing them from my index. I was thinking about something like:

```js
search.addWidget(
  instantsearch.widgets.refinementList({
    container: '#brands',
    attributeName: 'brand',
    transformData: function(data) {
      if (data.value === 'uggly') return false;
      // [...]
      return data;
    }
  })
);
```

or

```js
search.addWidget(
  instantsearch.widgets.refinementList({
    container: '#brands',
    attributeName: 'brand',
    filterFacets: function(facets) {
      return filter(facets, function (f) { return f.value !== 'uggly' });
    }
  })
);
```

If well documented, I don't think it will conflict with the `limit` attribute.

What do you think?

**Comment by vvo** [comment]
filterFacets seems good, more obvious

**Comment by vvo** [comment]
filterData might be better since we already have transformatData (which is a "mapData" in the end).

**Comment by vvo** [comment]
Ultimately it would be easier to have a "changeData" Where you receive the whole facetValues and you must return a new complete facetValues. So that you can do both filter, reduce, map, anything you want, just send us the results.

**Comment by redox** [comment]
> filterData might be better since we already have transformatData (which is a "mapData" in the end).

It was my initial proposal but since I wanted it to be applied on **all** facets and not for **each** facet, it was kind of confusing.

**Comment by vvo** [comment]
> It was my initial proposal but since I wanted it to be applied on all facets and not for each facet, it was kind of confusing.

Ohhh I did not see it. Maybe we could right now try to find a good name where we are able to reformat the whole data (and thus handle both map, filter, reduce..)

**Comment by vvo** [comment]
We are most probably going for templates being only functions, thus the need to reformat the whole data can be handled in the templating system. Then it will be our job to educate on how to keep using mustache while being able to reformat the data.

I will revisit this one once settled on the template situation.

**Comment by timkelty** [comment]
Interested in this too…

@vvo is there an example of this somewhere?

**Comment by Haroenv** [comment]
Hey @timkelty, this is a very old issue, could you make a new one describing your issue? You can use every template as a function, and there leave out any values you need

**Comment by timkelty** [comment]
@Haroenv My use-case was a bit more involved (more than just filtering, but similar requirements), so I made an issue: https://github.com/algolia/instantsearch.js/issues/2283
