### ISSUE TITLE
Ability to enforce query parameters

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#740]
When doing a search on a subset of your dataset, the filter you used will show up in the currentRefinedValues and can show up in a refinement list.

This issue has no quick win : 
- We could add an `exclude` or `filterData` to every widget. This would work, but adds yet another type of needed logic to every widget and I'm definitely against it. However it remains a considerable option.
- We could add some logic to the helper that would allow to flag some filters as being `enforced`, which would mean that we wouldn't list them in the facetValues it sends back to the widgets.
- Or we could do a simple thing, which requires adding some size to the JS client build (but if we go with https://github.com/algolia/algoliasearch-client-js/issues/179 , this is no issue) : add the `generateSecuredAPIKey` to the client, expose a `privateSearchParameters` to `instantsearch`, and generate a securedAPIKey that would contain these parameters in itself.

cc @redox .

And @vvo , we already have multiple use cases where this would be needed.
- In Magento, in a specific category, you don't want your users to be able to unrefine
- In Magento, @maxiloc is using something like `visibility: true`
- In Shopify, I have already two users using us on categories pages using tags.

**Comment by vvo** [comment]
Can you precise what you call "when doing a search on a subset..?" And maybe show a screenshot of what is shown thx

**Comment by vvo** [comment]
> add the generateSecuredAPIKey

Careful this is a node.js only method

**Comment by Jerskouille** [comment]
> Can you precise what you call "when doing a search on a subset..?"
I'm doing it with the three examples for which I specifically tagged you.
A screenshot wouldn't help.
In a shop, in the *Shoes* page, you only want to list `Shoes` results, not anything else. You hence don't want the user to be able to remove the *Shoes*.
```js
var search = instantsearch(/* ... */);
// ...
search.addWidget({
  init: ({helper}) => { helper.toggleRefinement('category', 'Shoes') };
});
// Now, currentRefinedValues will list Shoes when we don't want it listed
// Now, a refinementList on category will list Shoes when we don't want it listed
// Now, if you click a clearAll widget, it will remove Shoes when we don't want it to be removed
```

> > add the generateSecuredAPIKey
> Careful this is a node.js only method

Which is why I said "add".

Food of thought after thinking about this. The `securedAPIKey` only solves the `currentRefinedValues` and the `clearAll` issue. However, for `refinementList` the `Shoes` option will be listed, and can be toggled endlessly without changing anything. So in the end, this isn't a good solution.

**Comment by vvo** [comment]
> Which is why I said "add".

Yes sorry I was not precise enough. This is a method using crypto features: you can have it client side but it will add A LOT of code and possibly unsafe code because frontend crypto libraries are not based on native system features.

But more importantly to generate the secured API key you need an admin key you do not want to expose on the frontend (If this is what you had in mind).

**Comment by vvo** [comment]
To sump up this issue is about: "I have a default refinement I don't want the users to be able to remove or see in any widget". Is that it?

**Comment by vvo** [comment]
I currently see the filterData option as the easiest way to do it right now,

> We could add some logic to the helper that would allow to flag some filters as being enforced, which would mean that we wouldn't list them in the facetValues it sends back to the widgets.

Could you try to imagine how such API would look like in the helper? And what would be the effect of it on the dataset sent back by the helper (results)?

**Comment by Jerskouille** [comment]
> But more importantly to generate the secured API key you need an admin key you do not want to expose on the frontend (If this is what you had in mind). 

No, we wouldn't have been using it with the "secured" sense of the secured API key, but just for its capability to embed and hide query parameters.

> To sump up this issue is about: "I have a default refinement I don't want the users to be able to remove or see in any widget". Is that it?

:+1: 

> Could you try to imagine how such API would look like in the helper? And what would be the effect of it on the dataset sent back by the helper (results)?

I don't know. I'm not doing an API proposal, just suggesting ideas.

**Comment by pixelastic** [comment]
I like the idea of being able to define some filters as being impossible to change. It's more than `defaultFilters`, it's more like `defaultAndUnalterableFilters`. They won't be removed when we `clearFilter` and will not be returned by the helper when we play with the filter API.

But we have to be careful about what it implies on the helper API and see if it makes sense in every method. If it makes the helper too complex (to understand and to code), I'm ok with:

- "Manually" fixing it in a transformData whenever we need it. But this will result in a lot of boilerplate code copy-pasted in several implementations
- Fixing it at the UI level in instantsearch.js, ie. not displaying the facets in the render part of the widgets, but still letting user remove it programmatically with the helper API.

**Comment by vvo** [comment]
One thing I want to clarify: Let's say you want "color: 'blue'" to be a default filter then I guess not only you do not want "blue" to be shown in the refinement list but you do not want to show the whole color refinement list, since it already has a default value?

I guess it depends on the use case but I fail to imagine a use case where you have a default value for a filter and still want to display other filtering options for the same facet.

The only place where I can think it makes sense is hierarchical facet (but already handled by the "rootPath" option which allows you to preselect a root path).

I would let the user do it by providing him the necessary tool: filterData which will allow him to remove some facet values from a refinement list IF he really need both a default filter and still showing the refinement list.

Unless someone can come up of a good helper implementation + instantsearch.js, filterData is the easiest way for now.

**Comment by maxiloc** [comment]
> The only place where I can think it makes sense is hierarchical facet (but already handled by the "rootPath" option which allows you to preselect a root path).

Except for the currentRefinements widget that is allowing to remove rootPath refinement it for now

**Comment by Jerskouille** [comment]
@vvo 

> but you do not want to show the whole color refinement list, since it already has a default value
> [...]
>  I fail to imagine a use case where you have a default value for a filter and still want to display other filtering options for the same facet
Well, no, for example when using tags to restrict the search. Ability to filter on associated tags still makes sense.
If you don't want to display the refinement list, it's easy, just don't call `addWidget` with it.

> The only place where I can think it makes sense is hierarchical facet (but already handled by the "rootPath" option which allows you to preselect a root path).
You actually also want to hide the `rootPath` because it will show up in `currentRefinedValues` otherwise.

> Unless someone can come up of a good helper implementation + instantsearch.js, filterData is the easiest way for now.
Alright, but I'm really worried that we add yet another thing to ALL facetting widgets. Our library becomes less and less extendable with that.

**Comment by vvo** [comment]
> Except for the currentRefinements widget that is allowing to remove rootPath refinement it for now

Yes. Could this be handled inside the currentRefinements widget by providing either a whitelist or a blacklist of refinement names to show? (Or just a filter function)

**Comment by Jerskouille** [comment]
> Yes. Could this be handled inside the currentRefinements widget by providing either a whitelist or a blacklist of refinement names to show? (Or just a filter function) 

Yes it can, but then it falls under my previous concern. I would be way happier to have a way to exclude it from the `getRefinements` instead.

**Comment by vvo** [comment]
> Well, no, for example when using tags to restrict the search. Ability to filter on associated tags still makes sense.

Yep, so in this case "filterData" can work, you could put your default value on top of the list in a "disabled" state so that user see that it's automatically enabled (depend on use case/ux)

**Comment by Jerskouille** [comment]
> Yep, so in this case "filterData" can work, you could put your default value on top of the list in a "disabled" state so that user see that it's automatically enabled (depend on use case/ux)

Indeed

**Comment by bobylito** [comment]
Yeah! I'm late to the party, but this issue got me thinking. I've added an issue in the helper that could help us here https://github.com/algolia/algoliasearch-helper-js/issues/273 (tldr: it fixes a reset point to which all values would go back, if we "clear" them). If we add the capability to clearly express which field should not change, we could have a headless widget that does the constant configuration. The API would look like : 

```js
var instantsearch = instantsearch();
instantsearch.addWidget(FixConfigWidget({
  constants: ['categories',  'tags']
}))
```

Do you think that could help here?

**Comment by Shipow** [comment]
up /o\

**Comment by vvo** [comment]
filterData is the way to go here, it will allow you to completely reformat the data passed to the templates

**Comment by bobylito** [comment]
@vvo the problem is not visual, but on the query side. If we clear all then the filter is not there which means that the hits won't be the one expected.

What I suggested to @Shipow is to implement in its widget with default parameters to bind the helper `change` event, and add back the filter if it was cleared.

**Comment by vvo** [comment]
I think I need to see an acutal UX implementation to really understand the requirement

**Comment by pixelastic** [comment]
You can have a look at [searchstone](http://searchstone.io/). On the top right corner you can select the language (which is a facet). All cards are in the same index, but filtered on their `lang` attribute.

If you start adding new filters, then "clear all", you will no longer have a filtering on the language, and all cards of all languages will be displayed.

What would be nice would be a way to have "protected filters" that are not removed when we "clear all".

**Comment by vvo** [comment]
Ok so this looks more of a clear all API need no? A way to give a list of attributes to clear all that won't be cleared.

**Comment by pixelastic** [comment]
I think it's higher level than that, not only clear all.

For example, you might want to define a default filter on the page to show only the playable cards, so you add the facet `type:playable`. But you still allow users to sort on other card attributes like `type:minion`, `type:spell`, `type:whatever`. And you do not want the `type:playable` facet to be displayed in your refinement list.

The filters defined this way will always be part of the query made to the API, but will not be displayed in the UI. Their are part of the query, on the same level as the APPID, the API key or the index name. You cannot alter them from the UI, and you should not even see them from the UI.

So when you `clearAll`, they still stay. When you display a list of active facets for this attribute, they do not show.

**Comment by Shipow** [comment]
I think it's a top level "init" widget where you could set the configuration and precise attributes that will be used by default and if they are read only / visible.

**Comment by vvo** [comment]
> And you do not want the type:playable facet to be displayed in your refinement list.

For that, it's only a matter of adding the right flag to the facet value you want to be hidden in a transformData function no?

**Comment by Jerskouille** [comment]
> For that, it's only a matter of adding the right flag to the facet value you want to be hidden in a transformData function no?

This is a weird hack which will have the inconvenient of removing X facet values for this specific facet. Plus, this will still be added to the markup, and you have to use a custom template that will add `display: none` to this specific facet. A lot of pain involved here.

**Comment by vvo** [comment]
I agree but finding API entries for every use case is not a solution either, and we did not find one here. I am more and more up for finding the right pluggable interface and delegating advanced use cases to tutorials.

**Comment by pixelastic** [comment]
I think what @bobylito mentionned earlier about this being added to the helper would be the best solution here.

We will still need a way to pass this config to the helper from instantsearch, though. I really think this is not something that must be handled on a per-widget basis, but being in the core of the helper.

As usual, we could either give users access to the helper and let them configure this `constants` (but this requires to totally embrace the helper, document it completly, and so on). Or we could expose one more API entrypoint to instantsearch that delegates to the helper, with the added overhead of every new entrypoint we add to instantsearch...

I feel like we are pushing the limits of what can be done with a JavaScript search library. What is considered "advanced" use case today should be default basic options of the instantsearch.js of tomorow.

**Comment by vvo** [comment]
At this point we do not have any clear proposal on this being a feature of the helper.

I think we should go with a more simple approach for now, I created #1064
