### ISSUE TITLE
`npm run docs:jsdoc` fails

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#743]
I cannot run `npm run docs:jsdoc`, this fails on a weird error.

```
$ npm run docs:jsdoc


> instantsearch.js@1.2.0-beta.0 docs:jsdoc /home/tim/local/www/algolia/javascript/instantsearch.js
> babel-node ./scripts/docs/gen-widget-doc.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: /home/tim/local/www/algolia/javascript/instantsearch.js/node_modules/jsdoc-parse/node_modules/jsdoc-75lb/lib/jsdoc/src/astnode.js:214
                var key = prop.key.name;
                                  ^

TypeError: Cannot read property 'name' of undefined
```

If, in `src/lib/InstantSearch.js`, I remove line 68 (`this.searchParameters = {...searchParameters, index: indexName};`), then it works again... I have no idea what is going on here.

**Comment by vvo** [comment]
cc maybe @bobylito knows

**Comment by pixelastic** [comment]
Oh yes, makes sense. I'll update.

**Comment by vvo** [comment]
Handling this one

**Comment by pixelastic** [comment]
Thanks. I'm curious :)

**Comment by vvo** [comment]
So the real fix is here: https://github.com/jsdoc3/jsdoc/pull/1141

And waiting for https://github.com/jsdoc2md/jsdoc-to-markdown/issues/61#issuecomment-169064903 answer
