### ISSUE TITLE
Documentation: get the json result of the research for export.

### ISSUE THREAD

**Issue by clementvp** [algolia/instantsearch.js#746]
Hi,
Documentation is a bite confuse on how to get the json response of the search queries  and how to log it in the console ( for test ).
I want to extract in another format (like csv ) the entire result of my research (with some of my facets  and my slider engaged), not just the current page result.
Exemple my querie return 500 results on 50 pages with 10 hitPerPage, i want the 500 results.
Maybe TransformData on the hit widget it's a clue, but honestly i'm little lost with this.
Thx :)

**Comment by vvo** [comment]
Hi @clementvp,

If you want to do an extract of your full data to a CSV file, you should use our JavaScript client directly: https://github.com/algolia/algoliasearch-client-js

Otherwise, you could also do you own hits widgets like so:

```js
var myHitsWidget = {
  _container: $('#myHits'),
  getConfiguration: function() {
    return {
      hitsPerPage: 500
    }
  },
  init: function() {
    // if you need some jQuery code here, do it
  },
  render: function(args) {
    var out = '';
    args.results.hits.forEach(function(hit) {
      out += '...'; // do whatever you want here, any html structure
    });
    this._container.html(html);
  }
};

search.addWidget(myHitsWidget);
```

**Comment by clementvp** [comment]
Thank you for your rapid reply, i will try that ;)
