### ISSUE TITLE
BEM Mixins for element and modifier are inverted

### ISSUE THREAD

**Issue by proudlygeek** [algolia/instantsearch.js#747]
Hi guys,

It seems that the [Sass BEM][1] mixin is using the wrong BEM convention for the ```element``` and ```modifier``` mixin:

```sass
@mixin element($element) {
  &--#{$element} {
    @content
  }
}

@mixin modifier($modifier) {
  &__#{$modifier} {
    @content
  }
}
```

According to [BEM][2] it should rather be:
```sass
@mixin element($element) {
  &__#{$element} {
    @content
  }
}

@mixin modifier($modifier) {
  &--#{$modifier} {
    @content
  }
}
```

[1]: https://github.com/algolia/instantsearch.js/blame/master/src/css/_base.scss#L7-L17
[2]: http://getbem.com/naming/

**Comment by redox** [comment]
@pixelastic /o\

**Comment by vvo** [comment]
Woops. This would be a breaking change to modify them. Or we could duplicate :D

**Comment by pixelastic** [comment]
Oops...
![Sorry...](https://media.giphy.com/media/xFOc3rYIGE3aE/giphy.gif)

I don't think we can duplicate (this will be sooo strange). Let's keep that for the next breaking release :)

**Comment by vvo** [comment]
Just to be clear, this will be fixed in a 2.0.0 release "at some point"

**Comment by bobylito** [comment]
Actually if you read the broader litterature, the convention is Block Element Modifier but then you can more or less choose whatever you want since it's only syntax not semantics...

**Comment by pixelastic** [comment]
Yes, it's only syntax, and nothing is really broken with that syntax. I'm wondering if we really need to change it with 2.0. This will be a CSS breaking change for sure, but do we really need it?

**Comment by vvo** [comment]
indeed the link from @bobylito clearly state we can go wild with naming

**Comment by proudlygeek** [comment]
:b: __ :ear: -- :monkey:

**Comment by vvo** [comment]
Wiiiild!
