### ISSUE TITLE
Hits widget should support table as a valid container

### ISSUE THREAD

**Issue by taylorbrooks** [algolia/instantsearch.js#748]
Here is my hits widget:
````js
search.addWidget(                                                                  
  instantsearch.widgets.hits({                                                     
    container: '#donations',                                                       
    templates: {                                                                   
      item: '<tr><td>{{created_at}}</td><td>${{gross_amount}} {{donor}}</td></tr>' 
    }                                                                              
  })                                                                               
);                                                                                 
````
My markup:
````html
<table id="donations" class="table table-striped table-condensed"></table> 
````

Apparently this code is not valid and I get this error message in the console:
`Warning: validateDOMNesting(...): <div> cannot appear as a child of <table>. See table > Hits > div.`

Is it possible to use a `table` element as a container for hits?

**Comment by taylorbrooks** [comment]
Semi-related #707

**Comment by pixelastic** [comment]
Hmm, interesting. We use React internally for the rendering, and it uses `div`s internally. This might conflict with its internal validation when using it to render inside a `table`.

I think #707 would fix this issue as well, by letting you handle the whole rendering loop yourself in Hogan without needing React for each individual hit.

This is definitely a valid concern. @bobylito any idea on how to tell React to render a loop inside a `table` as a workaround until #707 is fixed?

**Comment by bobylito** [comment]
Well no I don't have some magic recipe for this case :) The good thing is that it makes #707 completely valid and should be done ASAP :)

**Comment by vvo** [comment]
Follow #707 for a way to do this

**Comment by vvo** [comment]
Actually we should support both situations (targeting a table as a container, using a full `hits`). will create separate issues

**Comment by vvo** [comment]
This could be easily solved if react implements the "fragment" api: https://github.com/facebook/react/issues/2127

**Comment by vvo** [comment]
Moved to #770
