### ISSUE TITLE
Question: Reset all filtering when searching

### ISSUE THREAD

**Issue by ricktbaker** [algolia/instantsearch.js#750]
It appears that when using the search widget it takes all of your current filters and facets into consideration along with your search term.   Is there a way to be able to reset those when a search is performed, so it will search across the entire index?

**Comment by pixelastic** [comment]
Hello @ricktbaker,

The goal of instantsearch.js was to provide a unified set of widgets that share the same 'state' (filters applied, query typed, etc).

If you want to remove all the current filters through the UI, you can have a look at the [clearAll](https://community.algolia.com/instantsearch.js/documentation/#clearall) widget.

If you want to do it programmatically, you can have access to the `.helper` property of your instantsearch instance, which is an instance of https://github.com/algolia/algoliasearch-helper-js. You can then [clear filters](https://github.com/algolia/algoliasearch-helper-js#clearing-filters) from here.

I would suggest the first solution, as it is more in line with the underlying philosophy of the instantsearch.js project. The other one might work but is a bit hackish.

**Comment by ricktbaker** [comment]
We'll need to go the second route, since the search is always site wide.   Thanks for the direction!

**Comment by pixelastic** [comment]
Glad I could help. I'm closing the issue, but don't hesitate to comment again if you need anything else.
