### ISSUE TITLE
IE9 incompatibility

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#751]
<img width="1345" alt="poly_error" src="https://cloud.githubusercontent.com/assets/29529/11951358/a1c71bec-a890-11e5-8786-1dd5f299fada.png">

**Comment by vvo** [comment]
Do you have the url to debug it?

**Comment by vvo** [comment]
I was not able to reproduce using the current build. Launched IE9 along with our dev app and it works.

Either we fixed it or we are missing some reproducible information.

Also remember that for IE9 to work you need to include a polyfill, see readme: https://github.com/algolia/instantsearch.js#browser-support
