### ISSUE TITLE
Adding parameter manually

### ISSUE THREAD

**Issue by prspace** [algolia/instantsearch.js#752]
Can any one please tell me how can i add parameter into the query string before start();

**Comment by bobylito** [comment]
If you want to add parameters to the query string, you can use plain js : 

```js
window.location.search = 'my=parameters'
```

All the foreign parameters will be preserved with the changes of the search parameters.

Let me know if this was your issue?

**Comment by prspace** [comment]
sorry for my incomplete question. I was talking about adding any refinement manually without widgets.

**Comment by pixelastic** [comment]
Hello @prspace,

You can pass them when instantiating instantsearch, using the `searchParameters` options

```javascript
var search = instantsearch({
    [...],
    searchParameters: {
        hitsPerPage: 5,
        // Any other Algolia options
    }
});
```

**Comment by vvo** [comment]
@prspace did that fix your issue?

**Comment by prspace** [comment]
Thank you, no it didn't fix my issue as i want always to attach a filter like i have an index name listings i want to return only listings where listing.status = 'ACTIVE'.

**Comment by vvo** [comment]
Can you try doing something like this:

```js
var search = instantsearch({
    [...],
    searchParameters: {
        hitsPerPage: 5,
        facetFilters: [
          'listing.status:ACTIVE'
        ]
    }
});
```

Where "listing.status" is an attribute in your records and is defined as an "Attribute for faceting" in the dashboard.

Let us know

**Comment by vvo** [comment]
@prspace I updated my comment

**Comment by prspace** [comment]
It's worked, thank you very much.

**Comment by vvo** [comment]
AWESOME

**Comment by roszelj** [comment]
I was needing the same thing but it didn't work for me, not sure why I did add my Attribute to the dashboard still with no luck.

var search = instantsearch({

    indexName: 'jobs',
    searchParameters: {
         facets: ['status'],
         facetsRefinements: {'status': 'published'}

    }
});

**Comment by roszelj** [comment]
I figured it out in-case someone has the same problem:

searchParameters: {
         facets: ['status'],
         facetsRefinements: {status: ['published']}

    }

**Comment by vvo** [comment]
Thanks @roszelj for the hints
