### ISSUE TITLE
[slider/priceRange]: Allow changing the attribute filtered programmatically

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#753]
Imagine I have a list of items to sell, and for each item I have their price stored in various currencies (euro, dollar, yen, etc). In my UI, I only want to display prices in the selected currency, but still allow users to swap displayed currency (through a dropdown menu) if they need to.

I also want to let them filter the results through a slider/priceRange widget.

A naive implementation would be to add three widgets, one for each currency, and add a bit of logic to hide/show them based on the currently selected currency. This will unfortunatly yield bad results: if I set a range in euros, then switch to dollars, then the range in dollar will not be correctly set. And worse, I now have no way to change or revert the range in euros.

I see various ways to fix this issue:

- Exposing a `.changeAttribute()` method on the widget itself that would allow keeping the same widget, but changing its targeted attribute
- Allowing to `.removeWidget()` the same way we `.addWidget()` on the instantsearch instance directly and letting the user destroying the previous dollar slider and adding a euro slider instead.

What do you think might be the best way? Or is there a more obvious solution I did not see?

**Comment by popup-user** [comment]
:+1: for this feature. We'd like to use it ASAP. Thank you!

**Comment by vvo** [comment]
We should be able to solve this by providing:
- a way to update the configuration of a widget (update the slider configuration and discard the previous configuration)
- a way to force a render of the interface (so that transformData on the hits widget runs again and you are able to switch the #price attribute you are using based on what the user selected in a custom widget)

What do you think?

**Comment by pixelastic** [comment]
I would name it `updateConfiguration` (as to be clear that this is not the way to init a widget). What would be perfect would be to be able to update every configuration option, but I'm not sure how possible it will be (like changing the bound DOM container, the templates, etc).

**Comment by vvo** [comment]
To solve this, I propose to have:
- search.removeWidget(widget) that will remove the widget and clean any needed DOM/events

Then you would just add a new slider with a different configuration.

This is a lot simpler and could be done for every widget.

Moved to #1065
