### ISSUE TITLE
Possible to reference a script template instead of a string ?

### ISSUE THREAD

**Issue by chrisvidal** [algolia/instantsearch.js#755]
Possible to reference a script template instead of a string ?

**Comment by redox** [comment]
Hey @chrisvidal,

what do you mean by `script template`, you mean a DOM selector referencing a `<script type="text/template">` content?

**Comment by chrisvidal** [comment]
yes exactly

**Comment by bobylito** [comment]
What about using `document.querySelector('.my-class').innerHTML' and pass it as the string?

**Comment by chrisvidal** [comment]
hehe it seems to work nicely :+1: :)
thanks

**Comment by bobylito** [comment]
Anytime :)
