### ISSUE TITLE
New Widget : autocomplete Select2 Js Library type

### ISSUE THREAD

**Issue by chrisvidal** [algolia/instantsearch.js#757]
the idea is to dispose of a widget able to search in a secondary index ( lets say an index of project for the sake of this example) with an autocomplete feature and a select2 kind of look. i think it should be pretty easy to build ?
maybe the issue is coming from the fact that the user need to be able to select a value (here a project) and then perform a new search in the real index ( which is a company listing that had worked on one or many projects)

**Comment by redox** [comment]
:+1:

**Comment by pixelastic** [comment]
Just to make sure I understand the issue, could you confirm this is the workflow you have in mind?

1. Users selects a project in a dropdown list (helped with an autocomplete so they do not have to scroll into the whole list).
2. Results are filtered, so only hits that matches this project are displayed
3. Users can type a query to further refine the list of results

In your example, the dropdown is populated through a secondary index, but this is actually used as a list of facets. How many projects (approx.) do you have in this list? Just to see if we're talking about a dropdown on a small list of facets, or a full search in another index.

**Comment by chrisvidal** [comment]
my use case is as follows:
i have 36 000 projects linked to 40 000 companies.
Client requirement is to find companies that has worked on this or that project (with other facets also)

so i imagined the flow :
there is input allowing the user to search in the projet list. there is some kind of autocomplete or more likely a results list (capped to a maximum result i guess)
the user can click and select a project from the result list to add it to the search. Here companies results listing is refined
he can then search another projet and click and select it to add it to the search.Here companies results listing is refined
the 2 previous selected project should be easily removable as well.

**Comment by pixelastic** [comment]
As of today, I think you could be able to build something like this using our [autocomplete.js](https://github.com/algolia/autocomplete.js) library (this is a fork of Typeahead that uses Algolia) and the `instantsearch.helper` property (that maps to our [javascript helper](https://github.com/algolia/algoliasearch-helper-js).

This will require a bit of plumbing, but the main idea would be to listen to the `autocomplete:selected` event of `autocomplete.js`, and here add a new `facetRefinement` to the `helper`, that matches the value selected in `autocomplete`...

We have plans to add search into facets values directly at the API level, but no ETA at the moment. I don't think we're going to add this feature like this directly into instantsearch core (because of file size, and custom setup requirements in term of indices), but maybe we should write a detailed guide on how our two libraries could work together.

Any other thoughts @redox @vvo @bobylito ?

**Comment by vvo** [comment]
We could definitely create a community widget that given the user as the right configuration would provide a refinementList sort widget with an input search on top of it and custom behavior to add remove refinements.

Would that work?

**Comment by pixelastic** [comment]
:+1: From my POV, this would work. It only requires a bit of specific index configuration on the user side. But we could explain all that in this widget specific readme.

**Comment by bobylito** [comment]
> We could definitely create a community widget that given the user as the right configuration would provide a refinementList sort widget with an input search on top

this is not really like select2...

<img width="870" alt="screenshot 2016-01-12 15 45 49" src="https://cloud.githubusercontent.com/assets/393765/12266466/a3029784-b943-11e5-89ae-30bd726e072c.png">

**Comment by vvo** [comment]
Indeed @bobylito, we have two different widgets here (that's why a GIF/screenshot is worth 6 github comments :D).

**Comment by chrisvidal** [comment]
@pixelastic @vvo 
solution proposed seems good implementation for my case.
where can i find (if exist ofc) more details about the implementation ?

**Comment by vvo** [comment]
@chrisvidal There's no current implementation of what you really want. If you want to go further on creating a specific widget, I would advise you to:
- build a graphical mockup of the widget (how would it look in a simple way)
- list the features available for the user
- design a JavaScript API listing the widget options

Then once you have all this design setup we can walk you through internal implementation.

You can do so in a new issue, it will be easier.

Thanks a lot!

**Comment by chrisvidal** [comment]
@vvo yes im trying to implement the solution presented by pixelastic which fits my requirements.
- The autocomplete part is almost done after setting up all the required index in algolia side.
- Now im digging in the algolia instant helper documentation to see how to add the selected value in the autocomplete widget.

**Comment by chrisvidal** [comment]
now the tricky part i guess, is to link the object named 'client' in the helpers which look like an instance of the old algolia search with the new 'serachclient' coming from the instantsearch API

**Comment by vvo** [comment]
@chrisvidal

- "algoliasearch" is the JS API client (just handling requests to the API).
- The helper (algoliasearch-helper) is the search state holder (what are the current refinements/query). It wraps the algoliasearch client
- instantsearch is then wrapping helper

If you have a test repository I can have a look and help you out.

**Comment by chrisvidal** [comment]
i can the skeleton of the related code here
<pre>
// instantsearch api, set up a refinementList
var categoriesRefinementList = instantsearch.widgets.refinementList({
            container: '#facet-categories',
            attributeName: 'categories',
            operator: 'or',
            limit: 8,
            autoHideContainer: false,
            sortBy: ['isRefined', 'count'],
            cssClasses: {
              root: 'root',
              header: 'facet-title',
              item: 'facet-value checkbox',
              count: 'facet-count uk-float-right',
              active: 'facet-active'
            },
            templates: {
              header: getHeader('Categories'),
            }
          });
        window.categoriesRefinementList = categoriesRefinementList;
        search.addWidget(
          categoriesRefinementList
        );
      // start
        search.start();
</pre>
Then creating the autocomplete
<pre>
   var client = algoliasearch('UIXXXXXX', '1241342342352524');
    var index = client.initIndex('CATEGORIES');
    setTimeout(autocompleteCategories, 250);

function autocompleteCategories() {
        $('#autocomplete-categories').autocomplete({ autoselect: true, openOnFocus: true, hint: false, minLength: 2 }, [
            {
              source: function(q, cb) {
                index.search(q, { hitsPerPage: 10 }, function(error, content) {
                  if (error) {
                    cb([]);
                    return;
                  }
                  cb(content.hits, content);
                });
              },
              displayKey: 'name',
              templates: {
                suggestion: function(suggestion) {
                  return suggestion._highlightResult.name.value;
                }
              }
            }
          ]).on('autocomplete:selected', function(event, suggestion, dataset) {
            console.log(suggestion, dataset);
 // here, not sure which client variable should be refered to ?
            var helper = algoliasearchHelper( client, 'COMPANIES_production', {
                disjunctiveFacets: ['ORcategories']
            });
            helper.setQuery(suggestion.name).addDisjunctiveFacetRefinement('ORcategories');
            helper.search();
            helper.on('result', function(results) { updateUI(results); });
          });
        }
</pre>

**Comment by chrisvidal** [comment]
awesome, found the solution after digging in the widget examples. thanks again guys for pointing out a solution :+1: 

<pre>.on('autocomplete:selected', function(event, suggestion, dataset) {          
            var helper = search.helper; // search is an instance of instantsearch
            helper.addDisjunctiveFacetRefinement('categories', suggestion.name);
            helper.search();
          });</pre>

**Comment by vvo** [comment]
Cool cool!

**Comment by smileBeda** [comment]
I am wondering though, how is this `select2`?
The title here might be a "tad" off, because select2 is [this](https://github.com/algolia/instantsearch/issues/757#issuecomment-170935298), would get populated by whatever values come from `attribute`, and instead of being a "simple" select, it is... a select2 select instance.

I do not see how the solutions herein proposed solve any of this?

**Comment by smileBeda** [comment]
Here's what I came up with - I am sure there are better ways, but this works.
Note, it is presumed you do add relevant libs on your own, and I use this with Typesense, but it should also work with Algolia since it uses instantsearchJS

```
const customMenuSelect = instantsearch.connectors.connectMenu((renderOptions, isFirstRender) => {
            const { refine, items, widgetParams } = renderOptions;

            if (isFirstRender) {
                const select = document.createElement('select');
                widgetParams.container.appendChild(select);

                select.addEventListener('change', event => {
                    refine(event.target.value || '');
                });
            }

            const select = widgetParams.container.querySelector('select');
            select.innerHTML = '';

            // Add an 'All' option at the top of the select element
            const allOption = document.createElement('option');
            allOption.value = '';
            allOption.text = 'All';  // Adjust this label if needed
            allOption.selected = items.every(item => !item.isRefined);
            select.appendChild(allOption);

            // Add other options with counts
            items.forEach(item => {
                const option = document.createElement('option');
                option.value = item.value;
                option.text = `${item.label} (${item.count})`;  // Including count here
                option.selected = item.isRefined;
                select.appendChild(option);
            });

            // Re-initialize Select2 after updating options
            $(select).select2({
                placeholder: 'Select a Category',
                allowClear: true,
                width: '100%',
            }).on('select2:select select2:unselect', function (e) {
                refine(e.target.value || '');
            });
        });
```

And in the `addWidgets`:
```
...
customMenuSelect({
					container: document.querySelector('#categories-refinement-list'),
					attribute: 'Category'
				}),
...
```

This does produce a working select2 that is populated with values from the attribute, and updates accordingly when values are changed.
