### ISSUE TITLE
Bad link in docs

### ISSUE THREAD

**Issue by sammarcus** [algolia/instantsearch.js#759]
In the [Custom Themes](https://community.algolia.com/instantsearch.js/documentation/#custom-themes) section of the docs, the stylesheet no longer exists at https://github.com/algolia/instantsearch.js/blob/master/css/instantsearch.scss.

**Comment by Shipow** [comment]
Good catch! thank you for report! :bug: :dart:

**Comment by Shipow** [comment]
https://github.com/algolia/instantsearch.js/pull/760

**Comment by sammarcus** [comment]
Whoops, pasted the wrong URL. Thanks for fixing anyway :blush: :raised_hands: :100: :+1:
