### ISSUE TITLE
documentation: list community widgets

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#766]
As proposed by multiple people and namely @seafoox, I am convinced we should now add a "community widgets" documentation section with the google maps and (maybe) the custom jquery slider example (if it really makes sense).

It should go in last position of the documentation, so that people do stumble on it if they are looking for it.

**Comment by pixelastic** [comment]
Agreed, with a "want to add your own?" link that points to a small getting started guide.

**Comment by bobylito** [comment]
Maybe have a dedicated page for community widgets? With big warnings and all? :)

**Comment by vvo** [comment]
Why big warnings? :)

**Comment by bobylito** [comment]
To explain that we do not do support on them :)
