### ISSUE TITLE
Let the developer choose when to trigger the search.

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#769]
## Current behavior

Every time a user changes a filter or change an input, this triggers a new search which will then trigger a refresh of the UI with the new results.

## Problem

This is perfect for desktop environment where there is a lot of space to display both the results and the refinements.

On mobile, space is scarce and we often need to have the refinements and the results on separate screens, and this leads to unnecessary calls to the search API because the results are not visible.

## Possible fix

Let the dev choose when to refresh (disable the auto search + provide a method on instantsearch to trigger the search). But then the filters values are not updated, which might leave the user with the "no results and I don't know why" UX...

Other ideas?

**Comment by redox** [comment]
It's even more tricky than that. Not doing the search after selecting a refinement would not refresh the refinements lists and therefore can lead to "no results" page (which is really something we want to avoid).

Imagine you have the following refinements:

````
Facet1:
 - A
 - B
 - C

Facet2:
 - X
 - Y
 - Z
````

if you refine on `A`, maybe only results with the `X` and `Y` categories will be in the results set => therefore A and Z should **never** be refined together. If you don't refresh the list after each refinement, that's definitely something that will happen.

**Comment by redox** [comment]
> But then the filters values are not updated, which might leave the user with the "no results and I don't know why" UX...

I really think those API calls are necessary to refresh the refinements list; even if we don't use the underlying hits -> nothing superfluous here I would say.

I assume that in some very specific cases where you can ensure it will always return results, it could make sense but I don't have any in mind. For sure if it's to "save" API calls, we should not dot it because the refinements refresh is as important as the hits refresh.

**Comment by vvo** [comment]
This should be doable now with the searchFunction option of instantsearch.js
