### ISSUE TITLE
widgets with both `container` and `item(s)` template should support <tables> container

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#770]
Following #748.

We are currently unable to use `<table>` as a container and `<tr><td>..` as an item/hit template.

We could leverage https://github.com/facebook/react/issues/2127 to be able to do so at some point.

In the meantime, this templating will be supported through a regular `<div>` and #707

**Comment by vvo** [comment]
currently not doable, you must use the `template.allItems` option of the hits widget

**Comment by taylorbrooks** [comment]
@vvo Are there any examples for how to use `template.allItems` and use a table?

**Comment by vvo** [comment]
Yes its now documented, see: https://community.algolia.com/instantsearch.js/documentation/#hits

Also see our example:
- https://github.com/algolia/instantsearch.js/blob/498577e4c3785c373c273913833ead5a90c7fbf7/dev/app.js#L53
- https://github.com/algolia/instantsearch.js/blob/498577e4c3785c373c273913833ead5a90c7fbf7/dev/index.html#L70
- https://github.com/algolia/instantsearch.js/blob/498577e4c3785c373c273913833ead5a90c7fbf7/dev/templates/all-items.html

As you can see, you must create the table inside the template, it can't be the main container.

**Comment by AdamBCo** [comment]
@vvo Have there been updates to allow this? I know this issue was closed a year ago, so I'm not sure if someone has revisited the issue. Thanks for the help.

**Comment by bobylito** [comment]
Since then, we have implemented [connectors](https://community.algolia.com/instantsearch.js/v2/connectors.html) that allows you to completely control the rendering. Here you can see an example using the [connectHits](https://community.algolia.com/instantsearch.js/v2/connectors/connectHits.html): https://codesandbox.io/s/30m61z42v5
