### ISSUE TITLE
Use different template engine that Hogan.

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#78]

**Comment by vvo** [comment]
@maxiloc stay safe in holidays we handle it! :D

**Comment by maxiloc** [comment]
Cool !! :+1:

**Comment by vvo** [comment]
We already have a way to pass a template as a `function` so we are good with multiple templating engine.

We are not going to embed multiple templating engines because it would make our code size much higher.

**Comment by maxiloc** [comment]
Yep I saw it. Nicely done
