### ISSUE TITLE
Question: Attribute For Distinct

### ISSUE THREAD

**Issue by ricktbaker** [algolia/instantsearch.js#780]
Back again, with another question.      We have products with multiple colors and sizes and when searching we group by the item, so it will only show one.     The problem with that is if we search for "nike shirt", the results only show one result as we need, but the facets don't have all of the color/size variations.

Not sure if this is even possible, but is there a way to group by a facet in the search, but have the actual facets ignore the group by setting?

**Comment by vvo** [comment]
Hi @ricktbaker could you write this to support@algolia.com, we will need to have a look at your index.
