### ISSUE TITLE
optionalWords=querystring not doable

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#784]
We don't have a way to do optionnalWords=querystring for each query.
Probably an option in searchbox should do it

**Comment by pixelastic** [comment]
You can pass any Algolia option to the `instantsearch()` instanciation call using the `searchParameters` option. Would that work?

**Comment by pixelastic** [comment]
I thought I added that to the doc but I think we haven't deployed the latest version on the community website yet.

**Comment by maxiloc** [comment]
No that won't work because this need to be set for each query with the query.
So if I search for "Iphone 6 case" optionnalWords will be "Iphone 6 case"
if I search "Iphone 5 charger" optionnalWords will be "Iphone 5 charger"

**Comment by bobylito** [comment]
Putting that as an option in the search box will work. The only problem that can happen is with several widget that have the ability to set the query.

If we have that in instantsearch core, then it needs to intercept the query and then change the parameters. What if the helper could be prevented to send the search query when the `search` event is triggered https://github.com/algolia/algoliasearch-helper-js/blob/master/src/algoliasearch.helper.js#L723
This would be like : 
 - searchbox sets query and do the search
 - search event is triggered and interupted if the value of the query is not the optionnalWords
 - state is modified with the optionnalWords set to the query value
 - trigger the search again

First solution is way simpler :P

**Comment by vvo** [comment]
An option in the searchBox looks good, this is where it should belong. Now we need a name for it that actually maps a feature

**Comment by vvo** [comment]
This can be solved using the queryHook or searchFunction or creating a custom widget that will listen to helper change and set the optionnal words accordingly.

No need for a new API entry.
