### ISSUE TITLE
[slider/priceRange]: Allow changing the values using text inputs

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#785]
Would be great to have an option that enables the display of two inputs above / under the slider and that enable the user to manually set the wanted values. 

I can see various reasons why I can be useful:

* In the case there are a lot of possible values, it might be tricky to set the slider to the exact value.
* On mobile, because screens are smaller, but also touch interactions not as precise as mouse, its often easier to set a value using the keyboard.

What do you think do?

**Comment by bobylito** [comment]
:+1: for the overall idea.

Could you give more details on the API you can think of to match this? Also can you describe more the mobile part (shall we continue to display the slide, desactivate it...)?

**Comment by vvo** [comment]
See #1069
