### ISSUE TITLE
API Proposal: Every refining widget should expose `widget.on('refine')`

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#79]
Every refinement widget instance should be an EventEmitter and so we would be able to:

```js
var categories =   instantsearch.widgets.menu({
  container: '#categories',
  facetName: 'categories',
  limit: 10,
  rootClass: 'list-unstyled',
  template: require('./templates/category.html')
});

categories.on('refine', function(newValue, previousValue) {
  // do whatever you want here, like scrolling to some specific place or top.
});

search.addWidget(categories);
```

@algolia/javascript ?

**Comment by pixelastic** [comment]
Yes, could be really nice. Would you trigger it before or after the rendering of the widget itself?

Also, shouldn't it have access to the helper in the callback? So users can handle complex and custom selections (like "When I filter by Brand, I want to disable the filter by free shipping", etc).

Or do you have a specific need in mind?

**Comment by vvo** [comment]
> Would you trigger it before or after the rendering of the widget itself?

Dunno if they are some pro/cons on this.

> Also, shouldn't it have access to the helper in the callback?

That's a good idea. Easy to add. Good for power users.

> Or do you have a specific need in mind?

scrollTo what you want, analytics, popin warning about "free shipping", automatically refine on another attribute (like you said).

**Comment by pixelastic** [comment]
Maybe we need both? `beforeRefine` and `afterRefine`.

The first could have the helper as a parameter and could be used to handle specific needs of changing filters based on the user choice.

The second will be mostly used to update the rendering in one way or another (add classes to elements? scroll to top?)

**Comment by vvo** [comment]
> Maybe we need both? beforeRefine and afterRefine.

Yes having them right now would help clarify the things and handle all cases, :+1: 

I love the `beforeRefine` where you are able to change filters automatically so that you can refine multiple things when they are linked.

**Comment by vvo** [comment]
There's already #83
