### ISSUE TITLE
Allow overriding the default click behavior on refinement lists

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#791]
User request: being able to show facets but when clicking them, go to a particular webpage (like the corresponding category page) instead of refining the results.

This is a legit edge-case that we should address I believe.

http://stackoverflow.com/questions/34944597/algolia-how-to-set-anchor-in-facets

**Comment by pixelastic** [comment]
Maybe allowing the users to define custom methods to be called on specific actions on the widget. They could either override the default behavior of our widgets or plug themselves into the flow. 

Or maybe this could simply be handled with emitting global events and letting the user listen to the `on:refine` and change the url from here.

**Comment by vvo** [comment]
possible API:
- refine hook (similar to query hook)
- refine event on widget (not global, since you then have to find a way to distinguish refines from widgets)
- option on widget like "do not refine on click"

**Comment by pixelastic** [comment]
I'm not found of the third solution (option on the widget). It will clutter the API in the end, we can't handle all use-cases.

I don't think I'm familiar with the refine hook, how does it work?

I like the refine event on the widget idea. A global refine event could work as well if we can have access to the originating widget from the event itself (`event.from` being the widget instance?)

**Comment by vvo** [comment]
Refine hook should cut it, always tricky to provide events that in the end are disabling a behavior. The dom handle this by passing event and event.preventDefault but that would look like weird in our case I guess.
 
So passing a refineHook(value, refine) where you need to call refine, would allow good crazy implementations and use cases.

Works?

**Comment by pixelastic** [comment]
What would `refine` expect as an argument? Just the value of the current facet? Like if I click on the "outdoor" `tag`, I should just need to call `refine('outdoor')`, or `refine('tag', 'outdoor')`?

**Comment by vvo** [comment]
Yep thats a nice api similar to queryHook

**Comment by vvo** [comment]
moved to #1068
