### ISSUE TITLE
Pagination is visible with a single page of results

### ISSUE THREAD

**Issue by hkdobrev** [algolia/instantsearch.js#793]
I'd like to be able to configure the pagination in some way so it does not appear at all, when there is only one page of results. At the moment there is a configuration option to hide it only when there are no results at all.

Is there a way to do this at the moment?

**Comment by bobylito** [comment]
Thanks @hkdobrev for the feedback. Right now, this is not possible as part of instantsearch.js but we can definitely work something out to have an option. In the meantime, you could monkeypatch the widget and check the number of pages, like so:
```js
var paginationWidget = instantsearch.widgets.pagination({/*parameters*/});
var oldRender = paginationWidget.render;
paginationWidget.render = function(params) {
  var currentState = params.state;
  
}

**Comment by hkdobrev** [comment]
@bobylito Thanks! I was going to wrap the whole pagination widget into a new one, but you helped me realise I can override just the render method.

Looking forward to the pagination widget in the future when you would at least have an option for this, if not the ability to use templates for everything in the widget.

**Comment by bobylito** [comment]
:+1: :)

**Comment by pixelastic** [comment]
Regarding adding the option for a future version, what about:

- a `minPages` options (that mirrors the `maxPages`). If the number of pages is below that threshold, no widget is displayed
- or allowing `autoHideContainer` to accept a function instead of a boolean that let users decide when hiding the widget.

Just ideas on the top of my head, to be discussed.

**Comment by hkdobrev** [comment]
@pixelastic Thanks for spending the time on this.

I think the option name `minPages` would not represent the behaviour and it would bring confusion when it's being compared with the semantics behind `maxPages`.

Having a function for `autoHideContainer` - basically a hook is always useful. This is something very similar to what is considered for the search box widget with https://github.com/algolia/instantsearch.js/issues/776#issuecomment-172900988.

**Comment by vvo** [comment]
@hkdobrev Using the `render` event you should be able to hide/show the pagination: https://community.algolia.com/instantsearch.js/documentation/#events

**Comment by hkdobrev** [comment]
@vvo But the render event does not provide the `params` object as an argument like the `render` method of the pagination widget does.
