### ISSUE TITLE
Cannot listen to first internal helper `on:result` call.

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#796]
We do expose the inner `.helper` property of instantsearch, which is a nice thing, letting users listen to the helper events and hook custom behavior if need be. This can be done through `instant.helper.on('result', function(results) { });` calls.

Unfortunatly, it is not possible to listen to the first calls made by the internal helper that way. I'm talking about calls for the empty query, to get the list of facets, init the range slider, etc.

The `.helper` is only initialized when we call `search.start()`, so we cannot register events before that. And of course, after calling `start()` it's too late, calls are already made.

Do you think it would be possible to init the helper as soon as we init instantsearch, so we can register events on it, and only fire the first request on `start()`?

**Comment by vvo** [comment]
everything is feasible of course but what is the underlying use case? Maybe you need an official API here.

I think the fact that the helper is available publicly is not really an API decision, more an hidden feature right now.

**Comment by vvo** [comment]
You can now use searchFunction from the instantsearch() init method. So you can hook into the calls to helper.search() before they are done.
