### ISSUE TITLE
Add support for optionalFilters

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#799]
This feature is still in beta but it still could be convenient to be able to set it. This is related to https://github.com/algolia/algoliasearch-helper-js/issues/200

**Comment by vvo** [comment]
Since we can now pass it to searchParameters, does it makes it done?

**Comment by ryantbrown** [comment]
Is anything happening on this? We are trying to use `optionalFacetFilters` but it doesn't seem to be working. I noticed it located in the [algoliasearch-helper-js](https://github.com/algolia/algoliasearch-helper-js/blob/39bec1caf24a60acd042eb7bb5d7d7c719fde58b/src/SearchParameters/index.js) file? 

This repository lists `algoliasearch-helper-js` as a dependency, does instantsearch.js use helper underneath the hood? If so then I would assume it would be working.

**Comment by vvo** [comment]
Hi @ryantbrown You should be able to do that by passing them to the searchParameters option:

```js
instantsearch({
  searchParameters: {
    optionalFacetFilters: ...
  }
});
```

Let me know how it goes.

**Comment by bobylito** [comment]
@olance I think I could need your help to define the way widgets could use optionalFilters (the new name of optionalFacetFilters).

**Comment by olance** [comment]
@bobylito let's have a chat then :)

**Comment by bobylito** [comment]
Usage of the optional filters has been tested in this example: https://jsfiddle.net/bobylito/5Lx0ea3q/

Since it's for personalization, it means that it will probably be set behind the scenes and this example shows exactly how to set it.
