### ISSUE TITLE
externalize all widgets

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#8]
we should externalize and develop all widgets in separated modules

To ease development, we can have an `npm run link-all-widgets` that will clone, checkout master and npm-link every known widget.

So that we can easily develop them using the `npm run dev` task.

**Comment by vvo** [comment]
=> No, it would complexify the `dev` workflow and thus slow us down.

cc @redox @pixelastic 

This does not prevents us to easilyt collaborate of course, since when developping a widget you only need to work in widget/*

**Comment by redox** [comment]
I'm happy with keeping a single project with subdirs :+1:

**Comment by vvo** [comment]
It may be a good thing later on, but it's really too early right now, this would slowwwwwww down
