### ISSUE TITLE
Adding 2 refinementList doesn't merge the underlying query parameters

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#80]
The query is sent with a single `facets: ["lastRefinementListFacet"]` at the end.

**Comment by vvo** [comment]
Yes we need to use https://lodash.com/docs#defaultsDeep instead of merge here

**Comment by vvo** [comment]
So thanks @bobylito because the issue is not about deep/defaults.. merge is already deep. The issue is that we need to merge arrays like the doc has an example on this: https://lodash.com/docs#merge

**Comment by redox** [comment]
I've just added the reproduction use-case @bobylito

**Comment by bobylito** [comment]
Thanks @redox :D
