### ISSUE TITLE
Programmatically updating the query will not update the searchbox

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#803]
Should we provide an option or handle it by default?

There have been usecases report lately about this and the workaround was not only to change the helper query but also update the DOM element manually (which is hacky and may result in multiple searches?)

**Comment by bobylito** [comment]
From an implementation POV, it's a bit sad that the searchbox does not update itself when the query of the SearchParameters is updated. Have we tried with the latest version with the urlsync fix?
