### ISSUE TITLE
When searchBox is inside a <form>, <button type="reset"> has no effect

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#804]
Should we, can we handle this? As seen in http://shipow.github.io/searchbox/

@Shipow's searchbox is not yet using instantsearch but if we would want to use it we would not be able to do it competely. It's using a button reset for the reset of the input (native dom behavior).

Either we can solve it easily, natively without any other API entry OR we start providing searchBox instance methods like searchBoxWidgetInstance.setQuery() that will update and run a new search.

**Comment by Shipow** [comment]
Pressing 'esc' fire the event so, I think it's just a matter of type of event watched by instantsearch, it's probably 'input' and should be 'change'

**Comment by Shipow** [comment]
https://github.com/algolia/instantsearch.js/blob/master/src/widgets/search-box/search-box.js#L144

**Comment by Shipow** [comment]
When using url sync it seems that the reset event won't be enough because it reset to the value of the form when loading the page.

**Comment by vvo** [comment]
This should be solved by doing https://github.com/algolia/instantsearch.js/issues/859.
