### ISSUE TITLE
Do not send the `state` argument before the `helper` argument

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#82]
Current widget API is:

```js
init(state, helper);
render(results, state, helper);
```

I see us never using the `state` param for now, and it is accessible through helper.state.

I am not sure it will be easy to understand and we do not advocate using the `helper.state` token in the helper docs either.

So I propose to either:
- remove entirely the state argument from our widget API function signatures
- always put it last in function signatures

What do you think?

**Comment by vvo** [comment]
=> we put state at the end

**Comment by pixelastic** [comment]
So what is the difference between `state` and `helper.state` here?

**Comment by vvo** [comment]
So in some situations helper.state is not the one linked to the results events. Here's an example workflow that @bobylito gave me:

- instantiate
- helper.state is X
- call .search() #1
- refine on smg
- helper.state is Y
- => result() event for search #1. helper.state is Y (mismatch), result(data, state) is X (ok)
- call .search() #2
- => result event for search #2. helper.state is Y (ok),  result(data, state) is X (ok)

This is why we should still give the `right` state event in the widgets render(), the helper is doing the work to provide the right state in the result event.

**Comment by pixelastic** [comment]
Ok, I get it. `helper.state` is the current state of the helper, `state` is the state if was before sending the `search`. In practice, we'll only need the `state`, and even this one we'll not need that often.

**Comment by vvo** [comment]
Yes `state` in the widget API is `.on('result', data, state)` and not helper.state.

And `.on('result', data', state)` the state is always the state of the search corresponding to the result/data event

**Comment by vvo** [comment]
This will be solved by Tim's #90
