### ISSUE TITLE
beforeSearch hook

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#823]
What about providing a `beforeSearch(helper)` hook that would be responsible one provided for launching the helper.search() method?

It would solve cases like:
- I want to programmatically add filters based on the query: if the query changes, I want to update optional facet filters (cc @olance)
- I want to avoid doing the first search query #4 
- avoid search if chars.length < X #185 #182 
- debounce the searchbox #776 #817 (only issue being you do not know it was triggered by the searchBox, but should be enough)
- Let the developer choose to trigger the search (not sure fully resolved by this proposal) #769 

The naming might not be the best one, other possiblities:
- searchHook
- ??

```js
instantsearch(appID, apiKey, {
  searchHook: function(helper) {
    // once you define the search hook, it's your responsability to call helper.search, otherwise: no search is done
  }
})
```

**Comment by maxiloc** [comment]
:+1:

**Comment by bobylito** [comment]
Solves everything!(tm) The proposed API is a bit raw, though. Why not make that an event? And like DOM events, provide a function that would let stop the behavior? (and lets retrigger it).

Otherwise seems great :+1:

**Comment by seafoox** [comment]
:+1:

**Comment by vvo** [comment]
> Why not make that an event? And like DOM events, provide a function that would let stop the behavior?

Something like:

```js
on('before search', function(helper, preventDefault) {
  // modify helper
  // or call e.preventDefault()
});
```

?

I am not used to use helper to cancel actions that would normally happen but yes since the instance is already an event emitter, maybe. Depends on what does it brings more

**Comment by vvo** [comment]
> Solves everything!(tm)

I am pretty sure it does not :D Someone will come and say "YES BUT.."

**Comment by olance** [comment]
An event would be way better indeed :+1: 
Why not have it return falsy/truthy and test that to check if the search should continue?

I don't see the point in introducing a function just for stopping the search in our case.

**Comment by vvo** [comment]
> An event would be way better indeed

Why/How would it be better?

**Comment by vvo** [comment]
> Why not have it return falsy/truthy and test that to check if the search should continue?

That's what I planned at the begining but I always found those kind of APIS less obvious than just calling "helper.search"

**Comment by vvo** [comment]
Warning this do not means you would be able to easily do the "render on server, cancel first query" Because rendering on server would not make the facets value clickable. They would not yet be binded.

I believe if one use would really want to implement a full server-side - bind on frontend, it would require us to work on #833 a lot more.

**Comment by vvo** [comment]
cc @hkdobrev you will find the proposal to solve both initial query and search debounce in the first comment.

See https://github.com/algolia/instantsearch.js/issues/823#issuecomment-183356773 to understand that having a full server side rendering AND using instantsearch.js to rebind server-generated facet values is not currently feasible, if you have any idea how we would do so, let me know.

Also cc @VonD

**Comment by olance** [comment]
> > An event would be way better indeed
> Why/How would it be better?

I think it's better because it allows you to add different hooks from different places, and setting a hook by using events means you're not replacing someone else's hook! (which is the case if you have to do `thing.beforeHook = ...`)

**Comment by vvo** [comment]
> I think it's better because it allows you to add different hooks from different places, and setting a hook by using events means you're not replacing someone else's hook!

Agree that for events it's always better to use a real event interface. But here I wonder, it's really a hook. Something that will completely replace the helper.search() calls by anything you do.

In the end I guess you are both right @bobylito @olance, making it an event will make it more flexible and also more inline with what we have today.

Maybe we should split it in two,

Add a `beforeSearch` event:
```js
search.on('beforeSearch', function(helper) {
  // do anything you want with the helper
  // no need to call helper.search()
});
```

Solves adding filters programmatically.

Add a `searchFunction` API entry, it will default to helper.search()

```js
instantsearch(appID, apiKey, {
  searchFunction: function(helper) {
    // your responsibility to call helper.search()
   }
});
```

Solves other cases like min char length, debounce ..

I am proposing this split because I read

> I think it's better because it allows you to add different hooks from different places

And yes it makes sense but only if it's not actually your responsibility to call helper.search when using the event, otherwise you would have to synchronize yourself between your event listeners for who should call helper.search().

@bobylito 
> And like DOM events, provide a function that would let stop the behavior?

If we do this, it would be harder for consumers to then implement debouncing. Since you would have to somehow still call a method to say "do not search".

**Comment by bobylito** [comment]
> I think it's better because it allows you to add different hooks from different places

Well having configuration for hooks in multiple places might lead to poorly understandable behavior. For example if you have two hooks set in different places you won't necessarily know exactly what the other one is doing. If both try to do the same thing (like a debounce) it can be pretty messy.

:+1: on your proposition @vvo to have two API's

**Comment by olance** [comment]
> Well having configuration for hooks in multiple places might lead to poorly understandable behavior. For example if you have two hooks set in different places you won't necessarily know exactly what the other one is doing. If both try to do the same thing (like a debounce) it can be pretty messy.
I agree, but that's something you should leave to the developer.
I have had problems with that kind of decisions being made for me in the past. Forcing a single hook can be in some situations very difficult to work with. When several event hooks can be registered, you have more flexibility and you can decide what's OK to do and what's not depending on your own context.

I am not sure I agree with the complexity of having two methods introduced.  
I see this `beforeSearch` hook just as a "before filter" in Rails: you can register several filters that will be called one after the other before a controller action takes place; any of the filters can return false/raise an exception/trigger a redirect, which will block the default execution flow.

An analogy that could make more sense here are the middlewares in Express.js for instance.  
Why should we separate this logic into two different methods/hooks when you can have a single one?

Call the hooks in the order they were registered. Each hook can change the helper config and do just that, and others can prevent search execution by returning false or calling a special function (I'd prefer returning false but that's another point).  
I can't see the need for a special function that would replace the search logic?

**Comment by vvo** [comment]
> An analogy that could make more sense here are the middlewares in Express.js for instance.

Yes what you describe are middlewares: functions able to cancel or continue the flow of others. But it seems a bit overkill here?

For example, how would you implement debouncing with this solution?

**Comment by olance** [comment]
I guess that would work?

```js
function debounce(func, wait, immediate) {
	var timeout;
	return function() {
		var context = this, args = arguments;
		var later = function() {
			timeout = null;
			if (!immediate) func.apply(context, args);
		};
		var callNow = immediate && !timeout;
		clearTimeout(timeout);
		timeout = setTimeout(later, wait);
		return callNow ? func.apply(context, args) : return false;
	};
};

search.on('beforeSearch', debounce(function() { return true; }, 100));
```

**Comment by vvo** [comment]
@olance We cannot implement the return true/false pattern. This is not a common JavaScript pattern in APIS.

Most of the time when you have events, no code will listen to the return value of the event handler.

**Comment by olance** [comment]
@vvo This is just an implementation detail. If you want to separate into two API methods you can do that; if you want to have more of a middleware concept, which I think is a more elegant solution, whether it checks that each middleware returned true/false or called a callback you provided is up to you.

Plus, the return pattern is a very simple way to achieve what we want, and easily documented too (`return false if you want to cancel the current search`), and no-one is actually going to need to "listen" to the return value but your own internal code. So to me that's not that big of an issue.

**Comment by vvo** [comment]
In the end, for a start, I will go for the initial proposal that can solve the needs and do not require too much new API entries.

If you really need to split your hook in multiple functions that will be still feasible, on your side. Using any middleware library or your own.

We will see how people use this and iterate if needed.

Exposing a single function should be ok in most cases.

**Comment by olance** [comment]
OK, the simpler the better, let's start with that :) :+1:

**Comment by vvo** [comment]
was done and implemented as searchFunction
