### ISSUE TITLE
pagination scroll to top is no working on mobile

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#825]

**Comment by bobylito** [comment]
Can you specify the tested platforms?

**Comment by Shipow** [comment]
Yes it works with safari ios, but not with chrome ios. os and apps up to date.

**Comment by hkdobrev** [comment]
I can confirm it works on Chrome Beta for Android version 49.0.2623.34. Android version 6.0.1.

**Comment by vvo** [comment]
Tested and worked on mobile safari. open a new issue with more details if still buggy
