### ISSUE TITLE
[hits]: Apply `transformData.allItems` even if no `template.allItems`

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#829]
Currently, the `transformData.allItems` method is only applied when a `templates.allItems` template is defined. What if I want to filter the list of results returned but still use the default rendering (and thus only want to use the `templates.item` property)?

This can be used for example to dedupe elements returned by the API in more custom ways, or merge elements together. Currently this can only be achieved by defining a `templates.allItems` that only reproduce the default behavior.

I suggest we always apply `transformData.allItems` to the list of returned hits, even if no `allItems` template is defined. Then, each of the resulting hit will be normally passed to the `transformData.item` methods.

This does not change the fact that the `item` and `allItems` templates are mutually exclusive, just the fact the that `allItems` `transformData` is always called.

Thoughts? I can take care of the PR.

**Comment by bobylito** [comment]
Do you have a practical example? For deduplication, isn't distinct in the API enough? (since we are not merging several requests into one)

**Comment by pixelastic** [comment]
The example I have currently in mind is when searching in a large text (like a book). I have split my text in chunks that roughly equals a paragraph. In order to display a nice UI, I want to display the matching chunk of text, along with its context (paragraph before and paragraph after). `content`, `after` and `before` are all stored in the same record.

The thing is, if I have two results like this:

```
before: A
content: B
after: C
```
```
before: B
content: C
after: D
```

You can see that they are actually two paragraphs following one another. Instead of duplicating the render, I would like to merge them in something like:
```
before: A
content: B + C
after: D
```

To do that I need to access the full list and merge some hits together before passing it to the rendering.

I just remembered that the `template` and `transformData` keys are really linked, a `transformData` will always be applied to the data when calling the template with the same name. This actually makes a lot of sense and makes the API very predictable. I'm now unsure I really need to change that :)

Maybe using an `allItems` template is actually the best solution. I'm closing the issue for now, but feel free to comment if you have anything other thoughts to add.
