### ISSUE TITLE
Initialize instantsearch.js with a hierarchicalFacetsRefinements parameter

### ISSUE THREAD

**Issue by amelielescure** [algolia/instantsearch.js#830]
Hi, 

I would like to retrieve a list of objects for a defined category. 

For this I tested two methods:
```javascript
var search = instantsearch({
    [...],
    searchParameters: {
      hierarchicalFacetsRefinements: {
        'categories.fr.0': {
          0: 'Revêtement > Éléments de décor > Poignées de portes'
        }
      }
    }
  });
```
This returns me an error message: _Uncaught TypeError: Cannot read property 'facets' of undefined_

```javascript
var search = instantsearch({
    [...],
    searchParameters: {
      facetsRefinements: {
        'categories.fr.0': {
          0: 'Revêtement'
        }
      }
    }
  });
```
It works just for a level 1 category .. In my case "Revêtement", then I want to pass it "Revêtement > Éléments de décor > Poignées de portes"

How to do ? An idea ?

**Comment by lgdelrosario** [comment]
I got it working but returns error: Uncaught TypeError: e[t].concat is not a function
and the widgets filter not showing anything. How can I set initial facet filter checkbox checked?

`  var search = instantsearch({
    appId: opts.appId,
    apiKey: opts.apiKey,
    indexName: opts.indexName,
    urlSync: true,
    searchParameters: {

       disjunctiveFacetsRefinements : {
        'category': {
          0: 'Equipment'
        }
      }      
    }
  });`

**Comment by vvo** [comment]
Hi @amelielescure sorry for the late reply, could you explain in term of UI/use case what you want to achieve? So that then we can see what's the best solution to achieve it.

Thanks.

**Comment by lgdelrosario** [comment]
Hi @vvo 

I'm also looking for a command to filter the facets initially. I'm using disjunctive facet, how can a certain category selected by default? I tried facetFilter but it says in console not yet in current version.

**Comment by vvo** [comment]
> I'm also looking for a command to filter the facets initially. I'm using disjunctive facet, how can a certain category selected by default? I tried facetFilter but it says in console not yet in current version.

Can you open a new issue and give the full JavaScript code you are using where you want to pre-select a facet filter? Thanks, it will help not hijack conversations and this particular issue. Once done I will remove the comments here

**Comment by amelielescure** [comment]
Hi @vvo, sorry for the response time too.
Indeed, for my product index , I have a facet 'categories.fr.0 ' and use a hierarchical widget instantsearch for the categories . So I wanted to have a page listing products with a category selected during initialization.
Finaly, the algolia support gave me the solution:
```javascript
var search = instantsearch({
  [...],
  searchParameters: {
    hierarchicalFacetsRefinements: {
      'categories.fr.0': ['Revêtement > Éléments de décor > Poignées de portes']
    }
  }
});
```

**Comment by vvo** [comment]
Nice! Happy coding with instantsearch.js :)
