### ISSUE TITLE
Integration within React apps

### ISSUE THREAD

**Issue by VonD** [algolia/instantsearch.js#833]
Follow-up from #831 

---

@vvo thanks! Not much feedback for the moment as the project is still at a very early stage and as i'm just discovering the lib.

I was wondering, though, if there might be a more straightforward integration within a React app. Excuse-me if it's already the case. I was thinking about an api like, for example : 

```es6
import React, { Component } from 'react' 
import { InstantSearch, SearchBox, Hits } from 'instantsearch.js'

class MySearchComponent extends Component {
  render() {
    return (
      <InstantSearch
        appId={ appId }
        apiKey={ apiKey }
        indexName={ indexName }
      >
        <SearchBox
          placeholder={ 'Custom placeholder' }
        />
        <Hits
          hitsPerPage={ 6 }
          renderHit={ hit => <MyItemComponent item={ hit } /> }
        />
      </InstantSearch>
    );
  }
}
```

Some of the benefits i see in such an approach would be : 
* the whole tree gets re-rendered when the parent component's `props` or `state` are updated
* the `context` does not get lost : useful with libs relying on it such as `react-router`
* we get server-side rendering for free
* no risk of conflicts between different React versions
* maybe modularize dependencies to avoid bundling `hogan` or other libs that react apps won't use

Would that be a big refactoring ? I understand the lib is not mainly targeting React apps, but as it is all React, it doesn't seem too difficult. The reference to the search helper could be passed to the widgets via `context`

Sorry if all that's already possible or off-topic.

**Comment by VonD** [comment]
@vvo 

Hi,

After playing a bit more with Algolia, I think the best fit for a React app is to use directly the js client. I just wanted to share some thoughts about it with you, but would be glad to contribute to this lib if I can help : it is great and has a really impressive potential!

The search helper is a state manager. Most React apps would already manage the app state somehow, whether it be through Flux stores, some component's state,  etc… which means the helper's state is either hidden from the rest of the app or to be synced with what manages its state.
The latter is clearly an anti-pattern. The former is ok if the helper's state can be seamlessly flowed down the entire subtree and the rest of the app doesn't need to know about it. Within the scope of this library, this means : it is ok if writing custom widgets is as simple as registering to the app's `context` through `contextTypes`.

Furthermore, the evented nature of the heper (`helper.on`) makes it impracticable server-side.

Finally, in its current state, using this lib within a React app requires a lot of hacks : `ReactDOM.render` being called several times, `props` or `context` do not get passed down seamlessly which is against React's nature.

I feel it's much more natural to think about the query made to Algolia's API this way : 

`state → build query → render with hits → UI change → update state → build query → …`

What I mean is that the query should be built from scratch every time the app's state updates, rather than tweaking the helper.

This is quite straightforward with the client : 

```es6
componentDidUpdate(prevProps, prevState) {
    if (this.state.search !== prevState.search) this.client.search(this.state.query, this.setRefinementsFromState(), (err, results) => this.setState({ results }))
}
```

Once again, I understand React apps are not the main target of this lib, but I reckon it could be exposed to React in a way, and with all the templating and widgets logic in another. For example : 

```es6
// From react
import { InstantSearch, SearchBox, Hits, Pagination } from 'instantsearch.js/react'
// From another environment
import instantsearch from 'instantsearch.js'
```

Anyway,.. sorry for the long write-up, I just wanted to give some feedback on this.

**Comment by vvo** [comment]
> which means the helper's state is either hidden from the rest of the app or to be synced with what manages its state.
> The latter is clearly an anti-pattern. The former is ok if the helper's state can be seamlessly flowed down the entire subtree and the rest of the app doesn't need to know about it

I am not sure to be skilled enough in building real application (versus just using React inside a library like we did) to fully understand what you propose/what would be better. Can you precise?

> Furthermore, the evented nature of the heper (helper.on) makes it impracticable server-side.

I think it might be possible server side to use the helper, thoughts @bobylito? Also node.js as events so I am not sure to get the actual issue (besides maybe some hacks to know when the helper computed the data)

> ReactDOM.render being called several times, props or context do not get passed down seamlessly which is against React's nature

We tried to get some reference on this: is calling ReactDOM.render multiple time a true antipattern? But without any luck. The thing is that from the library POV we want to be able to instantiate a widgets at any place in the DOM.

While when having a single ReactDOM.render I believe this is not feasible? You have only a single entrypoint/DOM container. 

> componentDidUpdate(prevProps, prevState) {
>     if (this.state.search !== prevState.search) this.client.search(this.state.query, this.setRefinementsFromState(), (err, results) => this.setState({ results }))
> }

This looks very nice and straightforward yes

> Once again, I understand React apps are not the main target of this lib, but I reckon it could be exposed to React in a way

This is definitely something we should think about. We first designed the lib to be smart wrappers (widgets), modifying the state of the search and getting hits back to pass them to "dumb" (display only) react components.

Doing the opposite (smart components, dumb wrappers) would require a lot of change of course but would also be a bolder move to finally be a full "React toolkit" with a "vanilla JavaScript wrapper" that would maybe be the real instantsearch.js project.

If you happen to re-build some of our components in a smart way (them holding and modifying the search state), we would be happy to see them, contribute and maybe that would be the start of the next instantsearch.js big iteration.

> // From react
> import { InstantSearch, SearchBox, Hits, Pagination } from 'instantsearch.js/react'
> // From another environment
> import instantsearch from 'instantsearch.js'

This is very well thought and we are amazed that by just reading and playing with the code you figured it out soemthing that took us long time to think after building instantsearch.js

> Anyway,.. sorry for the long write-up, I just wanted to give some feedback on this.

That's an awesome feedback, we would love to have this conversation at our office maybe? We are in Paris.

**Comment by VonD** [comment]
> I think it might be possible server side to use the helper

Yes, sorry, it is totally possible to use the helper server-side. I was thinking about `helper.on` which made me think we would need to unbind some listeners in the callback - which felt a bit dirty - but I see now that `helper.once` exists.
Now, if we want to use React server-side and have our components work out of the box, we would need to expose a static method to fetch the proper data based on `props`.

> is calling ReactDOM.render multiple time a true antipattern? [...] from the library POV we want to be able to instantiate a widgets at any place in the DOM.

I think calling `ReactDOM.render` is an anti-patten only in the context of a React application. I understand that from the library's POV widgets **have** to do it. I feel that the components could be built in a way that, if they are called from React, they are part of the application's tree, and that the vanilla JS wrappers could do this job of calling `ReactDOM.render` only when it's needed.
In case it helps, here's an example of why I call it an anti-pattern in the context of a React app : let's say your app has a `Search` component instantiating your `instantsearch.js` widgets, and, at a higher level, a `UserSettings` component passing down a `currency` prop. One of the widgets could be set like so : 

```es6
search.addWidget(
  instantsearch.widgets.hits({
    templates: {
      item: hit => <Hit hit={ hit } currency={ this.props.currency } />
    }
  })
);
``` 

Now when the `currency` prop updates, the `Hit` component won't get re-rendered. The `Search` component would need to track that and manually do the job.
`context` getting lost is another reason : if you use `react-router` and that `Hit` contains a `Link` component, you'll get an error on click because `this.context.push` is not defined.

> We first designed the lib to be smart wrappers (widgets), modifying the state of the search and getting hits back to pass them to "dumb" (display only) react components.

Yes, I understand now that it is a hard problem. Ideally, the components would act as React's controlled components, such as `input`. But if they have to be of some use, they have to know something about the structure of the search. This is particularly true of the widgets dealing with facets. Currently the components are dumb, but the widgets are smart, which, in a way, makes of the lib a collection of smart components. If the widgets have to be optional and used only outside of React, we must either put back some of this logic into the components or find a way to make them really dumb.

> we would love to have this conversation at our office maybe?

Yes, I'd be very pleased too :) I'm Paris too and can make myself available this week when you want!

> **VonD** which means the helper's state is either hidden from the rest of the app or to be synced with what manages its state.
> The latter is clearly an anti-pattern. The former is ok if the helper's state can be seamlessly flowed down the entire subtree and the rest of the app doesn't need to know about it
> ...
> **vvo** Can you precise?

I have in mind use-cases where your app needs to know either about the search's state or the results'. For example logging, analytics, routing, ... The last use-case is particularly relevant : if you use a routing component, your `Search` component would be instantiated with some `initialSearch` prop. If you are already in the context of a search and click on some link, e.g `/search/facet1/facet2`, the `Search` component won't be mounted again but re-rendered with the new `initialSearch` prop, set from route params. You would then need to update the `helper`'s state and trigger search again (which is fine). You have here two options : 
* reset the helper's state to none and inject back all params - but maybe you want to keep some of the helper's sate ?
* make some external store the keeper of the state - but you would need to sync the helper with this store


I meant - but I realize now I have to dig much more into the raw API and into the helper - that I feel the helper can be cumbersome to work with if you need to manage the state or to push/replace history yourself.

**Comment by vvo** [comment]
> Yes, I'd be very pleased too :) I'm Paris too and can make myself available this week when you want!

Can you send me an email to vincent@algolia.com to further continue this discussion? We have plans to make instantsearch.js more React friendly, in an iterative way

**Comment by vvo** [comment]
We are going to create reusable React components
