### ISSUE TITLE
Stop updating the url at every keystroke, only update after thresold

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#837]
This is triggering bad behavior on chrome osx and also sometime chrome linux.

There's some good overhead because updating the url seems to not be DOM or V8 but browser related. So if the browser implemented it in a bad way then it fails.

You can ask @olance or @seafoox for visual proof of this slowness, that's impressive.

See #827 

On a UX side in the end updating the url at every keystroke does introduce a rendering noise were two very different part of the interface changes: the url bar, the instant search interface. After disabling it to test the performance I found it less intrusive to only update it after the thresold.

Thoughts?

**Comment by bobylito** [comment]
To proper test UX, you need UX testing ;) Otherwise, all other arguments make sense, kill it :+1:

**Comment by vvo** [comment]
> To proper test UX, you need UX testing ;)

Agree, it was only my own experience that I generalized :D

**Comment by vvo** [comment]
Not so easy because if you do not update it after each keystroke, you will only update it "after some time" and it can lead also to weird behavior (the results are updated then suddenly the url is updated).

There's also a good chance that we are doing at each keystroke with the helper (cloning a lot of things) is slowing down it more.

We need a full perf investigation here before making choices.

**Comment by olance** [comment]
Makes sense!

**Comment by vvo** [comment]
No more discussed.

We optimized the urlSync behavior by removing some loops in the helper. The current behavior to update it at every keystroke then create a state after some time seems to be the best we could come up with for now.
