### ISSUE TITLE
Ability to change the shortened parameters

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#838]
On some integrations, we want to integrate instantsearch without changing the current behaviour (SEO purposes for instance). So we integrate on top of them.
For the URL, most search pages use the `q` query parameter to handle search, which makes it trivial to integrate in them.
However, some others use `query`. For these, it would be really neat to change the shortened version of the `query` parameter in order to have the parameter synchronization directly.

My example:
- Zendesk's `/search` page accepts a `query` parameter.
- I want to keep the default back-end search (which uses `query`) to have decent SEO on a query
- However, by activating instantsearch, I end up with two parameters in the url `/search?query=a&q=a`
- When I change the state the url becomes `/search?query=a&q=abc`.
  If someone shares this URL, the back-end search will return results for `a` and the front-end results for `abc`, which is pretty uncool.

If I could change the "shortened" version of `query` from `q` to `query`, everything would be ultra simple.
I post it here because I believe it could be a `urlSync` parameter.

In order to do so, it would require us to expose the shortener on the helper, which is what https://github.com/algolia/algoliasearch-helper-js/pull/280 aims to do.

**Comment by vvo** [comment]
This is a good idea yes

**Comment by hkdobrev** [comment]
I've tried to do that myself using the helper. I had a problem with existing URLs using `?page=<page>` for pagination and the helper uses `?p=<page>`. Would definitely use this if available.

**Comment by vvo** [comment]
awesome, @Jerskouille already started implementing it in the helper so it should not take too long

**Comment by vvo** [comment]
It was merged in the helper https://github.com/algolia/algoliasearch-helper-js/commit/7d93cac8aac6ae1ca2e50b73270ba139ec9b72fa so it should only be now an issue of implementing it (passing the parameter) and documenting it in instantsearch.js. @Jerskouille are you up to doing it? thx
