### ISSUE TITLE
hierarchicalMenu: hide parent's siblings when a sub level is selected

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#839]
For now when a item is selected in the hierarchicalMenu, if that one contains child elements then it displays those. But at the same time it also displays all the sibling elements of the parent level.

Hidden the parent's sibling items is a UX pattern that we can see on more and more website: Amazon, Birchbox.fr

![image](https://cloud.githubusercontent.com/assets/1101220/13044727/fc8e961c-d3cf-11e5-94d6-1365eb3e6f83.png)

![image](https://cloud.githubusercontent.com/assets/1101220/13044710/e5481fdc-d3cf-11e5-8b7d-acf260d4a784.png)

Could be interesting providing that out of the box, as part of the hierarchicalMenu widget.

PS: That behavior is already handled by the JS Helper https://github.com/algolia/algoliasearch-helper-js#hide-parent-level-of-current-parent-level

**Comment by vvo** [comment]
:+1: low hanging fruit, it's only about creating the right option in instantsearch.js

**Comment by vvo** [comment]
Before we go further on this one, we need to check if the current helper options around hierarchicalMenu would allow us to do that.

Then we can think about how do we propose it as an API entry.

The use case is legit.

**Comment by bobylito** [comment]
I've worked on trying to better explain this feature.

[We are using](https://community.algolia.com/instantsearch.js/v2/widgets/hierarchicalMenu.html#struct-HierarchicalMenuWidgetOptions-showParentLevel) the `showParentLevel` option from the helper. The thing that make this behaviour confusing is that it keeps the sibling values of the root. If that's considered a bug, we should consider filling it on the helper side and then integrate it in all InstantSearch libraries. I will close it for now, until we change the behavior in the Helper.
