### ISSUE TITLE
Make Hits widget focusable and let the user navigate with arrows keys

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#84]
When I do a search, I would like, as a user to be able to browse the results with the arrows of the keyboard. What could be nice is that when I hit the the return key in the search field, the hits are focused and the first element is highlighted.

What do you think?

PS : yes I know, this is not standard / common but most of the websites just fail at doing basic keyboard interaction that I don't consider them as good examples.
PPS : but I would be very interested in using great keyboard experience
PPPS : yes vim bindings would a great easter egg ;)

**Comment by redox** [comment]
Google implements that actually:
 * from the searchbar, hit <TAB>
 * up/down :)
 * enter

**Comment by bobylito** [comment]
And we want to be like google :D

**Comment by vvo** [comment]
Should be doable but maybe behind an option. Using https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/tabindex?

**Comment by bobylito** [comment]
Yes tabindex will be needed to make a div focusable.

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is very old and not done, reopen if you have the need and want to fix it

**Comment by Giovanni-Mattucci** [comment]
Looking for a solution to achieve this.

**Comment by vvo** [comment]
@Giovanni-Mattucci For now you will have to implement it on your side, via some JavaScript custom coding/tabIndex in your hits. This should be doable

**Comment by spoeken** [comment]
Is there a sollution for this now?

**Comment by Haroenv** [comment]
if you are using `connectHits`, you can add keyboard handling there yourself for now
