### ISSUE TITLE
website: Add a tutorials section

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#849]
I propose to add a new tutorials section on the website (givent we write some of them).

If you have tutorials ideas, add them to github and tag them with **tutorial**

**Comment by powtac** [comment]
**instantsearch.js + Bootstrap** is very important for us. Currently almost no layout works for us :-(

**Comment by vvo** [comment]
@powtac Can you open a new issue with specific issues while working with bootstrap? Also feel free to close issues that were solved, thanks
