### ISSUE TITLE
Try searchkit

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#850]
We may have things to learn from https://github.com/searchkit/searchkit so doing the instantsearch demo using searchkit may be a good way to learn from them and enhance instantsearch.js

**Comment by pixelastic** [comment]
Wouldn't this require some knowledge and running instance of ES to get started?

**Comment by vvo** [comment]
Yes it does

**Comment by Shipow** [comment]
up for trying

**Comment by vvo** [comment]
This would be a nice opportunity to see what are they doing well that we do not

**Comment by vvo** [comment]
We are "close friends" now with searchkit and beneficiated from their API design too :D
