### ISSUE TITLE
Create an easy to use API entry to preselect values

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#853]
Being able to specify default selected values can be very handy in all list-related stuff.

Currently you have to dig inside the helper config etc (seehttp://stackoverflow.com/questions/35437004/algolia-initial-search-parameters-instantsearch-js/35440096#35440096).

Today (feb 16) we had 4-5 people asking for this feature and how to do it (even Algolia employees)

To solve this recurring issue, I propose something like this:

```js
refinementList({
 ...,
 preselectedValues: ['..'],
 cssClasses: {
    preselectedValues: 'hide'
  } 
})
```

What do you think?

**Comment by collegeminer** [comment]
![algolia-error](https://cloud.githubusercontent.com/assets/2465014/13225979/4fb4fe66-d95d-11e5-9877-1d4cbb6d0d20.png)

I tried adding to the item class. It adds it to the object.cssClass, but fails to add to the html. See the image.

  if (preselectedCategories.indexOf(item.name) !== -1) {
                     console.log(item);
                     item.cssClasses.item += ' pre-selected';
                 }

**Comment by vvo** [comment]
@collegeminer Hi! Please can you open a new issue and explain your problem with some context?

Provide the full reproducible code that you used and what you are trying to achieve. Thanks.

**Comment by collegeminer** [comment]
Added here https://github.com/algolia/instantsearch.js/issues/866

**Comment by vvo** [comment]
see #1062
