### ISSUE TITLE
Allow passing the min max values of the slider programmatically

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#858]
Instead of relying only on the facet stats.

It's a user requirement, cc @trek can you precise how this would help you? I mean what's the underlying need to not just use the facets min max computation?

**Comment by vvo** [comment]
This all boils down to creating min and max options in the range-slider widget then always pass them to the underlying Slider component.

**Comment by trek** [comment]
Sorry for the delayed reply and also not tackling this myself (maintaining my own OSS stuff around Ember.js eats most of my OSS time)

The change at https://github.com/algolia/instantsearch.js/commit/409295cc80c90a29141c101c90e45bdd24817514 is what we needed.

> I mean what's the underlying need to not just use the facets min max computation?

On an empty query, the min/max values for each facet don't (currently) represent the whole set. @speedblue explained why in an email and suggested allowing user override would be a good short-term solution.

**Comment by vvo** [comment]
@trek Thanks a lot for getting back here and give feedback. This is now released!
