### ISSUE TITLE
Warn when unknown option used anywhere in the API

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#860]
We currently do not warn on unknown option when used in a widget, could be cool. It saves time when debugging.

First steps for this issue would be to identify and list the possible cases where warning would really help our users. For example: "Creating a menu while the facet is not an attribute for faceting"

**Comment by bobylito** [comment]
:+1: I was thinnking of a step beyond that yesterday : what about we check the edit distance with the keys of the known options, so that we can provide a message like "you used [blah] options which is not recoganized, maybe you meant [bloh]". What do think? Overkill? :)

**Comment by vvo** [comment]
Good idea but maybe overkill, we could have the usage showing up, should be enough.

Also always a bit weird situation where "Hey did you mean 'good-option-name'?
=> YES I meant it, please fix this for me, smart computer program :dancer:

**Comment by bobylito** [comment]
It is possible to create a key that is able to only get the settings. But that requires to have a new custom key generated by the user... Would also require to have the plumbing to create the first query to check the configuration.

Maybe that could be a dev tool? Offline check before the production?

**Comment by Haroenv** [comment]
We can make it not impact the production build by giving the errors in `if (process.env.NODE_ENV === "development")`, which can be filtered out in webpack with either:

````js
new webpack.DefinePlugin({
  'process.env': {
    NODE_ENV: JSON.stringify('production')
  }
}),
```

or

```js
  new webpack.EnvironmentPlugin({
    NODE_ENV: 'development', // use 'development' unless process.env.NODE_ENV is defined
  }),
```

combined with uglify.

See as well how [react](https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build) does it.

**Comment by rayrutjes** [comment]
I think I mainly see it used like `if (process.env.NODE_ENV !== "production")`.
That way if production is mistyped, you get the errors ;) (I suppose there are other reasons as well)

**Comment by bobylito** [comment]
When a parameter is not recognized, it returns an error and this pretty fast to see with the initial search. For the parameters that are not throwing an error, we only have the facets as a use but we didn't have much problems so far with that. Let's close this issue for now and revisit if we get a brilliant idea or if we identify a pain.
