### ISSUE TITLE
Selected category in menu reorder when equal number of items

### ISSUE THREAD

**Issue by esquire900** [algolia/instantsearch.js#862]
When selecting an item from the menu widget which has a similar number of items as other items in the menu, it is reordered which is rather unexpected
![image](https://cloud.githubusercontent.com/assets/2980417/13144919/b68a9ac8-d64d-11e5-9564-fb6cb1f905d1.png)
![image](https://cloud.githubusercontent.com/assets/2980417/13144922/bc13d554-d64d-11e5-9ebf-dbc65f91bde6.png)

**Comment by vvo** [comment]
Thanks for the bug report, we will have a look asap
