### ISSUE TITLE
Adding to item.cssClasses.item doesn't work

### ISSUE THREAD

**Issue by collegeminer** [algolia/instantsearch.js#866]
CSS 

```css
 .pre-selected {
  display: hidden;
}
```

JavaScript
```js
search.addWidget(
         instantsearch.widgets.refinementList({
             transformData: function (item) {
                 if (preselectedCategories.indexOf(item.name) !== -1) {
                     console.log(item);
                     item.cssClasses.item += ' pre-selected';
                 }
                    return item;
             },
             container: '#skills',
             attributeName: 'SkillName',
             operator: 'or',
             limit: 1000,
             templates: {item: facetTemplateCheckbox,
                header: '<div class="facet-title">My Skills</div class="facet-title">'}
         })
       );
```

Problem - Look at screenshot below. It adds correctly to the object.cssClass but isn't added to the HTML. 

![algolia-error](https://cloud.githubusercontent.com/assets/2465014/13226296/c5990450-d95e-11e5-86ea-42320d2beaf2.png)

**Comment by vvo** [comment]
Can you show the complete code by editing your question? It lacks some context like what is `facetTemplateCheckbox`?

**Comment by vvo** [comment]
Also it's not "display: hidden" but "display: none"

**Comment by collegeminer** [comment]
`  var facetTemplateCheckbox =
       
       '<a href="javascript:void(0);" class="facet-item">' +
         '<input type="checkbox" class="{{cssClasses.checkbox}}" value="{{name}}" {{#isRefined}}checked{{/isRefined}} />{{name}}' +
         '<span class="facet-count">({{count}})</span>' +
       '</a>';`

**Comment by vvo** [comment]
Here's a jsfiddle doing exactly what you asked: https://jsfiddle.net/n51573u9/

**Comment by collegeminer** [comment]
Exactly what I needed! Thank you.

The correct answer is ` item.cssClasses.item+= ' hide';` needed to be changed to ` item.cssClasses.label += ' hide';`

**Comment by vvo** [comment]
Great! Thanks a lot for the feedback, you can always come to github to ask questions, thats the best, open way.

We uncovered a nasty bug here, updating "item.cssClasses.label" do not work. Thanks.
