### ISSUE TITLE
Menu as a select field

### ISSUE THREAD

**Issue by candypaint** [algolia/instantsearch.js#868]
Is there any simple way to have the menu widget appear as a select field? Also to have the first option to be "All" that would remove the refinement?

**Comment by vvo** [comment]
Hi, do you mean you would want the menu to have the form of a `<select>` element?

**Comment by candypaint** [comment]
Exactly. But I also want to have the first and default item to be "All" where the refinement is removed.

**Comment by vvo** [comment]
@candypaint I must say you will have to implement this widget yourself using our:
- widget API: https://community.algolia.com/instantsearch.js/documentation/#custom-widgets
- algoliasearch-helper: https://github.com/algolia/algoliasearch-helper-js

This is basically the only tools we use to build custom widgets. If you have some coding experience this is feasible.

Let's say you want to build a menu on the "categories" attribute name:

1. Use the `getConfiguration` method to add your attribute name use for faceting as a disjunctive facet:

```js
var selectCategories = {
  getConfiguration: function() {
    return {
      hierarchicalFacets: [{
        name: 'categories',
        attributes: ['categories']
      }]
    }
  }
};
``` 
2. Use the `init` function to bind the change event to then refine the selected value with the helper

```js
var selectCategories = {
  getConfiguration...,
  $selectCategories: document.querySelector('#select-categories'),
  this._refine: function(helper, changeEvent) {
    // this is where we refine the categories
    helper.toggleRefinement('categories', changeEvent.target.value);
    // now trigger a new search
    helper.search();
  },
  init: function(params) {
    this._refine = this._refine.bind(this, params.helper);
    // regular HTML/JS coding to create or bind to an existing select box change event
    this.$mySelect.addEventListener('change', this._refine);
  }
};
```

Here's the `select` html that you need to put in your page
```html
<select id="select-categories"></select>
```

3. Use the `render` method to fill the select at each new results:

```js
var selectCategories = {
  getConfiguration...,
  $selectCategories...,
  this._refine...,
  init...,
  render: function(params) {
    var hasCategorySelected = params.helper.hasRefinements('categories');
    var all = {name: 'All', value: ''};
    if (!hasCategorySelected) {
      all.isRefined = true;
    }
    var results = [all];
    results = results.concat(params.results.getFacetValues('categories').data || []);
    var selectValues = results.map(function(result) {
      return '<option value="' + result.value + '"' + result.isRefined ? ' selected' : '' + '>' + result.name + '<option>';
    });
    this.$selectCategories.innerHTML = selectValues;
  }
};
```

4. Add your widget to instantsearch:

```js
search.addWidget(selectCategories);
search.start(); // should already be present in your page
```

Some steps might not be accurate and the code might fail but that's the general idea. If you have any question, add it here.

**Comment by candypaint** [comment]
Thanks. Got the idea.

I still think you should consider having it built in as a option. The long list of categories for refinement is not practical in most cases for mobile.

**Comment by vvo** [comment]
@candypaint That's a good idea. We are currently not focused enough on mobile indeed.

**Comment by combs** [comment]
yes @vvo this would be very nice as a basic builtin for instantsearch.js. Would make Algolia instantsearch.js a lot more mobile friendly, which would of course help the bulk of our 1m+ monthly unique users.

**Comment by vvo** [comment]
See #1904, thanks for feedback

**Comment by combs** [comment]
Super, thank you @vvo!

**Comment by Brotakuu** [comment]
Is there support for converting a `numericRefinementList` into a `numericSelector` or `menuSelector`?

For example, my widget options look like this:

```
    options: [
      {name: 'Any'},
      {start: (timeNow-86400), end: timeNow, name: 'Past 24 hours'},
      {start: (timeNow-592200), end: timeNow, name: 'Past Week'}
    ]
```

**Comment by bobylito** [comment]
Hi @Brotakuu. Can you describe in more details what would you like to achieve?

**Comment by sjelfull** [comment]
@bobylito I'm looking for the same. Basically, we want to show `numericRefinementList` as a `select` instead of a list of radio buttons.

**Comment by Haroenv** [comment]
@sjelfull you can use `connectNumericRefinementList` and make it into a select. I’m on my phone now but the example in the documentation is exactly that, but you just need to change the DOM tags.
