### ISSUE TITLE
[rangeslider] Let the user configure set the min and max values.

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#870]
There is an issue in Algolia engine that makes the empty query return wrong min and max values. One quick fix is to let the user configure a fixed min and max values.

What do you think?

**Comment by vvo** [comment]
Yes we should do it.

I think its a duplicate of https://github.com/algolia/instantsearch.js/issues/858. If that's the case you lost 20 points in the contributor game. :D

**Comment by bobylito** [comment]
Oh no!! #fail
