### ISSUE TITLE
Accessing the highlighted results

### ISSUE THREAD

**Issue by mojosef** [algolia/instantsearch.js#871]
Hi

Is it possible to access the highlighted result using instantsearch? I want to show what was found as I'm not necessarily displaying all the information.

Thanks

Joe

**Comment by vvo** [comment]
@mojosef Yes you can access it in hit your template with `{{{_highlightResult.name.value}}}` for example.

Is that what you are looking for?

**Comment by mojosef** [comment]
Hi
Thanks for your reply! Yeah that's what I tried. I was hoping to pass it to a helper to loop through and find out what was matched on. But I just get the text I've just realised. Is there any way of passing it into a function?

search.templatesConfig.helpers.highlightResults = function (text, render){
    //loop through _highlightResult Object
}

**Comment by vvo** [comment]
I am not sure to get your usecase, what are you trying to achieve in term of user interface?

**Comment by mojosef** [comment]
I maybe display 3 items out of my object but the search is set up for maybe 10 items in the object. I'd like to display on the result hits what triggered the result?

I hope that makes sense

**Comment by vvo** [comment]
Can you inline an example simplified _highlightResult object that you got and how would you want to display it ultimately. So that I can better understand what you are trying to filter.

**Comment by mojosef** [comment]
Hi Vincent

So basically my app is being used in a matching system. The user will search for suitable matches and be presented by a limited amount of information. However in the results, say for example the result matched on 'eye colour'. I want to display the this is why this particular hit was presented. This is how I'd like it to work...

```
<div class="hit">
	<div class="resultReason">@{{#helpers.highlightResults}}@{{{ _highlightResult }}}@{{/helpers.highlightResults}}</div>
	<div class="result">
		<p>Name: @{{ fname }} @{{ lname }}</p>
		<p>Email: @{{ email }}</p>
		<p>Town: @{{ town }}</p>
		<p>Age: @{{ age }}</p>
		<a href="/profile/@{{ id }}">Full Profile</a>
	</div>
</div>


<script>
//
//SEARCH CODE ETC
//

search.templatesConfig.helpers.highlightResults = function (text, render){
	//loop through _highlightResult
	//
	//Create Message
	var message = "<div>This result was matched on:" + _highlightResult.title;
	//add to hit result
	return message;
}
</script>
```

**Comment by vvo** [comment]
Ok thanks for clarification. You can use the hits option.transformData.item: function(item) {} to add any pre-computed data (where you would have done your loop inside) to the item and then access it.

For example:

```js
var hits = instantsearch.widget.hits({
  transformData: {
    item: function(item) {
      item.matchedData = ...
      return item;
    }
  }
});
```

Then in your template, use item.matchedData.

As for helpers, you need to use them like this:

```js
search.templatesConfig.helpers.highlightResults = function (text, render){
  var data = render(text);
  return modifiedData(data)
}
```

To get the actual data object you need to call render on the passed text, this is a bit weird but how hogan.js (our template engine) works with helpers.

**Comment by mojosef** [comment]
Thank you so much, you are definitely my fave person at the minute haha

**Comment by IAmDragon** [comment]
@vvo Hey, trying to do this in the same way (Kind of)

I don't understand what you're doing with the item.matchedData, I'd like to ideally just have each hit list kind of like this - I store certain things in arrays (I have Acting Credits and in it might be
`'actingcredits' = ['The Incredible Hulk, Co-Star, Michael Whocares, Film', 'Next Move Credit Whatever']`

I'd like to display the matched items as in searching for Hulk might bring out

`'<a href="https://mywebsite.com/{{username}}">{{name}}</a>: The Incredible _Hulk_, Co-Star, Michael Whocares, Film'`

Can I modify your code to allow that?

**Comment by vvo** [comment]
Hi @IAmDragon, can you open a new issue describing your problem in full length? This one was closed and might be hard to discuss here. Thanks!
