### ISSUE TITLE
When searchOnEnterKeyPressOnly is true, URL is still updated on each keystroke

### ISSUE THREAD

**Issue by hkdobrev** [algolia/instantsearch.js#875]
Related to #837, but this is a separate issue only when `searchOnEnterKeyPressOnly` option is set to `true`.

I would expect when search is triggered only on Enter, the URL to also be updated only when Enter is pressed and search is performed. However the URL is actually updated on each keystroke.

**Comment by u3804** [comment]
Experienced the same issue (have stayed with 1.1 in the interim).  Thanks to @hkdobrev.

**Comment by vvo** [comment]
Indeed, that's a bug
