### ISSUE TITLE
disjuntivefacets with nested data

### ISSUE THREAD

**Issue by collegeminer** [algolia/instantsearch.js#877]
Below is a user, I need to set a disjunctive facet on Skills.SkillName (eg where Skills.SkillName = 'SQL' OR 'Accounting')

 {"FirstName" : "John",
  "LastName" : "Smith",
  "JobFunction" : "Information Technology",
  "Skills" : [{
      "SkillID" : "2vRdiqCOE2XBDS3nsS1LA",
      "SkillName" : "SQL",
      "SkillRating" : 3
    }, {
      "SkillID" : "WEPMtg3JkU2xlpmgmvkYQ",
      "SkillName" : "Accounting",
      "SkillRating" : 4
    }, {
      "SkillID" : "d9c514035a554a5d8d99c411e43b683d",
      "SkillName" : "Leadership",
      "SkillRating" : 4
    }]}

Ive attempted a lot of different things, but here is what I think makes sense:

`var preselectedCategories = ['SQL', 'Accounting'];
var search = instantsearch({
    appId: 'appid',
    apiKey: 'api',
    indexName: 'UserActivity',
    searchParameters: {
        disjunctiveFacetsRefinements: {
            Skills: {
                SkillName: preselectedCategories
            }
        }
    }
});`

Documentation is definitely lacking on this so any help will be greatly appreciated. Thanks!

**Comment by bobylito** [comment]
Can you try with:

```js
 "disjunctiveFacetsRefinements": {
    "Skills.SkillName": ['SQL', 'Accounting']
  }
```

**Comment by collegeminer** [comment]
This worked, but however when we log the hit it doesnt retrieve the records. 
`var preselectedCategories = ['Data', 'SQL'];
var search = instantsearch({
    appId: '1VPDOL194L',
    apiKey: 'a1c4dfaccd605139795a6ba19a46cf56',
    indexName: 'UserActivity',
    searchParameters: {
        "disjunctiveFacetsRefinements": {
           "Skills.SkillName": preselectedCategories
        }
    }
});`


Then adding the widget:
`search.addWidget(
  instantsearch.widgets.hits({
      container: '#hits',
      hitsPerPage: 10,
      templates: {
          empty: noResultsTemplate,
          item: newTemplate
      },             
      transformData: function (hit) {
          hit.stars = [];
          for (var i = 1; i <= 5; ++i) {
              hit.stars.push(i <= hit.rating);
          }          
          console.log(hit);
          return hit;
      }
  })
);`

Here are the results in the console:
![disjunctive](https://cloud.githubusercontent.com/assets/2465014/13402971/b729f500-dee0-11e5-830e-04625e49cf58.png)

**Comment by collegeminer** [comment]
this issue is pretty much resolved, but taking this one step further how do you do:

where Skills.SkillName = 'SQL' OR 'Accounting' OR ToUser.Email = 'john@email.com'

this does not work as it is essentially doing:
where Skills.SkillName = 'SQL' OR 'Accounting' AND ToUser.Email = 'john@email.com'

 var search = instantsearch({
        appId: '1VPDOL194L',
        apiKey: 'a1c4dfaccd605139795a6ba19a46cf56',
        indexName: 'UserActivity',
        searchParameters: {
            "disjunctiveFacetsRefinements": {

                "Skills.SkillName": preselectedCategories, "ToUser.EmailAddress": emailaddress

            }
        }
    });

How can we do this? Thanks!

**Comment by bobylito** [comment]
This is not possible with the underlying component of instantsearch called algoliasearch-helper. I created an issue https://github.com/algolia/algoliasearch-helper-js/issues/290
