### ISSUE TITLE
Limited number of sub-categories coming from algolia

### ISSUE THREAD

**Issue by prspace** [algolia/instantsearch.js#882]
In this image we have clearly have a third lavel of subcategory name 'backpackers'
![algolia hosted cloud search as a service 2016-03-01 13-10-24](https://cloud.githubusercontent.com/assets/8875411/13420814/5022fdaa-dfaf-11e5-9f66-a85bc6b5dbd7.png)

But it's not coming in our hierarchy menu ....
![search eventerprise 2016-03-01 13-13-51](https://cloud.githubusercontent.com/assets/8875411/13420860/a76a80b0-dfaf-11e5-88ba-77fe5ac4252b.png)

and my hierarchicalMenu widget code is like that...

    search.addWidget(

                instantsearch.widgets.hierarchicalMenu({
                    container: '#category',
                    attributes: ['category_navigation.lvl0', 'category_navigation.lvl1', 'category_navigation.lvl2'],
                    cssClasses: {
                        root: 'category_tree',
                        active: 'item_active'
                    },
                    templates: {
                        item: '<a href="javascript:void(0);" title="{{fullname}}" data-customfacet="{{facet}}" data-customname="{{name}}" class="facet-item {{#isRefined}}active{{/isRefined}}"><span><img id="{{slug}}" src="{{icon}}"></span> <span>{{name}} ({{count}})</span></a>'
                    },
                    transformData: function (hit) {
                        hit.facet = 'category_navigation.lvl0';
                        hit.slug = hit.name;
                        hit.icon = ParentCategories.indexOf(hit.slug) == -1 ? categoryImageSrc : base_url + '/img/category_img/'+hit.slug+'.svg';
                        hit.fullname = hit.name.replace(/-/g, " ").capitalizeFirstLetter();
                        hit.name = niceText(hit.name);
                        return hit;
                    }
                })
        );
`

What should i do now? Is there anything more i have to do with this widget? thanks.

**Comment by vvo** [comment]
@prspace We limit the number of returned categories by default to only show the most relevant ones (most counts), can you try with passing the `limit` option?

```js
search.addWidget(
  instantsearch.widgets.hierarchicalMenu({
    // all other options, then
    limit: 20
  });
);
```

**Comment by prspace** [comment]
I have already tried with limit but no luck.

**Comment by vvo** [comment]
Indeed, that's a bug I am fixing.

**Comment by vvo** [comment]
Fixed and released a new version of instantsearch.js:1.2.5

**Comment by prspace** [comment]
Ok thank you. That would be very helpful.

**Comment by seulZarraga** [comment]
I have de same issue, I put limit 20, and the issue continue.
