### ISSUE TITLE
Passing the item position to `transformData`? 

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#903]
For the latest integration I did, I had to apply a specific markup to the 4 first displayed hits. In my case it was _not_ applying lazyloading of images to those elements.

So I needed to know, from inside the `transformData` method, the current position of the item in the returned set.

There is no easy way to do that at the moment, so I resorted to a hack involving setting a global counter (reseted on every `on('render')`), and increasing it on each call to my `hits.transformData`. It worked, but was far from optimal (code is separated in several parts, I have no clear guarantee that the `transformData` are actually executed in order), etc).

So I'm wondering if we shouldn't change the `transformData` signature to `transformData(item, position)` instead of just `transformData(item)`.

WDYT?

**Comment by vvo** [comment]
Yes good small improvement. Ultimately we would only propose a global transform function (not just per hit, but for all the hits where you have to return the full object).

**Comment by vvo** [comment]
Taking PR :)

**Comment by pixelastic** [comment]
Could you elaborate on: 

>  Ultimately we would only propose a global transform function (not just per hit, but for all the hits where you have to return the full object).

Do you mean we already have this in the works somewhere? Would it also work for `refinementLists` or only `hits`?

I'll try a PR on that subject, just to see the scope of the PR :)

**Comment by vvo** [comment]
@pixelastic Your addition is fine for now and your usecase.

Send a PR :)

-----

For more information and future evolution of transformData:

In the future I would like to only provide this:

```js
transformData(collection) {
  collection = collection.map(...).filter(...);
  return collection;
}
```

So that you can do any crazy stuff with the collection passed. For anything lists (so hits, refinement list etc...).

See https://github.com/algolia/instantsearch.js/issues/739 and https://github.com/algolia/instantsearch.js/issues/739#issuecomment-164774874

**Comment by pixelastic** [comment]
I'm now wondering if `transformData(data, position)` is the right approach. If I define my own template, I won't have access to this `position` variable...

Maybe extending the `data` passed to `templates.item` and `transformData.item` with a `__position` key instead?

Now that I know that I can pass functions to `templates`, I no longer need `transformData`...

**Comment by vvo** [comment]
> Now that I know that I can pass functions to templates, I no longer need transformData...

True :)
