### ISSUE TITLE
Date/Month picker

### ISSUE THREAD

**Issue by davidpike7** [algolia/instantsearch.js#906]
Whilst looking at your tourism [demo](https://community.algolia.com/instantsearch.js/examples/tourism/) I noticed that the date picker doesn't seem to work.

Are there plans to include a date/month picker widget? Its a featured we'd be very interested in for our tourism based client

**Comment by redox** [comment]
Hi David,

> Whilst looking at your tourism demo I noticed that the date picker doesn't seem to work.

yes indeed, we disable it for the demo purpose (was too complex to have a dataset that will work if you change the underlying booking date) but it's definitely a widget that would make a lot of sense for instantsearch.js

I would just wrap an existing date picker library like we did for:
 - the ionRange slider: https://github.com/instantsearch/instantsearch-ion.rangeSlider
 - or Google Map: https://github.com/instantsearch/instantsearch-googlemaps

I don't think that's on the short-term roadmap on our side, but maybe the community (you?) can help building one? We would be happy to promote it on our instantsearch.js website!

**Comment by vvo** [comment]
we need to build one, multiple users showed interest

moved to #1077
