### ISSUE TITLE
Page jumps to top on every refinement

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#91]
Currently, the whole page jumps to top when I add refinements (categories, price range and sometimes free shipping).

This is not desirable as the I lose what I was currently looking at.

This might be caused by the `href="#"` links and I think @bobylito is working on that. We should make sure to have a consistent behavior on all widgets for that.

**Comment by vvo** [comment]
All refinement widgets should receive the corresponding "state change" as a precomputed {{href}}. Is that #29?

**Comment by vvo** [comment]
And yes when clicking on href=# it jumps to the top because there's no preventDefault on links, @bobylito is working on it :).

**Comment by bobylito** [comment]
Yes (but as a way to fix a side effect :) )

**Comment by vvo** [comment]
solved by #95
