### ISSUE TITLE
make tourism dates a date picker or make them editable

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#914]
bit of a shame otherwise

**Comment by redox** [comment]
It was on purpose because too complex to have the underlying dataset compliant with non-fixed dates. Happy to find an alternative :)

**Comment by vvo** [comment]
Yes I remember that (on purpose). Maybe we can just remove them or gray them more explicitly. It seems right now they could work but the click is not working (+ add a tooltip "this is just a demo")

**Comment by redox** [comment]
Arg indeed, my "disabled" styling has been lost here: https://github.com/algolia/instantsearch.js/commit/b6692a3b51556bf966f11320e08bace7d4e799ef#diff-0bef9ae98cf9cc145c4e1afd8bb65d1dL33

**Comment by vvo** [comment]
ok will add it back
