### ISSUE TITLE
[searchBox] Powered by

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#92]
Based on this issue ( https://github.com/algolia/instantsearch.js/issues/25 ), I'm not sure anymore that the search input will be a widget, but if it is, it could be great to embed the "Powered by" with it, enabled by default.

What do you think?

**Comment by bobylito** [comment]
It is a widget and I think it'll stay that way. Why not adding the option :)

**Comment by vvo** [comment]
Dunno if it should be enabled by defaultm especially for paying customers it might feel weird

**Comment by bobylito** [comment]
well activated by default is not great yeah. But the option would be useful to avoid people that don't have the time to invest on adding an algolia :) No excuse :)

**Comment by Jerskouille** [comment]
You're right, it makes sense only on integrations where this can be relayed to the configuration panel.

**Comment by redox** [comment]
it's definitely something we need to have to ease our community plan. We could also have it in the Stats widget.

**Comment by pixelastic** [comment]
I would put it by default but with an easy option to turn it off (directly from the widget for manual install, but also from the dashboard of our magento-like implementations)
