### ISSUE TITLE
[searchBox]: queryHook not called on initial search

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#921]
Currently the `queryHook` parameter to the `searchBox` widget is not called on the initial search (the one we usually refer to the "empty query").

This seems broken because it is correctly fired if I start typing something then delete everything (in essence getting back to the "empty query").

I'm not sure if this is a bug or if it is by design, tough.

**Comment by vvo** [comment]
What you are looking for is the searchFunction hook which is a global hook of the instantsearch({searchHook}).

The query hook is only called when the user actually type something.

**Comment by pixelastic** [comment]
Oh, so `queryHook` is more like a `keypressHook`. Thanks, I'll update my code to use that instead.

**Comment by vvo** [comment]
Yes it's more of a keypressHook, named queryHook because it's the hook that is called just before making the query from the searchbox.

We could rename it though because it's very new so won't be so hard.

**Comment by pixelastic** [comment]
It's called `searchFunction` and it works perfectly, thanks.

**Comment by vvo** [comment]
awesome :)

**Comment by pixelastic** [comment]
What about renaming `searchFunction` to `beforeSearch` et `queryHook` to `onKeyPress`?

**Comment by vvo** [comment]
beforeSearch could be understood as being an event like hook: not actually expressing we are replacing the search function.

onKeyPress is kind of the same, how does it says it's replacing the default query?

Naming is hard!

**Comment by vvo** [comment]
onKeyPress can be ok, not sure about beforeSearch

**Comment by vvo** [comment]
You may also be victim of previous issues titles that we discussed where it was proposed as "beforeSearch" #823. :D

**Comment by pixelastic** [comment]
Both methods currently expect you to call a callback to continue the initial flow. It you just define them with a `noop`, everything is broken :p.

I feel like they should have a similar naming for that reason.

Actually, on a broader topic I feel like we have three kind of methods:

- The event, that you can just listen to and react to, but in a "forked" workflow. Like the `on('render')`.
- The method getting a value as input ( `transformData`) and expecting you to return a new version of the data
- The method with a callback as input, expecting you to call it when you're done to resume the normal workflow

My point is that we should be able to clearly know which kind of method we're dealing with from their name. Do you think that would be a good idea?

We could still maintain backward compatibility by keeping the old names.

**Comment by vvo** [comment]
> It you just define them with a noop, everything is broken :p.

Yes that's on purpose, once you use the hook, you need to call the search function/call the callback. That's the API exposed so that you can implement complex patterns with it (debounce, min length, act on helper, do an asynchronous call to an API..).

> My point is that we should be able to clearly know which kind of method we're dealing with from their name. Do you think that would be a good idea?

Yes, as you said:
- we have **events**. As for libs I use, events are better being things that you can only listen to, only the DOM provides things like events + event object you can cancel. But only given the complexity of those.
- we have hooks (searchFunction, queryHook), we could maybe call them that way, searchHook, queryHook
- then we have formatData but I am not sure there's a need to change anything to it, we did not have issues about it or misunderstanding. The only one being that people would like to reformat the whole dataset, not per hit (thats another topic)

**Comment by pixelastic** [comment]
I think you summarized this well. No need to change our events or `transformData`-like methods. And this is not a big issue, we just have trouble remembering the option names

The naming issue might only come from:

- `queryHook` is called on every keypress, with the actual query and the helper as parameters
- `searchFunction` is called just before a search is made, with only the helper as parameter

Maybe replacing them with:

- `onQueryChangedHook`, in the searchbox widget
- `beforeSearchHook` more globally

Just throwing ideas here. WDYT?
