### ISSUE TITLE
How to declare my attributes for faceting ?

### ISSUE THREAD

**Issue by clementvp** [algolia/instantsearch.js#927]
Hi,
I want to know how to declare my attributes for faceting ?
I don't want to declare them in my dashboard, because there are generated.
I see the searchParameters options but i d'ont find how to declare the attributes for faceting with instant Search.

when i do: 

var search = instantsearch({
  appId: 'myAppId',
  apiKey: 'MyKey',
  indexName: 'Agoarts',
  searchParameters: {
    facets: [
      'coloris'
    ]
  }
});

There are nothing, i see hts and results, but not my coloris filter.
I have to go through the js api ?
If yes, how to do that with Instant Search and it's widgets ?

Thanks you for your attention :)

**Comment by vvo** [comment]
Hi Clementvp, you need to declare the attributes for faceting in the dashboard OR use the REST settings call to set them from a script for instance that would run on your infrastructure: https://www.algolia.com/doc/rest#change-index-settings

The JS client has a setSettings method: https://github.com/algolia/algoliasearch-client-js#index-settings

Then once the attributes for faceting are defined in your settings, you can use any refinementList or menu or hierarchicalMenu widget.

Let me know how it goes.

**Comment by clementvp** [comment]
Ok good form me with the REST API.

But when i try with the JS client and the setSettings method, like that:

var client = algoliasearch('APPID', 'APPKEY');
var index = client.initIndex('Agoarts');
index.setSettings({attributesForFaceting: ['coloris', 'dimension', 'prixttc']});

Console give me:  AlgoliaSearchError: This method is only available in HTTPS. Why ? 
( my tests are in local).

Thank you for your reactivity.

**Comment by vvo** [comment]
@clementvp when you run a JS script with the JS client we default to the page protocol for all calls. This is something we can fix for all writes to the API since they need to be done in https.

You can either run this script in node.js OR do this:

```js
var client = algoliasearch('APPID', 'APPKEY', {protocol: 'https:'});
```

Thanks

**Comment by clementvp** [comment]
Ok thanks :)
