### ISSUE TITLE
performing a facet search

### ISSUE THREAD

**Issue by filimar2** [algolia/instantsearch.js#929]
Hi guys,

I am trying to perform a search based on a given facet that I previously set up in Algolia. Something like this:

 if($("#hits").length){
           InstantSearch.addWidget(
	        instantsearch.widgets.hits({
	            container: '#hits',
	            hitsPerPage: 10,                   
                    facetFilters: [
                                            {"parentCategoryName:Art"}
                                        ]
	        	templates: {
	                item: getTemplate('hit'),
	                empty: getTemplate('no-results')
	            }
	        })
    	);
    }

I don't know if this is meant to be done in "hits" or "searchbox"
Help would be much appreciated!!! Thanks

**Comment by vvo** [comment]
Hi filimar, I believe what you want is to pre-select a specific filter for your search interface?

The hits widgets has no facetFilters option. You should use this:

```js
var search = instantsearch({
// ... other options
searchParameters: {
  facetsRefinements: {
    parentCategoryName: ['Art']
  }
}
});
```

let me know

**Comment by filimar2** [comment]
You saved my life dude!! Thanks so much!!

**Comment by vvo** [comment]
OSS FTW!

**Comment by joshuabaker** [comment]
Is this documented somewhere?

**Comment by pixelastic** [comment]
It is hidden in the Helper documentation, but I just submitted a PR to have a mention of it in the instantsearch documentation.

https://github.com/algolia/instantsearch.js/pull/1027

'd appreciate your feedback @joshuabaker, to tell me if this is clear enough
