### ISSUE TITLE
[slider] make tooltips contenteditable

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#93]
Something like this would be fun (@bobylito idea):

![untitled screencast 5](https://cloud.githubusercontent.com/assets/123822/9878898/474f5390-5bc5-11e5-84f6-351f0f247d22.gif)

In order to do so, [algolia/noUiSlider](https://github.com/algolia/noUiSlider) must first be enhanced to provide this new option:

```js
tooltips: {
  format: function() {},
  editable: true
}
```

Then:
- we would have to parse the formatted tooltip in search for the numeric value
- isolate the numeric value inside a `<span contenteditable="true"></span>`
- allow clicking the tooltip (currently it's e.preventDefault). We need to isolate drags from clicks (mousedown/touch + move = drag, mousedown/touch + mouseup/touch = click)
- listen for contenteditable changes, update the slider and refinement accordingly
- automatically reformat tooltip value after 100ms with no keystroke

Annnnd a lot of other possible issues to fix. But still a good idea to provide a good slider

**Comment by redox** [comment]
Hmmm, not yet sure about the UX behind that guys; keep in mind we're mostly targeting non-advanced users. @Shipow ?

**Comment by vvo** [comment]
Yes it's not obvious you can do it even when I did the small demo. Inputs are more recognized as being editable.

**Comment by bobylito** [comment]
Not sure that it will work with user either. But it sure look nice on paper ;)

About the currency, maybe we could anything but the number non editable?

**Comment by vvo** [comment]
> maybe we could anything but the number non editable?

Yes that would be a strategy, make

**Comment by pixelastic** [comment]
This is part of the main guidelines of #135 .

**Comment by vvo** [comment]
Maybe we can close this and move all slider current improvment ideas to #135. Then create issues once we know WHAT to do.
