### ISSUE TITLE
PR sent to master are accepted by default

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#931]
See https://github.com/algolia/instantsearch.js/pull/930

cc @pixelastic?

**Comment by pixelastic** [comment]
Hmm, yes that's weird.

**Comment by pixelastic** [comment]
What is even weirder is that it's not that the Travis check is always succeeding, it's that the Travis check does not even start.

**Comment by pixelastic** [comment]
^ actually, I got confused by the GitHub display. I'm testing PR on master/develop.
