### ISSUE TITLE
Should urlSync allows attribute names mapping?

### ISSUE THREAD

**Issue by fitztrev** [algolia/instantsearch.js#933]
With the URL mapping from #922, is it possible to map hierarchical facets to a different name?

For example, here is my configuration and the query string it generates:

##### Current:

```javascript
mapping: {
    'q': 'query',
    'p': 'page',
    'hPP': 'hits',
    'hFR': 'filter',
},
```

```
?query=&page=0&filter[facets.facets.fits.make][0]=Ford&is_v=1
```

##### Desired:

Without changing the structure of the record inside my index, could I configure it so it's like this?

```
?query=&page=0&filter[make][0]=Ford&is_v=1
```

Or, better yet:

```
?query=&page=0&make[0]=Ford&is_v=1
```

**Comment by vvo** [comment]
I think this is not feasible @fitztrev, you can only map the parameters names (q, query...) not the attribute names unfortunately.

There's no easy way to do so. It would require more changes in the helper: https://github.com/algolia/algoliasearch-helper-js/pull/281

**Comment by vvo** [comment]
This will be provided in react-instantsearch

**Comment by NicolasPK** [comment]
Hi @vvo,
Is this still not feasible? If so, is this feasible only by using the react implementation like you said back then?

**Comment by Haroenv** [comment]
@nicolaspk, can you leave your opinion on the implementation in https://github.com/algolia/instantsearch.js/pull/2636 ? It seems like an interesting usecase that could be covered by that proposal

**Comment by NicolasPK** [comment]
@Haroenv sounds like what I'm looking for indeed.
I guess a simpler configuration would've been appreciated (in the vein of the current `urlSync`), but I noticed that I'll be able to update the title as well so that sounds exactly like what I need ([by looking at this demo](http://weary-plants.surge.sh/app.js)).
This is the very last thing I need to do to fully replace our current (local) system by algolia's 🎉

**Comment by Haroenv** [comment]
great news! feel free to leave a code snippet or fiddle so we can play around and figure out what broke your implementation too, or open a new issue for that
