### ISSUE TITLE
star-rating cannot work with float values

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#935]
When ratings are in the form of 3.2 3.8 4.1 then the star-rating widget cannot work because it's adding refinements like "rating = 2" or "rating = 3".

I wonder if we could use numeric filters? Maybe not because we want the counts for each rating, is that it?

**Comment by redox** [comment]
Indeed, it's "designed" to run on integers and having the counts on floating point numbers won't be possible. I would rather insist on the "must be integers from 0 to 5" in the documentation.

**Comment by vvo** [comment]
Ok will add that, also its totally ok to still duplicate the rating attribute in precise form and have it configured as a custom ranking attribute so that the ranking is still very precise.
