### ISSUE TITLE
How to dynamically update searchParameters?

### ISSUE THREAD

**Issue by powtac** [algolia/instantsearch.js#938]
I want to update the [SearchParameter](https://community.algolia.com/algoliasearch-helper-js/docs/SearchParameters.html) `restrictSearchableAttributes` according to a user selection in a dropdown next to the search box. 

Updating `search.searchParameters` like `search.restrictSearchableAttributes = 'mynumbers'` does not work.

How can I set searchParameters **after** the initial setup:

```
var search = instantsearch({
    ...
    searchParameters: {
        restrictSearchableAttributes: 'text',
    }
})

$('#x').on('click', function() {
    // How to update "restrictSearchableAttributes" here (and start a new search)?
    // ?

    // This does NOT work:
    search.restrictSearchableAttributes = 'mynumbers';
    search.start();
})
```

**Comment by vvo** [comment]
You would have to build your own [custom widget](https://community.algolia.com/instantsearch.js/documentation/#custom-widgets):

```js
var customWidget = {
  init: function(options) {
    $('x').onClick(function() {
      options.helper.setQueryParameter('restrictSearchableAttributes', ...);
    });
  }
};

search.addWidget(customWidget);
```

Let me know.

**Comment by powtac** [comment]
I simply have to add this as an additional widget? Or do I have to replace and reprogram my searchbox widget?

**Comment by powtac** [comment]
It works, by adding this additional widget! Thanks a lot!

Is there a way to reset a setting? Like to remove `restrictSearchableAttributes` afterwards?  `delete options.helper.restrictSearchableAttribute;` does not work.

**Comment by vvo** [comment]
Can you try options.helper.setQueryParameter('restrictableSearchableAttributes');

Just passing no value should remove it

**Comment by powtac** [comment]
`options.helper.setQueryParameter('restrictableSearchableAttributes')` does not work. The previous value is still set. I tried already null, false, ''. But they all raise an error from the API.

**Comment by vvo** [comment]
Ah I think what I missed in the custom widget, you need to call helper.search() at the end of the line:

```js
 options.helper.setQueryParameter('restrictSearchableAttributes', ...);
 options.helper.search();
```

I just tried this and it worked well:

```js
var algoliasearch = require("algoliasearch"); // algoliasearch is a peer dependency. 
var helper = require("algoliasearch-helper")
var client = algoliasearch('latency', '6be0576ff61c053d5f9a3225e2a90f76');
var helper = helper(client, 'instant_search');
helper.setQueryParameter('restrictSearchableAttributes', ['categories']);
helper.search()
helper.setQueryParameter('restrictSearchableAttributes');
helper.search()
```

The "helper" you are using is this: https://github.com/algolia/algoliasearch-helper-js

**Comment by vvo** [comment]
If it's really not working can you give me a reproducible website where you have the issue, or a github project, or send an email to support@algolia.com with a private url if you need to.

**Comment by powtac** [comment]
`options.helper.search();` did the job! Thanks for your help, @vvo! I'll come back to your offer and contact you via the support forms later this week.
