### ISSUE TITLE
Query parameters depending on which index is selected

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#94]
We need to be able to set some query parameters depending on the selected index. For instance, we're used to disable the typo-tolerance when you select the "sorted by price" index (otherwise you have very approximative results with low price first).

Any idea how to deal with that?

**Comment by redox** [comment]
> For instance, we're used to disable the typo-tolerance when you select the "sorted by price" index

For that specific example, we could also set the setting at indexing time.

**Comment by bobylito** [comment]
Seems hard to make it implementable :) (searching for a solution)

**Comment by pixelastic** [comment]
We planned on having widgets emit event before doing the query, receiving the `helper` as parameter.

You could then plug your custom code to change the settings before the search is send. Would that work?

**Comment by bobylito** [comment]
You can't change the configuration once it's started. But that can be fixed (everything can be fixed).

Even if we consider it's possible with events and change of configuration, it is a lot of code (with respect to the declarative aspect of the rest of the API) that the user has to create to get the proper behavior. We would need a good recipe book.

**Comment by vvo** [comment]
> For that specific example, we could also set the setting at indexing time.

I would go for this for now then.

**Comment by redox** [comment]
> Even if we consider it's possible with events and change of configuration, it is a lot of code (with respect to the declarative aspect of the rest of the API) that the user has to create to get the proper behavior. We would need a good recipe book.

I would not worry too much, it's a pretty rare use-case. But I thought it was good to start chatting about it because we'll need it.

**Comment by redox** [comment]
> I would go for this for now then.

Yes for the sort by price it makes sense.

But here is another use case: I would love to use such widget to create a dropdown-menu filter:

Sort by:

<table>
<tr>
<td>...</td>
<td>v</td>
</tr>
<tr>
<td>
By relevance<br />
Only popular<br />
Only whatever
</tr>
</table>


The "Only popular" would target the same index than "Default", but add a numeric filter `popularity>1000`. I already implemented such thing. It can be another widget however.

**Comment by vvo** [comment]
Could be dealt with events modifying the helper as Tim said. If so it would be another pointer for #83

I do not see an easy way right now to have a declarative API in indexSelector to add something as "complex" as a numeric filter?

**Comment by bobylito** [comment]
We could have a menu that is a partial state object setter. For example 

```js
var myConfigSetterMenu = configSetterMenu({
  config: {
    'By relevance': {index: 'index1'},
    'Only popular': {index: 'index2', numericFilters:{attr1:{'>': [1000]}}}
  }
});
```

Something like that maybe?

**Comment by bobylito** [comment]
Needless to say that it would be great that the parameters are exclusive (especially for filters) to this widget and all the settings are consistent with each options (index and numericFilters for all the settings).

**Comment by redox** [comment]
Yep like that :) I would rather speak about "filtersMenu" than "configSetter" but definitely in that way.

Then, if we accep all query parameters, we'll need to think how to merge regular refinements and such raw `*Filter` query parameter.

**Comment by vvo** [comment]
> numericFilters:{attr1:{'>': [1000]}

The only drawback I see is that we will need to document a lot of the internal helper data format while right now we document the helper.methods().

So someone already using the helper would feel a bit lost I guess.

**Comment by redox** [comment]
```
search.addWidget(
  instantsearch.widgets.filteringMenu({
    container: '#filtering-selector',
    filters: [
      { label: 'By relevance' },
      {
        label: 'Only popular',
        configure: function(helper) {
            helper.addNumericRefinement("popularity", ">", 1000);
        }
      },
    ],
    cssClass: 'form-control'
  })
);
```

**Comment by vvo** [comment]
Also exposing and advocating to use internal helper data structure will make major versions or even  modifying internal data structure while updating the helper.methods impossible because it will be "in the wild"

**Comment by vvo** [comment]
> (we still need to think about how to "revert"):

Could be done either in the other label's configure OR as setup()/teardown() install()/revert() selected/unselected (which start to looks like events)

**Comment by vvo** [comment]
:horse: CLOSING BOT SAYS:
> This is very old and not done, reopen if you have the need and want to fix it
