### ISSUE TITLE
Documentation missing of how to implement debounce in searchbox widget

### ISSUE THREAD

**Issue by powtac** [algolia/instantsearch.js#940]
[The documentation for the searchBox widget](https://community.algolia.com/instantsearch.js/documentation/#searchbox) says:

![unbenannt](https://cloud.githubusercontent.com/assets/36167/13920180/02668938-ef72-11e5-93bb-65a1ddfafbfd.PNG)

But how exactly must it be implemented? Does `queryHook` expect a (debounced) return? If so, what? object, function, bool? 

Calling a [debounce/deferr/throttle](https://code.openhub.net/file?fid=B6-cenRVoJ7qDbRegFtkguIsHY0&cid=uXtUw5YhiiU&s=&fp=305271&mp&projSelected=true#L0) function inside queryHook seems not to work.

```
	queryHook:function(query, search) {
		$.debounce(search(query), 1000);
		return false; // ? 
	}
```

**Comment by vvo** [comment]
You would do something like that:

```js
    queryHook: $.debounce(function(query, search) {
      search(query);
    }, 1000);
```

Thanks for all the feedbacks and issues, much appreciated, really. We have a tutorial section #849 planned that would go deeper into cases like that.

**Comment by powtac** [comment]
This works! Thank you, @vvo !

```
...
queryHook: $.throttle(function(query, search) {
    query = query.replace(/\./, "");
    search(query);
}, 1000),
...
```

**Comment by vvo** [comment]
awesome ;)
