### ISSUE TITLE
React destroys our HTML structure by inserting a lot of divs

### ISSUE THREAD

**Issue by powtac** [algolia/instantsearch.js#941]
Especially on hit lists or refined lists, there are a lot of `<div>`s wrapped around `<li>` and `<a>` elements. This destroys the formatting of Bootstrap that heavily relays also on a somehow semantic HTML structure for several layout elements like lists. For example, Bootstrap uses a `.nav-list > li > a` styling that is fully destroyed by those React divs. 

[I've read in the docs that jQuery is supported for custom widgets](https://github.com/instantsearch/instantsearch-jQuery-widget)... 

It is unclear for me how/or what exactly is different when using jQuery, is it possible to avoid React as "renderer" at all or only for custom widgets?

This is related to http://stackoverflow.com/a/34517968/22470

**Comment by vvo** [comment]
I really thought bootstrap were going to a non structure-dependent API?

> It is unclear for me how/or what exactly is different when using jQuery, is it possible to avoid React as "renderer" at all or only for custom widgets?

Yes, if you want to build custom widgets that are not using React where you control the full html rendering thats completely feasible.

With custom widgets you are free do to anything outside of React.

**Comment by powtac** [comment]
Bootstrap heavily relays on a (good) structure, have a look at form styling for example: https://getbootstrap.com/css/#forms

When there is no solution to avoid React divs around refinementList template items, this ticket can be set to "wontfix". :-/

**Comment by vvo** [comment]
I won't (and did not) set it to wontfix but I have no easy solution for you to make instantsearch.js play nicely with bootstrap right now.

Can you provide a jsfiddle where we can quickly see the issue? (https://jsfiddle.net/).

Basically a webpage with bootstrap, instantsearch.js and some CSS that cannot be applied.

**Comment by powtac** [comment]
Ok! 

(I figured out it also depended on our rather old version of Bootstrap 2.3...) But will try to recreate the issue in JSFiddle.

**Comment by vvo** [comment]
> (I figured out it also depended on our rather old version of Bootstrap 2.3...)

Yes I think bootstrap should be less and less concerned about very precise HTML trees but still sometime may require it, also see all the possible "cssClasses.*" options on every widget because you might find gems that will help you put the right bootstrap class at the right level.

**Comment by pixelastic** [comment]
We tried to be as compatible with Bootstrap 3 as possible while building the app, but we do not have any official support of it. As @vvo suggested, sometimes you can get away with the `cssClasses` options, or defining a 'master' template where you have all control on the markup (but need to do everything yourself). Still, not all our widgets provide this functionality.

A JSFiddle would help fixing your specific problem :)

**Comment by vvo** [comment]
We will provide either or both:
- a `renderer` option where you can control the full markup rendering
- a bootstrap renderer that will only use bootstrap type syntax
