### ISSUE TITLE
Fast assynchron typing into search box not possible

### ISSUE THREAD

**Issue by powtac** [algolia/instantsearch.js#944]
When typing very fast into the search box not all chars are recognized! So when typing "test" only "tst" is recognized and triggered. 

Thought it might be related to #943 but when setting `urlSync: false,` typing is still delayed / syncron and not asynchronous. 

Window 7, Firefox 45, Internet Explorer 11

**Comment by vvo** [comment]
Wow that is be very bad, can you give us the initialization and widget init code you are using so we can reproduce it?

**Comment by vvo** [comment]
A jsfiddle would be awesome

**Comment by powtac** [comment]
I think I found the part that issues the slow down, it is the "templates" part:

```
var table	= Hogan.compile($.trim($('#table-template').text()));
var stats	= Hogan.compile($.trim($('#stats-template').text()));
var hits	= Hogan.compile($.trim($('#hit-template').text()));

search.addWidget(
	instantsearch.widgets.hits({
		container: '#table-container',
		templates: {
			empty: '<table class="table table-bordered table-suchergebnisliste"><tbody id="hits">No Results</tbody></table>',
			// Template MUST be a full <table>, see https://github.com/algolia/instantsearch.js/issues/770#issuecomment-184115613
			allItems:  function(data) {react!
				var stats_html	= stats.render(data);
				var hits_html	= '';
				$.each(data.hits, function(a, b) {
					hits_html += hits.render(b);
				});
				var table_html	= table.render({stats: stats_html, hits: hits_html});
				
				return table_html;
			},
		},
		hitsPerPage: 	15,
		transformData: 	function(data) {
			data.processingTimeS = data.processingTimeMS / 100;
			return data;
		}
  })
);
```

When I disable the whole `template:` part, typing into the search box works as expected, it is rapid fast. It seems that the HTML generation is synchronous.

**Comment by vvo** [comment]
Just to be clear, with this setup, you were able to have an example where when you typed "test", the rendering was actually "tst"?

Having a working example would help me a lot, thanks for the code example though. Do you think I could access your development website? (You can send it to support@algolia.com).

**Comment by powtac** [comment]
Email sent...

**Comment by vvo** [comment]
1.4.1 will be available on jsdelivr in ~30 minutes

**Comment by powtac** [comment]
Ok, much better now. But there is still a flickering at the moment when the hash URL is updated the cursor jumps forward and backwards and it seems that chars are lost at that moment. Not sure since I type "w"'s all the time.

**Comment by vvo** [comment]
> So I restarted Firefox with all add-ons deactivated and no more flickering! It might be that on URL refresh a antivir or addblock plugin/add-ons checks this "new" URL and leads to delay?!

Yes indeed if you have a lot of plugins it might be linked to them.

**Comment by vvo** [comment]
@powtac If you still have an issue linked to useHash: true please open a new issue, we might still have a bug here
