### ISSUE TITLE
Given a query, after refresh, searchBox cursor jumps at the begining of the input

### ISSUE THREAD

**Issue by powtac** [algolia/instantsearch.js#946]
When having `autofocus: true` in the searchBox widget and `urlSync` activated in the instantsearch, the search box is populated with the previous search query after a reload happens and the cursor is placed (with focus()?) into the search box input field.

![unbenannt](https://cloud.githubusercontent.com/assets/36167/13947604/cc067efc-f01b-11e5-94b6-d9e12075d880.PNG)

In this case I would **expect that the cursor is placed at the end** of the query and not at the beginning.

**Comment by vvo** [comment]
Yes indeed this looks like a bug, can you give me:
- browser
- browser version
- system

Thanks

**Comment by powtac** [comment]
* Firefox 45.0.1
* Windows 7

**Comment by vvo** [comment]
I am not able to reproduce this on a simple example so it might be one of your scripts conflicting with our input. I would recommend you to double check everywhere you may be  or a script may be doing an autofocus the wrong way.

**Comment by powtac** [comment]
Sure! Could be the case, I will investigate soon. 

----
BTW Firebug for Firefox has an "Events" section at the right, beside "Styles, Layout, DOM", when you have selected a element in the HTML view. 

![events](https://cloud.githubusercontent.com/assets/36167/13957883/55a8758e-f04e-11e5-96b1-02d8ad40f4e3.PNG)

This should give the answer...

**Comment by vvo** [comment]
> BTW Firebug for Firefox has an "Events" section at the right, beside "Styles, Layout, DOM", when you have selected a element in the HTML view.

Yes I guess you will be able to find the bad event maybe from here, otherwise just remove some of the JS scripts from your page and see when it stops doing bad things

**Comment by vvo** [comment]
Just reproduced this on the current develop branch:
- search for smg
- refresh

Cursor is at the begining.

Most probably because we fill the query field AFTER autofocus has triggered.
