### ISSUE TITLE
Pagination widget - access to the data?

### ISSUE THREAD

**Issue by powtac** [algolia/instantsearch.js#947]
Is it possible to get a pagination widget output with dotted and very last/very first entry on large numbers of pages, like this?

![unbenannt](https://cloud.githubusercontent.com/assets/36167/13947771/a431e49c-f01c-11e5-8dd4-0d1abfb695aa.PNG)

I can imagine to have something similar like `transformData` to manipulate the array of pages to show in the pagination widget output.

**Comment by vvo** [comment]
This is not currently doable, cc @olance I think you may have planned at some point to contribute to provide an option to do so.
