### ISSUE TITLE
Adding tranformData breaks the emptytemplate

### ISSUE THREAD

**Issue by collegeminer** [algolia/instantsearch.js#952]
Adding a transformData to the widget breaks the noResultsTemplate. If I have no data it does not pull up the empty template. 

`search.addWidget(
  instantsearch.widgets.hits({
      container: '#hits',
      hitsPerPage: 10,
      templates: {
 item: newTemplate2Panel,
          empty: noResultsTemplate
      },
      transformData: function (hit) {
          hit.skills = [];
          try
          {
              for (var i = 0; i < hit.Skills.length; i++) {
                  hit.skills.push(hit.Skills[i].SkillName)
              }
              hit.RunDate = jQuery.timeago(hit.RunDate);
  return hit;
          }
          catch(err) { 
          } }}));`

**Comment by vvo** [comment]
Yes, you need to use this:

```js
instantsearch.widgets.hits({
  transformData: {
    item: function() {},
    empty: function() {}
  }
});
```

Let me know if this fixes the issue

**Comment by pixelastic** [comment]
As pointed, `transformData` should be an object with `item` and `empty` keys. In previous versions of instantsearch, we allowed passing a function directly, as a shortcut for `transformData.item` but this will be deprecated.

Maybe we have an example/tutorial/documentation somewhere with the old behavior. If that's the case, please give us the url so we can fix this :)

**Comment by vvo** [comment]
I had one here: http://stackoverflow.com/questions/35437004/algolia-initial-search-parameters-instantsearch-js/35440096#35440096

Now fixed
