### ISSUE TITLE
Callback for returned hits

### ISSUE THREAD

**Issue by jamesfzhang** [algolia/instantsearch.js#953]
Hello! Loving Algolia for search so far! Is there a way to access the hits from the search query? On our [search page](https://theartistunion.com/search), we want users to be able to play through searched music and then autoplay to the next song when the first one finishes. As a result, we need to be able to store the hits returned from the search query.

I'm thinking the API would look something like this

```js
search.addWidget(
  instantsearch.widgets.searchBox({
    container: '#search-box',
    placeholder: 'Search by title or artist',
    autofocus: true,
    onHit: (query, hits) => {
      this.setState({ hits: hits });
    }
  })
);
```

Does this exist? If not, how would I implement this? Thanks!

**Comment by vvo** [comment]
You can use `transformData.item` option (https://community.algolia.com/instantsearch.js/documentation/#hits "all options"), it will be called for every hit, with the hit content.

Let me know if that works for you.

**Comment by jamesfzhang** [comment]
Hi Vincent, thanks for your suggestion. I ended up using `transformData.allItems`. Thank you!

**Comment by anantakrishna** [comment]
For anyone landing here while searching… There is another way — custom widgets. Inspired by https://stackoverflow.com/a/42674116/3082178.

In InstantSearch v4 it looks like this:

```js
search.addWidgets([
  {
    $$type: 'Playlist manager',
    render: ({ results }) => {
      console.log(results);
    },
  },
]);
```

P.S.
@jamesfzhang I have faced the same use case, ability to autoplay the next song when the first one finishes in the search results.
