### ISSUE TITLE
Setting custom/non search parameters url attributes while refining the search

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#960]
I have a use case where I want to:

```js
search.addWidget({
  container: document.querySelector('#custom-widget'),
  render: function(options) {
    var link = document.createElement('a');
    link.innerText = 'test';
    link.addEventListener('click', function(e) {
      e.preventDefault();
      history.pushState(null, '', location.search + '&isCustom=true&test_custom=false');
      options.helper.toggleRefine('brand', 'Samsung');
      options.helper.search();
    });
    this.container.innerHTML = '';
    this.container.appendChild(link);
  }
});
```

So basically, it's a simple link, that when clicked, will refine the search while setting url custom attributes.

It works when clicking but if I click on back button then `&isCustom=true&test_custom=false` will still be in the url while they should not be here. I believe it's not really a bug, just the way things are working right now.

Do we need a higher level API to be able to update the current url state or am I missing something?

@bobylito Could you help me on this?

**Comment by bobylito** [comment]
It looks like bug to me. The URL is stored in the browser history. If at a previous step we didn't have the custom parameters, well they should not stay while using back. Do you have the same behavior across browsers? Maybe this could a good use case for a selenium test case :)

**Comment by vvo** [comment]
Ok it's only a matter of how do we update the url:

```js
search.addWidget({
  container: document.querySelector('#custom-widget'),
  render: function(options) {
    var link = document.createElement('a');
    link.innerText = 'test';
    link.addEventListener('click', function(e) {
      e.preventDefault();
      options.helper.toggleRefine('brand', 'Samsung');
      history.replaceState(null, '', location.search + '&isCustom=true&test_custom=false');
      options.helper.search();
    });
    this.container.innerHTML = '';
    this.container.appendChild(link);
  }
});
```

So basically, for anyone wondering, you need to do this to be able to add custom url attributes in the right way:

```js
      options.helper.toggleRefine('brand', 'Samsung');
      history.replaceState(null, '', location.search + '&isCustom=true&test_custom=false');
      options.helper.search();
```

In this particular order, using replaceState. Thanks @bobylito
