### ISSUE TITLE
Is there any way to add user specific info to result of algolia?

### ISSUE THREAD

**Issue by fab10m** [algolia/instantsearch.js#961]
Hi,

I need to append some info related to authenticated user to the result returned by algolia algoliasearchHelper. I tried to make a ajax request inside helper.on method

```
helper.on('result', function(data) {
        renderHits(data);
        myfunction(data);
});
```
but I always get this error: "Uncaught TypeError: Illegal invocation".
Do you have any kind of suggestion?

Regards

**Comment by vvo** [comment]
Hi, did you figure out how to do it @fab10m?

**Comment by fab10m** [comment]
Hi Vincent, I closed the issue because I realized that the error was caused by my trivial mistake :-)
I did big steps forward, but I still have some doubts about which is the best approach:

1. append to the objects contained in data variable, the extra attribute retrieved throgh tha ajax request; then execute the function renderHits that compile the template with hogan.js.
2. render the page executing the function renderHits and then execute my function to modify the html

Do you have any kind of suggestion?

Regards

**Comment by vvo** [comment]
Is the data you want to add to hits related to the results you got from Algolia? Or can you get this data independently?

**Comment by fab10m** [comment]
The data is only related to the objectID. Pratically, I need to add the info that tells whether a user is following or not an object.

**Comment by vvo** [comment]
There's a formatData function on the hits widget that let's you rework the hits.

Unfortunately it is not yet asynchronous compatible, we could add that maybe by just supporting returning promises.

In the meantime what I would do is just put some `<div class="more-data" data-object-id="$OBJECTID"></div>` in your hit template.

Then fill it after each search, like this:

```js
search.on('render', function() {
  var more = document.querySelectorAll('.more-data');
  // loop through all the more data elements, find the object id, do the requests, fill in the html
});
```

What do you think?

**Comment by fab10m** [comment]
I did something similar to what you suggest, but definitely less elegant :-) 
I retrieved the objectID in this way 
```
var services_id = $.map(data.hits, function(o){
                return o.objectID;
 }).join();

```
While we are in chat, could tell me how can I update an attribute of the algolia's indexed object?

**Comment by vvo** [comment]
Can you open another issue with a more descriptive content? It's a lot easier to deal with and for people to refer to in the future, thanks!
