### ISSUE TITLE
Continue to show a selected refinement when it's over maxValuesPerFacet

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#962]
This issue is  directly linked to http://stackoverflow.com/questions/36319673/algolia-instantsearch-refinementlist-item-toogle-when-search-for-something-else .
The user want to be able to keep track of already selected refinements in his refinement list, even when its count would imply it's not sent back as a facet value in the response.

Here the refinement is selected:
![selected](http://i.stack.imgur.com/uUbhu.png)

But if your change the query, it disappears:
![selected but gone](http://i.stack.imgur.com/6SfZ4.png)

As I've said in the answer, this is partly solved by _currentRefinedValues_. Do we want to also expose an option on faceting widgets?

**Comment by vvo** [comment]
Hi sorry @Jerskouille I ignored not on purpose this issue. Yes this is a good idea because this would allow people to unselect facet values from the same list they selected them when the facet values are no more relevant.

This need an API proposal

**Comment by bobylito** [comment]
Reviving this issue as we are going through all the issues. We already had this issue in the helper, and it now provides all the facets even if they are returned in the list of facets but they are selected. The only problem is that by default in instantsearch.js the sort (of the refinement list) does not use isRefined as the first sort argument. Therefore even if it is refined and present in the list of facets, it is not considered relevant.

Here is an example that fixes the issue for the `materials` facet on the amazing/ecommerce sample:
```js
search.addWidget(
  instantsearch.widgets.refinementList({
    container: '#materials',
    attributeName: 'materials',
    operator: 'or',
    limit: 10,
    sortBy: ['isRefined', 'count:desc', 'name:asc'],
    templates: {
      item: facetTemplateCheckbox,
      header: '<div class="facet-title">Materials</div class="facet-title">'
    }
  })
);
```

Note the new sort that I used: `sortBy: ['isRefined', 'count:desc', 'name:asc']` It is clearly not obvious in the documentation and be a recipe.

I did a small screencast to show you what is my understanding of the correct behavior. Let me know @Jerskouille @vvo 

![facets-hidden](https://cloud.githubusercontent.com/assets/393765/15925519/c4cae22c-2e37-11e6-9d22-5627653269f4.gif)

**Comment by vvo** [comment]
Seems right but I still have trouble understanding how it really work :D

**Comment by bobylito** [comment]
The default sort has changed in v2.

**Comment by bobylito** [comment]
Now that in v2, the default behaviour will keep the refined facet values on top, I don't think we need a guide. WDYT @vvo ?

**Comment by Jerskouille** [comment]
Can you still override it to achieve a Amazon-like star widget?
![image](https://user-images.githubusercontent.com/5095856/27032920-48e5e078-4f77-11e7-96b7-322f3c50a134.png)

**Comment by vvo** [comment]
> Now that in v2, the default behaviour will keep the refined facet values on top

> The user want to be able to keep track of already selected refinements in his refinement list, even when its count would imply it's not sent back as a facet value in the response.

I am unsure this we are talking about the same issue here. ?

**Comment by Jerskouille** [comment]
I guess if they're always on top, this solves my issue of the facet disappearing when it goes after the list.
The only case I can think of where you wouldn't want the refined first will be cases where the amount of facets are fixed.

**Comment by bobylito** [comment]
> I am unsure this we are talking about the same issue here. ?

Yes the values are consolidated in the helper. The problem is displaying those values, when there is a soft limit on the number of facet displayed. We might retrieve 20 (show more), only display 10 (limit 10) and have 3 that are selected but have a 0 count.

I'm not sure I get the star widget problem. Can you give an example @Jerskouille ?

**Comment by Jerskouille** [comment]
The screenshot I gave in my first post. An amazon like widget, when you click 3-stars, you don't want it above every other option, you want it right between 2 and 4 stars. Hence my first question: are we still able to override the sorting strategy ? :)

**Comment by bobylito** [comment]
There is no sorting strategy applied on stars https://community.algolia.com/instantsearch.js/v2/examples/media/?q=tomato&idx=movies&p=0&is_v=2
