### ISSUE TITLE
Make future formatting hooks asynchronous compliant

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#963]
Could be nice to be able to:

```js
function formatData(data) {
  return new Promise(resolve){
    resolve(modifiedData)
  }
}
```

or

```js
function formatData(data, cb) {
  cb(data);
}
```

Linked with https://github.com/algolia/instantsearch.js/issues/961#issuecomment-203604054

**Comment by bobylito** [comment]
Where would this fit in the rendering flow of instant search? Would it postpone the rendering?

**Comment by bobylito** [comment]
The use case is not clear. Let's get back to it someday, closing for now (automatic bot 🐴 👯  )
