### ISSUE TITLE
[Docs] When I search for an option, I want the "All options" tab to be displayed

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#966]
Otherwise, we don't understand the result:

![gif](http://g.recordit.co/vH5y4Hclng.gif)

**Comment by redox** [comment]
I'm actually wondering is the "All options" shouldn't be the default opened tab + rename "Snippet" to "Example" as the second tab.

What do you think @algolia/javascript @Shipow ?

**Comment by vvo** [comment]
Works for me

**Comment by proudlygeek** [comment]
Makes sense :+1:
