### ISSUE TITLE
Prototype.js

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#97]
It seems there is a conflict with prototype.js.

This method line ```return new (_bind.apply(Class, [null].concat(args)))();```  fails because it is using the bind method of prototype

**Comment by vvo** [comment]
Can you point a link where we can reproduce this? I am doing a release right now

**Comment by maxiloc** [comment]
I will try to reproduce it outside of magento tomorow

**Comment by vvo** [comment]
If you can push your magento branch I can test

**Comment by redox** [comment]
So Prototype.js (< 1.7.2) actually replaces the `bind` method in every cases: https://github.com/sstephenson/prototype/commit/9559d8892d9edb8bdf53391c11dfa32bdaf6bf39

**Comment by vvo** [comment]
For reference, prototype.js 1. overwrite .bind in < 1.7.2. 2. does a bad job with the polyfill (not forwarding .prototype etc).

You can just inline this:

```js
// Magento is using a very old prototype.js version with a poor Function.prototype.bind
// forced overloading, we redefine it here so that our code works
// ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
Function.prototype.bind = function(oThis) {
  if (typeof this !== 'function') {
    // closest thing possible to the ECMAScript 5
    // internal IsCallable function
    throw new TypeError('Function.prototype.bind - what is trying to be bound is not callable');
  }

  var aArgs   = Array.prototype.slice.call(arguments, 1),
      fToBind = this,
      fNOP    = function() {},
      fBound  = function() {
        return fToBind.apply(this instanceof fNOP
               ? this
               : oThis,
               aArgs.concat(Array.prototype.slice.call(arguments)));
      };

  if (this.prototype) {
    // native functions don't have a prototype
    fNOP.prototype = this.prototype;
  }
  fBound.prototype = new fNOP();

  return fBound;
};
```

Before inserting instantsearch.js
