### ISSUE TITLE
Filter results with custom widget?

### ISSUE THREAD

**Issue by ZayLong** [algolia/instantsearch.js#971]
Not a bug just a question,

I'm trying to figure out a way i can pro-grammatically filter products in the hits component. is this possible using instantsearch.js ?

**Comment by vvo** [comment]
Yes you can use options.transformData.item like this:

```js
var hits = instantsearch.widgets.hits({
  transformData: {
    item: function(hit) {
      // change hit then
      // hit.show = true/false
      // return hit
    }
  }
});
```

Then in your template, just conditionally display the hit based on `show` value: http://stackoverflow.com/questions/6027525/how-do-i-accomplish-an-if-else-in-mustache-js

**Comment by ZayLong** [comment]
I tried this solution with the custom widget, and it worked out, 

but root categories become unsearchable in the instantsearch hierarchialMenu widget whenever toggleRefinement is called

is there a proper way to clear active filters so I can preserve hierarchalMenu?

Thanks

**Comment by ZayLong** [comment]
I think this is because the custom widget I made to filter items is still active even though i added another widget to clear all filters.

Is there a way to actually delete widgets?

**Comment by vvo** [comment]
Can you submit a jsfiddle where we can see what you are trying to do? All coding issues are easier to solve when live. Thanks

**Comment by ZayLong** [comment]
Sure, here is the code sample I'm working with.

up top are two buttons, one to apply a custom widget filter, and another to remove it.

The hierarchical categories are removed when this custom filter is applied.

Even when i clear the filters, they don't return 

[https://jsfiddle.net/w28pmeg0/5/](url)

**Comment by bobylito** [comment]
Hi @ZayLong, I think I fixed your jsFiddle, let me know if this was the behavior you were looking for.
https://jsfiddle.net/Ly2s2971/

**Comment by ZayLong** [comment]
These are both exactly the same.

Maybe your changes didn't save?

**Comment by vvo** [comment]
This issue is very old, I hope @ZayLong you managed to solve it somehow, if not please open a new one (you will see there's a new issue template for you to easily create an example jsfiddle)
