### ISSUE TITLE
hierarchicalMenu sorting problem

### ISSUE THREAD

**Issue by tecmusti** [algolia/instantsearch.js#973]
How can I define a sortBy option for each level in hierarchicalMenu widget?

**Comment by vvo** [comment]
This is not currently doable.

Can you provide me more information on your usecase/data? Thanks.

**Comment by tecmusti** [comment]
Thanks for your reply @vvo,
I want to use it to sort product categories, for example
Clothing
  Clothing > Dresses
    Clothing > Mini Dresses
    Clothing > Midi Dresses
  Clothing > Tops
  Clothing > Bottoms
  Clothing > Outwears
Accessories
  Accessories > Jewelery
  Accessories > Bags
...

I need to sort items by levels name:desc - count:desc -  or custom sort function for each level.

**Comment by vvo** [comment]
So you want first level to be count based and second level to be name based?

**Comment by tecmusti** [comment]
Exactly I want something like this @vvo 
```javascript
search.addWidget(
  instantsearch.widgets.hierarchicalMenu({
    container: '#categories',
    attributes: [ 'category','sub_category','sub_sub_category'],
    sortBy: [custom,'name:asc','count:desc']
  })
);
```
And I achieved this by writing the code below, maybe it can help someone else.
##### Example Category Tree
* Clothing
  * Clothing > Dresses
    * Clothing > Dresses > Mini Dresses
    * Clothing > Dresses > Midi Dresses
  * Clothing > Tops
  * Clothing > Bottoms
  * Clothing > Outwears
* Accessories
  * Accessories > Jewelery
  * Accessories > Bags

##### Javascript
```javascript
search.addWidget(
  instantsearch.widgets.hierarchicalMenu({
    container: '#categories',
    attributes: [ 'category','sub_category','sub_sub_category'],
    sortBy: customSort
  })
);
var categories = ["Clothing", "Clothing > Dresses", "Clothing > Dresses > Mini Dresses", "Clothing > Dresses > Midi Dresses",...];
function customSort(a,b){
	if(a.path.split(">").length==1){ //category
		return categories.indexOf(a.path) - categories.indexOf(b.path);
	}else if(a.path.split(">").length==2){ //sub_category
		return a.name > b.name;
	}else{
		 //sub_sub_category
		return a.count < b.count;
	}
}
```

**Comment by vvo** [comment]
Awesome! Very nice. I knew the custom sort with a function could help someone at some point ;)

**Comment by vvo** [comment]
Thanks a lot for giving us feedback
