### ISSUE TITLE
[Question] Infinite Scroll Support

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#977]
Hey!

Pagination widgets looks awesome. I'm interested in add infinite scroll in my project. Altought pagination widget support many options, I don't see nothing related with infinite scroll.

Do you think that could be possible add this feature and have sense be resolved from the library instead of use a external dependency?

**Comment by hkdobrev** [comment]
Duplicate of #936, previous discussion in #328.

**Comment by Kikobeats** [comment]
Oh dammit! I used the search before create the issue. Maybe the title is clever :P
