### ISSUE TITLE
demo should be easy to read

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#98]
use the standard build and standard js file instead of a full webpack example.

**Comment by vvo** [comment]
@redox Not sure how to deal with it.

Currently the templates are well separated in example/templates/*.html. If I start rewriting the demo "old school" then I will need to put the templates either in the js files or in the main html file. It would be a pain for us then to update it.

If the goal is for the user to understand the underlying code, we can definitely link from the demo page to the github example/ folder where it will be easier to them to understand.

**Comment by redox** [comment]
I would rather do something like:

```html
<script src="//cdn,jsdelivr.com/............/latest/instantsearch.js"></script>
<!-- or -->
<script src="../dist/instantsearch.js"></script>

<script>
$(function() {
  var search = instantsearch(....);

  search.addWidget(
    instantsearch.widgets.searchBox({
      container: '#q-container',
      cssClass: 'form-control input-lg'
    })
  );

 // [...]  

  search.start();
});
</script>
```

**Comment by vvo** [comment]
> I would rather do something like:

Yes that's what I wanted to do, but then, where do we store the templates?

I do not want to again include templates in `<script>` inside the main html file etc.. and showing it to our users. This is a bad practice we give to our users in the end. It cripples the html file and prevent the templates to be cached (and the js to be cached).

I'd rather prefer them to discover the underlying simple webpack config file and great things like require('template.html').

From a documentation point of view we will do the straightforward things: no webpack advice etc.. But still, as for our own code, the fact that we do use webpack should not be an issue for them.

If they want to see the code and templates I will link to the github project.

Even inlining everything will have it's own limit, we would end up with a very big html file. If the user is smart enough to "view source" then it will be no problem for him to come to github I am sure.

What do you think?

**Comment by redox** [comment]
> I do not want to again include templates in <script> inside the main html file etc.. and showing it to our users. This is a bad practice we give to our users in the end. It cripples the html file and prevent the templates to be cached (and the js to be cached).

I get your point but that's what we're gonna do in most integrations.

> But still, as for our own code, the fact that we do use webpack should not be an issue for them.

Sure fair enough, but let's just make it readable by including the dist file + another non-minified include with the templates and the widgets setup; most users don't want to understand the github repository/build system when looking at a demo.

```html
<script src="//cdn,jsdelivr.com/............/latest/instantsearch.js"></script>
<!-- or -->
<script src="../dist/instantsearch.js"></script>

<script src="app.js"></script>
```

```js
  var hitTemplate = '......'; /* require("hit.html") */

  var search = instantsearch(....);

  search.addWidget(
    instantsearch.widgets.searchBox({
      container: '#q-container',
      cssClass: 'form-control input-lg'
    })
  );

 // [...]  

  search.start();
```

**Comment by vvo** [comment]
You want to keep track of the issue thats it? Wfm

**Comment by redox** [comment]
Wrong waffle manipulation actually :)
