### ISSUE TITLE
Urls should be safe by default

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#982]
Following https://github.com/algolia/instantsearch.js/issues/848#issuecomment-191795411 and a support request we had also recently, I believe we should fix our urls.

We will get more and more issues about unsafe urls in the future.

## Problem :trollface: 

we implemented urls so that they do not look too bad:
`?query=&hits=24&idx=instant_search&p=0&nR[price][<=][0]=320&is_v=1`

But this is not really standard because most parameters should be encoded so that our urls are compatible with every use case (copy pasting from/to email/app/slack, server side parsing, library parsing..)

Thus it would mean having urls like:

`?query=&hits=24&idx=instant_search&p=0&nR%5Bprice%5D%5B%3C%3D%5D%5B0%5D=380&is_v=1`

Not so clean and readable but would work everywhere.

## Possible solutions :horse: 

- allow the helper to always encode. It's currently [disabled](https://github.com/algolia/algoliasearch-helper-js/blob/4357cf95d7efb0c1d017a0c897093289bf31c266/src/url.js#L157) and [we specifically asked](https://github.com/ljharb/qs/issues/116) for this feature in the `qs` project (lol)

This even seem to be backward compatible. It would be a WTF moment for developers but safety first!

- create a brand new stringifier for complex objects => url which would not be based on unsafe characters like [ ] > =

Here we should be careful about URL versions if we want to stay backward compatible (is_v= will help)

- use https://github.com/vjeux/URLON

Help and feedback appreciated.

**Comment by bobylito** [comment]
Maybe we tried to be generic and infer stuff that we shouldn't have in the first place. What about, we force the users to alias everything that can be?

**Comment by vvo** [comment]
> Maybe we tried to be generic and infer stuff that we shouldn't have in the first place. What about, we force the users to alias everything that can be?

I do not get how this would solve the issue?

**Comment by vvo** [comment]
First part of providing a safe: true option is done in the helper, cc @olance this is coming this week

**Comment by bobylito** [comment]
> I do not get how this would solve the issue?

Let me explain further. Right now, we have a generic solution that completly maps whatever could be in the SearchParameters. Our problem comes from the fact we serialize deep structures automatically. This leads to : `fR[format][0]=Wild` in which we have `[` and `]`. What about we let the user make it's own mapping, `format=Wild,Standard` for a the list of selected facets for the attribute `format`?

I don't have an idea for an API. :) 

In the mean time, the PR look nice :)

**Comment by vvo** [comment]
Yes this could be an interesting way to solve this. we would need to discuss it further, for now the safe option is more of a bug fix introduced as an option to avoid breaking current versions.

But I like your proposition, I will open a new discussion about it

**Comment by olance** [comment]
Yup @bobylito this would actually solve two problems in one, with people who want to completely change the URL params names used by the helper! :)

**Comment by xPaw** [comment]
Is there any reason to encode `[` and `]` in URLs? As far as I know, that's how HTML5 forms that have arrays are sent and they are not encoded. Like `name[0]=Actor1&name[1]=Actor2`. I think not encoding these 2 characters will provide a more readable URL and keep the compatibility.

**Comment by Haroenv** [comment]
@xPaw, because it's not safe in all use cases, it's described in the linked issue: https://github.com/algolia/instantsearch.js/issues/848#issuecomment-191795411

**Comment by xPaw** [comment]
@Haroenv I think that particular issue was not encoding `>=`, and not `[ ]`.

**Comment by vvo** [comment]
We had to encode [] also because when copy pasting links those need to be encoded.

You can check which ones needs to be encoded in a URL by doing:

```
> encodeURIComponent('[]')
"%5B%5D"
```

For example copy pasting those links in slack or in emails resulted in failures given the email client or the slack client.

Happy to revisit/rediscuss this if some testing prove this is not necessary. (maybe open another issue if so)

**Comment by vvo** [comment]
Also this post has some good details: https://stackoverflow.com/a/1016737/147079
