### ISSUE TITLE
RefinementList, hide the facet block when only 1 result

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#986]
Following this magento issue https://github.com/algolia/algoliasearch-magento/issues/318
I did not find a way to do this.

And I think it could make sense to add an option.

**Comment by vvo** [comment]
For now you could always do it very hacky way by showing/hiding facet blocks by looking at the number of facet values you get in a render() call of a specific widget (or just by subscribing to the helper.on('results') event.

As for providing an option to do it directly in instantsearch.js => everything is doable but needs an API entry that is making sense and easy to name. Go for it :)

**Comment by vvo** [comment]
autoHideContainer currently only hides refinementList if there's no facet values in the set. Whereas here it seems like this is a bug, because if there's only one facet value, there's no need to display the choice.

**Comment by vvo** [comment]
This is either solved by creating a guide on "How to conditionnaly display widgets" or we could also allow users to provide a custom function to the autoHideContainer option where they can return true/false given the dataset.

```js
autoHideContainer: function(facetValues) {
  if (facetValues.length === 1) return false;
  return true;
}
```

**Comment by bobylito** [comment]
Well this widget is both for filtering and displaying a summary of the answers. So my call is to say that it depends on the implementor's desire and the UX he/she is looking for and therefore not a bug.

**Comment by vvo** [comment]
moved to #1086
