### ISSUE TITLE
instantsearch.widgets.searchBox does not apply custom cssClasses to search input

### ISSUE THREAD

**Issue by cmalpeli** [algolia/instantsearch.js#989]
Implementation:

```
search.addWidget(
    instantsearch.widgets.searchBox({
      container: '#search-box',
      placeholder: 'Search profiles...',
      wrapInput: true,
      cssClasses: {
         input: 'form-control search-input'
      }
    })
  );
```

Chrome (Mac) Output:
```<input autocapitalize="off" autocomplete="off" autocorrect="off" placeholder="Search profiles..." role="textbox" spellcheck="false" type="text" value="" class="ais-search-box--input form-control search-input">```

IE 11 Windows 10 PC Output:
```<input class="ais-search-box--input" role="textbox" spellcheck="false" type="text" placeholder="Search profiles..." value="" autocapitalize="off" autocomplete="off" autocorrect="off">```

You can see this in action on pythonjobs.com/profiles

Thanks!

**Comment by cmalpeli** [comment]
Note the missing classes on the IE `<input>`

**Comment by vvo** [comment]
Thanks for reporting this, gonna have a quick look
