### ISSUE TITLE
Requiring instantsearch.js leads to lodash error

### ISSUE THREAD

**Issue by jamesfzhang** [algolia/instantsearch.js#996]
Calling `var instantsearch = require('instantsearch.js');` causes `Uncaught TypeError: Cannot read property '0' of undefined(…)` on this line in lodash.

```js
var keys = require('lodash/object/keys');
```

Seems like a dependency problem. This started happening after I updated my project to `react@15.0.1` and `instantsearch.js@1.4.5`. I verified that lodash is properly installed in node_modules.

**Comment by vvo** [comment]
Can you create an example repository so that we can esily debug this issue? Thanks a lot

**Comment by jamesfzhang** [comment]
I ended up deleting the project and reinstalling all packages, which fixed the problem.

**Comment by vvo** [comment]
Good! Thanks for feedback. Happy coding
